Otawa: otawa::dcache::BlockAccess Class Reference
otawa::dcache::BlockAccess Class Reference
Data Cache
A block access represents a data memory access of an instruction.
#include <otawa/dcache/features.h>
Public Types
enum action_t { NONE = 0, LOAD = 1, STORE = 2, PURGE = 3 }
enum kind_t { ANY = 0, BLOCK = 1, RANGE = 2 }
typedef enum otawa::dcache::BlockAccess::action_t action_t
typedef enum otawa::dcache::BlockAccess::kind_t kind_t
Public Member Functions
BlockAccess (void)
Build a null block access.
BlockAccess (Inst *instruction, action_t action)
Build a block access of type ANY.
BlockAccess (Inst *instruction, action_t action, const Block &block)
BlockAccess (Inst *instruction, action_t action, Address::offset_t first, Address::offset_t last)
Build a block access of type range.
BlockAccess (const BlockAccess &acc)
Construction by cloning.
BlockAccess & operator= (const BlockAccess &acc)
Inst * instruction (void) const
Get the instruction performing the access.
kind_t kind (void) const
Get the kind of the access.
bool isAny (void) const
action_t action (void) const
Get the performed action.
const Block & block (void) const
Only for kind BLOCK, get the accessed block.
int first (void) const
int last (void) const
bool inRange (int block) const
Test if the given block is the range of the given access.
bool inSet (int set, const hard::Cache *cache) const
Test if the given set concerns the range access.
bool in (const Block &block) const
Test if the given block may be concerned by the current access.
void print (io::Output &out) const
Property * getProp (const AbstractIdentifier *id) const
Find a property by its identifier.
void setProp (Property *prop)
Set the property in the property list removing any double.
void setProp (const AbstractIdentifier *id)
void removeProp (const AbstractIdentifier *id)
Remove a property matching the given identifier.
void removeProp (const AbstractIdentifier &id)
Property * extractProp (const AbstractIdentifier *id)
Remove a property matching the given identifier and return it.
Property * extractProp (const AbstractIdentifier &id)
Remove a property matching the given identifier and return it.
void addProp (Property *prop)
Add property to the list without checking of duplication.
void removeAllProp (const AbstractIdentifier *id)
Remove all the properties matching the given identifier.
bool hasProp (const AbstractIdentifier &id) const
Test if the property list contains a property matching the given identifier.
void clearProps (void)
Remove all properties from the list.
void addProps (const PropList &props)
Add all properties from the given property list, in a reverse order.
void print (elm::io::Output &out) const
Display the current property list.
Static Public Attributes
static const PropList EMPTY
This is an empty proplist for convenience.
Private Attributes
Inst * inst
t::uint8 _kind
t::uint8 _action
union {
const Block * blk
struct {
hard::Cache::block_t first
hard::Cache::block_t last
} range
} data
Detailed Description
A block access represents a data memory access of an instruction.
The action is defined by BlockAccess::action_t that may be:
NONE – invalid action (only for convenience),
READ – read of cache,
WRITE – write of cache,
PURGE – target block are purged (possibly written back to memory).
Possible kinds of data accesses include:
ANY Most imprecised access: one memory accessed is performed but the address is unknown.
BLOCK A single block is accessed (given by block() method).
RANGE A range of block may be accessed (between first() and last() methods addresses).
Member Typedef Documentation
typedef enum otawa::dcache::BlockAccess::action_t otawa::dcache::BlockAccess::action_t
typedef enum otawa::dcache::BlockAccess::kind_t otawa::dcache::BlockAccess::kind_t
Member Enumeration Documentation
enum otawa::dcache::BlockAccess::action_t
Enumerator
NONE
LOAD
STORE
PURGE
enum otawa::dcache::BlockAccess::kind_t
Enumerator
ANY
BLOCK
RANGE
Constructor & Destructor Documentation
otawa::dcache::BlockAccess::BlockAccess (void) inline
Build a null block access.
otawa::dcache::BlockAccess::BlockAccess (Inst * instruction, action_t action) inline
Build a block access of type ANY.
Parameters
instruction Instruction performing the access.
action Type of action.
otawa::dcache::BlockAccess::BlockAccess (Inst * instruction, action_t action, const Block & block) inline
otawa::dcache::BlockAccess::BlockAccess (Inst * instruction, action_t action, Address::offset_t first, Address::offset_t last) inline
Build a block access of type range.
Notice the address of first block may be greater than the address of the second block, meaning that the accessed addresses ranges across the address modulo by 0.
Parameters
instruction Instruction performing the access.
action Type of action.
first First accessed block (must a cache block boundary address).
last Last access block (must a cache block boundary address).
otawa::dcache::BlockAccess::BlockAccess (const BlockAccess & acc) inline
Construction by cloning.
Parameters
acc Cloned access.
References data.
Member Function Documentation
action_t otawa::dcache::BlockAccess::action (void) const inline
Get the performed action.
Returns
Performed action.
Referenced by otawa::etime::StandardEventBuilder::processBB(), otawa::dcache::MUSTProblem::purge(), otawa::dcache::PERSProblem::purge(), otawa::dcache::MUSTPERS::update(), otawa::dcache::MUSTProblem::update(), and otawa::dcache::DirtyManager::update().
void otawa::PropList::addProp (Property * prop) inherited
Add property to the list without checking of duplication.
Parameters
prop Property to add.
References otawa::Property::_next.
Referenced by otawa::Identifier< T >::add(), otawa::ast::ASTInfo::ASTInfo(), otawa::Identifier< otawa::arm::Info * >::copy(), otawa::AbstractIdentifier::initProps(), otawa::ContextualProperty::make(), otawa::script::Script::makeConfig(), otawa::ccg::Builder::processLBlockSet(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), and otawa::ContextualProperty::refProps().
void otawa::PropList::addProps (const PropList & props) inherited
Add all properties from the given property list, in a reverse order.
Parameters
props Property list to clone.
References otawa::Property::copy(), otawa::PropList::head, and otawa::Property::next().
Referenced by otawa::display::CFGDrawer::CFGDrawer(), otawa::display::GraphVizGraph::GraphVizGraph(), otawa::ParamFeature::instantiate(), otawa::Manager::loadXML(), otawa::display::GraphVizGraph::newEdge(), otawa::display::GraphVizGraph::newNode(), otawa::Process::Process(), otawa::display::GraphVizItem::setProps(), otawa::VirtualBasicBlock::VirtualBasicBlock(), and otawa::VirtualCFG::VirtualCFG().
const Block & otawa::dcache::BlockAccess::block (void) const inline
Only for kind BLOCK, get the accessed block.
Returns
Accessed block.
References otawa::BLOCK.
Referenced by otawa::dcache::operator<<(), otawa::etime::StandardEventBuilder::processBB(), otawa::dcache::CATBuilder::processLBlockSet(), otawa::dcache::MUSTProblem::purge(), otawa::dcache::PERSProblem::purge(), otawa::dcache::MUSTPERS::update(), otawa::dcache::MUSTProblem::update(), otawa::dcache::MAYProblem::update(), and otawa::dcache::DirtyManager::update().
void otawa::PropList::clearProps (void) inherited
Remove all properties from the list.
References otawa::Property::next().
Referenced by otawa::PSTBuilder::getVCFG(), otawa::display::GraphVizItem::setProps(), and otawa::WorkSpace::~WorkSpace().
Property * otawa::PropList::extractProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::script::Script::makeConfig().
Property * otawa::PropList::extractProp (const AbstractIdentifier & id) inline inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::PropList::extractProp().
Referenced by otawa::PropList::extractProp().
int otawa::dcache::BlockAccess::first (void) const inline
Property * otawa::PropList::getProp (const AbstractIdentifier * id) const inherited
Find a property by its identifier.
Parameters
id Identifier of the property to find.
Returns
Found property or null.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::Identifier< otawa::arm::Info * >::exists(), otawa::ContextualProperty::exists(), otawa::ContextualProperty::find(), otawa::Identifier< T >::get(), otawa::ContextualProperty::make(), otawa::ParamFeature::matches(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::print(), otawa::ContextualProperty::print(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), otawa::ContextualProperty::refProps(), otawa::Identifier< T >::set(), otawa::Identifier< T >::use(), and otawa::Identifier< T >::value().
bool otawa::PropList::hasProp (const AbstractIdentifier & id) const inline inherited
Test if the property list contains a property matching the given identifier.
Parameters
id Property identifier to look for.
Returns
True if the list contains the matching property, false else.
References otawa::p::print().
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::Monitor::configure(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::exists(), and otawa::Manager::setVerbosity().
bool otawa::dcache::BlockAccess::in (const Block & block) const
Test if the given block may be concerned by the current access.
Parameters
block Block to test.
Returns
True if it concerned, false else.
References otawa::dcache::Block::address(), otawa::etime::BLOCK, otawa::dcache::Block::index(), kind, and OTAWA_PROC_VERSION.
Referenced by otawa::dcache::operator<<().
bool otawa::dcache::BlockAccess::inRange (int block) const inline
Test if the given block is the range of the given access.
Parameters
block Address of the cache block.
Returns
True if it is in the range, false else.
References cache().
Referenced by otawa::dcache::operator<<(), otawa::dcache::MUSTProblem::purge(), otawa::dcache::PERSProblem::purge(), and otawa::dcache::DirtyManager::update().
bool otawa::dcache::BlockAccess::inSet (int set, const hard::Cache * cache) const
Test if the given set concerns the range access.
Parameters
set Set to test for.
cache Current cache (to get set information).
Returns
True if the set contains a block of the range, false else.
References otawa::hard::Cache::set(), otawa::hard::Cache::setCount(), and otawa::hard::Cache::tag().
Referenced by otawa::dcache::operator<<().
Inst * otawa::dcache::BlockAccess::instruction (void) const inline
Get the instruction performing the access.
Returns
Instruction performing the access (must be an instruction of the basic block the access is applied to).
Referenced by otawa::etime::StandardEventBuilder::processBB(), and otawa::dcache::CatConstraintBuilder::processWorkSpace().
bool otawa::dcache::BlockAccess::isAny (void) const inline
Referenced by otawa::dcache::operator<<().
kind_t otawa::dcache::BlockAccess::kind (void) const inline
Get the kind of the access.
Returns
Access kind.
Referenced by otawa::dcache::operator<<(), otawa::etime::StandardEventBuilder::processBB(), otawa::dcache::CATBuilder::processLBlockSet(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), otawa::dcache::MUSTProblem::purge(), otawa::dcache::PERSProblem::purge(), otawa::dcache::MUSTPERS::update(), otawa::dcache::MUSTProblem::update(), otawa::dcache::MAYProblem::update(), and otawa::dcache::DirtyManager::update().
int otawa::dcache::BlockAccess::last (void) const inline
BlockAccess& otawa::dcache::BlockAccess::operator= (const BlockAccess & acc) inline
References _action, _kind, data, and inst.
void otawa::PropList::print (elm::io::Output & out) const inherited
Display the current property list.
Parameters
out Output to use.
Referenced by otawa::Edge::kindName(), otawa::operator<<(), and otawa::ContextualProperty::print().
void otawa::dcache::BlockAccess::print (io::Output & out) const
References otawa::BLOCK, and otawa::dcache::PURGE.
Referenced by otawa::dcache::operator<<().
void otawa::PropList::removeAllProp (const AbstractIdentifier * id) inherited
Remove all the properties matching the given identifier.
Parameters
id Identifier of properties to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::LoopUnroller::unroll().
void otawa::PropList::removeProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier.
Parameters
id Identifier of the property to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::PSTBuilder::buildTree(), otawa::BBRemover< T >::clean(), otawa::CFGBuilder::cleanup(), otawa::display::CFGOutput::processCFG(), otawa::SubCFGBuilder::processWorkSpace(), otawa::Identifier< otawa::arm::Info * >::remove(), and otawa::ContextualPath::Ref< T >::remove().
void otawa::PropList::removeProp (const AbstractIdentifier & id) inline inherited
References otawa::PropList::removeProp().
Referenced by otawa::PropList::removeProp().
void otawa::PropList::setProp (Property * prop) inherited
Set the property in the property list removing any double.
Parameters
prop Property to set.
References otawa::Property::_next, otawa::Property::id(), and otawa::Property::next().
void otawa::PropList::setProp (const AbstractIdentifier * id) inline inherited
References otawa::PropList::setProp().
Referenced by otawa::PropList::setProp().
Member Data Documentation
t::uint8 otawa::dcache::BlockAccess::_action private
Referenced by operator=().
t::uint8 otawa::dcache::BlockAccess::_kind private
Referenced by operator=().
const Block* otawa::dcache::BlockAccess::blk
union { ... } otawa::dcache::BlockAccess::data
Referenced by BlockAccess(), and operator=().
const PropList otawa::PropList::EMPTY static inherited
This is an empty proplist for convenience.
Referenced by otawa::DynProcessor::configure(), otawa::ActualFeature::processor(), otawa::SilentFeature::SilentFeature(), otawa::Processor::version(), and otawa::display::Driver::~Driver().
Address::offset_t otawa::dcache::BlockAccess::first
Only for the RANGE kind, get the first accessed block.
Returns
First accessed block.
Referenced by otawa::etime::StandardEventBuilder::processBB(), otawa::dcache::MUSTPERS::update(), and otawa::dcache::MUSTProblem::update().
Inst* otawa::dcache::BlockAccess::inst private
Referenced by operator=().
Address::offset_t otawa::dcache::BlockAccess::last
Only for the RANGE kind, get the last accessed block.
Returns
Last accessed block.
Referenced by otawa::dcache::MUSTPERS::update(), and otawa::dcache::MUSTProblem::update().
struct { ... } otawa::dcache::BlockAccess::range
The documentation for this class was generated from the following files:
include/otawa/dcache/features.h
src/dcache/dcache.cpp
src/dcache/dcache_BlockBuilder.cpp