Otawa: otawa::dcache::DirtyManager Class Reference
otawa::dcache::DirtyManager Class Reference
A dirty manager allows to exploit the results of the dirty analysis (DIRTY_FEATURE).
#include <otawa/dcache/features.h>
Classes
struct t
Public Types
typedef struct otawa::dcache::DirtyManager::t t
State for the dirty analysis.
Public Member Functions
DirtyManager (const BlockCollection &coll)
bool mayBeDirty (const t &value, int block) const
Test if the given block may be dirty.
bool mustBeDirty (const t &value, int block) const
Test if the given block must be dirty.
const t & bottom (void) const
Build a bottom dirty state.
const t & top (void) const
Build a top dirty state.
void set (t &d, const t &s) const
Copy a state in an existing one.
void update (t &d, const BlockAccess &acc)
Update the dirty state with the given block access.
void join (t &d, const t &s) const
Join two dirty states.
bool equals (const t &s1, const t &s2) const
Test if both dirty states are equals.
Private Attributes
t bot
t _top
const BlockCollection & _coll
Detailed Description
A dirty manager allows to exploit the results of the dirty analysis (DIRTY_FEATURE).
The code below shows how to use it:
DirtyManager man(my_block_row, my_cache);
DirtyManager::t s = man.clone(DIRTY(my_bb));
Pair<int, BlockAccess *> accs = DATA_BLOCKS(my_bb);
for(int i = 0; i < accs.fst; i++) {
        man.update(s, accs.snd[i]);
        if(man.mustBeDirty(d, my_cache_block))  ...;
        if(man.mayBeDirty(d, my_cache_block)) ...;
}
Member Typedef Documentation
otawa::dcache::DirtyManager::t
State for the dirty analysis.
Constructor & Destructor Documentation
otawa::dcache::DirtyManager::DirtyManager (const BlockCollection & coll)
References _top, bot, otawa::dfa::BitSet::empty(), otawa::dfa::BitSet::fill(), otawa::dcache::DirtyManager::t::may(), and otawa::dcache::DirtyManager::t::must().
Member Function Documentation
const DirtyManager::t & otawa::dcache::DirtyManager::bottom (void) const
Build a bottom dirty state.
References bot.
Referenced by otawa::dcache::DirtyManager::t::print().
bool otawa::dcache::DirtyManager::equals (const t & s1, const t & s2) const
Test if both dirty states are equals.
Parameters
s1 First state to compare.
s2 Second state to compare.
Returns
True if they are equal, false else.
References otawa::dfa::BitSet::equals(), otawa::dcache::DirtyManager::t::may(), and otawa::dcache::DirtyManager::t::must().
Referenced by otawa::dcache::DirtyManager::t::print().
void otawa::dcache::DirtyManager::join (t & d, const t & s) const
Join two dirty states.
Parameters
d First and target dirty state.
s Second dirty state.
References otawa::dcache::DirtyManager::t::may(), and otawa::dcache::DirtyManager::t::must().
bool otawa::dcache::DirtyManager::mayBeDirty (const t & state, int block) const
Test if the given block may be dirty.
Parameters
state Dirty state.
block Block to test.
Returns
True if it may be dirty, false else.
References otawa::dfa::BitSet::contains(), and otawa::dcache::DirtyManager::t::may().
bool otawa::dcache::DirtyManager::mustBeDirty (const t & state, int block) const
Test if the given block must be dirty.
Parameters
state Dirty state.
block Block to test.
Returns
True if it must be dirty, false else.
References otawa::dfa::BitSet::contains(), and otawa::dcache::DirtyManager::t::must().
void otawa::dcache::DirtyManager::set (t & d, const t & s) const
Copy a state in an existing one.
Parameters
d State to copy to.
s State to copy from.
References otawa::dcache::DirtyManager::t::may(), and otawa::dcache::DirtyManager::t::must().
const DirtyManager::t & otawa::dcache::DirtyManager::top (void) const
Build a top dirty state.
References _top.
void otawa::dcache::DirtyManager::update (t & d, const BlockAccess & acc)
Update the dirty state with the given block access.
Parameters
d Dirty state to change (input and output of the update).
acc Block access to update with.
References _coll, otawa::dcache::BlockAccess::action(), otawa::dfa::BitSet::add(), otawa::dcache::BlockAccess::ANY, otawa::dcache::BlockAccess::BLOCK, otawa::dcache::BlockAccess::block(), otawa::dcache::BlockCollection::cacheSet(), otawa::dcache::BlockCollection::count(), otawa::dfa::BitSet::empty(), otawa::dfa::BitSet::fill(), otawa::dcache::Block::index(), otawa::dcache::BlockAccess::inRange(), otawa::dcache::BlockAccess::kind(), otawa::dcache::BlockAccess::LOAD, otawa::dcache::DirtyManager::t::may(), otawa::dcache::DirtyManager::t::must(), otawa::clp::NONE, otawa::dcache::BlockAccess::PURGE, otawa::dcache::BlockAccess::RANGE, otawa::dfa::BitSet::remove(), otawa::dcache::Block::set(), and otawa::dcache::BlockAccess::STORE.
Referenced by otawa::dcache::DirtyManager::t::print().
Member Data Documentation
const BlockCollection& otawa::dcache::DirtyManager::_coll private
Referenced by update().
t otawa::dcache::DirtyManager::_top private
Referenced by DirtyManager(), and top().
t otawa::dcache::DirtyManager::bot private
Referenced by bottom(), and DirtyManager().
The documentation for this class was generated from the following files:
include/otawa/dcache/features.h
src/dcache/Dirty.cpp