Otawa: otawa::ai::CFGGraph Class Reference
otawa::ai::CFGGraph Class Reference
New Abstract Interpretation Engine
BiDiGraph implementation for CFG.
#include <otawa/dfa/ai.h>
Classes
class Iterator
class Predecessor
class Successor
Public Types
typedef BasicBlock * vertex_t
typedef Edge * edge_t
Public Member Functions
CFGGraph (CFG *cfg)
vertex_t entry (void) const
vertex_t exit (void) const
vertex_t sinkOf (edge_t e) const
vertex_t sourceOf (edge_t e) const
int index (vertex_t v) const
int count (void) const
Private Attributes
CFG * _cfg
Detailed Description
BiDiGraph implementation for CFG.
BiDiGraph adapter implementation for CFG.
Member Typedef Documentation
typedef Edge* otawa::ai::CFGGraph::edge_t
typedef BasicBlock* otawa::ai::CFGGraph::vertex_t
Constructor & Destructor Documentation
otawa::ai::CFGGraph::CFGGraph (CFG * cfg) inline
Member Function Documentation
int otawa::ai::CFGGraph::count (void) const inline
vertex_t otawa::ai::CFGGraph::entry (void) const inline
vertex_t otawa::ai::CFGGraph::exit (void) const inline
int otawa::ai::CFGGraph::index (vertex_t v) const inline
References otawa::BasicBlock::number().
vertex_t otawa::ai::CFGGraph::sinkOf (edge_t e) const inline
References otawa::Edge::target().
vertex_t otawa::ai::CFGGraph::sourceOf (edge_t e) const inline
References otawa::Edge::source().
Member Data Documentation
CFG* otawa::ai::CFGGraph::_cfg private
The documentation for this class was generated from the following file:
include/otawa/dfa/ai.h