Otawa: otawa::MUSTPERS Class Reference
otawa::MUSTPERS Class Reference
#include <otawa/cache/cat2/MUSTPERS.h>
Classes
class Domain
Public Member Functions
MUSTPERS (const int _size, LBlockSet *_lbset, WorkSpace *_fw, const hard::Cache *_cache, const int _A)
const Domain & bottom (void) const
const Domain & entry (void) const
void lub (Domain &a, const Domain &b) const
void assign (Domain &a, const Domain &b) const
bool equals (const Domain &a, const Domain &b) const
void update (Domain &out, const Domain &in, BasicBlock *bb)
void enterContext (Domain &dom, BasicBlock *header, hai_context_t ctx)
void leaveContext (Domain &dom, BasicBlock *header, hai_context_t ctx)
Private Attributes
MUSTProblem mustProb
PERSProblem persProb
Domain bot
Domain ent
unsigned int line
Constructor & Destructor Documentation
otawa::MUSTPERS::MUSTPERS (const int _size, LBlockSet * _lbset, WorkSpace * _fw, const hard::Cache * _cache, const int _A)
References otawa::MUSTProblem::assign(), otawa::PERSProblem::assign(), bot, otawa::MUSTProblem::bottom(), otawa::PERSProblem::bottom(), ent, otawa::MUSTProblem::entry(), otawa::PERSProblem::entry(), otawa::MUSTPERS::Domain::must, mustProb, otawa::MUSTPERS::Domain::pers, and persProb.
Member Function Documentation
void otawa::MUSTPERS::assign (Domain & a, const Domain & b) const inline
Referenced by update().
const MUSTPERS::Domain & otawa::MUSTPERS::bottom (void) const
References bot.
void otawa::MUSTPERS::enterContext (Domain & dom, BasicBlock * header, hai_context_t ctx) inline
References otawa::MUSTProblem::enterContext(), otawa::PERSProblem::enterContext(), otawa::MUSTPERS::Domain::must, mustProb, otawa::MUSTPERS::Domain::pers, and persProb.
const MUSTPERS::Domain & otawa::MUSTPERS::entry (void) const
References ent.
bool otawa::MUSTPERS::equals (const Domain & a, const Domain & b) const inline
References otawa::cfgio::bb(), otawa::MUSTPERS::Domain::equals(), and update().
void otawa::MUSTPERS::leaveContext (Domain & dom, BasicBlock * header, hai_context_t ctx) inline
References otawa::MUSTProblem::leaveContext(), otawa::PERSProblem::leaveContext(), otawa::MUSTPERS::Domain::must, mustProb, otawa::MUSTPERS::Domain::pers, and persProb.
void otawa::MUSTPERS::lub (Domain & a, const Domain & b) const inline
References otawa::MUSTPERS::Domain::lub().
void otawa::MUSTPERS::update (Domain & out, const Domain & in, BasicBlock * bb)
References assign(), otawa::LBlock::cacheblock(), otawa::MUSTPERS::Domain::inject(), otawa::LAST_LBLOCK, and line.
Referenced by equals().
Member Data Documentation
Domain otawa::MUSTPERS::bot private
Referenced by bottom(), and MUSTPERS().
Domain otawa::MUSTPERS::ent private
Referenced by entry(), and MUSTPERS().
unsigned int otawa::MUSTPERS::line private
Referenced by update().
MUSTProblem otawa::MUSTPERS::mustProb private
Referenced by enterContext(), leaveContext(), and MUSTPERS().
PERSProblem otawa::MUSTPERS::persProb private
Referenced by enterContext(), leaveContext(), and MUSTPERS().
The documentation for this class was generated from the following files:
include/otawa/cache/cat2/MUSTPERS.h
src/prog/cache_MUSTPERS.cpp