Otawa: otawa::stack::Manager Class Reference
otawa::stack::Manager Class Reference
Stack Analysis
Manager for results of stack analysis.
#include <otawa/stack/features.h>
Public Types
typedef State * t
Public Member Functions
Manager (WorkSpace *ws)
~Manager (void)
t bot (void)
void free (t s)
bool equals (t s1, t s2)
t copy (t s)
t joinPath (t s1, t s2)
t state (BasicBlock *bb)
t updatePath (t s, sem::inst i)
Value getReg (t s, int i)
Get register value.
Value getMem (t s, Value addr, int size)
Get value from memory.
Private Attributes
StackProblem * p
State * _bot
Detailed Description
Manager for results of stack analysis.
Implements concept StateManager.
Member Typedef Documentation
typedef State* otawa::stack::Manager::t
Constructor & Destructor Documentation
otawa::stack::Manager::Manager (WorkSpace * ws)
otawa::stack::Manager::~Manager (void)
Member Function Documentation
Manager::t otawa::stack::Manager::bot (void)
Manager::t otawa::stack::Manager::copy (t s)
bool otawa::stack::Manager::equals (t s1, t s2)
void otawa::stack::Manager::free (t s)
References otawa::sem::StateIter< Manager >::s.
Value otawa::stack::Manager::getMem (t s, Value addr, int size)
Get value from memory.
Parameters
addr Value address.
size Value size.
Returns
Memory value.
Value otawa::stack::Manager::getReg (t s, int i)
Get register value.
Parameters
i Register index.
Returns
Register value.
Manager::t otawa::stack::Manager::joinPath (t s1, t s2)
Manager::t otawa::stack::Manager::state (BasicBlock * bb)
References otawa::stack::STATE.
Manager::t otawa::stack::Manager::updatePath (t s, sem::inst i)
References otawa::ADDRESS_ANALYSIS_FEATURE, otawa::stack::ADDRESS_FEATURE, otawa::ADDRESS_STATS, otawa::ADDRESSES, otawa::stack::ALL, otawa::AccessedAddress::ANY, otawa::p::init::base(), otawa::cfgio::bb(), otawa::cfgio::cfg(), otawa::CFGProcessor::configure(), otawa::stack::CST, otawa::stack::Iter::getReg(), otawa::sem::StateIter< Manager >::i, otawa::sem::StateIter< S >::instruction(), otawa::BasicBlock::isEnd(), otawa::stack::Iter::Iter(), otawa::stack::Value::kind(), otawa::sem::LOAD, otawa::p::init::maker(), otawa::stack::MANAGER, otawa::stack::NONE, otawa::stack::REG, otawa::CFGProcessor::reg, otawa::p::require, otawa::sem::StateIter< Manager >::s, otawa::AccessedAddresses::set(), otawa::stack::SP, otawa::sem::StateIter< Manager >::ss, otawa::sem::StateIter< S >::start(), otawa::sem::STORE, and otawa::stack::Value::value().
Member Data Documentation
State* otawa::stack::Manager::_bot private
StackProblem* otawa::stack::Manager::p private
The documentation for this class was generated from the following files:
include/otawa/stack/features.h
src/prog/util_StackAnalysis.cpp