Otawa: otawa::ParamFeature Class Reference
otawa::ParamFeature Class Reference
Parametric Features and Processor
A parametric feature is a feature that may be instantiated according to some parameters passed in a property list.
#include <otawa/proc/ParamFeature.h>
Public Member Functions
ParamFeature (cstring id, AbstractParamProcessor &def)
ActualFeature * instantiate (const PropList &props)
Instantiate the feature.
const AbstractParamProcessor *& defaultValue (void) const
void add (PropList &list, const AbstractParamProcessor *&value) const
Add a generic property to the given list with the current identifier.
void add (PropList *list, const AbstractParamProcessor *&value) const
Add a generic property to the given list with the current identifier.
void set (PropList &list, const AbstractParamProcessor *&value) const
Set the value of a generic property with the current identifier to the given list.
void set (PropList *list, const AbstractParamProcessor *&value) const
Set the value of a generic property with the current identifier to the given list.
void set (Property *prop, const AbstractParamProcessor *&value) const
elm::Option< AbstractParamProcessor * > get (const PropList &list) const
const AbstractParamProcessor *& get (const PropList &list, const AbstractParamProcessor *&def) const
Get the value associated with a property matching the current identifier.
elm::Option< AbstractParamProcessor * > get (const PropList *list) const
const AbstractParamProcessor *& get (const PropList *list, const AbstractParamProcessor *&def) const
Get the value associated with a property matching the current identifier.
const AbstractParamProcessor *& get (const Property *prop) const
AbstractParamProcessor *& ref (PropList &list) const
AbstractParamProcessor *& ref (PropList *list) const
const AbstractParamProcessor *& use (const PropList &list) const
Get the value matching the current identifier in the given list.
const AbstractParamProcessor *& use (const PropList *list) const
Get the value matching the current identifier in the given list.
const AbstractParamProcessor *& value (const PropList &list) const
For internal use only.
Ref< AbstractParamProcessor *, Identifier > value (PropList &list) const
For internal use only.
const AbstractParamProcessor *& value (const PropList *list) const
For internal use only.
Ref< AbstractParamProcessor *, Identifier< AbstractParamProcessor * > > value (PropList *list) const
For internal use only.
void remove (PropList &list) const
Remove the property with the current identifier from the given list.
void remove (PropList *list) const
Remove the property with the current identifier from the given list.
bool exists (const PropList &list) const
bool exists (const PropList *list) const
void copy (PropList &list, Property *prop)
void copy (PropList *list, Property *prop)
virtual Property * copy (Property &prop) const
Build a copy of the given property.
Property * copy (Property *prop) const
const AbstractParamProcessor *& operator() (const PropList &props) const
Read the value in a functional way.
const AbstractParamProcessor *& operator() (const PropList *props) const
Read the value in a functional way.
Ref< AbstractParamProcessor *, Identifier< AbstractParamProcessor * > > operator() (PropList &props) const
Read or write a property value in a functional way.
Ref< AbstractParamProcessor *, Identifier< AbstractParamProcessor * > > operator() (PropList *props) const
Read or write a property value in a functional way.
const AbstractParamProcessor *& operator() (Property *prop) const
virtual void print (elm::io::Output &out, const Property *prop) const
Print the value of the given property (accordint the property matches the given identifier).
void print (elm::io::Output &out) const
Print the identifier.
void print (elm::io::Output &output, const Property &prop) const
virtual void printFormatted (io::Output &out, const Property *prop) const
Print the value of the given property in a formatted way, that is, possibly to perform re-scanning after.
void printFormatted (elm::io::Output &output, const Property &prop) const
virtual const Type & type (void) const
Get the identifier of data linked with this property.
virtual void fromString (PropList &props, const string &str) const
Get value of an identifier from a string and store it in the given property list.
const string name (void) const
Get the string name of the identifier.
virtual bool equals (const Property *prop1, const Property *prop2) const
Test if two properties are equal.
virtual void serialize (Property *prop, elm::serial2::Serializer &serializer)
Serialize the workspace to the current serializer.
virtual Property * unserialize (elm::serial2::Unserializer &unserializer)
Unserialize the workspace to the current unserializer.
Property * getProp (const AbstractIdentifier *id) const
Find a property by its identifier.
void setProp (Property *prop)
Set the property in the property list removing any double.
void setProp (const AbstractIdentifier *id)
void removeProp (const AbstractIdentifier *id)
Remove a property matching the given identifier.
void removeProp (const AbstractIdentifier &id)
Property * extractProp (const AbstractIdentifier *id)
Remove a property matching the given identifier and return it.
Property * extractProp (const AbstractIdentifier &id)
Remove a property matching the given identifier and return it.
void addProp (Property *prop)
Add property to the list without checking of duplication.
void removeAllProp (const AbstractIdentifier *id)
Remove all the properties matching the given identifier.
bool hasProp (const AbstractIdentifier &id) const
Test if the property list contains a property matching the given identifier.
void clearProps (void)
Remove all properties from the list.
void addProps (const PropList &props)
Add all properties from the given property list, in a reverse order.
Static Public Member Functions
static AbstractIdentifier * find (const string &name)
Find an abstract identifier by its name.
Static Public Attributes
static Identifier< AbstractParamIdentifier * > PARAM_ID
This identifier is used to hook parametric identifiers associated with a parametric feature.
static const PropList EMPTY
This is an empty proplist for convenience.
Protected Member Functions
void initProps (Property *prop, VarArg &args)
Add the properties found in the arguments (list of Property * ended by null) to the identifier properties.
void initProps (const PropList &props)
Initialize properties coming from the constructor.
Private Member Functions
bool matches (ActualFeature *feat, const PropList &def)
Test if the given feature matches the given properties.
Private Attributes
const AbstractParamProcessor & proc
genstruct::Vector< ActualFeature * > feats
Detailed Description
A parametric feature is a feature that may be instantiated according to some parameters passed in a property list.
Parameters
id Param feature identifier.
def Default processor.
Author
H. Cass casse.nosp@m.@iri.nosp@m.t.fr
Constructor & Destructor Documentation
otawa::ParamFeature::ParamFeature (cstring id, AbstractParamProcessor & def)
Member Function Documentation
void otawa::Identifier< AbstractParamProcessor * >::add (PropList & list, const AbstractParamProcessor * & value) const inline inherited
Add a generic property to the given list with the current identifier.
Parameters
list List to add to.
value Value of the property.
void otawa::Identifier< AbstractParamProcessor * >::add (PropList * list, const AbstractParamProcessor * & value) const inline inherited
Add a generic property to the given list with the current identifier.
Parameters
list List to add to.
value Value of the property.
void otawa::PropList::addProp (Property * prop) inherited
Add property to the list without checking of duplication.
Parameters
prop Property to add.
References otawa::Property::_next.
Referenced by otawa::Identifier< T >::add(), otawa::ast::ASTInfo::ASTInfo(), otawa::Identifier< otawa::arm::Info * >::copy(), otawa::AbstractIdentifier::initProps(), otawa::ContextualProperty::make(), otawa::script::Script::makeConfig(), otawa::ccg::Builder::processLBlockSet(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), and otawa::ContextualProperty::refProps().
void otawa::PropList::addProps (const PropList & props) inherited
Add all properties from the given property list, in a reverse order.
Parameters
props Property list to clone.
References otawa::Property::copy(), otawa::PropList::head, and otawa::Property::next().
Referenced by otawa::display::CFGDrawer::CFGDrawer(), otawa::display::GraphVizGraph::GraphVizGraph(), instantiate(), otawa::Manager::loadXML(), otawa::display::GraphVizGraph::newEdge(), otawa::display::GraphVizGraph::newNode(), otawa::Process::Process(), otawa::display::GraphVizItem::setProps(), otawa::VirtualBasicBlock::VirtualBasicBlock(), and otawa::VirtualCFG::VirtualCFG().
void otawa::PropList::clearProps (void) inherited
Remove all properties from the list.
References otawa::Property::next().
Referenced by otawa::PSTBuilder::getVCFG(), otawa::display::GraphVizItem::setProps(), and otawa::WorkSpace::~WorkSpace().
Property* otawa::AbstractIdentifier::copy (Property * prop) const inline inherited
References otawa::AbstractIdentifier::AbstractIdentifier(), otawa::AbstractIdentifier::copy(), otawa::AbstractIdentifier::initProps(), otawa::AbstractIdentifier::name(), otawa::AbstractIdentifier::serialize(), and otawa::AbstractIdentifier::unserialize().
Referenced by otawa::AbstractIdentifier::copy().
void otawa::Identifier< AbstractParamProcessor * >::copy (PropList & list, Property * prop) inline inherited
void otawa::Identifier< AbstractParamProcessor * >::copy (PropList * list, Property * prop) inline inherited
virtual Property* otawa::Identifier< AbstractParamProcessor * >::copy (Property & prop) const inline virtual inherited
Build a copy of the given property.
Parameters
prop Property to copy.
Returns
Copy of the property.
Reimplemented from otawa::AbstractIdentifier.
const AbstractParamProcessor * & otawa::Identifier< AbstractParamProcessor * >::defaultValue (void) const inline inherited
bool otawa::AbstractIdentifier::equals (const Property * prop1, const Property * prop2) const virtual inherited
Test if two properties are equal.
Parameters
prop1 First property.
prop2 Second property.
Returns
True if they are equal, false else.
Referenced by otawa::AbstractIdentifier::printFormatted().
bool otawa::Identifier< AbstractParamProcessor * >::exists (const PropList & list) const inline inherited
bool otawa::Identifier< AbstractParamProcessor * >::exists (const PropList * list) const inline inherited
Property * otawa::PropList::extractProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::script::Script::makeConfig().
Property * otawa::PropList::extractProp (const AbstractIdentifier & id) inline inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::PropList::extractProp().
Referenced by otawa::PropList::extractProp().
AbstractIdentifier * otawa::AbstractIdentifier::find (const string & name) static inherited
Find an abstract identifier by its name.
Parameters
name Name of the looked identifier.
Returns
Found identifier or null.
Referenced by otawa::ProcessorPlugin::getIdentifier(), and otawa::Application::run().
virtual void otawa::Identifier< AbstractParamProcessor * >::fromString (PropList & props, const string & str) const virtual inherited
Get value of an identifier from a string and store it in the given property list.
Parameters
props Property list to store result into.
str String to get value from.
Reimplemented from otawa::AbstractIdentifier.
elm::Option<AbstractParamProcessor * > otawa::Identifier< AbstractParamProcessor * >::get (const PropList & list) const inline inherited
const AbstractParamProcessor * & otawa::Identifier< AbstractParamProcessor * >::get (const PropList & list, const AbstractParamProcessor * & def) const inline inherited
Get the value associated with a property matching the current identifier.
If the property is not found, return the default value.
Parameters
list List to look in.
def Default value.
Returns
Found value or the default value.
elm::Option<AbstractParamProcessor * > otawa::Identifier< AbstractParamProcessor * >::get (const PropList * list) const inline inherited
const AbstractParamProcessor * & otawa::Identifier< AbstractParamProcessor * >::get (const PropList * list, const AbstractParamProcessor * & def) const inline inherited
Get the value associated with a property matching the current identifier.
If the property is not found, return the default value.
Parameters
list List to look in.
def Default value.
Returns
Found value or the default value.
const AbstractParamProcessor * & otawa::Identifier< AbstractParamProcessor * >::get (const Property * prop) const inline inherited
Property * otawa::PropList::getProp (const AbstractIdentifier * id) const inherited
Find a property by its identifier.
Parameters
id Identifier of the property to find.
Returns
Found property or null.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::Identifier< otawa::arm::Info * >::exists(), otawa::ContextualProperty::exists(), otawa::ContextualProperty::find(), otawa::Identifier< T >::get(), otawa::ContextualProperty::make(), matches(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::print(), otawa::ContextualProperty::print(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), otawa::ContextualProperty::refProps(), otawa::Identifier< T >::set(), otawa::Identifier< T >::use(), and otawa::Identifier< T >::value().
bool otawa::PropList::hasProp (const AbstractIdentifier & id) const inline inherited
Test if the property list contains a property matching the given identifier.
Parameters
id Property identifier to look for.
Returns
True if the list contains the matching property, false else.
References otawa::p::print().
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::Monitor::configure(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::exists(), and otawa::Manager::setVerbosity().
void otawa::AbstractIdentifier::initProps (Property * prop, VarArg & args) protected inherited
Add the properties found in the arguments (list of Property * ended by null) to the identifier properties.
Parameters
prop First property.
args Null-ended properties to scan.
References otawa::PropList::addProp(), and otawa::Property::next().
Referenced by otawa::AbstractIdentifier::AbstractIdentifier(), and otawa::AbstractIdentifier::copy().
void otawa::AbstractIdentifier::initProps (const PropList & props) protected inherited
Initialize properties coming from the constructor.
References otawa::IDENTIFIER_ID, and otawa::AbstractIdentifier::nam.
ActualFeature * otawa::ParamFeature::instantiate (const PropList & props)
Instantiate the feature.
Parameters
props Properties to instantiate the feature.
Returns
Instantiated feature.
References otawa::AbstractParamIdentifier::ACTUAL_ID, otawa::PropList::addProps(), feats, matches(), PARAM_ID, and proc.
bool otawa::ParamFeature::matches (ActualFeature * feat, const PropList & props) private
Test if the given feature matches the given properties.
Parameters
feat Feature to test.
props Property list to test.
Returns
True if both matches, false else.
References otawa::PropList::getProp().
Referenced by instantiate().
const elm::String & otawa::AbstractIdentifier::name (void) const inline inherited
Get the string name of the identifier.
Returns
Identifier name.
References otawa::AbstractIdentifier::nam, and otawa::AbstractIdentifier::print().
Referenced by otawa::AlternativeProcessor::AlternativeProcessor(), otawa::AbstractIdentifier::copy(), otawa::AbstractIdentifier::fromString(), otawa::ParamProcessor::instantiate(), otawa::WorkSpace::provide(), otawa::hard::Platform::Identification::split(), and otawa::ParamProcessor::AbstractMaker::~AbstractMaker().
const AbstractParamProcessor * & otawa::Identifier< AbstractParamProcessor * >::operator() (const PropList & props) const inline inherited
Read the value in a functional way.
Parameters
props Property list to read the property from.
Returns
Value of the property matching the current identifier in the list.
const AbstractParamProcessor * & otawa::Identifier< AbstractParamProcessor * >::operator() (const PropList * props) const inline inherited
Read the value in a functional way.
Parameters
props Property list to read the property from.
Returns
Value of the property matching the current identifier in the list.
Ref<AbstractParamProcessor * , Identifier<AbstractParamProcessor * > > otawa::Identifier< AbstractParamProcessor * >::operator() (PropList & props) const inline inherited
Read or write a property value in a functional way.
The returned value may be read (automatic conversion to the value) or written (using operator = to set the value or += to add a new value at the property list.
Parameters
props Property list to read the property from.
Returns
Value of the property matching the current identifier in the list.
Ref<AbstractParamProcessor * , Identifier<AbstractParamProcessor * > > otawa::Identifier< AbstractParamProcessor * >::operator() (PropList * props) const inline inherited
Read or write a property value in a functional way.
The returned value may be read (automatic conversion to the value) or written (using operator = to set the value or += to add a new value at the property list.
Parameters
props Property list to read the property from.
Returns
Value of the property matching the current identifier in the list.
const AbstractParamProcessor * & otawa::Identifier< AbstractParamProcessor * >::operator() (Property * prop) const inline inherited
void otawa::AbstractIdentifier::print (elm::io::Output & out) const inherited
Print the identifier.
Parameters
out Output stream.
References otawa::AbstractIdentifier::nam.
Referenced by otawa::display::GraphVizItem::getPropertiesString(), and otawa::AbstractIdentifier::name().
void otawa::AbstractIdentifier::print (elm::io::Output & output, const Property & prop) const inline inherited
References otawa::AbstractIdentifier::print(), and otawa::AbstractIdentifier::printFormatted().
Referenced by otawa::AbstractIdentifier::print().
virtual void otawa::Identifier< AbstractParamProcessor * >::print (elm::io::Output & out, const Property * prop) const inline virtual inherited
Print the value of the given property (accordint the property matches the given identifier).
It is an error to call this method with a property matching a different identifier.
Use the print() method of a property instead.
Reimplemented from otawa::AbstractIdentifier.
void otawa::AbstractIdentifier::printFormatted (elm::io::Output & output, const Property & prop) const inline inherited
References otawa::AbstractIdentifier::copy(), otawa::AbstractIdentifier::equals(), otawa::AbstractIdentifier::fromString(), otawa::AbstractIdentifier::printFormatted(), and otawa::AbstractIdentifier::type().
Referenced by otawa::AbstractIdentifier::printFormatted().
virtual void otawa::Identifier< AbstractParamProcessor * >::printFormatted (io::Output & out, const Property * prop) const inline virtual inherited
Print the value of the given property in a formatted way, that is, possibly to perform re-scanning after.
For example, string are quoted and special character escaped.
Parameters
out Output to use.
prop Property to display.
Reimplemented from otawa::AbstractIdentifier.
AbstractParamProcessor * & otawa::Identifier< AbstractParamProcessor * >::ref (PropList & list) const inline inherited
AbstractParamProcessor * & otawa::Identifier< AbstractParamProcessor * >::ref (PropList * list) const inline inherited
void otawa::Identifier< AbstractParamProcessor * >::remove (PropList & list) const inline inherited
Remove the property with the current identifier from the given list.
Parameters
list List to remove from.
void otawa::Identifier< AbstractParamProcessor * >::remove (PropList * list) const inline inherited
Remove the property with the current identifier from the given list.
Parameters
list List to remove from.
void otawa::PropList::removeAllProp (const AbstractIdentifier * id) inherited
Remove all the properties matching the given identifier.
Parameters
id Identifier of properties to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::LoopUnroller::unroll().
void otawa::PropList::removeProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier.
Parameters
id Identifier of the property to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::PSTBuilder::buildTree(), otawa::BBRemover< T >::clean(), otawa::CFGBuilder::cleanup(), otawa::display::CFGOutput::processCFG(), otawa::SubCFGBuilder::processWorkSpace(), otawa::Identifier< otawa::arm::Info * >::remove(), and otawa::ContextualPath::Ref< T >::remove().
void otawa::PropList::removeProp (const AbstractIdentifier & id) inline inherited
References otawa::PropList::removeProp().
Referenced by otawa::PropList::removeProp().
void otawa::AbstractIdentifier::serialize (Property * prop, elm::serial2::Serializer & serializer) virtual inherited
Serialize the workspace to the current serializer.
In the default implementation, do nothing.
Parameters
prop Property containing the value to serialize.
serializer Serializer to serialize to.
Referenced by otawa::AbstractIdentifier::copy().
void otawa::Identifier< AbstractParamProcessor * >::set (PropList & list, const AbstractParamProcessor * & value) const inline inherited
Set the value of a generic property with the current identifier to the given list.
Parameters
list List to set in.
value Value to set.
void otawa::Identifier< AbstractParamProcessor * >::set (PropList * list, const AbstractParamProcessor * & value) const inline inherited
Set the value of a generic property with the current identifier to the given list.
Parameters
list List to set in.
value Value to set.
void otawa::Identifier< AbstractParamProcessor * >::set (Property * prop, const AbstractParamProcessor * & value) const inline inherited
void otawa::PropList::setProp (Property * prop) inherited
Set the property in the property list removing any double.
Parameters
prop Property to set.
References otawa::Property::_next, otawa::Property::id(), and otawa::Property::next().
void otawa::PropList::setProp (const AbstractIdentifier * id) inline inherited
References otawa::PropList::setProp().
Referenced by otawa::PropList::setProp().
virtual const Type& otawa::Identifier< AbstractParamProcessor * >::type (void) const inline virtual inherited
Get the identifier of data linked with this property.
It may return Type::no_type ever meaning that the identifier does not support type system or that it is just a flag without associated data.
Returns
Type of the associated data.
Reimplemented from otawa::AbstractIdentifier.
Property * otawa::AbstractIdentifier::unserialize (elm::serial2::Unserializer & unserializer) virtual inherited
Unserialize the workspace to the current unserializer.
In the default implementation, do nothing.
Parameters
unserializer Unserializer to unserialize to.
Returns
Property result of unserialization, null if the property cannot be unserialized.
Referenced by otawa::AbstractIdentifier::copy().
const AbstractParamProcessor * & otawa::Identifier< AbstractParamProcessor * >::use (const PropList & list) const inline inherited
Get the value matching the current identifier in the given list.
Cause a run-time abort if the property is not available.
Parameters
list List to look in.
Returns
Matching value.
const AbstractParamProcessor * & otawa::Identifier< AbstractParamProcessor * >::use (const PropList * list) const inline inherited
Get the value matching the current identifier in the given list.
Cause a run-time abort if the property is not available.
Parameters
list List to look in.
Returns
Matching value.
const AbstractParamProcessor * & otawa::Identifier< AbstractParamProcessor * >::value (const PropList & list) const inline inherited
For internal use only.
Ref<AbstractParamProcessor * , Identifier> otawa::Identifier< AbstractParamProcessor * >::value (PropList & list) const inline inherited
For internal use only.
const AbstractParamProcessor * & otawa::Identifier< AbstractParamProcessor * >::value (const PropList * list) const inline inherited
For internal use only.
Ref<AbstractParamProcessor * , Identifier<AbstractParamProcessor * > > otawa::Identifier< AbstractParamProcessor * >::value (PropList * list) const inline inherited
For internal use only.
Member Data Documentation
const PropList otawa::PropList::EMPTY static inherited
This is an empty proplist for convenience.
Referenced by otawa::DynProcessor::configure(), otawa::ActualFeature::processor(), otawa::SilentFeature::SilentFeature(), otawa::Processor::version(), and otawa::display::Driver::~Driver().
genstruct::Vector<ActualFeature *> otawa::ParamFeature::feats private
Referenced by instantiate().
Identifier< AbstractParamIdentifier * > otawa::ParamFeature::PARAM_ID static
This identifier is used to hook parametric identifiers associated with a parametric feature.
This identifier is automatically used at parametric identifier creation.
Hooks
otawa::ParamFeature
Referenced by otawa::AbstractParamIdentifier::AbstractParamIdentifier(), and instantiate().
const AbstractParamProcessor& otawa::ParamFeature::proc private
Referenced by instantiate().
The documentation for this class was generated from the following files:
include/otawa/proc/ParamFeature.h
src/prog/proc_ParamFeature.cpp