Otawa: otawa::hard::Processor Class Reference
otawa::hard::Processor Class Reference
Platform Description
Description of a processor pipeline.
#include <otawa/hard/Processor.h>
Classes
class Make
Public Types
typedef genstruct::Vector< Step > steps_t
Public Member Functions
Processor (void)
Processor (const Make &m, cstring name="")
Build a processor using a processor builder.
Processor (const Processor &proc, cstring name="")
Build a clone of the given processor.
virtual ~Processor (void)
elm::String getArch (void) const
elm::String getModel (void) const
elm::String getBuilder (void) const
const Table< Stage * > & getStages (void) const
const Table< Queue * > & getQueues (void) const
t::uint64 getFrequency (void) const
virtual void execute (Inst *inst, steps_t &steps) const
Generate the execution steps to execute the given instruction on the current processor.
virtual Processor * clone (cstring name="") const
virtual Processor * instantiate (Process *process, cstring name="") const
Perform a copy a copy of the current processor specialized for the given process.
const string name (void) const
Get the string name of the identifier.
void print (elm::io::Output &out) const
Print the identifier.
virtual void print (elm::io::Output &output, const Property *prop) const
Print the value of the given property (accordint the property matches the given identifier).
void print (elm::io::Output &output, const Property &prop) const
virtual void printFormatted (io::Output &out, const Property *prop) const
Print the value of the given property in a formatted way, that is, possibly to perform re-scanning after.
void printFormatted (elm::io::Output &output, const Property &prop) const
virtual const Type & type (void) const
Get the identifier of data linked with this property.
virtual void fromString (PropList &props, const string &str) const
Get value of an identifier from a string and store it in the given property list.
virtual bool equals (const Property *prop1, const Property *prop2) const
Test if two properties are equal.
virtual Property * copy (Property &prop) const
Build a copy of the given property.
Property * copy (Property *prop) const
virtual void serialize (Property *prop, elm::serial2::Serializer &serializer)
Serialize the workspace to the current serializer.
virtual Property * unserialize (elm::serial2::Unserializer &unserializer)
Unserialize the workspace to the current unserializer.
Property * getProp (const AbstractIdentifier *id) const
Find a property by its identifier.
void setProp (Property *prop)
Set the property in the property list removing any double.
void setProp (const AbstractIdentifier *id)
void removeProp (const AbstractIdentifier *id)
Remove a property matching the given identifier.
void removeProp (const AbstractIdentifier &id)
Property * extractProp (const AbstractIdentifier *id)
Remove a property matching the given identifier and return it.
Property * extractProp (const AbstractIdentifier &id)
Remove a property matching the given identifier and return it.
void addProp (Property *prop)
Add property to the list without checking of duplication.
void removeAllProp (const AbstractIdentifier *id)
Remove all the properties matching the given identifier.
bool hasProp (const AbstractIdentifier &id) const
Test if the property list contains a property matching the given identifier.
void clearProps (void)
Remove all properties from the list.
void addProps (const PropList &props)
Add all properties from the given property list, in a reverse order.
Static Public Member Functions
static Processor * load (const elm::system::Path &path) throw (LoadException)
Load a processor descriptor from the given file.
static Processor * load (xom::Element *element) throw (LoadException)
Load a processor description from an XML element.
static AbstractIdentifier * find (const string &name)
Find an abstract identifier by its name.
Static Public Attributes
static const Processor null
Null processor: no stage, no queue.
static const PropList EMPTY
This is an empty proplist for convenience.
Protected Member Functions
Process * process (void) const
void initProps (Property *prop, VarArg &args)
Add the properties found in the arguments (list of Property * ended by null) to the identifier properties.
void initProps (const PropList &props)
Initialize properties coming from the constructor.
Private Member Functions
& FIELD (builder)&FIELD(stages)&FIELD(queues)&FIELD(frequency))
Private Attributes
string arch
string model
string builder
AllocatedTable< Stage * > stages
AllocatedTable< Queue * > queues
t::uint64 frequency
Process * _process
Friends
class ProcessorProcessor
Detailed Description
Description of a processor pipeline.
A pipeline is viewed as a collection of stages (otawa::hard::Stage) separated by instructions queues (otawa::hard::Queue).
Member Typedef Documentation
typedef genstruct::Vector<Step> otawa::hard::Processor::steps_t
Constructor & Destructor Documentation
otawa::hard::Processor::Processor (void)
Referenced by clone(), instantiate(), and load().
otawa::hard::Processor::Processor (const Make & m, cstring name = "")
Build a processor using a processor builder.
References otawa::hard::Processor::Make::queues, queues, otawa::hard::Processor::Make::stages, and stages.
otawa::hard::Processor::Processor (const Processor & proc, cstring name = "")
Build a clone of the given processor.
Parameters
proc Processor to clone.
name Name of the new processor (optional).
References queues, and stages.
otawa::hard::Processor::~Processor (void) virtual
References null.
Member Function Documentation
void otawa::PropList::addProp (Property * prop) inherited
Add property to the list without checking of duplication.
Parameters
prop Property to add.
References otawa::Property::_next.
Referenced by otawa::Identifier< T >::add(), otawa::ast::ASTInfo::ASTInfo(), otawa::Identifier< otawa::arm::Info * >::copy(), otawa::AbstractIdentifier::initProps(), otawa::ContextualProperty::make(), otawa::script::Script::makeConfig(), otawa::ccg::Builder::processLBlockSet(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), and otawa::ContextualProperty::refProps().
void otawa::PropList::addProps (const PropList & props) inherited
Add all properties from the given property list, in a reverse order.
Parameters
props Property list to clone.
References otawa::Property::copy(), otawa::PropList::head, and otawa::Property::next().
Referenced by otawa::display::CFGDrawer::CFGDrawer(), otawa::display::GraphVizGraph::GraphVizGraph(), otawa::ParamFeature::instantiate(), otawa::Manager::loadXML(), otawa::display::GraphVizGraph::newEdge(), otawa::display::GraphVizGraph::newNode(), otawa::Process::Process(), otawa::display::GraphVizItem::setProps(), otawa::VirtualBasicBlock::VirtualBasicBlock(), and otawa::VirtualCFG::VirtualCFG().
void otawa::PropList::clearProps (void) inherited
Remove all properties from the list.
References otawa::Property::next().
Referenced by otawa::PSTBuilder::getVCFG(), otawa::display::GraphVizItem::setProps(), and otawa::WorkSpace::~WorkSpace().
Processor * otawa::hard::Processor::clone (cstring name = "") const virtual
References Processor().
Referenced by instantiate().
Property * otawa::AbstractIdentifier::copy (Property & prop) const virtual inherited
Build a copy of the given property.
Parameters
prop Property to copy.
Returns
Copy of the property.
Reimplemented in otawa::Identifier< T >, otawa::Identifier< otawa::ccg::Node * >, otawa::Identifier< typename Problem::Domain * >, otawa::Identifier< dfa::BitSet * >, otawa::Identifier< double >, otawa::Identifier< otawa::CFG * >, otawa::Identifier< otawa::ast::AST * >, otawa::Identifier< init_t >, otawa::Identifier< otawa::Microprocessor< ExeNode > * >, otawa::Identifier< otawa::ccg::Collection * >, otawa::Identifier< Domain * >, otawa::Identifier< AbstractParamProcessor * >, otawa::Identifier< otawa::CFGInfo * >, otawa::Identifier< BracketSet * >, otawa::Identifier< elm::io::OutStream * >, otawa::Identifier< otawa::StatInfo * >, otawa::Identifier< int >, otawa::Identifier< T * >, otawa::Identifier< otawa::PropList * >, otawa::Identifier< String >, otawa::Identifier< elm::system::time_t >, otawa::Identifier< display::kind_t >, otawa::Identifier< typename P::Domain * >, otawa::Identifier< Path >, otawa::Identifier< string >, otawa::Identifier< typename otawa::dfa::hai::FirstUnrollingFixPoint::FixPointState * >, otawa::Identifier< CString >, otawa::Identifier< elm::system::Path >, otawa::Identifier< otawa::PCG * >, otawa::Identifier< otawa::BasicBlock * >, otawa::Identifier< Processor * >, otawa::Identifier< otawa::tsim::TreePath< otawa::BasicBlock *, otawa::tsim::BBPath * > * >, otawa::Identifier< log_level_t >, otawa::Identifier< otawa::CEClass * >, otawa::Identifier< bool >, otawa::Identifier< otawa::AbstractParamIdentifier * >, otawa::Identifier< typename otawa::dfa::hai::WideningFixPoint::FixPointState * >, otawa::Identifier< otawa::Progress * >, otawa::Identifier< typename otawa::dfa::hai::DefaultFixPoint::FixPointState * >, otawa::Identifier< typename FixPoint::FixPointState * >, otawa::Identifier< otawa::Symbol * >, otawa::Identifier< otawa::display::ILPSystemAddon * >, otawa::Identifier< AbstractIdentifier * >, otawa::Identifier< elm::io::Output * >, and otawa::Identifier< otawa::arm::Info * >.
Referenced by otawa::AbstractIdentifier::printFormatted().
Property* otawa::AbstractIdentifier::copy (Property * prop) const inline inherited
References otawa::AbstractIdentifier::AbstractIdentifier(), otawa::AbstractIdentifier::copy(), otawa::AbstractIdentifier::initProps(), otawa::AbstractIdentifier::name(), otawa::AbstractIdentifier::serialize(), and otawa::AbstractIdentifier::unserialize().
Referenced by otawa::AbstractIdentifier::copy().
bool otawa::AbstractIdentifier::equals (const Property * prop1, const Property * prop2) const virtual inherited
Test if two properties are equal.
Parameters
prop1 First property.
prop2 Second property.
Returns
True if they are equal, false else.
Referenced by otawa::AbstractIdentifier::printFormatted().
void otawa::hard::Processor::execute (Inst * inst, steps_t & steps) const virtual
Generate the execution steps to execute the given instruction on the current processor.
On VLIW architecture, the given instruction must be the start of bundle and the execute will return the execution steps for the whole bundle.
As a default, apply the processor pipeline direct execution using the dispatch map if there is several functional units. This method may be overload to provide customization in the way the execution steps are generated.
Parameters
inst Instruction (or bundle) to generate execution for.
steps Vector to receive the steps of the instructions.
References _process, otawa::hard::Stage::EXEC, otawa::hard::PipelineUnit::getLatency(), otawa::Process::platform(), queues, otawa::hard::Step::READ, otawa::Inst::readRegSet(), otawa::hard::Step::RELEASE, stages, otawa::hard::Step::WRITE, and otawa::Inst::writeRegSet().
Property * otawa::PropList::extractProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::script::Script::makeConfig().
Property * otawa::PropList::extractProp (const AbstractIdentifier & id) inline inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::PropList::extractProp().
Referenced by otawa::PropList::extractProp().
& otawa::hard::Processor::FIELD (builder) private
AbstractIdentifier * otawa::AbstractIdentifier::find (const string & name) static inherited
Find an abstract identifier by its name.
Parameters
name Name of the looked identifier.
Returns
Found identifier or null.
Referenced by otawa::ProcessorPlugin::getIdentifier(), and otawa::Application::run().
void otawa::AbstractIdentifier::fromString (PropList & props, const string & str) const virtual inherited
Get value of an identifier from a string and store it in the given property list.
Parameters
props Property list to store result into.
str String to get value from.
Reimplemented in otawa::Identifier< T >, otawa::Identifier< otawa::ccg::Node * >, otawa::Identifier< typename Problem::Domain * >, otawa::Identifier< dfa::BitSet * >, otawa::Identifier< double >, otawa::Identifier< otawa::CFG * >, otawa::Identifier< otawa::ast::AST * >, otawa::Identifier< init_t >, otawa::Identifier< otawa::Microprocessor< ExeNode > * >, otawa::Identifier< otawa::ccg::Collection * >, otawa::Identifier< Domain * >, otawa::Identifier< AbstractParamProcessor * >, otawa::Identifier< otawa::CFGInfo * >, otawa::Identifier< BracketSet * >, otawa::Identifier< elm::io::OutStream * >, otawa::Identifier< otawa::StatInfo * >, otawa::Identifier< int >, otawa::Identifier< T * >, otawa::Identifier< otawa::PropList * >, otawa::Identifier< String >, otawa::Identifier< elm::system::time_t >, otawa::Identifier< display::kind_t >, otawa::Identifier< typename P::Domain * >, otawa::Identifier< Path >, otawa::Identifier< string >, otawa::Identifier< typename otawa::dfa::hai::FirstUnrollingFixPoint::FixPointState * >, otawa::Identifier< CString >, otawa::Identifier< elm::system::Path >, otawa::Identifier< otawa::PCG * >, otawa::Identifier< otawa::BasicBlock * >, otawa::Identifier< Processor * >, otawa::Identifier< otawa::tsim::TreePath< otawa::BasicBlock *, otawa::tsim::BBPath * > * >, otawa::Identifier< log_level_t >, otawa::Identifier< otawa::CEClass * >, otawa::Identifier< bool >, otawa::Identifier< otawa::AbstractParamIdentifier * >, otawa::Identifier< typename otawa::dfa::hai::WideningFixPoint::FixPointState * >, otawa::Identifier< otawa::Progress * >, otawa::Identifier< typename otawa::dfa::hai::DefaultFixPoint::FixPointState * >, otawa::Identifier< typename FixPoint::FixPointState * >, otawa::Identifier< otawa::Symbol * >, otawa::Identifier< otawa::display::ILPSystemAddon * >, otawa::Identifier< AbstractIdentifier * >, otawa::Identifier< elm::io::Output * >, otawa::Identifier< otawa::arm::Info * >, and otawa::Identifier< T >.
References otawa::AbstractIdentifier::name().
Referenced by otawa::AbstractIdentifier::printFormatted().
elm::String otawa::hard::Processor::getArch (void) const inline
elm::String otawa::hard::Processor::getBuilder (void) const inline
t::uint64 otawa::hard::Processor::getFrequency (void) const inline
elm::String otawa::hard::Processor::getModel (void) const inline
Property * otawa::PropList::getProp (const AbstractIdentifier * id) const inherited
Find a property by its identifier.
Parameters
id Identifier of the property to find.
Returns
Found property or null.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::Identifier< otawa::arm::Info * >::exists(), otawa::ContextualProperty::exists(), otawa::ContextualProperty::find(), otawa::Identifier< T >::get(), otawa::ContextualProperty::make(), otawa::ParamFeature::matches(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::print(), otawa::ContextualProperty::print(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), otawa::ContextualProperty::refProps(), otawa::Identifier< T >::set(), otawa::Identifier< T >::use(), and otawa::Identifier< T >::value().
const Table<Queue *>& otawa::hard::Processor::getQueues (void) const inline
Referenced by otawa::Microprocessor< N >::Microprocessor(), and otawa::ParExeProc::ParExeProc().
const Table<Stage *>& otawa::hard::Processor::getStages (void) const inline
Referenced by otawa::Microprocessor< N >::Microprocessor(), and otawa::ParExeProc::ParExeProc().
bool otawa::PropList::hasProp (const AbstractIdentifier & id) const inline inherited
Test if the property list contains a property matching the given identifier.
Parameters
id Property identifier to look for.
Returns
True if the list contains the matching property, false else.
References otawa::p::print().
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::Monitor::configure(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::exists(), and otawa::Manager::setVerbosity().
void otawa::AbstractIdentifier::initProps (Property * prop, VarArg & args) protected inherited
Add the properties found in the arguments (list of Property * ended by null) to the identifier properties.
Parameters
prop First property.
args Null-ended properties to scan.
References otawa::PropList::addProp(), and otawa::Property::next().
Referenced by otawa::AbstractIdentifier::AbstractIdentifier(), and otawa::AbstractIdentifier::copy().
void otawa::AbstractIdentifier::initProps (const PropList & props) protected inherited
Initialize properties coming from the constructor.
References otawa::IDENTIFIER_ID, and otawa::AbstractIdentifier::nam.
Processor * otawa::hard::Processor::instantiate (Process * process, cstring name = "") const virtual
Perform a copy a copy of the current processor specialized for the given process.
Parameters
process Process to use.
name Name of the created entity (optional).
References _process, clone(), otawa::hard::Stage::COMMIT, otawa::p::config, otawa::Processor::configure(), otawa::hard::Stage::DECOMP, otawa::hard::Stage::EXEC, otawa::hard::Stage::FETCH, otawa::ProcessorPlugin::getIdentifier(), instantiate(), otawa::hard::Stage::LAZY, load(), otawa::p::init::maker(), proc(), otawa::WorkSpace::process(), process(), otawa::PROCESSOR, Processor(), otawa::hard::PROCESSOR, otawa::PROCESSOR_ELEMENT, otawa::hard::PROCESSOR_FEATURE, otawa::hard::PROCESSOR_ID, otawa::PROCESSOR_PATH, ProcessorProcessor, otawa::p::init::provide(), SERIALIZE(), and VALUE().
Referenced by instantiate().
hard::Processor * otawa::hard::Processor::load (const elm::system::Path & path) throw (LoadException) static
Load a processor descriptor from the given file.
Parameters
path Path to the file.
Exceptions
LoadException Thrown if an error is found.
References Processor().
Referenced by instantiate(), and otawa::hard::Platform::loadProcessor().
hard::Processor * otawa::hard::Processor::load (xom::Element * element) throw (LoadException) static
Load a processor description from an XML element.
Parameters
element XML element to load from.
Exceptions
LoadException Thrown if an error is found.
References Processor().
const elm::String & otawa::AbstractIdentifier::name (void) const inline inherited
Get the string name of the identifier.
Returns
Identifier name.
References otawa::AbstractIdentifier::nam, and otawa::AbstractIdentifier::print().
Referenced by otawa::AlternativeProcessor::AlternativeProcessor(), otawa::AbstractIdentifier::copy(), otawa::AbstractIdentifier::fromString(), otawa::ParamProcessor::instantiate(), otawa::WorkSpace::provide(), otawa::hard::Platform::Identification::split(), and otawa::ParamProcessor::AbstractMaker::~AbstractMaker().
void otawa::AbstractIdentifier::print (elm::io::Output & out) const inherited
Print the identifier.
Parameters
out Output stream.
References otawa::AbstractIdentifier::nam.
Referenced by otawa::display::GraphVizItem::getPropertiesString(), and otawa::AbstractIdentifier::name().
void otawa::AbstractIdentifier::print (elm::io::Output & output, const Property * prop) const virtual inherited
Print the value of the given property (accordint the property matches the given identifier).
It is an error to call this method with a property matching a different identifier.
Use the print() method of a property instead.
Reimplemented in otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< otawa::ccg::Node * >, otawa::Identifier< typename Problem::Domain * >, otawa::Identifier< dfa::BitSet * >, otawa::Identifier< double >, otawa::Identifier< otawa::CFG * >, otawa::Identifier< otawa::ast::AST * >, otawa::Identifier< init_t >, otawa::Identifier< otawa::Microprocessor< ExeNode > * >, otawa::Identifier< otawa::ccg::Collection * >, otawa::Identifier< Domain * >, otawa::Identifier< AbstractParamProcessor * >, otawa::Identifier< otawa::CFGInfo * >, otawa::Identifier< BracketSet * >, otawa::Identifier< elm::io::OutStream * >, otawa::Identifier< otawa::StatInfo * >, otawa::Identifier< int >, otawa::Identifier< T * >, otawa::Identifier< otawa::PropList * >, otawa::Identifier< String >, otawa::Identifier< elm::system::time_t >, otawa::Identifier< display::kind_t >, otawa::Identifier< typename P::Domain * >, otawa::Identifier< Path >, otawa::Identifier< string >, otawa::Identifier< typename otawa::dfa::hai::FirstUnrollingFixPoint::FixPointState * >, otawa::Identifier< CString >, otawa::Identifier< elm::system::Path >, otawa::Identifier< otawa::PCG * >, otawa::Identifier< otawa::BasicBlock * >, otawa::Identifier< Processor * >, otawa::Identifier< otawa::tsim::TreePath< otawa::BasicBlock *, otawa::tsim::BBPath * > * >, otawa::Identifier< log_level_t >, otawa::Identifier< otawa::CEClass * >, otawa::Identifier< bool >, otawa::Identifier< otawa::AbstractParamIdentifier * >, otawa::Identifier< typename otawa::dfa::hai::WideningFixPoint::FixPointState * >, otawa::Identifier< otawa::Progress * >, otawa::Identifier< typename otawa::dfa::hai::DefaultFixPoint::FixPointState * >, otawa::Identifier< typename FixPoint::FixPointState * >, otawa::Identifier< otawa::Symbol * >, otawa::Identifier< otawa::display::ILPSystemAddon * >, otawa::Identifier< AbstractIdentifier * >, otawa::Identifier< elm::io::Output * >, and otawa::Identifier< otawa::arm::Info * >.
void otawa::AbstractIdentifier::print (elm::io::Output & output, const Property & prop) const inline inherited
References otawa::AbstractIdentifier::print(), and otawa::AbstractIdentifier::printFormatted().
Referenced by otawa::AbstractIdentifier::print().
void otawa::AbstractIdentifier::printFormatted (io::Output & out, const Property * prop) const virtual inherited
Print the value of the given property in a formatted way, that is, possibly to perform re-scanning after.
For example, string are quoted and special character escaped.
Parameters
out Output to use.
prop Property to display.
Reimplemented in otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< otawa::ccg::Node * >, otawa::Identifier< typename Problem::Domain * >, otawa::Identifier< dfa::BitSet * >, otawa::Identifier< double >, otawa::Identifier< otawa::CFG * >, otawa::Identifier< otawa::ast::AST * >, otawa::Identifier< init_t >, otawa::Identifier< otawa::Microprocessor< ExeNode > * >, otawa::Identifier< otawa::ccg::Collection * >, otawa::Identifier< Domain * >, otawa::Identifier< AbstractParamProcessor * >, otawa::Identifier< otawa::CFGInfo * >, otawa::Identifier< BracketSet * >, otawa::Identifier< elm::io::OutStream * >, otawa::Identifier< otawa::StatInfo * >, otawa::Identifier< int >, otawa::Identifier< T * >, otawa::Identifier< otawa::PropList * >, otawa::Identifier< String >, otawa::Identifier< elm::system::time_t >, otawa::Identifier< display::kind_t >, otawa::Identifier< typename P::Domain * >, otawa::Identifier< Path >, otawa::Identifier< string >, otawa::Identifier< typename otawa::dfa::hai::FirstUnrollingFixPoint::FixPointState * >, otawa::Identifier< CString >, otawa::Identifier< elm::system::Path >, otawa::Identifier< otawa::PCG * >, otawa::Identifier< otawa::BasicBlock * >, otawa::Identifier< Processor * >, otawa::Identifier< otawa::tsim::TreePath< otawa::BasicBlock *, otawa::tsim::BBPath * > * >, otawa::Identifier< log_level_t >, otawa::Identifier< otawa::CEClass * >, otawa::Identifier< bool >, otawa::Identifier< otawa::AbstractParamIdentifier * >, otawa::Identifier< typename otawa::dfa::hai::WideningFixPoint::FixPointState * >, otawa::Identifier< otawa::Progress * >, otawa::Identifier< typename otawa::dfa::hai::DefaultFixPoint::FixPointState * >, otawa::Identifier< typename FixPoint::FixPointState * >, otawa::Identifier< otawa::Symbol * >, otawa::Identifier< otawa::display::ILPSystemAddon * >, otawa::Identifier< AbstractIdentifier * >, otawa::Identifier< elm::io::Output * >, and otawa::Identifier< otawa::arm::Info * >.
Referenced by otawa::AbstractIdentifier::print().
void otawa::AbstractIdentifier::printFormatted (elm::io::Output & output, const Property & prop) const inline inherited
References otawa::AbstractIdentifier::copy(), otawa::AbstractIdentifier::equals(), otawa::AbstractIdentifier::fromString(), otawa::AbstractIdentifier::printFormatted(), and otawa::AbstractIdentifier::type().
Referenced by otawa::AbstractIdentifier::printFormatted().
Process* otawa::hard::Processor::process (void) const inline protected
Referenced by instantiate().
void otawa::PropList::removeAllProp (const AbstractIdentifier * id) inherited
Remove all the properties matching the given identifier.
Parameters
id Identifier of properties to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::LoopUnroller::unroll().
void otawa::PropList::removeProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier.
Parameters
id Identifier of the property to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::PSTBuilder::buildTree(), otawa::BBRemover< T >::clean(), otawa::CFGBuilder::cleanup(), otawa::display::CFGOutput::processCFG(), otawa::SubCFGBuilder::processWorkSpace(), otawa::Identifier< otawa::arm::Info * >::remove(), and otawa::ContextualPath::Ref< T >::remove().
void otawa::PropList::removeProp (const AbstractIdentifier & id) inline inherited
References otawa::PropList::removeProp().
Referenced by otawa::PropList::removeProp().
void otawa::AbstractIdentifier::serialize (Property * prop, elm::serial2::Serializer & serializer) virtual inherited
Serialize the workspace to the current serializer.
In the default implementation, do nothing.
Parameters
prop Property containing the value to serialize.
serializer Serializer to serialize to.
Referenced by otawa::AbstractIdentifier::copy().
void otawa::PropList::setProp (Property * prop) inherited
Set the property in the property list removing any double.
Parameters
prop Property to set.
References otawa::Property::_next, otawa::Property::id(), and otawa::Property::next().
void otawa::PropList::setProp (const AbstractIdentifier * id) inline inherited
References otawa::PropList::setProp().
Referenced by otawa::PropList::setProp().
const Type & otawa::AbstractIdentifier::type (void) const virtual inherited
Get the identifier of data linked with this property.
It may return Type::no_type ever meaning that the identifier does not support type system or that it is just a flag without associated data.
Returns
Type of the associated data.
Reimplemented in otawa::Identifier< T >, otawa::Identifier< otawa::ccg::Node * >, otawa::Identifier< typename Problem::Domain * >, otawa::Identifier< dfa::BitSet * >, otawa::Identifier< double >, otawa::Identifier< otawa::CFG * >, otawa::Identifier< otawa::ast::AST * >, otawa::Identifier< init_t >, otawa::Identifier< otawa::Microprocessor< ExeNode > * >, otawa::Identifier< otawa::ccg::Collection * >, otawa::Identifier< Domain * >, otawa::Identifier< AbstractParamProcessor * >, otawa::Identifier< otawa::CFGInfo * >, otawa::Identifier< BracketSet * >, otawa::Identifier< elm::io::OutStream * >, otawa::Identifier< otawa::StatInfo * >, otawa::Identifier< int >, otawa::Identifier< T * >, otawa::Identifier< otawa::PropList * >, otawa::Identifier< String >, otawa::Identifier< elm::system::time_t >, otawa::Identifier< display::kind_t >, otawa::Identifier< typename P::Domain * >, otawa::Identifier< Path >, otawa::Identifier< string >, otawa::Identifier< typename otawa::dfa::hai::FirstUnrollingFixPoint::FixPointState * >, otawa::Identifier< CString >, otawa::Identifier< elm::system::Path >, otawa::Identifier< otawa::PCG * >, otawa::Identifier< otawa::BasicBlock * >, otawa::Identifier< Processor * >, otawa::Identifier< otawa::tsim::TreePath< otawa::BasicBlock *, otawa::tsim::BBPath * > * >, otawa::Identifier< log_level_t >, otawa::Identifier< otawa::CEClass * >, otawa::Identifier< bool >, otawa::Identifier< otawa::AbstractParamIdentifier * >, otawa::Identifier< typename otawa::dfa::hai::WideningFixPoint::FixPointState * >, otawa::Identifier< otawa::Progress * >, otawa::Identifier< typename otawa::dfa::hai::DefaultFixPoint::FixPointState * >, otawa::Identifier< typename FixPoint::FixPointState * >, otawa::Identifier< otawa::Symbol * >, otawa::Identifier< otawa::display::ILPSystemAddon * >, otawa::Identifier< AbstractIdentifier * >, otawa::Identifier< elm::io::Output * >, and otawa::Identifier< otawa::arm::Info * >.
References otawa::Type::no_type.
Referenced by otawa::AbstractIdentifier::printFormatted().
Property * otawa::AbstractIdentifier::unserialize (elm::serial2::Unserializer & unserializer) virtual inherited
Unserialize the workspace to the current unserializer.
In the default implementation, do nothing.
Parameters
unserializer Unserializer to unserialize to.
Returns
Property result of unserialization, null if the property cannot be unserialized.
Referenced by otawa::AbstractIdentifier::copy().
Friends And Related Function Documentation
friend class ProcessorProcessor friend
Referenced by instantiate().
Member Data Documentation
Process* otawa::hard::Processor::_process private
Referenced by execute(), and instantiate().
string otawa::hard::Processor::arch private
string otawa::hard::Processor::builder private
const PropList otawa::PropList::EMPTY static inherited
This is an empty proplist for convenience.
Referenced by otawa::DynProcessor::configure(), otawa::ActualFeature::processor(), otawa::SilentFeature::SilentFeature(), otawa::Processor::version(), and otawa::display::Driver::~Driver().
t::uint64 otawa::hard::Processor::frequency private
string otawa::hard::Processor::model private
const Processor otawa::hard::Processor::null static
Null processor: no stage, no queue.
Referenced by otawa::GraphBBTime< G >::processWorkSpace(), and ~Processor().
AllocatedTable<Queue *> otawa::hard::Processor::queues private
Referenced by execute(), and Processor().
AllocatedTable<Stage *> otawa::hard::Processor::stages private
Referenced by execute(), and Processor().
The documentation for this class was generated from the following files:
include/otawa/hard/Processor.h
src/prog/hard_Processor.cpp