Otawa: otawa::LockedProperty< T > Class Template Reference
otawa::LockedProperty< T > Class Template Reference
Properties System
This class is used for building a lock property, that is, for taking pointer values implementing the elm::Locked class.
#include <otawa/prop/Property.h>
Public Member Functions
LockedProperty (const AbstractIdentifier *id, T value)
Build a new locked property.
LockedProperty (const AbstractIdentifier &id, T value)
Build a new locked property with a static identifier.
LockedProperty (elm::CString name, T value)
Build a new locked property with a named identifier.
const T & value (void) const
Get the value of the property.
T & value (void)
Get the value of the property.
const AbstractIdentifier * id (void) const
Get the identifier code of the property.
Property * next (void) const
Get the next property.
template<class T >
const T & get (void) const
template<class T >
void set (const T &value)
virtual void print (elm::io::Output &out) const
Print the given property, that is, the identifier and its value if any.
Static Public Member Functions
static GenericProperty< T > * make (const AbstractIdentifier *id, const T &value)
Build a new generic property with the given data.
static const AbstractIdentifier * getID (elm::CString name)
Allocate a new identifier matching the given name.
Protected Member Functions
virtual ~LockedProperty (void)
virtual Property * copy (void)
This method is called when a property is copied.
Detailed Description
template<class T>
class otawa::LockedProperty< T >
This class is used for building a lock property, that is, for taking pointer values implementing the elm::Locked class.
It provides management of the lock along the life of the property: creation, copy and deletion.
Parameters
T Type of the date stored in the property.
Constructor & Destructor Documentation
template<class T > virtual otawa::LockedProperty< T >::~LockedProperty (void) inline protected virtual
References otawa::GenericProperty< T >::value().
template<class T > otawa::LockedProperty< T >::LockedProperty (const AbstractIdentifier * id, T _value) inline
Build a new locked property.
Parameters
id Property identifier.
_value Lock pointer value.
References otawa::GenericProperty< T >::value().
template<class T > otawa::LockedProperty< T >::LockedProperty (const AbstractIdentifier & id, T _value) inline
Build a new locked property with a static identifier.
Parameters
id Property identifier.
_value Lock pointer value.
References otawa::GenericProperty< T >::value().
template<class T > otawa::LockedProperty< T >::LockedProperty (elm::CString name, T _value) inline
Build a new locked property with a named identifier.
Parameters
name Property identifier name.
_value Lock pointer value.
References otawa::GenericProperty< T >::value().
Member Function Documentation
template<class T > virtual Property* otawa::LockedProperty< T >::copy (void) inline protected virtual
This method is called when a property is copied.
It may be specialized by Property class children.
Returns
Copy of the current property.
Reimplemented from otawa::GenericProperty< T >.
References otawa::Property::id(), and otawa::GenericProperty< T >::value().
template<class T > const T & otawa::Property::get (void) const inline inherited
const AbstractIdentifier * otawa::Property::getID (elm::CString name) static inherited
Allocate a new identifier matching the given name.
Note that, if an identifier exists with the same name, its code will be returned ensuring consistency between name and code for identifiers.
Parameters
name Name of the identifier.
Returns
Allocated identifier code.
References otawa::display::find().
const Identifier * otawa::Property::id (void) const inline inherited
Get the identifier code of the property.
Returns
Identifier code.
Referenced by otawa::GenericProperty< T >::copy(), otawa::LockedProperty< T >::copy(), and otawa::PropList::setProp().
template<class T> GenericProperty< T > * otawa::GenericProperty< T >::make (const AbstractIdentifier * id, const T & value) inline static inherited
Build a new generic property with the given data.
Defining the constructor as is, allows replacing the default building behaviour by specialized ones.
Parameters
id Identifier of the property.
value Value of the property.
Returns
Built property.
References otawa::GenericProperty< T >::GenericProperty().
Referenced by otawa::Identifier< otawa::arm::Info * >::copy(), and otawa::Identifier< T >::ref().
Property * otawa::Property::next (void) const inline inherited
Get the next property.
Returns
Next property.
References otawa::p::print().
Referenced by otawa::PropList::addProps(), otawa::PropList::clearProps(), otawa::PropList::extractProp(), otawa::PropList::getProp(), otawa::AbstractIdentifier::initProps(), otawa::PropList::Iter::next(), otawa::PropList::removeAllProp(), otawa::PropList::removeProp(), and otawa::PropList::setProp().
void otawa::Property::print (elm::io::Output & out) const virtual inherited
Print the given property, that is, the identifier and its value if any.
Parameters
out Output to use.
References otawa::END().
Referenced by otawa::operator<<().
template<class T > void otawa::Property::set (const T & value) inline inherited
References otawa::GenericProperty< T >::value().
template<class T> const T & otawa::GenericProperty< T >::value (void) const inline inherited
Get the value of the property.
Returns
Value of the property.
References otawa::GenericProperty< T >::_value.
Referenced by otawa::GenericProperty< T >::copy(), otawa::LockedProperty< T >::copy(), otawa::LockedProperty< T >::LockedProperty(), otawa::Identifier< T >::ref(), otawa::Property::set(), otawa::DeletableProperty< T >::~DeletableProperty(), and otawa::LockedProperty< T >::~LockedProperty().
template<class T> T & otawa::GenericProperty< T >::value (void) inline inherited
Get the value of the property.
Returns
Value of the property.
References otawa::GenericProperty< T >::_value.
The documentation for this class was generated from the following files:
include/otawa/prop/Property.h
src/prog/prop_Property.cpp