Otawa: otawa::stack::Iter Class Reference
otawa::stack::Iter Class Reference
Iterator on the result of stack analysis.
#include <otawa/stack/features.h>
Public Member Functions
Iter (WorkSpace *ws)
Value getReg (int i)
Value getMem (Value addr, int size)
void start (BasicBlock *bb)
void next (void)
void nextInst (void)
void toEnd (void)
bool ended (void) const
Inst * instruction (void) const
sem::inst item (void) const
Manager::t state (void)
Get the state matching the current point.
Private Attributes
Manager * man
Detailed Description
Iterator on the result of stack analysis.
Constructor & Destructor Documentation
otawa::stack::Iter::Iter (WorkSpace * ws)
Referenced by otawa::stack::Manager::updatePath().
Member Function Documentation
bool otawa::sem::StateIter< Manager >::ended (void) const inline inherited
References otawa::sem::BBIter::ended(), and otawa::sem::StateIter< S >::i.
Value otawa::stack::Iter::getMem (Value addr, int size) inline
Value otawa::stack::Iter::getReg (int i) inline
Referenced by otawa::stack::Manager::updatePath().
Inst* otawa::sem::StateIter< Manager >::instruction (void) const inline inherited
References otawa::sem::StateIter< S >::i, and otawa::sem::BBIter::instruction().
sem::inst otawa::sem::StateIter< Manager >::item (void) const inline inherited
References otawa::sem::StateIter< S >::i.
void otawa::sem::StateIter< Manager >::next (void) inline inherited
References otawa::sem::BBIter::ended(), otawa::sem::StateIter< S >::es, otawa::sem::StateIter< S >::i, otawa::sem::BBIter::isCond(), otawa::sem::StateIter< S >::man, otawa::sem::BBIter::next(), otawa::sem::BBIter::pathEnd(), otawa::sem::StateIter< S >::s, and otawa::sem::StateIter< S >::ss.
void otawa::sem::StateIter< Manager >::nextInst (void) inline inherited
References otawa::sem::StateIter< S >::i, otawa::sem::BBIter::instEnd(), and otawa::sem::StateIter< S >::next().
void otawa::sem::StateIter< Manager >::start (BasicBlock * bb) inline inherited
References otawa::sem::StateIter< S >::es, otawa::sem::StateIter< S >::i, otawa::sem::StateIter< S >::man, otawa::sem::StateIter< S >::s, otawa::sem::StateIter< S >::ss, and otawa::sem::BBIter::start().
Manager ::t otawa::sem::StateIter< Manager >::state (void) inline inherited
Get the state matching the current point.
References otawa::sem::StateIter< S >::s.
void otawa::sem::StateIter< Manager >::toEnd (void) inline inherited
References otawa::sem::BBIter::ended(), otawa::sem::StateIter< S >::i, and otawa::sem::StateIter< S >::next().
Member Data Documentation
Manager* otawa::stack::Iter::man private
The documentation for this class was generated from the following files:
include/otawa/stack/features.h
src/prog/util_StackAnalysis.cpp