Otawa: otawa::MUSTPERS::Domain Class Reference
otawa::MUSTPERS::Domain Class Reference
#include <otawa/cache/cat2/MUSTPERS.h>
Public Member Functions
Domain (const int _size, const int _A)
Domain (const Domain &source)
Domain (const MUSTProblem::Domain &m, const PERSProblem::Domain &p)
Domain & operator= (const Domain &src)
const MUSTProblem::Domain & getMust (void) const
const PERSProblem::Domain & getPers (void) const
void lub (const Domain &dom)
int getSize (void)
bool equals (const Domain &dom) const
void empty ()
bool mustContains (const int id)
bool persContains (const int id, const int index)
bool isWiped (const int id, const int index)
bool isPersistent (const int id, const int index)
void inject (const int id)
void print (elm::io::Output &output) const
Private Attributes
PERSProblem::Domain pers
MUSTProblem::Domain must
Friends
class MUSTPERS
Constructor & Destructor Documentation
otawa::MUSTPERS::Domain::Domain (const int _size, const int _A) inline
otawa::MUSTPERS::Domain::Domain (const Domain & source) inline
otawa::MUSTPERS::Domain::Domain (const MUSTProblem::Domain & m, const PERSProblem::Domain & p) inline
Member Function Documentation
void otawa::MUSTPERS::Domain::empty () inline
References otawa::MUSTProblem::Domain::empty(), otawa::PERSProblem::Domain::empty(), must, and pers.
bool otawa::MUSTPERS::Domain::equals (const Domain & dom) const inline
References otawa::MUSTProblem::Domain::equals(), otawa::PERSProblem::Domain::equals(), must, and pers.
Referenced by otawa::MUSTPERS::equals().
const MUSTProblem::Domain& otawa::MUSTPERS::Domain::getMust (void) const inline
References must.
const PERSProblem::Domain& otawa::MUSTPERS::Domain::getPers (void) const inline
References pers.
int otawa::MUSTPERS::Domain::getSize (void) inline
References otawa::MUSTProblem::Domain::getSize(), and must.
void otawa::MUSTPERS::Domain::inject (const int id) inline
References otawa::MUSTProblem::Domain::inject(), otawa::PERSProblem::Domain::inject(), must, and pers.
Referenced by otawa::MUSTPERS::update().
bool otawa::MUSTPERS::Domain::isPersistent (const int id, const int index) inline
References otawa::PERSProblem::Domain::isPersistent(), and pers.
bool otawa::MUSTPERS::Domain::isWiped (const int id, const int index) inline
References otawa::PERSProblem::Domain::isWiped(), and pers.
void otawa::MUSTPERS::Domain::lub (const Domain & dom) inline
References otawa::MUSTProblem::Domain::lub(), otawa::PERSProblem::Domain::lub(), must, and pers.
Referenced by otawa::MUSTPERS::lub().
bool otawa::MUSTPERS::Domain::mustContains (const int id) inline
References otawa::MUSTProblem::Domain::contains(), and must.
Domain& otawa::MUSTPERS::Domain::operator= (const Domain & src) inline
References must, and pers.
bool otawa::MUSTPERS::Domain::persContains (const int id, const int index) inline
References otawa::PERSProblem::Domain::contains(), and pers.
void otawa::MUSTPERS::Domain::print (elm::io::Output & output) const inline
References must, pers, otawa::MUSTProblem::Domain::print(), and otawa::PERSProblem::Domain::print().
Referenced by otawa::operator<<().
Friends And Related Function Documentation
friend class MUSTPERS friend
Member Data Documentation
MUSTProblem::Domain otawa::MUSTPERS::Domain::must private
Referenced by empty(), otawa::MUSTPERS::enterContext(), equals(), getMust(), getSize(), inject(), otawa::MUSTPERS::leaveContext(), lub(), mustContains(), otawa::MUSTPERS::MUSTPERS(), operator=(), and print().
PERSProblem::Domain otawa::MUSTPERS::Domain::pers private
Referenced by empty(), otawa::MUSTPERS::enterContext(), equals(), getPers(), inject(), isPersistent(), isWiped(), otawa::MUSTPERS::leaveContext(), lub(), otawa::MUSTPERS::MUSTPERS(), operator=(), persContains(), and print().
The documentation for this class was generated from the following file:
include/otawa/cache/cat2/MUSTPERS.h