Otawa: otawa::hard::Memory Class Reference
otawa::hard::Memory Class Reference
Platform Description
Class to represent the whole memory of the platform.
#include <otawa/hard/Memory.h>
Public Member Functions
Memory (bool full=false)
Memory constructor.
virtual ~Memory (void)
const Table< const Bank * > & banks (void) const
Get the list of banks in memory.
const Table< const Bus * > & buses (void) const
Get the list of buses connected to memory banks.
const Bank * get (Address address) const
Get the bank matching the given address.
int worstAccess (void) const
Compute the worst access latency.
int worstReadAccess (void) const
Compute the worst read access latency.
int worstWriteAccess (void) const
Compute the worst read access latency.
Static Public Member Functions
static Memory * load (const elm::system::Path &path) throw (LoadException)
Load a memory configuration from an XML file.
static Memory * load (xom::Element *element) throw (LoadException)
Static Public Attributes
static const Memory null
Default null memory.
static const Memory full
Full memory: all memory is occupied by big RAM bank.
Private Member Functions
SERIALIZABLE (Memory, field("banks", _banks)&field("buses", _buses))
Private Attributes
AllocatedTable< const Bank * > _banks
AllocatedTable< const Bus * > _buses
Detailed Description
Class to represent the whole memory of the platform.
Author
H. Cassé casse.nosp@m.@iri.nosp@m.t.fr
Constructor & Destructor Documentation
otawa::hard::Memory::Memory (bool full = false)
Memory constructor.
References otawa::hard::Bank::full.
otawa::hard::Memory::~Memory (void) virtual
Member Function Documentation
const Table< const Bank * > & otawa::hard::Memory::banks (void) const inline
Get the list of banks in memory.
Returns
List of memory banks.
Referenced by otawa::dcache::BlockBuilder::processBB(), otawa::hard::Dumper::processWorkSpace(), otawa::clp::Analysis::processWorkSpace(), and otawa::etime::StandardEventBuilder::setup().
const Table< const Bus * > & otawa::hard::Memory::buses (void) const inline
Get the list of buses connected to memory banks.
Returns
List of memory buses.
References otawa::ot::address(), and otawa::sem::load().
const Bank * otawa::hard::Memory::get (Address address) const
Get the bank matching the given address.
Parameters
address Address to find bank for.
Returns
Found bank or null.
References otawa::hard::Bank::contains(), and load().
Referenced by otawa::ccg::LBlockBuilder::addLBlock(), otawa::LBlockBuilder::addLBlock(), otawa::etime::StandardEventBuilder::costOf(), otawa::dcache::WCETFunctionBuilder::processBB(), otawa::dcache::CLPBlockBuilder::processBB(), and otawa::dcache::BlockBuilder::processBB().
Memory * otawa::hard::Memory::load (const elm::system::Path & path) throw (LoadException) static
Load a memory configuration from an XML file.
Parameters
path Path to the file.
Returns
Built cache configuration.
Referenced by get(), otawa::hard::Platform::loadMemory(), and worstWriteAccess().
static Memory* otawa::hard::Memory::load (xom::Element * element) throw (LoadException) static
otawa::hard::Memory::SERIALIZABLE (Memory , field("banks", _banks)&field("buses", _buses)) private
int otawa::hard::Memory::worstAccess (void) const
Compute the worst access latency.
Returns
Worst access latency.
References otawa::clp::max().
int otawa::hard::Memory::worstReadAccess (void) const
Compute the worst read access latency.
Returns
Worst read access latency.
References otawa::hard::Bank::latency(), and otawa::clp::max().
Referenced by otawa::etime::StandardEventBuilder::processBB(), and otawa::dcache::WCETFunctionBuilder::setup().
int otawa::hard::Memory::worstWriteAccess (void) const
Compute the worst read access latency.
Returns
Worst read access latency.
References otawa::p::config, otawa::Processor::configure(), load(), otawa::p::init::maker(), otawa::clp::max(), otawa::hard::MEMORY, otawa::MEMORY_ELEMENT, otawa::hard::MEMORY_FEATURE, otawa::MEMORY_OBJECT, otawa::MEMORY_PATH, otawa::p::init::provide(), and otawa::hard::Bank::writeLatency().
Referenced by otawa::etime::StandardEventBuilder::processBB(), and otawa::dcache::WCETFunctionBuilder::setup().
Member Data Documentation
AllocatedTable<const Bank *> otawa::hard::Memory::_banks private
AllocatedTable<const Bus *> otawa::hard::Memory::_buses private
const Memory otawa::hard::Memory::full static
Full memory: all memory is occupied by big RAM bank.
Referenced by otawa::hard::Bank::Bank().
const Memory otawa::hard::Memory::null static
Default null memory.
Referenced by otawa::hard::Bank::Bank().
The documentation for this class was generated from the following files:
include/otawa/hard/Memory.h
src/prog/hard_Memory.cpp