Otawa: otawa::MAYProblem Class Reference
otawa::MAYProblem Class Reference
#include <otawa/cache/cat2/MAYProblem.h>
Classes
class Domain
Public Member Functions
MAYProblem (const int _size, LBlockSet *_lbset, WorkSpace *_fw, const hard::Cache *_cache, const int _A)
~MAYProblem ()
const Domain & bottom (void) const
const Domain & entry (void) const
void lub (Domain &a, const Domain &b) const
void assign (Domain &a, const Domain &b) const
bool equals (const Domain &a, const Domain &b) const
void update (Domain &out, const Domain &in, BasicBlock *bb)
void enterContext (Domain &dom, BasicBlock *header, util::hai_context_t ctx)
void leaveContext (Domain &dom, BasicBlock *header, util::hai_context_t ctx)
Public Attributes
Domain callstate
Private Attributes
LBlockSet * lbset
WorkSpace * fw
const int line
const hard::Cache * cache
Domain bot
Domain ent
Constructor & Destructor Documentation
MAYProblem::MAYProblem (const int _size, LBlockSet * _lbset, WorkSpace * _fw, const hard::Cache * _cache, const int _A)
References otawa::MAYProblem::Domain::empty(), and ent.
MAYProblem::~MAYProblem ()
Member Function Documentation
void otawa::MAYProblem::assign (Domain & a, const Domain & b) const inline
Referenced by update().
const MAYProblem::Domain & MAYProblem::bottom (void) const
References bot.
void otawa::MAYProblem::enterContext (Domain & dom, BasicBlock * header, util::hai_context_t ctx) inline
const MAYProblem::Domain & MAYProblem::entry (void) const
References ent.
bool otawa::MAYProblem::equals (const Domain & a, const Domain & b) const inline
References otawa::cfgio::bb(), otawa::MAYProblem::Domain::equals(), and update().
void otawa::MAYProblem::leaveContext (Domain & dom, BasicBlock * header, util::hai_context_t ctx) inline
References otawa::operator<<().
void otawa::MAYProblem::lub (Domain & a, const Domain & b) const inline
References otawa::MAYProblem::Domain::lub().
void MAYProblem::update (Domain & out, const Domain & in, BasicBlock * bb)
References assign(), otawa::LBlock::cacheblock(), otawa::MAYProblem::Domain::inject(), otawa::LAST_LBLOCK, and line.
Referenced by equals().
Member Data Documentation
Domain otawa::MAYProblem::bot private
Referenced by bottom().
const hard::Cache* otawa::MAYProblem::cache private
Domain otawa::MAYProblem::callstate
Domain otawa::MAYProblem::ent private
Referenced by entry(), and MAYProblem().
WorkSpace* otawa::MAYProblem::fw private
LBlockSet* otawa::MAYProblem::lbset private
const int otawa::MAYProblem::line private
Referenced by update().
The documentation for this class was generated from the following files:
include/otawa/cache/cat2/MAYProblem.h
src/prog/cache_MAYProblem.cpp