Otawa: otawa::BasicBlock::BundleIter Class Reference
otawa::BasicBlock::BundleIter Class Reference
CFG (Control Flow Graph)
Iterator on bundles composing a basic block.
#include <otawa/cfg/BasicBlock.h>
Public Member Functions
BundleIter (void)
BundleIter (BasicBlock *bb)
bool ended (void) const
const Bundle & item (void) const
void next (void)
Private Attributes
Bundle b
Address top
Detailed Description
Iterator on bundles composing a basic block.
See also
VLIW Support
Constructor & Destructor Documentation
otawa::BasicBlock::BundleIter::BundleIter (void) inline
otawa::BasicBlock::BundleIter::BundleIter (BasicBlock * bb) inline
References otawa::BasicBlock::firstInst(), otawa::BasicBlock::isEnd(), and otawa::BasicBlock::topAddress().
Member Function Documentation
bool otawa::BasicBlock::BundleIter::ended (void) const inline
const Bundle& otawa::BasicBlock::BundleIter::item (void) const inline
void otawa::BasicBlock::BundleIter::next (void) inline
Member Data Documentation
Bundle otawa::BasicBlock::BundleIter::b private
Address otawa::BasicBlock::BundleIter::top private
The documentation for this class was generated from the following file:
include/otawa/cfg/BasicBlock.h