Otawa: otawa::ParExeProc Class Reference
otawa::ParExeProc Class Reference
Parametric Execution Graph
Représentation of a processor (to be used to build a ParExeGraph).
#include <otawa/parexegraph/ParExeProc.h>
Classes
class QueueIterator
Iterator for the instruction queues.
Public Types
enum instruction_category_t {
IALU = 0, FALU = 1, MEMORY = 2, CONTROL = 3,
MUL = 4, DIV = 5, INST_CATEGORY_NUMBER
}
typedef enum otawa::ParExeProc::instruction_category_t instruction_category_t
Public Member Functions
ParExeProc (const hard::Processor *proc)
Constructor.
void addQueue (elm::String name, int size)
Add an instruction queue to the processor.
ParExeQueue * queue (int index)
Returns a pointer to the queue specified by index.
void setFetchStage (ParExeStage *stage)
Declares a stage as the fetch stage (it will undergo a special processing when building a ParExeGraph).
ParExeStage * fetchStage (void)
void setExecStage (ParExeStage *stage)
Declares a stage as the execution stage (it will undergo a special processing when building a ParExeGraph).
ParExeStage * execStage (void)
ParExeStage * lastStage (void)
bool isLastStage (ParExeStage *stage)
ParExePipeline * pipeline ()
elm::genstruct::SLList< ParExeStage * > * listOfInorderStages ()
Private Attributes
elm::genstruct::Vector< ParExeQueue * > _queues
ParExePipeline _pipeline
elm::genstruct::SLList< ParExeStage * > _inorder_stages
ParExeStage * _fetch_stage
ParExeStage * _exec_stage
Detailed Description
Représentation of a processor (to be used to build a ParExeGraph).
A processor is a pipeline, with a number of stages, among which a fetch stage and an execution stage, and a set of instruction queues.
See also
Parametric Execution Graph
Member Typedef Documentation
typedef enum otawa::ParExeProc::instruction_category_t otawa::ParExeProc::instruction_category_t
Member Enumeration Documentation
enum otawa::ParExeProc::instruction_category_t
Enumerator
IALU
FALU
MEMORY
CONTROL
MUL
DIV
INST_CATEGORY_NUMBER
Constructor & Destructor Documentation
otawa::ParExeProc::ParExeProc (const hard::Processor * proc)
Constructor.
Parameters
Description of the processor.
References _inorder_stages, _pipeline, otawa::ParExeStage::addBinding(), otawa::ParExeStage::addFunctionalUnit(), addQueue(), otawa::ParExePipeline::addStage(), otawa::ParExeStage::COMMIT, otawa::hard::Stage::COMMIT, otawa::ParExeStage::DECODE, otawa::hard::Stage::EXEC, otawa::ParExeStage::EXECUTE, otawa::ParExeStage::FETCH, otawa::hard::Stage::FETCH, otawa::ParExePipeline::firstStage(), otawa::ParExeStage::fu(), otawa::hard::Stage::getDispatch(), otawa::hard::Stage::getFUs(), otawa::hard::PipelineUnit::getLatency(), otawa::hard::PipelineUnit::getName(), otawa::hard::Processor::getQueues(), otawa::hard::Processor::getStages(), otawa::hard::Stage::getType(), otawa::hard::PipelineUnit::getWidth(), otawa::ParExeStage::hasNodes(), otawa::ParExeStage::IN_ORDER, otawa::hard::FunctionalUnit::isPipelined(), otawa::hard::Stage::LAZY, otawa::ParExeStage::numFus(), otawa::ParExePipeline::numStages(), otawa::ParExeStage::OUT_OF_ORDER, queue(), setExecStage(), and setFetchStage().
Member Function Documentation
void otawa::ParExeProc::addQueue (elm::String name, int size) inline
Add an instruction queue to the processor.
Parameters
name Name of the queue.
size Size (capacity) of the queue.
Referenced by ParExeProc().
ParExeStage * otawa::ParExeProc::execStage (void) inline
Returns
Pointer to the execution stage (must have been set beforehand).
Referenced by otawa::ParExeGraph::addEdgesForDataDependencies(), and otawa::ParExeGraph::addEdgesForMemoryOrder().
ParExeStage * otawa::ParExeProc::fetchStage (void) inline
Returns
Pointer to the fetch stage (must have been set beforehand).
Referenced by otawa::ParExeGraph::addEdgesForFetch().
bool otawa::ParExeProc::isLastStage (ParExeStage * stage) inline
Parameters
stage Pointer to a stage.
Returns
True if the stage is the last in the pipeline.
References otawa::ParExePipeline::lastStage().
ParExeStage* otawa::ParExeProc::lastStage (void) inline
References otawa::ParExePipeline::lastStage().
Referenced by otawa::GraphBBTime< G >::FillSequence().
elm::genstruct::SLList<ParExeStage *>* otawa::ParExeProc::listOfInorderStages () inline
Referenced by otawa::ParExeGraph::addEdgesForProgramOrder().
ParExePipeline * otawa::ParExeProc::pipeline () inline
Returns
Pointer to the pipeline.
Referenced by otawa::ParExeGraph::addEdgesForQueues(), otawa::GraphBBTime< G >::BuildVectorOfHwResources(), otawa::ParExeGraph::createNodes(), otawa::ParExeGraph::delta(), otawa::ParExeGraph::findContendingNodes(), otawa::ResourceList::ResourceList(), and otawa::ParExeGraph::~ParExeGraph().
ParExeQueue * otawa::ParExeProc::queue (int index) inline
Returns a pointer to the queue specified by index.
Queues are numbered when they are added to the processor.
Parameters
index Index of the queue.
Returns
Pointer to the indexed queue.
Referenced by ParExeProc().
void otawa::ParExeProc::setExecStage (ParExeStage * stage) inline
Declares a stage as the execution stage (it will undergo a special processing when building a ParExeGraph).
Parameters
stage Pointer to the stage.
Referenced by ParExeProc().
void otawa::ParExeProc::setFetchStage (ParExeStage * stage) inline
Declares a stage as the fetch stage (it will undergo a special processing when building a ParExeGraph).
Parameters
stage Pointer to the stage.
Referenced by ParExeProc().
Member Data Documentation
ParExeStage* otawa::ParExeProc::_exec_stage private
ParExeStage* otawa::ParExeProc::_fetch_stage private
elm::genstruct::SLList<ParExeStage *> otawa::ParExeProc::_inorder_stages private
Referenced by ParExeProc().
ParExePipeline otawa::ParExeProc::_pipeline private
Referenced by ParExeProc().
elm::genstruct::Vector<ParExeQueue *> otawa::ParExeProc::_queues private
The documentation for this class was generated from the following files:
include/otawa/parexegraph/ParExeProc.h
src/prog/parexegraph_ParExeProc.cpp