Otawa: otawa::graph::Edge Class Reference
otawa::graph::Edge Class Reference
This class represents a directed edge between two nodes.
#include <otawa/graph/Graph.h>
Public Member Functions
Edge (Node *source, Node *target)
Build an edge between two nodes.
Node * source (void) const
Get the source node.
Node * target (void) const
Get the target node.
Protected Member Functions
virtual ~Edge (void)
Private Attributes
Node * src
Node * tgt
Edge * sedges
Edge * tedges
Friends
class Node
class Graph
class Node::Successor
class Node::Predecessor
Detailed Description
This class represents a directed edge between two nodes.
Constructor & Destructor Documentation
otawa::graph::Edge::~Edge (void) protected virtual
Reimplemented in otawa::ccg::Edge.
otawa::graph::Edge::Edge (Node * source, Node * target) inline
Build an edge between two nodes.
Warning
Both nodes must be contained in the same graph.
Parameters
source Source node.
target Target node.
References otawa::graph::Node::graph(), otawa::graph::Node::ins, and otawa::graph::Node::outs.
Member Function Documentation
Node * otawa::graph::Edge::source (void) const inline
Get the source node.
Returns
Source node.
Referenced by otawa::graph::Node::Predecessor::item(), otawa::GenGraph< N, E >::GenEdge::source(), and otawa::graph::Graph::sourceOf().
Node * otawa::graph::Edge::target (void) const inline
Get the target node.
Returns
Target node.
Referenced by otawa::graph::Node::Successor::item(), otawa::graph::Graph::sinkOf(), and otawa::GenGraph< N, E >::GenEdge::target().
Friends And Related Function Documentation
friend class Graph friend
friend class Node friend
friend class Node::Predecessor friend
friend class Node::Successor friend
Member Data Documentation
Edge* otawa::graph::Edge::sedges private
Referenced by otawa::graph::Node::Successor::next(), and otawa::graph::Graph::remove().
Node* otawa::graph::Edge::src private
Referenced by otawa::graph::Graph::remove().
Edge * otawa::graph::Edge::tedges private
Referenced by otawa::graph::Node::Predecessor::next(), and otawa::graph::Graph::remove().
Node * otawa::graph::Edge::tgt private
Referenced by otawa::graph::Graph::remove().
The documentation for this class was generated from the following files:
include/otawa/graph/Graph.h
src/prog/util_Edge.cpp