Otawa: otawa::hard::Processor::Make Class Reference
otawa::hard::Processor::Make Class Reference
#include <otawa/hard/Processor.h>
Public Member Functions
Make (string arch)
Make & model (string m)
Make & builder (string b)
Make & frequency (t::uint64 f)
Make & add (Stage *s)
Make & add (Stage &s)
Make & add (Stage::Make &m)
Make & add (Queue *q)
Make & add (Queue &q)
Make & add (Queue::Make &m)
Private Attributes
string _arch
string _model
string _builder
t::uint64 _frequency
genstruct::Vector< Stage * > stages
genstruct::Vector< Queue * > queues
Friends
class Processor
Constructor & Destructor Documentation
otawa::hard::Processor::Make::Make (string arch) inline
Member Function Documentation
Make& otawa::hard::Processor::Make::add (Stage * s) inline
References add().
Referenced by add().
Make& otawa::hard::Processor::Make::add (Stage & s) inline
References add().
Make& otawa::hard::Processor::Make::add (Stage::Make & m) inline
References add().
Make& otawa::hard::Processor::Make::add (Queue * q) inline
References add().
Make& otawa::hard::Processor::Make::add (Queue & q) inline
References add().
Make& otawa::hard::Processor::Make::add (Queue::Make & m) inline
References add().
Make& otawa::hard::Processor::Make::builder (string b) inline
Make& otawa::hard::Processor::Make::frequency (t::uint64 f) inline
Make& otawa::hard::Processor::Make::model (string m) inline
Friends And Related Function Documentation
friend class Processor friend
Member Data Documentation
string otawa::hard::Processor::Make::_arch private
string otawa::hard::Processor::Make::_builder private
t::uint64 otawa::hard::Processor::Make::_frequency private
string otawa::hard::Processor::Make::_model private
genstruct::Vector<Queue *> otawa::hard::Processor::Make::queues private
Referenced by otawa::hard::Processor::Processor().
genstruct::Vector<Stage *> otawa::hard::Processor::Make::stages private
Referenced by otawa::hard::Processor::Processor().
The documentation for this class was generated from the following file:
include/otawa/hard/Processor.h