Otawa: otawa::ilp::Alias Class Reference
otawa::ilp::Alias Class Reference
ILP -- Integer Linear Programming
An alias is a specific variable that represents an expressions.
#include <otawa/ilp/Var.h>
Public Types
enum type_t { NO_TYPE = 0, INT = 1, BIN = 2, FLOAT = 3 }
Type of an ILP variable.
Public Member Functions
Alias (Expression *expr)
Build an anonymous alias variable.
Alias (string name, Expression *expr)
Build a named alias variable.
virtual ~Alias (void)
virtual Alias * toAlias (void)
If the variable is an alias, return it.
virtual double eval (System *sys)
Evaluate the variable in the given system.
const Expression * expression (void) const
const string & name (void) const
Get the name of the variable if any.
type_t type (void) const
Get the type of the variable.
virtual void print (io::Output &out)
Print the name of the variable.
Private Attributes
Expression * _expr
Detailed Description
An alias is a specific variable that represents an expressions.
This allows to reduce the number of true variable and to replace any variable by any possible expression.
Member Enumeration Documentation
enum otawa::ilp::Var::type_t inherited
Type of an ILP variable.
Enumerator
NO_TYPE
Null value for ILP variable type.
INT
Integer (default) type for ILP variable.
BIN
Binary type (0 or 1) for ILP variable.
FLOAT
Real type for ILP variable.
Constructor & Destructor Documentation
otawa::ilp::Alias::Alias (Expression * expr)
Build an anonymous alias variable.
Parameters
expr Expression of the alias (this object is responsible for freeing it).
otawa::ilp::Alias::Alias (string name, Expression * expr)
Build a named alias variable.
Parameters
name Name of the variable.
expr Expression of the alias (this object is responsible for freeing it).
otawa::ilp::Alias::~Alias (void) virtual
References _expr.
Member Function Documentation
double otawa::ilp::Alias::eval (System * sys) virtual
Evaluate the variable in the given system.
Parameters
sys Resolved system to look in.
Returns
Value of the variable.
Reimplemented from otawa::ilp::Var.
References _expr, and otawa::ilp::Expression::eval().
const Expression* otawa::ilp::Alias::expression (void) const inline
Referenced by otawa::ilp::Expression::add().
String & otawa::ilp::Var::name (void) const inline inherited
Get the name of the variable if any.
Return an empty string if there is none.
Returns
Variable name.
Referenced by otawa::tsim::BBPath::makeVarName(), otawa::display::ILPSystemDisplayer::nameOf(), and otawa::ilp::operator<<().
void otawa::ilp::Var::print (io::Output & out) virtual inherited
Print the name of the variable.
Parameters
out Output to use.
References otawa::ilp::Var::_name.
Referenced by otawa::ilp::operator<<().
Alias * otawa::ilp::Alias::toAlias (void) virtual
If the variable is an alias, return it.
Returns
Alias object if it is alias, null else.
Reimplemented from otawa::ilp::Var.
type_t otawa::ilp::Var::type (void) const inline inherited
Get the type of the variable.
Returns
Variable type.
Referenced by otawa::ilp::operator<<().
Member Data Documentation
Expression* otawa::ilp::Alias::_expr private
Referenced by eval(), and ~Alias().
The documentation for this class was generated from the following files:
include/otawa/ilp/Var.h
src/prog/ilp_Var.cpp