Otawa: otawa::display::GenGraphAdapter< G >::Vertex Class Reference
otawa::display::GenGraphAdapter< G >::Vertex Class Reference
#include <otawa/display/GenGraphAdapter.h>
Public Member Functions
Vertex (typename G::_Node *_node)
int index (void)
G::_Node * operator-> (void) const
Public Attributes
G::_Node * node
Constructor & Destructor Documentation
template<class G > otawa::display::GenGraphAdapter< G >::Vertex::Vertex (typename G::_Node * _node) inline
Referenced by otawa::display::GenGraphAdapter< G >::Iterator::item(), otawa::display::GenGraphAdapter< G >::Edge::sink(), and otawa::display::GenGraphAdapter< G >::Edge::source().
Member Function Documentation
template<class G > int otawa::display::GenGraphAdapter< G >::Vertex::index (void) inline
References otawa::display::GenGraphAdapter< G >::Vertex::node.
template<class G > G::_Node* otawa::display::GenGraphAdapter< G >::Vertex::operator-> (void) const inline
References otawa::display::GenGraphAdapter< G >::Vertex::node.
Member Data Documentation
template<class G > G::_Node* otawa::display::GenGraphAdapter< G >::Vertex::node
Referenced by otawa::display::GenGraphAdapter< G >::Vertex::index(), otawa::display::GenGraphAdapter< G >::Vertex::operator->(), and otawa::display::GenGraphAdapter< G >::VertexMap< T >::put().
The documentation for this class was generated from the following file:
include/otawa/display/GenGraphAdapter.h