Otawa: otawa::ParamExeGraph::QueueResource Class Reference
otawa::ParamExeGraph::QueueResource Class Reference
#include <otawa/exegraph/ParamExeGraph.h>
Public Member Functions
QueueResource (elm::String name, Queue< ParamExeNode > *queue, int slot, int index, int offset, StageResource *upper_bound, int upper_bound_offset)
Queue< ParamExeNode > * queue ()
int slot ()
StageResource * upperBound ()
int upperBoundOffset ()
elm::String name ()
resource_type_t type ()
int index ()
int offset ()
Private Attributes
Queue< ParamExeNode > * _queue
int _slot
StageResource * _upper_bound
int _upper_bound_offset
Constructor & Destructor Documentation
otawa::ParamExeGraph::QueueResource::QueueResource (elm::String name, Queue< ParamExeNode > * queue, int slot, int index, int offset, StageResource * upper_bound, int upper_bound_offset) inline
Member Function Documentation
int otawa::ParamExeGraph::Resource::index (void) inline inherited
Referenced by otawa::ParamExeGraph::cost(), and otawa::ParamExeGraph::Delta().
elm::String otawa::ParamExeGraph::Resource::name (void) inline inherited
Referenced by otawa::ParamExeGraph::cost(), and otawa::ParamExeGraph::Delta().
int otawa::ParamExeGraph::Resource::offset (void) inline inherited
Referenced by otawa::ParamExeGraph::Delta().
Queue<ParamExeNode>* otawa::ParamExeGraph::QueueResource::queue () inline
int otawa::ParamExeGraph::QueueResource::slot () inline
resource_type_t otawa::ParamExeGraph::Resource::type (void) inline inherited
Referenced by otawa::ParamExeGraph::Delta().
StageResource* otawa::ParamExeGraph::QueueResource::upperBound () inline
int otawa::ParamExeGraph::QueueResource::upperBoundOffset () inline
Member Data Documentation
Queue<ParamExeNode>* otawa::ParamExeGraph::QueueResource::_queue private
int otawa::ParamExeGraph::QueueResource::_slot private
StageResource* otawa::ParamExeGraph::QueueResource::_upper_bound private
int otawa::ParamExeGraph::QueueResource::_upper_bound_offset private
The documentation for this class was generated from the following file:
include/otawa/exegraph/ParamExeGraph.h