Otawa: otawa::ccg::Node Class Reference
otawa::ccg::Node Class Reference
CCG Plugin
Node of a CCG (Cache Conflict Graph).
#include <otawa/ccg/Node.h>
Public Member Functions
Node (LBlock *node)
LBlock * lblock ()
int index (void) const
bool hasSucc (void) const
bool hasPred (void) const
int countSucc (void) const
int countPred (void) const
bool isPredOf (const GenNode *node)
bool isSuccOf (const GenNode *node)
Private Attributes
LBlock * lbl
Detailed Description
Node of a CCG (Cache Conflict Graph).
Plugin
CCG Plugin
Constructor & Destructor Documentation
otawa::ccg::Node::Node (LBlock * node)
References lbl.
Member Function Documentation
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::countPred (void) const inline inherited
References otawa::graph::Node::countPred().
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::countSucc (void) const inline inherited
References otawa::graph::Node::countSucc().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::hasPred (void) const inline inherited
References otawa::graph::Node::hasPred().
Referenced by otawa::LiExeGraph::shadeNodes().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::hasSucc (void) const inline inherited
References otawa::graph::Node::hasSucc().
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::index (void) const inline inherited
References otawa::graph::Node::index().
Referenced by otawa::ParamExeGraph::cost().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::isPredOf (const GenNode * node) inline inherited
References otawa::graph::Node::countPred().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::isSuccOf (const GenNode * node) inline inherited
References otawa::graph::Node::isSuccOf().
LBlock* otawa::ccg::Node::lblock () inline
References lbl.
Referenced by otawa::ccg::ConstraintBuilder::addConstraintHeader(), and otawa::ccg::ConstraintBuilder::processLBlockSet().
Member Data Documentation
LBlock* otawa::ccg::Node::lbl private
Referenced by lblock(), and Node().
The documentation for this class was generated from the following files:
include/otawa/ccg/Node.h
src/ccg/ccg_Node.cpp