Otawa: otawa::hard::Stage::Make Class Reference
otawa::hard::Stage::Make Class Reference
#include <otawa/hard/Processor.h>
Public Member Functions
Make (string name="", type_t type=NONE)
Make & latency (int l)
Make & width (int w)
Make & do_branch (void)
Make & access_mem (void)
Make & is_ordered (void)
Make & add (FunctionalUnit *fu)
Make & add (FunctionalUnit &fu)
Make & add (const FunctionalUnit::Make &m)
Make & dispatch (Dispatch::type_t t, FunctionalUnit *f)
Private Attributes
type_t _type
bool _ordered
genstruct::Vector< FunctionalUnit * > fus
genstruct::Vector< Dispatch * > dispatches
Friends
class Stage
Constructor & Destructor Documentation
otawa::hard::Stage::Make::Make (string name = "", type_t type = NONE) inline
Member Function Documentation
Make& otawa::hard::Stage::Make::access_mem (void) inline
References otawa::hard::PipelineUnit::Make::access_mem().
Make& otawa::hard::Stage::Make::add (FunctionalUnit * fu) inline
References add().
Referenced by add(), and dispatch().
Make& otawa::hard::Stage::Make::add (FunctionalUnit & fu) inline
References add().
Make& otawa::hard::Stage::Make::add (const FunctionalUnit::Make & m) inline
References add().
Make& otawa::hard::Stage::Make::dispatch (Dispatch::type_t t, FunctionalUnit * f) inline
References add().
Make& otawa::hard::Stage::Make::do_branch (void) inline
References otawa::hard::PipelineUnit::Make::do_branch().
Make& otawa::hard::Stage::Make::is_ordered (void) inline
Make& otawa::hard::Stage::Make::latency (int l) inline
References otawa::hard::PipelineUnit::Make::latency().
Make& otawa::hard::Stage::Make::width (int w) inline
References otawa::hard::PipelineUnit::Make::width().
Friends And Related Function Documentation
friend class Stage friend
Member Data Documentation
bool otawa::hard::Stage::Make::_ordered private
type_t otawa::hard::Stage::Make::_type private
genstruct::Vector<Dispatch *> otawa::hard::Stage::Make::dispatches private
Referenced by otawa::hard::Stage::Stage().
genstruct::Vector<FunctionalUnit *> otawa::hard::Stage::Make::fus private
Referenced by otawa::hard::Stage::Stage().
The documentation for this class was generated from the following file:
include/otawa/hard/Processor.h