Otawa: otawa::ilp::Expression Class Reference
otawa::ilp::Expression Class Reference
ILP -- Integer Linear Programming
An expression allows to represent a sum of terms and may be used to represent the value of an aliased variable.
#include <otawa/ilp/Expression.h>
Classes
class Iterator
Public Member Functions
Expression (void)
Build an empty expression.
Expression (const Expression *expr)
Build an expression by cloning the given one.
void add (coef_t coef, ilp::Var *var=0)
Add a term to the expression.
void sub (coef_t coef, ilp::Var *var=0)
Subtract a term to the expression.
void add (const Term &t)
void sub (const Term &t)
void add (const Expression *expr, coef_t coef=1)
Perform the addition to the current expression of the given expression multiplied by the coefficient.
void sub (const Expression *expr, coef_t coef=1)
Perform the subtraction from the current expression of the given expression multiplied by the coefficient.
void mul (coef_t coef)
Multiply all terms of the expression by the given coefficient.
void div (coef_t coef)
Divide all terms of the expression by the given coefficient.
void add (const Expression &e)
Add an expression to an existing expression.
void sub (const Expression &e)
Subtract an expression to an existing expression.
double eval (System *sys)
Evaluate the expression using the variables solution of the given ILP system.
Private Attributes
genstruct::SLList< Term > terms
Detailed Description
An expression allows to represent a sum of terms and may be used to represent the value of an aliased variable.
Constructor & Destructor Documentation
otawa::ilp::Expression::Expression (void) inline
Build an empty expression.
otawa::ilp::Expression::Expression (const Expression * expr) inline
Build an expression by cloning the given one.
Parameters
expr Expression to clone.
References otawa::sem::add().
Member Function Documentation
void otawa::ilp::Expression::add (coef_t coef, ilp::Var * var = 0)
Add a term to the expression.
Parameters
coef Coefficient of the term.
var Variable of the term.
References otawa::ilp::Alias::expression(), terms, and otawa::ilp::Var::toAlias().
Referenced by otawa::ilp::AbstractConstraint::add(), otawa::ilp::ConstraintImpl::add(), add(), otawa::ilp::AbstractSystem::addObjectFunction(), otawa::ilp::operator+(), otawa::ilp::operator-(), otawa::ilp::ConstraintImpl::sub(), and sub().
void otawa::ilp::Expression::add (const Term & t) inline
References add(), otawa::ilp::Term::fst, and otawa::ilp::Term::snd.
Referenced by add().
void otawa::ilp::Expression::add (const Expression * expr, coef_t coef = 1)
Perform the addition to the current expression of the given expression multiplied by the coefficient.
Parameters
expr Expression to add.
coef Multiplication coefficient.
References terms.
void otawa::ilp::Expression::add (const Expression & e)
Add an expression to an existing expression.
Parameters
e Added expression.
References add().
void otawa::ilp::Expression::div (coef_t coef)
Divide all terms of the expression by the given coefficient.
Parameters
coef Coefficient to divide with.
References terms.
double otawa::ilp::Expression::eval (System * sys)
Evaluate the expression using the variables solution of the given ILP system.
Parameters
sys System to look for variable value?
Returns
Value of the expression in the system.
References otawa::ilp::System::valueOf().
Referenced by otawa::ilp::Alias::eval().
void otawa::ilp::Expression::mul (coef_t coef)
Multiply all terms of the expression by the given coefficient.
Parameters
coef Coefficient to multiply with.
References terms.
void otawa::ilp::Expression::sub (coef_t coef, ilp::Var * var = 0) inline
Subtract a term to the expression.
Parameters
coef Coefficient of the term.
var Variable of the term.
Referenced by otawa::ilp::operator-(), otawa::ilp::AbstractConstraint::sub(), and sub().
void otawa::ilp::Expression::sub (const Term & t) inline
References otawa::sem::add(), otawa::sem::div(), otawa::ilp::Term::fst, otawa::sem::mul(), otawa::ilp::Term::snd, sub(), and otawa::sem::sub().
Referenced by sub().
void otawa::ilp::Expression::sub (const Expression * expr, coef_t coef = 1)
Perform the subtraction from the current expression of the given expression multiplied by the coefficient.
Parameters
expr Expression to subtract.
coef Multiplication coefficient.
References add().
void otawa::ilp::Expression::sub (const Expression & e)
Subtract an expression to an existing expression.
Parameters
e Subtracted expression.
References sub().
Member Data Documentation
genstruct::SLList<Term> otawa::ilp::Expression::terms private
Referenced by add(), div(), and mul().
The documentation for this class was generated from the following files:
include/otawa/ilp/Expression.h
src/prog/ilp_Expression.cpp