Otawa: otawa::display::GraphVizGraphElement Class Reference
otawa::display::GraphVizGraphElement Class Reference abstract
#include </home/yashas/otawa/linux-x86_64/otawa-core-build/otawa/src/odisplay/graphviz.h>
Public Member Functions
virtual String attributes ()=0
calls attributes(const PropList& style) with the PropList containing the style of the item.
virtual void setProps (const PropList &props)
Protected Member Functions
virtual ~GraphVizGraphElement (void)
virtual bool printAttribute (elm::io::Output &out, const PropList::Iter &prop)
Process the Property given by the iterator pointing to it.
virtual String getPropertiesString ()
Makes a string containing the values of all properties in _props separated by newlines.
virtual void printOthersAttributes (elm::io::Output &out)
Prints attributes after all the style PropList have been iterated.
virtual String attributes (const PropList &props)
Prints all attributes (styles) in a string, between brackets.
Protected Attributes
PropList _props
Properties of the attached object.
elm::genstruct::HashTable< const AbstractIdentifier *, int > _include
List of properties to print.
elm::genstruct::HashTable< const AbstractIdentifier *, int > _exclude
List of properties to hide.
bool _defaultInclude
true if the default is to include all properties
Detailed Description
Author
G. Cavaignac
This class is the superclass of elements contained in the graph (Node & Edge)
Constructor & Destructor Documentation
virtual otawa::display::GraphVizGraphElement::~GraphVizGraphElement (void) inline protected virtual
Member Function Documentation
String otawa::display::GraphVizItem::attributes (const PropList & style) protected virtual inherited
Prints all attributes (styles) in a string, between brackets.
First iterates on the style PropList, calling printAttribute() for each property, and then, calls printOthersAttributes() to finish. This functions escapes all the newlines that have been appened in the functions printAttribute() and printOthersAttributes()
Parameters
style styles to be printed
Returns
String containing the attributes. For example: [color="red"]
References otawa::PropList::Iter::ended(), otawa::display::GraphVizItem::printAttribute(), otawa::display::GraphVizItem::printOthersAttributes(), and otawa::display::quoteNewlines().
otawa::display::GraphVizItem::attributes (void) pure virtual inherited
calls attributes(const PropList& style) with the PropList containing the style of the item.
Generally, the proplist is the object itself, because it inherits from PropList
Implemented in otawa::display::GraphVizGraph, otawa::display::GraphVizEdge, and otawa::display::GraphVizNode.
Referenced by otawa::display::GraphVizNode::attributes(), otawa::display::GraphVizEdge::attributes(), and otawa::display::GraphVizGraph::attributes().
String otawa::display::GraphVizItem::getPropertiesString () protected virtual inherited
Makes a string containing the values of all properties in _props separated by newlines.
Returns
string containing properties values
References otawa::display::GraphVizItem::_defaultInclude, otawa::display::GraphVizItem::_exclude, otawa::display::GraphVizItem::_include, otawa::display::GraphVizItem::_props, otawa::PropList::Iter::ended(), and otawa::AbstractIdentifier::print().
Referenced by otawa::display::GraphVizNode::printOthersAttributes(), and otawa::display::GraphVizEdge::printOthersAttributes().
bool otawa::display::GraphVizGraphElement::printAttribute (elm::io::Output & out, const PropList::Iter & prop) protected virtual
Process the Property given by the iterator pointing to it.
Prints the value to the given output, or store the property for example (the property can be printed furthermore by printOthersAttributes())
Parameters
out output where to print when something have to be printed iterator on properties. Used to compare the identifier and to get the property value
Returns
true if something have been written on the output, false else
Reimplemented from otawa::display::GraphVizItem.
Reimplemented in otawa::display::GraphVizEdge, and otawa::display::GraphVizNode.
References otawa::display::FONT, otawa::display::FONT_COLOR, otawa::display::FONT_SIZE, otawa::display::GraphVizItem::printAttribute(), otawa::display::quoteSpecials(), otawa::display::STYLE, otawa::display::STYLE_BOLD, otawa::display::STYLE_DASHED, otawa::display::STYLE_DOTTED, otawa::display::STYLE_FILLED, and otawa::display::STYLE_PLAIN.
Referenced by otawa::display::GraphVizNode::printAttribute(), and otawa::display::GraphVizEdge::printAttribute().
void otawa::display::GraphVizItem::printOthersAttributes (elm::io::Output & out) protected virtual inherited
Prints attributes after all the style PropList have been iterated.
One can append endlines to the output
Parameters
out output where to print others attributes
Reimplemented in otawa::display::GraphVizGraph, otawa::display::GraphVizEdge, and otawa::display::GraphVizNode.
Referenced by otawa::display::GraphVizItem::attributes().
void otawa::display::GraphVizItem::setProps (const PropList & props) virtual inherited
See also
Item::setProps(const PropList& props)
Reimplemented in otawa::display::GraphVizGraph, otawa::display::GraphVizEdge, and otawa::display::GraphVizNode.
References otawa::display::GraphVizItem::_props, otawa::PropList::addProps(), and otawa::PropList::clearProps().
Referenced by otawa::display::GraphVizNode::setProps(), otawa::display::GraphVizEdge::setProps(), and otawa::display::GraphVizGraph::setProps().
Member Data Documentation
bool otawa::display::GraphVizItem::_defaultInclude protected inherited
true if the default is to include all properties
Referenced by otawa::display::GraphVizItem::getPropertiesString(), and otawa::display::GraphVizItem::printAttribute().
elm::genstruct::HashTable<const AbstractIdentifier*, int> otawa::display::GraphVizItem::_exclude protected inherited
List of properties to hide.
If the key exists, exclude the property
Referenced by otawa::display::GraphVizItem::getPropertiesString(), and otawa::display::GraphVizItem::printAttribute().
elm::genstruct::HashTable<const AbstractIdentifier*, int> otawa::display::GraphVizItem::_include protected inherited
List of properties to print.
If the key exists, include the property
Referenced by otawa::display::GraphVizItem::getPropertiesString(), and otawa::display::GraphVizItem::printAttribute().
PropList otawa::display::GraphVizItem::_props protected inherited
Properties of the attached object.
Referenced by otawa::display::GraphVizItem::getPropertiesString(), and otawa::display::GraphVizItem::setProps().
The documentation for this class was generated from the following files:
src/odisplay/graphviz.h
src/odisplay/graphviz_GraphElement.cpp