Otawa: otawa::ParExeQueue Class Reference
otawa::ParExeQueue Class Reference
Parametric Execution Graph
Representation of a hardware instruction queue to be used to build a ParExeGraph.
#include <otawa/parexegraph/ParExeProc.h>
Public Member Functions
ParExeQueue (elm::String name, int size)
Constructor.
elm::String name (void)
int size (void)
ParExeStage * fillingStage (void)
ParExeStage * emptyingStage (void)
void setFillingStage (ParExeStage *stage)
void setEmptyingStage (ParExeStage *stage)
Private Attributes
elm::String _name
int _size
ParExeStage * _filling_stage
ParExeStage * _emptying_stage
Detailed Description
Representation of a hardware instruction queue to be used to build a ParExeGraph.
See also
Parametric Execution Graph
Constructor & Destructor Documentation
otawa::ParExeQueue::ParExeQueue (elm::String name, int size) inline
Constructor.
Parameters
name Name of the queue (used for debugging purposes)
size Capacity (number of instructions) of the queue.
Member Function Documentation
ParExeStage * otawa::ParExeQueue::emptyingStage (void) inline
Returns
Pointer to the pipeline stage (ParExeStage) that gets instructions from the queue.
ParExeStage * otawa::ParExeQueue::fillingStage (void) inline
Returns
Pointer to the pipeline stage (ParExeStage) that puts instructions into the queue.
Referenced by otawa::ParExeGraph::addEdgesForQueues(), and otawa::ParExeGraph::initDelays().
elm::String otawa::ParExeQueue::name (void) inline
Returns
Name of the queue.
Referenced by otawa::ParExeGraph::addEdgesForQueues().
void otawa::ParExeQueue::setEmptyingStage (ParExeStage * stage) inline
Referenced by otawa::ParExePipeline::addStage().
void otawa::ParExeQueue::setFillingStage (ParExeStage * stage) inline
Referenced by otawa::ParExePipeline::addStage().
int otawa::ParExeQueue::size (void) inline
Returns
Size (capacity) of the queue.
Referenced by otawa::ParExeGraph::addEdgesForQueues().
Member Data Documentation
ParExeStage* otawa::ParExeQueue::_emptying_stage private
ParExeStage* otawa::ParExeQueue::_filling_stage private
elm::String otawa::ParExeQueue::_name private
int otawa::ParExeQueue::_size private
The documentation for this class was generated from the following files:
include/otawa/parexegraph/ParExeProc.h
src/prog/parexegraph_ParExeProc.cpp