Otawa: otawa::LBlock Class Reference
otawa::LBlock Class Reference
The l-block is an abstraction allowing to split the basic block according to the bound of the cache block, that is, instructions composing a l-block are owned by the same basic block and same cache block.
#include <otawa/cache/LBlock.h>
Public Member Functions
LBlock (LBlockSet *set, BasicBlock *bb, Inst *inst, t::uint32 size, int cache_index)
Build a new LBlock.
int index (void) const
Address address (void) const
BasicBlock * bb (void) const
ot::size size (void) const
Get the size of the current l-block.
LBlockSet * lblockset (void) const
int countInsts (void)
Count the instructions in the l-block.
int cacheBlock (void) const
Compute the cache block of this L-block.
Inst * instruction (void) const
int number (void) const
Get the number of the LBlock in its cache row.
int id (void)
int cacheblock (void) const
Property * getProp (const AbstractIdentifier *id) const
Find a property by its identifier.
void setProp (Property *prop)
Set the property in the property list removing any double.
void setProp (const AbstractIdentifier *id)
void removeProp (const AbstractIdentifier *id)
Remove a property matching the given identifier.
void removeProp (const AbstractIdentifier &id)
Property * extractProp (const AbstractIdentifier *id)
Remove a property matching the given identifier and return it.
Property * extractProp (const AbstractIdentifier &id)
Remove a property matching the given identifier and return it.
void addProp (Property *prop)
Add property to the list without checking of duplication.
void removeAllProp (const AbstractIdentifier *id)
Remove all the properties matching the given identifier.
bool hasProp (const AbstractIdentifier &id) const
Test if the property list contains a property matching the given identifier.
void clearProps (void)
Remove all properties from the list.
void addProps (const PropList &props)
Add all properties from the given property list, in a reverse order.
void print (elm::io::Output &out) const
Display the current property list.
Static Public Attributes
static const PropList EMPTY
This is an empty proplist for convenience.
Private Member Functions
~LBlock (void)
Private Attributes
LBlockSet * lbs
Inst * _inst
t::uint32 _size
BasicBlock * _bb
int idx
int cid
Friends
class LBlockSet
Detailed Description
The l-block is an abstraction allowing to split the basic block according to the bound of the cache block, that is, instructions composing a l-block are owned by the same basic block and same cache block.
Therefore, when the first one is load in the cache, the next instructions are also load.
Constructor & Destructor Documentation
otawa::LBlock::LBlock (LBlockSet * lbset, BasicBlock * bb, Inst * inst, t::uint32 size, int cache_index)
Build a new LBlock.
Parameters
lbset L-block set which owns this l-block.
inst Instruction it starts with.
bb Basic block containing this l-block.
size Size of the l-block.
cache_indx Cache index.
References idx.
otawa::LBlock::~LBlock (void) private
Referenced by cacheblock().
Member Function Documentation
void otawa::PropList::addProp (Property * prop) inherited
Add property to the list without checking of duplication.
Parameters
prop Property to add.
References otawa::Property::_next.
Referenced by otawa::Identifier< T >::add(), otawa::ast::ASTInfo::ASTInfo(), otawa::Identifier< otawa::arm::Info * >::copy(), otawa::AbstractIdentifier::initProps(), otawa::ContextualProperty::make(), otawa::script::Script::makeConfig(), otawa::ccg::Builder::processLBlockSet(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), and otawa::ContextualProperty::refProps().
void otawa::PropList::addProps (const PropList & props) inherited
Add all properties from the given property list, in a reverse order.
Parameters
props Property list to clone.
References otawa::Property::copy(), otawa::PropList::head, and otawa::Property::next().
Referenced by otawa::display::CFGDrawer::CFGDrawer(), otawa::display::GraphVizGraph::GraphVizGraph(), otawa::ParamFeature::instantiate(), otawa::Manager::loadXML(), otawa::display::GraphVizGraph::newEdge(), otawa::display::GraphVizGraph::newNode(), otawa::Process::Process(), otawa::display::GraphVizItem::setProps(), otawa::VirtualBasicBlock::VirtualBasicBlock(), and otawa::VirtualCFG::VirtualCFG().
Address otawa::LBlock::address (void) const inline
References _inst, and otawa::ProgItem::address().
Referenced by otawa::cat::CATBuilder::worst().
BasicBlock* otawa::LBlock::bb (void) const inline
References _bb.
Referenced by otawa::cat::CATBuilder::worst().
int otawa::LBlock::cacheBlock (void) const inline
Compute the cache block of this L-block.
Returns
Cache block.
References cid.
Referenced by otawa::LBlockSet::add().
int otawa::LBlock::cacheblock (void) const inline
References cid, and ~LBlock().
Referenced by otawa::MUSTPERS::update(), otawa::MAYProblem::update(), and otawa::MUSTProblem::update().
void otawa::PropList::clearProps (void) inherited
Remove all properties from the list.
References otawa::Property::next().
Referenced by otawa::PSTBuilder::getVCFG(), otawa::display::GraphVizItem::setProps(), and otawa::WorkSpace::~WorkSpace().
int otawa::LBlock::countInsts (void)
Count the instructions in the l-block.
Returns
L-block instruction count.
References _bb, _inst, _size, and otawa::ProgItem::address().
Referenced by lblockset().
Property * otawa::PropList::extractProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::script::Script::makeConfig().
Property * otawa::PropList::extractProp (const AbstractIdentifier & id) inline inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::PropList::extractProp().
Referenced by otawa::PropList::extractProp().
Property * otawa::PropList::getProp (const AbstractIdentifier * id) const inherited
Find a property by its identifier.
Parameters
id Identifier of the property to find.
Returns
Found property or null.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::Identifier< otawa::arm::Info * >::exists(), otawa::ContextualProperty::exists(), otawa::ContextualProperty::find(), otawa::Identifier< T >::get(), otawa::ContextualProperty::make(), otawa::ParamFeature::matches(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::print(), otawa::ContextualProperty::print(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), otawa::ContextualProperty::refProps(), otawa::Identifier< T >::set(), otawa::Identifier< T >::use(), and otawa::Identifier< T >::value().
bool otawa::PropList::hasProp (const AbstractIdentifier & id) const inline inherited
Test if the property list contains a property matching the given identifier.
Parameters
id Property identifier to look for.
Returns
True if the list contains the matching property, false else.
References otawa::p::print().
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::Monitor::configure(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::exists(), and otawa::Manager::setVerbosity().
int otawa::LBlock::id (void) inline
References idx.
Referenced by otawa::cat::CATBuilder::worst().
int otawa::LBlock::index (void) const inline
References idx.
Inst* otawa::LBlock::instruction (void) const inline
References _inst.
LBlockSet* otawa::LBlock::lblockset (void) const inline
References countInsts(), and lbs.
Referenced by otawa::operator<<().
int otawa::LBlock::number (void) const inline
Get the number of the LBlock in its cache row.
This numbers span from 0 to LBlockSet::count() - 1.
Returns
Number of the l-block.
References idx.
Referenced by otawa::operator<<().
void otawa::PropList::print (elm::io::Output & out) const inherited
Display the current property list.
Parameters
out Output to use.
Referenced by otawa::Edge::kindName(), otawa::operator<<(), and otawa::ContextualProperty::print().
void otawa::PropList::removeAllProp (const AbstractIdentifier * id) inherited
Remove all the properties matching the given identifier.
Parameters
id Identifier of properties to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::LoopUnroller::unroll().
void otawa::PropList::removeProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier.
Parameters
id Identifier of the property to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::PSTBuilder::buildTree(), otawa::BBRemover< T >::clean(), otawa::CFGBuilder::cleanup(), otawa::display::CFGOutput::processCFG(), otawa::SubCFGBuilder::processWorkSpace(), otawa::Identifier< otawa::arm::Info * >::remove(), and otawa::ContextualPath::Ref< T >::remove().
void otawa::PropList::removeProp (const AbstractIdentifier & id) inline inherited
References otawa::PropList::removeProp().
Referenced by otawa::PropList::removeProp().
void otawa::PropList::setProp (Property * prop) inherited
Set the property in the property list removing any double.
Parameters
prop Property to set.
References otawa::Property::_next, otawa::Property::id(), and otawa::Property::next().
void otawa::PropList::setProp (const AbstractIdentifier * id) inline inherited
References otawa::PropList::setProp().
Referenced by otawa::PropList::setProp().
size_t otawa::LBlock::size (void) const inline
Get the size of the current l-block.
Returns
L-block size.
References _size.
Friends And Related Function Documentation
friend class LBlockSet friend
Member Data Documentation
BasicBlock* otawa::LBlock::_bb private
Referenced by bb(), and countInsts().
Inst* otawa::LBlock::_inst private
Referenced by address(), countInsts(), and instruction().
t::uint32 otawa::LBlock::_size private
Referenced by countInsts(), and size().
int otawa::LBlock::cid private
Referenced by cacheBlock(), and cacheblock().
const PropList otawa::PropList::EMPTY static inherited
This is an empty proplist for convenience.
Referenced by otawa::DynProcessor::configure(), otawa::ActualFeature::processor(), otawa::SilentFeature::SilentFeature(), otawa::Processor::version(), and otawa::display::Driver::~Driver().
int otawa::LBlock::idx private
Referenced by id(), index(), LBlock(), and number().
LBlockSet* otawa::LBlock::lbs private
Referenced by lblockset().
The documentation for this class was generated from the following files:
include/otawa/cache/LBlock.h
src/prog/cache_LBlock.cpp