Otawa: otawa::ParExeEdge Class Reference
otawa::ParExeEdge Class Reference
Parametric Execution Graph
An edge in a ParExeGraph.
#include <otawa/parexegraph/ParExeGraph.h>
Public Types
enum edge_type_t { SOLID = 1, SLASHED = 2 }
typedef enum otawa::ParExeEdge::edge_type_t edge_type_t_t
Public Member Functions
ParExeEdge (ParExeNode *source, ParExeNode *target, edge_type_t type, int latency=0, const string &name="")
int latency (void) const
void setLatency (int latency)
edge_type_t type (void) const
const elm::string & name (void) const
N * source (void) const
N * target (void) const
Private Attributes
edge_type_t _type
elm::String _name
int _latency
Detailed Description
An edge in a ParExeGraph.
See also
Parametric Execution Graph
Member Typedef Documentation
typedef enum otawa::ParExeEdge::edge_type_t otawa::ParExeEdge::edge_type_t_t
Member Enumeration Documentation
enum otawa::ParExeEdge::edge_type_t
Enumerator
SOLID
SLASHED
Constructor & Destructor Documentation
otawa::ParExeEdge::ParExeEdge (ParExeNode * source, ParExeNode * target, edge_type_t type, int latency = 0, const string & name = "") inline
Member Function Documentation
int otawa::ParExeEdge::latency (void) const inline
const elm::string& otawa::ParExeEdge::name (void) const inline
void otawa::ParExeEdge::setLatency (int latency) inline
Referenced by otawa::etime::EdgeTimeBuilder::apply().
template<class N, class E> N* otawa::GenGraph< N, E >::GenEdge::source (void) const inline inherited
References OTAWA_GCAST, and otawa::graph::Edge::source().
template<class N, class E> N* otawa::GenGraph< N, E >::GenEdge::target (void) const inline inherited
References OTAWA_GCAST, and otawa::graph::Edge::target().
edge_type_t otawa::ParExeEdge::type (void) const inline
Member Data Documentation
int otawa::ParExeEdge::_latency private
elm::String otawa::ParExeEdge::_name private
edge_type_t otawa::ParExeEdge::_type private
The documentation for this class was generated from the following file:
include/otawa/parexegraph/ParExeGraph.h