Otawa: otawa::sim::AbstractCacheDriver Class Reference
otawa::sim::AbstractCacheDriver Class Reference abstract
This is an abstract implementation of the cache driver allowing to customize only the cache replacement policy.
#include <otawa/sim/AbstractCacheDriver.h>
Public Types
typedef unsigned long tag_t
enum result_t { MISS = 0, HIT = 1 }
This enumeration allows to know the result of a cache access.
enum action_t { READ, WRITE }
This enumeration identifies the kind of cache access.
Public Member Functions
AbstractCacheDriver (const hard::Cache *cache)
Build a cache driver with the given cache.
virtual ~AbstractCacheDriver (void)
virtual result_t access (address_t address, size_t size, action_t action)
This function is called each time the cache is accessed.
const hard::Cache * cache (void) const
Static Public Member Functions
static CacheDriver * lookup (const hard::Cache *cache)
This method retrieve the cache driver matching the given cache description.
Static Public Attributes
static CacheDriver & ALWAYS_HIT = HIT_DRIVER
This cache driver specialization generates a hit each time it is accessed.
static CacheDriver & ALWAYS_MISS = MISS_DRIVER
This cache driver specialization generates a miss each time it is accessed.
Protected Member Functions
virtual void touch (int index, int num, tag_t *line)=0
This function is called each time a cache block in a set is accessed (read / write).
virtual void replace (tag_t tag, int num, tag_t *line)=0
This function is called each time a replacement in a set is required.
Private Attributes
const hard::Cache * _cache
tag_t * lines
Detailed Description
This is an abstract implementation of the cache driver allowing to customize only the cache replacement policy.
Implementations of this class includes:
DirectMappedCacheDriver
LRUCacheDriver
FIFOCacheDriver
Member Typedef Documentation
typedef unsigned long otawa::sim::AbstractCacheDriver::tag_t
Member Enumeration Documentation
enum otawa::sim::CacheDriver::action_t inherited
This enumeration identifies the kind of cache access.
Enumerator
READ
A read is performed on the cache.
WRITE
A write is performed on the cache.
enum otawa::sim::CacheDriver::result_t inherited
This enumeration allows to know the result of a cache access.
Enumerator
MISS
The result of a cache access produces a miss.
HIT
The result of a cache access produces a hit.
Constructor & Destructor Documentation
otawa::sim::AbstractCacheDriver::AbstractCacheDriver (const hard::Cache * cache)
Build a cache driver with the given cache.
Parameters
cache Used cache.
References lines.
otawa::sim::AbstractCacheDriver::~AbstractCacheDriver (void) virtual
References lines.
Member Function Documentation
CacheDriver::result_t otawa::sim::AbstractCacheDriver::access (address_t address, size_t size, action_t action) virtual
This function is called each time the cache is accessed.
It must be overload to specialize the cache behavior.
Parameters
address Address of the accessed data.
size Size of the accessed data.
action Action performed.
Returns
HIT or MISS according presence of the block of data in the cache.
Implements otawa::sim::CacheDriver.
References _cache, otawa::sim::CacheDriver::HIT, otawa::hard::Cache::line(), lines, otawa::sim::CacheDriver::MISS, replace(), otawa::hard::Cache::tag(), touch(), and otawa::hard::Cache::wayCount().
const hard::Cache* otawa::sim::AbstractCacheDriver::cache (void) const inline
References cache().
Referenced by otawa::sim::LRUCacheDriver::replace(), and otawa::sim::FIFOCacheDriver::replace().
CacheDriver * otawa::sim::AbstractCacheDriver::lookup (const hard::Cache * cache) static
This method retrieve the cache driver matching the given cache description.
Parameters
cache Cache to look a driver for.
Returns
Matching cache driver or null.
References otawa::hard::Cache::FIFO, otawa::hard::Cache::LRU, otawa::hard::Cache::replacementPolicy(), and otawa::hard::Cache::wayCount().
void otawa::sim::AbstractCacheDriver::replace (tag_t tag, int num, tag_t * line) protected pure virtual
This function is called each time a replacement in a set is required.
This method implementer must wipe out one of the block and replaced it by the given tag.
Parameters
tag New tag to store in the set.
num Number of the affected set/line.
line Array base containing tags of the line.
Implemented in otawa::sim::FIFOCacheDriver, otawa::sim::DirectMappedCacheDriver, and otawa::sim::LRUCacheDriver.
Referenced by access().
void otawa::sim::AbstractCacheDriver::touch (int index, int num, tag_t * line) protected pure virtual
This function is called each time a cache block in a set is accessed (read / write).
The implementer may use this call to update its tag order in the set.
Parameters
index Index of the accessed tag in the tag array.
num Number of the set/line accessed.
line Base of the array containing tags of the current set/line.
Implemented in otawa::sim::FIFOCacheDriver, otawa::sim::DirectMappedCacheDriver, and otawa::sim::LRUCacheDriver.
Referenced by access().
Member Data Documentation
const hard::Cache* otawa::sim::AbstractCacheDriver::_cache private
Referenced by access().
CacheDriver & otawa::sim::CacheDriver::ALWAYS_HIT = HIT_DRIVER static inherited
This cache driver specialization generates a hit each time it is accessed.
Referenced by otawa::sim::CacheDriver::~CacheDriver().
CacheDriver & otawa::sim::CacheDriver::ALWAYS_MISS = MISS_DRIVER static inherited
This cache driver specialization generates a miss each time it is accessed.
Referenced by otawa::sim::CacheDriver::~CacheDriver().
tag_t* otawa::sim::AbstractCacheDriver::lines private
Referenced by AbstractCacheDriver(), access(), and ~AbstractCacheDriver().
The documentation for this class was generated from the following files:
include/otawa/sim/AbstractCacheDriver.h
src/prog/sim_AbstractCacheDriver.cpp