Otawa: otawa::hard::PipelineUnit::Make Class Reference
otawa::hard::PipelineUnit::Make Class Reference
#include <otawa/hard/Processor.h>
Public Member Functions
Make (string name="")
Make & latency (int l)
Make & width (int w)
Make & do_branch (void)
Make & access_mem (void)
Private Attributes
string _name
int _latency
int _width
bool branch
bool mem
Friends
class PipelineUnit
Constructor & Destructor Documentation
otawa::hard::PipelineUnit::Make::Make (string name = "") inline
Member Function Documentation
Make& otawa::hard::PipelineUnit::Make::access_mem (void) inline
Referenced by otawa::hard::FunctionalUnit::Make::access_mem(), and otawa::hard::Stage::Make::access_mem().
Make& otawa::hard::PipelineUnit::Make::do_branch (void) inline
References otawa::sem::branch().
Referenced by otawa::hard::FunctionalUnit::Make::do_branch(), and otawa::hard::Stage::Make::do_branch().
Make& otawa::hard::PipelineUnit::Make::latency (int l) inline
Referenced by otawa::hard::FunctionalUnit::Make::latency(), and otawa::hard::Stage::Make::latency().
Make& otawa::hard::PipelineUnit::Make::width (int w) inline
Referenced by otawa::hard::FunctionalUnit::Make::width(), and otawa::hard::Stage::Make::width().
Friends And Related Function Documentation
friend class PipelineUnit friend
Member Data Documentation
int otawa::hard::PipelineUnit::Make::_latency private
string otawa::hard::PipelineUnit::Make::_name private
int otawa::hard::PipelineUnit::Make::_width private
bool otawa::hard::PipelineUnit::Make::branch private
bool otawa::hard::PipelineUnit::Make::mem private
The documentation for this class was generated from the following file:
include/otawa/hard/Processor.h