Otawa: otawa::hard::PipelineUnit Class Reference
otawa::hard::PipelineUnit Class Reference
Platform Description
A pipeline unit is microprocessor place that used to execute an instruction.
#include <otawa/hard/Processor.h>
Classes
class Make
Public Member Functions
PipelineUnit (void)
Empty pipeline unit builder.
PipelineUnit (const Make &maker)
Build a pipeline unit using a maker.
PipelineUnit (const PipelineUnit *unit)
Cloning constructor.
virtual ~PipelineUnit (void)
elm::String getName (void) const
Get the name of the pipeline unit.
int getLatency (void) const
Get the latency of the pipeline unit.
int getWidth (void) const
Get the width of the pipeline instruction, i.e.
bool isBranch (void) const
Test if the pipeline unit performs branchs.
bool isMem (void) const
Test if the pipeline unit performs data memory access.
Protected Attributes
string name
int latency
int width
bool branch
bool mem
Private Member Functions
SERIALIZABLE (otawa::hard::PipelineUnit, FIELD(name)&FIELD(latency)&FIELD(width)&FIELD(branch)&FIELD(mem))
Detailed Description
A pipeline unit is microprocessor place that used to execute an instruction.
It factorize common configuration items of stage and functional unit.
Constructor & Destructor Documentation
otawa::hard::PipelineUnit::PipelineUnit (void)
Empty pipeline unit builder.
otawa::hard::PipelineUnit::PipelineUnit (const Make & maker)
Build a pipeline unit using a maker.
otawa::hard::PipelineUnit::PipelineUnit (const PipelineUnit * unit)
Cloning constructor.
otawa::hard::PipelineUnit::~PipelineUnit (void) virtual
Member Function Documentation
int otawa::hard::PipelineUnit::getLatency (void) const inline
Get the latency of the pipeline unit.
Returns
Latency (in cycles).
Referenced by otawa::hard::Processor::execute(), and otawa::ParExeProc::ParExeProc().
elm::String otawa::hard::PipelineUnit::getName (void) const inline
Get the name of the pipeline unit.
Returns
Pipeline unit name.
References name.
Referenced by otawa::ParExeProc::ParExeProc().
int otawa::hard::PipelineUnit::getWidth (void) const inline
Get the width of the pipeline instruction, i.e.
the number of instruction is can process in parallel.
Returns
Pipeline unit width (in instructions).
Referenced by otawa::ParExeProc::ParExeProc().
bool otawa::hard::PipelineUnit::isBranch (void) const inline
Test if the pipeline unit performs branchs.
Returns
True if it performs branch, false else.
References otawa::sem::branch().
bool otawa::hard::PipelineUnit::isMem (void) const inline
Test if the pipeline unit performs data memory access.
Returns
True if it performs data memory access, false else.
otawa::hard::PipelineUnit::SERIALIZABLE (otawa::hard::PipelineUnit , FIELD(name)&FIELD(latency)&FIELD(width)&FIELD(branch)&FIELD(mem)) private
Member Data Documentation
bool otawa::hard::PipelineUnit::branch protected
int otawa::hard::PipelineUnit::latency protected
bool otawa::hard::PipelineUnit::mem protected
string otawa::hard::PipelineUnit::name protected
int otawa::hard::PipelineUnit::width protected
The documentation for this class was generated from the following files:
include/otawa/hard/Processor.h
src/prog/hard_Processor.cpp