Otawa: otawa::graph::Node::Successor Class Reference
otawa::graph::Node::Successor Class Reference
This class allows to iterates on the successors of a node.
#include <otawa/graph/Graph.h>
Public Member Functions
Successor (const Node *node)
Build an iterator on the successor of the given node.
bool ended (void) const
void next (void)
Node * item (void) const
Edge * edge (void) const
Get the edge leading to the current successor.
Private Attributes
Edge * _edge
Detailed Description
This class allows to iterates on the successors of a node.
Constructor & Destructor Documentation
otawa::graph::Node::Successor::Successor (const Node * node) inline
Build an iterator on the successor of the given node.
Parameters
node Node whose successors will be iterated.
Member Function Documentation
Edge * otawa::graph::Node::Successor::edge (void) const inline
Get the edge leading to the current successor.
Returns
Current edge.
References _edge.
Referenced by otawa::graph::Node::countPred(), and otawa::graph::Node::countSucc().
bool otawa::graph::Node::Successor::ended (void) const inline
References _edge.
Node * otawa::graph::Node::Successor::item (void) const inline
References _edge, and otawa::graph::Edge::target().
Referenced by otawa::graph::Graph::addAll(), and otawa::graph::Graph::removeAll().
void otawa::graph::Node::Successor::next (void) inline
References _edge, and otawa::graph::Edge::sedges.
Member Data Documentation
Edge* otawa::graph::Node::Successor::_edge private
Referenced by edge(), ended(), item(), next(), and otawa::graph::Node::Predecessor::next().
The documentation for this class was generated from the following files:
include/otawa/graph/Graph.h
src/prog/util_Node.cpp