Otawa: otawa::PERSBranch::Domain Class Reference
otawa::PERSBranch::Domain Class Reference
#include <otawa/branch/BranchProblem.h>
Public Member Functions
Domain (const int _size, const int _A)
~Domain ()
Domain (const Domain &source)
Domain & operator= (const Domain &src)
void lub (const Domain &dom)
void lub (const Item &item)
bool equals (const Domain &dom) const
void empty ()
void setToBottom ()
Item & getWhole ()
bool contains (const int id, const int index)
void inject (MUSTBranch::Domain *must, const int id)
bool isWiped (const int id, const int index)
int getAge (const int id, const int index) const
bool isPersistent (const int id, const int index)
void print (elm::io::Output &output) const
void enterContext ()
void leaveContext ()
int length ()
Item & getItem (const int idx) const
Private Attributes
int A
int size
bool isBottom
Item whole
genstruct::Vector< Item * > data
Constructor & Destructor Documentation
otawa::PERSBranch::Domain::Domain (const int _size, const int _A) inline
otawa::PERSBranch::Domain::~Domain () inline
otawa::PERSBranch::Domain::Domain (const Domain & source) inline
References data.
Member Function Documentation
bool otawa::PERSBranch::Domain::contains (const int id, const int index) inline
References otawa::MUSTBranch::Domain::contains().
void otawa::PERSBranch::Domain::empty () inline
Referenced by otawa::BranchProblem::Domain::empty(), and otawa::PERSBranch::PERSBranch().
void otawa::PERSBranch::Domain::enterContext () inline
References otawa::PERSBranch::Item::empty().
Referenced by otawa::PERSBranch::enterContext().
bool otawa::PERSBranch::Domain::equals (const Domain & dom) const inline
References data, otawa::MUSTBranch::Domain::equals(), isBottom, and whole.
Referenced by otawa::PERSBranch::equals(), and otawa::BranchProblem::Domain::equals().
int otawa::PERSBranch::Domain::getAge (const int id, const int index) const inline
References otawa::MUSTBranch::Domain::getAge().
Item& otawa::PERSBranch::Domain::getItem (const int idx) const inline
Item& otawa::PERSBranch::Domain::getWhole () inline
void otawa::PERSBranch::Domain::inject (MUSTBranch::Domain * must, const int id) inline
References otawa::MUSTBranch::Domain::inject().
Referenced by otawa::BranchProblem::Domain::inject().
bool otawa::PERSBranch::Domain::isPersistent (const int id, const int index) inline
Referenced by otawa::branch::BranchBuilder::categorize().
bool otawa::PERSBranch::Domain::isWiped (const int id, const int index) inline
void otawa::PERSBranch::Domain::leaveContext () inline
Referenced by otawa::PERSBranch::leaveContext().
int otawa::PERSBranch::Domain::length () inline
Referenced by otawa::branch::BranchBuilder::categorize().
void otawa::PERSBranch::Domain::lub (const Domain & dom) inline
References data, isBottom, and whole.
Referenced by otawa::PERSBranch::lub(), and otawa::BranchProblem::Domain::lub().
void otawa::PERSBranch::Domain::lub (const Item & item) inline
References otawa::MUSTBranch::Domain::lub().
Domain& otawa::PERSBranch::Domain::operator= (const Domain & src) inline
References data, isBottom, and whole.
void otawa::PERSBranch::Domain::print (elm::io::Output & output) const inline
Referenced by otawa::operator<<(), and otawa::BranchProblem::Domain::print().
void otawa::PERSBranch::Domain::setToBottom () inline
Referenced by otawa::PERSBranch::PERSBranch().
Member Data Documentation
int otawa::PERSBranch::Domain::A private
genstruct::Vector<Item*> otawa::PERSBranch::Domain::data private
Referenced by Domain(), equals(), lub(), and operator=().
bool otawa::PERSBranch::Domain::isBottom private
Referenced by equals(), lub(), and operator=().
int otawa::PERSBranch::Domain::size private
Item otawa::PERSBranch::Domain::whole private
Referenced by equals(), lub(), and operator=().
The documentation for this class was generated from the following file:
include/otawa/branch/BranchProblem.h