Otawa: otawa::hard::Stage Class Reference
otawa::hard::Stage Class Reference
Platform Description
This class represents a stage in a pipeline.
#include <otawa/hard/Processor.h>
Classes
class Make
Public Types
enum type_t {
NONE = 0, FETCH, LAZY, EXEC,
COMMIT, DECOMP
}
typedef enum otawa::hard::Stage::type_t type_t
Public Member Functions
Stage (type_t _type=NONE)
Build a simple stage.
Stage (const Make &maker)
Stage (const Stage *stage)
Build a stage by cloning the given one.
virtual ~Stage (void)
type_t getType (void) const
Get type of the stage.
const Table< FunctionalUnit * > & getFUs (void) const
Get the table of functional units.
const Table< Dispatch * > & getDispatch (void) const
Get the table of dispatch.
bool isOrdered (void) const
Test if the stage is ordered or not.
FunctionalUnit * select (Inst *inst) const
Select the pipeline unit to execute the given instruction.
template<class T >
T select (Inst *inst, const T table[]) const
template<class T >
T select (Inst::kind_t kind, const T table[]) const
elm::String getName (void) const
Get the name of the pipeline unit.
int getLatency (void) const
Get the latency of the pipeline unit.
int getWidth (void) const
Get the width of the pipeline instruction, i.e.
bool isBranch (void) const
Test if the pipeline unit performs branchs.
bool isMem (void) const
Test if the pipeline unit performs data memory access.
Protected Attributes
string name
int latency
int width
bool branch
bool mem
Private Member Functions
SERIALIZABLE (otawa::hard::Stage, BASE(otawa::hard::PipelineUnit)&FIELD(type)&FIELD(fus)&FIELD(dispatch)&FIELD(ordered))
Private Attributes
type_t type
AllocatedTable< FunctionalUnit * > fus
AllocatedTable< Dispatch * > dispatch
bool ordered
Friends
class StageBuilder
Detailed Description
This class represents a stage in a pipeline.
The stages have a type:
otawa::hard::Stage::FETCH – a stage loading instruction from memory (usually the initial stage of a pipeline).
otawa::hard::Stage::LAZY – a simple stage that is traversed by instructions,
otawa::hard::Stage::EXEC – a stage that performs execution of instructions (it contains functionnal units that performs the work of the instructions),
otawa::hard::Stage::COMMIT – a stage that writes result of an instruction in the processor state (usually the end of the traversal of the instructions).
The stages are described by the following attributes:
the name,
the width (number of instructions traversing in parallel the stage),
the latency (number of cycles taken to traverse the stage),
the order (is the instructions traversal perform in program order or not),
for the EXEC stage only, a functionnal unit list (otawa::hard::FunctionalUnit) and dispatch list (otawa::hard::Dispatch).
Member Typedef Documentation
typedef enum otawa::hard::Stage::type_t otawa::hard::Stage::type_t
Member Enumeration Documentation
enum otawa::hard::Stage::type_t
Enumerator
NONE
FETCH
LAZY
EXEC
COMMIT
DECOMP
Constructor & Destructor Documentation
otawa::hard::Stage::Stage (type_t t = NONE)
Build a simple stage.
Parameters
t Type mask.
otawa::hard::Stage::Stage (const Make & maker)
References dispatch, otawa::hard::Stage::Make::dispatches, otawa::hard::Stage::Make::fus, and fus.
otawa::hard::Stage::Stage (const Stage * stage)
Build a stage by cloning the given one.
Parameters
stage Stage to clone.
References dispatch, and fus.
otawa::hard::Stage::~Stage (void) virtual
Member Function Documentation
const Table< Dispatch * > & otawa::hard::Stage::getDispatch (void) const inline
Get the table of dispatch.
Returns
Table of dispatch.
Referenced by otawa::ParExeProc::ParExeProc().
const Table< FunctionalUnit * > & otawa::hard::Stage::getFUs (void) const inline
Get the table of functional units.
Returns
Functional unit table.
Referenced by otawa::ParExeProc::ParExeProc().
int otawa::hard::PipelineUnit::getLatency (void) const inline inherited
Get the latency of the pipeline unit.
Returns
Latency (in cycles).
Referenced by otawa::hard::Processor::execute(), and otawa::ParExeProc::ParExeProc().
elm::String otawa::hard::PipelineUnit::getName (void) const inline inherited
Get the name of the pipeline unit.
Returns
Pipeline unit name.
References name.
Referenced by otawa::ParExeProc::ParExeProc().
type_t otawa::hard::Stage::getType (void) const inline
Get type of the stage.
Returns
Stage type.
References otawa::type().
Referenced by otawa::ParExeProc::ParExeProc().
int otawa::hard::PipelineUnit::getWidth (void) const inline inherited
Get the width of the pipeline instruction, i.e.
the number of instruction is can process in parallel.
Returns
Pipeline unit width (in instructions).
Referenced by otawa::ParExeProc::ParExeProc().
bool otawa::hard::PipelineUnit::isBranch (void) const inline inherited
Test if the pipeline unit performs branchs.
Returns
True if it performs branch, false else.
References otawa::sem::branch().
bool otawa::hard::PipelineUnit::isMem (void) const inline inherited
Test if the pipeline unit performs data memory access.
Returns
True if it performs data memory access, false else.
bool otawa::hard::Stage::isOrdered (void) const inline
Test if the stage is ordered or not.
Returns
True if the stage is ordered, false else.
References kind.
FunctionalUnit * otawa::hard::Stage::select (Inst * inst) const
Select the pipeline unit to execute the given instruction.
Works only with stages of type EXEC.
Parameters
inst Instruction to look a functional unit for.
Returns
Found functional unit or null.
References dispatch, otawa::Inst::kind(), and kind.
template<class T > T otawa::hard::Stage::select (Inst * inst, const T table[]) const inline
References otawa::Inst::kind().
template<class T > T otawa::hard::Stage::select (Inst::kind_t kind, const T table[]) const inline
References elm::serial2::__serialize(), elm::serial2::__unserialize(), ENUM(), otawa::hard::PROCESSOR, otawa::hard::PROCESSOR_FEATURE, and otawa::hard::PROCESSOR_ID.
otawa::hard::Stage::SERIALIZABLE (otawa::hard::Stage , BASE(otawa::hard::PipelineUnit)&FIELD(type)&FIELD(fus)&FIELD(dispatch)&FIELD(ordered)) private
Friends And Related Function Documentation
friend class StageBuilder friend
Member Data Documentation
bool otawa::hard::PipelineUnit::branch protected inherited
AllocatedTable<Dispatch *> otawa::hard::Stage::dispatch private
Referenced by select(), and Stage().
AllocatedTable<FunctionalUnit *> otawa::hard::Stage::fus private
Referenced by Stage().
int otawa::hard::PipelineUnit::latency protected inherited
bool otawa::hard::PipelineUnit::mem protected inherited
string otawa::hard::PipelineUnit::name protected inherited
bool otawa::hard::Stage::ordered private
type_t otawa::hard::Stage::type private
int otawa::hard::PipelineUnit::width protected inherited
The documentation for this class was generated from the following files:
include/otawa/hard/Processor.h
src/prog/hard_Processor.cpp