Otawa: otawa::ilp::ConstraintImpl Class Reference
otawa::ilp::ConstraintImpl Class Reference abstract
Provide a simple implementation of a constraint using expression.
#include <otawa/ilp/impl.h>
Public Types
enum comparator_t {
UNDEF = -3, LT = -2, LE = -1, EQ = 0,
GE = 1, GT = 2
}
typedef enum otawa::ilp::Constraint::comparator_t comparator_t
typedef otawa::ilp::Term Term
Public Member Functions
ConstraintImpl (comparator_t comparator, string label="")
Build an empty constraint.
virtual double coefficient (Var *var)
virtual double constant (void) const
virtual comparator_t comparator (void) const
Get the constraint comparator.
virtual const string & label (void) const
virtual void add (double coef, Var *var)
Add a term to the constraint to the left part of constraint.
virtual void sub (double coef, Var *var)
Substact a factor from the constraint.
virtual elm::datastruct::IteratorInst< Term > * terms (void)
virtual double coefficient (Var *var=0) const =0
Get the coefficient for the given variable.
void add (const Term &t)
void add (const Expression &e)
void Constraint::setComparator(comparator_t comp); Change the comparator of the constraint.
void sub (const Term &t)
void sub (const Expression &e)
Subtract an expression from the left part of the constraint.
void addLeft (double coef, Var *var=0)
Add a factor on the left side.
void addRight (double coef, Var *var=0)
Add a factor on the right side.
virtual void setComparator (comparator_t comp)=0
virtual void setLabel (const string &label)=0
Private Attributes
Expression expr
comparator_t comp
string lab
Detailed Description
Provide a simple implementation of a constraint using expression.
The stored expression e states only that: e {=|<|>|<=|>=} 0. It is relatively easy to push back the constant to the right of the constraint.
Member Typedef Documentation
typedef enum otawa::ilp::Constraint::comparator_t otawa::ilp::Constraint::comparator_t inherited
typedef otawa::ilp::Term otawa::ilp::Constraint::Term inherited
Member Enumeration Documentation
enum otawa::ilp::Constraint::comparator_t inherited
Enumerator
UNDEF
LT
LE
EQ
GE
GT
Constructor & Destructor Documentation
otawa::ilp::ConstraintImpl::ConstraintImpl (comparator_t comparator, string label = "")
Build an empty constraint.
Parameters
comparator Comparator to use.
label Label of the constraint.
Member Function Documentation
void otawa::ilp::ConstraintImpl::add (double coef, Var * var) virtual
Add a term to the constraint to the left part of constraint.
If var is null, sum the coefficient to the right part of the constraint.
Parameters
coef Coefficient of the factor.
var Variable of the factor. When null, modify the constant.
Implements otawa::ilp::Constraint.
References otawa::ilp::Expression::add(), and expr.
void otawa::ilp::Constraint::add (const Term & t) inline inherited
References otawa::ilp::Constraint::add(), otawa::ilp::Term::fst, and otawa::ilp::Term::snd.
Referenced by otawa::ilp::Constraint::add().
void otawa::ilp::Constraint::add (const Expression & e) inherited
void Constraint::setComparator(comparator_t comp); Change the comparator of the constraint.
Parameters
comp Comparator to set.
Since
ILP interface 1.2.0 void Constraint::setLabel(const string& label); Change the label of the constraint.
Parameters
label Label to set.
Since
ILP interface 1.2.0 Add an expression to the left part of the constraint.
Parameters
e Added expression.
References otawa::ilp::Constraint::add().
void otawa::ilp::Constraint::addLeft (double coef, Var * var = 0) inline inherited
Add a factor on the left side.
Parameters
coef Coefficient of the factor.
var Variable of the factor.
References otawa::ilp::Constraint::add().
Referenced by otawa::ccg::ConstraintBuilder::addConstraintHeader(), otawa::etime::EdgeTimeBuilder::contributeSplit(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::ipet::CachePenaltiesObjectFunctionBuilder::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::tsim::Delta::processBBPath(), otawa::cat::CATConstraintBuilder::processLBlockSet(), otawa::ccg::ConstraintBuilder::processLBlockSet(), otawa::EdgeCAT2ConstraintBuilder::processWorkSpace(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), and otawa::dcache::CatConstraintBuilder::processWorkSpace().
void otawa::ilp::Constraint::addRight (double coef, Var * var = 0) inline inherited
Add a factor on the right side.
Parameters
coef Coefficient of the factor.
var Variable of the factor.
References otawa::ilp::Constraint::add(), otawa::ilp::Constraint::label(), otawa::ilp::Constraint::setComparator(), and otawa::ilp::Constraint::setLabel().
Referenced by otawa::ccg::ConstraintBuilder::addConstraintHeader(), otawa::etime::EdgeTimeBuilder::contributeSplit(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::etime::EventCollector::make(), otawa::ipet::CachePenaltiesObjectFunctionBuilder::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::tsim::Delta::processBBPath(), otawa::cat::CATConstraintBuilder::processLBlockSet(), otawa::ccg::ConstraintBuilder::processLBlockSet(), otawa::EdgeCAT2ConstraintBuilder::processWorkSpace(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), and otawa::dcache::CatConstraintBuilder::processWorkSpace().
double otawa::ilp::ConstraintImpl::coefficient (Var * var) virtual
References expr.
double otawa::ilp::Constraint::coefficient (Var * var = 0) const pure virtual inherited
Get the coefficient for the given variable.
Parameters
var Variable to get the coefficent of. Null variable allows getting the constant part.
Returns
Variable coefficient.
Implemented in otawa::ilp::AbstractConstraint.
Referenced by otawa::ilp::Constraint::~Constraint().
Constraint::comparator_t otawa::ilp::ConstraintImpl::comparator (void) const virtual
Get the constraint comparator.
Returns
Constraint comparator.
Implements otawa::ilp::Constraint.
References comp.
double otawa::ilp::ConstraintImpl::constant (void) const virtual
Implements otawa::ilp::Constraint.
References expr.
const string & otawa::ilp::ConstraintImpl::label (void) const virtual
Implements otawa::ilp::Constraint.
References lab.
virtual void otawa::ilp::Constraint::setComparator (comparator_t comp) pure virtual inherited
Referenced by otawa::ilp::Constraint::addRight().
virtual void otawa::ilp::Constraint::setLabel (const string & label) pure virtual inherited
Implemented in otawa::ilp::AbstractConstraint.
Referenced by otawa::ilp::Constraint::addRight(), and otawa::ilp::model::operator()().
void otawa::ilp::ConstraintImpl::sub (double coef, Var * var) virtual
Substact a factor from the constraint.
Parameters
coef Coefficient of the factor.
var Variable of the factor.
Implements otawa::ilp::Constraint.
References otawa::ilp::Expression::add(), and expr.
void otawa::ilp::Constraint::sub (const Term & t) inline inherited
References otawa::ilp::Constraint::add(), otawa::ilp::Term::fst, otawa::ilp::Term::snd, and otawa::ilp::Constraint::sub().
Referenced by otawa::ilp::Constraint::sub().
void otawa::ilp::Constraint::sub (const Expression & e) inherited
Subtract an expression from the left part of the constraint.
Parameters
e Subtracted expression.
References otawa::ilp::Constraint::sub().
elm::datastruct::IteratorInst< Term > * otawa::ilp::ConstraintImpl::terms (void) virtual
Implements otawa::ilp::Constraint.
References expr.
Member Data Documentation
comparator_t otawa::ilp::ConstraintImpl::comp private
Referenced by comparator().
Expression otawa::ilp::ConstraintImpl::expr private
Referenced by add(), coefficient(), constant(), sub(), and terms().
string otawa::ilp::ConstraintImpl::lab private
Referenced by label().
The documentation for this class was generated from the following files:
include/otawa/ilp/impl.h
src/prog/ilp_impl.cpp