Otawa: otawa::PERSBranch Class Reference
otawa::PERSBranch Class Reference
#include <otawa/branch/BranchProblem.h>
Classes
class Domain
class Item
Public Member Functions
PERSBranch (const int _size, WorkSpace *_fw, const int _A, const int _row)
~PERSBranch ()
const Domain & bottom (void) const
const Domain & entry (void) const
void lub (Domain &a, const Domain &b) const
void assign (Domain &a, const Domain &b) const
bool equals (const Domain &a, const Domain &b) const
void update (Domain &out, const Domain &in, BasicBlock *bb)
void enterContext (Domain &dom, BasicBlock *header, util::hai_context_t ctx)
void leaveContext (Domain &dom, BasicBlock *header, util::hai_context_t ctx)
Private Attributes
int row
WorkSpace * fw
Domain bot
Domain ent
Constructor & Destructor Documentation
otawa::PERSBranch::PERSBranch (const int _size, WorkSpace * _fw, const int _A, const int _row)
References bot, otawa::PERSBranch::Domain::empty(), ent, and otawa::PERSBranch::Domain::setToBottom().
otawa::PERSBranch::~PERSBranch ()
Member Function Documentation
void otawa::PERSBranch::assign (Domain & a, const Domain & b) const inline
Referenced by otawa::BranchProblem::BranchProblem().
const PERSBranch::Domain & otawa::PERSBranch::bottom (void) const
References bot.
Referenced by otawa::BranchProblem::BranchProblem().
void otawa::PERSBranch::enterContext (Domain & dom, BasicBlock * header, util::hai_context_t ctx) inline
References otawa::dfa::hai::CTX_LOOP, and otawa::PERSBranch::Domain::enterContext().
Referenced by otawa::BranchProblem::enterContext().
const PERSBranch::Domain & otawa::PERSBranch::entry (void) const
References ent.
Referenced by otawa::BranchProblem::BranchProblem().
bool otawa::PERSBranch::equals (const Domain & a, const Domain & b) const inline
References otawa::cfgio::bb(), otawa::PERSBranch::Domain::equals(), and otawa::MUSTBranch::update().
void otawa::PERSBranch::leaveContext (Domain & dom, BasicBlock * header, util::hai_context_t ctx) inline
References otawa::dfa::hai::CTX_LOOP, and otawa::PERSBranch::Domain::leaveContext().
Referenced by otawa::BranchProblem::leaveContext().
void otawa::PERSBranch::lub (Domain & a, const Domain & b) const inline
References otawa::PERSBranch::Domain::lub().
void otawa::PERSBranch::update (Domain & out, const Domain & in, BasicBlock * bb)
Member Data Documentation
Domain otawa::PERSBranch::bot private
Referenced by bottom(), and PERSBranch().
Domain otawa::PERSBranch::ent private
Referenced by entry(), and PERSBranch().
WorkSpace* otawa::PERSBranch::fw private
int otawa::PERSBranch::row private
The documentation for this class was generated from the following files:
include/otawa/branch/BranchProblem.h
src/branch/branch_BranchProblem.cpp