Otawa: otawa::ContextualStep Class Reference
otawa::ContextualStep Class Reference
#include <otawa/prop/ContextualProperty.h>
Public Types
enum kind_t {
NONE = 0, FUNCTION, CALL, FIRST_ITER,
OTHER_ITER
}
typedef enum otawa::ContextualStep::kind_t kind_t
Public Member Functions
ContextualStep (void)
ContextualStep (kind_t kind, const Address &address)
ContextualStep (const ContextualStep &step)
ContextualStep & operator= (const ContextualStep &step)
kind_t kind (void) const
const Address & address (void) const
bool equals (const ContextualStep &step) const
bool operator== (const ContextualStep &step) const
bool operator!= (const ContextualStep &step) const
void print (io::Output &out) const
Private Attributes
kind_t _kind
Address addr
Member Typedef Documentation
typedef enum otawa::ContextualStep::kind_t otawa::ContextualStep::kind_t
Member Enumeration Documentation
enum otawa::ContextualStep::kind_t
Enumerator
NONE
FUNCTION
CALL
FIRST_ITER
OTHER_ITER
Constructor & Destructor Documentation
otawa::ContextualStep::ContextualStep (void) inline
otawa::ContextualStep::ContextualStep (kind_t kind, const Address & address) inline
otawa::ContextualStep::ContextualStep (const ContextualStep & step) inline
Member Function Documentation
const Address& otawa::ContextualStep::address (void) const inline
Referenced by equals().
bool otawa::ContextualStep::equals (const ContextualStep & step) const inline
References address(), and kind().
kind_t otawa::ContextualStep::kind (void) const inline
Referenced by equals(), and otawa::ContextualPath::getEnclosingFunction().
bool otawa::ContextualStep::operator!= (const ContextualStep & step) const inline
ContextualStep& otawa::ContextualStep::operator= (const ContextualStep & step) inline
References _kind, and addr.
bool otawa::ContextualStep::operator== (const ContextualStep & step) const inline
void otawa::ContextualStep::print (io::Output & out) const
References _kind, addr, CALL, FIRST_ITER, FUNCTION, NONE, and OTHER_ITER.
Referenced by otawa::operator<<().
Member Data Documentation
kind_t otawa::ContextualStep::_kind private
Referenced by operator=(), and print().
Address otawa::ContextualStep::addr private
Referenced by operator=(), and print().
The documentation for this class was generated from the following files:
include/otawa/prop/ContextualProperty.h
src/prog/prop_ContextualProperty.cpp