Otawa: otawa::MAYBranch Class Reference
otawa::MAYBranch Class Reference
#include <otawa/branch/BranchProblem.h>
Classes
class Domain
Public Member Functions
MAYBranch (const int _size, WorkSpace *_fw, const int _A, const int _row)
~MAYBranch ()
const Domain & bottom (void) const
const Domain & entry (void) const
void lub (Domain &a, const Domain &b) const
void assign (Domain &a, const Domain &b) const
bool equals (const Domain &a, const Domain &b) const
void update (Domain &out, const Domain &in, BasicBlock *bb)
void enterContext (Domain &dom, BasicBlock *header, util::hai_context_t ctx)
void leaveContext (Domain &dom, BasicBlock *header, util::hai_context_t ctx)
Private Attributes
int row
WorkSpace * fw
Domain bot
Domain ent
Constructor & Destructor Documentation
otawa::MAYBranch::MAYBranch (const int _size, WorkSpace * _fw, const int _A, const int _row)
References otawa::MAYBranch::Domain::empty(), and ent.
otawa::MAYBranch::~MAYBranch ()
Member Function Documentation
void otawa::MAYBranch::assign (Domain & a, const Domain & b) const inline
const MAYBranch::Domain & otawa::MAYBranch::bottom (void) const
References bot.
void otawa::MAYBranch::enterContext (Domain & dom, BasicBlock * header, util::hai_context_t ctx) inline
Referenced by otawa::BranchProblem::enterContext().
const MAYBranch::Domain & otawa::MAYBranch::entry (void) const
References ent.
bool otawa::MAYBranch::equals (const Domain & a, const Domain & b) const inline
References otawa::cfgio::bb(), otawa::MAYBranch::Domain::equals(), and otawa::MUSTBranch::update().
void otawa::MAYBranch::leaveContext (Domain & dom, BasicBlock * header, util::hai_context_t ctx) inline
Referenced by otawa::BranchProblem::leaveContext().
void otawa::MAYBranch::lub (Domain & a, const Domain & b) const inline
References otawa::MAYBranch::Domain::lub().
void otawa::MAYBranch::update (Domain & out, const Domain & in, BasicBlock * bb)
Member Data Documentation
Domain otawa::MAYBranch::bot private
Referenced by bottom().
Domain otawa::MAYBranch::ent private
Referenced by entry(), and MAYBranch().
WorkSpace* otawa::MAYBranch::fw private
int otawa::MAYBranch::row private
The documentation for this class was generated from the following files:
include/otawa/branch/BranchProblem.h
src/branch/branch_BranchProblem.cpp