Otawa: otawa::MUSTBranch Class Reference
otawa::MUSTBranch Class Reference
#include <otawa/branch/BranchProblem.h>
Classes
class Domain
Public Member Functions
MUSTBranch (const int _size, WorkSpace *_fw, const int _A, const int _row)
~MUSTBranch ()
const Domain & bottom (void) const
const Domain & entry (void) const
void lub (Domain &a, const Domain &b) const
void assign (Domain &a, const Domain &b) const
bool equals (const Domain &a, const Domain &b) const
void update (Domain &out, const Domain &in, BasicBlock *bb)
void enterContext (Domain &dom, BasicBlock *header, util::hai_context_t ctx)
void leaveContext (Domain &dom, BasicBlock *header, util::hai_context_t ctx)
Private Attributes
int row
WorkSpace * fw
Domain bot
Domain ent
Constructor & Destructor Documentation
otawa::MUSTBranch::MUSTBranch (const int _size, WorkSpace * _fw, const int _A, const int _row)
References otawa::MUSTBranch::Domain::empty(), and ent.
otawa::MUSTBranch::~MUSTBranch ()
Member Function Documentation
void otawa::MUSTBranch::assign (Domain & a, const Domain & b) const inline
Referenced by otawa::BranchProblem::BranchProblem().
const MUSTBranch::Domain & otawa::MUSTBranch::bottom (void) const
References bot.
Referenced by otawa::BranchProblem::BranchProblem().
void otawa::MUSTBranch::enterContext (Domain & dom, BasicBlock * header, util::hai_context_t ctx) inline
Referenced by otawa::BranchProblem::enterContext().
const MUSTBranch::Domain & otawa::MUSTBranch::entry (void) const
References ent.
Referenced by otawa::BranchProblem::BranchProblem().
bool otawa::MUSTBranch::equals (const Domain & a, const Domain & b) const inline
References otawa::cfgio::bb(), otawa::MUSTBranch::Domain::equals(), and update().
void otawa::MUSTBranch::leaveContext (Domain & dom, BasicBlock * header, util::hai_context_t ctx) inline
Referenced by otawa::BranchProblem::leaveContext().
void otawa::MUSTBranch::lub (Domain & a, const Domain & b) const inline
References otawa::MUSTBranch::Domain::lub().
void otawa::MUSTBranch::update (Domain & out, const Domain & in, BasicBlock * bb)
Referenced by equals(), otawa::MAYBranch::equals(), otawa::PERSBranch::equals(), and otawa::BranchProblem::equals().
Member Data Documentation
Domain otawa::MUSTBranch::bot private
Referenced by bottom().
Domain otawa::MUSTBranch::ent private
Referenced by entry(), and MUSTBranch().
WorkSpace* otawa::MUSTBranch::fw private
int otawa::MUSTBranch::row private
The documentation for this class was generated from the following files:
include/otawa/branch/BranchProblem.h
src/branch/branch_BranchProblem.cpp