Otawa: otawa::AbstractIdentifier Class Reference
otawa::AbstractIdentifier Class Reference
Properties System
Represents a unique identifier used by the annotation system.
#include <otawa/prop/AbstractIdentifier.h>
Public Member Functions
AbstractIdentifier (void)
Build an anonymous identifier.
AbstractIdentifier (cstring name)
Build a new identifier.
AbstractIdentifier (cstring name, const PropList &props)
Initialize an identifier with a property list (mainly useful for named object deriving from AbstractIdentifier).
virtual ~AbstractIdentifier (void)
const string name (void) const
Get the string name of the identifier.
void print (elm::io::Output &out) const
Print the identifier.
virtual void print (elm::io::Output &output, const Property *prop) const
Print the value of the given property (accordint the property matches the given identifier).
void print (elm::io::Output &output, const Property &prop) const
virtual void printFormatted (io::Output &out, const Property *prop) const
Print the value of the given property in a formatted way, that is, possibly to perform re-scanning after.
void printFormatted (elm::io::Output &output, const Property &prop) const
virtual const Type & type (void) const
Get the identifier of data linked with this property.
virtual void fromString (PropList &props, const string &str) const
Get value of an identifier from a string and store it in the given property list.
virtual bool equals (const Property *prop1, const Property *prop2) const
Test if two properties are equal.
virtual Property * copy (Property &prop) const
Build a copy of the given property.
Property * copy (Property *prop) const
virtual void serialize (Property *prop, elm::serial2::Serializer &serializer)
Serialize the workspace to the current serializer.
virtual Property * unserialize (elm::serial2::Unserializer &unserializer)
Unserialize the workspace to the current unserializer.
AbstractIdentifier (cstring name, Property *prop, VarArg &args)
Build an identifier with the given name and properties read from the given arguments that must be a list of Property * pointer (1) ended by a null identifier pointer and (2) and will be released by the current identifier.
Property * getProp (const AbstractIdentifier *id) const
Find a property by its identifier.
void setProp (Property *prop)
Set the property in the property list removing any double.
void setProp (const AbstractIdentifier *id)
void removeProp (const AbstractIdentifier *id)
Remove a property matching the given identifier.
void removeProp (const AbstractIdentifier &id)
Property * extractProp (const AbstractIdentifier *id)
Remove a property matching the given identifier and return it.
Property * extractProp (const AbstractIdentifier &id)
Remove a property matching the given identifier and return it.
void addProp (Property *prop)
Add property to the list without checking of duplication.
void removeAllProp (const AbstractIdentifier *id)
Remove all the properties matching the given identifier.
bool hasProp (const AbstractIdentifier &id) const
Test if the property list contains a property matching the given identifier.
void clearProps (void)
Remove all properties from the list.
void addProps (const PropList &props)
Add all properties from the given property list, in a reverse order.
Static Public Member Functions
static AbstractIdentifier * find (const string &name)
Find an abstract identifier by its name.
Static Public Attributes
static const PropList EMPTY
This is an empty proplist for convenience.
Protected Member Functions
void initProps (Property *prop, VarArg &args)
Add the properties found in the arguments (list of Property * ended by null) to the identifier properties.
void initProps (const PropList &props)
Initialize properties coming from the constructor.
Private Member Functions
void initialize (void)
For internal use only.
Private Attributes
string nam
Friends
class elm::Initializer< AbstractIdentifier >
Detailed Description
Represents a unique identifier used by the annotation system.
Identifier pointers may be compared for testing equality.
Information on identifiers
To have nice display of identifier and their value, one can provide to the OTAWA identifier system informations for human reading. As an identifier is also a property list, one may attach properties with the following identifier: otawa::IDENTIFIER_LABEL – a short label to display in front of the property value, otawa::IDENTIFIER_DESC – a more precise description of the identifier.
Both information may be set using some dedicated macros:
#include <otawa/prop/info.h>
Identifier<int> MY_ID("MY_ID", 111);
SET_LABEL(MY_ID, "my identifier");
SET_DESC(MY_ID, "this is my identifier !");
Constructor & Destructor Documentation
otawa::AbstractIdentifier::AbstractIdentifier (void)
Build an anonymous identifier.
Referenced by copy().
otawa::AbstractIdentifier::AbstractIdentifier (cstring name)
Build a new identifier.
Only one identifier may exists in the OTAWA with a given name. If there is a name clash, the framework will immediatelly be stopped.
Parameters
name Name of the identifier.
parent Parent namespace.
otawa::AbstractIdentifier::AbstractIdentifier (cstring name, const PropList & props)
Initialize an identifier with a property list (mainly useful for named object deriving from AbstractIdentifier).
Parameters
name Identifier name (possibly empty).
props Configuration properties.
References initProps().
virtual otawa::AbstractIdentifier::~AbstractIdentifier (void) inline virtual
otawa::AbstractIdentifier::AbstractIdentifier (cstring name, Property * prop, VarArg & args)
Build an identifier with the given name and properties read from the given arguments that must be a list of Property * pointer (1) ended by a null identifier pointer and (2) and will be released by the current identifier.
Parameters
name Name of the identifier ("" for anonymous)
prop First property.
args Arguments to derive identifier properties.
References initProps().
Member Function Documentation
void otawa::PropList::addProp (Property * prop) inherited
Add property to the list without checking of duplication.
Parameters
prop Property to add.
References otawa::Property::_next.
Referenced by otawa::Identifier< T >::add(), otawa::ast::ASTInfo::ASTInfo(), otawa::Identifier< otawa::arm::Info * >::copy(), initProps(), otawa::ContextualProperty::make(), otawa::script::Script::makeConfig(), otawa::ccg::Builder::processLBlockSet(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), and otawa::ContextualProperty::refProps().
void otawa::PropList::addProps (const PropList & props) inherited
Add all properties from the given property list, in a reverse order.
Parameters
props Property list to clone.
References otawa::Property::copy(), otawa::PropList::head, and otawa::Property::next().
Referenced by otawa::display::CFGDrawer::CFGDrawer(), otawa::display::GraphVizGraph::GraphVizGraph(), otawa::ParamFeature::instantiate(), otawa::Manager::loadXML(), otawa::display::GraphVizGraph::newEdge(), otawa::display::GraphVizGraph::newNode(), otawa::Process::Process(), otawa::display::GraphVizItem::setProps(), otawa::VirtualBasicBlock::VirtualBasicBlock(), and otawa::VirtualCFG::VirtualCFG().
void otawa::PropList::clearProps (void) inherited
Remove all properties from the list.
References otawa::Property::next().
Referenced by otawa::PSTBuilder::getVCFG(), otawa::display::GraphVizItem::setProps(), and otawa::WorkSpace::~WorkSpace().
Property * otawa::AbstractIdentifier::copy (Property & prop) const virtual
Build a copy of the given property.
Parameters
prop Property to copy.
Returns
Copy of the property.
Reimplemented in otawa::Identifier< T >, otawa::Identifier< otawa::ccg::Node * >, otawa::Identifier< typename Problem::Domain * >, otawa::Identifier< dfa::BitSet * >, otawa::Identifier< double >, otawa::Identifier< otawa::CFG * >, otawa::Identifier< otawa::ast::AST * >, otawa::Identifier< init_t >, otawa::Identifier< otawa::Microprocessor< ExeNode > * >, otawa::Identifier< otawa::ccg::Collection * >, otawa::Identifier< Domain * >, otawa::Identifier< AbstractParamProcessor * >, otawa::Identifier< otawa::CFGInfo * >, otawa::Identifier< BracketSet * >, otawa::Identifier< elm::io::OutStream * >, otawa::Identifier< otawa::StatInfo * >, otawa::Identifier< int >, otawa::Identifier< T * >, otawa::Identifier< otawa::PropList * >, otawa::Identifier< String >, otawa::Identifier< elm::system::time_t >, otawa::Identifier< display::kind_t >, otawa::Identifier< typename P::Domain * >, otawa::Identifier< Path >, otawa::Identifier< string >, otawa::Identifier< typename otawa::dfa::hai::FirstUnrollingFixPoint::FixPointState * >, otawa::Identifier< CString >, otawa::Identifier< elm::system::Path >, otawa::Identifier< otawa::PCG * >, otawa::Identifier< otawa::BasicBlock * >, otawa::Identifier< Processor * >, otawa::Identifier< otawa::tsim::TreePath< otawa::BasicBlock *, otawa::tsim::BBPath * > * >, otawa::Identifier< log_level_t >, otawa::Identifier< otawa::CEClass * >, otawa::Identifier< bool >, otawa::Identifier< otawa::AbstractParamIdentifier * >, otawa::Identifier< typename otawa::dfa::hai::WideningFixPoint::FixPointState * >, otawa::Identifier< otawa::Progress * >, otawa::Identifier< typename otawa::dfa::hai::DefaultFixPoint::FixPointState * >, otawa::Identifier< typename FixPoint::FixPointState * >, otawa::Identifier< otawa::Symbol * >, otawa::Identifier< otawa::display::ILPSystemAddon * >, otawa::Identifier< AbstractIdentifier * >, otawa::Identifier< elm::io::Output * >, and otawa::Identifier< otawa::arm::Info * >.
Referenced by printFormatted().
Property* otawa::AbstractIdentifier::copy (Property * prop) const inline
References AbstractIdentifier(), copy(), initProps(), name(), serialize(), and unserialize().
Referenced by copy().
bool otawa::AbstractIdentifier::equals (const Property * prop1, const Property * prop2) const virtual
Test if two properties are equal.
Parameters
prop1 First property.
prop2 Second property.
Returns
True if they are equal, false else.
Referenced by printFormatted().
Property * otawa::PropList::extractProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::script::Script::makeConfig().
Property * otawa::PropList::extractProp (const AbstractIdentifier & id) inline inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::PropList::extractProp().
Referenced by otawa::PropList::extractProp().
AbstractIdentifier * otawa::AbstractIdentifier::find (const string & name) static
Find an abstract identifier by its name.
Parameters
name Name of the looked identifier.
Returns
Found identifier or null.
Referenced by otawa::ProcessorPlugin::getIdentifier(), and otawa::Application::run().
void otawa::AbstractIdentifier::fromString (PropList & props, const string & str) const virtual
Get value of an identifier from a string and store it in the given property list.
Parameters
props Property list to store result into.
str String to get value from.
Reimplemented in otawa::Identifier< T >, otawa::Identifier< otawa::ccg::Node * >, otawa::Identifier< typename Problem::Domain * >, otawa::Identifier< dfa::BitSet * >, otawa::Identifier< double >, otawa::Identifier< otawa::CFG * >, otawa::Identifier< otawa::ast::AST * >, otawa::Identifier< init_t >, otawa::Identifier< otawa::Microprocessor< ExeNode > * >, otawa::Identifier< otawa::ccg::Collection * >, otawa::Identifier< Domain * >, otawa::Identifier< AbstractParamProcessor * >, otawa::Identifier< otawa::CFGInfo * >, otawa::Identifier< BracketSet * >, otawa::Identifier< elm::io::OutStream * >, otawa::Identifier< otawa::StatInfo * >, otawa::Identifier< int >, otawa::Identifier< T * >, otawa::Identifier< otawa::PropList * >, otawa::Identifier< String >, otawa::Identifier< elm::system::time_t >, otawa::Identifier< display::kind_t >, otawa::Identifier< typename P::Domain * >, otawa::Identifier< Path >, otawa::Identifier< string >, otawa::Identifier< typename otawa::dfa::hai::FirstUnrollingFixPoint::FixPointState * >, otawa::Identifier< CString >, otawa::Identifier< elm::system::Path >, otawa::Identifier< otawa::PCG * >, otawa::Identifier< otawa::BasicBlock * >, otawa::Identifier< Processor * >, otawa::Identifier< otawa::tsim::TreePath< otawa::BasicBlock *, otawa::tsim::BBPath * > * >, otawa::Identifier< log_level_t >, otawa::Identifier< otawa::CEClass * >, otawa::Identifier< bool >, otawa::Identifier< otawa::AbstractParamIdentifier * >, otawa::Identifier< typename otawa::dfa::hai::WideningFixPoint::FixPointState * >, otawa::Identifier< otawa::Progress * >, otawa::Identifier< typename otawa::dfa::hai::DefaultFixPoint::FixPointState * >, otawa::Identifier< typename FixPoint::FixPointState * >, otawa::Identifier< otawa::Symbol * >, otawa::Identifier< otawa::display::ILPSystemAddon * >, otawa::Identifier< AbstractIdentifier * >, otawa::Identifier< elm::io::Output * >, otawa::Identifier< otawa::arm::Info * >, and otawa::Identifier< T >.
References name().
Referenced by printFormatted().
Property * otawa::PropList::getProp (const AbstractIdentifier * id) const inherited
Find a property by its identifier.
Parameters
id Identifier of the property to find.
Returns
Found property or null.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::Identifier< otawa::arm::Info * >::exists(), otawa::ContextualProperty::exists(), otawa::ContextualProperty::find(), otawa::Identifier< T >::get(), otawa::ContextualProperty::make(), otawa::ParamFeature::matches(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::print(), otawa::ContextualProperty::print(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), otawa::ContextualProperty::refProps(), otawa::Identifier< T >::set(), otawa::Identifier< T >::use(), and otawa::Identifier< T >::value().
bool otawa::PropList::hasProp (const AbstractIdentifier & id) const inline inherited
Test if the property list contains a property matching the given identifier.
Parameters
id Property identifier to look for.
Returns
True if the list contains the matching property, false else.
References otawa::p::print().
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::Monitor::configure(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::exists(), and otawa::Manager::setVerbosity().
void otawa::AbstractIdentifier::initialize (void) private
For internal use only.
References otawa::Type::bool_type, otawa::Type::char_type, otawa::Type::cstring_type, otawa::IDENTIFIER_DESC, otawa::IDENTIFIER_ID, otawa::IDENTIFIER_LABEL, otawa::Type::int32_type, otawa::Type::int64_type, nam, TRACE, and otawa::Identifier< T >::type().
void otawa::AbstractIdentifier::initProps (Property * prop, VarArg & args) protected
Add the properties found in the arguments (list of Property * ended by null) to the identifier properties.
Parameters
prop First property.
args Null-ended properties to scan.
References otawa::PropList::addProp(), and otawa::Property::next().
Referenced by AbstractIdentifier(), and copy().
void otawa::AbstractIdentifier::initProps (const PropList & props) protected
Initialize properties coming from the constructor.
References otawa::IDENTIFIER_ID, and nam.
const elm::String & otawa::AbstractIdentifier::name (void) const inline
Get the string name of the identifier.
Returns
Identifier name.
References nam, and print().
Referenced by otawa::AlternativeProcessor::AlternativeProcessor(), copy(), fromString(), otawa::ParamProcessor::instantiate(), otawa::WorkSpace::provide(), otawa::hard::Platform::Identification::split(), and otawa::ParamProcessor::AbstractMaker::~AbstractMaker().
void otawa::AbstractIdentifier::print (elm::io::Output & out) const
Print the identifier.
Parameters
out Output stream.
References nam.
Referenced by otawa::display::GraphVizItem::getPropertiesString(), and name().
void otawa::AbstractIdentifier::print (elm::io::Output & output, const Property * prop) const virtual
Print the value of the given property (accordint the property matches the given identifier).
It is an error to call this method with a property matching a different identifier.
Use the print() method of a property instead.
Reimplemented in otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< otawa::ccg::Node * >, otawa::Identifier< typename Problem::Domain * >, otawa::Identifier< dfa::BitSet * >, otawa::Identifier< double >, otawa::Identifier< otawa::CFG * >, otawa::Identifier< otawa::ast::AST * >, otawa::Identifier< init_t >, otawa::Identifier< otawa::Microprocessor< ExeNode > * >, otawa::Identifier< otawa::ccg::Collection * >, otawa::Identifier< Domain * >, otawa::Identifier< AbstractParamProcessor * >, otawa::Identifier< otawa::CFGInfo * >, otawa::Identifier< BracketSet * >, otawa::Identifier< elm::io::OutStream * >, otawa::Identifier< otawa::StatInfo * >, otawa::Identifier< int >, otawa::Identifier< T * >, otawa::Identifier< otawa::PropList * >, otawa::Identifier< String >, otawa::Identifier< elm::system::time_t >, otawa::Identifier< display::kind_t >, otawa::Identifier< typename P::Domain * >, otawa::Identifier< Path >, otawa::Identifier< string >, otawa::Identifier< typename otawa::dfa::hai::FirstUnrollingFixPoint::FixPointState * >, otawa::Identifier< CString >, otawa::Identifier< elm::system::Path >, otawa::Identifier< otawa::PCG * >, otawa::Identifier< otawa::BasicBlock * >, otawa::Identifier< Processor * >, otawa::Identifier< otawa::tsim::TreePath< otawa::BasicBlock *, otawa::tsim::BBPath * > * >, otawa::Identifier< log_level_t >, otawa::Identifier< otawa::CEClass * >, otawa::Identifier< bool >, otawa::Identifier< otawa::AbstractParamIdentifier * >, otawa::Identifier< typename otawa::dfa::hai::WideningFixPoint::FixPointState * >, otawa::Identifier< otawa::Progress * >, otawa::Identifier< typename otawa::dfa::hai::DefaultFixPoint::FixPointState * >, otawa::Identifier< typename FixPoint::FixPointState * >, otawa::Identifier< otawa::Symbol * >, otawa::Identifier< otawa::display::ILPSystemAddon * >, otawa::Identifier< AbstractIdentifier * >, otawa::Identifier< elm::io::Output * >, and otawa::Identifier< otawa::arm::Info * >.
void otawa::AbstractIdentifier::print (elm::io::Output & output, const Property & prop) const inline
References print(), and printFormatted().
Referenced by print().
void otawa::AbstractIdentifier::printFormatted (io::Output & out, const Property * prop) const virtual
Print the value of the given property in a formatted way, that is, possibly to perform re-scanning after.
For example, string are quoted and special character escaped.
Parameters
out Output to use.
prop Property to display.
Reimplemented in otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< otawa::ccg::Node * >, otawa::Identifier< typename Problem::Domain * >, otawa::Identifier< dfa::BitSet * >, otawa::Identifier< double >, otawa::Identifier< otawa::CFG * >, otawa::Identifier< otawa::ast::AST * >, otawa::Identifier< init_t >, otawa::Identifier< otawa::Microprocessor< ExeNode > * >, otawa::Identifier< otawa::ccg::Collection * >, otawa::Identifier< Domain * >, otawa::Identifier< AbstractParamProcessor * >, otawa::Identifier< otawa::CFGInfo * >, otawa::Identifier< BracketSet * >, otawa::Identifier< elm::io::OutStream * >, otawa::Identifier< otawa::StatInfo * >, otawa::Identifier< int >, otawa::Identifier< T * >, otawa::Identifier< otawa::PropList * >, otawa::Identifier< String >, otawa::Identifier< elm::system::time_t >, otawa::Identifier< display::kind_t >, otawa::Identifier< typename P::Domain * >, otawa::Identifier< Path >, otawa::Identifier< string >, otawa::Identifier< typename otawa::dfa::hai::FirstUnrollingFixPoint::FixPointState * >, otawa::Identifier< CString >, otawa::Identifier< elm::system::Path >, otawa::Identifier< otawa::PCG * >, otawa::Identifier< otawa::BasicBlock * >, otawa::Identifier< Processor * >, otawa::Identifier< otawa::tsim::TreePath< otawa::BasicBlock *, otawa::tsim::BBPath * > * >, otawa::Identifier< log_level_t >, otawa::Identifier< otawa::CEClass * >, otawa::Identifier< bool >, otawa::Identifier< otawa::AbstractParamIdentifier * >, otawa::Identifier< typename otawa::dfa::hai::WideningFixPoint::FixPointState * >, otawa::Identifier< otawa::Progress * >, otawa::Identifier< typename otawa::dfa::hai::DefaultFixPoint::FixPointState * >, otawa::Identifier< typename FixPoint::FixPointState * >, otawa::Identifier< otawa::Symbol * >, otawa::Identifier< otawa::display::ILPSystemAddon * >, otawa::Identifier< AbstractIdentifier * >, otawa::Identifier< elm::io::Output * >, and otawa::Identifier< otawa::arm::Info * >.
Referenced by print().
void otawa::AbstractIdentifier::printFormatted (elm::io::Output & output, const Property & prop) const inline
References copy(), equals(), fromString(), printFormatted(), and type().
Referenced by printFormatted().
void otawa::PropList::removeAllProp (const AbstractIdentifier * id) inherited
Remove all the properties matching the given identifier.
Parameters
id Identifier of properties to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::LoopUnroller::unroll().
void otawa::PropList::removeProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier.
Parameters
id Identifier of the property to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::PSTBuilder::buildTree(), otawa::BBRemover< T >::clean(), otawa::CFGBuilder::cleanup(), otawa::display::CFGOutput::processCFG(), otawa::SubCFGBuilder::processWorkSpace(), otawa::Identifier< otawa::arm::Info * >::remove(), and otawa::ContextualPath::Ref< T >::remove().
void otawa::PropList::removeProp (const AbstractIdentifier & id) inline inherited
References otawa::PropList::removeProp().
Referenced by otawa::PropList::removeProp().
void otawa::AbstractIdentifier::serialize (Property * prop, elm::serial2::Serializer & serializer) virtual
Serialize the workspace to the current serializer.
In the default implementation, do nothing.
Parameters
prop Property containing the value to serialize.
serializer Serializer to serialize to.
Referenced by copy().
void otawa::PropList::setProp (Property * prop) inherited
Set the property in the property list removing any double.
Parameters
prop Property to set.
References otawa::Property::_next, otawa::Property::id(), and otawa::Property::next().
void otawa::PropList::setProp (const AbstractIdentifier * id) inline inherited
References otawa::PropList::setProp().
Referenced by otawa::PropList::setProp().
const Type & otawa::AbstractIdentifier::type (void) const virtual
Get the identifier of data linked with this property.
It may return Type::no_type ever meaning that the identifier does not support type system or that it is just a flag without associated data.
Returns
Type of the associated data.
Reimplemented in otawa::Identifier< T >, otawa::Identifier< otawa::ccg::Node * >, otawa::Identifier< typename Problem::Domain * >, otawa::Identifier< dfa::BitSet * >, otawa::Identifier< double >, otawa::Identifier< otawa::CFG * >, otawa::Identifier< otawa::ast::AST * >, otawa::Identifier< init_t >, otawa::Identifier< otawa::Microprocessor< ExeNode > * >, otawa::Identifier< otawa::ccg::Collection * >, otawa::Identifier< Domain * >, otawa::Identifier< AbstractParamProcessor * >, otawa::Identifier< otawa::CFGInfo * >, otawa::Identifier< BracketSet * >, otawa::Identifier< elm::io::OutStream * >, otawa::Identifier< otawa::StatInfo * >, otawa::Identifier< int >, otawa::Identifier< T * >, otawa::Identifier< otawa::PropList * >, otawa::Identifier< String >, otawa::Identifier< elm::system::time_t >, otawa::Identifier< display::kind_t >, otawa::Identifier< typename P::Domain * >, otawa::Identifier< Path >, otawa::Identifier< string >, otawa::Identifier< typename otawa::dfa::hai::FirstUnrollingFixPoint::FixPointState * >, otawa::Identifier< CString >, otawa::Identifier< elm::system::Path >, otawa::Identifier< otawa::PCG * >, otawa::Identifier< otawa::BasicBlock * >, otawa::Identifier< Processor * >, otawa::Identifier< otawa::tsim::TreePath< otawa::BasicBlock *, otawa::tsim::BBPath * > * >, otawa::Identifier< log_level_t >, otawa::Identifier< otawa::CEClass * >, otawa::Identifier< bool >, otawa::Identifier< otawa::AbstractParamIdentifier * >, otawa::Identifier< typename otawa::dfa::hai::WideningFixPoint::FixPointState * >, otawa::Identifier< otawa::Progress * >, otawa::Identifier< typename otawa::dfa::hai::DefaultFixPoint::FixPointState * >, otawa::Identifier< typename FixPoint::FixPointState * >, otawa::Identifier< otawa::Symbol * >, otawa::Identifier< otawa::display::ILPSystemAddon * >, otawa::Identifier< AbstractIdentifier * >, otawa::Identifier< elm::io::Output * >, and otawa::Identifier< otawa::arm::Info * >.
References otawa::Type::no_type.
Referenced by printFormatted().
Property * otawa::AbstractIdentifier::unserialize (elm::serial2::Unserializer & unserializer) virtual
Unserialize the workspace to the current unserializer.
In the default implementation, do nothing.
Parameters
unserializer Unserializer to unserialize to.
Returns
Property result of unserialization, null if the property cannot be unserialized.
Referenced by copy().
Friends And Related Function Documentation
friend class elm::Initializer< AbstractIdentifier > friend
Member Data Documentation
const PropList otawa::PropList::EMPTY static inherited
This is an empty proplist for convenience.
Referenced by otawa::DynProcessor::configure(), otawa::ActualFeature::processor(), otawa::SilentFeature::SilentFeature(), otawa::Processor::version(), and otawa::display::Driver::~Driver().
string otawa::AbstractIdentifier::nam private
Referenced by initialize(), initProps(), name(), and print().
The documentation for this class was generated from the following files:
include/otawa/prop/AbstractIdentifier.h
src/prog/prop_AbstractIdentifier.cpp