Otawa: otawa::ccg::Problem Class Reference
otawa::ccg::Problem Class Reference
#include <otawa/ccg/DFA.h>
Public Types
typedef Domain domain_t
Public Member Functions
Problem (LBlockSet *_ccggraph, int _size, const hard::Cache *_cach, WorkSpace *_fw)
Domain * empty (void)
Domain * gen (CFG *cfg, BasicBlock *bb)
Domain * preserve (CFG *cfg, BasicBlock *bb)
void free (Domain *d)
Private Attributes
LBlockSet * ccggraph
const hard::Cache * cach
int size
WorkSpace * fw
Static Private Attributes
static int vars = 0
Member Typedef Documentation
typedef Domain otawa::ccg::Problem::domain_t
Constructor & Destructor Documentation
otawa::ccg::Problem::Problem (LBlockSet * _ccggraph, int _size, const hard::Cache * _cach, WorkSpace * _fw) inline
References otawa::dfa::BitSet::size().
Member Function Documentation
Domain* otawa::ccg::Problem::empty (void) inline
References otawa::cfgio::bb(), otawa::cfgio::cfg(), otawa::ccg::Domain::Domain(), otawa::ccg::Domain::reset(), and otawa::dfa::BitSet::size().
void otawa::ccg::Problem::free (Domain * d) inline
Domain * otawa::ccg::Problem::gen (CFG * cfg, BasicBlock * bb)
References otawa::dfa::BitSet::add(), otawa::ot::address(), otawa::cfgio::bb(), otawa::dfa::BitSet::count(), elm::dtd::empty, otawa::ENTRY_CFG, and otawa::BasicBlock::isEntry().
Domain * otawa::ccg::Problem::preserve (CFG * cfg, BasicBlock * bb)
References elm::dtd::empty, and otawa::dfa::BitSet::fill().
Member Data Documentation
const hard::Cache* otawa::ccg::Problem::cach private
LBlockSet* otawa::ccg::Problem::ccggraph private
WorkSpace* otawa::ccg::Problem::fw private
int otawa::ccg::Problem::size private
int otawa::ccg::Problem::vars = 0 static private
The documentation for this class was generated from the following files:
include/otawa/ccg/DFA.h
src/ccg/ccg_DFA.cpp