Otawa: otawa::ilp::AbstractSystem Class Reference
otawa::ilp::AbstractSystem Class Reference abstract
ILP -- Integer Linear Programming
This class provides a convenient way to handle ILP systems in OTAWA.
#include <otawa/ilp/AbstractSystem.h>
Classes
class AbstractVar
class ConstIter
class VarIter
Public Member Functions
AbstractSystem (void)
virtual ~AbstractSystem (void)
virtual Constraint * newConstraint (Constraint::comparator_t comp, double constant)
Build a new constraint that may be initialized by the user.
virtual Constraint * newConstraint (const string &label, Constraint::comparator_t comp, double constant)
virtual void addObjectFunction (double coef, Var *var)
Add a factor to the object function.
virtual Var * newVar (const string &name)
virtual int countVars (void)
Count the number of variables in the system.
virtual int countConstraints (void)
Count the number of constraints in the system.
virtual elm::datastruct::IteratorInst< ilp::Constraint * > * constraints (void)
virtual elm::datastruct::IteratorInst< ilp::Constraint::Term > * objTerms (void)
virtual void exportLP (io::Output &out)
Export the system to the given output using the LP format (lp_solve).
virtual void dumpSolution (io::Output &out)
Dump the solution textually to the given output.
virtual Var * newVar (Var::type_t type, const string &name)
Build a new variable with the given type.
virtual bool solve (WorkSpace *ws=0)=0
Solve the ILP system.
virtual bool solve (WorkSpace *ws, otawa::Monitor &mon)
Solve the ILP system in the given workspace using the given monitor to output logs.
virtual double valueOf (Var *var)=0
This method can only be called after the resolution of the system and returns the value of a variable.
virtual double value (void)=0
Return the value of the optimized object function.
virtual void dumpSystem (io::Output &out=elm::cout)
Dump the system in text format (as a default, call exportLP).
virtual void dump (elm::io::OutStream &out=elm::io::out)
Dump the system to the given output.
void dump (format_t fmt, elm::io::OutStream &out=elm::io::out)
Dump the system to the given output and format.
virtual string lastErrorMessage (void)
Get the message of the last error.
virtual ILPPlugin * plugin (void)
Return the owner plugin.
bool hasDump (format_t fmt)
Tests if it is possible to dump in the given format.
void dumpLPSolve (elm::io::OutStream &out=elm::io::out)
Dump in LPSolve format.
void dumpCPlex (elm::io::OutStream &out=elm::io::out)
Dump system in CPlex format.
void dumpMOSEK (elm::io::OutStream &out=elm::io::out)
Dump in MOSEK format.
Protected Member Functions
int index (ilp::Var *var)
Get index (in the system storage table) of the variable.
Private Member Functions
void remove (AbstractConstraint *cons)
Remove a constraint from the system.
void remove (AbstractVar *var)
Remove a variable from the system.
Private Attributes
genstruct::FragTable< AbstractVar * > vars
genstruct::FragTable< AbstractConstraint * > conss
Expression obj
bool cleaning
Friends
class AbstractConstraint
class AbstractVar
Detailed Description
This class provides a convenient way to handle ILP systems in OTAWA.
The ILP system (constraints, variables) are stored in OTAWA the solve() method is called. This method is not provided by AbstractSystem but the implementation is left to a child class for customization: the child class can now visit the system and built the equivalent one in a particular solver.
Constructor & Destructor Documentation
otawa::ilp::AbstractSystem::AbstractSystem (void)
otawa::ilp::AbstractSystem::~AbstractSystem (void) virtual
References cleaning, conss, and vars.
Member Function Documentation
void otawa::ilp::AbstractSystem::addObjectFunction (double coef, Var * var) virtual
Add a factor to the object function.
Parameters
coef Coefficient of the factor.
var Variable of the factor.
Implements otawa::ilp::System.
References otawa::ilp::Expression::add(), and obj.
elm::datastruct::IteratorInst< Constraint * > * otawa::ilp::AbstractSystem::constraints (void) virtual
Implements otawa::ilp::System.
int otawa::ilp::AbstractSystem::countConstraints (void) virtual
Count the number of constraints in the system.
Returns
Constraint count.
Implements otawa::ilp::System.
References conss.
int otawa::ilp::AbstractSystem::countVars (void) virtual
Count the number of variables in the system.
Returns
Variable count.
Implements otawa::ilp::System.
References vars.
void otawa::ilp::System::dump (elm::io::OutStream & out = elm::io::out) virtual inherited
Dump the system to the given output.
The dumping format depends upon the actual used ILP engine. Usually, it is compatible with other tools of the ILP engine.
Parameters
out Used output.
Deprecated:
Use dumpSystem() and dumpSolution() instead.
Referenced by exportLP(), otawa::ilp::Output::processWorkSpace(), and otawa::ilp::System::~System().
void otawa::ilp::System::dump (format_t fmt, elm::io::OutStream & out = elm::io::out) inherited
Dump the system to the given output and format.
Parameters
out Used output.
fmt Used format
References otawa::ilp::CPLEX, otawa::ilp::DEFAULT, otawa::ilp::LP_SOLVE, and otawa::ilp::MOSEK.
void otawa::ilp::System::dumpCPlex (elm::io::OutStream & out = elm::io::out) inherited
Dump system in CPlex format.
Parameters
_out Output stream to use.
References otawa::ilp::Constraint::EQ, otawa::ilp::Constraint::GE, otawa::ilp::Constraint::GT, otawa::ilp::Constraint::LE, otawa::ilp::Constraint::LT, and otawa::sign().
Referenced by otawa::ilp::System::~System().
void otawa::ilp::System::dumpLPSolve (elm::io::OutStream & out = elm::io::out) inherited
Dump in LPSolve format.
Parameters
_out Output stream.
References otawa::ilp::Var::BIN, otawa::ilp::Constraint::comparator(), otawa::ilp::Constraint::constant(), otawa::ilp::Var::FLOAT, otawa::ilp::Var::INT, otawa::ilp::Constraint::label(), otawa::sem::neg(), and otawa::ilp::Constraint::terms().
Referenced by otawa::ilp::System::~System().
void otawa::ilp::System::dumpMOSEK (elm::io::OutStream & out = elm::io::out) inherited
Dump in MOSEK format.
Parameters
_out Output stream.
References otawa::ilp::Constraint::EQ, otawa::ilp::Constraint::GE, otawa::ilp::Constraint::GT, otawa::ilp::Constraint::LE, otawa::ilp::Constraint::LT, and otawa::sign().
Referenced by otawa::ilp::System::~System().
void otawa::ilp::AbstractSystem::dumpSolution (io::Output & out) virtual
Dump the solution textually to the given output.
Parameters
out Stream to output to (default to cout).
Implements otawa::ilp::System.
References otawa::ilp::System::valueOf(), and vars.
void otawa::ilp::System::dumpSystem (io::Output & out = elm::cout) virtual inherited
Dump the system in text format (as a default, call exportLP).
Parameters
out Stream to dump to (default to cout).
Referenced by otawa::ilp::System::~System().
void otawa::ilp::AbstractSystem::exportLP (io::Output & out) virtual
Export the system to the given output using the LP format (lp_solve).
Parameters
out Stream to export to (default to cout).
Implements otawa::ilp::System.
References otawa::ilp::CPLEX, and otawa::ilp::System::dump().
bool otawa::ilp::System::hasDump (format_t fmt) inherited
Tests if it is possible to dump in the given format.
Parameters
fmt Used format
Returns
Boolean
References otawa::ilp::CPLEX, otawa::ilp::DEFAULT, otawa::ilp::LP_SOLVE, and otawa::ilp::MOSEK.
Referenced by otawa::ilp::System::~System().
int otawa::ilp::AbstractSystem::index (ilp::Var * var) protected
Get index (in the system storage table) of the variable.
This method is useful to associate AbstractSystem variables with the underlying ILP system.
Parameters
var Variable to get index for.
Returns
Variable index.
string otawa::ilp::System::lastErrorMessage (void) virtual inherited
Get the message of the last error.
Since
1.2.0 ILP interface.
Returns
Last error message.
Referenced by otawa::ipet::WCETComputation::processWorkSpace(), and otawa::ilp::System::~System().
Constraint * otawa::ilp::AbstractSystem::newConstraint (Constraint::comparator_t comp, double constant) virtual
Build a new constraint that may be initialized by the user.
As the ILP system manage the memory of the constraint, the constraint must never be deleted by the user.
Parameters
comp Comparator used (one of Constraint::LT, LE, EQ, GT, GE).
constant Constant value.
Returns
Built constraint.
Implements otawa::ilp::System.
Constraint * otawa::ilp::AbstractSystem::newConstraint (const string & label, Constraint::comparator_t comp, double constant) virtual
Implements otawa::ilp::System.
References otawa::ilp::AbstractConstraint::_idx, otawa::ilp::AbstractConstraint::_sys, AbstractConstraint, and conss.
Var * otawa::ilp::AbstractSystem::newVar (const string & name) virtual
Implements otawa::ilp::System.
References otawa::ilp::Var::INT.
Var * otawa::ilp::AbstractSystem::newVar (Var::type_t type, const string & name) virtual
Build a new variable with the given type.
Parameters
type Type of the variable.
name Variable name.
Returns
Built variable.
Since
ILP 1.2.0
Implements otawa::ilp::System.
References otawa::ilp::AbstractSystem::AbstractVar::_idx, otawa::ilp::AbstractSystem::AbstractVar::_sys, AbstractVar, and vars.
elm::datastruct::IteratorInst< Constraint::Term > * otawa::ilp::AbstractSystem::objTerms (void) virtual
Implements otawa::ilp::System.
References obj.
ILPPlugin * otawa::ilp::System::plugin (void) virtual inherited
Return the owner plugin.
As a default, return null.
Returns
Owner plugin.
Referenced by otawa::ipet::WCETComputation::processWorkSpace(), and otawa::ilp::System::~System().
void otawa::ilp::AbstractSystem::remove (AbstractConstraint * cons) private
Remove a constraint from the system.
Parameters
cons Removed constraint.
References otawa::ilp::AbstractConstraint::_idx, cleaning, and conss.
Referenced by otawa::ilp::AbstractConstraint::~AbstractConstraint(), and otawa::ilp::AbstractSystem::AbstractVar::~AbstractVar().
void otawa::ilp::AbstractSystem::remove (AbstractVar * var) private
Remove a variable from the system.
Parameters
var Variable to remove.
References otawa::ilp::AbstractSystem::AbstractVar::_idx, cleaning, and vars.
boolean otawa::ilp::System::solve (WorkSpace * ws = 0) pure virtual inherited
Solve the ILP system.
Parameters
ws If passed (default to null), the given workspace is used to test if the computation is cancelled in order to stop the solver.
Returns
True if the resolution is succesful or false else (mainly due to lack of constraint).
Referenced by otawa::ipet::WCETComputation::processWorkSpace(), and otawa::ilp::System::~System().
bool otawa::ilp::System::solve (WorkSpace * ws, otawa::Monitor & mon) virtual inherited
Solve the ILP system in the given workspace using the given monitor to output logs.
The workspace may be used to support cancellation or progression in user interface.
Parameters
ws Current workspace.
mon Monitor to use.
double otawa::ilp::System::value (void) pure virtual inherited
Return the value of the optimized object function.
Returns
Object function optimum.
Referenced by otawa::ipet::WCETComputation::processWorkSpace(), and otawa::ilp::System::~System().
double otawa::ilp::System::valueOf (Var * var) pure virtual inherited
This method can only be called after the resolution of the system and returns the value of a variable.
It is an error to pass a variable not involved in the system.
Parameters
var Variable whose value is looked for.
Returns
Value of the variable.
Referenced by otawa::display::ILPSystemDisplayer::displayVar(), dumpSolution(), otawa::ilp::Var::eval(), otawa::ilp::Expression::eval(), otawa::ipet::WCETCountRecorder::processBB(), otawa::BBRatioDisplayer::processBB(), otawa::BBRatioDisplayer::processCFG(), otawa::display::ILPSystemDisplayer::processWorkSpace(), and otawa::ilp::System::~System().
Friends And Related Function Documentation
friend class AbstractConstraint friend
Referenced by newConstraint().
friend class AbstractVar friend
Referenced by newVar().
Member Data Documentation
bool otawa::ilp::AbstractSystem::cleaning private
Referenced by remove(), and ~AbstractSystem().
genstruct::FragTable<AbstractConstraint *> otawa::ilp::AbstractSystem::conss private
Referenced by countConstraints(), newConstraint(), remove(), and ~AbstractSystem().
Expression otawa::ilp::AbstractSystem::obj private
Referenced by addObjectFunction(), and objTerms().
genstruct::FragTable<AbstractVar *> otawa::ilp::AbstractSystem::vars private
Referenced by countVars(), dumpSolution(), newVar(), remove(), and ~AbstractSystem().
The documentation for this class was generated from the following files:
include/otawa/ilp/AbstractSystem.h
src/prog/ilp_AbstractSystem.cpp