Otawa: otawa::ContextualProperty Class Reference
otawa::ContextualProperty Class Reference
A contextual property is a special property that allows to retrieve a property value by its contextual path (ContextualPath).
#include <otawa/prop/ContextualProperty.h>
Classes
class Node
Public Member Functions
ContextualProperty (void)
Build a contextual property.
const AbstractIdentifier * id (void) const
Get the identifier code of the property.
Property * next (void) const
Get the next property.
template<class T >
const T & get (void) const
template<class T >
void set (const T &value)
virtual void print (elm::io::Output &out) const
Print the given property, that is, the identifier and its value if any.
Static Public Member Functions
static bool exists (const PropList &props, const ContextualPath &path, const AbstractIdentifier &id)
Test if a contextual property exists, that is, the property value is defined at any step of the given contextual path.
static PropList & ref (PropList &props, const ContextualPath &path, const AbstractIdentifier &id)
Obtain a reference on a property value in the given contextual path.
static const PropList & find (const PropList &props, const ContextualPath &path, const AbstractIdentifier &id)
Get a contextual property from a property list.
static PropList & make (PropList &props, const ContextualPath &path)
Set a contextual property.
static void print (io::Output &out, const PropList &props)
Display the contextual information of the given property list.
static const AbstractIdentifier * getID (elm::CString name)
Allocate a new identifier matching the given name.
Protected Member Functions
virtual Property * copy (void)
This method is called when a property is copied.
Private Member Functions
const PropList & findProps (const PropList &props, const ContextualPath &path, const AbstractIdentifier &id) const
Find the property list matching the best the given path.
PropList & makeProps (const ContextualPath &path)
Find or make the property list for the given path.
PropList & refProps (PropList &props, const ContextualPath &path, const AbstractIdentifier &id)
void print (io::Output &out, const Node &node, int indent=0) const
Private Attributes
Node root
Static Private Attributes
static AbstractIdentifier ID
Private identifier for contextual properties.
Detailed Description
A contextual property is a special property that allows to retrieve a property value by its contextual path (ContextualPath).
Contextual path allows to takes into account the context of execution of a block, that is, the chaining of function, calls and loop iteration driving to the block. Notice that the path must be precise while the matching is performed on a blurred contextual tree. This means that some parts of the contextual path may be ignored if an embedding context is found in the contextual property. For example, the path [c1, c2, c3] may match a property whose path is [c1, c3] as it is considered as [c1, *, c2], that is more general that the given path. * means "any component".
Constructor & Destructor Documentation
otawa::ContextualProperty::ContextualProperty (void)
Build a contextual property.
Referenced by make(), and ref().
Member Function Documentation
Property * otawa::Property::copy (void) inline protected virtual inherited
This method is called when a property is copied.
It may be specialized by Property class children.
Returns
Copy of the current property.
Reimplemented in otawa::LockedProperty< T >, and otawa::GenericProperty< T >.
References name.
Referenced by otawa::PropList::addProps(), and refProps().
bool otawa::ContextualProperty::exists (const PropList & props, const ContextualPath & path, const AbstractIdentifier & id) static
Test if a contextual property exists, that is, the property value is defined at any step of the given contextual path.
Parameters
props Property list to look in.
path Contextual path.
id Looked identifier.
References findProps(), otawa::PropList::getProp(), and ID.
Referenced by otawa::ContextualPath::Ref< T >::exists().
const PropList & otawa::ContextualProperty::find (const PropList & props, const ContextualPath & path, const AbstractIdentifier & id) static
Get a contextual property from a property list.
Parameters
props Property list to look in.
path Contextual path.
id Identifier of the looked property.
Returns
Found property or null.
References findProps(), otawa::PropList::getProp(), and ID.
Referenced by otawa::ContextualPath::get().
const PropList & otawa::ContextualProperty::findProps (const PropList & props, const ContextualPath & path, const AbstractIdentifier & id) const private
Find the property list matching the best the given path.
Parameters
path Path to match.
stack Stack of property list leading to the full context.
Returns
More precise property list matching the path.
References otawa::ContextualPath::count(), root, and otawa::ContextualProperty::Node::step.
Referenced by exists(), and find().
template<class T > const T & otawa::Property::get (void) const inline inherited
const AbstractIdentifier * otawa::Property::getID (elm::CString name) static inherited
Allocate a new identifier matching the given name.
Note that, if an identifier exists with the same name, its code will be returned ensuring consistency between name and code for identifiers.
Parameters
name Name of the identifier.
Returns
Allocated identifier code.
References otawa::display::find().
const Identifier * otawa::Property::id (void) const inline inherited
Get the identifier code of the property.
Returns
Identifier code.
Referenced by otawa::GenericProperty< T >::copy(), otawa::LockedProperty< T >::copy(), and otawa::PropList::setProp().
PropList & otawa::ContextualProperty::make (PropList & props, const ContextualPath & path) static
Set a contextual property.
Parameters
props Property list to set in.
path Contextual path of the property.
prop Property to set.
References otawa::PropList::addProp(), ContextualProperty(), otawa::ContextualPath::count(), otawa::PropList::getProp(), ID, and makeProps().
Referenced by otawa::ContextualPath::Ref< T >::add(), refProps(), and otawa::ContextualPath::Ref< T >::remove().
PropList & otawa::ContextualProperty::makeProps (const ContextualPath & path) private
Find or make the property list for the given path.
Parameters
path Contextual path.
Returns
Property matching the given path.
References otawa::ContextualPath::count(), root, and otawa::ContextualProperty::Node::step.
Referenced by make().
Property * otawa::Property::next (void) const inline inherited
Get the next property.
Returns
Next property.
References otawa::p::print().
Referenced by otawa::PropList::addProps(), otawa::PropList::clearProps(), otawa::PropList::extractProp(), otawa::PropList::getProp(), otawa::AbstractIdentifier::initProps(), otawa::PropList::Iter::next(), otawa::PropList::removeAllProp(), otawa::PropList::removeProp(), and otawa::PropList::setProp().
void otawa::Property::print (elm::io::Output & out) const virtual inherited
Print the given property, that is, the identifier and its value if any.
Parameters
out Output to use.
References otawa::END().
Referenced by otawa::operator<<().
void otawa::ContextualProperty::print (io::Output & out, const PropList & props) static
Display the contextual information of the given property list.
Parameters
out Stream to output to.
props Property list.
References otawa::PropList::getProp(), ID, print(), and root.
Referenced by print().
void otawa::ContextualProperty::print (io::Output & out, const Node & node, int indent = 0) const private
References ID, otawa::PropList::print(), print(), and otawa::ContextualProperty::Node::step.
PropList & otawa::ContextualProperty::ref (PropList & props, const ContextualPath & path, const AbstractIdentifier & id) static
Obtain a reference on a property value in the given contextual path.
If the property does not exists, create and return it. If the property exists at an intermediate level, copy it at the top level and return reference to it.
Parameters
props Property list to look in.
path Contextual path.
id Looked identifier.
References otawa::PropList::addProp(), ContextualProperty(), otawa::ContextualPath::count(), otawa::PropList::getProp(), ID, and refProps().
Referenced by otawa::ContextualPath::Ref< T >::ref().
PropList & otawa::ContextualProperty::refProps (PropList & props, const ContextualPath & path, const AbstractIdentifier & id) private
References otawa::PropList::addProp(), otawa::Property::copy(), otawa::ContextualPath::count(), otawa::PropList::getProp(), make(), root, and otawa::ContextualProperty::Node::step.
Referenced by ref().
template<class T > void otawa::Property::set (const T & value) inline inherited
References otawa::GenericProperty< T >::value().
Member Data Documentation
AbstractIdentifier otawa::ContextualProperty::ID static private
Private identifier for contextual properties.
Referenced by exists(), find(), make(), print(), and ref().
Node otawa::ContextualProperty::root private
Referenced by findProps(), makeProps(), print(), and refProps().
The documentation for this class was generated from the following files:
include/otawa/prop/ContextualProperty.h
src/prog/prop_ContextualProperty.cpp