Otawa: otawa::WorkSpace Class Reference
otawa::WorkSpace Class Reference
Program Representation
A workspace represents a program, its run-time and all information about WCET computation or any other analysis.
#include <otawa/prog/WorkSpace.h>
Public Member Functions
WorkSpace (Process *_proc)
Build a new wokspace with the given process.
WorkSpace (const WorkSpace *ws)
Build a new workspace on the same process as the given one.
virtual ~WorkSpace (void)
Delete the workspace and the associated process.
Process * process (void) const
virtual hard::Platform * platform (void)
virtual Manager * manager (void)
virtual Inst * start (void)
virtual Inst * findInstAt (address_t addr)
string format (Address addr, bool with_address=true)
Format an address to make it human-readable.
elm::xom::Element * config (void)
Get the current configuration, if any, as an XML XOM element.
void loadConfig (const elm::system::Path &path)
Load the given configuration in the process.
void require (const AbstractFeature &feature, const PropList &props=PropList::EMPTY)
Ensure that a feature is provided.
void provide (const AbstractFeature &feature, const Vector< const AbstractFeature * > *required=NULL)
Record in the workspace that a feature is provided.
bool isProvided (const AbstractFeature &feature)
Test if a feature is provided.
void remove (const AbstractFeature &feature)
Remove a feature.
void invalidate (const AbstractFeature &feature)
Invalidate a feature (removing its dependencies)
FeatureDependency * getDependency (const AbstractFeature *feature)
Get the dependency graph node associated with the feature and workspace.
void clearCancellation (void)
Reset the cancellation bit.
void cancel (void)
Informs the current computation to stop as soon as possible.
bool isCancelled (void) const
Test if the cancel() method has been called on the workspace.
virtual void serialize (elm::serial2::Serializer &serializer)
Serialize the workspace to the current serializer.
virtual void unserialize (elm::serial2::Unserializer &unserializer)
Unserialize the workspace to the current unserializer.
ast::ASTInfo * getASTInfo (void)
Get the AST of the project.
ilp::System * newILPSystem (bool max=true)
Build an ILP system with the default ILP engine.
CFGInfo * getCFGInfo (void)
Get the CFG of the project.
CFG * getStartCFG (void)
Get the entry CFG of the program.
virtual const hard::CacheConfiguration & cache (void)
Property * getProp (const AbstractIdentifier *id) const
Find a property by its identifier.
void setProp (Property *prop)
Set the property in the property list removing any double.
void setProp (const AbstractIdentifier *id)
void removeProp (const AbstractIdentifier *id)
Remove a property matching the given identifier.
void removeProp (const AbstractIdentifier &id)
Property * extractProp (const AbstractIdentifier *id)
Remove a property matching the given identifier and return it.
Property * extractProp (const AbstractIdentifier &id)
Remove a property matching the given identifier and return it.
void addProp (Property *prop)
Add property to the list without checking of duplication.
void removeAllProp (const AbstractIdentifier *id)
Remove all the properties matching the given identifier.
bool hasProp (const AbstractIdentifier &id) const
Test if the property list contains a property matching the given identifier.
void clearProps (void)
Remove all properties from the list.
void addProps (const PropList &props)
Add all properties from the given property list, in a reverse order.
void print (elm::io::Output &out) const
Display the current property list.
Static Public Attributes
static const PropList EMPTY
This is an empty proplist for convenience.
Private Types
typedef HashTable< const AbstractFeature *, FeatureDependency * > feat_map_t
Private Member Functions
void newFeatDep (const AbstractFeature *feature)
Create a new FeatureDependency associated with the feature.
bool hasFeatDep (const AbstractFeature *feature)
Tests if the feature has a dependency graph associated with it, in the context of the present workspace.
void delFeatDep (const AbstractFeature *feature)
Invalidates and delete the FeatureDependency associated w/ this feature and workspace It has to be freed by the user.
Private Attributes
LockPtr< Process > proc
feat_map_t featMap
bool cancelled
Detailed Description
A workspace represents a program, its run-time and all information about WCET computation or any other analysis.
Member Typedef Documentation
typedef HashTable<const AbstractFeature*, FeatureDependency*> otawa::WorkSpace::feat_map_t private
Constructor & Destructor Documentation
otawa::WorkSpace::WorkSpace (Process * _proc)
Build a new wokspace with the given process.
Parameters
_proc Process to use.
References proc, and TRACE.
otawa::WorkSpace::WorkSpace (const WorkSpace * ws)
Build a new workspace on the same process as the given one.
Parameters
ws Workspace to get the process form.
References proc, process(), and TRACE.
otawa::WorkSpace::~WorkSpace (void) virtual
Delete the workspace and the associated process.
References otawa::PropList::clearProps(), featMap, invalidate(), isProvided(), proc, and TRACE.
Member Function Documentation
void otawa::PropList::addProp (Property * prop) inherited
Add property to the list without checking of duplication.
Parameters
prop Property to add.
References otawa::Property::_next.
Referenced by otawa::Identifier< T >::add(), otawa::ast::ASTInfo::ASTInfo(), otawa::Identifier< otawa::arm::Info * >::copy(), otawa::AbstractIdentifier::initProps(), otawa::ContextualProperty::make(), otawa::script::Script::makeConfig(), otawa::ccg::Builder::processLBlockSet(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), and otawa::ContextualProperty::refProps().
void otawa::PropList::addProps (const PropList & props) inherited
Add all properties from the given property list, in a reverse order.
Parameters
props Property list to clone.
References otawa::Property::copy(), otawa::PropList::head, and otawa::Property::next().
Referenced by otawa::display::CFGDrawer::CFGDrawer(), otawa::display::GraphVizGraph::GraphVizGraph(), otawa::ParamFeature::instantiate(), otawa::Manager::loadXML(), otawa::display::GraphVizGraph::newEdge(), otawa::display::GraphVizGraph::newNode(), otawa::Process::Process(), otawa::display::GraphVizItem::setProps(), otawa::VirtualBasicBlock::VirtualBasicBlock(), and otawa::VirtualCFG::VirtualCFG().
const hard::CacheConfiguration & otawa::WorkSpace::cache (void) virtual
Deprecated:
References proc.
Referenced by otawa::ets::ACSComputation::applyProcess(), otawa::ets::ACSComputation::initialization(), and otawa::ets::ACSComputation::processAST().
void otawa::WorkSpace::cancel (void) inline
Informs the current computation to stop as soon as possible.
This feature has not direct on the workspace but is used by code processor to change their behaviour. It may be used to stop a computation in a parallel or a GUI context.
void otawa::WorkSpace::clearCancellation (void) inline
Reset the cancellation bit.
This function must be called before starting a long running time computation.
void otawa::PropList::clearProps (void) inherited
Remove all properties from the list.
References otawa::Property::next().
Referenced by otawa::PSTBuilder::getVCFG(), otawa::display::GraphVizItem::setProps(), and ~WorkSpace().
xom::Element * otawa::WorkSpace::config (void)
Get the current configuration, if any, as an XML XOM element.
Returns
Configuration XML element or null.
References otawa::CONFIG_ELEMENT, otawa::CONFIG_PATH, and loadConfig().
void otawa::WorkSpace::delFeatDep (const AbstractFeature * feature) private
Invalidates and delete the FeatureDependency associated w/ this feature and workspace It has to be freed by the user.
Parameters
feature Provided feature.
References featMap.
Referenced by invalidate().
Property * otawa::PropList::extractProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::script::Script::makeConfig().
Property * otawa::PropList::extractProp (const AbstractIdentifier & id) inline inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::PropList::extractProp().
Referenced by otawa::PropList::extractProp().
virtual Inst* otawa::WorkSpace::findInstAt (address_t addr) inline virtual
References otawa::p::config, otawa::p::invalidate, proc(), otawa::p::provide, and otawa::p::require.
Referenced by otawa::CFGBuilder::buildCFG(), otawa::AbsoluteAddress::cfg(), otawa::LabelAddress::cfg(), otawa::CFGBuilder::cleanup(), otawa::FlowFactLoader::findCall(), format(), otawa::VarTextDecoder::getInst(), otawa::ipet::FlowFactLoader::lookLineAt(), makeAddress(), otawa::ast::ASTLoader::makeBlock(), otawa::VarTextDecoder::processWorkSpace(), otawa::CFGBuilder::setup(), and otawa::CFGProcessor::str().
string otawa::WorkSpace::format (Address addr, bool with_address = true)
Format an address to make it human-readable.
First look for debugging information, else try to build the form label + offset else fall back to address itself.
Parameters
addr Address to display.
with_address Set to true to ever display the address.
Returns
Formatted string.
References otawa::ProgItem::address(), findInstAt(), otawa::Process::getSourceLine(), otawa::Symbol::ID, otawa::Address::isNull(), otawa::Inst::prevInst(), and process().
Referenced by otawa::CFGChecker::processBB(), and otawa::ipet::FlowFactConstraintBuilder::processBB().
ast::ASTInfo * otawa::WorkSpace::getASTInfo (void)
Get the AST of the project.
Deprecated:
Referenced by otawa::ets::ACSComputation::applyProcess(), otawa::ets::CacheHitComputation::computation(), otawa::ets::CacheMissComputation::computation(), otawa::ets::CacheFirstMissComputation::computation(), otawa::ets::WCETComputation::computation(), otawa::ets::ACSComputation::initialization(), otawa::ets::FlowFactLoader::processAST(), otawa::ets::TrivialAstBlockTime::processAST(), and otawa::FunProcessor::processWorkSpace().
CFGInfo * otawa::WorkSpace::getCFGInfo (void)
Get the CFG of the project.
If it does not exists, built it.
Deprecated:
References otawa::CFGInfo::ID, and otawa::Processor::process().
Referenced by getStartCFG().
FeatureDependency * otawa::WorkSpace::getDependency (const AbstractFeature * feature)
Get the dependency graph node associated with the feature and workspace.
Parameters
feature Provided feature.
References featMap.
Referenced by invalidate(), otawa::Processor::process(), and provide().
Property * otawa::PropList::getProp (const AbstractIdentifier * id) const inherited
Find a property by its identifier.
Parameters
id Identifier of the property to find.
Returns
Found property or null.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::Identifier< otawa::arm::Info * >::exists(), otawa::ContextualProperty::exists(), otawa::ContextualProperty::find(), otawa::Identifier< T >::get(), otawa::ContextualProperty::make(), otawa::ParamFeature::matches(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::print(), otawa::ContextualProperty::print(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), otawa::ContextualProperty::refProps(), otawa::Identifier< T >::set(), otawa::Identifier< T >::use(), and otawa::Identifier< T >::value().
CFG * otawa::WorkSpace::getStartCFG (void)
Get the entry CFG of the program.
Returns
Entry CFG if any or null.
Deprecated:
References otawa::CFGInfo::findCFG(), getCFGInfo(), and start().
bool otawa::WorkSpace::hasFeatDep (const AbstractFeature * feature) private
Tests if the feature has a dependency graph associated with it, in the context of the present workspace.
Parameters
feature Provided feature.
References featMap.
Referenced by provide().
bool otawa::PropList::hasProp (const AbstractIdentifier & id) const inline inherited
Test if the property list contains a property matching the given identifier.
Parameters
id Property identifier to look for.
Returns
True if the list contains the matching property, false else.
References otawa::p::print().
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::Monitor::configure(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::exists(), and otawa::Manager::setVerbosity().
void otawa::WorkSpace::invalidate (const AbstractFeature & feature)
Invalidate a feature (removing its dependencies)
Parameters
feature Provided feature.
References delFeatDep(), getDependency(), and isProvided().
Referenced by otawa::Processor::process(), and ~WorkSpace().
bool otawa::WorkSpace::isCancelled (void) const inline
Test if the cancel() method has been called on the workspace.
This method is usually called by code processor to know if the computation has been canceled.
Returns
True if the computation has been cancelled, false else.
References cache(), and otawa::clp::max().
Referenced by otawa::Processor::process().
bool otawa::WorkSpace::isProvided (const AbstractFeature & feature)
Test if a feature is provided.
Parameters
feature Feature to test.
Returns
True if it is provided, false else.
References featMap.
Referenced by otawa::AbsoluteAddress::cfg(), otawa::LabelAddress::cfg(), otawa::FeatureRequirer::FeatureRequirer(), invalidate(), makeAddress(), otawa::Processor::process(), otawa::FlowFactLoader::processWorkSpace(), provide(), require(), otawa::ipet::FlowFactLoader::setup(), otawa::BBRatioDisplayer::setup(), otawa::etime::StandardEventBuilder::setup(), and ~WorkSpace().
void otawa::WorkSpace::loadConfig (const elm::system::Path & path)
Load the given configuration in the process.
Parameters
path Path to the XML configuration file.
Exceptions
LoadException If the file cannot be found or if it does not match the OTAWA XML type.
References otawa::CONFIG_ELEMENT.
Referenced by config().
virtual Manager* otawa::WorkSpace::manager (void) inline virtual
References proc().
Referenced by newILPSystem().
void otawa::WorkSpace::newFeatDep (const AbstractFeature * feature) private
Create a new FeatureDependency associated with the feature.
Parameters
feature Provided feature.
References featMap.
Referenced by provide().
ilp::System * otawa::WorkSpace::newILPSystem (bool max = true)
Build an ILP system with the default ILP engine.
Parameters
max True for a maximized system, false for a minimized.
Returns
ILP system ready to use, NULL fi there is no support for ILP.
Deprecated:
References manager(), and otawa::Manager::newILPSystem().
virtual hard::Platform* otawa::WorkSpace::platform (void) inline virtual
References proc().
Referenced by otawa::ExeGraph< N >::build(), otawa::ParExeGraph::createSequenceResources(), otawa::ParamExeGraph::ParamExeGraph(), otawa::EdgeCAT2Builder::processCFG(), otawa::EdgeCAT2ConstraintBuilder::processWorkSpace(), otawa::EdgeACSBuilder::processWorkSpace(), otawa::ResourceList::ResourceList(), and otawa::dcache::BlockBuilder::setup().
void otawa::PropList::print (elm::io::Output & out) const inherited
Display the current property list.
Parameters
out Output to use.
Referenced by otawa::Edge::kindName(), otawa::operator<<(), and otawa::ContextualProperty::print().
Process* otawa::WorkSpace::process (void) const inline
References proc().
Referenced by otawa::PFGBuilder::addFunction(), otawa::FlowFactLoader::addressOf(), otawa::Loader::check(), otawa::FlowFactLoader::findCall(), otawa::CFGInfo::findCFG(), otawa::ast::ASTLoader::findLabel(), format(), otawa::VarTextDecoder::getBytes(), otawa::VarTextDecoder::getInst(), otawa::hard::Processor::instantiate(), otawa::ipet::FlowFactLoader::lookLineAt(), makeAddress(), otawa::clp::Manager::Manager(), otawa::DelayedBuilder::next(), otawa::FlowFactLoader::onCheckSum(), otawa::FlowFactLoader::onIgnoreControl(), otawa::FlowFactLoader::onIgnoreSeq(), otawa::FlowFactLoader::onLoop(), otawa::FlowFactLoader::onMemoryAccess(), otawa::FlowFactLoader::onMultiBranch(), otawa::FlowFactLoader::onMultiCall(), otawa::FlowFactLoader::onNoCall(), otawa::FlowFactLoader::onNoInline(), otawa::FlowFactLoader::onNoReturn(), otawa::FlowFactLoader::onPreserve(), otawa::FlowFactLoader::onRegSet(), otawa::FlowFactLoader::onReturn(), otawa::FlowFactLoader::onSetInlining(), otawa::stack::operator<<(), otawa::ParExeGraph::ParExeGraph(), otawa::cfgio::Output::processBB(), otawa::BBRatioDisplayer::processBB(), otawa::CFGCheckSummer::processCFG(), otawa::ipet::ConstraintLoader::processCFG(), otawa::TextDecoder::processWorkSpace(), otawa::VarTextDecoder::processWorkSpace(), otawa::hard::Dumper::processWorkSpace(), otawa::FixedTextDecoder::processWorkSpace(), otawa::CFGBuilder::processWorkSpace(), otawa::PFGBuilder::processWorkSpace(), otawa::StackAnalysis::processWorkSpace(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::ast::ASTLoader::processWorkSpace(), otawa::display::ILPSystemDisplayer::processWorkSpace(), otawa::clp::Analysis::processWorkSpace(), otawa::FlowFactLoader::processWorkSpace(), otawa::dfa::State::record(), otawa::FlowFactLoader::scanAddress(), otawa::FlowFactLoader::scanIgnoreControl(), otawa::FlowFactLoader::scanIgnoreSeq(), otawa::FlowFactLoader::scanMultiBranch(), otawa::FlowFactLoader::scanMultiCall(), otawa::FlowFactLoader::scanNoInline(), otawa::FlowFactLoader::scanSetInlining(), otawa::FlowFactLoader::scanXCall(), otawa::FlowFactLoader::scanXFun(), otawa::FlowFactLoader::scanXLoop(), serialize(), otawa::FixedTextDecoder::setup(), otawa::tsim::BBTimeSimulator::setup(), otawa::dcache::BlockBuilder::setup(), otawa::tsim::BBPath::simulate(), otawa::DelayedBuilder::size(), otawa::LabelAddress::toAddress(), otawa::script::Script::work(), and WorkSpace().
void otawa::WorkSpace::provide (const AbstractFeature & feature, const Vector< const AbstractFeature * > * required = NULL)
Record in the workspace that a feature is provided.
Also update the feature dependency graph
Parameters
feature Provided feature.
References otawa::FeatureDependency::add(), otawa::Identifier< T >::get(), getDependency(), hasFeatDep(), isProvided(), otawa::AbstractIdentifier::name(), and newFeatDep().
Referenced by otawa::Process::link(), and otawa::Processor::process().
void otawa::WorkSpace::remove (const AbstractFeature & feature)
Remove a feature.
It is usually called by processor whose actions remove some properties from the workspace.
Parameters
feature Feature to remove.
References otawa::AbstractFeature::clean().
void otawa::PropList::removeAllProp (const AbstractIdentifier * id) inherited
Remove all the properties matching the given identifier.
Parameters
id Identifier of properties to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::LoopUnroller::unroll().
void otawa::PropList::removeProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier.
Parameters
id Identifier of the property to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::PSTBuilder::buildTree(), otawa::BBRemover< T >::clean(), otawa::CFGBuilder::cleanup(), otawa::display::CFGOutput::processCFG(), otawa::SubCFGBuilder::processWorkSpace(), otawa::Identifier< otawa::arm::Info * >::remove(), and otawa::ContextualPath::Ref< T >::remove().
void otawa::PropList::removeProp (const AbstractIdentifier & id) inline inherited
References otawa::PropList::removeProp().
Referenced by otawa::PropList::removeProp().
void otawa::WorkSpace::require (const AbstractFeature & feature, const PropList & props = PropList::EMPTY)
Ensure that a feature is provided.
Parameters
feature Required feature.
props Configuration properties (optional).
References isProvided(), and otawa::AbstractFeature::process().
Referenced by otawa::Processor::process(), otawa::Application::require(), and otawa::script::Script::work().
void otawa::WorkSpace::serialize (elm::serial2::Serializer & serializer) virtual
Serialize the workspace to the current serializer.
Parameters
serializer Serializer to serialize to.
References otawa::Process::loader(), and process().
void otawa::PropList::setProp (Property * prop) inherited
Set the property in the property list removing any double.
Parameters
prop Property to set.
References otawa::Property::_next, otawa::Property::id(), and otawa::Property::next().
void otawa::PropList::setProp (const AbstractIdentifier * id) inline inherited
References otawa::PropList::setProp().
Referenced by otawa::PropList::setProp().
virtual Inst* otawa::WorkSpace::start (void) inline virtual
References proc().
Referenced by getStartCFG(), otawa::VarTextDecoder::processWorkSpace(), otawa::CFGBuilder::processWorkSpace(), and otawa::PFGBuilder::processWorkSpace().
void otawa::WorkSpace::unserialize (elm::serial2::Unserializer & unserializer) virtual
Unserialize the workspace to the current unserializer.
Parameters
unserializer Unserializer to unserialize to.
Member Data Documentation
bool otawa::WorkSpace::cancelled private
const PropList otawa::PropList::EMPTY static inherited
This is an empty proplist for convenience.
Referenced by otawa::DynProcessor::configure(), otawa::ActualFeature::processor(), otawa::SilentFeature::SilentFeature(), otawa::Processor::version(), and otawa::display::Driver::~Driver().
feat_map_t otawa::WorkSpace::featMap private
Referenced by delFeatDep(), getDependency(), hasFeatDep(), isProvided(), newFeatDep(), and ~WorkSpace().
LockPtr<Process> otawa::WorkSpace::proc private
Referenced by cache(), WorkSpace(), and ~WorkSpace().
The documentation for this class was generated from the following files:
include/otawa/prog/WorkSpace.h
src/prog/prog_WorkSpace.cpp