Otawa: otawa::dfa::hai::DefaultListener< P > Class Template Reference
otawa::dfa::hai::DefaultListener< P > Class Template Reference
This listener gathers in an array the LUB of the in-states for all analyzed basic blocks.
#include <otawa/dfa/hai/DefaultListener.h>
Public Types
typedef P Problem
Public Member Functions
DefaultListener (WorkSpace *_fw, Problem &_prob, bool _store_out=false)
~DefaultListener ()
void blockInterpreted (const DefaultFixPoint< DefaultListener > *fp, BasicBlock *bb, const typename Problem::Domain &in, const typename Problem::Domain &out, CFG *cur_cfg, elm::genstruct::Vector< Edge * > *callStack) const
This is called whenever a block is processed.
void fixPointReached (const DefaultFixPoint< DefaultListener > *fp, BasicBlock *bb)
This is called whenever a loop's fixpoint is reached.
Problem & getProb ()
Public Attributes
Problem::Domain *** results
Problem::Domain *** results_out
Static Public Attributes
static Identifier< typename Problem::Domain * > BB_OUT_STATE
PRIVATE - DO NOT USE.
Private Attributes
WorkSpace * fw
Problem & prob
bool store_out
Detailed Description
template<class P>
class otawa::dfa::hai::DefaultListener< P >
This listener gathers in an array the LUB of the in-states for all analyzed basic blocks.
At the end of the analysis, you can access result[CFGNUMBER][BBNUMBER] to obtain the in-state of the basic block BBNUMBER of cfg CFGNUMBER.
Member Typedef Documentation
template<class P> typedef P otawa::dfa::hai::DefaultListener< P >::Problem
Constructor & Destructor Documentation
template<class P> otawa::dfa::hai::DefaultListener< P >::DefaultListener (WorkSpace * _fw, Problem & _prob, bool _store_out = false) inline
References otawa::cfgio::cfg(), otawa::CFGCollection::count(), otawa::CFG::countBB(), otawa::dfa::hai::DefaultListener< P >::fw, otawa::CFGCollection::get(), otawa::INVOLVED_CFGS, otawa::dfa::hai::DefaultListener< P >::prob, and otawa::dfa::hai::DefaultListener< P >::store_out.
template<class P> otawa::dfa::hai::DefaultListener< P >::~DefaultListener () inline
References otawa::cfgio::bb(), otawa::dfa::hai::DefaultListener< P >::blockInterpreted(), otawa::cfgio::cfg(), otawa::CFGCollection::count(), otawa::CFG::countBB(), otawa::dfa::hai::DefaultListener< P >::fixPointReached(), otawa::dfa::hai::DefaultListener< P >::fw, otawa::CFGCollection::get(), otawa::INVOLVED_CFGS, otawa::dfa::hai::DefaultListener< P >::results, otawa::dfa::hai::DefaultListener< P >::results_out, and otawa::dfa::hai::DefaultListener< P >::store_out.
Member Function Documentation
template<class Problem > void otawa::dfa::hai::DefaultListener< P >::blockInterpreted (const DefaultFixPoint< DefaultListener< P > > * fp, BasicBlock * bb, const typename Problem::Domain & in, const typename Problem::Domain & out, CFG * cur_cfg, elm::genstruct::Vector< Edge * > * callStack) const
This is called whenever a block is processed.
In the DefaultListener, we do the LUB of all the in-states of each block.
Parameters
fp The FixPoint object
bb The Basic Block
in In-state
out Out-state (not used in this class)
cur_cfg Current CFG
References otawa::dfa::hai::DefaultListener< P >::BB_OUT_STATE, otawa::CFG::number(), otawa::BasicBlock::number(), otawa::dfa::hai::DefaultListener< P >::prob, otawa::dfa::hai::DefaultListener< P >::results, otawa::dfa::hai::DefaultListener< P >::results_out, and otawa::dfa::hai::DefaultListener< P >::store_out.
Referenced by otawa::dfa::hai::DefaultListener< P >::~DefaultListener().
template<class Problem > void otawa::dfa::hai::DefaultListener< P >::fixPointReached (const DefaultFixPoint< DefaultListener< P > > * fp, BasicBlock * bb)
This is called whenever a loop's fixpoint is reached.
Parameters
fp The FixPoint object
bb The loop header.
Referenced by otawa::dfa::hai::DefaultListener< P >::~DefaultListener().
template<class P> Problem& otawa::dfa::hai::DefaultListener< P >::getProb () inline
References otawa::dfa::hai::DefaultListener< P >::prob.
Member Data Documentation
template<class P> Identifier< typename Problem::Domain * > otawa::dfa::hai::DefaultListener< Problem >::BB_OUT_STATE static
PRIVATE - DO NOT USE.
Referenced by otawa::dfa::hai::DefaultListener< P >::blockInterpreted().
template<class P> WorkSpace* otawa::dfa::hai::DefaultListener< P >::fw private
Referenced by otawa::dfa::hai::DefaultListener< P >::DefaultListener(), and otawa::dfa::hai::DefaultListener< P >::~DefaultListener().
template<class P> Problem& otawa::dfa::hai::DefaultListener< P >::prob private
Referenced by otawa::dfa::hai::DefaultListener< P >::blockInterpreted(), otawa::dfa::hai::DefaultListener< P >::DefaultListener(), and otawa::dfa::hai::DefaultListener< P >::getProb().
template<class P> Problem::Domain*** otawa::dfa::hai::DefaultListener< P >::results
Referenced by otawa::dfa::hai::DefaultListener< P >::blockInterpreted(), otawa::dcache::DirtyManager::t::print(), otawa::ACSMayBuilder::processLBlockSet(), otawa::ACSBuilder::processLBlockSet(), otawa::dcache::ACSMayBuilder::processLBlockSet(), otawa::dcache::ACSBuilder::processLBlockSet(), and otawa::dfa::hai::DefaultListener< P >::~DefaultListener().
template<class P> Problem::Domain*** otawa::dfa::hai::DefaultListener< P >::results_out
Referenced by otawa::dfa::hai::DefaultListener< P >::blockInterpreted(), and otawa::dfa::hai::DefaultListener< P >::~DefaultListener().
template<class P> bool otawa::dfa::hai::DefaultListener< P >::store_out private
Referenced by otawa::dfa::hai::DefaultListener< P >::blockInterpreted(), otawa::dfa::hai::DefaultListener< P >::DefaultListener(), and otawa::dfa::hai::DefaultListener< P >::~DefaultListener().
The documentation for this class was generated from the following files:
include/otawa/dfa/hai/DefaultListener.h
src/prog/dfa_hai_DefaultListener.cpp