Otawa: otawa::display::AbstractDrawer::Edge Class Reference
otawa::display::AbstractDrawer::Edge Class Reference
ODisplay Library
An edge in a AbstractDrawer.
#include <otawa/display/AbstractDrawer.h>
Public Member Functions
Edge (AbstractDrawer &drawer, Vertex *source, Vertex *sink)
Build an edge.
virtual ~Edge (void)
virtual void configure (Output &label, TextStyle &text, LineStyle &line)
This method may be overriden to provide a customized displayed text.
Public Attributes
TextStyle text
Style of the text publicly accessible for customization.
LineStyle line
Style of the line publicly accessible for customization.
Private Member Functions
void setup (void)
Private Attributes
display::Edge * edge
Friends
class AbstractDrawer
Detailed Description
An edge in a AbstractDrawer.
Constructor & Destructor Documentation
otawa::display::AbstractDrawer::Edge::Edge (AbstractDrawer & drawer, Vertex * source, Vertex * sink)
Build an edge.
Parameters
drawer Owner drawer.
source Source vertex.
sink Sink vertex.
References otawa::display::AbstractDrawer::default_edge_line, otawa::display::AbstractDrawer::default_edge_text, otawa::cfgio::edge(), otawa::display::AbstractDrawer::edges, otawa::display::AbstractDrawer::graph, otawa::display::Graph::newEdge(), and otawa::display::AbstractDrawer::Vertex::node.
virtual otawa::display::AbstractDrawer::Edge::~Edge (void) inline virtual
Member Function Documentation
void otawa::display::AbstractDrawer::Edge::configure (Output & label, TextStyle & text, LineStyle & line) virtual
This method may be overriden to provide a customized displayed text.
Parameters
label Label of the edge.
text Label text style to configure.
line Edge line style to configure.
Reimplemented in otawa::display::GenDrawer< G, D >::Edge.
void otawa::display::AbstractDrawer::Edge::setup (void) private
References otawa::display::AbstractDrawer::configure(), otawa::cfgio::edge(), and otawa::display::LABEL.
Friends And Related Function Documentation
friend class AbstractDrawer friend
Member Data Documentation
display::Edge* otawa::display::AbstractDrawer::Edge::edge private
otawa::display::AbstractDrawer::Edge::line
Style of the line publicly accessible for customization.
otawa::display::AbstractDrawer::Edge::text
Style of the text publicly accessible for customization.
The documentation for this class was generated from the following files:
include/otawa/display/AbstractDrawer.h
src/odisplay/display_AbstractDrawer.cpp