Otawa: otawa::CEClass Class Reference
otawa::CEClass Class Reference
#include <otawa/cfg/PSTBuilder.h>
Public Member Functions
CEClass (void)
void inc (void)
void inc (Edge *bracket)
void dec (void)
bool isLast (void)
bool isFirst (void)
int getCount (void)
Private Attributes
int count
bool first
Edge * backEdge
Constructor & Destructor Documentation
otawa::CEClass::CEClass (void) inline
Member Function Documentation
void otawa::CEClass::dec (void) inline
Referenced by otawa::PSTBuilder::buildTree().
int otawa::CEClass::getCount (void) inline
void otawa::CEClass::inc (void) inline
void otawa::CEClass::inc (Edge * bracket) inline
bool otawa::CEClass::isFirst (void) inline
References first.
Referenced by otawa::PSTBuilder::buildTree().
bool otawa::CEClass::isLast (void) inline
Referenced by otawa::PSTBuilder::buildTree().
Member Data Documentation
Edge* otawa::CEClass::backEdge private
int otawa::CEClass::count private
bool otawa::CEClass::first private
Referenced by isFirst(), and otawa::SESERegion::isFirst().
The documentation for this class was generated from the following file:
include/otawa/cfg/PSTBuilder.h