Otawa: otawa::TimingContext Class Reference
otawa::TimingContext Class Reference
#include <otawa/parexegraph/ParExeGraph.h>
Classes
class NodeLatencyIterator
Public Member Functions
TimingContext ()
TimingContext (BasicBlock *h0, BasicBlock *h1=NULL)
TimingContext (TimingContext *ctxt)
~TimingContext ()
void addNodeLatency (NodeLatency *nl)
bool isEmpty ()
void setHeaders (BasicBlock *h0, BasicBlock *h1=NULL)
BasicBlock * header (int index)
void setType (CachePenalty::cache_penalty_type_t type)
CachePenalty::cache_penalty_type_t type ()
Private Attributes
elm::genstruct::SLList< NodeLatency * > _node_latencies_list
BasicBlock * _header [2]
CachePenalty::cache_penalty_type_t _type
Constructor & Destructor Documentation
otawa::TimingContext::TimingContext () inline
otawa::TimingContext::TimingContext (BasicBlock * h0, BasicBlock * h1 = NULL) inline
otawa::TimingContext::TimingContext (TimingContext * ctxt) inline
References _header, and _type.
otawa::TimingContext::~TimingContext () inline
Member Function Documentation
void otawa::TimingContext::addNodeLatency (NodeLatency * nl) inline
Referenced by otawa::GraphBBTime< G >::buildFMTimingContextListForICache(), otawa::GraphBBTime< G >::buildNCTimingContextListForICache(), and otawa::GraphBBTime< G >::computeDefaultTimingContextForICache().
BasicBlock* otawa::TimingContext::header (int index) inline
bool otawa::TimingContext::isEmpty (void) inline
Referenced by otawa::GraphBBTime< G >::analyzePathContext().
void otawa::TimingContext::setHeaders (BasicBlock * h0, BasicBlock * h1 = NULL) inline
void otawa::TimingContext::setType (CachePenalty::cache_penalty_type_t type) inline
References otawa::type().
Referenced by otawa::GraphBBTime< G >::buildFMTimingContextListForICache().
CachePenalty::cache_penalty_type_t otawa::TimingContext::type (void) inline
Member Data Documentation
BasicBlock* otawa::TimingContext::_header[2] private
Referenced by TimingContext().
elm::genstruct::SLList<NodeLatency *> otawa::TimingContext::_node_latencies_list private
CachePenalty::cache_penalty_type_t otawa::TimingContext::_type private
Referenced by TimingContext().
The documentation for this class was generated from the following file:
include/otawa/parexegraph/ParExeGraph.h