Otawa: otawa::BranchProblem::Domain Class Reference
otawa::BranchProblem::Domain Class Reference
#include <otawa/branch/BranchProblem.h>
Public Member Functions
Domain (const int _size, const int _A)
Domain (const Domain &source)
Domain & operator= (const Domain &src)
MAYBranch::Domain & getMay ()
MUSTBranch::Domain & getMust ()
PERSBranch::Domain & getPers ()
void lub (const Domain &dom)
int getSize (void)
bool equals (const Domain &dom) const
void empty ()
void inject (const int id)
void print (elm::io::Output &output) const
Private Attributes
PERSBranch::Domain pers
MUSTBranch::Domain must
MAYBranch::Domain may
Friends
class BranchProblem
Constructor & Destructor Documentation
otawa::BranchProblem::Domain::Domain (const int _size, const int _A) inline
otawa::BranchProblem::Domain::Domain (const Domain & source) inline
Member Function Documentation
void otawa::BranchProblem::Domain::empty () inline
References otawa::MUSTBranch::Domain::empty(), otawa::MAYBranch::Domain::empty(), and otawa::PERSBranch::Domain::empty().
bool otawa::BranchProblem::Domain::equals (const Domain & dom) const inline
References otawa::MUSTBranch::Domain::equals(), otawa::MAYBranch::Domain::equals(), otawa::PERSBranch::Domain::equals(), may, must, and pers.
Referenced by otawa::BranchProblem::equals().
MAYBranch::Domain& otawa::BranchProblem::Domain::getMay () inline
Referenced by otawa::branch::BranchBuilder::categorize().
MUSTBranch::Domain& otawa::BranchProblem::Domain::getMust () inline
Referenced by otawa::branch::BranchBuilder::categorize().
PERSBranch::Domain& otawa::BranchProblem::Domain::getPers () inline
Referenced by otawa::branch::BranchBuilder::categorize().
int otawa::BranchProblem::Domain::getSize (void) inline
References otawa::MUSTBranch::Domain::getSize().
void otawa::BranchProblem::Domain::inject (const int id) inline
References otawa::MUSTBranch::Domain::inject(), otawa::MAYBranch::Domain::inject(), and otawa::PERSBranch::Domain::inject().
Referenced by otawa::BranchProblem::update().
void otawa::BranchProblem::Domain::lub (const Domain & dom) inline
References otawa::MUSTBranch::Domain::lub(), otawa::MAYBranch::Domain::lub(), otawa::PERSBranch::Domain::lub(), may, must, and pers.
Referenced by otawa::BranchProblem::lub().
Domain& otawa::BranchProblem::Domain::operator= (const Domain & src) inline
References may, must, and pers.
void otawa::BranchProblem::Domain::print (elm::io::Output & output) const inline
References otawa::MUSTBranch::Domain::print(), otawa::MAYBranch::Domain::print(), and otawa::PERSBranch::Domain::print().
Friends And Related Function Documentation
friend class BranchProblem friend
Member Data Documentation
MAYBranch::Domain otawa::BranchProblem::Domain::may private
Referenced by otawa::BranchProblem::enterContext(), equals(), otawa::BranchProblem::leaveContext(), lub(), and operator=().
MUSTBranch::Domain otawa::BranchProblem::Domain::must private
Referenced by otawa::BranchProblem::BranchProblem(), otawa::BranchProblem::enterContext(), equals(), otawa::BranchProblem::leaveContext(), lub(), and operator=().
PERSBranch::Domain otawa::BranchProblem::Domain::pers private
Referenced by otawa::BranchProblem::BranchProblem(), otawa::BranchProblem::enterContext(), equals(), otawa::BranchProblem::leaveContext(), lub(), and operator=().
The documentation for this class was generated from the following file:
include/otawa/branch/BranchProblem.h