Otawa: otawa::ContextualLoopBound Class Reference
otawa::ContextualLoopBound Class Reference
A contextual loop bound is a collection of loop bound (including max iteration and total iteration number) for the different call contexts of a loop.
#include <otawa/flowfact/ContextualLoopBound.h>
Classes
struct data_t
Public Member Functions
ContextualLoopBound (int max=undefined, int total=undefined)
Build a contextual loop bound with the given bounds.
void addMax (const ContextPath< Address > &path, int max) throw (AmbiguousBoundException)
Add a context max bound.
void addTotal (const ContextPath< Address > &path, int total) throw (AmbiguousBoundException)
Add a context total bound.
int findMax (const ContextPath< Address > &path)
Find the maximum bound for the given context.
int findTotal (const ContextPath< Address > &path)
Find the total bound for the given context.
Static Public Attributes
static const int undefined = -1
Private Types
typedef struct otawa::ContextualLoopBound::data_t data_t
Private Member Functions
genstruct::Tree< data_t > * look (const ContextPath< Address > &path)
Look for the subtree matching the given path (build the subtree if required).
int lookMax (genstruct::Tree< data_t > *cur)
Look to find the maximum in the tree children.
int lookTotal (genstruct::Tree< data_t > *cur)
Look to find the total in the tree children.
void print (genstruct::Tree< data_t > *cur, int tab=0)
Private Attributes
genstruct::Tree< data_t > tree
Detailed Description
A contextual loop bound is a collection of loop bound (including max iteration and total iteration number) for the different call contexts of a loop.
The contextual loop bound does not require to contain all possible contexts but enough information for the top part of the call context. At worse, it may only contain the max loop bound for any context. The collection of the collections does not need to be exhaustive if safe loop count is given for less precise contexts.
Member Typedef Documentation
typedef struct otawa::ContextualLoopBound::data_t otawa::ContextualLoopBound::data_t private
Constructor & Destructor Documentation
otawa::ContextualLoopBound::ContextualLoopBound (int max = undefined, int total = undefined)
Build a contextual loop bound with the given bounds.
Parameters
max Maximum iteration.
total Total iteration.
Member Function Documentation
void otawa::ContextualLoopBound::addMax (const ContextPath< Address > & path, int max) throw (AmbiguousBoundException)
Add a context max bound.
Parameters
path Call context.
max Max bound.
Exceptions
AmbiguousBoundException Thrown when there is already a bound for the given context.
References look(), and otawa::clp::max().
void otawa::ContextualLoopBound::addTotal (const ContextPath< Address > & path, int total) throw (AmbiguousBoundException)
Add a context total bound.
Parameters
path Call context.
total Total bound.
Exceptions
AmbiguousBoundException Thrown when there is already a bound for the given context.
References look(), and otawa::clp::max().
int otawa::ContextualLoopBound::findMax (const ContextPath< Address > & path)
Find the maximum bound for the given context.
Parameters
path Context path.
Returns
Maxmimum value (may be undefined).
References otawa::ContextPath< T >::count(), lookMax(), otawa::clp::max(), tree, and undefined.
int otawa::ContextualLoopBound::findTotal (const ContextPath< Address > & path)
Find the total bound for the given context.
Parameters
path Context path.
Returns
Total value (may be undefined).
References otawa::CONTEXTUAL_LOOP_BOUND, otawa::ContextPath< T >::count(), lookTotal(), otawa::clp::max(), tree, and undefined.
genstruct::Tree< ContextualLoopBound::data_t > * otawa::ContextualLoopBound::look (const ContextPath< Address > & path) private
Look for the subtree matching the given path (build the subtree if required).
Parameters
path Path to look in.
Returns
Matching subtree.
References otawa::ContextPath< T >::count(), and tree.
Referenced by addMax(), and addTotal().
int otawa::ContextualLoopBound::lookMax (genstruct::Tree< data_t > * cur) private
Look to find the maximum in the tree children.
Parameters
cur Tree to look in.
Returns
Maximum.
References otawa::clp::max(), and undefined.
Referenced by findMax().
int otawa::ContextualLoopBound::lookTotal (genstruct::Tree< data_t > * cur) private
Look to find the total in the tree children.
Parameters
cur Tree to look in.
Returns
Total.
References undefined.
Referenced by findTotal().
void otawa::ContextualLoopBound::print (genstruct::Tree< data_t > * cur, int tab = 0) private
Member Data Documentation
genstruct::Tree<data_t> otawa::ContextualLoopBound::tree private
Referenced by findMax(), findTotal(), and look().
const int otawa::ContextualLoopBound::undefined = -1 static
Referenced by findMax(), findTotal(), lookMax(), and lookTotal().
The documentation for this class was generated from the following files:
include/otawa/flowfact/ContextualLoopBound.h
src/prog/flowfact_ContextualLoopBound.cpp