Otawa: otawa::hard::BHT Class Reference
otawa::hard::BHT Class Reference
This class contains all information about the Branch History Predictor, that is,.
#include <otawa/hard/BHT.h>
Public Types
enum replace_policy_t {
NONE = 0, OTHER = 1, LRU = 2, RANDOM = 3,
FIFO = 4, PLRU = 5
}
typedef enum otawa::hard::PureCache::replace_policy_t replace_policy_t
Public Member Functions
BHT (void)
virtual ~BHT (void)
void setCondPenalty (int time)
void setIndirectPenalty (int time)
void setCondIndirectPenalty (int time)
void setDefaultPrediction (int def)
int getCondPenalty (void) const
int getIndirectPenalty (void) const
int getCondIndirectPenalty (void) const
int getDefaultPrediction (void) const
ot::size cacheSize (void) const
ot::size blockSize (void) const
int wayCount (void) const
int rowCount (void) const
int blockCount (void) const
replace_policy_t replacementPolicy (void) const
int blockBits (void) const
int rowBits (void) const
int tagBits (void) const
int wayBits (void) const
ot::mask blockMask (void) const
ot::mask lineMask (void) const
ot::mask tagMask (void) const
ot::mask offset (address_t addr) const
ot::mask line (address_t addr) const
ot::mask tag (address_t addr) const
ot::mask block (address_t addr) const
void setBlockBits (int block_bits)
void setRowBits (int set_bits)
Set the row count as a number of bits.
void setWayBits (int way_bits)
Set the way count as a number of bits.
void setReplacePolicy (replace_policy_t replace)
Set the replace policy of the cache.
Public Attributes
int block_bits
int row_bits
int way_bits
replace_policy_t replace
Private Member Functions
SERIALIZABLE (BHT, ELM_BASE(PureCache)&DFIELD(cond_penalty, 10)&DFIELD(indirect_penalty, 10)&DFIELD(cond_indirect_penalty, 10)&)
Private Attributes
int cond_penalty
int indirect_penalty
int cond_indirect_penalty
int def_predict
Detailed Description
This class contains all information about the Branch History Predictor, that is,.
the definition of the stored target a cache,
timing information for non-predicted conditional branch,
timing for predicted indirect branch,
timing for non-predicted indirect branch,
default prediction behavior.
Member Typedef Documentation
typedef enum otawa::hard::PureCache::replace_policy_t otawa::hard::PureCache::replace_policy_t inherited
Member Enumeration Documentation
enum otawa::hard::PureCache::replace_policy_t inherited
Enumerator
NONE
OTHER
LRU
RANDOM
FIFO
PLRU
Constructor & Destructor Documentation
otawa::hard::BHT::BHT (void) inline
virtual otawa::hard::BHT::~BHT (void) inline virtual
Member Function Documentation
ot::mask otawa::hard::PureCache::block (address_t addr) const inline inherited
References otawa::hard::PureCache::blockBits(), ENUM(), and otawa::Address::offset().
Referenced by otawa::hard::PureCache::blockCount().
int otawa::hard::PureCache::blockBits (void) const inline inherited
References otawa::hard::PureCache::block_bits.
Referenced by otawa::hard::PureCache::block(), otawa::hard::PureCache::blockCount(), otawa::hard::PureCache::blockSize(), otawa::hard::PureCache::cacheSize(), otawa::hard::PureCache::line(), otawa::hard::PureCache::lineMask(), otawa::hard::PureCache::tag(), and otawa::hard::PureCache::tagBits().
int otawa::hard::PureCache::blockCount (void) const inline inherited
References otawa::hard::PureCache::block(), otawa::hard::PureCache::blockBits(), otawa::hard::PureCache::blockMask(), otawa::hard::PureCache::line(), otawa::hard::PureCache::lineMask(), otawa::hard::PureCache::offset(), otawa::hard::PureCache::replacementPolicy(), otawa::hard::PureCache::rowBits(), otawa::hard::PureCache::setBlockBits(), otawa::hard::PureCache::setReplacePolicy(), otawa::hard::PureCache::setRowBits(), otawa::hard::PureCache::setWayBits(), otawa::hard::PureCache::tag(), otawa::hard::PureCache::tagBits(), otawa::hard::PureCache::tagMask(), otawa::hard::PureCache::way_bits, and otawa::hard::PureCache::wayBits().
ot::mask otawa::hard::PureCache::blockMask (void) const inline inherited
References otawa::hard::PureCache::blockSize().
Referenced by otawa::hard::PureCache::blockCount(), otawa::hard::PureCache::offset(), and otawa::hard::PureCache::tagMask().
ot::size otawa::hard::PureCache::blockSize (void) const inline inherited
References otawa::hard::PureCache::blockBits().
Referenced by otawa::hard::PureCache::blockMask(), and otawa::hard::PureCache::~PureCache().
ot::size otawa::hard::PureCache::cacheSize (void) const inline inherited
References otawa::hard::PureCache::blockBits(), otawa::hard::PureCache::rowBits(), and otawa::hard::PureCache::wayBits().
Referenced by otawa::hard::PureCache::~PureCache().
int otawa::hard::BHT::getCondIndirectPenalty (void) const inline
References cond_indirect_penalty.
int otawa::hard::BHT::getCondPenalty (void) const inline
References cond_penalty.
Referenced by otawa::etime::StandardEventBuilder::handleVariableBranchPred(), and otawa::etime::StandardEventBuilder::processBB().
int otawa::hard::BHT::getDefaultPrediction (void) const inline
References otawa::hard::BHT_CONFIG, otawa::hard::BHT_FEATURE, and def_predict.
int otawa::hard::BHT::getIndirectPenalty (void) const inline
References indirect_penalty.
ot::mask otawa::hard::PureCache::line (address_t addr) const inline inherited
References otawa::hard::PureCache::blockBits(), otawa::hard::PureCache::lineMask(), and otawa::Address::offset().
Referenced by otawa::hard::PureCache::blockCount().
ot::mask otawa::hard::PureCache::lineMask (void) const inline inherited
References otawa::hard::PureCache::blockBits(), and otawa::hard::PureCache::rowCount().
Referenced by otawa::hard::PureCache::blockCount(), otawa::hard::PureCache::line(), and otawa::hard::PureCache::tagMask().
ot::mask otawa::hard::PureCache::offset (address_t addr) const inline inherited
References otawa::hard::PureCache::blockMask(), and otawa::Address::offset().
Referenced by otawa::hard::PureCache::blockCount().
PureCache::replace_policy_t otawa::hard::PureCache::replacementPolicy (void) const inline inherited
References otawa::hard::PureCache::replace.
Referenced by otawa::hard::PureCache::blockCount().
int otawa::hard::PureCache::rowBits (void) const inline inherited
References otawa::hard::PureCache::row_bits.
Referenced by otawa::hard::PureCache::blockCount(), otawa::hard::PureCache::cacheSize(), otawa::hard::PureCache::rowCount(), otawa::hard::PureCache::tag(), and otawa::hard::PureCache::tagBits().
int otawa::hard::PureCache::rowCount (void) const inline inherited
References otawa::hard::PureCache::rowBits().
Referenced by otawa::hard::PureCache::lineMask().
otawa::hard::BHT::SERIALIZABLE (BHT , ELM_BASE(PureCache)&DFIELD(cond_penalty, 10)&DFIELD(indirect_penalty, 10)&DFIELD(cond_indirect_penalty, 10)&) private
void otawa::hard::PureCache::setBlockBits (int block_bits) inherited
Referenced by otawa::hard::PureCache::blockCount().
void otawa::hard::BHT::setCondIndirectPenalty (int time) inline
void otawa::hard::BHT::setCondPenalty (int time) inline
void otawa::hard::BHT::setDefaultPrediction (int def) inline
void otawa::hard::BHT::setIndirectPenalty (int time) inline
void otawa::hard::PureCache::setReplacePolicy (replace_policy_t replace) inherited
Set the replace policy of the cache.
Parameters
replace Replace policy, one of OTHER, LRU, RANDOM, FIFO, PLRU.
References otawa::hard::PureCache::FIFO, otawa::hard::PureCache::LRU, otawa::hard::PureCache::NONE, otawa::hard::PureCache::OTHER, otawa::hard::PureCache::PLRU, otawa::hard::PureCache::RANDOM, SERIALIZE(), and VALUE().
Referenced by otawa::hard::PureCache::blockCount().
void otawa::hard::PureCache::setRowBits (int row_bits) inherited
Set the row count as a number of bits.
The actual row count is 1 << row_bits.
Parameters
row_bits Row count in bits.
Referenced by otawa::hard::PureCache::blockCount().
void otawa::hard::PureCache::setWayBits (int way_bits) inherited
Set the way count as a number of bits.
The actual way count is 1 << way_bits.
Parameters
way_bits Way count in bits.
Referenced by otawa::hard::PureCache::blockCount().
ot::mask otawa::hard::PureCache::tag (address_t addr) const inline inherited
References otawa::hard::PureCache::blockBits(), otawa::Address::offset(), and otawa::hard::PureCache::rowBits().
Referenced by otawa::hard::PureCache::blockCount().
int otawa::hard::PureCache::tagBits (void) const inline inherited
References otawa::hard::PureCache::blockBits(), and otawa::hard::PureCache::rowBits().
Referenced by otawa::hard::PureCache::blockCount().
ot::mask otawa::hard::PureCache::tagMask (void) const inline inherited
References otawa::hard::PureCache::blockMask(), and otawa::hard::PureCache::lineMask().
Referenced by otawa::hard::PureCache::blockCount().
int otawa::hard::PureCache::wayBits (void) const inline inherited
References otawa::hard::PureCache::way_bits.
Referenced by otawa::hard::PureCache::blockCount(), otawa::hard::PureCache::cacheSize(), and otawa::hard::PureCache::wayCount().
int otawa::hard::PureCache::wayCount (void) const inline inherited
References otawa::hard::PureCache::wayBits().
Member Data Documentation
int otawa::hard::PureCache::block_bits inherited
Referenced by otawa::hard::PureCache::blockBits().
int otawa::hard::BHT::cond_indirect_penalty private
Referenced by getCondIndirectPenalty().
int otawa::hard::BHT::cond_penalty private
Referenced by getCondPenalty().
int otawa::hard::BHT::def_predict private
Referenced by getDefaultPrediction().
int otawa::hard::BHT::indirect_penalty private
Referenced by getIndirectPenalty().
replace_policy_t otawa::hard::PureCache::replace inherited
Referenced by otawa::hard::PureCache::replacementPolicy().
int otawa::hard::PureCache::row_bits inherited
Referenced by otawa::hard::PureCache::rowBits().
int otawa::hard::PureCache::way_bits inherited
Referenced by otawa::hard::PureCache::blockCount(), and otawa::hard::PureCache::wayBits().
The documentation for this class was generated from the following file:
include/otawa/hard/BHT.h