Otawa: otawa::Monitor Class Reference
otawa::Monitor Class Reference
This class provide a unified interface to interact with external user.
#include <otawa/proc/Monitor.h>
Public Types
enum log_level_t {
LOG_NONE = 0, LOG_PROC = 1, LOG_FILE = 2, LOG_DEPS = LOG_FILE,
LOG_FUN = 3, LOG_CFG = LOG_FUN, LOG_BLOCK = 4, LOG_BB = LOG_BLOCK,
LOG_INST = 5
}
typedef enum otawa::Monitor::log_level_t log_level_t
Public Member Functions
Monitor (void)
WorkSpace * workspace (void)
Get the current workspace.
bool isVerbose (void) const
Test if the verbosity is activated.
bool logFor (log_level_t tested) const
Test if the given log level is activated or not.
log_level_t logLevel (void) const
void configure (const PropList &props)
Public Attributes
elm::io::Output out
Provide a stream to perform output for the user.
elm::io::Output log
Provide a stream to perform log output.
Static Public Attributes
static Monitor & null = __null_mon
Monitor that output nothing.
Protected Member Functions
void setWorkspace (WorkSpace *workspace)
Set the current workspace.
Protected Attributes
t::uint32 flags
Contains various bit flags.
Static Protected Attributes
static const t::uint32 IS_VERBOSE = 0x01
static const t::uint32 CUSTOM_SHIFT = 16
Private Attributes
log_level_t log_level
WorkSpace * ws
Detailed Description
This class provide a unified interface to interact with external user.
It includes features for:
performing output,
log display and support,
current workspace.
It aims to provide to code processor and external analysis a way to perform IO in a clean and compatible way.
The configuration of a monitor is obtained from a property list and supports the following properties:
OUTPUT
LOG
VERBOSE
LOG_LEVEL
In addition, verbosity can be activatedby declaring the environment variable 'OTAWA_VERBOSE'.
Member Typedef Documentation
typedef enum otawa::Monitor::log_level_t otawa::Monitor::log_level_t
Member Enumeration Documentation
enum otawa::Monitor::log_level_t
Enumerator
LOG_NONE
LOG_PROC
LOG_FILE
LOG_DEPS
LOG_FUN
LOG_CFG
LOG_BLOCK
LOG_BB
LOG_INST
Constructor & Destructor Documentation
otawa::Monitor::Monitor (void)
References otawa::LOG, otawa::LOG_LEVEL, LOG_NONE, otawa::OUTPUT, and otawa::VERBOSE.
Member Function Documentation
void otawa::Monitor::configure (const PropList & props)
References flags, otawa::PropList::hasProp(), IS_VERBOSE, log, otawa::LOG, LOG_BB, log_level, otawa::LOG_LEVEL, null, out, otawa::OUTPUT, otawa::VERBOSE, and verbose().
Referenced by otawa::Processor::configure().
bool otawa::Monitor::isVerbose (void) const inline
Test if the verbosity is activated.
Returns
True if verbosity is activated, false else.
Referenced by otawa::ccg::LBlockBuilder::addLBlock(), otawa::LBlockBuilder::addLBlock(), otawa::GraphBBTime< G >::analyzePathContext(), otawa::etime::EdgeTimeBuilder::applyFloppySplit(), otawa::etime::EdgeTimeBuilder::applyStrictSplit(), otawa::etime::EdgeTimeBuilder::applyWeightedSplit(), otawa::etime::EdgeTimeBuilder::makeSplit(), otawa::GraphBBTime< G >::processBB(), otawa::etime::EdgeTimeBuilder::processSequence(), and otawa::dcache::BlockBuilder::setup().
bool otawa::Monitor::logFor (log_level_t tested) const inline
Test if the given log level is activated or not.
Parameters
tested Tested log level.
Returns
True if the log level is activated, false else.
Referenced by otawa::CFGBuilder::addCFG(), otawa::ipet::ConstraintLoader::addConstraint(), otawa::PFGBuilder::addFunction(), otawa::FlowFactLoader::addressOf(), otawa::etime::EdgeTimeBuilder::applyWeightedSplit(), otawa::DelayedBuilder::buildBB(), otawa::CFGBuilder::buildCFG(), otawa::DelayedBuilder::buildEdges(), otawa::branch::BranchBuilder::categorize(), otawa::ipet::FlowFactLoader::cleanup(), otawa::dcache::CATBuilder::cleanup(), otawa::DelayedBuilder::cloneEdge(), otawa::CAT2Builder::configure(), otawa::ACSBuilder::configure(), otawa::etime::EdgeTimeBuilder::genForOneCost(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::Processor::init(), otawa::FlowFactLoader::load(), otawa::FlowFactLoader::loadF4(), otawa::script::Script::makeConfig(), otawa::CFGBuilder::nextBB(), otawa::FlowFactLoader::onLoop(), otawa::FlowFactLoader::onMemoryAccess(), otawa::FlowFactLoader::onNoInline(), otawa::FlowFactLoader::onReturn(), otawa::FlowFactLoader::onSetInlining(), otawa::Processor::process(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::branch::CondNumber::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::dcache::CLPBlockBuilder::processBB(), otawa::etime::StandardEventBuilder::processBB(), otawa::dcache::BlockBuilder::processBB(), otawa::CFGCheckSummer::processCFG(), otawa::EdgeProcessor::processCFG(), otawa::CAT2Builder::processCFG(), otawa::display::CFGOutput::processCFG(), otawa::ipet::ConstraintLoader::processCFG(), otawa::ContextualProcessor::processCFG(), otawa::BBProcessor::processCFG(), otawa::etime::EdgeTimeBuilder::processEdge(), otawa::VarTextDecoder::processEntry(), otawa::dcache::CATBuilder::processLBlockSet(), otawa::ACSMayBuilder::processLBlockSet(), otawa::CAT2Builder::processLBlockSet(), otawa::dcache::ACSBuilder::processLBlockSet(), otawa::etime::EdgeTimeBuilder::processSequence(), otawa::TextDecoder::processWorkSpace(), otawa::VarTextDecoder::processWorkSpace(), otawa::LBlockProcessor::processWorkSpace(), otawa::ipet::WCETComputation::processWorkSpace(), otawa::FixedTextDecoder::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), otawa::PFGBuilder::processWorkSpace(), otawa::StackAnalysis::processWorkSpace(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::branch::BranchBuilder::processWorkSpace(), otawa::CFGProcessor::processWorkSpace(), otawa::Virtualizer::processWorkSpace(), otawa::clp::Analysis::processWorkSpace(), otawa::script::Script::processWorkSpace(), otawa::ilp::Output::setup(), otawa::CFGBuilder::setup(), otawa::BBRatioDisplayer::setup(), otawa::dcache::BlockBuilder::setup(), otawa::CFGBuilder::thisBB(), otawa::ipet::FlowFactLoader::transfer(), otawa::Virtualizer::virtualize(), and otawa::script::Script::work().
log_level_t otawa::Monitor::logLevel (void) const inline
Referenced by otawa::script::Script::declareGlobals().
void otawa::Monitor::setWorkspace (WorkSpace * workspace) inline protected
Set the current workspace.
Parameters
workspace New current workspace.
WorkSpace * otawa::Monitor::workspace (void) inline
Get the current workspace.
Returns
Current workspace.
Member Data Documentation
const t::uint32 otawa::Monitor::CUSTOM_SHIFT = 16 static protected
t::uint32 otawa::Monitor::flags protected
Contains various bit flags.
Bits from 0 to CUSTOM_SHIFT - 1 are private while bits from CUSTOM_SHIFT to 31 may be customized. To build a bit mask for custom bit i, the CUSTOM_SHIFT may be used as below:
static const t::uint32 MY_MASK = 1 << (i + CUSTOM_SHIFT);
Referenced by configure(), otawa::Processor::init(), otawa::Processor::invalidate(), otawa::Processor::prepare(), otawa::Processor::Processor(), otawa::Processor::provide(), otawa::Processor::require(), otawa::Processor::use(), and otawa::Processor::~Processor().
const t::uint32 otawa::Monitor::IS_VERBOSE = 0x01 static protected
Referenced by configure().
elm::io::Output otawa::Monitor::log
Provide a stream to perform log output.
Should be used only when verbosity is activated.
Referenced by otawa::CFGBuilder::addCFG(), otawa::ipet::ConstraintLoader::addConstraint(), otawa::PFGBuilder::addFunction(), otawa::ccg::LBlockBuilder::addLBlock(), otawa::LBlockBuilder::addLBlock(), otawa::FlowFactLoader::addressOf(), otawa::GraphBBTime< G >::analyzePathContext(), otawa::etime::EdgeTimeBuilder::applyFloppySplit(), otawa::etime::EdgeTimeBuilder::applyStrictSplit(), otawa::etime::EdgeTimeBuilder::applyWeightedSplit(), otawa::DelayedBuilder::buildBB(), otawa::CFGBuilder::buildCFG(), otawa::branch::BranchBuilder::categorize(), otawa::ipet::FlowFactLoader::cleanup(), otawa::ipet::TrivialDataCacheManager::configure(), otawa::ACSBuilder::configure(), configure(), otawa::etime::EdgeTimeBuilder::displayConfs(), otawa::ipet::ConstraintLoader::error(), otawa::etime::EdgeTimeBuilder::genForOneCost(), otawa::ipet::ConstraintLoader::getBB(), otawa::VarTextDecoder::getInst(), otawa::ipet::ConstraintLoader::getVar(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::Processor::init(), otawa::FlowFactLoader::load(), otawa::FlowFactLoader::loadF4(), otawa::script::Script::makeConfig(), otawa::etime::EdgeTimeBuilder::makeSplit(), otawa::ipet::ConstraintLoader::newEdgeVar(), otawa::CFGBuilder::nextBB(), otawa::script::Script::onError(), otawa::FlowFactLoader::onLoop(), otawa::FlowFactLoader::onMemoryAccess(), otawa::FlowFactLoader::onNoInline(), otawa::FlowFactLoader::onReturn(), otawa::FlowFactLoader::onSetInlining(), otawa::script::Script::onWarning(), otawa::Processor::process(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::branch::CondNumber::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::dcache::CLPBlockBuilder::processBB(), otawa::etime::StandardEventBuilder::processBB(), otawa::dcache::BlockBuilder::processBB(), otawa::GraphBBTime< G >::processBB(), otawa::CFGCheckSummer::processCFG(), otawa::CAT2Builder::processCFG(), otawa::ipet::ConstraintLoader::processCFG(), otawa::ContextualProcessor::processCFG(), otawa::BBProcessor::processCFG(), otawa::etime::EdgeTimeBuilder::processEdge(), otawa::VarTextDecoder::processEntry(), otawa::dcache::CATBuilder::processLBlockSet(), otawa::ACSMayBuilder::processLBlockSet(), otawa::CAT2Builder::processLBlockSet(), otawa::dcache::ACSBuilder::processLBlockSet(), otawa::etime::EdgeTimeBuilder::processSequence(), otawa::TextDecoder::processWorkSpace(), otawa::VarTextDecoder::processWorkSpace(), otawa::LBlockProcessor::processWorkSpace(), otawa::FixedTextDecoder::processWorkSpace(), otawa::ipet::WCETComputation::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), otawa::StackAnalysis::processWorkSpace(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::branch::BranchBuilder::processWorkSpace(), otawa::CFGProcessor::processWorkSpace(), otawa::Virtualizer::processWorkSpace(), otawa::clp::Analysis::processWorkSpace(), otawa::ilp::Output::setup(), otawa::CFGBuilder::setup(), otawa::BBRatioDisplayer::setup(), otawa::dcache::BlockBuilder::setup(), otawa::CFGBuilder::thisBB(), otawa::ipet::FlowFactLoader::transfer(), otawa::Virtualizer::virtualize(), otawa::Processor::warn(), and otawa::script::Script::work().
log_level_t otawa::Monitor::log_level private
Referenced by configure().
Monitor & otawa::Monitor::null = __null_mon static
Monitor that output nothing.
Referenced by configure().
elm::io::Output otawa::Monitor::out
Provide a stream to perform output for the user.
Referenced by otawa::DelayedBuilder::buildEdges(), configure(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::Processor::init(), otawa::ast::ASTLoader::onError(), otawa::dcache::operator<<(), otawa::CFGChecker::processBB(), otawa::etime::StandardEventBuilder::processBB(), otawa::hard::Dumper::processWorkSpace(), otawa::ccg::Builder::processWorkSpace(), otawa::SubCFGBuilder::SubCFGBuilder(), and otawa::Virtualizer::virtualize().
WorkSpace* otawa::Monitor::ws private
The documentation for this class was generated from the following files:
include/otawa/proc/Monitor.h
src/prog/proc_Monitor.cpp