Otawa: otawa::DynProcessor Class Reference
otawa::DynProcessor Class Reference
This pseudo-processor allows to call processor based on their name.
#include <otawa/proc/DynProcessor.h>
Public Member Functions
DynProcessor (cstring name) throw (ProcessorNotFound)
Find the processor whose name is given.
~DynProcessor (void)
string name (void) const
Get the name of the processor.
Version version (void) const
Get the version of the processor.
void configure (const PropList &props)
Configure the processor.
void process (WorkSpace *ws, const PropList &props=PropList::EMPTY)
Process the given workspace on the processor.
Private Attributes
Processor * proc
Detailed Description
This pseudo-processor allows to call processor based on their name.
It is useful when one does not want or does not can't to include the requested processor. For example, it may be useful when the processor is contained in a plugin. In this case, the plugin will be automatically plugged and used.
Constructor & Destructor Documentation
otawa::DynProcessor::~DynProcessor (void)
References proc().
Member Function Documentation
void otawa::DynProcessor::configure (const PropList & props) inline
Configure the processor.
Parameters
props Configuration to pass to the processor.
References otawa::PropList::EMPTY, and proc().
string otawa::DynProcessor::name (void) const inline
Get the name of the processor.
Returns
Processor name.
References proc().
void otawa::DynProcessor::process (WorkSpace * ws, const PropList & props = PropList::EMPTY)
Process the given workspace on the processor.
Parameters
ws Workspace to work on.
props Configuration properties.
References proc().
Referenced by otawa::script::Script::work().
Version otawa::DynProcessor::version (void) const inline
Get the version of the processor.
Returns
Processor version.
References proc().
Member Data Documentation
Processor* otawa::DynProcessor::proc private
The documentation for this class was generated from the following files:
include/otawa/proc/DynProcessor.h
src/prog/proc_DynProcessor.cpp