Otawa: otawa::Address Class Reference
otawa::Address Class Reference
The representation of an address in OTAWA.
#include <otawa/base.h>
Public Types
typedef t::uint32 page_t
typedef t::uint32 offset_t
Public Member Functions
Address (void)
Build a null address.
Address (offset_t offset)
Build a simple absolute address.
Address (page_t page, offset_t offset)
Build a full address.
Address (const Address &address)
Build an address by cloning.
Address (const MemArea &mem_area)
page_t page (void) const
Get the page number.
offset_t offset (void) const
Get the offset value.
offset_t operator* (void) const
Short cut to offset().
bool isNull (void) const
Test if the address is null.
operator offset_t (void) const
shortcut to offset().
Address & operator= (const Address &address)
Address & operator= (offset_t offset)
Address & operator+= (int offset)
Address & operator+= (t::uint32 offset)
Address & operator-= (int offset)
Address & operator-= (t::uint32 offset)
Address operator+ (t::int32 offset) const
Address operator+ (t::uint32 offset) const
Address operator- (t::int32 offset) const
Address operator- (t::uint32 offset) const
offset_t operator- (const Address &address) const
bool equals (const Address &address) const
Test if two address are equals.
int compare (const Address &address) const
Compare two addresses and returns:
bool operator== (const Address &addr) const
bool operator!= (const Address &addr) const
bool operator< (const Address &addr) const
bool operator<= (const Address &addr) const
bool operator> (const Address &addr) const
bool operator>= (const Address &addr) const
Static Public Attributes
static Address null
Null address.
static const page_t null_page = elm::type_info<page_t>::max
Private Attributes
page_t pg
offset_t off
Detailed Description
The representation of an address in OTAWA.
To match most architectures, the address is split in two component:
a page component,
an offset component from the page.
The page component may be used to represent different, non overlapping address spaces. For example, a Harvard architecture for example: page 0 may be used to store code and page 1 to store data.
It is bad idea to use the page to represent segemented memory as in the paged mode of the x86 architecture. The rule is that each item must have a unique address in order to perform valid address comparison and computation. For example, the M68HCxx banking memory that assign different code banks in memory from 0x8000 to 0xC000 is better handled by assigning to each an absolute address above the maximal address computed by: 0x10000 + bank_number * 0x4000.
Finally, notice that the page 0xffffffff is reserved to represent the null address.
Member Typedef Documentation
typedef t::uint32 otawa::Address::offset_t
typedef t::uint32 otawa::Address::page_t
Constructor & Destructor Documentation
otawa::Address::Address (void) inline
Build a null address.
otawa::Address::Address (offset_t offset) inline
Build a simple absolute address.
Parameters
offset Absolute value of the address.
otawa::Address::Address (page_t page, offset_t offset) inline
Build a full address.
Parameters
page Address page.
offset Offset in the page.
otawa::Address::Address (const Address & address) inline
Build an address by cloning.
Parameters
address Cloned address.
otawa::Address::Address (const MemArea & mem_area) inline
Member Function Documentation
int otawa::Address::compare (const Address & address) const inline
Compare two addresses and returns:
<0 if the current address is less than the given one,
=0 if both addresses are equal,
>0 if the current address is greater than the given one.
Warning
It is an error to compare address of different pages.
Parameters
address Address to compare to.
Returns
See above.
References off, and pg.
Referenced by otawa::clp::operator<<().
bool otawa::Address::equals (const Address & address) const inline
Test if two address are equals.
Parameters
address Address to compare with.
Returns
True if both addresses are equals, false else.
References off, and pg.
bool otawa::Address::isNull (void) const inline
Test if the address is null.
Returns
True if it is the null address, false else.
Referenced by otawa::FlowFactLoader::addressOf(), otawa::dcache::Block::Block(), otawa::WorkSpace::format(), otawa::dcache::BlockCollection::obtain(), operator-(), otawa::operator<<(), otawa::stack::operator<<(), otawa::dcache::BlockBuilder::processBB(), otawa::hard::Cache::round(), otawa::FlowFactLoader::scanAddress(), otawa::FlowFactLoader::scanXBody(), otawa::FlowFactLoader::scanXCall(), otawa::FlowFactLoader::scanXFun(), otawa::FlowFactLoader::scanXLoop(), and otawa::CFGProcessor::str().
offset_t otawa::Address::offset (void) const inline
Get the offset value.
Returns
Offset value.
Referenced by elm::serial2::__serialize(), otawa::ParExeGraph::addEdgesForFetch(), otawa::ot::address(), otawa::hard::PureCache::block(), otawa::hard::Cache::block(), otawa::Process::findSymbolAt(), elm::HashKey< otawa::Address >::hash(), otawa::dfa::State::isInitialized(), otawa::hard::PureCache::line(), otawa::hard::Cache::line(), otawa::hard::PureCache::offset(), otawa::hard::Cache::offset(), otawa::operator<<(), otawa::stack::operator<<(), otawa::clp::operator<<(), otawa::BBRatioDisplayer::processBB(), otawa::dcache::BlockBuilder::processBB(), otawa::hard::Cache::round(), otawa::FlowFactLoader::scanValue(), otawa::CFGProcessor::str(), otawa::hard::PureCache::tag(), and otawa::hard::Cache::tag().
otawa::Address::operator offset_t (void) const inline
shortcut to offset().
bool otawa::Address::operator!= (const Address & addr) const inline
offset_t otawa::Address::operator* (void) const inline
Short cut to offset().
Address otawa::Address::operator+ (t::int32 offset) const inline
Address otawa::Address::operator+ (t::uint32 offset) const inline
Address& otawa::Address::operator+= (int offset) inline
Address& otawa::Address::operator+= (t::uint32 offset) inline
Address otawa::Address::operator- (t::int32 offset) const inline
Address otawa::Address::operator- (t::uint32 offset) const inline
offset_t otawa::Address::operator- (const Address & address) const inline
References isNull(), off, and pg.
Address& otawa::Address::operator-= (int offset) inline
Address& otawa::Address::operator-= (t::uint32 offset) inline
bool otawa::Address::operator< (const Address & addr) const inline
References off, and pg.
bool otawa::Address::operator<= (const Address & addr) const inline
References off, and pg.
Address& otawa::Address::operator= (const Address & address) inline
References off, and pg.
Address& otawa::Address::operator= (offset_t offset) inline
bool otawa::Address::operator== (const Address & addr) const inline
bool otawa::Address::operator> (const Address & addr) const inline
References off, and pg.
bool otawa::Address::operator>= (const Address & addr) const inline
References off, and pg.
page_t otawa::Address::page (void) const inline
Get the page number.
Returns
Page number.
Referenced by elm::serial2::__serialize(), otawa::hard::Bank::contains(), otawa::Segment::findItemAt(), elm::HashKey< otawa::Address >::hash(), otawa::operator<<(), otawa::dcache::BlockBuilder::processBB(), and otawa::hard::Cache::round().
Member Data Documentation
Address otawa::Address::null static
Null address.
Please that the null address is not the adress 0 but an invalid address that can not be mapped to the platform memory :
Address::null != Address(0x00000000)
Referenced by otawa::CFG::address(), otawa::FlowFactLoader::addressOf(), otawa::Exception::Exception(), otawa::File::findLabel(), otawa::Process::findLabel(), otawa::ContextualPath::getEnclosingFunction(), otawa::Process::initialSP(), otawa::sim::Driver::lowerRead(), otawa::sim::Driver::lowerWrite(), otawa::OutOfSegmentException::message(), otawa::Inst::multiCount(), otawa::Manager::prefixPath(), otawa::StackAnalysis::processWorkSpace(), otawa::CFGProcessor::str(), otawa::LabelAddress::toAddress(), otawa::sim::Driver::upperRead(), and otawa::sim::Driver::upperWrite().
const page_t otawa::Address::null_page = elm::type_info<page_t>::max static
offset_t otawa::Address::off private
Referenced by compare(), equals(), operator-(), operator<(), operator<=(), operator=(), operator>(), and operator>=().
page_t otawa::Address::pg private
Referenced by compare(), equals(), operator-(), operator<(), operator<=(), operator=(), operator>(), and operator>=().
The documentation for this class was generated from the following files:
include/otawa/base.h
src/prog/base.cpp