Otawa: otawa::display::CFGAdapter::Vertex Class Reference
otawa::display::CFGAdapter::Vertex Class Reference
#include <otawa/display/CFGAdapter.h>
Public Member Functions
Vertex (BasicBlock *_bb)
int index (void)
Public Attributes
BasicBlock * bb
Constructor & Destructor Documentation
otawa::display::CFGAdapter::Vertex::Vertex (BasicBlock * _bb) inline
Referenced by otawa::display::CFGAdapter::Iterator::item(), otawa::display::CFGAdapter::Edge::sink(), and otawa::display::CFGAdapter::Edge::source().
Member Function Documentation
int otawa::display::CFGAdapter::Vertex::index (void) inline
References bb, and otawa::BasicBlock::number().
Member Data Documentation
BasicBlock* otawa::display::CFGAdapter::Vertex::bb
Referenced by index(), and otawa::display::CFGAdapter::VertexMap< T >::put().
The documentation for this class was generated from the following file:
include/otawa/display/CFGAdapter.h