Otawa: otawa::CFGCollection::BBIterator Class Reference
otawa::CFGCollection::BBIterator Class Reference
#include <otawa/cfg/features.h>
Public Member Functions
BBIterator (const CFGCollection *cfgs)
BBIterator (const BBIterator &i)
BBIterator & operator= (const BBIterator &i)
bool ended (void) const
BasicBlock * item (void) const
void next (void)
Private Attributes
Iterator cfg
CFG::BBIterator bb
Constructor & Destructor Documentation
otawa::CFGCollection::BBIterator::BBIterator (const CFGCollection * cfgs) inline
otawa::CFGCollection::BBIterator::BBIterator (const BBIterator & i) inline
Member Function Documentation
bool otawa::CFGCollection::BBIterator::ended (void) const inline
References otawa::cfgio::bb().
BasicBlock* otawa::CFGCollection::BBIterator::item (void) const inline
References otawa::cfgio::bb().
void otawa::CFGCollection::BBIterator::next (void) inline
References otawa::cfgio::bb(), and otawa::cfgio::cfg().
BBIterator& otawa::CFGCollection::BBIterator::operator= (const BBIterator & i) inline
References bb, otawa::cfgio::bb(), cfg, and otawa::cfgio::cfg().
Member Data Documentation
CFG::BBIterator otawa::CFGCollection::BBIterator::bb private
Referenced by operator=().
Iterator otawa::CFGCollection::BBIterator::cfg private
Referenced by operator=().
The documentation for this class was generated from the following file:
include/otawa/cfg/features.h