Otawa: otawa::ParExePipeline Class Reference
otawa::ParExePipeline Class Reference
Parametric Execution Graph
Representation of a pipeline (list of stages).
#include <otawa/parexegraph/ParExeProc.h>
Classes
class StageIterator
Public Member Functions
ParExePipeline ()
~ParExePipeline ()
ParExeStage * lastStage ()
ParExeStage * firstStage ()
void addStage (ParExeStage *stage)
Adds a stage to the pipeline.
int numStages ()
Protected Attributes
elm::genstruct::Vector< ParExeStage * > _stages
Private Attributes
ParExeStage * _last_stage
ParExeStage * _first_stage
Detailed Description
Representation of a pipeline (list of stages).
See also
Parametric Execution Graph
Constructor & Destructor Documentation
otawa::ParExePipeline::ParExePipeline () inline
otawa::ParExePipeline::~ParExePipeline () inline
Member Function Documentation
void otawa::ParExePipeline::addStage (ParExeStage * stage) inline
Adds a stage to the pipeline.
Stages must be added in the pipeline order.
Parameters
Pointer to the stage to be added.
References otawa::ParExeStage::destinationQueue(), otawa::ParExeQueue::setEmptyingStage(), otawa::ParExeQueue::setFillingStage(), and otawa::ParExeStage::sourceQueue().
Referenced by otawa::ParExeStage::addFunctionalUnit(), and otawa::ParExeProc::ParExeProc().
ParExeStage * otawa::ParExePipeline::firstStage () inline
Returns
Pointer to the first stage.
Referenced by otawa::ParExeGraph::addEdgesForDataDependencies(), otawa::ParExeGraph::addEdgesForMemoryOrder(), otawa::GraphBBTime< G >::BuildVectorOfHwResources(), otawa::ParExeProc::ParExeProc(), and otawa::ResourceList::ResourceList().
ParExeStage * otawa::ParExePipeline::lastStage () inline
Returns
Pointer to the last stage.
Referenced by otawa::ParExeProc::isLastStage(), and otawa::ParExeProc::lastStage().
int otawa::ParExePipeline::numStages () inline
Returns
Number of stages.
Referenced by otawa::GraphBBTime< G >::BuildVectorOfHwResources(), otawa::ParExeGraph::delta(), otawa::ParExeProc::ParExeProc(), and otawa::ResourceList::ResourceList().
Member Data Documentation
ParExeStage* otawa::ParExePipeline::_first_stage private
ParExeStage* otawa::ParExePipeline::_last_stage private
elm::genstruct::Vector<ParExeStage *> otawa::ParExePipeline::_stages protected
The documentation for this class was generated from the following files:
include/otawa/parexegraph/ParExeProc.h
src/prog/parexegraph_ParExeProc.cpp