Otawa: otawa::PropList::Iter Class Reference
otawa::PropList::Iter Class Reference
Properties System
This iterator is used for reading all properties of a property list.
#include <otawa/prop/PropList.h>
Public Member Functions
Iter (const PropList &list)
Build a property iterator.
Iter (const PropList *list)
Build a property iterator.
void next (void)
Go to the next property.
bool ended (void) const
Test if there is still a property to examine.
Property * item (void) const
Get the current property.
bool operator== (const AbstractIdentifier *id) const
Equality overload for testing if a property is equals to an identifier.
bool operator!= (const AbstractIdentifier *id) const
Equality overload for testing if a property is equals to an identifier.
bool operator== (const AbstractIdentifier &id) const
Equality overload for testing if a property is equals to an identifier.
bool operator!= (const AbstractIdentifier &id) const
Equality overload for testing if a property is equals to an identifier.
Private Attributes
Property * prop
Detailed Description
This iterator is used for reading all properties of a property list.
Constructor & Destructor Documentation
otawa::PropList::Iter::Iter (const PropList & list) inline
Build a property iterator.
Parameters
list Property list to traverse.
otawa::PropList::Iter::Iter (const PropList * list) inline
Build a property iterator.
Parameters
list Property list to traverse.
Member Function Documentation
bool otawa::PropList::Iter::ended (void) const inline
Test if there is still a property to examine.
Returns
True if traversal is ended.
Referenced by otawa::display::GraphVizItem::attributes(), and otawa::display::GraphVizItem::getPropertiesString().
Property * otawa::PropList::Iter::item (void) const inline
Get the current property.
void otawa::PropList::Iter::next (void) inline
Go to the next property.
References otawa::Property::next().
bool otawa::PropList::Iter::operator!= (const AbstractIdentifier * id) const inline
Equality overload for testing if a property is equals to an identifier.
bool otawa::PropList::Iter::operator!= (const AbstractIdentifier & id) const inline
Equality overload for testing if a property is equals to an identifier.
bool otawa::PropList::Iter::operator== (const AbstractIdentifier * id) const inline
Equality overload for testing if a property is equals to an identifier.
bool otawa::PropList::Iter::operator== (const AbstractIdentifier & id) const inline
Equality overload for testing if a property is equals to an identifier.
Member Data Documentation
Property* otawa::PropList::Iter::prop private
The documentation for this class was generated from the following files:
include/otawa/prop/PropList.h
src/prog/prop_PropList.cpp