Otawa: otawa::PERSProblem Class Reference
otawa::PERSProblem Class Reference
Problem for computing the PERS ACS of L-blocks.
#include <otawa/cache/cat2/PERSProblem.h>
Classes
class Domain
class Item
Public Member Functions
PERSProblem (const int _size, LBlockSet *_lbset, WorkSpace *_fw, const hard::Cache *_cache, const int _A)
~PERSProblem ()
const Domain & bottom (void) const
const Domain & entry (void) const
void lub (Domain &a, const Domain &b) const
void assign (Domain &a, const Domain &b) const
bool equals (const Domain &a, const Domain &b) const
void update (Domain &out, const Domain &in, BasicBlock *bb)
void enterContext (Domain &dom, BasicBlock *header, hai_context_t ctx)
void leaveContext (Domain &dom, BasicBlock *header, hai_context_t ctx)
Public Attributes
Domain callstate
Private Attributes
LBlockSet * lbset
CFG * cfg
WorkSpace * fw
const hard::Cache * cache
Domain bot
Domain ent
const int line
Detailed Description
Problem for computing the PERS ACS of L-blocks.
This implements Ferdinand's Persistence analysis.
Constructor & Destructor Documentation
otawa::PERSProblem::PERSProblem (const int _size, LBlockSet * _lbset, WorkSpace * _fw, const hard::Cache * _cache, const int _A)
References bot, otawa::PERSProblem::Domain::empty(), ent, otawa::PERSProblem::Domain::enterContext(), and otawa::PERSProblem::Domain::setToBottom().
otawa::PERSProblem::~PERSProblem ()
Member Function Documentation
void otawa::PERSProblem::assign (Domain & a, const Domain & b) const inline
Referenced by otawa::MUSTPERS::MUSTPERS().
const PERSProblem::Domain & otawa::PERSProblem::bottom (void) const
References bot.
Referenced by otawa::MUSTPERS::MUSTPERS().
void otawa::PERSProblem::enterContext (Domain & dom, BasicBlock * header, hai_context_t ctx) inline
References otawa::dfa::hai::CTX_LOOP, and otawa::PERSProblem::Domain::enterContext().
Referenced by otawa::MUSTPERS::enterContext().
const PERSProblem::Domain & otawa::PERSProblem::entry (void) const
References ent.
Referenced by otawa::MUSTPERS::MUSTPERS().
bool otawa::PERSProblem::equals (const Domain & a, const Domain & b) const inline
References otawa::cfgio::bb(), otawa::PERSProblem::Domain::equals(), and update().
void otawa::PERSProblem::leaveContext (Domain & dom, BasicBlock * header, hai_context_t ctx) inline
References otawa::dfa::hai::CTX_LOOP, otawa::PERSProblem::Domain::leaveContext(), and otawa::operator<<().
Referenced by otawa::MUSTPERS::leaveContext().
void otawa::PERSProblem::lub (Domain & a, const Domain & b) const inline
References otawa::PERSProblem::Domain::lub().
void otawa::PERSProblem::update (Domain & out, const Domain & in, BasicBlock * bb)
Referenced by equals().
Member Data Documentation
Domain otawa::PERSProblem::bot private
Referenced by bottom(), and PERSProblem().
const hard::Cache* otawa::PERSProblem::cache private
Domain otawa::PERSProblem::callstate
CFG* otawa::PERSProblem::cfg private
Domain otawa::PERSProblem::ent private
Referenced by entry(), and PERSProblem().
WorkSpace* otawa::PERSProblem::fw private
LBlockSet* otawa::PERSProblem::lbset private
const int otawa::PERSProblem::line private
The documentation for this class was generated from the following files:
include/otawa/cache/cat2/PERSProblem.h
src/prog/cache_PERSProblem.cpp