Otawa: otawa::dfa::hai::HalfAbsInt< FixPoint > Class Template Reference
otawa::dfa::hai::HalfAbsInt< FixPoint > Class Template Reference
Implements abstract interpretation.
#include <otawa/dfa/hai/HalfAbsInt.h>
Public Member Functions
FixPoint::FixPointState * getFixPointState (BasicBlock *bb)
Get the FixPointState of a loop.
int solve (otawa::CFG *main_cfg=0, typename FixPoint::Domain *entdom=0, BasicBlock *start_bb=0)
Do the abstract interpretation of the CFG.
HalfAbsInt (FixPoint &_fp, WorkSpace &_fw)
~HalfAbsInt (void)
FixPoint::Domain backEdgeUnion (BasicBlock *bb)
Given a loop header, returns the union of the value of its back edges.
FixPoint::Domain entryEdgeUnion (BasicBlock *bb)
Given a loop header, returns the union of the value of is entry edges (the entry edges are the in-edges that are not back-edges.)
Private Member Functions
bool isEdgeDone (Edge *edge)
Tests if an edge verify the conditions needed to add its target BasicBlock.
bool tryAddToWorkList (BasicBlock *bb)
Try to add the BasicBlock to the worklist.
Edge * detectCalls (bool &enter_call, elm::genstruct::Vector< Edge * > &call_edges, BasicBlock *bb)
void inputProcessing (typename FixPoint::Domain &entdom)
void outputProcessing ()
void addSuccessors ()
Private Attributes
FixPoint & fp
WorkSpace & ws
CFG & entry_cfg
CFG * cur_cfg
elm::genstruct::Vector< BasicBlock * > * workList
elm::genstruct::Vector< Edge * > * callStack
elm::genstruct::Vector< CFG * > * cfgStack
BasicBlock * current
FixPoint::Domain in
FixPoint::Domain out
elm::genstruct::Vector< Edge * > call_edges
Edge * next_edge
bool enter_call
bool fixpoint
bool mainEntry
Static Private Attributes
static Identifier< typename FixPoint::FixPointState * > FIXPOINT_STATE
Detailed Description
template<class FixPoint>
class otawa::dfa::hai::HalfAbsInt< FixPoint >
Implements abstract interpretation.
Parameters
FixPoint Class used to manage loops.
FixPoint
This parameter must match the following signature:
class FixPoint {
                typedef ... Domain;
                class FixPointState {
                        ...
                };
                void init(CFG*, HalfAbsInt<FixPoint>*);
                FixPointState *newState(void);
                void fixPoint(BasicBlock*, bool&, Domain&, bool) const;
                void markEdge(Edge*, Domain&);
                void unmarkEdge(Edge*);
                Domain* getMark(Edge*);
                const Domain& bottom(void);
        void lub(Domain &, const Domain &) const;
        void assign(Domain &, const Domain &) const;
        bool equals(const Domain &, const Domain &) const;
        void update(Domain &, const Domain &, BasicBlock*) const;
        void blockInterpreted(BasicBlock*, const Domain&, const Domain&) const ;
        void fixPointReached(BasicBlock*) const;
                const Domain& entry(void);
}
Signature explanation
Domain – this type is the Domain of the abstract values used in the abstract interpretation.
FixPointState – this class can holds, for each loop, status informations needed by FixPoint. This status information can be accessed and modified by calling the halfAbsInt::getFixPointState() method.
void init(CFG*, HalfAbsInt<FixPoint>*) – Method called at HalfAbsInt initialization. Gives FixPoint the chance to perform initialization tasks that were impossible to do in FixPoint's constructor because HalfAbsInt was not instantiated yet.
FixPointState *newState(void) – Create a new (empty) FixPointState.
markEdge(Edge*, Domain&) – Mark the edge with the value.
unmarkEdge(Edge*) – Delete the mark from the edge.
Domain* getMark(Edge*) – Retrieve the value from the marked edge.
Domain& bottom(void) – Returns the least abstract value (BOTTOM)
The lub, assign, equals methods are easy to understand.
void update(Domain& out, const Domain& in, BasicBlock*) const – Compute the OUT value, from the IN value and the BasicBlock.
void blockInterpreted(BasicBlock*, const Domain& in, const Domain& out) const – Is called when a BasicBlock is interpreted by HalfAbsInt. Informations provided: The BasicBlock, and its IN & OUT values
void FixPointReached(BasicBlock*) const – Called by HalfAbsInt when the fixpoint is reached on a particular loop. The loop header is passed in the parameter.
const Domain& bottom(void) – returns the least element of the domain.
const Domain& entry(void) – returns the domain value at the entry of CFG.
An important precondition on the implementation of the fixpoint is that the Domain MUST support a complete partial order, we use "<=" to denote this order. The following applies on the different functions handling the domain:
bottom() must returns the least element of the domain, that is, whatever d in Domain, bottom() <= d.
update() must be monotonic, that is, if d1 <= d2, update(d'1, BB, d1) and update(d'2, BB, d2), d'1 <= d'2.
lub() must gives a greater element, that is, if d = d1 and join(d, d2) then d1 <= d and d2 <= d.
If these constraints are not ensured, the termination of the analysis performed by HalfAbsInst can not be asserted.
Inside a code processor
To be used inside an OTAWA code processor, the following features must be available (passed in the requirement list of the code processor):
otawa::LOOP_INFO_FEATURE
otawa::COLLECTED_CFG_FEATURE
Debugging the analysis
Causes of a failed abstract interpretation performed by HalfAbsInt may be hard to understand. To get details on what does the analyzer for debugging purpose, you may define the constant HAI_DEBUG before including the HalfAbsInt header file. When the analysis will be launched, the processing performed on basic block will be outputted with the values of the domain. To have a readable display of the domain, you have also to provide an overload of "<<" operator to perform the display:
#define HAI_DEBUG
#include <otawa/util/HalfAbsInt.h>
// definition of domain, fixpoint, etc
elm::io::Output operator<<(elm::io::Output& out, const TheDomain& d) {
                // display the domain to output
}
Constructor & Destructor Documentation
template<class FixPoint> otawa::dfa::hai::HalfAbsInt< FixPoint >::HalfAbsInt (FixPoint & _fp, WorkSpace & _fw) inline
References otawa::dfa::hai::HalfAbsInt< FixPoint >::callStack, otawa::dfa::hai::HalfAbsInt< FixPoint >::cfgStack, otawa::dfa::hai::HalfAbsInt< FixPoint >::fp, and otawa::dfa::hai::HalfAbsInt< FixPoint >::workList.
template<class FixPoint > otawa::dfa::hai::HalfAbsInt< FixPoint >::~HalfAbsInt (void) inline
References otawa::cfgio::bb(), otawa::Edge::CALL, otawa::dfa::hai::HalfAbsInt< FixPoint >::entry_cfg, otawa::dfa::hai::HalfAbsInt< FixPoint >::fp, otawa::dfa::hai::HalfAbsInt< FixPoint >::out, and otawa::dfa::hai::HalfAbsInt< FixPoint >::workList.
Member Function Documentation
template<class FixPoint > void otawa::dfa::hai::HalfAbsInt< FixPoint >::addSuccessors () private
References otawa::Edge::CALL, otawa::dfa::hai::HalfAbsInt< FixPoint >::current, otawa::dfa::hai::HalfAbsInt< FixPoint >::fp, otawa::dfa::hai::HAI_BYPASS_SOURCE, otawa::dfa::hai::HAI_DONT_ENTER, HAI_TRACE, otawa::dfa::hai::HalfAbsInt< FixPoint >::out, otawa::dfa::hai::HalfAbsInt< FixPoint >::tryAddToWorkList(), and otawa::Edge::VIRTUAL_CALL.
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing().
template<class FixPoint > typename FixPoint::Domain otawa::dfa::hai::HalfAbsInt< FixPoint >::backEdgeUnion (BasicBlock * bb) inline
Given a loop header, returns the union of the value of its back edges.
Parameters
bb The loop header.
Returns
The unionized value.
References otawa::Edge::CALL, otawa::Dominance::dominates(), otawa::dfa::hai::FIRST_ITER, otawa::dfa::hai::HalfAbsInt< FixPoint >::fp, and HAI_TRACE.
template<class FixPoint > Edge * otawa::dfa::hai::HalfAbsInt< FixPoint >::detectCalls (bool & enter_call, elm::genstruct::Vector< Edge * > & call_edges, BasicBlock * bb) private
References otawa::Edge::CALL, otawa::dfa::hai::HalfAbsInt< FixPoint >::fp, otawa::dfa::hai::HAI_DONT_ENTER, and otawa::dfa::hai::HalfAbsInt< FixPoint >::next_edge.
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::solve().
template<class FixPoint > typename FixPoint::Domain otawa::dfa::hai::HalfAbsInt< FixPoint >::entryEdgeUnion (BasicBlock * bb) inline
Given a loop header, returns the union of the value of is entry edges (the entry edges are the in-edges that are not back-edges.)
Parameters
bb The loop header
Returns
The unionized value.
References otawa::Edge::CALL, otawa::dfa::hai::CTX_LOOP, otawa::Dominance::dominates(), otawa::dfa::hai::HalfAbsInt< FixPoint >::fp, otawa::dfa::hai::HAI_BYPASS_TARGET, HAI_TRACE, and otawa::Edge::VIRTUAL_RETURN.
template<class FixPoint > typename FixPoint::FixPointState * otawa::dfa::hai::HalfAbsInt< FixPoint >::getFixPointState (BasicBlock * bb) inline
Get the FixPointState of a loop.
Parameters
bb The header of the loop which we want to get the state.
Returns
The requested FixPointState info.
References otawa::dfa::hai::HalfAbsInt< FixPoint >::FIXPOINT_STATE.
Referenced by otawa::dfa::hai::FirstUnrollingFixPoint< Listener >::getIter().
template<class FixPoint> void otawa::dfa::hai::HalfAbsInt< FixPoint >::inputProcessing (typename FixPoint::Domain & entdom) private
References otawa::Edge::CALL, otawa::dfa::hai::HalfAbsInt< FixPoint >::call_edges, otawa::dfa::hai::HalfAbsInt< FixPoint >::current, otawa::Dominance::dominates(), otawa::dfa::hai::FIRST_ITER, otawa::dfa::hai::FIXED, otawa::dfa::hai::HalfAbsInt< FixPoint >::fixpoint, otawa::dfa::hai::HalfAbsInt< FixPoint >::FIXPOINT_STATE, otawa::dfa::hai::HalfAbsInt< FixPoint >::fp, otawa::dfa::hai::HAI_BYPASS_TARGET, HAI_TRACE, otawa::dfa::hai::HalfAbsInt< FixPoint >::in, otawa::BasicBlock::isEntry(), otawa::LOOP_HEADER, otawa::dfa::hai::HalfAbsInt< FixPoint >::mainEntry, otawa::dfa::hai::HalfAbsInt< FixPoint >::next_edge, and otawa::Edge::VIRTUAL_RETURN.
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::solve().
template<class FixPoint > bool otawa::dfa::hai::HalfAbsInt< FixPoint >::isEdgeDone (Edge * edge) inline private
Tests if an edge verify the conditions needed to add its target BasicBlock.
Parameters
edge The edge to test
Returns
Returns false if the edge's target cannot be added to the worklist. True otherwise.
References otawa::Dominance::dominates(), otawa::dfa::hai::FIRST_ITER, otawa::dfa::hai::FIXED, otawa::dfa::hai::HalfAbsInt< FixPoint >::fp, otawa::LOOP_EXIT_EDGE, otawa::Edge::source(), and otawa::Edge::target().
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::tryAddToWorkList().
template<class FixPoint > void otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing (void) private
References otawa::dfa::hai::HalfAbsInt< FixPoint >::addSuccessors(), otawa::dfa::hai::HalfAbsInt< FixPoint >::call_edges, otawa::Edge::calledCFG(), otawa::dfa::hai::HalfAbsInt< FixPoint >::callStack, otawa::dfa::hai::HalfAbsInt< FixPoint >::cfgStack, otawa::dfa::hai::CTX_FUNC, otawa::dfa::hai::CTX_LOOP, otawa::dfa::hai::HalfAbsInt< FixPoint >::cur_cfg, otawa::dfa::hai::HalfAbsInt< FixPoint >::current, otawa::cfgio::edge(), otawa::dfa::hai::HalfAbsInt< FixPoint >::enter_call, otawa::CFG::entry(), otawa::EXIT_LIST, otawa::dfa::hai::HalfAbsInt< FixPoint >::fixpoint, otawa::dfa::hai::HalfAbsInt< FixPoint >::fp, HAI_TRACE, otawa::dfa::hai::HalfAbsInt< FixPoint >::in, otawa::BasicBlock::isExit(), otawa::CFG::label(), otawa::LOOP_HEADER, otawa::dfa::hai::HalfAbsInt< FixPoint >::next_edge, otawa::dfa::hai::HalfAbsInt< FixPoint >::out, otawa::Edge::source(), otawa::dfa::hai::HalfAbsInt< FixPoint >::tryAddToWorkList(), and otawa::dfa::hai::HalfAbsInt< FixPoint >::workList.
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::solve().
template<class FixPoint> int otawa::dfa::hai::HalfAbsInt< FixPoint >::solve (otawa::CFG * main_cfg = 0, typename FixPoint::Domain * entdom = 0, BasicBlock * start_bb = 0)
Do the abstract interpretation of the CFG.
Returns
The number of iterations of the algorithm.
References otawa::dfa::hai::HalfAbsInt< FixPoint >::call_edges, otawa::dfa::hai::HalfAbsInt< FixPoint >::callStack, otawa::dfa::hai::HalfAbsInt< FixPoint >::cur_cfg, otawa::dfa::hai::HalfAbsInt< FixPoint >::current, otawa::dfa::hai::HalfAbsInt< FixPoint >::detectCalls(), otawa::dfa::hai::HalfAbsInt< FixPoint >::enter_call, otawa::CFG::entry(), otawa::dfa::hai::HalfAbsInt< FixPoint >::entry_cfg, otawa::dfa::hai::HalfAbsInt< FixPoint >::fixpoint, otawa::dfa::hai::HalfAbsInt< FixPoint >::fp, HAI_TRACE, otawa::dfa::hai::HalfAbsInt< FixPoint >::in, otawa::dfa::hai::HalfAbsInt< FixPoint >::inputProcessing(), otawa::dfa::hai::HalfAbsInt< FixPoint >::mainEntry, otawa::dfa::hai::HalfAbsInt< FixPoint >::next_edge, otawa::dfa::hai::HalfAbsInt< FixPoint >::out, otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing(), and otawa::dfa::hai::HalfAbsInt< FixPoint >::workList.
Referenced by otawa::dcache::DirtyManager::t::print(), otawa::ACSMayBuilder::processLBlockSet(), otawa::EdgeACSBuilder::processLBlockSet(), otawa::ACSBuilder::processLBlockSet(), otawa::dcache::ACSMayBuilder::processLBlockSet(), otawa::dcache::ACSBuilder::processLBlockSet(), and otawa::branch::BranchBuilder::processWorkSpace().
template<class FixPoint > void otawa::dfa::hai::HalfAbsInt< FixPoint >::tryAddToWorkList (BasicBlock * bb) inline private
Try to add the BasicBlock to the worklist.
In order to be added, the BasicBlock's in-edges must verify some conditions. These conditions are verified by isEdgeDone()
Parameters
bb The BasicBlock to try to add.
References otawa::sem::add(), otawa::Edge::CALL, otawa::dfa::hai::FIRST_ITER, otawa::dfa::hai::HalfAbsInt< FixPoint >::fp, otawa::dfa::hai::HAI_BYPASS_TARGET, HAI_TRACE, otawa::dfa::hai::HalfAbsInt< FixPoint >::isEdgeDone(), otawa::LOOP_HEADER, otawa::BasicBlock::number(), otawa::Edge::VIRTUAL_RETURN, and otawa::dfa::hai::HalfAbsInt< FixPoint >::workList.
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::addSuccessors(), and otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing().
Member Data Documentation
template<class FixPoint> elm::genstruct::Vector<Edge*> otawa::dfa::hai::HalfAbsInt< FixPoint >::call_edges private
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::inputProcessing(), otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing(), and otawa::dfa::hai::HalfAbsInt< FixPoint >::solve().
template<class FixPoint> elm::genstruct::Vector<Edge*>* otawa::dfa::hai::HalfAbsInt< FixPoint >::callStack private
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::HalfAbsInt(), otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing(), and otawa::dfa::hai::HalfAbsInt< FixPoint >::solve().
template<class FixPoint> elm::genstruct::Vector<CFG*>* otawa::dfa::hai::HalfAbsInt< FixPoint >::cfgStack private
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::HalfAbsInt(), and otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing().
template<class FixPoint> CFG* otawa::dfa::hai::HalfAbsInt< FixPoint >::cur_cfg private
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing(), and otawa::dfa::hai::HalfAbsInt< FixPoint >::solve().
template<class FixPoint> BasicBlock* otawa::dfa::hai::HalfAbsInt< FixPoint >::current private
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::addSuccessors(), otawa::dfa::hai::HalfAbsInt< FixPoint >::inputProcessing(), otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing(), and otawa::dfa::hai::HalfAbsInt< FixPoint >::solve().
template<class FixPoint> bool otawa::dfa::hai::HalfAbsInt< FixPoint >::enter_call private
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing(), and otawa::dfa::hai::HalfAbsInt< FixPoint >::solve().
template<class FixPoint> CFG& otawa::dfa::hai::HalfAbsInt< FixPoint >::entry_cfg private
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::solve(), and otawa::dfa::hai::HalfAbsInt< FixPoint >::~HalfAbsInt().
template<class FixPoint> bool otawa::dfa::hai::HalfAbsInt< FixPoint >::fixpoint private
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::inputProcessing(), otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing(), and otawa::dfa::hai::HalfAbsInt< FixPoint >::solve().
template<class FixPoint> Identifier< typename FixPoint::FixPointState * > otawa::dfa::hai::HalfAbsInt< FixPoint >::FIXPOINT_STATE static private
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::getFixPointState(), and otawa::dfa::hai::HalfAbsInt< FixPoint >::inputProcessing().
template<class FixPoint> FixPoint& otawa::dfa::hai::HalfAbsInt< FixPoint >::fp private
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::addSuccessors(), otawa::dfa::hai::HalfAbsInt< FixPoint >::backEdgeUnion(), otawa::dfa::hai::HalfAbsInt< FixPoint >::detectCalls(), otawa::dfa::hai::HalfAbsInt< FixPoint >::entryEdgeUnion(), otawa::dfa::hai::HalfAbsInt< FixPoint >::HalfAbsInt(), otawa::dfa::hai::HalfAbsInt< FixPoint >::inputProcessing(), otawa::dfa::hai::HalfAbsInt< FixPoint >::isEdgeDone(), otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing(), otawa::dfa::hai::HalfAbsInt< FixPoint >::solve(), otawa::dfa::hai::HalfAbsInt< FixPoint >::tryAddToWorkList(), and otawa::dfa::hai::HalfAbsInt< FixPoint >::~HalfAbsInt().
template<class FixPoint> FixPoint::Domain otawa::dfa::hai::HalfAbsInt< FixPoint >::in private
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::inputProcessing(), otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing(), and otawa::dfa::hai::HalfAbsInt< FixPoint >::solve().
template<class FixPoint> bool otawa::dfa::hai::HalfAbsInt< FixPoint >::mainEntry private
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::inputProcessing(), and otawa::dfa::hai::HalfAbsInt< FixPoint >::solve().
template<class FixPoint> Edge* otawa::dfa::hai::HalfAbsInt< FixPoint >::next_edge private
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::detectCalls(), otawa::dfa::hai::HalfAbsInt< FixPoint >::inputProcessing(), otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing(), and otawa::dfa::hai::HalfAbsInt< FixPoint >::solve().
template<class FixPoint> FixPoint::Domain otawa::dfa::hai::HalfAbsInt< FixPoint >::out private
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::addSuccessors(), otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing(), otawa::dfa::hai::HalfAbsInt< FixPoint >::solve(), and otawa::dfa::hai::HalfAbsInt< FixPoint >::~HalfAbsInt().
template<class FixPoint> elm::genstruct::Vector<BasicBlock*>* otawa::dfa::hai::HalfAbsInt< FixPoint >::workList private
Referenced by otawa::dfa::hai::HalfAbsInt< FixPoint >::HalfAbsInt(), otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing(), otawa::dfa::hai::HalfAbsInt< FixPoint >::solve(), otawa::dfa::hai::HalfAbsInt< FixPoint >::tryAddToWorkList(), and otawa::dfa::hai::HalfAbsInt< FixPoint >::~HalfAbsInt().
template<class FixPoint> WorkSpace& otawa::dfa::hai::HalfAbsInt< FixPoint >::ws private
The documentation for this class was generated from the following files:
include/otawa/dfa/hai/HalfAbsInt.h
src/prog/dfa_hai_HalfAbsInt.cpp