Otawa: otawa::cat::CATDomain Class Reference
otawa::cat::CATDomain Class Reference
#include <otawa/cat/CATDFA.h>
Public Member Functions
CATDomain (int size)
void reset (void)
void join (CATDomain *d)
void meet (CATDomain *d)
bool equals (CATDomain *d)
bool isEmpty (void) const
Test if the bit set is empty.
bool isFull (void) const
Test if the bit set contains all existing items.
void fill (void)
Fill the bit set with all items.
void empty (void)
Remove all items from the bit set.
bool contains (int index) const
Test if the bit set contains an item.
void add (int index)
Add an item to the bit set.
void add (const BitSet &set)
Add the items of the given bit set to the current one.
void remove (int index)
Remove an item from the bit set.
void remove (const BitSet &set)
Remove the items contained in the given bit set from the current one.
bool equals (const BitSet &set) const
Test if two bit sets are equals.
bool includes (const BitSet &set) const
Test if the current bit set contains the given one.
bool includesStrictly (const BitSet &set) const
Test if the current bit set contains strictly the given one, that is, both bit sets are equals.
void complement (void)
Complement the current bit set.
int size (void) const
void mask (const BitSet &set)
Keep only in this set the items also containted in the given one (performs intersection operation).
int count (void) const
BitSet doComp (void) const
Compute a bit set complement of the current one.
BitSet doUnion (const BitSet &set) const
Build a new bit set as union between the current and the given one.
BitSet doInter (const BitSet &set) const
Build a new bit set as intersection between the current and the given one.
BitSet doDiff (const BitSet &set) const
Build a new bit set as difference between the current and the given one.
BitSet & operator+= (int index)
Same as add(int).
BitSet & operator+= (const BitSet &set)
Same as add(const BitSet&).
BitSet & operator-= (int index)
Same as remove(int).
BitSet & operator-= (const BitSet &set)
Same as remove(const BitSet&).
BitSet operator+ (const BitSet &set)
Same as doUnion().
BitSet operator- (const BitSet &set)
Same as doDiff().
BitSet & operator|= (const BitSet &set)
Same as add(const BitSet&).
BitSet & operator&= (const BitSet &set)
Same as remove(const BitSet&).
BitSet operator| (const BitSet &set)
Same as doUnion().
BitSet operator& (const BitSet &set)
Same as doInter().
bool operator== (const BitSet &set) const
Same as equals().
bool operator!= (const BitSet &set) const
Same as !equals().
bool operator>= (const BitSet &set) const
Same as includes().
bool operator<= (const BitSet &set) const
Same as !includesStrictly().
bool operator> (const BitSet &set) const
Same as includesStrictly().
bool operator< (const BitSet &set) const
Same as !includes().
Static Public Attributes
static int __used_size = 0
static int __max_size = 0
static int __total_size = 0
Constructor & Destructor Documentation
otawa::cat::CATDomain::CATDomain (int size) inline
Referenced by otawa::cat::CATProblem::empty().
Member Function Documentation
void otawa::dfa::BitSet::add (int index) inline inherited
Add an item to the bit set.
Parameters
index Index identifying the added item.
References OTAWA_BITSET_ALLOC, and OTAWA_BITSET_FREE.
Referenced by otawa::ccg::Problem::gen(), otawa::cat::CATProblem::gen(), otawa::ccg::Domain::join(), join(), otawa::bpred::BPredProcessor::lshift_BitSet(), otawa::bpred::BPredProcessor::setMitraInit(), and otawa::dcache::DirtyManager::update().
void otawa::dfa::BitSet::add (const BitSet & set) inline inherited
Add the items of the given bit set to the current one.
Parameters
set Set to add.
References OTAWA_BITSET_ALLOC, and OTAWA_BITSET_FREE.
void otawa::dfa::BitSet::complement (void) inline inherited
Complement the current bit set.
Referenced by otawa::cat::CATProblem::preserve().
bool otawa::dfa::BitSet::contains (int index) const inline inherited
Test if the bit set contains an item.
Parameters
index Index identifying the looked item.
Returns
True if the item is in the bit set, false else.
Referenced by otawa::bpred::BPredProcessor::BitSet_to_String(), otawa::bpred::BPredProcessor::lshift_BitSet(), otawa::dcache::DirtyManager::mayBeDirty(), otawa::dcache::DirtyManager::mustBeDirty(), otawa::dfa::operator<<(), otawa::ccg::Builder::processLBlockSet(), otawa::LoopReductor::reduce(), otawa::cat::CATBuilder::setCATEGORISATION(), and otawa::cat::CATBuilder::worst().
int otawa::dfa::BitSet::count (void) const inline inherited
Referenced by otawa::ccg::Problem::gen(), otawa::cat::CATProblem::gen(), otawa::LoopReductor::reduce(), and otawa::cat::CATBuilder::worst().
BitSet otawa::dfa::BitSet::doComp (void) const inline inherited
Compute a bit set complement of the current one.
Returns
Complemented bit set.
BitSet otawa::dfa::BitSet::doDiff (const BitSet & set) const inline inherited
Build a new bit set as difference between the current and the given one.
Parameters
set Set to do difference with.
Returns
Difference of both sets.
BitSet otawa::dfa::BitSet::doInter (const BitSet & set) const inline inherited
Build a new bit set as intersection between the current and the given one.
Parameters
set Set to do intersection with.
Returns
Intersection of both sets.
BitSet otawa::dfa::BitSet::doUnion (const BitSet & set) const inline inherited
Build a new bit set as union between the current and the given one.
Parameters
set Set to do union with.
Returns
Union of both sets.
void otawa::dfa::BitSet::empty (void) inline inherited
Remove all items from the bit set.
Referenced by otawa::dcache::DirtyManager::DirtyManager(), otawa::PSTBuilder::getVCFG(), otawa::bpred::BPredProcessor::lshift_BitSet(), otawa::ccg::Domain::reset(), reset(), and otawa::dcache::DirtyManager::update().
bool otawa::cat::CATDomain::equals (CATDomain * d) inline
bool otawa::dfa::BitSet::equals (const BitSet & set) const inline inherited
Test if two bit sets are equals.
Parameters
set Bit set to compare the current one with.
Returns
True if they are equal, false else.
Referenced by otawa::ccg::Domain::equals(), and otawa::dcache::DirtyManager::equals().
void otawa::dfa::BitSet::fill (void) inline inherited
Fill the bit set with all items.
Referenced by otawa::dcache::DirtyManager::DirtyManager(), otawa::ccg::Problem::preserve(), otawa::cat::CATProblem::preserve(), and otawa::dcache::DirtyManager::update().
bool otawa::dfa::BitSet::includes (const BitSet & set) const inline inherited
Test if the current bit set contains the given one.
Parameters
set Set to test for inclusion.
Returns
True if the current bit set contains the given one.
bool otawa::dfa::BitSet::includesStrictly (const BitSet & set) const inline inherited
Test if the current bit set contains strictly the given one, that is, both bit sets are equals.
Parameters
set Set to test for inclusion.
Returns
True if the current bit set contains the given one.
bool otawa::dfa::BitSet::isEmpty (void) const inline inherited
Test if the bit set is empty.
Returns
True if it is empty, false else.
bool otawa::dfa::BitSet::isFull (void) const inline inherited
Test if the bit set contains all existing items.
Returns
True if it is full, false else.
void otawa::cat::CATDomain::join (CATDomain * d) inline
References otawa::dfa::BitSet::add().
void otawa::dfa::BitSet::mask (const BitSet & set) inline inherited
Keep only in this set the items also containted in the given one (performs intersection operation).
Parameters
set Set to intersect with.
References OTAWA_BITSET_ALLOC, and OTAWA_BITSET_FREE.
Referenced by otawa::ccg::Domain::meet(), meet(), and otawa::cat::CATBuilder::worst().
void otawa::cat::CATDomain::meet (CATDomain * d) inline
References otawa::dfa::BitSet::mask().
bool otawa::dfa::BitSet::operator!= (const BitSet & set) const inline inherited
Same as !equals().
BitSet otawa::dfa::BitSet::operator& (const BitSet & set) inline inherited
Same as doInter().
BitSet & otawa::dfa::BitSet::operator&= (const BitSet & set) inline inherited
Same as remove(const BitSet&).
BitSet otawa::dfa::BitSet::operator+ (const BitSet & set) inline inherited
Same as doUnion().
BitSet & otawa::dfa::BitSet::operator+= (int index) inline inherited
Same as add(int).
References otawa::sem::add().
BitSet & otawa::dfa::BitSet::operator+= (const BitSet & set) inline inherited
Same as add(const BitSet&).
References otawa::sem::add().
BitSet otawa::dfa::BitSet::operator- (const BitSet & set) inline inherited
Same as doDiff().
BitSet & otawa::dfa::BitSet::operator-= (int index) inline inherited
Same as remove(int).
BitSet & otawa::dfa::BitSet::operator-= (const BitSet & set) inline inherited
Same as remove(const BitSet&).
bool otawa::dfa::BitSet::operator< (const BitSet & set) const inline inherited
Same as !includes().
bool otawa::dfa::BitSet::operator<= (const BitSet & set) const inline inherited
Same as !includesStrictly().
bool otawa::dfa::BitSet::operator== (const BitSet & set) const inline inherited
Same as equals().
bool otawa::dfa::BitSet::operator> (const BitSet & set) const inline inherited
Same as includesStrictly().
bool otawa::dfa::BitSet::operator>= (const BitSet & set) const inline inherited
Same as includes().
BitSet otawa::dfa::BitSet::operator| (const BitSet & set) inline inherited
Same as doUnion().
BitSet & otawa::dfa::BitSet::operator|= (const BitSet & set) inline inherited
Same as add(const BitSet&).
References otawa::sem::add().
void otawa::dfa::BitSet::remove (int index) inline inherited
Remove an item from the bit set.
Parameters
index Index identifying the removed item.
References OTAWA_BITSET_ALLOC, and OTAWA_BITSET_FREE.
Referenced by otawa::cat::CATProblem::preserve(), otawa::LoopReductor::reduce(), otawa::dcache::DirtyManager::update(), and otawa::cat::CATBuilder::worst().
void otawa::dfa::BitSet::remove (const BitSet & set) inline inherited
Remove the items contained in the given bit set from the current one.
Parameters
set Set containing items to remove.
References OTAWA_BITSET_ALLOC, and OTAWA_BITSET_FREE.
void otawa::cat::CATDomain::reset (void) inline
References otawa::dfa::BitSet::empty().
Referenced by otawa::cat::CATProblem::empty().
int otawa::dfa::BitSet::size (void) const inline inherited
Referenced by otawa::bpred::BPredProcessor::BitSet_to_String(), otawa::ccg::Problem::empty(), otawa::bpred::BPredProcessor::lshift_BitSet(), otawa::dfa::operator<<(), and otawa::ccg::Problem::Problem().
Member Data Documentation
int otawa::dfa::BitSet::__max_size = 0 static inherited
int otawa::dfa::BitSet::__total_size = 0 static inherited
int otawa::dfa::BitSet::__used_size = 0 static inherited
The documentation for this class was generated from the following file:
include/otawa/cat/CATDFA.h