Otawa: otawa::dcache::MUSTPERS Class Reference
otawa::dcache::MUSTPERS Class Reference
#include <otawa/dcache/MUSTPERS.h>
Classes
class Domain
ACS of the MUSTPERS problem.
Public Member Functions
MUSTPERS (const BlockCollection *_lbset, WorkSpace *_fw, const hard::Cache *_cache)
void setMust (Domain &d, const ACS &acs) const
void emptyPers (Domain &d) const
void setPers (Domain &d, const ACS &acs, const acs_stack_t &s)
const Domain & bottom (void) const
const Domain & entry (void) const
void lub (Domain &a, const Domain &b) const
void assign (Domain &a, const Domain &b) const
bool equals (const Domain &a, const Domain &b) const
void print (elm::io::Output &output, const Domain &d) const
Print the MUSTPERS ACS.
void update (Domain &out, const Domain &in, BasicBlock *bb)
void update (Domain &s, const BlockAccess &access)
Update according to the given access.
void ageAll (Domain &d) const
void inject (Domain &d, const int id) const
void enterContext (Domain &dom, BasicBlock *header, util::hai_context_t ctx)
void leaveContext (Domain &dom, BasicBlock *header, util::hai_context_t ctx)
Private Attributes
Domain bot
Domain ent
int set
MUSTProblem mustProb
PERSProblem persProb
Constructor & Destructor Documentation
otawa::dcache::MUSTPERS::MUSTPERS (const BlockCollection * _lbset, WorkSpace * _fw, const hard::Cache * _cache)
References otawa::dcache::MUSTProblem::assign(), otawa::dcache::PERSProblem::assign(), bot, otawa::dcache::MUSTProblem::bottom(), otawa::dcache::PERSProblem::bottom(), ent, otawa::dcache::MUSTProblem::entry(), otawa::dcache::PERSProblem::entry(), otawa::dcache::MUSTPERS::Domain::must, mustProb, otawa::dcache::MUSTPERS::Domain::pers, and persProb.
Member Function Documentation
void otawa::dcache::MUSTPERS::ageAll (Domain & d) const inline
References otawa::dcache::MUSTProblem::Domain::ageAll(), otawa::dcache::PERSProblem::Domain::ageAll(), otawa::dcache::MUSTPERS::Domain::must, and otawa::dcache::MUSTPERS::Domain::pers.
Referenced by otawa::dcache::CATBuilder::processLBlockSet(), and update().
void otawa::dcache::MUSTPERS::assign (Domain & a, const Domain & b) const inline
References otawa::dcache::MUSTProblem::assign(), otawa::dcache::PERSProblem::assign(), mustProb, and persProb.
Referenced by update().
const MUSTPERS::Domain & otawa::dcache::MUSTPERS::bottom (void) const
References bot.
Referenced by otawa::dcache::CATBuilder::processLBlockSet(), and setPers().
void otawa::dcache::MUSTPERS::emptyPers (Domain & d) const inline
References otawa::dcache::PERSProblem::Domain::empty(), and otawa::dcache::MUSTPERS::Domain::pers.
Referenced by otawa::dcache::CATBuilder::processLBlockSet().
void otawa::dcache::MUSTPERS::enterContext (Domain & dom, BasicBlock * header, util::hai_context_t ctx) inline
References otawa::dcache::MUSTProblem::enterContext(), otawa::dcache::PERSProblem::enterContext(), otawa::dcache::MUSTPERS::Domain::must, mustProb, otawa::dcache::MUSTPERS::Domain::pers, and persProb.
const MUSTPERS::Domain & otawa::dcache::MUSTPERS::entry (void) const
References ent.
Referenced by setPers().
bool otawa::dcache::MUSTPERS::equals (const Domain & a, const Domain & b) const inline
References otawa::cfgio::bb(), otawa::dcache::MUSTProblem::equals(), otawa::dcache::PERSProblem::equals(), mustProb, persProb, print(), and update().
Referenced by otawa::dcache::PERSProblem::Domain::equals().
void otawa::dcache::MUSTPERS::inject (Domain & d, const int id) const inline
References otawa::dcache::MUSTProblem::Domain::inject(), otawa::dcache::PERSProblem::Domain::inject(), otawa::dcache::MUSTPERS::Domain::must, and otawa::dcache::MUSTPERS::Domain::pers.
Referenced by otawa::dcache::PERSProblem::Domain::inject(), otawa::dcache::CATBuilder::processLBlockSet(), and update().
void otawa::dcache::MUSTPERS::leaveContext (Domain & dom, BasicBlock * header, util::hai_context_t ctx) inline
References otawa::dcache::MUSTProblem::leaveContext(), otawa::dcache::PERSProblem::leaveContext(), otawa::dcache::MUSTPERS::Domain::must, mustProb, otawa::dcache::MUSTPERS::Domain::pers, and persProb.
void otawa::dcache::MUSTPERS::lub (Domain & a, const Domain & b) const inline
References otawa::dcache::MUSTProblem::lub(), otawa::dcache::PERSProblem::lub(), otawa::dcache::MUSTPERS::Domain::must, mustProb, otawa::dcache::MUSTPERS::Domain::pers, and persProb.
Referenced by otawa::dcache::PERSProblem::Domain::lub().
void otawa::dcache::MUSTPERS::print (elm::io::Output & output, const Domain & d) const
Print the MUSTPERS ACS.
Parameters
output Stream to output to.
References otawa::dcache::MUSTPERS::Domain::must, otawa::dcache::MUSTPERS::Domain::pers, otawa::dcache::ACS::print(), and otawa::dcache::PERSProblem::Domain::print().
Referenced by equals().
void otawa::dcache::MUSTPERS::setMust (Domain & d, const ACS & acs) const inline
References otawa::dcache::MUSTProblem::assign(), otawa::dcache::MUSTPERS::Domain::must, and mustProb.
Referenced by otawa::dcache::CATBuilder::processLBlockSet().
void otawa::dcache::MUSTPERS::setPers (Domain & d, const ACS & acs, const acs_stack_t & s) inline
References bottom(), entry(), otawa::dcache::MUSTPERS::Domain::pers, and otawa::dcache::PERSProblem::Domain::set().
Referenced by otawa::dcache::CATBuilder::processLBlockSet().
void otawa::dcache::MUSTPERS::update (Domain & out, const Domain & in, BasicBlock * bb)
References assign(), and otawa::dcache::DATA_BLOCKS.
Referenced by equals().
void otawa::dcache::MUSTPERS::update (Domain & s, const BlockAccess & access)
Update according to the given access.
Parameters
s Domain to udpate.
access Access to apply.
References otawa::dcache::BlockAccess::action(), ageAll(), otawa::dcache::BlockAccess::ANY, otawa::dcache::BlockAccess::BLOCK, otawa::dcache::BlockAccess::block(), otawa::dcache::BlockAccess::first, otawa::dcache::Block::index(), inject(), otawa::dcache::BlockAccess::kind(), otawa::dcache::BlockAccess::last, otawa::dcache::BlockAccess::LOAD, otawa::dcache::MUSTPERS::Domain::must, MUST_DEBUG, mustProb, otawa::dcache::MUSTPERS::Domain::pers, persProb, otawa::dcache::MUSTProblem::purge(), otawa::dcache::PERSProblem::purge(), otawa::dcache::BlockAccess::PURGE, otawa::dcache::BlockAccess::RANGE, otawa::dcache::Block::set(), and otawa::dcache::BlockAccess::STORE.
Member Data Documentation
Domain otawa::dcache::MUSTPERS::bot private
Referenced by bottom(), and MUSTPERS().
Domain otawa::dcache::MUSTPERS::ent private
Referenced by entry(), and MUSTPERS().
MUSTProblem otawa::dcache::MUSTPERS::mustProb private
Referenced by assign(), enterContext(), equals(), leaveContext(), lub(), MUSTPERS(), setMust(), and update().
PERSProblem otawa::dcache::MUSTPERS::persProb private
Referenced by assign(), enterContext(), equals(), leaveContext(), lub(), MUSTPERS(), and update().
int otawa::dcache::MUSTPERS::set private
The documentation for this class was generated from the following files:
include/otawa/dcache/MUSTPERS.h
src/dcache/dcache_ACSBuilder.cpp