Otawa: otawa::dcache::PERSProblem Class Reference
otawa::dcache::PERSProblem Class Reference
Data Cache
Problem for computing the PERS ACS of L-blocks.
#include <otawa/dcache/PERSProblem.h>
Classes
class Domain
class Item
ACS for the multi-level data cache persistence analysis.
Public Member Functions
PERSProblem (const int _size, const BlockCollection *_lbset, WorkSpace *_fw, const hard::Cache *_cache, const int _A)
~PERSProblem (void)
const Domain & bottom (void) const
const Domain & entry (void) const
void lub (Domain &a, const Domain &b) const
void assign (Domain &a, const Domain &b) const
bool equals (const Domain &a, const Domain &b) const
void update (Domain &out, const Domain &in, BasicBlock *bb)
void update (Domain &s, const BlockAccess &access)
void purge (Item &item, const BlockAccess &acc)
Apply the given purge action to the given item.
void purge (Domain &domain, const BlockAccess &acc)
Apply the given purge action to the given domain.
void enterContext (Domain &dom, BasicBlock *header, util::hai_context_t ctx)
void leaveContext (Domain &dom, BasicBlock *header, util::hai_context_t ctx)
Public Attributes
Domain callstate
Private Attributes
const BlockCollection * lbset
CFG * cfg
WorkSpace * fw
const hard::Cache * cache
Domain bot
Domain ent
const int line
Detailed Description
Problem for computing the PERS ACS of L-blocks.
Problem for the data cache persistence analysis.
This implements Ferdinand's Persistence analysis.
Constructor & Destructor Documentation
otawa::dcache::PERSProblem::PERSProblem (const int _size, const BlockCollection * _lbset, WorkSpace * _fw, const hard::Cache * _cache, const int _A)
References bot, otawa::dcache::PERSProblem::Domain::empty(), ent, otawa::dcache::PERSProblem::Domain::enterContext(), and otawa::dcache::PERSProblem::Domain::setToBottom().
otawa::dcache::PERSProblem::~PERSProblem (void)
Member Function Documentation
void otawa::dcache::PERSProblem::assign (Domain & a, const Domain & b) const inline
Referenced by otawa::dcache::MUSTPERS::assign(), and otawa::dcache::MUSTPERS::MUSTPERS().
const PERSProblem::Domain & otawa::dcache::PERSProblem::bottom (void) const
References bot.
Referenced by otawa::dcache::MUSTPERS::MUSTPERS().
void otawa::dcache::PERSProblem::enterContext (Domain & dom, BasicBlock * header, util::hai_context_t ctx) inline
References otawa::dfa::hai::CTX_LOOP, and otawa::dcache::PERSProblem::Domain::enterContext().
Referenced by otawa::dcache::MUSTPERS::enterContext(), and otawa::dcache::PERSProblem::Domain::refresh().
const PERSProblem::Domain & otawa::dcache::PERSProblem::entry (void) const
References ent.
Referenced by otawa::dcache::MUSTPERS::MUSTPERS().
bool otawa::dcache::PERSProblem::equals (const Domain & a, const Domain & b) const inline
References otawa::cfgio::bb(), otawa::dcache::PERSProblem::Domain::equals(), purge(), and update().
Referenced by otawa::dcache::MUSTPERS::equals().
void otawa::dcache::PERSProblem::leaveContext (Domain & dom, BasicBlock * header, util::hai_context_t ctx) inline
References otawa::dfa::hai::CTX_LOOP, and otawa::dcache::PERSProblem::Domain::leaveContext().
Referenced by otawa::dcache::MUSTPERS::leaveContext(), and otawa::dcache::PERSProblem::Domain::refresh().
void otawa::dcache::PERSProblem::lub (Domain & a, const Domain & b) const inline
References otawa::dcache::PERSProblem::Domain::lub().
Referenced by otawa::dcache::MUSTPERS::lub().
void otawa::dcache::PERSProblem::purge (Item & item, const BlockAccess & acc)
Apply the given purge action to the given item.
Parameters
item Item to work on.
acc Purge action to perform.
References otawa::dcache::BlockAccess::action(), otawa::dcache::BlockAccess::ANY, otawa::dcache::BlockAccess::BLOCK, otawa::dcache::BlockAccess::block(), otawa::dcache::ACS::getA(), otawa::dcache::ACS::getSize(), otawa::dcache::BlockAccess::inRange(), otawa::dcache::BlockAccess::kind(), line, otawa::dcache::BlockAccess::PURGE, otawa::dcache::BlockAccess::RANGE, and otawa::dcache::Block::set().
Referenced by equals(), purge(), and otawa::dcache::MUSTPERS::update().
void otawa::dcache::PERSProblem::purge (Domain & domain, const BlockAccess & acc)
Apply the given purge action to the given domain.
Parameters
domain Domain to work on.
acc Purge action to perform.
References otawa::dcache::PERSProblem::Domain::getItem(), otawa::dcache::PERSProblem::Domain::getWhole(), otawa::dcache::PERSProblem::Domain::length(), and purge().
void otawa::dcache::PERSProblem::update (Domain & out, const Domain & in, BasicBlock * bb)
Referenced by equals().
void otawa::dcache::PERSProblem::update (Domain & s, const BlockAccess & access)
Member Data Documentation
Domain otawa::dcache::PERSProblem::bot private
Referenced by bottom(), and PERSProblem().
const hard::Cache* otawa::dcache::PERSProblem::cache private
Domain otawa::dcache::PERSProblem::callstate
CFG* otawa::dcache::PERSProblem::cfg private
Domain otawa::dcache::PERSProblem::ent private
Referenced by entry(), and PERSProblem().
WorkSpace* otawa::dcache::PERSProblem::fw private
const BlockCollection* otawa::dcache::PERSProblem::lbset private
const int otawa::dcache::PERSProblem::line private
Referenced by purge().
The documentation for this class was generated from the following files:
include/otawa/dcache/PERSProblem.h
src/dcache/dcache_ACSBuilder.cpp