Otawa: otawa::display::GraphVizEdge Class Reference
otawa::display::GraphVizEdge Class Reference
#include </home/yashas/otawa/linux-x86_64/otawa-core-build/otawa/src/odisplay/graphviz.h>
Public Member Functions
GraphVizEdge (GraphVizNode *src, GraphVizNode *dest)
Creates a new edge with the first node given as source node, and the second node as target node.
virtual GraphVizNode * source ()
This function returns the source of this edge.
virtual GraphVizNode * target ()
This function returns the target of this edge.
virtual String attributes ()
calls attributes(const PropList& style) with the PropList containing the style of the item.
virtual void setProps (const PropList &props)
Set the object properties that have to be printed.
Property * getProp (const AbstractIdentifier *id) const
Find a property by its identifier.
void setProp (Property *prop)
Set the property in the property list removing any double.
void setProp (const AbstractIdentifier *id)
void removeProp (const AbstractIdentifier *id)
Remove a property matching the given identifier.
void removeProp (const AbstractIdentifier &id)
Property * extractProp (const AbstractIdentifier *id)
Remove a property matching the given identifier and return it.
Property * extractProp (const AbstractIdentifier &id)
Remove a property matching the given identifier and return it.
void addProp (Property *prop)
Add property to the list without checking of duplication.
void removeAllProp (const AbstractIdentifier *id)
Remove all the properties matching the given identifier.
bool hasProp (const AbstractIdentifier &id) const
Test if the property list contains a property matching the given identifier.
void clearProps (void)
Remove all properties from the list.
void addProps (const PropList &props)
Add all properties from the given property list, in a reverse order.
void print (elm::io::Output &out) const
Display the current property list.
Static Public Attributes
static const PropList EMPTY
This is an empty proplist for convenience.
Protected Member Functions
virtual void printOthersAttributes (elm::io::Output &out)
Prints attributes after all the style PropList have been iterated.
virtual bool printAttribute (elm::io::Output &out, const PropList::Iter &prop)
Process the Property given by the iterator pointing to it.
virtual String getPropertiesString ()
Makes a string containing the values of all properties in _props separated by newlines.
virtual String attributes (const PropList &props)
Prints all attributes (styles) in a string, between brackets.
Protected Attributes
bool _hasLabel
true if the label have been set, even if it is an empty string
String _label
label of the edge
GraphVizNode * _src
source of the edge
GraphVizNode * _dest
target of the edge
PropList _props
Properties of the attached object.
elm::genstruct::HashTable< const AbstractIdentifier *, int > _include
List of properties to print.
elm::genstruct::HashTable< const AbstractIdentifier *, int > _exclude
List of properties to hide.
bool _defaultInclude
true if the default is to include all properties
Detailed Description
Author
G. Cavaignac
This class represents the links between the graphviz nodes in the graphviz graph
Constructor & Destructor Documentation
otawa::display::GraphVizEdge::GraphVizEdge (GraphVizNode * src, GraphVizNode * dest)
Creates a new edge with the first node given as source node, and the second node as target node.
Parameters
src source node
dest target node
Member Function Documentation
void otawa::PropList::addProp (Property * prop) inherited
Add property to the list without checking of duplication.
Parameters
prop Property to add.
References otawa::Property::_next.
Referenced by otawa::Identifier< T >::add(), otawa::ast::ASTInfo::ASTInfo(), otawa::Identifier< otawa::arm::Info * >::copy(), otawa::AbstractIdentifier::initProps(), otawa::ContextualProperty::make(), otawa::script::Script::makeConfig(), otawa::ccg::Builder::processLBlockSet(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), and otawa::ContextualProperty::refProps().
void otawa::PropList::addProps (const PropList & props) inherited
Add all properties from the given property list, in a reverse order.
Parameters
props Property list to clone.
References otawa::Property::copy(), otawa::PropList::head, and otawa::Property::next().
Referenced by otawa::display::CFGDrawer::CFGDrawer(), otawa::display::GraphVizGraph::GraphVizGraph(), otawa::ParamFeature::instantiate(), otawa::Manager::loadXML(), otawa::display::GraphVizGraph::newEdge(), otawa::display::GraphVizGraph::newNode(), otawa::Process::Process(), otawa::display::GraphVizItem::setProps(), otawa::VirtualBasicBlock::VirtualBasicBlock(), and otawa::VirtualCFG::VirtualCFG().
String otawa::display::GraphVizItem::attributes (const PropList & style) protected virtual inherited
Prints all attributes (styles) in a string, between brackets.
First iterates on the style PropList, calling printAttribute() for each property, and then, calls printOthersAttributes() to finish. This functions escapes all the newlines that have been appened in the functions printAttribute() and printOthersAttributes()
Parameters
style styles to be printed
Returns
String containing the attributes. For example: [color="red"]
References otawa::PropList::Iter::ended(), otawa::display::GraphVizItem::printAttribute(), otawa::display::GraphVizItem::printOthersAttributes(), and otawa::display::quoteNewlines().
String otawa::display::GraphVizEdge::attributes (void) virtual
calls attributes(const PropList& style) with the PropList containing the style of the item.
Generally, the proplist is the object itself, because it inherits from PropList
Implements otawa::display::GraphVizItem.
References otawa::display::GraphVizItem::attributes().
Referenced by otawa::display::GraphVizGraph::printGraphData().
void otawa::PropList::clearProps (void) inherited
Remove all properties from the list.
References otawa::Property::next().
Referenced by otawa::PSTBuilder::getVCFG(), otawa::display::GraphVizItem::setProps(), and otawa::WorkSpace::~WorkSpace().
Property * otawa::PropList::extractProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::script::Script::makeConfig().
Property * otawa::PropList::extractProp (const AbstractIdentifier & id) inline inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::PropList::extractProp().
Referenced by otawa::PropList::extractProp().
Property * otawa::PropList::getProp (const AbstractIdentifier * id) const inherited
Find a property by its identifier.
Parameters
id Identifier of the property to find.
Returns
Found property or null.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::Identifier< otawa::arm::Info * >::exists(), otawa::ContextualProperty::exists(), otawa::ContextualProperty::find(), otawa::Identifier< T >::get(), otawa::ContextualProperty::make(), otawa::ParamFeature::matches(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::print(), otawa::ContextualProperty::print(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), otawa::ContextualProperty::refProps(), otawa::Identifier< T >::set(), otawa::Identifier< T >::use(), and otawa::Identifier< T >::value().
String otawa::display::GraphVizItem::getPropertiesString () protected virtual inherited
Makes a string containing the values of all properties in _props separated by newlines.
Returns
string containing properties values
References otawa::display::GraphVizItem::_defaultInclude, otawa::display::GraphVizItem::_exclude, otawa::display::GraphVizItem::_include, otawa::display::GraphVizItem::_props, otawa::PropList::Iter::ended(), and otawa::AbstractIdentifier::print().
Referenced by otawa::display::GraphVizNode::printOthersAttributes(), and printOthersAttributes().
bool otawa::PropList::hasProp (const AbstractIdentifier & id) const inline inherited
Test if the property list contains a property matching the given identifier.
Parameters
id Property identifier to look for.
Returns
True if the list contains the matching property, false else.
References otawa::p::print().
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::Monitor::configure(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::exists(), and otawa::Manager::setVerbosity().
void otawa::PropList::print (elm::io::Output & out) const inherited
Display the current property list.
Parameters
out Output to use.
Referenced by otawa::Edge::kindName(), otawa::operator<<(), and otawa::ContextualProperty::print().
bool otawa::display::GraphVizEdge::printAttribute (elm::io::Output & out, const PropList::Iter & prop) protected virtual
Process the Property given by the iterator pointing to it.
Prints the value to the given output, or store the property for example (the property can be printed furthermore by printOthersAttributes())
Parameters
out output where to print when something have to be printed iterator on properties. Used to compare the identifier and to get the property value
Returns
true if something have been written on the output, false else
Reimplemented from otawa::display::GraphVizGraphElement.
References _hasLabel, _label, otawa::Identifier< T >::get(), otawa::display::LABEL, otawa::display::GraphVizGraphElement::printAttribute(), and otawa::display::WEIGHT.
void otawa::display::GraphVizEdge::printOthersAttributes (elm::io::Output & out) protected virtual
Prints attributes after all the style PropList have been iterated.
One can append endlines to the output
Parameters
out output where to print others attributes
Reimplemented from otawa::display::GraphVizItem.
References _hasLabel, _label, otawa::display::GraphVizItem::getPropertiesString(), and otawa::display::quoteSpecials().
void otawa::PropList::removeAllProp (const AbstractIdentifier * id) inherited
Remove all the properties matching the given identifier.
Parameters
id Identifier of properties to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::LoopUnroller::unroll().
void otawa::PropList::removeProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier.
Parameters
id Identifier of the property to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::PSTBuilder::buildTree(), otawa::BBRemover< T >::clean(), otawa::CFGBuilder::cleanup(), otawa::display::CFGOutput::processCFG(), otawa::SubCFGBuilder::processWorkSpace(), otawa::Identifier< otawa::arm::Info * >::remove(), and otawa::ContextualPath::Ref< T >::remove().
void otawa::PropList::removeProp (const AbstractIdentifier & id) inline inherited
References otawa::PropList::removeProp().
Referenced by otawa::PropList::removeProp().
void otawa::PropList::setProp (Property * prop) inherited
Set the property in the property list removing any double.
Parameters
prop Property to set.
References otawa::Property::_next, otawa::Property::id(), and otawa::Property::next().
void otawa::PropList::setProp (const AbstractIdentifier * id) inline inherited
References otawa::PropList::setProp().
Referenced by otawa::PropList::setProp().
void otawa::display::GraphVizEdge::setProps (const PropList & props) virtual
Set the object properties that have to be printed.
Parameters
props Set the properties to print.
Implements otawa::display::Item.
References otawa::display::GraphVizItem::setProps().
Referenced by otawa::display::GraphVizGraph::newEdge().
otawa::display::GraphVizEdge::source (void) inline virtual
This function returns the source of this edge.
Returns
source of this edge
Referenced by otawa::display::GraphVizGraph::printGraphData().
otawa::display::GraphVizEdge::target (void) inline virtual
This function returns the target of this edge.
Returns
target of this edge
Referenced by otawa::display::GraphVizGraph::printGraphData().
Member Data Documentation
bool otawa::display::GraphVizItem::_defaultInclude protected inherited
true if the default is to include all properties
Referenced by otawa::display::GraphVizItem::getPropertiesString(), and otawa::display::GraphVizItem::printAttribute().
GraphVizNode* otawa::display::GraphVizEdge::_dest protected
target of the edge
elm::genstruct::HashTable<const AbstractIdentifier*, int> otawa::display::GraphVizItem::_exclude protected inherited
List of properties to hide.
If the key exists, exclude the property
Referenced by otawa::display::GraphVizItem::getPropertiesString(), and otawa::display::GraphVizItem::printAttribute().
bool otawa::display::GraphVizEdge::_hasLabel protected
true if the label have been set, even if it is an empty string
Referenced by printAttribute(), and printOthersAttributes().
elm::genstruct::HashTable<const AbstractIdentifier*, int> otawa::display::GraphVizItem::_include protected inherited
List of properties to print.
If the key exists, include the property
Referenced by otawa::display::GraphVizItem::getPropertiesString(), and otawa::display::GraphVizItem::printAttribute().
String otawa::display::GraphVizEdge::_label protected
label of the edge
Referenced by printAttribute(), and printOthersAttributes().
PropList otawa::display::GraphVizItem::_props protected inherited
Properties of the attached object.
Referenced by otawa::display::GraphVizItem::getPropertiesString(), and otawa::display::GraphVizItem::setProps().
GraphVizNode* otawa::display::GraphVizEdge::_src protected
source of the edge
const PropList otawa::PropList::EMPTY static inherited
This is an empty proplist for convenience.
Referenced by otawa::DynProcessor::configure(), otawa::ActualFeature::processor(), otawa::SilentFeature::SilentFeature(), otawa::Processor::version(), and otawa::display::Driver::~Driver().
The documentation for this class was generated from the following files:
src/odisplay/graphviz.h
src/odisplay/graphviz_Edge.cpp