Otawa: otawa::ast::SeqAST Class Reference
otawa::ast::SeqAST Class Reference
AST Plugin
This AST represents sequences.
#include <otawa/ast/SeqAST.h>
Public Member Functions
SeqAST (AST *child1, AST *child2)
Build a new sequence with the given children.
AST * child1 (void) const
Get the first child AST of the sequence.
AST * child2 (void) const
Get the second child AST of the sequence.
virtual Inst * first (void)
virtual ast_kind_t kind (void) const
Get the kind of the AST.
virtual SeqAST * toSeq (void)
Get the sequence AST if this AST is a sequence, null else.
virtual int countInstructions (void) const
Count the number of instructions in the ast block.
virtual void release (void)
Deletion of AST can only be performed using this method.
virtual bool isNOP (void)
Test if the AST is the NOP AST.
virtual bool isUndef (void)
Test if the AST is the undefined AST.
virtual BlockAST * toBlock (void)
Get the block AST if this AST is a block, null else.
virtual CallAST * toCall (void)
Get the call AST if this AST is a call, null else.
virtual IfAST * toIf (void)
Get the selection AST if this AST is a selection, null else.
virtual WhileAST * toWhile (void)
Get the repetition AST if this AST is a repeatition, null else.
virtual DoWhileAST * toDoWhile (void)
Get the repetition AST if this AST is a repetition, null else.
virtual ForAST * toFor (void)
Get the repetition AST if this AST is a repetition, null else.
Property * getProp (const AbstractIdentifier *id) const
Find a property by its identifier.
void setProp (Property *prop)
Set the property in the property list removing any double.
void setProp (const AbstractIdentifier *id)
void removeProp (const AbstractIdentifier *id)
Remove a property matching the given identifier.
void removeProp (const AbstractIdentifier &id)
Property * extractProp (const AbstractIdentifier *id)
Remove a property matching the given identifier and return it.
Property * extractProp (const AbstractIdentifier &id)
Remove a property matching the given identifier and return it.
void addProp (Property *prop)
Add property to the list without checking of duplication.
void removeAllProp (const AbstractIdentifier *id)
Remove all the properties matching the given identifier.
bool hasProp (const AbstractIdentifier &id) const
Test if the property list contains a property matching the given identifier.
void clearProps (void)
Remove all properties from the list.
void addProps (const PropList &props)
Add all properties from the given property list, in a reverse order.
void print (elm::io::Output &out) const
Display the current property list.
Static Public Attributes
static AST & NOP = nop_inst
Unique instance of the NOP AST.
static AST & UNDEF = undef_inst
Unique instance of the Undef AST.
static const PropList EMPTY
This is an empty proplist for convenience.
Protected Member Functions
virtual ~SeqAST (void)
Private Attributes
AST * c1
AST * c2
Detailed Description
This AST represents sequences.
It accept only two children so that sequences must be currified.
Constructor & Destructor Documentation
otawa::ast::SeqAST::~SeqAST (void) protected virtual
References c1, c2, and otawa::ast::AST::release().
otawa::ast::SeqAST::SeqAST (AST * child1, AST * child2)
Build a new sequence with the given children.
Parameters
child1 First child.
child2 Second child.
Member Function Documentation
void otawa::PropList::addProp (Property * prop) inherited
Add property to the list without checking of duplication.
Parameters
prop Property to add.
References otawa::Property::_next.
Referenced by otawa::Identifier< T >::add(), otawa::ast::ASTInfo::ASTInfo(), otawa::Identifier< otawa::arm::Info * >::copy(), otawa::AbstractIdentifier::initProps(), otawa::ContextualProperty::make(), otawa::script::Script::makeConfig(), otawa::ccg::Builder::processLBlockSet(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), and otawa::ContextualProperty::refProps().
void otawa::PropList::addProps (const PropList & props) inherited
Add all properties from the given property list, in a reverse order.
Parameters
props Property list to clone.
References otawa::Property::copy(), otawa::PropList::head, and otawa::Property::next().
Referenced by otawa::display::CFGDrawer::CFGDrawer(), otawa::display::GraphVizGraph::GraphVizGraph(), otawa::ParamFeature::instantiate(), otawa::Manager::loadXML(), otawa::display::GraphVizGraph::newEdge(), otawa::display::GraphVizGraph::newNode(), otawa::Process::Process(), otawa::display::GraphVizItem::setProps(), otawa::VirtualBasicBlock::VirtualBasicBlock(), and otawa::VirtualCFG::VirtualCFG().
AST * otawa::ast::SeqAST::child1 (void) const inline
Get the first child AST of the sequence.
Returns
First child in sequence.
References c1.
Referenced by otawa::ets::ACSComputation::applyProcess(), otawa::ets::CacheHitComputation::computation(), otawa::ets::CacheMissComputation::computation(), otawa::ets::CacheFirstMissComputation::computation(), otawa::ets::WCETComputation::computation(), otawa::ets::ACSComputation::initialization(), otawa::ets::FlowFactLoader::processAST(), and otawa::ets::TrivialAstBlockTime::processAST().
AST * otawa::ast::SeqAST::child2 (void) const inline
Get the second child AST of the sequence.
Returns
Second child in sequence.
References c2, and first().
Referenced by otawa::ets::ACSComputation::applyProcess(), otawa::ets::CacheHitComputation::computation(), otawa::ets::CacheMissComputation::computation(), otawa::ets::CacheFirstMissComputation::computation(), otawa::ets::WCETComputation::computation(), otawa::ets::ACSComputation::initialization(), otawa::ets::FlowFactLoader::processAST(), and otawa::ets::TrivialAstBlockTime::processAST().
void otawa::PropList::clearProps (void) inherited
Remove all properties from the list.
References otawa::Property::next().
Referenced by otawa::PSTBuilder::getVCFG(), otawa::display::GraphVizItem::setProps(), and otawa::WorkSpace::~WorkSpace().
int otawa::ast::SeqAST::countInstructions (void) const virtual
Count the number of instructions in the ast block.
Returns
Number of instruction in the ast block.
Implements otawa::ast::AST.
References c1, c2, and otawa::ast::AST::countInstructions().
Referenced by toSeq().
Property * otawa::PropList::extractProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::script::Script::makeConfig().
Property * otawa::PropList::extractProp (const AbstractIdentifier & id) inline inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::PropList::extractProp().
Referenced by otawa::PropList::extractProp().
Inst * otawa::ast::SeqAST::first (void) virtual
Implements otawa::ast::AST.
References c1, c2, and otawa::ast::AST::first().
Referenced by child2(), otawa::ets::CacheFirstMissComputation::computation(), otawa::ets::CacheMissComputation::computation(), otawa::ets::CacheHitComputation::computation(), and otawa::ets::WCETComputation::computation().
Property * otawa::PropList::getProp (const AbstractIdentifier * id) const inherited
Find a property by its identifier.
Parameters
id Identifier of the property to find.
Returns
Found property or null.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::Identifier< otawa::arm::Info * >::exists(), otawa::ContextualProperty::exists(), otawa::ContextualProperty::find(), otawa::Identifier< T >::get(), otawa::ContextualProperty::make(), otawa::ParamFeature::matches(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::print(), otawa::ContextualProperty::print(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), otawa::ContextualProperty::refProps(), otawa::Identifier< T >::set(), otawa::Identifier< T >::use(), and otawa::Identifier< T >::value().
bool otawa::PropList::hasProp (const AbstractIdentifier & id) const inline inherited
Test if the property list contains a property matching the given identifier.
Parameters
id Property identifier to look for.
Returns
True if the list contains the matching property, false else.
References otawa::p::print().
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::Monitor::configure(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::exists(), and otawa::Manager::setVerbosity().
bool otawa::ast::AST::isNOP (void) inline virtual inherited
Test if the AST is the NOP AST.
Returns
True if it is the NOP AST, false else.
bool otawa::ast::AST::isUndef (void) inline virtual inherited
Test if the AST is the undefined AST.
Returns
True if it is the undefined AST, false else.
virtual ast_kind_t otawa::ast::SeqAST::kind (void) const inline virtual
Get the kind of the AST.
Implements otawa::ast::AST.
References otawa::ast::AST_Seq.
void otawa::PropList::print (elm::io::Output & out) const inherited
Display the current property list.
Parameters
out Output to use.
Referenced by otawa::Edge::kindName(), otawa::operator<<(), and otawa::ContextualProperty::print().
void otawa::ast::AST::release (void) virtual inherited
Deletion of AST can only be performed using this method.
References otawa::ast::AST::NOP, and otawa::ast::AST::UNDEF.
Referenced by otawa::ast::FunAST::FunAST(), otawa::ast::DoWhileAST::~DoWhileAST(), otawa::ast::ForAST::~ForAST(), otawa::ast::IfAST::~IfAST(), ~SeqAST(), and otawa::ast::WhileAST::~WhileAST().
void otawa::PropList::removeAllProp (const AbstractIdentifier * id) inherited
Remove all the properties matching the given identifier.
Parameters
id Identifier of properties to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::LoopUnroller::unroll().
void otawa::PropList::removeProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier.
Parameters
id Identifier of the property to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::PSTBuilder::buildTree(), otawa::BBRemover< T >::clean(), otawa::CFGBuilder::cleanup(), otawa::display::CFGOutput::processCFG(), otawa::SubCFGBuilder::processWorkSpace(), otawa::Identifier< otawa::arm::Info * >::remove(), and otawa::ContextualPath::Ref< T >::remove().
void otawa::PropList::removeProp (const AbstractIdentifier & id) inline inherited
References otawa::PropList::removeProp().
Referenced by otawa::PropList::removeProp().
void otawa::PropList::setProp (Property * prop) inherited
Set the property in the property list removing any double.
Parameters
prop Property to set.
References otawa::Property::_next, otawa::Property::id(), and otawa::Property::next().
void otawa::PropList::setProp (const AbstractIdentifier * id) inline inherited
References otawa::PropList::setProp().
Referenced by otawa::PropList::setProp().
BlockAST * otawa::ast::AST::toBlock (void) inline virtual inherited
Get the block AST if this AST is a block, null else.
Returns
Block AST or null.
Reimplemented in otawa::ast::BlockAST.
Referenced by otawa::ets::ACSComputation::applyProcess(), otawa::ets::CacheHitComputation::computation(), otawa::ets::CacheMissComputation::computation(), otawa::ets::CacheFirstMissComputation::computation(), otawa::ets::WCETComputation::computation(), otawa::ets::ACSComputation::initialization(), and otawa::ets::TrivialAstBlockTime::processAST().
CallAST * otawa::ast::AST::toCall (void) inline virtual inherited
Get the call AST if this AST is a call, null else.
Returns
Call AST or null.
Reimplemented in otawa::ast::CallAST.
Referenced by otawa::ets::ACSComputation::applyProcess(), otawa::ets::CacheHitComputation::computation(), otawa::ets::CacheFirstMissComputation::computation(), otawa::ets::CacheMissComputation::computation(), otawa::ets::WCETComputation::computation(), otawa::ets::ACSComputation::initialization(), otawa::ets::FlowFactLoader::processAST(), and otawa::ets::TrivialAstBlockTime::processAST().
BlockAST * otawa::ast::AST::toDoWhile (void) inline virtual inherited
Get the repetition AST if this AST is a repetition, null else.
Returns
Repetition AST or null.
Reimplemented in otawa::ast::DoWhileAST.
Referenced by otawa::ets::ACSComputation::applyProcess(), otawa::ets::CacheHitComputation::computation(), otawa::ets::CacheFirstMissComputation::computation(), otawa::ets::CacheMissComputation::computation(), otawa::ets::WCETComputation::computation(), otawa::ets::ACSComputation::initialization(), otawa::ets::FlowFactLoader::processAST(), and otawa::ets::TrivialAstBlockTime::processAST().
BlockAST * otawa::ast::AST::toFor (void) inline virtual inherited
Get the repetition AST if this AST is a repetition, null else.
Returns
Repetition AST or null.
Reimplemented in otawa::ast::ForAST.
References otawa::ast::AST::countInstructions().
Referenced by otawa::ets::ACSComputation::applyProcess(), otawa::ets::CacheHitComputation::computation(), otawa::ets::CacheFirstMissComputation::computation(), otawa::ets::CacheMissComputation::computation(), otawa::ets::WCETComputation::computation(), otawa::ets::ACSComputation::initialization(), otawa::ets::FlowFactLoader::processAST(), and otawa::ets::TrivialAstBlockTime::processAST().
BlockAST * otawa::ast::AST::toIf (void) inline virtual inherited
Get the selection AST if this AST is a selection, null else.
Returns
Selection AST or null.
Reimplemented in otawa::ast::IfAST.
Referenced by otawa::ets::ACSComputation::applyProcess(), otawa::ets::CacheHitComputation::computation(), otawa::ets::CacheFirstMissComputation::computation(), otawa::ets::CacheMissComputation::computation(), otawa::ets::WCETComputation::computation(), otawa::ets::ACSComputation::initialization(), otawa::ets::FlowFactLoader::processAST(), and otawa::ets::TrivialAstBlockTime::processAST().
virtual SeqAST* otawa::ast::SeqAST::toSeq (void) inline virtual
Get the sequence AST if this AST is a sequence, null else.
Returns
Sequence AST or null.
Reimplemented from otawa::ast::AST.
References countInstructions().
BlockAST * otawa::ast::AST::toWhile (void) inline virtual inherited
Get the repetition AST if this AST is a repeatition, null else.
Returns
Repetition AST or null.
Reimplemented in otawa::ast::WhileAST.
Referenced by otawa::ets::ACSComputation::applyProcess(), otawa::ets::CacheHitComputation::computation(), otawa::ets::CacheMissComputation::computation(), otawa::ets::CacheFirstMissComputation::computation(), otawa::ets::WCETComputation::computation(), otawa::ets::ACSComputation::initialization(), otawa::ets::FlowFactLoader::processAST(), and otawa::ets::TrivialAstBlockTime::processAST().
Member Data Documentation
AST* otawa::ast::SeqAST::c1 private
Referenced by child1(), countInstructions(), first(), and ~SeqAST().
AST * otawa::ast::SeqAST::c2 private
Referenced by child2(), countInstructions(), first(), and ~SeqAST().
const PropList otawa::PropList::EMPTY static inherited
This is an empty proplist for convenience.
Referenced by otawa::DynProcessor::configure(), otawa::ActualFeature::processor(), otawa::SilentFeature::SilentFeature(), otawa::Processor::version(), and otawa::display::Driver::~Driver().
AST & otawa::ast::AST::NOP = nop_inst static inherited
Unique instance of the NOP AST.
Referenced by otawa::ast::AST::release(), and otawa::ast::AST::~AST().
AST & otawa::ast::AST::UNDEF = undef_inst static inherited
Unique instance of the Undef AST.
Referenced by otawa::ast::AST::release().
The documentation for this class was generated from the following files:
include/otawa/ast/SeqAST.h
src/ast/SeqAST.cpp