Otawa: otawa::ccg::LBlockSet Class Reference
otawa::ccg::LBlockSet Class Reference
This class represents the list of l-blocks of a task for a chosen cache row.
#include <otawa/ccg/features.h>
Classes
class Iterator
Public Member Functions
LBlockSet (int row, const hard::Cache *cache)
Build a l-block set.
int add (LBlock *node)
Add a new l-block.
int count (void)
Get a number for a new l-block in the set.
int cacheBlockCount (void)
Get the internal counter of l-block number (only used internally).
LBlock * lblock (int i)
Get the l-block with the given index.
int set (void)
Get the set number of the l-blocks in the cache.
const hard::Cache * cache (void) const
int line (void)
Private Attributes
int linenumber
elm::genstruct::Vector< LBlock * > listelbc
int cblock_count
const hard::Cache * _cache
Friends
class CCGDFA
Detailed Description
This class represents the list of l-blocks of a task for a chosen cache row.
It is useful to perform analysis on l-blocks. It is accessible through the property otawa::LBLOCKS.
Constructor & Destructor Documentation
otawa::ccg::LBlockSet::LBlockSet (int line, const hard::Cache * cache)
Build a l-block set.
Parameters
line Cache row of the l-block set.
References otawa::ccg::COLLECTED_LBLOCKS_FEATURE.
Member Function Documentation
int otawa::ccg::LBlockSet::add (LBlock * lblock)
Add a new l-block.
Parameters
lblock l-block to add.
References otawa::ccg::LBlock::cacheBlock(), and otawa::ccg::LBlock::id().
const hard::Cache* otawa::ccg::LBlockSet::cache (void) const inline
int otawa::ccg::LBlockSet::cacheBlockCount (void) inline
Get the internal counter of l-block number (only used internally).
Referenced by otawa::ccg::LBlockBuilder::addLBlock().
int otawa::ccg::LBlockSet::count (void) inline
Get a number for a new l-block in the set.
Used internally to build l-blocks.
Returns
New l-block number.
Get the count of l-blocks in the set.
Returns
Count of l-blocks.
Referenced by otawa::ccg::ConstraintBuilder::addConstraintHeader(), otawa::ccg::ConstraintBuilder::processLBlockSet(), and otawa::ccg::Builder::processLBlockSet().
LBlock * otawa::ccg::LBlockSet::lblock (int i) inline
Get the l-block with the given index.
Parameters
i Index of the looked block.
Returns
L-block matching the index.
Referenced by otawa::ccg::Builder::processLBlockSet().
int otawa::ccg::LBlockSet::line (void) inline
Referenced by otawa::ccg::operator<<(), and otawa::ccg::Builder::processLBlockSet().
int otawa::ccg::LBlockSet::set (void) inline
Get the set number of the l-blocks in the cache.
Returns
Cache set number.
Friends And Related Function Documentation
friend class CCGDFA friend
Member Data Documentation
const hard::Cache* otawa::ccg::LBlockSet::_cache private
int otawa::ccg::LBlockSet::cblock_count private
int otawa::ccg::LBlockSet::linenumber private
elm::genstruct::Vector<LBlock *> otawa::ccg::LBlockSet::listelbc private
The documentation for this class was generated from the following files:
include/otawa/ccg/features.h
src/ccg/ccg_LBlockBuilder.cpp