Otawa: otawa::PERSProblem::Item Class Reference
otawa::PERSProblem::Item Class Reference
#include <otawa/cache/cat2/PERSProblem.h>
Public Member Functions
Item (const int _size, const int _A)
~Item ()
Item (const Item &source)
Item & operator= (const Item &src)
void refresh (int id, int newage)
void lub (const Item &dom)
bool equals (const Item &dom) const
void empty ()
bool contains (const int id)
void inject (MUSTProblem::Domain *must, const int id)
bool isWiped (const int id)
bool isPersistent (const int id)
int getAge (const int id) const
void addDamage (const int id, int damage)
void print (elm::io::Output &output) const
Public Attributes
int * age
Private Attributes
int A
int size
Constructor & Destructor Documentation
otawa::PERSProblem::Item::Item (const int _size, const int _A) inline
References age, and size.
Referenced by otawa::PERSProblem::Domain::enterContext().
otawa::PERSProblem::Item::~Item () inline
References age.
otawa::PERSProblem::Item::Item (const Item & source) inline
References age, and size.
Member Function Documentation
void otawa::PERSProblem::Item::addDamage (const int id, int damage) inline
References A, and age.
Referenced by otawa::PERSProblem::Domain::addDamage().
bool otawa::PERSProblem::Item::contains (const int id) inline
References age.
Referenced by otawa::PERSProblem::Domain::contains(), and isPersistent().
void otawa::PERSProblem::Item::empty () inline
References age, and size.
Referenced by otawa::PERSProblem::Domain::enterContext().
bool otawa::PERSProblem::Item::equals (const Item & dom) const inline
References A, age, and size.
Referenced by otawa::PERSProblem::Domain::equals().
int otawa::PERSProblem::Item::getAge (const int id) const inline
References age.
Referenced by otawa::PERSProblem::Domain::getAge().
void otawa::PERSProblem::Item::inject (MUSTProblem::Domain * must, const int id) inline
References A, age, otawa::MUSTProblem::Domain::contains(), and size.
Referenced by otawa::PERSProblem::Domain::inject().
bool otawa::PERSProblem::Item::isPersistent (const int id) inline
References contains(), and isWiped().
Referenced by otawa::PERSProblem::Domain::isPersistent().
bool otawa::PERSProblem::Item::isWiped (const int id) inline
References age.
Referenced by isPersistent(), and otawa::PERSProblem::Domain::isWiped().
void otawa::PERSProblem::Item::lub (const Item & dom) inline
References age, and size.
Referenced by otawa::PERSProblem::Domain::lub().
Item& otawa::PERSProblem::Item::operator= (const Item & src) inline
References A, age, and size.
void otawa::PERSProblem::Item::print (elm::io::Output & output) const inline
References age, and size.
void otawa::PERSProblem::Item::refresh (int id, int newage) inline
References age.
Referenced by otawa::PERSProblem::Domain::refresh().
Member Data Documentation
int otawa::PERSProblem::Item::A private
Referenced by addDamage(), equals(), inject(), and operator=().
int* otawa::PERSProblem::Item::age
Referenced by addDamage(), contains(), empty(), equals(), getAge(), inject(), isWiped(), Item(), lub(), operator=(), print(), refresh(), and ~Item().
int otawa::PERSProblem::Item::size private
Referenced by empty(), equals(), inject(), Item(), lub(), operator=(), and print().
The documentation for this class was generated from the following file:
include/otawa/cache/cat2/PERSProblem.h