Otawa: otawa::pfg::BB Class Reference
otawa::pfg::BB Class Reference
A basic block in a otawa::pfg::PFG .
#include <otawa/cfg/PFG.h>
Classes
class InstIter
Iterator on the instructions of a basic block.
Public Member Functions
BB (void)
BB (Inst *first, t::uint32 size)
Address address (void) const
Get the start address of the basic block.
Address topAddress (void) const
Get the address next after the basic block, that is, address + size.
t::uint32 size (void) const
Get the size of the basic block.
Inst * first (void) const
Get the first instruction of the basic block.
int count (void) const
Count the number of instructions in the basic block.
PFG & pfg (void) const
bool isControl (void) const
Test if the basic block is ended by a control instruction.
bool isBranch (void) const
Test if the basic block is ended by a simple branch instruction (neither a call, nor a return).
bool isConditional (void) const
Test if the basic block is ended by a conditional branch.
bool isBranched (void) const
bool isCall (void) const
Test if the basic block ends with a call instruction.
bool isReturn (void) const
Test if the basic block ends with a return instruction.
bool isMultiTarget (void) const
Test if the basic block ends with a multi-target branch instruction (either branch, or call).
void setSize (size_t size)
int index (void) const
bool hasSucc (void) const
bool hasPred (void) const
int countSucc (void) const
int countPred (void) const
bool isPredOf (const GenNode *node)
bool isSuccOf (const GenNode *node)
Private Attributes
Inst * _first
t::uint32 _size
Detailed Description
A basic block in a otawa::pfg::PFG .
Constructor & Destructor Documentation
otawa::pfg::BB::BB (void) inline
otawa::pfg::BB::BB (Inst * first, t::uint32 size) inline
Member Function Documentation
Address otawa::pfg::BB::address (void) const inline
Get the start address of the basic block.
Returns
Basic block address.
Referenced by otawa::pfg::PFG::add(), and otawa::PFGBuilder::finalizeBB().
int otawa::pfg::BB::count (void) const inline
Count the number of instructions in the basic block.
Returns
Number of instruction.
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::countPred (void) const inline inherited
References otawa::graph::Node::countPred().
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::countSucc (void) const inline inherited
References otawa::graph::Node::countSucc().
Inst * otawa::pfg::BB::first (void) const inline
Get the first instruction of the basic block.
Returns
First instruction.
Referenced by otawa::PFGBuilder::finalizeBB().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::hasPred (void) const inline inherited
References otawa::graph::Node::hasPred().
Referenced by otawa::LiExeGraph::shadeNodes().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::hasSucc (void) const inline inherited
References otawa::graph::Node::hasSucc().
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::index (void) const inline inherited
References otawa::graph::Node::index().
Referenced by otawa::ParamExeGraph::cost().
bool otawa::pfg::BB::isBranch (void) const
Test if the basic block is ended by a simple branch instruction (neither a call, nor a return).
Returns
True if it ends with a branch instructions, false else.
References otawa::pfg::Edge::BRANCH, otawa::pfg::Edge::COND_BRANCH, and otawa::cfgio::edge().
bool otawa::pfg::BB::isBranched (void) const
bool otawa::pfg::BB::isCall (void) const
Test if the basic block ends with a call instruction.
Returns
True if it ends with a call instruction, false else.
References otawa::pfg::Edge::CALL, otawa::pfg::Edge::COND_CALL, and otawa::cfgio::edge().
bool otawa::pfg::BB::isConditional (void) const
Test if the basic block is ended by a conditional branch.
Returns
True if it is ended by a conditional branch, false else.
References otawa::pfg::Edge::COND_BRANCH, otawa::pfg::Edge::COND_CALL, otawa::pfg::Edge::COND_RETURN, and otawa::cfgio::edge().
bool otawa::pfg::BB::isControl (void) const
Test if the basic block is ended by a control instruction.
Returns
True if it contains a control, false else.
References otawa::cfgio::edge(), and otawa::pfg::Edge::SEQ.
bool otawa::pfg::BB::isMultiTarget (void) const
Test if the basic block ends with a multi-target branch instruction (either branch, or call).
Returns
True if it ends with a multi-target branch instruction, false else.
References otawa::pfg::Edge::BRANCH, otawa::pfg::Edge::CALL, otawa::pfg::Edge::COND_BRANCH, otawa::pfg::Edge::COND_CALL, and otawa::cfgio::edge().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::isPredOf (const GenNode * node) inline inherited
References otawa::graph::Node::countPred().
bool otawa::pfg::BB::isReturn (void) const
Test if the basic block ends with a return instruction.
Returns
True if it ends with a return instruction, false else.
References otawa::pfg::Edge::COND_RETURN, otawa::cfgio::edge(), and otawa::pfg::Edge::RETURN.
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::isSuccOf (const GenNode * node) inline inherited
References otawa::graph::Node::isSuccOf().
PFG& otawa::pfg::BB::pfg (void) const inline
void otawa::pfg::BB::setSize (size_t size) inline
Referenced by otawa::PFGBuilder::finalizeBB().
size_t otawa::pfg::BB::size (void) const inline
Get the size of the basic block.
Returns
Basic block size in bytes.
Address otawa::pfg::BB::topAddress (void) const inline
Get the address next after the basic block, that is, address + size.
Returns
Basic block next after address.
References otawa::ot::address().
Member Data Documentation
Inst* otawa::pfg::BB::_first private
t::uint32 otawa::pfg::BB::_size private
The documentation for this class was generated from the following files:
include/otawa/cfg/PFG.h
src/prog/cfg_PFG.cpp