Otawa: otawa::DynIdentifier< T > Class Template Reference
otawa::DynIdentifier< T > Class Template Reference
Dynamic Identifier, Feature and Processor
An identifier dynamically resolved.
#include <otawa/prop/DynIdentifier.h>
Public Member Functions
DynIdentifier (cstring name)
Build a dynamic identifier.
cstring name (void) const
Get the full-qualified C++ name of the identifier.
const T & operator() (const PropList &props) const
const T & operator() (const PropList *props) const
Ref< T, Identifier< T > > operator() (PropList &props) const
Ref< T, Identifier< T > > operator() (PropList *props) const
Private Member Functions
Identifier< T > & id (void) const
Private Attributes
cstring _name
Identifier< T > * _id
Detailed Description
template<class T>
class otawa::DynIdentifier< T >
An identifier dynamically resolved.
Pass the full-qualified C++ name to the constructor and use it as a normal identifier.
Parameters
T Type of identifier value.
Constructor & Destructor Documentation
template<class T > otawa::DynIdentifier< T >::DynIdentifier (cstring name) inline
Build a dynamic identifier.
Parameters
name Full-qualified C++ name of the dynamic identifier.
Member Function Documentation
template<class T > Identifier<T>& otawa::DynIdentifier< T >::id (void) const inline private
References otawa::DynIdentifier< T >::_id, otawa::DynIdentifier< T >::_name, and otawa::ProcessorPlugin::getIdentifier().
Referenced by otawa::DynIdentifier< T >::operator()().
template<class T > cstring otawa::DynIdentifier< T >::name (void) const inline
Get the full-qualified C++ name of the identifier.
Returns
Identifier name.
References otawa::DynIdentifier< T >::_name.
template<class T > const T& otawa::DynIdentifier< T >::operator() (const PropList & props) const inline
References otawa::DynIdentifier< T >::id().
template<class T > const T& otawa::DynIdentifier< T >::operator() (const PropList * props) const inline
References otawa::DynIdentifier< T >::id().
template<class T > Ref<T, Identifier<T> > otawa::DynIdentifier< T >::operator() (PropList & props) const inline
References otawa::DynIdentifier< T >::id().
template<class T > Ref<T, Identifier<T> > otawa::DynIdentifier< T >::operator() (PropList * props) const inline
References otawa::DynIdentifier< T >::id().
Member Data Documentation
template<class T > Identifier<T>* otawa::DynIdentifier< T >::_id mutable private
Referenced by otawa::DynIdentifier< T >::id().
template<class T > cstring otawa::DynIdentifier< T >::_name private
Referenced by otawa::DynIdentifier< T >::id(), and otawa::DynIdentifier< T >::name().
The documentation for this class was generated from the following files:
include/otawa/prop/DynIdentifier.h
src/prog/proc_DynFeature.cpp