Otawa: otawa::display::CFGAdapter::Edge Class Reference
otawa::display::CFGAdapter::Edge Class Reference
#include <otawa/display/CFGAdapter.h>
Public Member Functions
Edge (otawa::Edge *_edge)
Vertex source (void) const
Vertex sink (void) const
Public Attributes
otawa::Edge * edge
Constructor & Destructor Documentation
otawa::display::CFGAdapter::Edge::Edge (otawa::Edge * _edge) inline
Member Function Documentation
Vertex otawa::display::CFGAdapter::Edge::sink (void) const inline
References otawa::cfgio::edge(), and otawa::display::CFGAdapter::Vertex::Vertex().
Vertex otawa::display::CFGAdapter::Edge::source (void) const inline
References otawa::cfgio::edge(), and otawa::display::CFGAdapter::Vertex::Vertex().
Member Data Documentation
otawa::Edge* otawa::display::CFGAdapter::Edge::edge
The documentation for this class was generated from the following file:
include/otawa/display/CFGAdapter.h