Otawa: otawa::hard::MeltedBank Class Reference
otawa::hard::MeltedBank Class Reference
Platform Description
A melted bank may contains registers with different sizes and kinds.
#include <otawa/hard/Register.h>
Public Member Functions
MeltedBank (elm::CString name,...)
Build a melted bank with the registers passed in the variable list arguments (ended by null).
~MeltedBank (void)
elm::CString name (void) const
Get the name of the bank.
Register::kind_t kind (void) const
Get the kind of registers in the bank.
int size (void) const
Get the size, in bits, of the registers in the bank.
int count (void) const
Get the count of register in the bank.
Register * get (int index) const
Get a register from the bank.
Register * operator[] (int index) const
Short to RegBank::get().
const elm::genstruct::Table< Register * > & registers () const
Protected Member Functions
void set (int index, Register *reg)
Protected Attributes
elm::CString _name
Register::kind_t _kind
int _size
elm::genstruct::AllocatedTable< Register * > _regs
Detailed Description
A melted bank may contains registers with different sizes and kinds.
It is useful for grouping state registers.
Constructor & Destructor Documentation
otawa::hard::MeltedBank::MeltedBank (elm::CString name, ...)
Build a melted bank with the registers passed in the variable list arguments (ended by null).
Parameters
name Name of the bank.
... List of registers in the bank.
References otawa::hard::RegBank::_regs.
otawa::hard::MeltedBank::~MeltedBank (void)
Member Function Documentation
int otawa::hard::RegBank::count (void) const inline inherited
Get the count of register in the bank.
Returns
Bank registers count.
Referenced by otawa::hard::PlainBank::PlainBank(), and otawa::ResourceList::ResourceList().
Register * otawa::hard::RegBank::get (int number) const inline inherited
Get a register from the bank.
Parameters
number Number of the register to get.
Returns
Register matching the given number.
Referenced by otawa::ResourceList::ResourceList().
Register::kind_t otawa::hard::RegBank::kind (void) const inline inherited
Get the kind of registers in the bank.
Returns
Bank register kind.
References otawa::hard::Register::_kind.
Referenced by otawa::hard::PlainBank::PlainBank().
elm::CString otawa::hard::RegBank::name (void) const inline inherited
Get the name of the bank.
Returns
Bank name.
References otawa::hard::Register::_name.
Referenced by otawa::ResourceList::ResourceList().
Register * otawa::hard::RegBank::operator[] (int index) const inline inherited
Short to RegBank::get().
const elm::genstruct::Table<Register *>& otawa::hard::RegBank::registers () const inline inherited
void otawa::hard::RegBank::set (int index, Register * reg) inline protected inherited
int otawa::hard::RegBank::size (void) const inline inherited
Get the size, in bits, of the registers in the bank.
Returns
Bank register size.
References otawa::hard::Register::_size.
Referenced by otawa::hard::PlainBank::PlainBank().
Member Data Documentation
Register::kind_t otawa::hard::RegBank::_kind protected inherited
elm::CString otawa::hard::RegBank::_name protected inherited
elm::genstruct::AllocatedTable<Register *> otawa::hard::RegBank::_regs protected inherited
Referenced by MeltedBank(), and otawa::hard::PlainBank::~PlainBank().
int otawa::hard::RegBank::_size protected inherited
The documentation for this class was generated from the following files:
include/otawa/hard/Register.h
src/prog/hard_Register.cpp