Otawa: otawa::dfa::Successor Class Reference
otawa::dfa::Successor Class Reference
Data Flow Analysis
This iterator is used to traverse backward a CFG in an iterative DFA analysis.
#include <otawa/dfa/IterativeDFA.h>
Public Types
typedef Predecessor Forward
Public Member Functions
Successor (BasicBlock *bb)
BasicBlock * item (void) const
bool ended (void) const
void next (void)
Static Public Member Functions
static BasicBlock * entry (CFG &cfg)
Private Member Functions
void look (void)
Private Attributes
BasicBlock::OutIterator iter
Detailed Description
This iterator is used to traverse backward a CFG in an iterative DFA analysis.
Member Typedef Documentation
typedef Predecessor otawa::dfa::Successor::Forward
Constructor & Destructor Documentation
otawa::dfa::Successor::Successor (BasicBlock * bb) inline
References otawa::dfa::Predecessor::look().
Member Function Documentation
bool otawa::dfa::Successor::ended (void) const inline
static BasicBlock* otawa::dfa::Successor::entry (CFG & cfg) inline static
References otawa::CFG::exit().
BasicBlock* otawa::dfa::Successor::item (void) const inline
void otawa::dfa::Successor::look (void) inline private
References otawa::Edge::CALL.
void otawa::dfa::Successor::next (void) inline
References otawa::dfa::Predecessor::look().
Member Data Documentation
BasicBlock::OutIterator otawa::dfa::Successor::iter private
The documentation for this class was generated from the following file:
include/otawa/dfa/IterativeDFA.h