Otawa: otawa::LiExeGraph Class Reference
otawa::LiExeGraph Class Reference
#include <otawa/exegraph/LiExeGraph.h>
Public Types
typedef class LiExeNode Node
enum code_part_t
typedef enum otawa::ExeGraph::code_part_t code_part_t
enum time_bound_t
enum time_step_t
typedef GenGraph< LiExeNode, typename ExeGraph< LiExeNode >::ExeEdge > Graph
Public Member Functions
LiExeGraph (WorkSpace *fw, Microprocessor< LiExeNode > *microprocessor, ExeSequence< LiExeNode > *sequence)
int analyze ()
void setTimesChanged ()
void dump (elm::io::Output &dotFile)
GenGraph< LiExeNode, typename ExeGraph< LiExeNode >::ExeEdge > * graph ()
void setEntryNode (LiExeNode *node)
Sets the entry node (used for topological graph exploration).
LiExeNode * entryNode (void)
virtual void build (WorkSpace *fw, Microprocessor< LiExeNode > *microprocessor, ExeSequence< LiExeNode > *sequence)
elm::String partName (code_part_t part)
void setFirstNode (code_part_t part, LiExeNode *node)
void setLastNode (code_part_t part, LiExeNode *node)
LiExeNode * firstNode (code_part_t part)
LiExeNode * lastNode (code_part_t part)
Protected Types
typedef struct otawa::ExeGraph::rename_table_t rename_table_t
Protected Attributes
LiExeNode * _entry_node
LiExeNode * _first_node [CODE_PARTS_NUMBER]
LiExeNode * _last_node [CODE_PARTS_NUMBER]
ExeSequence< LiExeNode > * _sequence
Microprocessor< LiExeNode > * _microprocessor
elm::String _part_name [CODE_PARTS_NUMBER]
GenGraph< LiExeNode, ExeEdge > _graph
Private Member Functions
void latestTimes ()
void earliestTimes ()
bool maxTimeToNode (LiExeNode *source, LiExeNode *target, int *time)
void shadeNodes (LiExeNode *node)
void nodeLatestTimes (LiExeNode *node)
void nodeEarliestTimes (LiExeNode *node)
bool separated (LiExeNode *u, LiExeNode *v)
elm::String timeName (int time)
Private Attributes
bool _times_changed
Member Typedef Documentation
typedef enum otawa::ExeGraph::code_part_t otawa::ExeGraph< LiExeNode >::code_part_t inherited
typedef GenGraph<LiExeNode ,typename ExeGraph<LiExeNode >::ExeEdge> otawa::ExeGraph< LiExeNode >::Graph inherited
typedef class LiExeNode otawa::LiExeGraph::Node
typedef struct otawa::ExeGraph::rename_table_t otawa::ExeGraph< LiExeNode >::rename_table_t protected inherited
Member Enumeration Documentation
enum otawa::ExeGraph::code_part_t inherited
enum otawa::ExeGraph::time_bound_t inherited
enum otawa::ExeGraph::time_step_t inherited
Constructor & Destructor Documentation
otawa::LiExeGraph::LiExeGraph (WorkSpace * fw, Microprocessor< LiExeNode > * microprocessor, ExeSequence< LiExeNode > * sequence) inline
Member Function Documentation
int LiExeGraph::analyze ()
References _times_changed, otawa::ExeGraph< LiExeNode >::BODY, delta(), earliestTimes(), otawa::ExeGraph< LiExeNode >::FINISH, otawa::ExeGraph< LiExeNode >::firstNode(), INFINITE_TIME, otawa::ExeGraph< LiExeNode >::lastNode(), otawa::ExeGraph< N >::ExeNode::latency(), latestTimes(), otawa::ExeGraph< LiExeNode >::MAX, maxTimeToNode(), otawa::ExeGraph< LiExeNode >::MIN, otawa::ExeGraph< LiExeNode >::PROLOGUE, shadeNodes(), and otawa::LiExeNode::time().
Referenced by otawa::LiExeGraphBBTime::processSequence().
virtual void otawa::ExeGraph< LiExeNode >::build (WorkSpace * fw, Microprocessor< LiExeNode > * microprocessor, ExeSequence< LiExeNode > * sequence) virtual inherited
Parameters
fw The framework.
microprocessor The microprocessor.
sequence The sequence of instructions the graph should represent.
void LiExeGraph::dump (elm::io::Output & dotFile)
References otawa::ExeGraph< LiExeNode >::_sequence, otawa::ExeGraph< LiExeNode >::BODY, otawa::ExeGraph< LiExeNode >::FINISH, otawa::ExeGraph< LiExeNode >::MAX, otawa::ExeGraph< LiExeNode >::MIN, otawa::ExeGraph< LiExeNode >::READY, otawa::ExeGraph< LiExeNode >::START, and timeName().
void LiExeGraph::earliestTimes () private
References otawa::ExeGraph< LiExeNode >::_entry_node, otawa::ExeGraph< LiExeNode >::_first_node, otawa::ExeGraph< LiExeNode >::BODY, otawa::ExeGraph< LiExeNode >::MIN, nodeEarliestTimes(), otawa::ExeGraph< LiExeNode >::READY, and otawa::LiExeNode::setTime().
Referenced by analyze().
LiExeNode * otawa::ExeGraph< LiExeNode >::entryNode (void) inline inherited
Returns
The entry node.
LiExeNode * otawa::ExeGraph< LiExeNode >::firstNode (code_part_t part) inline inherited
Parameters
part The code part.
Returns
The first node of the specified code part.
Referenced by analyze().
GenGraph<LiExeNode , typename ExeGraph<LiExeNode >::ExeEdge>* otawa::ExeGraph< LiExeNode >::graph (void) inline inherited
Returns
The graph.
LiExeNode * otawa::ExeGraph< LiExeNode >::lastNode (code_part_t part) inline inherited
Parameters
part The code part.
Returns
The last node of the specified code part.
Referenced by analyze(), latestTimes(), and nodeLatestTimes().
void LiExeGraph::latestTimes () private
References otawa::ExeGraph< LiExeNode >::_entry_node, otawa::ExeGraph< LiExeNode >::_first_node, otawa::ExeGraph< LiExeNode >::BODY, otawa::ExeGraph< LiExeNode >::FINISH, otawa::ExeGraph< LiExeNode >::lastNode(), otawa::ExeGraph< N >::ExeNode::latency(), otawa::ExeGraph< LiExeNode >::MAX, otawa::ExeGraph< LiExeNode >::MIN, nodeLatestTimes(), otawa::ExeGraph< LiExeNode >::PROLOGUE, otawa::ExeGraph< LiExeNode >::READY, otawa::LiExeNode::setTime(), shadeNodes(), and otawa::ExeGraph< LiExeNode >::START.
Referenced by analyze().
bool LiExeGraph::maxTimeToNode (LiExeNode * source, LiExeNode * target, int * time) private
References otawa::ExeGraph< N >::ExeNode::inst(), otawa::ExeGraph< N >::ExeNode::latency(), and otawa::ExeGraph< LiExeNode >::MIN.
Referenced by analyze().
void LiExeGraph::nodeEarliestTimes (LiExeNode * node) private
References otawa::sem::cont(), otawa::ExeGraph< LiExeNode >::FINISH, otawa::sem::inst::inst(), otawa::ExeGraph< N >::ExeNode::inst(), otawa::ExeGraph< N >::ExeNode::latency(), otawa::ExeGraph< LiExeNode >::MAX, otawa::ExeGraph< LiExeNode >::MIN, otawa::clp::min(), otawa::ExeGraph< N >::ExeNode::pipelineStage(), otawa::ExeGraph< LiExeNode >::READY, separated(), otawa::LiExeNode::setTime(), otawa::ExeGraph< LiExeNode >::START, and otawa::LiExeNode::time().
Referenced by earliestTimes().
void LiExeGraph::nodeLatestTimes (LiExeNode * node) private
References otawa::ExeGraph< LiExeNode >::BEFORE_PROLOGUE, otawa::sem::cont(), otawa::ExeGraph< LiExeNode >::FINISH, otawa::sem::inst::inst(), otawa::ExeGraph< N >::ExeNode::inst(), otawa::LiExeNode::isShaded(), otawa::ExeGraph< LiExeNode >::lastNode(), otawa::ExeGraph< N >::ExeNode::latency(), otawa::ExeGraph< LiExeNode >::MAX, otawa::ExeGraph< LiExeNode >::MIN, otawa::clp::min(), otawa::ExeGraph< N >::ExeNode::pipelineStage(), otawa::ExeGraph< LiExeNode >::READY, separated(), otawa::LiExeNode::setTime(), otawa::ExeGraph< LiExeNode >::START, and otawa::LiExeNode::time().
Referenced by latestTimes().
elm::String otawa::ExeGraph< LiExeNode >::partName (code_part_t part) inline inherited
Returns
The name of the code part (BEFORE_PROLOGUE, PROLOGUE, BODY or EPILOGUE).
bool LiExeGraph::separated (LiExeNode * u, LiExeNode * v) private
References otawa::ExeGraph< LiExeNode >::FINISH, otawa::ExeGraph< LiExeNode >::MAX, otawa::ExeGraph< LiExeNode >::MIN, otawa::ExeGraph< LiExeNode >::READY, and otawa::LiExeNode::time().
Referenced by nodeEarliestTimes(), and nodeLatestTimes().
void otawa::ExeGraph< LiExeNode >::setEntryNode (LiExeNode * node) inline inherited
Sets the entry node (used for topological graph exploration).
Parameters
node The entry node.
void otawa::ExeGraph< LiExeNode >::setFirstNode (code_part_t part, LiExeNode * node) inline inherited
Parameters
part The code part.
node The first node of this code part. Sets the first node of the specified code part.
void otawa::ExeGraph< LiExeNode >::setLastNode (code_part_t part, LiExeNode * node) inline inherited
Parameters
part The code part.
node The last node of this code part. Sets the last node of the specified code part.
void otawa::LiExeGraph::setTimesChanged () inline
Referenced by otawa::LiExeNode::setTime().
void LiExeGraph::shadeNodes (LiExeNode * node) private
References otawa::ExeGraph< LiExeNode >::FINISH, otawa::GenGraph< N, E >::GenNode::hasPred(), otawa::ExeGraph< LiExeNode >::MAX, otawa::ExeGraph< LiExeNode >::MIN, otawa::ExeGraph< LiExeNode >::READY, otawa::ExeGraph< LiExeNode >::START, and otawa::LiExeNode::time().
Referenced by analyze(), and latestTimes().
elm::String LiExeGraph::timeName (int time) inline private
References EPSILON, INFINITE_TIME, and otawa::LiExeNode::time().
Referenced by dump().
Member Data Documentation
LiExeNode * otawa::ExeGraph< LiExeNode >::_entry_node protected inherited
Referenced by earliestTimes(), and latestTimes().
LiExeNode * otawa::ExeGraph< LiExeNode >::_first_node[CODE_PARTS_NUMBER] protected inherited
Referenced by earliestTimes(), and latestTimes().
GenGraph<LiExeNode , ExeEdge> otawa::ExeGraph< LiExeNode >::_graph protected inherited
LiExeNode * otawa::ExeGraph< LiExeNode >::_last_node[CODE_PARTS_NUMBER] protected inherited
Microprocessor<LiExeNode >* otawa::ExeGraph< LiExeNode >::_microprocessor protected inherited
elm::String otawa::ExeGraph< LiExeNode >::_part_name[CODE_PARTS_NUMBER] protected inherited
ExeSequence<LiExeNode >* otawa::ExeGraph< LiExeNode >::_sequence protected inherited
Referenced by dump().
bool otawa::LiExeGraph::_times_changed private
Referenced by analyze().
The documentation for this class was generated from the following files:
include/otawa/exegraph/LiExeGraph.h
src/prog/exegraph_LiExeGraph.cpp