Otawa: otawa::CFGCollection Class Reference
otawa::CFGCollection Class Reference
CFG (Control Flow Graph)
Contains a collection of CFGs (used with INVOLVED_CFGS property).
#include <>>
Classes
class BBIterator
class Iterator
Iterator on the CFG contained in a CFGCollection.
Public Member Functions
int count (void) const
Get the count of CFG in the collection.
CFG * get (int index) const
Get a CFG from the collection using its index.
CFG * operator[] (int index) const
Shortcut to get().
void add (CFG *cfg)
Add a CFG to the collection.
Private Attributes
elm::genstruct::FragTable< CFG * > cfgs
Detailed Description
Contains a collection of CFGs (used with INVOLVED_CFGS property).
See also
otawa::CFGCollector, otawa::INVOLVED_CFGS
Member Function Documentation
void otawa::CFGCollection::add (CFG * cfg)
Add a CFG to the collection.
Parameters
cfg Added CFG.
References otawa::Identifier< T >::add(), otawa::CFGCollector::ADDED_CFG, otawa::CFGCollector::ADDED_FUNCTION, otawa::CALLED_BY, otawa::COLLECTED_CFG_FEATURE, otawa::INDEX, and otawa::INVOLVED_CFGS.
Referenced by otawa::Virtualizer::cleanup(), otawa::LoopUnroller::processWorkSpace(), otawa::CFGCollector::processWorkSpace(), and otawa::DelayedBuilder::processWorkSpace().
int otawa::CFGCollection::count (void) const inline
Get the count of CFG in the collection.
Returns
CFG count.
Referenced by otawa::dcache::CATBuilder::cleanup(), otawa::BBStatCollector::collect(), otawa::dfa::hai::DefaultListener< P >::DefaultListener(), otawa::CFGProcessor::doCleanUp(), otawa::dcache::operator<<(), otawa::BBStatCollector::process(), otawa::dcache::CATBuilder::processLBlockSet(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), otawa::CFGCollector::processWorkSpace(), otawa::BBStatCollector::total(), otawa::dfa::hai::UnrollingListener< P >::UnrollingListener(), otawa::dfa::hai::WideningListener< P >::WideningListener(), otawa::dfa::hai::DefaultListener< P >::~DefaultListener(), otawa::dfa::hai::UnrollingListener< P >::~UnrollingListener(), and otawa::dfa::hai::WideningListener< P >::~WideningListener().
CFG * otawa::CFGCollection::get (int index) const inline
Get a CFG from the collection using its index.
Parameters
index Index of the got CFG.
Returns
CFG matching the index.
Referenced by otawa::dcache::CATBuilder::cleanup(), otawa::LoopUnroller::cleanup(), otawa::DelayedBuilder::cleanup(), otawa::BBStatCollector::collect(), otawa::dfa::hai::DefaultListener< P >::DefaultListener(), otawa::CFGProcessor::doCleanUp(), otawa::dcache::operator<<(), otawa::BBStatCollector::process(), otawa::dcache::CATBuilder::processLBlockSet(), otawa::DeadCodeAnalysis::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), otawa::StackAnalysis::processWorkSpace(), otawa::CFGCollector::processWorkSpace(), otawa::Virtualizer::processWorkSpace(), otawa::clp::Analysis::processWorkSpace(), otawa::BBStatCollector::total(), otawa::LoopUnroller::unroll(), otawa::dfa::hai::UnrollingListener< P >::UnrollingListener(), otawa::dfa::hai::WideningListener< P >::WideningListener(), otawa::dfa::hai::DefaultListener< P >::~DefaultListener(), otawa::dfa::hai::UnrollingListener< P >::~UnrollingListener(), and otawa::dfa::hai::WideningListener< P >::~WideningListener().
CFG * otawa::CFGCollection::operator[] (int index) const inline
Shortcut to get().
Member Data Documentation
elm::genstruct::FragTable<CFG *> otawa::CFGCollection::cfgs private
The documentation for this class was generated from the following files:
include/otawa/cfg/features.h
src/prog/cfg_CFGCollector.cpp