Otawa: otawa::CFGInfo Class Reference
otawa::CFGInfo Class Reference
CFG (Control Flow Graph)
This allows storing all CFG available in a workspace.
#include <otawa/cfg/CFGInfo.h>
Classes
class Iter
Public Member Functions
CFGInfo (WorkSpace *fw)
Build a new CFGInfo.
virtual ~CFGInfo (void)
Delete the CFG information contained in this program.
CFG * findCFG (Address addr)
Get a CFG from the address of its first instruction.
CFG * findCFG (Inst *inst)
Find the CFG starting by the basic block containing this instruction.
CFG * findCFG (const BasicBlock *bb)
Find the CFG starting at the given basic block.
CFG * findCFG (String label)
Find the CFG starting at the given label.
void add (CFG *cfg)
Add a CFG to the CFG information structure.
void add (BasicBlock *bb)
Add the given BB to the CFG information.
void clear (void)
Remove all CFG stored in this CFG information.
Static Public Attributes
static Identifier< CFGInfo * > & ID = CFG_INFO
This property allows to get the CFG information from the current CFG is member of.
Private Attributes
WorkSpace * fw
genstruct::FragTable< CFG * > _cfgs
genstruct::FragTable< BasicBlock * > bbs
MemBlockMap< BasicBlock > map
Detailed Description
This allows storing all CFG available in a workspace.
Constructor & Destructor Documentation
otawa::CFGInfo::CFGInfo (WorkSpace * _fw)
Build a new CFGInfo.
Parameters
fw Workspace that the CFG information applies to.
References TRACE.
otawa::CFGInfo::~CFGInfo (void) virtual
Delete the CFG information contained in this program.
References clear(), and TRACE.
Member Function Documentation
void otawa::CFGInfo::add (CFG * cfg)
Add a CFG to the CFG information structure.
Parameters
cfg Added CFG.
References _cfgs.
Referenced by otawa::CFGBuilder::addCFG(), and otawa::CFGBuilder::buildCFG().
void otawa::CFGInfo::add (BasicBlock * bb)
Add the given BB to the CFG information.
Parameters
bb BB to add.
References otawa::BB_BOUNDS, bbs, otawa::CFG_INFO, and map.
void otawa::CFGInfo::clear (void)
Remove all CFG stored in this CFG information.
References _cfgs, otawa::cfgio::bb(), bbs, and otawa::cfgio::edge().
Referenced by ~CFGInfo().
CFG * otawa::CFGInfo::findCFG (Address addr)
Get a CFG from the address of its first instruction.
Parameters
addr Address of the first instruction.
Returns
Found CFG or null.
References otawa::cfgio::bb(), and map.
Referenced by findCFG(), otawa::WorkSpace::getStartCFG(), and otawa::CFGCollector::processWorkSpace().
CFG * otawa::CFGInfo::findCFG (Inst * inst)
Find the CFG starting by the basic block containing this instruction.
If the CFG does not exists, it is created and added.
The current algorithm does not allow detecting all CFG due to the irregular nature of the assembly code. Specially, function entries also used as loop head or as jump target of a function without continuation. Using this method, the user may inform the system about other existing CFG.
Parameters
inst Instruction to find the CFG starting with.
Returns
Matching CFG or null.
References otawa::ProgItem::address(), otawa::cfgio::bb(), findCFG(), and map.
CFG * otawa::CFGInfo::findCFG (const BasicBlock * bb)
Find the CFG starting at the given basic block.
Parameters
bb Basic block to look at.
Returns
Found CFG or this BB is not a CFG start.
References otawa::ENTRY.
CFG * otawa::CFGInfo::findCFG (String label)
Find the CFG starting at the given label.
Parameters
label Label of the first instruction of the CFG.
Returns
Matching CFG or null.
References findCFG(), otawa::Process::findInstAt(), fw, and otawa::WorkSpace::process().
Member Data Documentation
genstruct::FragTable<CFG *> otawa::CFGInfo::_cfgs private
Referenced by add(), and clear().
genstruct::FragTable<BasicBlock *> otawa::CFGInfo::bbs private
Referenced by add(), and clear().
WorkSpace* otawa::CFGInfo::fw private
Referenced by findCFG().
MemBlockMap<BasicBlock> otawa::CFGInfo::map private
Referenced by add(), and findCFG().
The documentation for this class was generated from the following files:
include/otawa/cfg/CFGInfo.h
src/prog/CFGInfo.cpp