Otawa: otawa::BasicBlock::InstIter Class Reference
otawa::BasicBlock::InstIter Class Reference
Iterator for instructions in the basic block.
#include <otawa/cfg/BasicBlock.h>
Public Member Functions
InstIter (void)
InstIter (const BasicBlock *bb)
bool ended (void) const
Inst * item (void) const
void next (void)
Private Member Functions
InstIter (Inst *i, Address t)
Private Attributes
otawa::Inst * inst
Address top
Friends
class Bundle
Detailed Description
Iterator for instructions in the basic block.
Constructor & Destructor Documentation
otawa::BasicBlock::InstIter::InstIter (void) inline
otawa::BasicBlock::InstIter::InstIter (const BasicBlock * bb) inline
References otawa::BasicBlock::firstInst(), otawa::BasicBlock::isEnd(), and otawa::BasicBlock::topAddress().
otawa::BasicBlock::InstIter::InstIter (Inst * i, Address t) inline private
Member Function Documentation
bool otawa::BasicBlock::InstIter::ended (void) const inline
Referenced by otawa::sem::BBIter::ended(), otawa::sim::BasicBlockDriver::nextInstruction(), and otawa::sim::BBPathDriver::nextInstruction().
Inst* otawa::BasicBlock::InstIter::item (void) const inline
Referenced by otawa::sim::BBPathDriver::nextInstruction().
void otawa::BasicBlock::InstIter::next (void) inline
Referenced by otawa::sim::BasicBlockDriver::nextInstruction(), and otawa::sim::BBPathDriver::nextInstruction().
Friends And Related Function Documentation
friend class Bundle friend
Member Data Documentation
otawa::Inst* otawa::BasicBlock::InstIter::inst private
Address otawa::BasicBlock::InstIter::top private
The documentation for this class was generated from the following file:
include/otawa/cfg/BasicBlock.h