Otawa: otawa::StartResource Class Reference
otawa::StartResource Class Reference
#include <otawa/parexegraph/Resource.h>
Public Types
enum resource_type_t {
BLOCK_START, STAGE, QUEUE, REG,
EXTERNAL_CONFLICT, INTERNAL_CONFLICT, RES_TYPE_NUM
}
typedef struct otawa::Resource::input_t input_t
Public Member Functions
StartResource (elm::String name, int index)
elm::String name ()
resource_type_t type ()
int index ()
void setIndex (int index)
Member Typedef Documentation
typedef struct otawa::Resource::input_t otawa::Resource::input_t inherited
Member Enumeration Documentation
enum otawa::Resource::resource_type_t inherited
Enumerator
BLOCK_START
STAGE
QUEUE
REG
EXTERNAL_CONFLICT
INTERNAL_CONFLICT
RES_TYPE_NUM
Constructor & Destructor Documentation
otawa::StartResource::StartResource (elm::String name, int index) inline
Member Function Documentation
index Resource::index (void) inline inherited
Returns
Index of the resource (i.e. its rank in the list of resources related to a ParExeGraph).
References otawa::Resource::_index.
Referenced by otawa::ParExeGraph::clearDelays(), otawa::ParExeGraph::delta(), otawa::ParExeGraph::propagate(), otawa::QueueResource::QueueResource(), and otawa::Resource::setIndex().
elm::String Resource::name (void) inline inherited
Returns
Name of the resource.
References otawa::Resource::_name.
void otawa::Resource::setIndex (int index) inline inherited
References otawa::Resource::index().
resource_type_t Resource::type (void) inline inherited
Returns
Type of the resource.
References otawa::Resource::_type.
Referenced by otawa::ParExeGraph::delta().
The documentation for this class was generated from the following file:
include/otawa/parexegraph/Resource.h