Otawa: otawa::ilp::cons Class Reference
otawa::ilp::cons Class Reference
ILP -- Integer Linear Programming
Encapsulation for ilp::Constraint pointers for {ilp} expr user-fiendly interface.
#include <otawa/ilp/expr.h>
Public Member Functions
cons (void)
cons (Constraint *cc)
cons operator+ (int t)
cons operator- (int t)
cons operator+ (const Term &t)
cons operator- (const Term &t)
cons operator+ (const Expression &e)
cons operator- (const Expression &e)
cons operator+= (int t)
cons operator-= (int t)
cons operator+= (const Term &t)
cons operator-= (const Term &t)
cons operator+= (const Expression &e)
cons operator-= (const Expression &e)
cons operator== (const Term &t)
cons operator== (const Expression &f)
cons operator<= (const Term &t)
cons operator<= (const Expression &f)
cons operator< (const Term &t)
cons operator< (const Expression &f)
cons operator>= (const Term &t)
cons operator>= (const Expression &f)
cons operator> (const Term &t)
cons operator> (const Expression &f)
Constraint * operator& (void) const
Constraint * operator-> (void) const
void free (void)
Private Member Functions
void set (Constraint::comparator_t comp)
Private Attributes
bool l
Constraint * c
Detailed Description
Encapsulation for ilp::Constraint pointers for {ilp} expr user-fiendly interface.
Constructor & Destructor Documentation
otawa::ilp::cons::cons (void) inline
otawa::ilp::cons::cons (Constraint * cc) inline
Member Function Documentation
void otawa::ilp::cons::free (void) inline
Constraint* otawa::ilp::cons::operator& (void) const inline
cons otawa::ilp::cons::operator+ (int t) inline
References otawa::ilp::Constraint::add().
Referenced by otawa::ilp::model::model_cons::operator%().
cons otawa::ilp::cons::operator+ (const Term & t) inline
References otawa::ilp::Constraint::add().
cons otawa::ilp::cons::operator+ (const Expression & e) inline
References otawa::ilp::Constraint::add().
cons otawa::ilp::cons::operator+= (int t) inline
References otawa::ilp::Constraint::add().
cons otawa::ilp::cons::operator+= (const Term & t) inline
References otawa::ilp::Constraint::add().
cons otawa::ilp::cons::operator+= (const Expression & e) inline
References otawa::ilp::Constraint::add().
cons otawa::ilp::cons::operator- (int t) inline
References otawa::ilp::Constraint::sub().
cons otawa::ilp::cons::operator- (const Term & t) inline
References otawa::ilp::Constraint::sub().
cons otawa::ilp::cons::operator- (const Expression & e) inline
References otawa::ilp::Constraint::sub().
cons otawa::ilp::cons::operator-= (int t) inline
References otawa::ilp::Constraint::sub().
cons otawa::ilp::cons::operator-= (const Term & t) inline
References otawa::ilp::Constraint::sub().
cons otawa::ilp::cons::operator-= (const Expression & e) inline
References otawa::ilp::Constraint::sub().
Constraint* otawa::ilp::cons::operator-> (void) const inline
cons otawa::ilp::cons::operator< (const Term & t) inline
References otawa::ilp::Constraint::LT.
cons otawa::ilp::cons::operator< (const Expression & f) inline
References otawa::ilp::Constraint::LT.
cons otawa::ilp::cons::operator<= (const Term & t) inline
References otawa::ilp::Constraint::LE.
cons otawa::ilp::cons::operator<= (const Expression & f) inline
References otawa::ilp::Constraint::LE.
cons otawa::ilp::cons::operator== (const Term & t) inline
References otawa::ilp::Constraint::EQ.
cons otawa::ilp::cons::operator== (const Expression & f) inline
References otawa::ilp::Constraint::EQ.
cons otawa::ilp::cons::operator> (const Term & t) inline
References otawa::ilp::Constraint::GT.
cons otawa::ilp::cons::operator> (const Expression & f) inline
References otawa::ilp::Constraint::GT.
cons otawa::ilp::cons::operator>= (const Term & t) inline
References otawa::ilp::Constraint::GE.
cons otawa::ilp::cons::operator>= (const Expression & f) inline
References otawa::ilp::Constraint::GE.
void otawa::ilp::cons::set (Constraint::comparator_t comp) inline private
Member Data Documentation
Constraint* otawa::ilp::cons::c private
bool otawa::ilp::cons::l private
The documentation for this class was generated from the following file:
include/otawa/ilp/expr.h