Otawa: otawa::LBlockSet Class Reference
otawa::LBlockSet Class Reference
This class represents the list of l-blocks of a task for a chosen cache row.
#include <otawa/cache/LBlockSet.h>
Classes
class Iterator
Public Member Functions
LBlockSet (int row, const hard::Cache *cache)
Build a l-block set.
int add (LBlock *node)
Add a new l-block.
int count (void)
Get a number for a new l-block in the set.
int cacheBlockCount (void)
Get the internal counter of l-block number (only used internally).
LBlock * lblock (int i)
Get the l-block with the given index.
int set (void)
Get the set number of the l-blocks in the cache.
const hard::Cache * cache (void) const
int line (void)
Private Attributes
int linenumber
elm::genstruct::Vector< LBlock * > listelbc
int cblock_count
const hard::Cache * _cache
Friends
class CCGDFA
Detailed Description
This class represents the list of l-blocks of a task for a chosen cache row.
It is useful to perform analysis on l-blocks. It is accessible through the property otawa::LBLOCKS.
Constructor & Destructor Documentation
otawa::LBlockSet::LBlockSet (int line, const hard::Cache * cache)
Build a l-block set.
Parameters
line Cache row of the l-block set.
Member Function Documentation
int otawa::LBlockSet::add (LBlock * lblock)
Add a new l-block.
Parameters
lblock l-block to add.
References otawa::LBlock::cacheBlock(), cblock_count, and listelbc.
const hard::Cache* otawa::LBlockSet::cache (void) const inline
int otawa::LBlockSet::cacheBlockCount (void) inline
Get the internal counter of l-block number (only used internally).
Referenced by otawa::LBlockBuilder::addLBlock(), otawa::ACSMayBuilder::processLBlockSet(), otawa::EdgeACSBuilder::processLBlockSet(), otawa::ACSBuilder::processLBlockSet(), and otawa::LinkedBlocksDetector::processWorkSpace().
int otawa::LBlockSet::count (void) inline
Get a number for a new l-block in the set.
Used internally to build l-blocks.
Returns
New l-block number.
Get the count of l-blocks in the set.
Returns
Count of l-blocks.
Referenced by otawa::cat::CATBuilder::buildLBLOCKSET(), otawa::EdgeCAT2Builder::processLBlockSet(), otawa::ACSMayBuilder::processLBlockSet(), otawa::CAT2Builder::processLBlockSet(), otawa::cat::CATBuilder::processLBlockSet(), otawa::EdgeCAT2ConstraintBuilder::processWorkSpace(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), otawa::LinkedBlocksDetector::processWorkSpace(), otawa::cat::CATBuilder::setCATEGORISATION(), and otawa::cat::CATBuilder::worst().
LBlock * otawa::LBlockSet::lblock (int i) inline
Get the l-block with the given index.
Parameters
i Index of the looked block.
Returns
L-block matching the index.
Referenced by otawa::cat::CATBuilder::setCATEGORISATION(), and otawa::cat::CATBuilder::worst().
int otawa::LBlockSet::line (void) inline
Referenced by otawa::operator<<(), otawa::EdgeCAT2Builder::processLBlockSet(), otawa::ACSMayBuilder::processLBlockSet(), otawa::EdgeACSBuilder::processLBlockSet(), otawa::CAT2Builder::processLBlockSet(), and otawa::ACSBuilder::processLBlockSet().
int otawa::LBlockSet::set (void) inline
Get the set number of the l-blocks in the cache.
Returns
Cache set number.
Friends And Related Function Documentation
friend class CCGDFA friend
Member Data Documentation
const hard::Cache* otawa::LBlockSet::_cache private
int otawa::LBlockSet::cblock_count private
Referenced by add().
int otawa::LBlockSet::linenumber private
elm::genstruct::Vector<LBlock *> otawa::LBlockSet::listelbc private
Referenced by add().
The documentation for this class was generated from the following files:
include/otawa/cache/LBlockSet.h
src/prog/cache_LBlockSet.cpp