Otawa: otawa::dcache::MAYProblem Class Reference
otawa::dcache::MAYProblem Class Reference
#include <otawa/dcache/ACSMayBuilder.h>
Classes
class Domain
Public Member Functions
MAYProblem (const BlockCollection &coll, WorkSpace *_fw, const hard::Cache *_cache)
~MAYProblem (void)
const Domain & bottom (void) const
const Domain & entry (void) const
void lub (Domain &a, const Domain &b) const
void assign (Domain &a, const Domain &b) const
bool equals (const Domain &a, const Domain &b) const
void update (Domain &out, const Domain &in, BasicBlock *bb)
Produces the output MAY cache state with the execution of given BB.
void update (Domain &s, const BlockAccess &access)
Update the state according to the given block access.
void enterContext (Domain &dom, BasicBlock *header, util::hai_context_t ctx)
void leaveContext (Domain &dom, BasicBlock *header, util::hai_context_t ctx)
Public Attributes
Domain callstate
Private Attributes
const BlockCollection & coll
WorkSpace * fw
int line
const hard::Cache * cache
Domain bot
Domain ent
Constructor & Destructor Documentation
MAYProblem::MAYProblem (const BlockCollection & coll, WorkSpace * _fw, const hard::Cache * _cache)
References otawa::dcache::ACS::empty(), and ent.
MAYProblem::~MAYProblem (void)
Member Function Documentation
void otawa::dcache::MAYProblem::assign (Domain & a, const Domain & b) const inline
Referenced by update().
const MAYProblem::Domain & MAYProblem::bottom (void) const
References bot.
void otawa::dcache::MAYProblem::enterContext (Domain & dom, BasicBlock * header, util::hai_context_t ctx) inline
const MAYProblem::Domain & MAYProblem::entry (void) const
References ent.
bool otawa::dcache::MAYProblem::equals (const Domain & a, const Domain & b) const inline
References otawa::cfgio::bb(), and otawa::dcache::ACS::equals().
void otawa::dcache::MAYProblem::leaveContext (Domain & dom, BasicBlock * header, util::hai_context_t ctx) inline
References otawa::hard::operator<<().
void otawa::dcache::MAYProblem::lub (Domain & a, const Domain & b) const inline
References otawa::dcache::MAYProblem::Domain::lub().
void MAYProblem::update (Domain & out, const Domain & in, BasicBlock * bb)
Produces the output MAY cache state with the execution of given BB.
Parameters
out Output state.
in Input state.
bb BB to to analyze.
References assign(), and otawa::dcache::DATA_BLOCKS.
void MAYProblem::update (Domain & s, const BlockAccess & access)
Update the state according to the given block access.
Parameters
s State to update.
access Cache access.
References otawa::dcache::BlockAccess::ANY, otawa::dcache::BlockAccess::BLOCK, otawa::dcache::BlockAccess::block(), otawa::dcache::Block::index(), otawa::dcache::MAYProblem::Domain::inject(), otawa::dcache::BlockAccess::kind(), line, otawa::dcache::BlockAccess::RANGE, and otawa::dcache::Block::set().
Member Data Documentation
Domain otawa::dcache::MAYProblem::bot private
Referenced by bottom().
const hard::Cache* otawa::dcache::MAYProblem::cache private
Domain otawa::dcache::MAYProblem::callstate
const BlockCollection& otawa::dcache::MAYProblem::coll private
Domain otawa::dcache::MAYProblem::ent private
Referenced by entry(), and MAYProblem().
WorkSpace* otawa::dcache::MAYProblem::fw private
int otawa::dcache::MAYProblem::line private
Referenced by update().
The documentation for this class was generated from the following files:
include/otawa/dcache/ACSMayBuilder.h
src/dcache/dcache_ACSMayBuilder.cpp