Otawa: otawa::script::ScriptItem Class Reference
otawa::script::ScriptItem Class Reference
Scripts
These objects represents the item of the configuration of a script.
#include <otawa/script/Script.h>
Inherited by otawa::script::BoolItem, otawa::script::EnumItem, and otawa::script::StringItem.
Public Types
enum type_t {
T_BOOL = 0, T_INT = 1, T_STRING = 2, T_RANGE = 3,
T_ENUM = 4, T_MAX = 5
}
Public Member Functions
virtual ~ScriptItem (void)
virtual string makeParam (const string &value)
Called to generate the string of parameter value before passing it to the XSLT processor.
Static Public Member Functions
static ScriptItem * parse (xom::Element &elt)
Parse an XML element to build the matching script item.
Public Attributes
string name
type_t type
string deflt
string label
string help
bool multi
Static Public Attributes
static cstring type_labels []
Label matching the scripts (as passed in XML item elements).
Protected Member Functions
ScriptItem (type_t t, xom::Element &elt)
Protected constructor.
Detailed Description
These objects represents the item of the configuration of a script.
Member Enumeration Documentation
enum otawa::script::ScriptItem::type_t
Enumerator
T_BOOL
T_INT
T_STRING
T_RANGE
T_ENUM
T_MAX
Constructor & Destructor Documentation
otawa::script::ScriptItem::~ScriptItem (void) virtual
References deflt, makeParam(), ScriptItem(), T_BOOL, T_ENUM, and T_STRING.
otawa::script::ScriptItem::ScriptItem (type_t t, xom::Element & elt) protected
Protected constructor.
References deflt, help, label, multi, and name.
Referenced by parse(), and ~ScriptItem().
Member Function Documentation
string otawa::script::ScriptItem::makeParam (const string & value) virtual
Called to generate the string of parameter value before passing it to the XSLT processor.
The result must be an XPath valid expression.
Parameters
value Value of the parameter.
Returns
XPath expression representing the parameter value.
Referenced by ~ScriptItem().
ScriptItem * otawa::script::ScriptItem::parse (xom::Element & elt) static
Parse an XML element to build the matching script item.
Parameters
elt Element to parse.
Returns
Built element.
Exceptions
ParseError If there is an error.
References otawa::p::end, otawa::script::Script::reg, ScriptItem(), T_MAX, and type_labels.
Referenced by otawa::script::Script::work().
Member Data Documentation
string otawa::script::ScriptItem::deflt
Referenced by ScriptItem(), and ~ScriptItem().
string otawa::script::ScriptItem::help
Referenced by ScriptItem().
string otawa::script::ScriptItem::label
Referenced by ScriptItem().
bool otawa::script::ScriptItem::multi
Referenced by ScriptItem().
string otawa::script::ScriptItem::name
Referenced by ScriptItem(), and otawa::script::Script::work().
type_t otawa::script::ScriptItem::type
cstring otawa::script::ScriptItem::type_labels static
Initial value:
= {
        "bool",
        "int",
        "string",
        "range",
        "enum",
        ""
}
Label matching the scripts (as passed in XML item elements).
Referenced by parse().
The documentation for this class was generated from the following files:
include/otawa/script/Script.h
src/prog/script_Script.cpp