Otawa: otawa::ParamExeGraph::RegResource Class Reference
otawa::ParamExeGraph::RegResource Class Reference
#include <otawa/exegraph/ParamExeGraph.h>
Classes
class UsingInstIterator
Public Member Functions
RegResource (elm::String name, otawa::hard::RegBank *reg_bank, int reg_index, int index, int offset)
otawa::hard::RegBank * regBank ()
int regIndex ()
void addUsingInst (ExeInst< ParamExeNode > *inst)
elm::String name ()
resource_type_t type ()
int index ()
int offset ()
Private Attributes
elm::genstruct::Vector< ExeInst< ParamExeNode > * > _using_instructions
otawa::hard::RegBank * _reg_bank
int _reg_index
Constructor & Destructor Documentation
otawa::ParamExeGraph::RegResource::RegResource (elm::String name, otawa::hard::RegBank * reg_bank, int reg_index, int index, int offset) inline
Member Function Documentation
void otawa::ParamExeGraph::RegResource::addUsingInst (ExeInst< ParamExeNode > * inst) inline
Referenced by otawa::ParamExeGraph::ParamExeGraph().
int otawa::ParamExeGraph::Resource::index (void) inline inherited
Referenced by otawa::ParamExeGraph::cost(), and otawa::ParamExeGraph::Delta().
elm::String otawa::ParamExeGraph::Resource::name (void) inline inherited
Referenced by otawa::ParamExeGraph::cost(), and otawa::ParamExeGraph::Delta().
int otawa::ParamExeGraph::Resource::offset (void) inline inherited
Referenced by otawa::ParamExeGraph::Delta().
otawa::hard::RegBank* otawa::ParamExeGraph::RegResource::regBank () inline
int otawa::ParamExeGraph::RegResource::regIndex () inline
resource_type_t otawa::ParamExeGraph::Resource::type (void) inline inherited
Referenced by otawa::ParamExeGraph::Delta().
Member Data Documentation
otawa::hard::RegBank* otawa::ParamExeGraph::RegResource::_reg_bank private
int otawa::ParamExeGraph::RegResource::_reg_index private
elm::genstruct::Vector<ExeInst<ParamExeNode> *> otawa::ParamExeGraph::RegResource::_using_instructions private
The documentation for this class was generated from the following file:
include/otawa/exegraph/ParamExeGraph.h