Otawa: otawa::ProcessException Class Reference
otawa::ProcessException Class Reference
An exception generated from a process.
#include <otawa/prog/Process.h>
Public Member Functions
ProcessException (Process *process)
ProcessException (Process *process, const string &message)
Build a process exception with a message.
Process * process (void) const
Get the process where the exception was thrown.
virtual String message (void)
Private Attributes
Process * proc
Detailed Description
An exception generated from a process.
Constructor & Destructor Documentation
otawa::ProcessException::ProcessException (Process * process) inline
otawa::ProcessException::ProcessException (Process * process, const string & message) inline
Build a process exception with a message.
Parameters
process Current process.
message Exception message.
Member Function Documentation
String otawa::ProcessException::message (void) virtual
Reimplemented in otawa::OutOfSegmentException, and otawa::UnsupportedFeatureException.
References name, and otawa::Process::program().
Referenced by otawa::VarTextDecoder::processEntry().
Process * otawa::ProcessException::process (void) const inline
Get the process where the exception was thrown.
Returns
Exception process.
References proc().
Member Data Documentation
Process* otawa::ProcessException::proc private
The documentation for this class was generated from the following files:
include/otawa/prog/Process.h
src/prog/Process.cpp