Otawa: otawa::CFG::BBIterator Class Reference
otawa::CFG::BBIterator Class Reference
#include <otawa/cfg/CFG.h>
Public Member Functions
BBIterator (CFG *cfg)
BBIterator (const BBIterator &iter)
Constructor & Destructor Documentation
otawa::CFG::BBIterator::BBIterator (CFG * cfg) inline
otawa::CFG::BBIterator::BBIterator (const BBIterator & iter) inline
References otawa::CFG::address(), otawa::CFG::CFG(), otawa::CFG::entry(), otawa::CFG::format(), otawa::CFG::label(), otawa::CFG::name(), otawa::CFG::number(), otawa::CFG::segment(), and otawa::CFG::~CFG().
The documentation for this class was generated from the following file:
include/otawa/cfg/CFG.h