Otawa: otawa::BranchProblem Class Reference
otawa::BranchProblem Class Reference
#include <otawa/branch/BranchProblem.h>
Classes
class Domain
Public Member Functions
BranchProblem (const int _size, WorkSpace *_fw, const int _A, const int _row)
const Domain & bottom (void) const
const Domain & entry (void) const
void lub (Domain &a, const Domain &b) const
void assign (Domain &a, const Domain &b) const
bool equals (const Domain &a, const Domain &b) const
void update (Domain &out, const Domain &in, BasicBlock *bb)
void updateLBlock (Domain &acs, LBlock *lblock)
void enterContext (Domain &dom, BasicBlock *header, util::hai_context_t ctx)
void leaveContext (Domain &dom, BasicBlock *header, util::hai_context_t ctx)
Private Attributes
MUSTBranch mustProb
PERSBranch persProb
MAYBranch mayProb
WorkSpace * fw
int row
Domain bot
Domain ent
Constructor & Destructor Documentation
otawa::BranchProblem::BranchProblem (const int _size, WorkSpace * _fw, const int _A, const int _row)
References otawa::MUSTBranch::assign(), otawa::PERSBranch::assign(), bot, otawa::MUSTBranch::bottom(), otawa::PERSBranch::bottom(), ent, otawa::MUSTBranch::entry(), otawa::PERSBranch::entry(), otawa::BranchProblem::Domain::must, mustProb, otawa::BranchProblem::Domain::pers, and persProb.
Member Function Documentation
void otawa::BranchProblem::assign (Domain & a, const Domain & b) const inline
Referenced by update().
const BranchProblem::Domain & otawa::BranchProblem::bottom (void) const
References bot.
void otawa::BranchProblem::enterContext (Domain & dom, BasicBlock * header, util::hai_context_t ctx) inline
References otawa::MUSTBranch::enterContext(), otawa::MAYBranch::enterContext(), otawa::PERSBranch::enterContext(), otawa::BranchProblem::Domain::may, otawa::BranchProblem::Domain::must, and otawa::BranchProblem::Domain::pers.
const BranchProblem::Domain & otawa::BranchProblem::entry (void) const
References ent.
bool otawa::BranchProblem::equals (const Domain & a, const Domain & b) const inline
References otawa::cfgio::bb(), otawa::BranchProblem::Domain::equals(), and otawa::MUSTBranch::update().
void otawa::BranchProblem::leaveContext (Domain & dom, BasicBlock * header, util::hai_context_t ctx) inline
References otawa::MUSTBranch::leaveContext(), otawa::MAYBranch::leaveContext(), otawa::PERSBranch::leaveContext(), otawa::BranchProblem::Domain::may, otawa::BranchProblem::Domain::must, and otawa::BranchProblem::Domain::pers.
void otawa::BranchProblem::lub (Domain & a, const Domain & b) const inline
References otawa::BranchProblem::Domain::lub().
void otawa::BranchProblem::update (Domain & out, const Domain & in, BasicBlock * bb)
References otawa::ProgItem::address(), assign(), otawa::hard::BHT_CONFIG, otawa::branch::COND_NUMBER, fw, otawa::BranchProblem::Domain::inject(), otawa::BasicBlock::lastInst(), and row.
void otawa::BranchProblem::updateLBlock (Domain & acs, LBlock * lblock)
Member Data Documentation
Domain otawa::BranchProblem::bot private
Referenced by bottom(), and BranchProblem().
Domain otawa::BranchProblem::ent private
Referenced by BranchProblem(), and entry().
WorkSpace* otawa::BranchProblem::fw private
Referenced by update().
MAYBranch otawa::BranchProblem::mayProb private
MUSTBranch otawa::BranchProblem::mustProb private
Referenced by BranchProblem().
PERSBranch otawa::BranchProblem::persProb private
Referenced by BranchProblem().
int otawa::BranchProblem::row private
Referenced by update().
The documentation for this class was generated from the following files:
include/otawa/branch/BranchProblem.h
src/branch/branch_BranchProblem.cpp