Otawa: otawa::LBlockBuilder Class Reference
otawa::LBlockBuilder Class Reference
This processor builds the list of l-blocks for each lines of instruction cache and stores it in the CFG.
#include <otawa/cache/LBlockBuilder.h>
Public Types
enum log_level_t {
LOG_NONE = 0, LOG_PROC = 1, LOG_FILE = 2, LOG_DEPS = LOG_FILE,
LOG_FUN = 3, LOG_CFG = LOG_FUN, LOG_BLOCK = 4, LOG_BB = LOG_BLOCK,
LOG_INST = 5
}
typedef enum otawa::Monitor::log_level_t log_level_t
Public Member Functions
LBlockBuilder (AbstractRegistration &r=reg)
Build a new l-block builder.
virtual void configure (const PropList &props)
Configure the current processor.
elm::String name (void) const
elm::Version version (void) const
void process (WorkSpace *ws, const PropList &props=PropList::EMPTY)
Execute the code processor on the given framework.
WorkSpace * workspace (void)
Get the current workspace.
bool isVerbose (void) const
Test if the verbosity is activated.
bool logFor (log_level_t tested) const
Test if the given log level is activated or not.
log_level_t logLevel (void) const
Public Attributes
elm::io::Output out
Provide a stream to perform output for the user.
elm::io::Output log
Provide a stream to perform log output.
Static Public Attributes
static p::declare reg
static Identifier< PropList * > STATS
This property identifiers is used to pass a property list to the processor that will be used to store statistics about the performed work.
static Identifier< bool > TIMED
If the value of the associated property is true (default to false), time statistics will also be collected with other processor statistics.
static Identifier< bool > RECURSIVE
static Identifier< Progress * > PROGRESS
Install.
static Identifier< bool > COLLECT_STATS
This property allows to activate collection of statistics for the work of the current processor.
static Identifier< elm::io::OutStream * > & OUTPUT = otawa::OUTPUT
This property identifier is used for setting the output stream used by the processor to write results.
static Identifier< elm::io::OutStream * > & LOG = otawa::LOG
This property identifier is used for setting the log stream used by the processor to write messages (information, warning, error).
static Identifier< bool > & VERBOSE = otawa::VERBOSE
This property activates the verbose mode of the processor: information about the processor work will be displayed.
static Identifier< log_level_t > & LOG_LEVEL = otawa::LOG_LEVEL
Property passed in the configuration property list of a processor to select the log level between LOG_PROC, LOG_CFG or LOG_BB.
static Identifier< elm::system::time_t > RUNTIME
This property identifier is used to store in the statistics of a processor the overall run time of the processor work.
static Monitor & null = __null_mon
Monitor that output nothing.
Protected Member Functions
virtual void processBB (WorkSpace *fw, CFG *cfg, BasicBlock *bb)
Perform the work of the given basic block.
virtual void cleanup (WorkSpace *fw)
This method is called after the end of the processor analysis to let it do some clean up.
virtual void setup (WorkSpace *fw)
This method is called before an anlysis to let the processor do some initialization.
virtual void processCFG (WorkSpace *ws, CFG *cfg)
See CFGProcessor::processCFG()
virtual void cleanupCFG (WorkSpace *ws, CFG *cfg)
This function may be overridden by a subclass to provide custom cleanup for a CFG.
virtual void cleanupBB (WorkSpace *ws, CFG *cfg, BasicBlock *bb)
When the function doCleanup() is called, this function is called for each basic block of the task.
template<class T >
void trackBB (const AbstractFeature &feature, const Identifier< T * > &id)
Track and delete the content of the given identifier on each basic block.
template<class T >
void trackBB (const AbstractFeature &feature, const Identifier< T > &id)
Track and remove properties put on basic blocks.
virtual void processWorkSpace (WorkSpace *fw)
Process the given framework.
void doCleanUp (void)
Trigger associated with CFG.
string str (const Address &address)
Transform an address to a smart string, that is, if a source line is available, transform it to "source_file:source_line", if the CFG has a label, it gives "label + 0xoffset", else return the address.
string str (const Address &base, const Address &address)
Transform an address to a smart string, that is, if a source line is available, transform it to "source_file:source_line", if the CFG has a label, it gives "label + 0xoffset", else return the address.
CFG * cfg (void) const
Get the current CFG.
bool isTimed (void) const
Test if the timed mode is activated (recording of timings in the statistics).
bool recordsStats (void) const
Test if the statictics mode is activated.
bool isAllocated (void) const
bool isPrepared (void) const
bool isCollectingStats (void) const
void require (const AbstractFeature &feature)
Usually called from a processor constructor, this method records a required feature for the work of the current processor.
void provide (const AbstractFeature &feature)
Usually called from a processor constructor, this method records a feature provided by the work of the current processor.
void invalidate (const AbstractFeature &feature)
Usually called from a processor constructor, this method records a feature invalidated by the work of the current processor.
void use (const AbstractFeature &feature)
Usually called from a processor constructor, this method records a feature as used by the work of the current processor.
void warn (const String &message)
Display a warning.
WorkSpace * workspace (void) const
Get the current workspace.
Progress & progress (void)
Get the current progress handler.
void recordStat (const AbstractFeature &feature, StatCollector *collector)
Add a statistics collector to the current workspace collection.
void addCleaner (const AbstractFeature &feature, Cleaner *cleaner)
Add a cleaner for the given feature.
template<class T >
void addRemover (const AbstractFeature &feature, const Ref< T, Identifier< T > > &ref)
template<class T >
void addDeletor (const AbstractFeature &feature, const Ref< T *, Identifier< T * > > &ref)
virtual void prepare (WorkSpace *ws)
This method called to let the processor customize its requirements according to some generic feature.
virtual void collectStats (WorkSpace *ws)
This method is invoked if the user has required to collect statistics about the processor.
virtual void processFrameWork (WorkSpace *fw)
Process the given workspace.
template<class T >
T * track (const AbstractFeature &feature, T *object)
template<class T >
void track (const AbstractFeature &feature, const Ref< T *, Identifier< T * > > &ref)
Track the release of an allocated object assigned to an identifier relatively to the given feature.
template<class T >
void track (const AbstractFeature &feature, const Ref< T *, const Identifier< T * > > &ref)
Track the release of an allocated object assigned to an identifier relatively to the given feature.
virtual void requireDyn (WorkSpace *ws, const PropList &props)
Method called after registration requirements to support dynamic requirements.
void setWorkspace (WorkSpace *workspace)
Set the current workspace.
Protected Attributes
PropList * stats
t::uint32 flags
Contains various bit flags.
Static Protected Attributes
static const t::uint32 IS_TIMED = 0x01 << CUSTOM_SHIFT
static const t::uint32 IS_ALLOCATED = 0x04 << CUSTOM_SHIFT
static const t::uint32 IS_PREPARED = 0x08 << CUSTOM_SHIFT
static const t::uint32 IS_COLLECTING = 0x10 << CUSTOM_SHIFT
static const t::uint32 IS_VERBOSE = 0x01
static const t::uint32 CUSTOM_SHIFT = 16
Private Member Functions
void addLBlock (BasicBlock *bb, Inst *inst, int &index, genstruct::AllocatedTable< LBlock * > *lblocks)
Add an lblock to the lblock lists.
Private Attributes
LBlockSet ** lbsets
const hard::Cache * cache
const hard::Memory * mem
genstruct::HashTable< ot::mask, int > block_map
Detailed Description
This processor builds the list of l-blocks for each lines of instruction cache and stores it in the CFG.
Required Features
INVOLVED_CFGS_FEATURE
require(hard::CACHE_CONFIGURATION_FEATURE)
require(hard::MEMORY_FEATURE)
Provided Features
COLLECTED_LBLOCKS_FEATURE
Member Typedef Documentation
typedef enum otawa::Monitor::log_level_t otawa::Monitor::log_level_t inherited
Member Enumeration Documentation
enum otawa::Monitor::log_level_t inherited
Enumerator
LOG_NONE
LOG_PROC
LOG_FILE
LOG_DEPS
LOG_FUN
LOG_CFG
LOG_BLOCK
LOG_BB
LOG_INST
Constructor & Destructor Documentation
otawa::LBlockBuilder::LBlockBuilder (AbstractRegistration & r = reg)
Build a new l-block builder.
Member Function Documentation
void otawa::Processor::addCleaner (const AbstractFeature & feature, Cleaner * cleaner) inline protected inherited
Add a cleaner for the given feature.
A cleaner is an object with a virtual destructor that is called when the associated feature is removed: this let the processor to release and clean up the resources it allocated to implement the provided features.
Parameters
feature Feature the cleaner apply to.
cleaner Cleaner to add.
Referenced by otawa::DelayedBuilder::cleanup(), otawa::StackAnalysis::cleanup(), otawa::Dominance::processCFG(), otawa::clp::Analysis::processWorkSpace(), and otawa::Processor::recordStat().
template<class T > void otawa::Processor::addDeletor (const AbstractFeature & feature, const Ref< T *, Identifier< T * > > & ref) inline protected inherited
Referenced by otawa::Virtualizer::cleanup().
void otawa::LBlockBuilder::addLBlock (BasicBlock * bb, Inst * inst, int & index, genstruct::AllocatedTable< LBlock * > * lblocks) private
Add an lblock to the lblock lists.
Parameters
bb Basic block containing the l-block.
inst Starting instruction of L-Block to create..
index Index in the BB lblock table. BB lblock table.
References otawa::ProgItem::address(), otawa::BasicBlock::address(), otawa::hard::Cache::block(), block_map, otawa::hard::Cache::blockMask(), cache, otawa::LBlockSet::cacheBlockCount(), otawa::hard::Memory::get(), otawa::hard::Bank::isCached(), otawa::Monitor::isVerbose(), lbsets, otawa::Monitor::log, mem, otawa::hard::Cache::round(), otawa::hard::Cache::set(), and otawa::BasicBlock::size().
Referenced by processBB().
template<class T > void otawa::Processor::addRemover (const AbstractFeature & feature, const Ref< T, Identifier< T > > & ref) inline protected inherited
Referenced by otawa::Virtualizer::cleanup().
CFG * otawa::CFGProcessor::cfg (void) const inline protected inherited
Get the current CFG.
Returns
Current CFG.
References otawa::CFGProcessor::_cfg, and otawa::CFGProcessor::init().
Referenced by otawa::BBCleaner::clean(), otawa::DelayedBuilder::fix(), otawa::PSTBuilder::getVCFG(), otawa::ContextualProcessor::processCFG(), otawa::DelayedBuilder::processWorkSpace(), otawa::CFGProcessor::processWorkSpace(), and otawa::bpred::BPredProcessor::setBit().
void otawa::LBlockBuilder::cleanup (WorkSpace * ws) protected virtual
This method is called after the end of the processor analysis to let it do some clean up.
Parameters
ws Workspace to work on.
Reimplemented from otawa::Processor.
References cache, lbsets, and otawa::hard::Cache::rowCount().
void otawa::BBProcessor::cleanupBB (WorkSpace * ws, CFG * cfg, BasicBlock * bb) protected virtual inherited
When the function doCleanup() is called, this function is called for each basic block of the task.
As a default do nothing.
Warning
If you override the cleanupCFG() function, do not forget to perform a call to the CFGProcessor original version.
Parameters
ws Current workspace.
cfg Current CFG.
bb Current BB.
Referenced by otawa::BBProcessor::cleanupCFG().
void otawa::BBProcessor::cleanupCFG (WorkSpace * ws, CFG * cfg) protected virtual inherited
This function may be overridden by a subclass to provide custom cleanup for a CFG.
It is called for each CFG of the task when doCleanUp() is called. As a default, do nothing.
Parameters
ws Current workspace.
cfg Current CFG.
Reimplemented from otawa::CFGProcessor.
References otawa::cfgio::bb(), and otawa::BBProcessor::cleanupBB().
void otawa::Processor::collectStats (WorkSpace * ws) protected virtual inherited
This method is invoked if the user has required to collect statistics about the processor.
In its default implementation, this method does nothing but it may be customized if the current implementation provides statistics. It is called after the main computation of the processor.
Statistics must be objects inheriting from the class StatCollector and recorded with method recordStat().
Parameters
ws Current workspace.
Reimplemented in otawa::dcache::CatConstraintBuilder, otawa::ipet::WCETComputation, and otawa::CAT2OnlyConstraintBuilder.
Referenced by otawa::Processor::process().
void otawa::CFGProcessor::configure (const PropList & props) virtual inherited
Configure the current processor.
Parameters
props Configuration properties.
Reimplemented from otawa::Processor.
Reimplemented in otawa::GraphBBTime< G >, otawa::GraphBBTime< ParExeGraph >, otawa::AccessedAddressFromStack, otawa::tsim::Delta, otawa::ipet::ConstraintLoader, otawa::bpred::BPredProcessor, otawa::display::CFGOutput, otawa::ipet::VarAssignment, otawa::EdgeCAT2Builder, otawa::ipet::BasicConstraintsBuilder, otawa::etime::StandardEventBuilder, otawa::dcache::BlockBuilder, otawa::CAT2Builder, otawa::branch::OnlyConsBuilder, otawa::BBRatioDisplayer, otawa::etime::EdgeTimeBuilder, otawa::ipet::FlowFactConstraintBuilder, otawa::CFGSaver, otawa::CFGChecker, otawa::ipet::TrivialBBTime, otawa::CFGNormalizer, and otawa::ipet::CachePenaltiesObjectFunctionBuilder.
References otawa::Processor::configure(), and otawa::CFGProcessor::init().
Referenced by otawa::CFGProcessor::CFGProcessor(), otawa::ipet::CachePenaltiesObjectFunctionBuilder::configure(), otawa::CFGNormalizer::configure(), otawa::ipet::TrivialBBTime::configure(), otawa::CFGChecker::configure(), otawa::ipet::FlowFactConstraintBuilder::configure(), otawa::branch::OnlyConsBuilder::configure(), otawa::BBRatioDisplayer::configure(), otawa::CAT2Builder::configure(), otawa::dcache::BlockBuilder::configure(), otawa::etime::StandardEventBuilder::configure(), otawa::EdgeCAT2Builder::configure(), otawa::ipet::BasicConstraintsBuilder::configure(), otawa::ipet::VarAssignment::configure(), otawa::display::CFGOutput::configure(), otawa::bpred::BPredProcessor::configure(), otawa::ipet::ConstraintLoader::configure(), otawa::tsim::Delta::configure(), otawa::GraphBBTime< G >::configure(), and otawa::stack::Manager::updatePath().
void otawa::CFGProcessor::doCleanUp (void) protected inherited
Trigger associated with CFG.
For each CFG, perform a call to cleanupCFG() that may be customized by a subclass.
References otawa::CFGProcessor::cleanupCFG(), otawa::CFGCollection::count(), otawa::ENTRY_CFG, otawa::CFGCollection::get(), otawa::INVOLVED_CFGS, otawa::PROCESSED_CFG, and otawa::Processor::workspace().
void otawa::Processor::invalidate (const AbstractFeature & feature) protected inherited
Usually called from a processor constructor, this method records a feature invalidated by the work of the current processor.
Parameters
feature Invalidated feature.
References otawa::Processor::_reg, otawa::AbstractRegistration::features, otawa::Monitor::flags, otawa::FeatureUsage::invalidate, otawa::Processor::IS_ALLOCATED, otawa::Processor::isAllocated(), and otawa::Processor::isPrepared().
Referenced by otawa::LoopReductor::LoopReductor().
bool otawa::Processor::isAllocated (void) const inline protected inherited
Referenced by otawa::Processor::invalidate(), otawa::Processor::provide(), otawa::Processor::require(), and otawa::Processor::use().
bool otawa::Processor::isCollectingStats (void) const inline protected inherited
References otawa::p::invalidate, otawa::p::provide, otawa::p::require, and otawa::p::use.
Referenced by otawa::Processor::process(), and otawa::Processor::recordStat().
bool otawa::Processor::isPrepared (void) const inline protected inherited
Referenced by otawa::Processor::invalidate(), otawa::Processor::process(), otawa::Processor::provide(), otawa::Processor::require(), and otawa::Processor::use().
bool otawa::Processor::isTimed (void) const inline protected inherited
Test if the timed mode is activated (recording of timings in the statistics).
Returns
True if timed mode is activated, false else.
Note
If statistics are not activated, this method returns ever false.
Referenced by otawa::Processor::process().
bool otawa::Monitor::isVerbose (void) const inline inherited
Test if the verbosity is activated.
Returns
True if verbosity is activated, false else.
Referenced by otawa::ccg::LBlockBuilder::addLBlock(), addLBlock(), otawa::GraphBBTime< G >::analyzePathContext(), otawa::etime::EdgeTimeBuilder::applyFloppySplit(), otawa::etime::EdgeTimeBuilder::applyStrictSplit(), otawa::etime::EdgeTimeBuilder::applyWeightedSplit(), otawa::etime::EdgeTimeBuilder::makeSplit(), otawa::GraphBBTime< G >::processBB(), otawa::etime::EdgeTimeBuilder::processSequence(), and otawa::dcache::BlockBuilder::setup().
bool otawa::Monitor::logFor (log_level_t tested) const inline inherited
Test if the given log level is activated or not.
Parameters
tested Tested log level.
Returns
True if the log level is activated, false else.
Referenced by otawa::CFGBuilder::addCFG(), otawa::ipet::ConstraintLoader::addConstraint(), otawa::PFGBuilder::addFunction(), otawa::FlowFactLoader::addressOf(), otawa::etime::EdgeTimeBuilder::applyWeightedSplit(), otawa::DelayedBuilder::buildBB(), otawa::CFGBuilder::buildCFG(), otawa::DelayedBuilder::buildEdges(), otawa::branch::BranchBuilder::categorize(), otawa::ipet::FlowFactLoader::cleanup(), otawa::dcache::CATBuilder::cleanup(), otawa::DelayedBuilder::cloneEdge(), otawa::CAT2Builder::configure(), otawa::ACSBuilder::configure(), otawa::etime::EdgeTimeBuilder::genForOneCost(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::Processor::init(), otawa::FlowFactLoader::load(), otawa::FlowFactLoader::loadF4(), otawa::script::Script::makeConfig(), otawa::CFGBuilder::nextBB(), otawa::FlowFactLoader::onLoop(), otawa::FlowFactLoader::onMemoryAccess(), otawa::FlowFactLoader::onNoInline(), otawa::FlowFactLoader::onReturn(), otawa::FlowFactLoader::onSetInlining(), otawa::Processor::process(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::branch::CondNumber::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::dcache::CLPBlockBuilder::processBB(), otawa::etime::StandardEventBuilder::processBB(), otawa::dcache::BlockBuilder::processBB(), otawa::CFGCheckSummer::processCFG(), otawa::EdgeProcessor::processCFG(), otawa::CAT2Builder::processCFG(), otawa::display::CFGOutput::processCFG(), otawa::ipet::ConstraintLoader::processCFG(), otawa::ContextualProcessor::processCFG(), otawa::BBProcessor::processCFG(), otawa::etime::EdgeTimeBuilder::processEdge(), otawa::VarTextDecoder::processEntry(), otawa::dcache::CATBuilder::processLBlockSet(), otawa::ACSMayBuilder::processLBlockSet(), otawa::CAT2Builder::processLBlockSet(), otawa::dcache::ACSBuilder::processLBlockSet(), otawa::etime::EdgeTimeBuilder::processSequence(), otawa::TextDecoder::processWorkSpace(), otawa::VarTextDecoder::processWorkSpace(), otawa::LBlockProcessor::processWorkSpace(), otawa::ipet::WCETComputation::processWorkSpace(), otawa::FixedTextDecoder::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), otawa::PFGBuilder::processWorkSpace(), otawa::StackAnalysis::processWorkSpace(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::branch::BranchBuilder::processWorkSpace(), otawa::CFGProcessor::processWorkSpace(), otawa::Virtualizer::processWorkSpace(), otawa::clp::Analysis::processWorkSpace(), otawa::script::Script::processWorkSpace(), otawa::ilp::Output::setup(), otawa::CFGBuilder::setup(), otawa::BBRatioDisplayer::setup(), otawa::dcache::BlockBuilder::setup(), otawa::CFGBuilder::thisBB(), otawa::ipet::FlowFactLoader::transfer(), otawa::Virtualizer::virtualize(), and otawa::script::Script::work().
log_level_t otawa::Monitor::logLevel (void) const inline inherited
Referenced by otawa::script::Script::declareGlobals().
elm::String otawa::Processor::name (void) const inline inherited
Referenced by otawa::Loader::check(), otawa::CFGCollector::configure(), otawa::display::ILPSystemDisplayer::displayVar(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::script::Script::makeConfig(), otawa::display::ILPSystemDisplayer::nameOf(), otawa::FlowFactLoader::onCheckSum(), otawa::Processor::process(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::ccg::ConstraintBuilder::processLBlockSet(), otawa::Processor::Processor(), otawa::ipet::WCETComputation::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), otawa::FlowFactLoader::scanBound(), otawa::FlowFactLoader::scanIgnoreEntry(), otawa::FlowFactLoader::scanInt(), otawa::FlowFactLoader::scanMemSet(), otawa::FlowFactLoader::scanRegSet(), otawa::FlowFactLoader::scanUInt(), otawa::FlowFactLoader::scanXBody(), otawa::FlowFactLoader::scanXConditional(), otawa::FlowFactLoader::scanXContent(), otawa::Processor::warn(), and otawa::script::Script::work().
void otawa::Processor::prepare (WorkSpace * ws) protected virtual inherited
This method called to let the processor customize its requirements according to some generic feature.
When overload, the original method MUST be called at the end of the custom overriding implementation.
Parameters
ws Current workspace.
References otawa::Monitor::flags, otawa::Processor::IS_PREPARED, otawa::StatInfo::remove(), and otawa::Processor::ws.
Referenced by otawa::Processor::process(), and otawa::ipet::TrivialDataCacheManager::processBB().
void otawa::Processor::process (WorkSpace * fw, const PropList & props = PropList::EMPTY) inherited
Execute the code processor on the given framework.
Parameters
fw Workspace to work on.
props Configuration properties.
References otawa::Processor::_reg, otawa::Processor::cleaners, otawa::Processor::cleanup(), otawa::Processor::collectStats(), otawa::Processor::configure(), otawa::WorkSpace::getDependency(), otawa::FeatureUsage::invalidate, otawa::WorkSpace::invalidate(), otawa::WorkSpace::isCancelled(), otawa::Processor::isCollectingStats(), otawa::Processor::isPrepared(), otawa::WorkSpace::isProvided(), otawa::Processor::isTimed(), kind, otawa::Monitor::log, otawa::Monitor::LOG_CFG, otawa::Monitor::LOG_DEPS, otawa::Monitor::LOG_PROC, otawa::Monitor::logFor(), otawa::AbstractRegistration::name(), otawa::Processor::name(), otawa::Processor::prepare(), otawa::Processor::processWorkSpace(), otawa::FeatureUsage::provide, otawa::WorkSpace::provide(), otawa::Processor::recordsStats(), otawa::FeatureUsage::require, otawa::WorkSpace::require(), otawa::Processor::RUNTIME, otawa::Processor::setup(), otawa::Processor::stats, otawa::FeatureUsage::use, otawa::AbstractRegistration::uses(), otawa::Processor::version(), and otawa::Processor::ws.
Referenced by otawa::PFGBuilder::finalizeBB(), otawa::WorkSpace::getCFGInfo(), otawa::FlowFactLoader::onIgnoreEntry(), otawa::SilentFeature::process(), otawa::ActualFeature::process(), otawa::Feature< T, C >::process(), otawa::p::feature::process(), otawa::TextDecoder::processWorkSpace(), otawa::cat::CATBuilder::processWorkSpace(), and otawa::DelayedBuilder::setup().
void otawa::LBlockBuilder::processBB (WorkSpace * ws, CFG * cfd, BasicBlock * bb) protected virtual
Perform the work of the given basic block.
Parameters
fw Container framework.
cfg Parent CFG.
bb Basic block to process.
Implements otawa::BBProcessor.
References addLBlock(), otawa::ProgItem::address(), otawa::BasicBlock::address(), otawa::BB_LBLOCKS, otawa::hard::Cache::blockBits(), otawa::hard::Cache::blockMask(), cache, otawa::COLLECTED_LBLOCKS_FEATURE, otawa::BasicBlock::firstInst(), otawa::BasicBlock::isEnd(), otawa::hard::Cache::set(), and otawa::BasicBlock::size().
void otawa::BBProcessor::processCFG (WorkSpace * ws, CFG * cfg) protected virtual inherited
See CFGProcessor::processCFG()
Implements otawa::CFGProcessor.
Reimplemented in otawa::BBRatioDisplayer, otawa::CFGSaver, otawa::CFGChecker, and otawa::cfgio::Output.
References otawa::ot::address(), otawa::cfgio::bb(), otawa::Monitor::log, otawa::Monitor::LOG_BB, otawa::Monitor::logFor(), and otawa::BBProcessor::processBB().
Referenced by otawa::cfgio::Output::processCFG(), otawa::CFGChecker::processCFG(), otawa::CFGSaver::processCFG(), and otawa::BBRatioDisplayer::processCFG().
void otawa::Processor::processFrameWork (WorkSpace * fw) protected virtual inherited
Process the given workspace.
Parameters
fw Workspace to process.
Deprecated:
Use processWorkSpace() instead.
Referenced by otawa::Processor::processWorkSpace().
void otawa::CFGProcessor::processWorkSpace (WorkSpace * fw) protected virtual inherited
Process the given framework.
Parameters
fw Framework to process.
Deprecated:
Use processWorkSpace() instead.
Reimplemented from otawa::Processor.
Reimplemented in otawa::GraphBBTime< G >, otawa::GraphBBTime< ParExeGraph >, otawa::ExeGraphBBTime< G >, otawa::ExeGraphBBTime< LiExeGraph >, otawa::ExeGraphBBTime< ParamExeGraph >, otawa::ipet::BasicConstraintsBuilder, otawa::DelayedBuilder, otawa::CFGSaver, and otawa::cfgio::Output.
References otawa::CFGProcessor::_cfg, otawa::CFGProcessor::cfg(), otawa::INVOLVED_CFGS, otawa::CFG::label(), otawa::Monitor::log, otawa::Monitor::LOG_CFG, otawa::Monitor::logFor(), otawa::CFGProcessor::processCFG(), otawa::PROCESSED_CFG, otawa::Processor::recordsStats(), and otawa::Processor::stats.
Referenced by otawa::CAT2Builder::processCFG(), otawa::cfgio::Output::processWorkSpace(), otawa::CFGSaver::processWorkSpace(), otawa::DelayedBuilder::processWorkSpace(), otawa::ipet::BasicConstraintsBuilder::processWorkSpace(), otawa::ExeGraphBBTime< G >::processWorkSpace(), and otawa::GraphBBTime< G >::processWorkSpace().
Progress & otawa::Processor::progress (void) inline protected inherited
Get the current progress handler.
Returns
Progress handler.
void otawa::Processor::provide (const AbstractFeature & feature) protected inherited
Usually called from a processor constructor, this method records a feature provided by the work of the current processor.
Parameters
feature Provided feature.
References otawa::Processor::_reg, otawa::AbstractRegistration::features, otawa::Monitor::flags, otawa::Processor::IS_ALLOCATED, otawa::Processor::isAllocated(), otawa::Processor::isPrepared(), and otawa::FeatureUsage::provide.
Referenced by otawa::ipet::BasicConstraintsBuilder::BasicConstraintsBuilder(), otawa::CFGBuilder::CFGBuilder(), otawa::CFGCheckSummer::CFGCheckSummer(), otawa::CFGCollector::CFGCollector(), otawa::CFGNormalizer::CFGNormalizer(), otawa::ContextTreeBuilder::ContextTreeBuilder(), otawa::ContextTreeByCFGBuilder::ContextTreeByCFGBuilder(), otawa::DeadCodeAnalysis::DeadCodeAnalysis(), otawa::Dominance::Dominance(), otawa::EdgeACSBuilder::EdgeACSBuilder(), otawa::EdgeCAT2Builder::EdgeCAT2Builder(), otawa::EdgeCAT2ConstraintBuilder::EdgeCAT2ConstraintBuilder(), otawa::ExeGraphBBTime< G >::ExeGraphBBTime(), otawa::FirstLastBuilder::FirstLastBuilder(), otawa::ipet::FlowFactConstraintBuilder::FlowFactConstraintBuilder(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::ipet::ILPSystemGetter::ILPSystemGetter(), otawa::LoopReductor::LoopReductor(), otawa::PCGBuilder::PCGBuilder(), otawa::PFGBuilder::PFGBuilder(), otawa::PostDominance::PostDominance(), otawa::PSTBuilder::PSTBuilder(), otawa::TextDecoder::TextDecoder(), otawa::ipet::TrivialDataCacheManager::TrivialDataCacheManager(), and otawa::VarTextDecoder::VarTextDecoder().
bool otawa::Processor::recordsStats (void) const inline protected inherited
Test if the statictics mode is activated.
Returns
True if the statistics mode is activated, false else.
Referenced by otawa::Processor::init(), otawa::Processor::process(), and otawa::CFGProcessor::processWorkSpace().
void otawa::Processor::recordStat (const AbstractFeature & feature, StatCollector * collector) protected inherited
Add a statistics collector to the current workspace collection.
The statistics object is tracked and linked to the feature. In case of the feature invalidation, the statistics information instance is purged of the statistics collector.
Parameters
feature Feature to link the collector to.
collector Statistics collector to add.
References otawa::StatInfo::add(), otawa::Processor::addCleaner(), otawa::Processor::isCollectingStats(), and otawa::Processor::workspace().
Referenced by otawa::CAT2OnlyConstraintBuilder::collectStats(), otawa::ipet::WCETComputation::collectStats(), and otawa::dcache::CatConstraintBuilder::collectStats().
void otawa::Processor::require (const AbstractFeature & feature) protected inherited
Usually called from a processor constructor, this method records a required feature for the work of the current processor.
Parameters
feature Required feature.
References otawa::Processor::_reg, otawa::AbstractRegistration::features, otawa::Monitor::flags, otawa::Processor::IS_ALLOCATED, otawa::Processor::isAllocated(), otawa::Processor::isPrepared(), and otawa::FeatureUsage::require.
Referenced by otawa::ipet::BasicConstraintsBuilder::BasicConstraintsBuilder(), otawa::CFGBuilder::CFGBuilder(), otawa::CFGCollector::CFGCollector(), otawa::CFGNormalizer::CFGNormalizer(), otawa::ContextTreeBuilder::ContextTreeBuilder(), otawa::ContextTreeByCFGBuilder::ContextTreeByCFGBuilder(), otawa::ContextualProcessor::ContextualProcessor(), otawa::DeadCodeAnalysis::DeadCodeAnalysis(), otawa::EdgeACSBuilder::EdgeACSBuilder(), otawa::EdgeCAT2Builder::EdgeCAT2Builder(), otawa::EdgeCAT2ConstraintBuilder::EdgeCAT2ConstraintBuilder(), otawa::FirstLastBuilder::FirstLastBuilder(), otawa::ipet::FlowFactConstraintBuilder::FlowFactConstraintBuilder(), otawa::LinkedBlocksDetector::LinkedBlocksDetector(), otawa::LoopReductor::LoopReductor(), otawa::PCGBuilder::PCGBuilder(), otawa::PFGBuilder::PFGBuilder(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::CAT2Builder::processCFG(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), otawa::PSTBuilder::PSTBuilder(), otawa::FeatureRequirer::require(), otawa::StackAnalysis::StackAnalysis(), otawa::TextDecoder::TextDecoder(), otawa::ipet::TrivialDataCacheManager::TrivialDataCacheManager(), otawa::ipet::WCETCountRecorder::WCETCountRecorder(), and otawa::script::Script::work().
void otawa::Processor::requireDyn (WorkSpace * ws, const PropList & props) protected virtual inherited
Method called after registration requirements to support dynamic requirements.
As a default, do nothing.
Parameters
ws Current workspace.
props Current properties.
Referenced by otawa::ipet::TrivialDataCacheManager::processBB().
void otawa::LBlockBuilder::setup (WorkSpace * ws) protected virtual
This method is called before an anlysis to let the processor do some initialization.
Parameters
ws Processed workspace.
Reimplemented from otawa::Processor.
References cache, otawa::hard::CACHE_CONFIGURATION, otawa::hard::CacheConfiguration::instCache(), otawa::LBLOCKS, lbsets, mem, otawa::hard::MEMORY, and otawa::hard::Cache::rowCount().
void otawa::Monitor::setWorkspace (WorkSpace * workspace) inline protected inherited
Set the current workspace.
Parameters
workspace New current workspace.
string otawa::CFGProcessor::str (const Address & address) protected inherited
Transform an address to a smart string, that is, if a source line is available, transform it to "source_file:source_line", if the CFG has a label, it gives "label + 0xoffset", else return the address.
Parameters
address Address to display.
Returns
Address transformed in string.
References otawa::Address::null.
Referenced by otawa::ipet::FlowFactLoader::processBB().
string otawa::CFGProcessor::str (const Address & base, const Address & address) protected inherited
Transform an address to a smart string, that is, if a source line is available, transform it to "source_file:source_line", if the CFG has a label, it gives "label + 0xoffset", else return the address.
Parameters
base Base address of the function containing the give address.
address Address to display.
Returns
Address transformed in string.
References otawa::CFGProcessor::_cfg, otawa::ProgItem::address(), otawa::ot::address(), otawa::WorkSpace::findInstAt(), otawa::CFG::firstInst(), otawa::FUNCTION_LABEL, otawa::Address::isNull(), otawa::Address::offset(), otawa::Processor::RECURSIVE, and otawa::Processor::workspace().
template<class T > T* otawa::Processor::track (const AbstractFeature & feature, T * object) inline protected inherited
Referenced by otawa::SubCFGBuilder::cleanup(), otawa::StackAnalysis::cleanup(), otawa::DelayedBuilder::cleanup(), and otawa::CFGBuilder::processWorkSpace().
template<class T > void otawa::Processor::track (const AbstractFeature & feature, const Ref< T *, Identifier< T * > > & ref) inline protected inherited
Track the release of an allocated object assigned to an identifier relatively to the given feature.
When the feature is deleted, the object is fried and the identifier is removed. It is used as below:
track(MY_FEATURE, MY_ID(props) = value);
Parameters
feature Linked feature.
ref Reference to the identifier to remove.
template<class T > void otawa::Processor::track (const AbstractFeature & feature, const Ref< T *, const Identifier< T * > > & ref) inline protected inherited
Track the release of an allocated object assigned to an identifier relatively to the given feature.
When the feature is deleted, the object is fried and the identifier is removed. It is used as below:
track(MY_FEATURE, MY_ID(props) = value);
Parameters
feature Linked feature.
ref Reference to the identifier to remove.
template<class T > void otawa::BBProcessor::trackBB (const AbstractFeature & feature, const Identifier< T * > & id) inline protected inherited
Track and delete the content of the given identifier on each basic block.
Parameters
feature Feature this identifier is linked to.
id Identifier of the properties to remove.
template<class T > void otawa::BBProcessor::trackBB (const AbstractFeature & feature, const Identifier< T > & id) inline protected inherited
Track and remove properties put on basic blocks.
Parameters
feature Feature this identifier is linked to.
id Identifier of the properties to remove.
void otawa::Processor::use (const AbstractFeature & feature) protected inherited
Usually called from a processor constructor, this method records a feature as used by the work of the current processor.
Parameters
feature Used feature.
References otawa::Processor::_reg, otawa::AbstractRegistration::features, otawa::Monitor::flags, otawa::Processor::IS_ALLOCATED, otawa::Processor::isAllocated(), otawa::Processor::isPrepared(), and otawa::FeatureUsage::use.
Referenced by otawa::Virtualizer::Virtualizer().
elm::Version otawa::Processor::version (void) const inline inherited
References otawa::PropList::EMPTY.
Referenced by otawa::Processor::process(), otawa::Processor::Processor(), and otawa::Processor::warn().
void otawa::Processor::warn (const String & message) protected inherited
Display a warning.
Parameters
message Message to display.
References otawa::Processor::COLLECT_STATS, otawa::Monitor::log, otawa::LOG, otawa::Processor::LOG, otawa::LOG_LEVEL, otawa::Processor::LOG_LEVEL, otawa::Processor::name(), otawa::Progress::null, otawa::OUTPUT, otawa::Processor::OUTPUT, otawa::Processor::PROGRESS, otawa::Processor::RUNTIME, otawa::Processor::STATS, otawa::Processor::TIMED, otawa::VERBOSE, otawa::Processor::VERBOSE, and otawa::Processor::version().
Referenced by otawa::CFGBuilder::addFile(), otawa::FlowFactLoader::addressOf(), otawa::CFGBuilder::buildCFG(), otawa::VarTextDecoder::getInst(), otawa::FlowFactLoader::load(), otawa::FlowFactLoader::loadF4(), otawa::FlowFactLoader::onWarning(), otawa::ets::FlowFactLoader::processAST(), otawa::ipet::FlowFactLoader::processBB(), otawa::CFGChecker::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::etime::StandardEventBuilder::processBB(), otawa::CFGNormalizer::processCFG(), otawa::CFGChecker::processCFG(), otawa::VarTextDecoder::processEntry(), otawa::VarTextDecoder::processWorkSpace(), otawa::FixedTextDecoder::processWorkSpace(), otawa::FlowFactLoader::processWorkSpace(), otawa::Processor::processWorkSpace(), otawa::FlowFactLoader::scanXBody(), otawa::FlowFactLoader::scanXLoop(), otawa::ipet::TrivialInstCacheManager::setup(), otawa::CFGBuilder::setup(), and otawa::script::Script::work().
WorkSpace * otawa::Monitor::workspace (void) inline inherited
Get the current workspace.
Returns
Current workspace.
WorkSpace * otawa::Processor::workspace (void) const inline protected inherited
Get the current workspace.
Returns
Current workspace.
Referenced by otawa::CFGProcessor::doCleanUp(), otawa::PFGBuilder::finalizeBB(), otawa::FlowFactLoader::findCall(), otawa::VarTextDecoder::getBytes(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::ipet::FlowFactLoader::lookLineAt(), otawa::etime::EdgeTimeBuilder::make(), otawa::DelayedBuilder::next(), otawa::FlowFactLoader::onIgnoreEntry(), otawa::VarTextDecoder::processEntry(), otawa::Processor::recordStat(), otawa::DelayedBuilder::setup(), otawa::DelayedBuilder::size(), and otawa::CFGProcessor::str().
Member Data Documentation
genstruct::HashTable<ot::mask, int> otawa::LBlockBuilder::block_map private
Referenced by addLBlock().
const hard::Cache* otawa::LBlockBuilder::cache private
Referenced by addLBlock(), cleanup(), processBB(), and setup().
Identifier< bool > otawa::Processor::COLLECT_STATS static inherited
This property allows to activate collection of statistics for the work of the current processor.
See also
StatInfo class.
Referenced by otawa::Processor::init(), and otawa::Processor::warn().
const t::uint32 otawa::Monitor::CUSTOM_SHIFT = 16 static protected inherited
t::uint32 otawa::Monitor::flags protected inherited
Contains various bit flags.
Bits from 0 to CUSTOM_SHIFT - 1 are private while bits from CUSTOM_SHIFT to 31 may be customized. To build a bit mask for custom bit i, the CUSTOM_SHIFT may be used as below:
static const t::uint32 MY_MASK = 1 << (i + CUSTOM_SHIFT);
Referenced by otawa::Monitor::configure(), otawa::Processor::init(), otawa::Processor::invalidate(), otawa::Processor::prepare(), otawa::Processor::Processor(), otawa::Processor::provide(), otawa::Processor::require(), otawa::Processor::use(), and otawa::Processor::~Processor().
const t::uint32 otawa::Processor::IS_ALLOCATED = 0x04 << CUSTOM_SHIFT static protected inherited
Referenced by otawa::Processor::invalidate(), otawa::Processor::Processor(), otawa::Processor::provide(), otawa::Processor::require(), otawa::Processor::use(), and otawa::Processor::~Processor().
const t::uint32 otawa::Processor::IS_COLLECTING = 0x10 << CUSTOM_SHIFT static protected inherited
Referenced by otawa::Processor::init().
const t::uint32 otawa::Processor::IS_PREPARED = 0x08 << CUSTOM_SHIFT static protected inherited
Referenced by otawa::Processor::prepare().
const t::uint32 otawa::Processor::IS_TIMED = 0x01 << CUSTOM_SHIFT static protected inherited
Referenced by otawa::Processor::init().
const t::uint32 otawa::Monitor::IS_VERBOSE = 0x01 static protected inherited
Referenced by otawa::Monitor::configure().
LBlockSet** otawa::LBlockBuilder::lbsets private
Referenced by addLBlock(), cleanup(), and setup().
elm::io::Output otawa::Monitor::log inherited
Provide a stream to perform log output.
Should be used only when verbosity is activated.
Referenced by otawa::CFGBuilder::addCFG(), otawa::ipet::ConstraintLoader::addConstraint(), otawa::PFGBuilder::addFunction(), otawa::ccg::LBlockBuilder::addLBlock(), addLBlock(), otawa::FlowFactLoader::addressOf(), otawa::GraphBBTime< G >::analyzePathContext(), otawa::etime::EdgeTimeBuilder::applyFloppySplit(), otawa::etime::EdgeTimeBuilder::applyStrictSplit(), otawa::etime::EdgeTimeBuilder::applyWeightedSplit(), otawa::DelayedBuilder::buildBB(), otawa::CFGBuilder::buildCFG(), otawa::branch::BranchBuilder::categorize(), otawa::ipet::FlowFactLoader::cleanup(), otawa::ipet::TrivialDataCacheManager::configure(), otawa::ACSBuilder::configure(), otawa::Monitor::configure(), otawa::etime::EdgeTimeBuilder::displayConfs(), otawa::ipet::ConstraintLoader::error(), otawa::etime::EdgeTimeBuilder::genForOneCost(), otawa::ipet::ConstraintLoader::getBB(), otawa::VarTextDecoder::getInst(), otawa::ipet::ConstraintLoader::getVar(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::Processor::init(), otawa::FlowFactLoader::load(), otawa::FlowFactLoader::loadF4(), otawa::script::Script::makeConfig(), otawa::etime::EdgeTimeBuilder::makeSplit(), otawa::ipet::ConstraintLoader::newEdgeVar(), otawa::CFGBuilder::nextBB(), otawa::script::Script::onError(), otawa::FlowFactLoader::onLoop(), otawa::FlowFactLoader::onMemoryAccess(), otawa::FlowFactLoader::onNoInline(), otawa::FlowFactLoader::onReturn(), otawa::FlowFactLoader::onSetInlining(), otawa::script::Script::onWarning(), otawa::Processor::process(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::branch::CondNumber::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::dcache::CLPBlockBuilder::processBB(), otawa::etime::StandardEventBuilder::processBB(), otawa::dcache::BlockBuilder::processBB(), otawa::GraphBBTime< G >::processBB(), otawa::CFGCheckSummer::processCFG(), otawa::CAT2Builder::processCFG(), otawa::ipet::ConstraintLoader::processCFG(), otawa::ContextualProcessor::processCFG(), otawa::BBProcessor::processCFG(), otawa::etime::EdgeTimeBuilder::processEdge(), otawa::VarTextDecoder::processEntry(), otawa::dcache::CATBuilder::processLBlockSet(), otawa::ACSMayBuilder::processLBlockSet(), otawa::CAT2Builder::processLBlockSet(), otawa::dcache::ACSBuilder::processLBlockSet(), otawa::etime::EdgeTimeBuilder::processSequence(), otawa::TextDecoder::processWorkSpace(), otawa::VarTextDecoder::processWorkSpace(), otawa::LBlockProcessor::processWorkSpace(), otawa::FixedTextDecoder::processWorkSpace(), otawa::ipet::WCETComputation::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), otawa::StackAnalysis::processWorkSpace(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::branch::BranchBuilder::processWorkSpace(), otawa::CFGProcessor::processWorkSpace(), otawa::Virtualizer::processWorkSpace(), otawa::clp::Analysis::processWorkSpace(), otawa::ilp::Output::setup(), otawa::CFGBuilder::setup(), otawa::BBRatioDisplayer::setup(), otawa::dcache::BlockBuilder::setup(), otawa::CFGBuilder::thisBB(), otawa::ipet::FlowFactLoader::transfer(), otawa::Virtualizer::virtualize(), otawa::Processor::warn(), and otawa::script::Script::work().
Identifier< elm::io::OutStream * > & otawa::Processor::LOG = otawa::LOG static inherited
This property identifier is used for setting the log stream used by the processor to write messages (information, warning, error).
Deprecated:
Referenced by otawa::Processor::init(), otawa::Manager::loadBin(), otawa::LiExeGraphBBTime::processBB(), and otawa::Processor::warn().
Identifier< Processor::log_level_t > & otawa::Processor::LOG_LEVEL = otawa::LOG_LEVEL static inherited
Property passed in the configuration property list of a processor to select the log level between LOG_PROC, LOG_CFG or LOG_BB.
Deprecated:
Referenced by otawa::Application::run(), and otawa::Processor::warn().
const hard::Memory* otawa::LBlockBuilder::mem private
Referenced by addLBlock(), and setup().
Monitor & otawa::Monitor::null = __null_mon static inherited
Monitor that output nothing.
Referenced by otawa::Monitor::configure().
elm::io::Output otawa::Monitor::out inherited
Provide a stream to perform output for the user.
Referenced by otawa::DelayedBuilder::buildEdges(), otawa::Monitor::configure(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::Processor::init(), otawa::ast::ASTLoader::onError(), otawa::dcache::operator<<(), otawa::CFGChecker::processBB(), otawa::etime::StandardEventBuilder::processBB(), otawa::hard::Dumper::processWorkSpace(), otawa::ccg::Builder::processWorkSpace(), otawa::SubCFGBuilder::SubCFGBuilder(), and otawa::Virtualizer::virtualize().
Identifier< elm::io::OutStream * > & otawa::Processor::OUTPUT = otawa::OUTPUT static inherited
This property identifier is used for setting the output stream used by the processor to write results.
Deprecated:
Referenced by otawa::Processor::init(), and otawa::Processor::warn().
Identifier< Progress * > otawa::Processor::PROGRESS static inherited
Install.
Referenced by otawa::Processor::init(), and otawa::Processor::warn().
Identifier<bool> otawa::Processor::RECURSIVE static inherited
Referenced by otawa::CFGProcessor::str().
p::declare otawa::LBlockBuilder::reg static
Initial value:
= p::init("otawa::util::LBlockBuilder", Version(1, 1, 0))
        .base(BBProcessor::reg)
        .require(COLLECTED_CFG_FEATURE)
        .require(hard::CACHE_CONFIGURATION_FEATURE)
        .require(hard::MEMORY_FEATURE)
        .provide(COLLECTED_LBLOCKS_FEATURE)
        .maker<LBlockBuilder>()
Identifier< elm::system::time_t > otawa::Processor::RUNTIME static inherited
This property identifier is used to store in the statistics of a processor the overall run time of the processor work.
Referenced by otawa::Processor::process(), and otawa::Processor::warn().
Identifier< PropList * > otawa::Processor::STATS static inherited
This property identifiers is used to pass a property list to the processor that will be used to store statistics about the performed work.
Implicitly, passing such a property activates the statistics recording facilities.
Referenced by otawa::Processor::init(), and otawa::Processor::warn().
PropList* otawa::Processor::stats protected inherited
Referenced by otawa::dcache::CATBuilder::cleanup(), otawa::tsim::Delta::cleanup(), otawa::Processor::init(), otawa::Processor::process(), and otawa::CFGProcessor::processWorkSpace().
Identifier< bool > otawa::Processor::TIMED static inherited
If the value of the associated property is true (default to false), time statistics will also be collected with other processor statistics.
Passing such a property without PROC_STATS has no effects.
Referenced by otawa::Processor::init(), and otawa::Processor::warn().
Identifier< bool > & otawa::Processor::VERBOSE = otawa::VERBOSE static inherited
This property activates the verbose mode of the processor: information about the processor work will be displayed.
Deprecated:
Referenced by otawa::Application::run(), otawa::Manager::setVerbosity(), and otawa::Processor::warn().
The documentation for this class was generated from the following files:
include/otawa/cache/LBlockBuilder.h
src/prog/cache_LBlockBuilder.cpp