Otawa: otawa::LBlockManager Class Reference
otawa::LBlockManager Class Reference
#include <otawa/parexegraph/GraphBBTime.h>
Public Member Functions
LBlockManager (void)
category_t next (BasicBlock *ibb, Inst *inst)
BasicBlock * header (void) const
Private Attributes
BasicBlock * bb
genstruct::AllocatedTable< LBlock * > * lbs
BasicBlock * hd
int i
Constructor & Destructor Documentation
otawa::LBlockManager::LBlockManager (void) inline
Member Function Documentation
BasicBlock* otawa::LBlockManager::header (void) const inline
References hd.
Referenced by otawa::GraphBBTime< G >::analyzePathContext(), and otawa::GraphBBTime< G >::buildFMTimingContextListForICache().
category_t otawa::LBlockManager::next (BasicBlock * ibb, Inst * inst) inline
References otawa::ProgItem::address(), bb, otawa::BB_LBLOCKS, otawa::CATEGORY, otawa::cache::CATEGORY_HEADER, otawa::FIRST_MISS, hd, i, otawa::INVALID_CATEGORY, and lbs.
Referenced by otawa::GraphBBTime< G >::analyzePathContext(), otawa::GraphBBTime< G >::buildFMTimingContextListForICache(), otawa::GraphBBTime< G >::buildNCTimingContextListForICache(), and otawa::GraphBBTime< G >::computeDefaultTimingContextForICache().
Member Data Documentation
BasicBlock* otawa::LBlockManager::bb private
Referenced by otawa::PathContext::dump(), next(), and otawa::PathContext::PathContext().
BasicBlock* otawa::LBlockManager::hd private
Referenced by header(), and next().
int otawa::LBlockManager::i private
Referenced by next().
genstruct::AllocatedTable<LBlock*>* otawa::LBlockManager::lbs private
Referenced by next().
The documentation for this class was generated from the following file:
include/otawa/parexegraph/GraphBBTime.h