Otawa: otawa::dcache::BlockCollection Class Reference
otawa::dcache::BlockCollection Class Reference
Data Cache
A block collections stores the list of data blocks used in a task for a specific line.
#include <otawa/dcache/features.h>
Public Member Functions
~BlockCollection (void)
const Block & operator[] (int i) const
const Block & obtain (const Address &addr)
Obtain a block matching the given address.
void setSet (int set)
Set the set number of the block collection.
int count (void) const
Get the count of blocks in this collection.
int cacheSet (void) const
Private Attributes
int _set
genstruct::Vector< Block * > blocks
Detailed Description
A block collections stores the list of data blocks used in a task for a specific line.
Constructor & Destructor Documentation
otawa::dcache::BlockCollection::~BlockCollection (void)
References otawa::dcache::BlockBuilder::blocks.
Member Function Documentation
int otawa::dcache::BlockCollection::cacheSet (void) const inline
Referenced by otawa::dcache::operator<<(), otawa::dcache::DirtyManager::t::print(), otawa::dcache::CATBuilder::processLBlockSet(), otawa::dcache::ACSMayBuilder::processLBlockSet(), otawa::dcache::ACSBuilder::processLBlockSet(), and otawa::dcache::DirtyManager::update().
int otawa::dcache::BlockCollection::count (void) const inline
Get the count of blocks in this collection.
Returns
Count of blocks.
Referenced by otawa::dcache::CATBuilder::processLBlockSet(), otawa::dcache::ACSMayBuilder::processLBlockSet(), otawa::dcache::ACSBuilder::processLBlockSet(), and otawa::dcache::DirtyManager::update().
const Block & otawa::dcache::BlockCollection::obtain (const Address & addr)
Obtain a block matching the given address.
Parameters
addr Address of the looked block.
Returns
Matching block (possibly created).
References otawa::ot::address(), otawa::dcache::BlockBuilder::blocks, and otawa::Address::isNull().
Referenced by otawa::dcache::CLPBlockBuilder::processBB(), and otawa::dcache::BlockBuilder::processBB().
const Block& otawa::dcache::BlockCollection::operator[] (int i) const inline
void otawa::dcache::BlockCollection::setSet (int set) inline
Set the set number of the block collection.
Parameters
set Set number.
Member Data Documentation
int otawa::dcache::BlockCollection::_set private
genstruct::Vector<Block *> otawa::dcache::BlockCollection::blocks private
The documentation for this class was generated from the following files:
include/otawa/dcache/features.h
src/dcache/dcache_BlockBuilder.cpp