Otawa: otawa::ExeGraph< N >::ExeNode Class Reference
otawa::ExeGraph< N >::ExeNode Class Reference
#include <otawa/exegraph/ExeGraph.h>
Classes
class ContenderIterator
Public Member Functions
ExeNode (ExeGraph< N > *graph, PipelineStage< N > *stage, ExeInst< N > *inst)
Constructor.
PipelineStage< N > * pipelineStage (void)
ExeInst< N > * inst (void)
int latency ()
int latency (time_bound_t bound)
void setLatency (time_bound_t bound, int latency)
bool needsOperands (void)
void setNeedsOperands (bool val)
Sets whether the node depends on input operands.
bool producesOperands (void)
void setProducesOperands (bool val)
Sets whether the node produces output operands.
void addContender (N *cont)
Adds a contender to the lists of contenders for the node.
elm::genstruct::Vector< N * > * contenders ()
elm::String name ()
Returns the name of the node, composed of the name of the pipeline stage and the name of the instruction (e.g.
int index (void) const
bool hasSucc (void) const
bool hasPred (void) const
int countSucc (void) const
int countPred (void) const
bool isPredOf (const GenNode *node)
bool isSuccOf (const GenNode *node)
Protected Attributes
elm::genstruct::Vector< N * > _contenders
Private Attributes
ExeInst< N > * _inst
PipelineStage< N > * _pipeline_stage
int _latency [BOUNDS]
bool _needs_operands
bool _produces_operands
elm::String _name
Constructor & Destructor Documentation
template<class N> otawa::ExeGraph< N >::ExeNode::ExeNode (ExeGraph< N > * graph, PipelineStage< N > * stage, ExeInst< N > * inst) inline
Constructor.
Parameters
graph The execution graph the node is attached to.
stage The pipeline stage the node is related to.
inst The instruction the node is related to.
References otawa::ExeInst< N >::index(), otawa::branch::MAX, otawa::PipelineStage< N >::maxLatency(), otawa::PipelineStage< N >::minLatency(), and otawa::PipelineStage< N >::shortName().
Member Function Documentation
template<class N> void otawa::ExeGraph< N >::ExeNode::addContender (N * cont) inline
Adds a contender to the lists of contenders for the node.
Parameters
cont The new contender for the node.
template<class N> elm::genstruct::Vector< N * > * otawa::ExeGraph< N >::ExeNode::contenders (void) inline
Returns
The list of contenders of the node.
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::countPred (void) const inline inherited
References otawa::graph::Node::countPred().
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::countSucc (void) const inline inherited
References otawa::graph::Node::countSucc().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::hasPred (void) const inline inherited
References otawa::graph::Node::hasPred().
Referenced by otawa::LiExeGraph::shadeNodes().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::hasSucc (void) const inline inherited
References otawa::graph::Node::hasSucc().
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::index (void) const inline inherited
References otawa::graph::Node::index().
Referenced by otawa::ParamExeGraph::cost().
template<class N> ExeInst< N > * otawa::ExeGraph< N >::ExeNode::inst (void) inline
Returns
The instruction the node is related to.
References otawa::ExeInst< N >::_inst.
Referenced by otawa::ParamExeGraph::analyzeContentions(), otawa::LiExeGraph::maxTimeToNode(), otawa::LiExeGraph::nodeEarliestTimes(), and otawa::LiExeGraph::nodeLatestTimes().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::isPredOf (const GenNode * node) inline inherited
References otawa::graph::Node::countPred().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::isSuccOf (const GenNode * node) inline inherited
References otawa::graph::Node::isSuccOf().
template<class N> int otawa::ExeGraph< N >::ExeNode::latency () inline
Returns
The minimum node latency.
Referenced by otawa::LiExeGraph::analyze(), otawa::ParamExeGraph::Delta(), otawa::LiExeGraph::latestTimes(), otawa::LiExeGraph::maxTimeToNode(), otawa::LiExeGraph::nodeEarliestTimes(), and otawa::LiExeGraph::nodeLatestTimes().
template<class N> int otawa::ExeGraph< N >::ExeNode::latency (time_bound_t bound) inline
Parameters
bound A time bound (MIN or MAX).
Returns
The node latency.
template<class N> elm::String otawa::ExeGraph< N >::ExeNode::name (void) inline
Returns the name of the node, composed of the name of the pipeline stage and the name of the instruction (e.g.
"CM(I8)").
Returns
Node name.
Referenced by otawa::ParamExeGraph::Delta().
template<class N> bool otawa::ExeGraph< N >::ExeNode::needsOperands (void) inline
Returns
Whether the node depends on input operands.
template<class N> PipelineStage< N > otawa::ExeGraph< N >::ExeNode::pipelineStage (void) inline
Returns
The pipeline stage the node is related to.
Referenced by otawa::ParamExeGraph::Delta(), otawa::LiExeGraph::nodeEarliestTimes(), otawa::LiExeGraph::nodeLatestTimes(), and otawa::ParamExeNode::ParamExeNode().
template<class N> bool otawa::ExeGraph< N >::ExeNode::producesOperands (void) inline
Returns
Whether the node produces output operands.
template<class N> void otawa::ExeGraph< N >::ExeNode::setLatency (time_bound_t bound, int latency) inline
Parameters
bound A time bound (MIN or MAX).
latency The new value of the latency.
template<class N> void otawa::ExeGraph< N >::ExeNode::setNeedsOperands (bool val) inline
Sets whether the node depends on input operands.
template<class N> void otawa::ExeGraph< N >::ExeNode::setProducesOperands (bool val) inline
Sets whether the node produces output operands.
Member Data Documentation
template<class N> elm::genstruct::Vector<N *> otawa::ExeGraph< N >::ExeNode::_contenders protected
template<class N> ExeInst<N>* otawa::ExeGraph< N >::ExeNode::_inst private
template<class N> int otawa::ExeGraph< N >::ExeNode::_latency[BOUNDS] private
template<class N> elm::String otawa::ExeGraph< N >::ExeNode::_name private
template<class N> bool otawa::ExeGraph< N >::ExeNode::_needs_operands private
template<class N> PipelineStage<N>* otawa::ExeGraph< N >::ExeNode::_pipeline_stage private
template<class N> bool otawa::ExeGraph< N >::ExeNode::_produces_operands private
The documentation for this class was generated from the following files:
include/otawa/exegraph/ExeGraph.h
src/prog/exegraph_ExeGraph.cpp