Otawa: otawa::dfa::AbsIntLite< G, T > Class Template Reference
otawa::dfa::AbsIntLite< G, T > Class Template Reference
This class provides a light implementation for abstract interpretation.
#include <otawa/dfa/AbsIntLite.h>
Public Member Functions
AbsIntLite (const G &graph, T &domain)
Build the analyzer.
void push (typename G::Vertex v)
G::Vertex pop (void)
void process (void)
void step (typename G::Vertex v)
const AbsIntLiteExtender< G, T >::t & in (typename G::Vertex v)
const AbsIntLiteExtender< G, T >::t & out (typename G::Vertex v) const
Private Attributes
AbsIntLiteExtender< G, T > e
Detailed Description
template<class G, class T>
class otawa::dfa::AbsIntLite< G, T >
This class provides a light implementation for abstract interpretation.
For details on the abstract interpretation, you may define the symbol OTAWA_AIL_DEBUG and process information will be printed on standard input.
The first template parameter must provide a graph traversal interface. Often used implementation of this interface for CFG includes ForwardCFGAdapter (forward traversal) or BackwardCFGAdapter (backward traversal).
Parameters
G Type of processed graph (must implement concept otawa::concept::DiGraphWithIndexedVertex, otawa::concept::DiGraphWithEntry and otawa::concept::DiGraphWithLoop)
T Type of abstract domain (must implement concept otawa::concept::AbstractDomain)
Constructor & Destructor Documentation
template<class G , class T > otawa::dfa::AbsIntLite< G, T >::AbsIntLite (const G & graph, T & domain) inline
Build the analyzer.
Parameters
graph Graph to work on.
domain Abstract domain handler.
Member Function Documentation
const AbsIntLiteExtender< G, T > ::t& otawa::dfa::AbsIntLiteEx< G, AbsIntLiteExtender< G, T > >::in (typename G::Vertex v) inline inherited
References otawa::dfa::AbsIntLiteEx< G, T >::d, otawa::dfa::AbsIntLiteEx< G, T >::g, OTAWA_AILD, otawa::dfa::AbsIntLiteEx< G, T >::t2, otawa::dfa::AbsIntLiteEx< G, T >::tmp, and otawa::dfa::AbsIntLiteEx< G, T >::vals.
const AbsIntLiteExtender< G, T > ::t& otawa::dfa::AbsIntLiteEx< G, AbsIntLiteExtender< G, T > >::out (typename G::Vertex v) const inline inherited
References otawa::dfa::AbsIntLiteEx< G, T >::g, and otawa::dfa::AbsIntLiteEx< G, T >::vals.
G::Vertex otawa::dfa::AbsIntLiteEx< G, AbsIntLiteExtender< G, T > >::pop (void) inline inherited
References otawa::dfa::AbsIntLiteEx< G, T >::g, and otawa::dfa::AbsIntLiteEx< G, T >::todo.
void otawa::dfa::AbsIntLiteEx< G, AbsIntLiteExtender< G, T > >::process (void) inline inherited
References otawa::dfa::AbsIntLiteEx< G, T >::d, otawa::dfa::AbsIntLiteEx< G, T >::g, OTAWA_AILD, otawa::dfa::AbsIntLiteEx< G, T >::pop(), otawa::dfa::AbsIntLiteEx< G, T >::push(), otawa::dfa::AbsIntLiteEx< G, T >::step(), otawa::dfa::AbsIntLiteEx< G, T >::todo, and otawa::dfa::AbsIntLiteEx< G, T >::vals.
void otawa::dfa::AbsIntLiteEx< G, AbsIntLiteExtender< G, T > >::push (typename G::Vertex v) inline inherited
References otawa::dfa::AbsIntLiteEx< G, T >::g, and otawa::dfa::AbsIntLiteEx< G, T >::todo.
void otawa::dfa::AbsIntLiteEx< G, AbsIntLiteExtender< G, T > >::step (typename G::Vertex v) inline inherited
References otawa::dfa::AbsIntLiteEx< G, T >::d, otawa::dfa::AbsIntLiteEx< G, T >::g, otawa::dfa::AbsIntLiteEx< G, T >::in(), OTAWA_AILD, otawa::dfa::AbsIntLiteEx< G, T >::push(), otawa::dfa::AbsIntLiteEx< G, T >::tmp, and otawa::dfa::AbsIntLiteEx< G, T >::vals.
Member Data Documentation
template<class G , class T > AbsIntLiteExtender<G, T> otawa::dfa::AbsIntLite< G, T >::e private
The documentation for this class was generated from the following files:
include/otawa/dfa/AbsIntLite.h
src/prog/dfa_AbsIntLite.cpp