Otawa: otawa::dcache::Block Class Reference
otawa::dcache::Block Class Reference
Data Cache
Represents a single block used by the data cache.
#include <otawa/dcache/features.h>
Public Member Functions
Block (void)
Build a "any" number (with a null address).
Block (int set, int index, const Address &address)
Build a simple block.
Block (const Block &block)
Cloning of a block.
int set (void) const
Get the set number of a block.
int index (void) const
Get the number of a block.
const Address & address (void) const
void print (io::Output &out) const
Print a block.
Private Attributes
int _set
int idx
Address addr
Detailed Description
Represents a single block used by the data cache.
Constructor & Destructor Documentation
otawa::dcache::Block::Block (void) inline
Build a "any" number (with a null address).
otawa::dcache::Block::Block (int set, int index, const Address & address) inline
Build a simple block.
Parameters
set Number of its cache set.
index Its number.
address Address of the block.
References otawa::Address::isNull().
otawa::dcache::Block::Block (const Block & block) inline
Cloning of a block.
Parameters
block Block to clone.
Member Function Documentation
const Address& otawa::dcache::Block::address (void) const inline
Referenced by otawa::dcache::BlockAccess::in(), and otawa::etime::StandardEventBuilder::processBB().
int otawa::dcache::Block::index (void) const inline
Get the number of a block.
Returns
Block number.
Referenced by otawa::dcache::BlockAccess::in(), otawa::dcache::BlockBuilder::processBB(), otawa::dcache::CATBuilder::processLBlockSet(), otawa::dcache::MUSTProblem::purge(), otawa::dcache::MUSTPERS::update(), otawa::dcache::MUSTProblem::update(), otawa::dcache::MAYProblem::update(), and otawa::dcache::DirtyManager::update().
void otawa::dcache::Block::print (io::Output & out) const
Print a block.
Referenced by otawa::dcache::operator<<().
int otawa::dcache::Block::set (void) const inline
Get the set number of a block.
Returns
Set number.
Referenced by otawa::dcache::operator<<(), otawa::dcache::BlockBuilder::processBB(), otawa::dcache::CATBuilder::processLBlockSet(), otawa::dcache::MUSTProblem::purge(), otawa::dcache::PERSProblem::purge(), otawa::dcache::MUSTPERS::update(), otawa::dcache::MUSTProblem::update(), otawa::dcache::MAYProblem::update(), and otawa::dcache::DirtyManager::update().
Member Data Documentation
int otawa::dcache::Block::_set private
Address otawa::dcache::Block::addr private
int otawa::dcache::Block::idx private
The documentation for this class was generated from the following files:
include/otawa/dcache/features.h
src/dcache/dcache_BlockBuilder.cpp