Otawa: otawa::MemArea Class Reference
otawa::MemArea Class Reference
Utility class representing an area in the memory defined by a base address and a size.
#include <otawa/base.h>
Public Member Functions
MemArea (void)
Build a null mem area.
MemArea (const MemArea &a)
MemArea (const Address &base, ot::size size)
MemArea (const Address &base, const Address &top)
MemArea::MemArea(const MemArea& a); Copy an existing mem area.
Address address (void) const
Get the base address of the area.
ot::size size (void) const
Get the size of the area.
Address topAddress (void) const
Get the top address of the area, that is, the address of the first byte after the area.
Address lastAddress (void) const
Get the last address of the area, that is, the address of the last byte in the area.
bool isNull (void) const
Test if the area is null.
bool isEmpty (void) const
Test whether the area is empty, that is, whether the size is null.
bool contains (const Address &addr) const
Test whether the area contains the given address.
bool equals (const MemArea &a) const
Test wether the current area and the given one are equal.
bool includes (const MemArea &a) const
Test if the current mem area includes (not strictly) the given one.
bool meets (const MemArea &a) const
Test if the current memory area meets at least one byte of the given one.
MemArea meet (const MemArea &a) const
Build the intersection of both memory areas.
MemArea join (const MemArea &a) const
Build a memory area that is the inclusive join of both memory areas.
void set (const MemArea &a)
void move (const Address &base)
void moveTop (const Address &top)
void resize (const ot::size size)
operator bool (void) const
bool operator== (const MemArea &a) const
bool operator!= (const MemArea &a) const
bool operator>= (const MemArea &a) const
bool operator> (const MemArea &a) const
bool operator< (const MemArea &a) const
bool operator<= (const MemArea &a) const
MemArea operator& (const MemArea &a) const
MemArea operator+ (const MemArea &a) const
MemArea operator= (const MemArea &a)
void operator&= (const MemArea &a)
void operator+= (const MemArea &a)
Static Public Attributes
static MemArea null
Null memory area.
Private Attributes
Address _base
ot::size _size
Detailed Description
Utility class representing an area in the memory defined by a base address and a size.
Constructor & Destructor Documentation
otawa::MemArea::MemArea (void) inline
Build a null mem area.
otawa::MemArea::MemArea (const MemArea & a) inline
otawa::MemArea::MemArea (const Address & base, ot::size size) inline
otawa::MemArea::MemArea (const Address & base, const Address & top) inline
MemArea::MemArea(const MemArea& a); Copy an existing mem area.
Parameters
a Area to copy. MemArea::MemArea(const Address& base, ot::size size); Build a memory area.
base Base address of the area.
size Size of the area (in bytes).
Build a memory area.
Parameters
base Base address of the area.
top Top address, that is, address of the first byte past the area.
Member Function Documentation
Address otawa::MemArea::address (void) const inline
Get the base address of the area.
Returns
Base address.
Referenced by includes(), join(), meet(), meets(), otawa::operator<<(), otawa::FlowFactLoader::scanIgnoreControl(), otawa::FlowFactLoader::scanIgnoreSeq(), otawa::FlowFactLoader::scanMemAccess(), otawa::FlowFactLoader::scanMemSet(), otawa::FlowFactLoader::scanMultiBranch(), otawa::FlowFactLoader::scanMultiCall(), otawa::FlowFactLoader::scanNoInline(), otawa::FlowFactLoader::scanSetInlining(), otawa::FlowFactLoader::scanValue(), otawa::FlowFactLoader::scanXBody(), otawa::FlowFactLoader::scanXCall(), otawa::FlowFactLoader::scanXFun(), and otawa::FlowFactLoader::scanXLoop().
bool otawa::MemArea::contains (const Address & addr) const inline
Test whether the area contains the given address.
Parameters
addr Address to test.
Returns
True if the address is in the area, false else.
bool otawa::MemArea::equals (const MemArea & a) const inline
Test wether the current area and the given one are equal.
Parameters
a Area to test equality for.
Returns
True if both areas are equal, false else.
References _base, and _size.
bool otawa::MemArea::includes (const MemArea & a) const
Test if the current mem area includes (not strictly) the given one.
Parameters
a Memory area tested for inclusion.
Returns
True if the current memory area contains the a memory area.
References otawa::ot::address(), address(), and lastAddress().
Referenced by operator<(), and operator<=().
bool otawa::MemArea::isEmpty (void) const inline
Test whether the area is empty, that is, whether the size is null.
Returns
True if the size is null, false else.
bool otawa::MemArea::isNull (void) const inline
Test if the area is null.
Returns
True if the area is null, false else.
Referenced by otawa::operator<<(), otawa::FlowFactLoader::scanIgnoreControl(), otawa::FlowFactLoader::scanIgnoreSeq(), otawa::FlowFactLoader::scanMultiBranch(), otawa::FlowFactLoader::scanMultiCall(), otawa::FlowFactLoader::scanNoInline(), and otawa::FlowFactLoader::scanSetInlining().
MemArea otawa::MemArea::join (const MemArea & a) const
Build a memory area that is the inclusive join of both memory areas.
Parameters
a Memory area to join with.
Returns
Result of inclusive join.
References otawa::ot::address(), address(), lastAddress(), otawa::clp::max(), otawa::clp::min(), and null.
Referenced by otawa::FlowFactLoader::addressOf(), and otawa::FlowFactLoader::scanMemAccess().
Address otawa::MemArea::lastAddress (void) const inline
Get the last address of the area, that is, the address of the last byte in the area.
Returns
Area last address.
Referenced by includes(), join(), meet(), meets(), otawa::FlowFactLoader::scanIgnoreControl(), otawa::FlowFactLoader::scanIgnoreSeq(), otawa::FlowFactLoader::scanMultiBranch(), otawa::FlowFactLoader::scanMultiCall(), otawa::FlowFactLoader::scanNoInline(), and otawa::FlowFactLoader::scanSetInlining().
MemArea otawa::MemArea::meet (const MemArea & a) const
Build the intersection of both memory areas.
Parameters
a Memory area to meet with.
Returns
Result of meet.
References otawa::ot::address(), address(), lastAddress(), otawa::clp::max(), and otawa::clp::min().
bool otawa::MemArea::meets (const MemArea & a) const
Test if the current memory area meets at least one byte of the given one.
Parameters
a Memory area to test.
Returns
True if there is, at least, one byte in common between both memory areas.
References otawa::ot::address(), address(), and lastAddress().
void otawa::MemArea::move (const Address & base) inline
References otawa::p::base.
void otawa::MemArea::moveTop (const Address & top) inline
otawa::MemArea::operator bool (void) const inline
bool otawa::MemArea::operator!= (const MemArea & a) const inline
MemArea otawa::MemArea::operator& (const MemArea & a) const inline
void otawa::MemArea::operator&= (const MemArea & a) inline
MemArea otawa::MemArea::operator+ (const MemArea & a) const inline
void otawa::MemArea::operator+= (const MemArea & a) inline
bool otawa::MemArea::operator< (const MemArea & a) const inline
References includes().
bool otawa::MemArea::operator<= (const MemArea & a) const inline
References includes().
MemArea otawa::MemArea::operator= (const MemArea & a) inline
bool otawa::MemArea::operator== (const MemArea & a) const inline
bool otawa::MemArea::operator> (const MemArea & a) const inline
bool otawa::MemArea::operator>= (const MemArea & a) const inline
void otawa::MemArea::resize (const ot::size size) inline
void otawa::MemArea::set (const MemArea & a) inline
References _base, and _size.
ot::size otawa::MemArea::size (void) const inline
Get the size of the area.
Returns
Area size (in bytes).
Address otawa::MemArea::topAddress (void) const inline
Get the top address of the area, that is, the address of the first byte after the area.
Returns
Area top address.
Referenced by otawa::operator<<(), and otawa::FlowFactLoader::scanMemAccess().
Member Data Documentation
Address otawa::MemArea::_base private
Referenced by equals(), and set().
ot::size otawa::MemArea::_size private
Referenced by equals(), and set().
MemArea otawa::MemArea::null static
Null memory area.
Referenced by otawa::FlowFactLoader::addressOf(), join(), and otawa::FlowFactLoader::scanAddress().
The documentation for this class was generated from the following files:
include/otawa/base.h
src/prog/base.cpp