Otawa: otawa::etime::EventCollector Class Reference
otawa::etime::EventCollector Class Reference
Collects variables linking events with blocks in ILP.
#include <otawa/etime/EventCollector.h>
Public Types
enum case_t {
PREFIX_OFF = 0, PREFIX_ON = 1, BLOCK_OFF = 2, BLOCK_ON = 3,
SIZE = 4
}
Public Member Functions
EventCollector (Event *event)
Event * event (void) const
void contribute (case_t c, ilp::Var *var)
Add a variable contribution.
void make (ilp::System *sys)
Make the variable and constraint for the current event.
Private Member Functions
bool isOn (case_t c)
Test if the event is on or off.
Private Attributes
t::uint32 imprec
Event * evt
genstruct::SLList< ilp::Var * > vars [SIZE]
Detailed Description
Collects variables linking events with blocks in ILP.
Member Enumeration Documentation
enum otawa::etime::EventCollector::case_t
Enumerator
PREFIX_OFF
PREFIX_ON
BLOCK_OFF
BLOCK_ON
SIZE
Constructor & Destructor Documentation
otawa::etime::EventCollector::EventCollector (Event * event) inline
Member Function Documentation
void otawa::etime::EventCollector::contribute (case_t c, ilp::Var * var)
Add a variable contribution.
Parameters
c Case of contribution.
var Variable of contribution (null for blurred contribution driving to estimation).
Referenced by event().
Event* otawa::etime::EventCollector::event (void) const inline
References contribute(), evt, isOn(), and make().
bool otawa::etime::EventCollector::isOn (case_t c) inline private
Test if the event is on or off.
Parameters
c Case to test.
Returns
True if on, false if off.
Referenced by event().
void otawa::etime::EventCollector::make (ilp::System * sys)
Make the variable and constraint for the current event.
According to the variable list and the provided overestimation, may generate zero, one or several constraints.
Parameters
sys System to create constraints in.
References otawa::ilp::Constraint::addRight(), otawa::etime::EDGE, otawa::ilp::Constraint::GE, and otawa::ilp::System::newConstraint().
Referenced by event().
Member Data Documentation
Event* otawa::etime::EventCollector::evt private
Referenced by event().
t::uint32 otawa::etime::EventCollector::imprec private
genstruct::SLList<ilp::Var *> otawa::etime::EventCollector::vars[SIZE] private
The documentation for this class was generated from the following files:
include/otawa/etime/EventCollector.h
src/etime/EdgeTimeBuilder.cpp