Otawa: otawa::hard::FunctionalUnit::Make Class Reference
otawa::hard::FunctionalUnit::Make Class Reference
#include <otawa/hard/Processor.h>
Public Member Functions
Make (string name="")
Make & latency (int l)
Make & width (int w)
Make & do_branch (void)
Make & access_mem (void)
Make & is_pipelined (void)
Private Attributes
bool _pipelined
Friends
class FunctionalUnit
Constructor & Destructor Documentation
otawa::hard::FunctionalUnit::Make::Make (string name = "") inline
Member Function Documentation
Make& otawa::hard::FunctionalUnit::Make::access_mem (void) inline
References otawa::hard::PipelineUnit::Make::access_mem().
Make& otawa::hard::FunctionalUnit::Make::do_branch (void) inline
References otawa::hard::PipelineUnit::Make::do_branch().
Make& otawa::hard::FunctionalUnit::Make::is_pipelined (void) inline
Make& otawa::hard::FunctionalUnit::Make::latency (int l) inline
References otawa::hard::PipelineUnit::Make::latency().
Make& otawa::hard::FunctionalUnit::Make::width (int w) inline
References otawa::hard::PipelineUnit::Make::width().
Friends And Related Function Documentation
friend class FunctionalUnit friend
Member Data Documentation
bool otawa::hard::FunctionalUnit::Make::_pipelined private
The documentation for this class was generated from the following file:
include/otawa/hard/Processor.h