Otawa: otawa::FlowFactLoader Class Reference
otawa::FlowFactLoader Class Reference
Flow Facts
This class is an abstract class to monitor the load of flow facts.
#include <otawa/util/FlowFactLoader.h>
Public Types
enum log_level_t {
LOG_NONE = 0, LOG_PROC = 1, LOG_FILE = 2, LOG_DEPS = LOG_FILE,
LOG_FUN = 3, LOG_CFG = LOG_FUN, LOG_BLOCK = 4, LOG_BB = LOG_BLOCK,
LOG_INST = 5
}
typedef enum otawa::Monitor::log_level_t log_level_t
Public Member Functions
FlowFactLoader (p::declare &r=reg)
Build a flow fact loader for the given executable file.
elm::String name (void) const
elm::Version version (void) const
void process (WorkSpace *ws, const PropList &props=PropList::EMPTY)
Execute the code processor on the given framework.
WorkSpace * workspace (void)
Get the current workspace.
bool isVerbose (void) const
Test if the verbosity is activated.
bool logFor (log_level_t tested) const
Test if the given log level is activated or not.
log_level_t logLevel (void) const
Public Attributes
elm::io::Output out
Provide a stream to perform output for the user.
elm::io::Output log
Provide a stream to perform log output.
Static Public Attributes
static p::declare reg
static Identifier< PropList * > STATS
This property identifiers is used to pass a property list to the processor that will be used to store statistics about the performed work.
static Identifier< bool > TIMED
If the value of the associated property is true (default to false), time statistics will also be collected with other processor statistics.
static Identifier< bool > RECURSIVE
static Identifier< Progress * > PROGRESS
Install.
static Identifier< bool > COLLECT_STATS
This property allows to activate collection of statistics for the work of the current processor.
static Identifier< elm::io::OutStream * > & OUTPUT = otawa::OUTPUT
This property identifier is used for setting the output stream used by the processor to write results.
static Identifier< elm::io::OutStream * > & LOG = otawa::LOG
This property identifier is used for setting the log stream used by the processor to write messages (information, warning, error).
static Identifier< bool > & VERBOSE = otawa::VERBOSE
This property activates the verbose mode of the processor: information about the processor work will be displayed.
static Identifier< log_level_t > & LOG_LEVEL = otawa::LOG_LEVEL
Property passed in the configuration property list of a processor to select the log level between LOG_PROC, LOG_CFG or LOG_BB.
static Identifier< elm::system::time_t > RUNTIME
This property identifier is used to store in the statistics of a processor the overall run time of the processor work.
static Monitor & null = __null_mon
Monitor that output nothing.
Protected Member Functions
WorkSpace * workSpace (void) const
Address addressOf (const string &label)
Get the address of the given label.
MemArea addressOf (const string &file, int line) throw (ProcessorException)
Get the address matching the given source file name and line.
void onError (const string &message)
This method is called when an error is encountered.
void onWarning (const string &message)
This method is called when a warning need to be displayed.
virtual void onCheckSum (const String &name, t::uint32 sum)
Check the consistency of the flow facts with the executable.
virtual void onLibrary (void)
Called to inform that the current FFX file is a library.
virtual void onLoop (address_t addr, int count, int total, const ContextualPath &path)
This method is called when a loop is found.
virtual void onReturn (address_t addr)
This method is called each a "return" statement is found.
virtual void onNoReturn (address_t addr)
This method is called each time a "noreturn ADDRESS" statement is found.
virtual void onNoReturn (String name)
This method is called each time a "noreturn NAME" statement is found.
virtual void onNoCall (Address address)
Called for the F4 production: "nocall ADDRESS".
virtual void onNoInline (Address address, bool no_inline, const ContextualPath &path)
Called for the F4 production: "noinline ADDRESS" or "inline ADDRESS".
virtual void onIgnoreSeq (Address address)
Called for the F4 construction "ignoreseq ADDRESS".
virtual void onIgnoreControl (Address address)
Called for the F4 construction "ignorecontrol ADDRESS".
virtual void onMultiBranch (Address control, const Vector< Address > &target)
Called for the F4 construction "multibranch ADDRESS to ADDRESS, ...".
virtual void onMultiCall (Address control, const Vector< Address > &target)
Called for the F4 construction "multicall ADDRESS to ADDRESS, ...".
virtual void onPreserve (Address address)
Called for the F4 production: "preserver ADDRESS".
virtual void onIgnoreEntry (string name)
Called when an "ignore entry" command is found.
virtual void onUnknownLoop (Address addr)
This method is called each the production "loop ADDRESS ?" is found.
virtual void onUnknownMultiBranch (Address control)
This method is called each the production "multibranch ADDRESS to ?" is found.
virtual void onUnknownMultiCall (Address control)
This method is called each the production "multicall ADDRESS to ?" is found.
virtual void onMemoryAccess (Address iaddr, Address lo, Address hi, const ContextualPath &path)
Load a memory range instruction.
virtual void onRegSet (string name, const dfa::Value &value)
Called when a register set is found.
virtual void onMemSet (Address addr, const Type *type, const dfa::Value &value)
Called to set a memory initialization.
virtual void onSetInlining (Address address, bool policy, const ContextualPath &path)
Called for the F4 production: "inlining-on ADDRESS" or "inlining-off ADDRESS".
virtual void processWorkSpace (WorkSpace *ws)
Process the given framework.
virtual void configure (const PropList &props)
This method may be called for configuring a processor thanks to information passed in the property list.
virtual void setup (WorkSpace *ws)
This method is called before an anlysis to let the processor do some initialization.
bool isTimed (void) const
Test if the timed mode is activated (recording of timings in the statistics).
bool recordsStats (void) const
Test if the statictics mode is activated.
bool isAllocated (void) const
bool isPrepared (void) const
bool isCollectingStats (void) const
void require (const AbstractFeature &feature)
Usually called from a processor constructor, this method records a required feature for the work of the current processor.
void provide (const AbstractFeature &feature)
Usually called from a processor constructor, this method records a feature provided by the work of the current processor.
void invalidate (const AbstractFeature &feature)
Usually called from a processor constructor, this method records a feature invalidated by the work of the current processor.
void use (const AbstractFeature &feature)
Usually called from a processor constructor, this method records a feature as used by the work of the current processor.
void warn (const String &message)
Display a warning.
WorkSpace * workspace (void) const
Get the current workspace.
Progress & progress (void)
Get the current progress handler.
void recordStat (const AbstractFeature &feature, StatCollector *collector)
Add a statistics collector to the current workspace collection.
void addCleaner (const AbstractFeature &feature, Cleaner *cleaner)
Add a cleaner for the given feature.
template<class T >
void addRemover (const AbstractFeature &feature, const Ref< T, Identifier< T > > &ref)
template<class T >
void addDeletor (const AbstractFeature &feature, const Ref< T *, Identifier< T * > > &ref)
virtual void prepare (WorkSpace *ws)
This method called to let the processor customize its requirements according to some generic feature.
virtual void cleanup (WorkSpace *ws)
This method is called after the end of the processor analysis to let it do some clean up.
virtual void collectStats (WorkSpace *ws)
This method is invoked if the user has required to collect statistics about the processor.
virtual void processFrameWork (WorkSpace *fw)
Process the given workspace.
template<class T >
T * track (const AbstractFeature &feature, T *object)
template<class T >
void track (const AbstractFeature &feature, const Ref< T *, Identifier< T * > > &ref)
Track the release of an allocated object assigned to an identifier relatively to the given feature.
template<class T >
void track (const AbstractFeature &feature, const Ref< T *, const Identifier< T * > > &ref)
Track the release of an allocated object assigned to an identifier relatively to the given feature.
virtual void requireDyn (WorkSpace *ws, const PropList &props)
Method called after registration requirements to support dynamic requirements.
void setWorkspace (WorkSpace *workspace)
Set the current workspace.
Protected Attributes
PropList * stats
t::uint32 flags
Contains various bit flags.
Static Protected Attributes
static const t::uint32 IS_TIMED = 0x01 << CUSTOM_SHIFT
static const t::uint32 IS_ALLOCATED = 0x04 << CUSTOM_SHIFT
static const t::uint32 IS_PREPARED = 0x08 << CUSTOM_SHIFT
static const t::uint32 IS_COLLECTING = 0x10 << CUSTOM_SHIFT
static const t::uint32 IS_VERBOSE = 0x01
static const t::uint32 CUSTOM_SHIFT = 16
Private Member Functions
friend int::util_fft_parse (FlowFactLoader *loader)
friend void::util_fft_error (otawa::FlowFactLoader *loader, const char *msg)
void loadF4 (const string &path) throw (ProcessorException)
Load an F4 file.
void load (WorkSpace *ws, const Path &path)
Load flow facts from the given file.
void loadXML (const string &path) throw (ProcessorException)
Load the flow facts from an XML file.
void scanXLoop (xom::Element *element, ContextualPath &path) throw (ProcessorException)
Scan a loop XML element.
void scanXFun (xom::Element *element, ContextualPath &path) throw (ProcessorException)
Scan a function XML element.
void scanXConditional (xom::Element *element, ContextualPath &path) throw (ProcessorException)
Called to scan an "if" element.
MemArea scanAddress (xom::Element *element, ContextualPath &path, bool call=false) throw (ProcessorException)
Retrieve the address of an element (function, loop, ...) from its XML element.
int findCall (cstring file, int line, Address &r)
Look in the instruction matching the given (file, line) location for a call.
Option< long > scanInt (xom::Element *element, cstring name) throw (ProcessorException)
Scan an integer attribute.
Option< unsigned long > scanUInt (xom::Element *element, cstring name) throw (ProcessorException)
Option< long > scanBound (xom::Element *element, cstring name) throw (ProcessorException)
Scan a a bound attribute.
void scanXContent (xom::Element *element, ContextualPath &path) throw (ProcessorException)
Scan the content of 'function' or of a 'loop'.
void scanXBody (xom::Element *element, ContextualPath &path) throw (ProcessorException)
Supports an XML flow fact content.
void scanXCall (xom::Element *element, ContextualPath &path) throw (ProcessorException)
Scan a call element that may have possibly two forms:
string xline (xom::Node *element)
Build an XML element position for user.
void scanNoInline (xom::Element *element, ContextualPath &cpath, bool no_inline)
Scan a noinline/doinline XML element.
void scanIgnoreEntry (xom::Element *element)
Called when an "ignore-entry" elemet is found.
void scanMultiBranch (xom::Element *element, ContextualPath &cpath)
Scan a multibranch XML element composed of items with a different location each.
void scanMultiCall (xom::Element *element, ContextualPath &cpath)
Scan a multicall XML element composed of items with a different location each.
void scanIgnoreControl (xom::Element *element, ContextualPath &cpath)
Scan a ignorecontrol XML element.
void scanIgnoreSeq (xom::Element *element, ContextualPath &cpath)
Scan a ignoreseq XML element.
dfa::Value scanValue (xom::Element *element)
Scan a value in the given element.
void scanMemAccess (xom::Element *element)
Scan for a memory access instruction.
void scanRegSet (xom::Element *element)
Load a register set instruction.
void scanMemSet (xom::Element *element)
Load a memory set.
void scanSetInlining (xom::Element *element, ContextualPath &cpath, bool policy)
Scan a inlining-off/inlining-on XML element.
Private Attributes
WorkSpace * _fw
bool checksummed
genstruct::Vector< Path > paths
genstruct::Vector< xom::Element * > nodes
Path current
bool mandatory
bool lines_available
dfa::State * state
bool lib
Detailed Description
This class is an abstract class to monitor the load of flow facts.
To get simple access to the flow fact files, a new class must be inherited from this class and this class must implement the virtual "onXXX" methods.
Required Features
dfa::INITIAL_STATE_FEATURE
Provided features
otawa::FLOW_FACTS_FEATURE
otawa::MKFF_PRESERVATION_FEATURE
Configuration
otawa::FLOW_FACTS_PATH – select the flow fact to load (if not present, the flow fact name is obtained by replacing extension or by appending ".ff" or ".ffx").
otawa::FLOW_FACTS_MANDATORY – if set to true, the processing fails if one loop bound is not available (default to false).
See also
F4 : Flow Facts File Format for more details on the flow facts files.
Author
H. Cass casse.nosp@m.@iri.nosp@m.t.fr
Member Typedef Documentation
typedef enum otawa::Monitor::log_level_t otawa::Monitor::log_level_t inherited
Member Enumeration Documentation
enum otawa::Monitor::log_level_t inherited
Enumerator
LOG_NONE
LOG_PROC
LOG_FILE
LOG_DEPS
LOG_FUN
LOG_CFG
LOG_BLOCK
LOG_BB
LOG_INST
Constructor & Destructor Documentation
otawa::FlowFactLoader::FlowFactLoader (p::declare & r = reg)
Build a flow fact loader for the given executable file.
Member Function Documentation
void otawa::Processor::addCleaner (const AbstractFeature & feature, Cleaner * cleaner) inline protected inherited
Add a cleaner for the given feature.
A cleaner is an object with a virtual destructor that is called when the associated feature is removed: this let the processor to release and clean up the resources it allocated to implement the provided features.
Parameters
feature Feature the cleaner apply to.
cleaner Cleaner to add.
Referenced by otawa::DelayedBuilder::cleanup(), otawa::StackAnalysis::cleanup(), otawa::Dominance::processCFG(), otawa::clp::Analysis::processWorkSpace(), and otawa::Processor::recordStat().
template<class T > void otawa::Processor::addDeletor (const AbstractFeature & feature, const Ref< T *, Identifier< T * > > & ref) inline protected inherited
Referenced by otawa::Virtualizer::cleanup().
template<class T > void otawa::Processor::addRemover (const AbstractFeature & feature, const Ref< T, Identifier< T > > & ref) inline protected inherited
Referenced by otawa::Virtualizer::cleanup().
Address otawa::FlowFactLoader::addressOf (const string & label) protected
Get the address of the given label.
Parameters
label Label to look for.
Returns
Matching address or null address if not found.
References _fw, otawa::Process::findLabel(), otawa::Address::isNull(), lib, otawa::Address::null, onWarning(), and otawa::WorkSpace::process().
Referenced by scanAddress(), and scanXFun().
MemArea otawa::FlowFactLoader::addressOf (const string & file, int line) throw (ProcessorException) protected
Get the address matching the given source file name and line.
Parameters
file Source file path.
line Line in the source file.
Returns
Matching first address.
Exceptions
ProcessorException If the file/line cannot be resolved to an address.
References otawa::ACCESS_RANGE, otawa::BRANCH_TARGET, otawa::CALL_TARGET, otawa::FLOW_FACTS_FEATURE, otawa::FLOW_FACTS_MANDATORY, otawa::FLOW_FACTS_NODES, otawa::FLOW_FACTS_PATH, otawa::Process::getAddresses(), otawa::IGNORE_CONTROL, otawa::IGNORE_ENTRY, otawa::IGNORE_SEQ, otawa::INLINING_POLICY, otawa::IS_RETURN, otawa::MemArea::join(), lines_available, otawa::Monitor::log, otawa::Monitor::LOG_DEPS, otawa::Monitor::logFor(), otawa::MAX_ITERATION, otawa::MIN_ITERATION, otawa::MKFF_PRESERVATION_FEATURE, otawa::NO_CALL, otawa::NO_INLINE, otawa::NO_RETURN, otawa::MemArea::null, onError(), otawa::PRESERVED, otawa::WorkSpace::process(), otawa::TOTAL_ITERATION, otawa::Processor::warn(), and workSpace().
void otawa::Processor::cleanup (WorkSpace * ws) protected virtual inherited
This method is called after the end of the processor analysis to let it do some clean up.
Parameters
ws Workspace to work on.
Reimplemented in otawa::AccessedAddressFromStack, otawa::Virtualizer, otawa::tsim::Delta, otawa::CFGSaver, otawa::DelayedBuilder, otawa::etime::EdgeTimeBuilder, otawa::StackAnalysis, otawa::LBlockBuilder, otawa::ccg::LBlockBuilder, otawa::SubCFGBuilder, otawa::dcache::CLPBlockBuilder, otawa::ipet::VarAssignment, otawa::BBRatioDisplayer, otawa::branch::CondNumber, otawa::CFGBuilder, otawa::tsim::BBTimeSimulator, otawa::LoopUnroller, otawa::CFGChecker, otawa::dcache::CATBuilder, otawa::ilp::Output, otawa::CFGCollector, otawa::ipet::FlowFactLoader, otawa::ipet::TrivialInstCacheManager, and otawa::ipet::WCETCountRecorder.
Referenced by otawa::Processor::process().
void otawa::Processor::collectStats (WorkSpace * ws) protected virtual inherited
This method is invoked if the user has required to collect statistics about the processor.
In its default implementation, this method does nothing but it may be customized if the current implementation provides statistics. It is called after the main computation of the processor.
Statistics must be objects inheriting from the class StatCollector and recorded with method recordStat().
Parameters
ws Current workspace.
Reimplemented in otawa::dcache::CatConstraintBuilder, otawa::ipet::WCETComputation, and otawa::CAT2OnlyConstraintBuilder.
Referenced by otawa::Processor::process().
void otawa::FlowFactLoader::configure (const PropList & props) protected virtual
This method may be called for configuring a processor thanks to information passed in the property list.
Parameters
props Configuration information.
Reimplemented from otawa::Processor.
References otawa::Processor::configure(), otawa::FLOW_FACTS_MANDATORY, otawa::FLOW_FACTS_NODES, otawa::FLOW_FACTS_PATH, mandatory, nodes, and paths.
int otawa::FlowFactLoader::findCall (cstring file, int line, Address & r) private
Look in the instruction matching the given (file, line) location for a call.
Parameters
file Source file path.
line Source file line.
r Address of the found call instruction.
Returns
Number of found calls.
References otawa::ProgItem::address(), otawa::WorkSpace::findInstAt(), otawa::Process::getAddresses(), otawa::Inst::isCall(), otawa::WorkSpace::process(), otawa::ProgItem::topAddress(), and otawa::Processor::workspace().
Referenced by scanAddress().
otawa::FlowFactLoader::int::util_fft_parse (FlowFactLoader * loader) private
void otawa::Processor::invalidate (const AbstractFeature & feature) protected inherited
Usually called from a processor constructor, this method records a feature invalidated by the work of the current processor.
Parameters
feature Invalidated feature.
References otawa::Processor::_reg, otawa::AbstractRegistration::features, otawa::Monitor::flags, otawa::FeatureUsage::invalidate, otawa::Processor::IS_ALLOCATED, otawa::Processor::isAllocated(), and otawa::Processor::isPrepared().
Referenced by otawa::LoopReductor::LoopReductor().
bool otawa::Processor::isAllocated (void) const inline protected inherited
Referenced by otawa::Processor::invalidate(), otawa::Processor::provide(), otawa::Processor::require(), and otawa::Processor::use().
bool otawa::Processor::isCollectingStats (void) const inline protected inherited
References otawa::p::invalidate, otawa::p::provide, otawa::p::require, and otawa::p::use.
Referenced by otawa::Processor::process(), and otawa::Processor::recordStat().
bool otawa::Processor::isPrepared (void) const inline protected inherited
Referenced by otawa::Processor::invalidate(), otawa::Processor::process(), otawa::Processor::provide(), otawa::Processor::require(), and otawa::Processor::use().
bool otawa::Processor::isTimed (void) const inline protected inherited
Test if the timed mode is activated (recording of timings in the statistics).
Returns
True if timed mode is activated, false else.
Note
If statistics are not activated, this method returns ever false.
Referenced by otawa::Processor::process().
bool otawa::Monitor::isVerbose (void) const inline inherited
Test if the verbosity is activated.
Returns
True if verbosity is activated, false else.
Referenced by otawa::ccg::LBlockBuilder::addLBlock(), otawa::LBlockBuilder::addLBlock(), otawa::GraphBBTime< G >::analyzePathContext(), otawa::etime::EdgeTimeBuilder::applyFloppySplit(), otawa::etime::EdgeTimeBuilder::applyStrictSplit(), otawa::etime::EdgeTimeBuilder::applyWeightedSplit(), otawa::etime::EdgeTimeBuilder::makeSplit(), otawa::GraphBBTime< G >::processBB(), otawa::etime::EdgeTimeBuilder::processSequence(), and otawa::dcache::BlockBuilder::setup().
void otawa::FlowFactLoader::load (WorkSpace * ws, const Path & path) private
Load flow facts from the given file.
Parameters
ws Current workspace.
path Path to the file to load flow facts from.
References checksummed, current, loadF4(), loadXML(), otawa::Monitor::log, otawa::Monitor::LOG_DEPS, otawa::Monitor::logFor(), and otawa::Processor::warn().
Referenced by processWorkSpace().
void otawa::FlowFactLoader::loadF4 (const string & path) throw (ProcessorException) private
Load an F4 file.
Parameters
path Path of the file.
References otawa::Monitor::log, otawa::Monitor::LOG_DEPS, otawa::Monitor::logFor(), mandatory, util_fft_in, util_fft_parse(), and otawa::Processor::warn().
Referenced by load().
void otawa::FlowFactLoader::loadXML (const string & path) throw (ProcessorException) private
Load the flow facts from an XML file.
Parameters
path Path of the XML file.
References scanXBody().
Referenced by load().
bool otawa::Monitor::logFor (log_level_t tested) const inline inherited
Test if the given log level is activated or not.
Parameters
tested Tested log level.
Returns
True if the log level is activated, false else.
Referenced by otawa::CFGBuilder::addCFG(), otawa::ipet::ConstraintLoader::addConstraint(), otawa::PFGBuilder::addFunction(), addressOf(), otawa::etime::EdgeTimeBuilder::applyWeightedSplit(), otawa::DelayedBuilder::buildBB(), otawa::CFGBuilder::buildCFG(), otawa::DelayedBuilder::buildEdges(), otawa::branch::BranchBuilder::categorize(), otawa::ipet::FlowFactLoader::cleanup(), otawa::dcache::CATBuilder::cleanup(), otawa::DelayedBuilder::cloneEdge(), otawa::CAT2Builder::configure(), otawa::ACSBuilder::configure(), otawa::etime::EdgeTimeBuilder::genForOneCost(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::Processor::init(), load(), loadF4(), otawa::script::Script::makeConfig(), otawa::CFGBuilder::nextBB(), onLoop(), onMemoryAccess(), onNoInline(), onReturn(), onSetInlining(), otawa::Processor::process(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::branch::CondNumber::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::dcache::CLPBlockBuilder::processBB(), otawa::etime::StandardEventBuilder::processBB(), otawa::dcache::BlockBuilder::processBB(), otawa::CFGCheckSummer::processCFG(), otawa::EdgeProcessor::processCFG(), otawa::CAT2Builder::processCFG(), otawa::display::CFGOutput::processCFG(), otawa::ipet::ConstraintLoader::processCFG(), otawa::ContextualProcessor::processCFG(), otawa::BBProcessor::processCFG(), otawa::etime::EdgeTimeBuilder::processEdge(), otawa::VarTextDecoder::processEntry(), otawa::dcache::CATBuilder::processLBlockSet(), otawa::ACSMayBuilder::processLBlockSet(), otawa::CAT2Builder::processLBlockSet(), otawa::dcache::ACSBuilder::processLBlockSet(), otawa::etime::EdgeTimeBuilder::processSequence(), otawa::VarTextDecoder::processWorkSpace(), otawa::TextDecoder::processWorkSpace(), otawa::LBlockProcessor::processWorkSpace(), otawa::FixedTextDecoder::processWorkSpace(), otawa::ipet::WCETComputation::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), otawa::PFGBuilder::processWorkSpace(), otawa::StackAnalysis::processWorkSpace(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::branch::BranchBuilder::processWorkSpace(), otawa::CFGProcessor::processWorkSpace(), otawa::Virtualizer::processWorkSpace(), otawa::clp::Analysis::processWorkSpace(), otawa::script::Script::processWorkSpace(), otawa::ilp::Output::setup(), otawa::CFGBuilder::setup(), otawa::BBRatioDisplayer::setup(), otawa::dcache::BlockBuilder::setup(), otawa::CFGBuilder::thisBB(), otawa::ipet::FlowFactLoader::transfer(), otawa::Virtualizer::virtualize(), and otawa::script::Script::work().
log_level_t otawa::Monitor::logLevel (void) const inline inherited
Referenced by otawa::script::Script::declareGlobals().
elm::String otawa::Processor::name (void) const inline inherited
Referenced by otawa::Loader::check(), otawa::CFGCollector::configure(), otawa::display::ILPSystemDisplayer::displayVar(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::script::Script::makeConfig(), otawa::display::ILPSystemDisplayer::nameOf(), onCheckSum(), otawa::Processor::process(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::ccg::ConstraintBuilder::processLBlockSet(), otawa::Processor::Processor(), otawa::ipet::WCETComputation::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), scanBound(), scanIgnoreEntry(), scanInt(), scanMemSet(), scanRegSet(), scanUInt(), scanXBody(), scanXConditional(), scanXContent(), otawa::Processor::warn(), and otawa::script::Script::work().
void otawa::FlowFactLoader::onCheckSum (const String & name, t::uint32 sum) protected virtual
Check the consistency of the flow facts with the executable.
Parameters
name Concerned file name.
sum Flow fact checksum.
References _fw, checksummed, otawa::Processor::name(), onError(), and otawa::WorkSpace::process().
void otawa::FlowFactLoader::onError (const string & message) protected
This method is called when an error is encountered.
Parameters
message Message of the error.
Exceptions
ProcessorException With the given message and position in the file.
References current.
Referenced by addressOf(), onCheckSum(), onIgnoreControl(), onIgnoreSeq(), onLoop(), onMemoryAccess(), onMultiBranch(), onMultiCall(), onNoCall(), onNoInline(), onNoReturn(), onPreserve(), onRegSet(), onReturn(), onSetInlining(), onUnknownLoop(), onUnknownMultiBranch(), onUnknownMultiCall(), scanMemAccess(), scanMemSet(), scanRegSet(), and scanValue().
void otawa::FlowFactLoader::onIgnoreControl (Address address) protected virtual
Called for the F4 construction "ignorecontrol ADDRESS".
Parameters
address Address of the ignored instruction.
References _fw, otawa::Process::findInstAt(), otawa::IGNORE_CONTROL, onError(), and otawa::WorkSpace::process().
Referenced by scanIgnoreControl().
void otawa::FlowFactLoader::onIgnoreEntry (string name) protected virtual
Called when an "ignore entry" command is found.
This ensures that the symbol is not considered as a code entry during decoding phase.
Parameters
name Name of the symbol.
References otawa::IGNORE_ENTRY, lib, onWarning(), otawa::Processor::process(), and otawa::Processor::workspace().
Referenced by scanIgnoreEntry().
void otawa::FlowFactLoader::onIgnoreSeq (Address address) protected virtual
Called for the F4 construction "ignoreseq ADDRESS".
Parameters
address Address of the ignored instruction.
References _fw, otawa::Process::findInstAt(), otawa::IGNORE_SEQ, onError(), and otawa::WorkSpace::process().
Referenced by scanIgnoreSeq().
void otawa::FlowFactLoader::onLibrary (void) protected virtual
Called to inform that the current FFX file is a library.
The main effect is that, if a label cannot be resolved, the fact is simply skipped and it does not cause an error.
References lib.
void otawa::FlowFactLoader::onLoop (address_t addr, int count, int total, const ContextualPath & path) protected virtual
This method is called when a loop is found.
Parameters
addr Address of the header of the loop.
count Bound on the loop iterations.
References _fw, otawa::ProgItem::address(), otawa::Process::findInstAt(), otawa::Monitor::log, otawa::Monitor::LOG_BB, otawa::Monitor::logFor(), otawa::clp::max(), otawa::MAX_ITERATION, onError(), otawa::WorkSpace::process(), otawa::ContextualPath::ref(), and otawa::TOTAL_ITERATION.
Referenced by scanXLoop().
void otawa::FlowFactLoader::onMemoryAccess (Address iaddr, Address lo, Address hi, const ContextualPath & path) protected virtual
Load a memory range instruction.
Parameters
iaddr Instruction address.
lo Low address (inclusive).
hi High address (exclusive).
path Current context.
References _fw, otawa::ACCESS_RANGE, otawa::Process::findInstAt(), otawa::Monitor::log, otawa::Monitor::LOG_BB, otawa::Monitor::logFor(), onError(), otawa::WorkSpace::process(), and otawa::ContextualPath::ref().
Referenced by scanMemAccess().
void otawa::FlowFactLoader::onMemSet (Address addr, const Type * type, const dfa::Value & value) protected virtual
Called to set a memory initialization.
Parameters
addr Address to initialize.
type Type in memory.
value Value to set.
References otawa::dfa::State::record(), and state.
Referenced by scanMemSet().
void otawa::FlowFactLoader::onMultiBranch (Address control, const Vector< Address > & targets) protected virtual
Called for the F4 construction "multibranch ADDRESS to ADDRESS, ...".
Parameters
control Multi-branch instruction address.
target List of targets.
References _fw, otawa::BRANCH_TARGET, otawa::Process::findInstAt(), onError(), otawa::WorkSpace::process(), and otawa::cfgio::target().
Referenced by scanMultiBranch().
void otawa::FlowFactLoader::onMultiCall (Address control, const Vector< Address > & targets) protected virtual
Called for the F4 construction "multicall ADDRESS to ADDRESS, ...".
Parameters
control Multi-call instruction address.
target List of targets.
References _fw, otawa::CALL_TARGET, otawa::Process::findInstAt(), onError(), otawa::WorkSpace::process(), and otawa::cfgio::target().
Referenced by scanMultiCall().
void otawa::FlowFactLoader::onNoCall (Address address) protected virtual
Called for the F4 production: "nocall ADDRESS".
Parameters
address Address of the instruction to work on.
Exceptions
ProcessorException If the instruction cannot be found.
References _fw, otawa::Process::findInstAt(), otawa::NO_CALL, onError(), and otawa::WorkSpace::process().
Referenced by scanXBody().
void otawa::FlowFactLoader::onNoInline (Address address, bool no_inline, const ContextualPath & path) protected virtual
Called for the F4 production: "noinline ADDRESS" or "inline ADDRESS".
Parameters
address Address of the instruction to work on.
no_inline The boolean value to be set in NO_INLINE
Exceptions
ProcessorException If the instruction cannot be found.
References _fw, otawa::Process::findInstAt(), otawa::Monitor::log, otawa::Monitor::LOG_BB, otawa::Monitor::logFor(), otawa::NO_INLINE, onError(), otawa::WorkSpace::process(), and otawa::ContextualPath::ref().
Referenced by scanNoInline().
void otawa::FlowFactLoader::onNoReturn (address_t addr) protected virtual
This method is called each time a "noreturn ADDRESS" statement is found.
Parameters
addr Address of the entry of the function.
References _fw, otawa::Process::findInstAt(), otawa::NO_RETURN, onError(), and otawa::WorkSpace::process().
Referenced by scanXBody().
void otawa::FlowFactLoader::onNoReturn (String name) protected virtual
This method is called each time a "noreturn NAME" statement is found.
Parameters
name Name of the function.
References _fw, otawa::Process::findInstAt(), lib, otawa::NO_RETURN, and otawa::WorkSpace::process().
void otawa::FlowFactLoader::onPreserve (Address address) protected virtual
Called for the F4 production: "preserver ADDRESS".
Parameters
address Address of instruction to preserve.
Exceptions
ProcessorException If the instruction cannot be found.
References _fw, otawa::Process::findInstAt(), onError(), otawa::PRESERVED, and otawa::WorkSpace::process().
void otawa::FlowFactLoader::onRegSet (string name, const dfa::Value & value) protected virtual
Called when a register set is found.
Parameters
name Name of the register.
value Value to set.
References otawa::hard::Platform::findReg(), onError(), otawa::Process::platform(), otawa::WorkSpace::process(), reg, otawa::dfa::State::set(), state, and workSpace().
Referenced by scanRegSet().
void otawa::FlowFactLoader::onReturn (address_t addr) protected virtual
This method is called each a "return" statement is found.
Parameters
addr Address of the statement to mark as return.
References _fw, otawa::Process::findInstAt(), otawa::IS_RETURN, otawa::Monitor::log, otawa::Monitor::LOG_INST, otawa::Monitor::logFor(), onError(), and otawa::WorkSpace::process().
Referenced by scanXBody().
void otawa::FlowFactLoader::onSetInlining (Address address, bool policy, const ContextualPath & path) protected virtual
Called for the F4 production: "inlining-on ADDRESS" or "inlining-off ADDRESS".
Parameters
address Address of the instruction to work on.
policy The boolean value to be set in INLINING_POLICY
Exceptions
ProcessorException If the instruction cannot be found.
References _fw, otawa::Process::findInstAt(), otawa::INLINING_POLICY, otawa::Monitor::log, otawa::Monitor::LOG_BB, otawa::Monitor::logFor(), onError(), otawa::WorkSpace::process(), and otawa::ContextualPath::ref().
Referenced by scanSetInlining().
void otawa::FlowFactLoader::onUnknownLoop (Address addr) protected virtual
This method is called each the production "loop ADDRESS ?" is found.
It usually emit an error.
Parameters
addr Address of the loop entry.
References onError().
void otawa::FlowFactLoader::onUnknownMultiBranch (Address control) protected virtual
This method is called each the production "multibranch ADDRESS to ?" is found.
It usually emit an error.
Parameters
control Address of the control instruction.
References onError().
void otawa::FlowFactLoader::onUnknownMultiCall (Address control) protected virtual
This method is called each the production "multicall ADDRESS to ?" is found.
It usually emit an error.
Parameters
control Address of the control instruction.
References onError().
void otawa::FlowFactLoader::onWarning (const string & message) protected
This method is called when a warning need to be displayed.
Parameters
fmt Message.
References current, and otawa::Processor::warn().
Referenced by addressOf(), onIgnoreEntry(), scanIgnoreControl(), scanIgnoreEntry(), scanIgnoreSeq(), scanMultiBranch(), scanMultiCall(), scanNoInline(), scanSetInlining(), scanXBody(), scanXCall(), scanXFun(), and scanXLoop().
void otawa::Processor::prepare (WorkSpace * ws) protected virtual inherited
This method called to let the processor customize its requirements according to some generic feature.
When overload, the original method MUST be called at the end of the custom overriding implementation.
Parameters
ws Current workspace.
References otawa::Monitor::flags, otawa::Processor::IS_PREPARED, otawa::StatInfo::remove(), and otawa::Processor::ws.
Referenced by otawa::Processor::process(), and otawa::ipet::TrivialDataCacheManager::processBB().
void otawa::Processor::process (WorkSpace * fw, const PropList & props = PropList::EMPTY) inherited
Execute the code processor on the given framework.
Parameters
fw Workspace to work on.
props Configuration properties.
References otawa::Processor::_reg, otawa::Processor::cleaners, otawa::Processor::cleanup(), otawa::Processor::collectStats(), otawa::Processor::configure(), otawa::WorkSpace::getDependency(), otawa::FeatureUsage::invalidate, otawa::WorkSpace::invalidate(), otawa::WorkSpace::isCancelled(), otawa::Processor::isCollectingStats(), otawa::Processor::isPrepared(), otawa::WorkSpace::isProvided(), otawa::Processor::isTimed(), kind, otawa::Monitor::log, otawa::Monitor::LOG_CFG, otawa::Monitor::LOG_DEPS, otawa::Monitor::LOG_PROC, otawa::Monitor::logFor(), otawa::AbstractRegistration::name(), otawa::Processor::name(), otawa::Processor::prepare(), otawa::Processor::processWorkSpace(), otawa::FeatureUsage::provide, otawa::WorkSpace::provide(), otawa::Processor::recordsStats(), otawa::FeatureUsage::require, otawa::WorkSpace::require(), otawa::Processor::RUNTIME, otawa::Processor::setup(), otawa::Processor::stats, otawa::FeatureUsage::use, otawa::AbstractRegistration::uses(), otawa::Processor::version(), and otawa::Processor::ws.
Referenced by otawa::PFGBuilder::finalizeBB(), otawa::WorkSpace::getCFGInfo(), onIgnoreEntry(), otawa::SilentFeature::process(), otawa::ActualFeature::process(), otawa::Feature< T, C >::process(), otawa::p::feature::process(), otawa::TextDecoder::processWorkSpace(), otawa::cat::CATBuilder::processWorkSpace(), and otawa::DelayedBuilder::setup().
void otawa::Processor::processFrameWork (WorkSpace * fw) protected virtual inherited
Process the given workspace.
Parameters
fw Workspace to process.
Deprecated:
Use processWorkSpace() instead.
Referenced by otawa::Processor::processWorkSpace().
void otawa::FlowFactLoader::processWorkSpace (WorkSpace * fw) protected virtual
Process the given framework.
Parameters
fw Framework to process.
Deprecated:
Use processWorkSpace() instead.
Reimplemented from otawa::Processor.
References _fw, otawa::WorkSpace::isProvided(), lines_available, load(), otawa::File::name(), nodes, paths, otawa::WorkSpace::process(), otawa::Process::program(), scanXBody(), otawa::SOURCE_LINE_FEATURE, otawa::Processor::warn(), and otawa::Processor::ws.
Progress & otawa::Processor::progress (void) inline protected inherited
Get the current progress handler.
Returns
Progress handler.
void otawa::Processor::provide (const AbstractFeature & feature) protected inherited
Usually called from a processor constructor, this method records a feature provided by the work of the current processor.
Parameters
feature Provided feature.
References otawa::Processor::_reg, otawa::AbstractRegistration::features, otawa::Monitor::flags, otawa::Processor::IS_ALLOCATED, otawa::Processor::isAllocated(), otawa::Processor::isPrepared(), and otawa::FeatureUsage::provide.
Referenced by otawa::ipet::BasicConstraintsBuilder::BasicConstraintsBuilder(), otawa::CFGBuilder::CFGBuilder(), otawa::CFGCheckSummer::CFGCheckSummer(), otawa::CFGCollector::CFGCollector(), otawa::CFGNormalizer::CFGNormalizer(), otawa::ContextTreeBuilder::ContextTreeBuilder(), otawa::ContextTreeByCFGBuilder::ContextTreeByCFGBuilder(), otawa::DeadCodeAnalysis::DeadCodeAnalysis(), otawa::Dominance::Dominance(), otawa::EdgeACSBuilder::EdgeACSBuilder(), otawa::EdgeCAT2Builder::EdgeCAT2Builder(), otawa::EdgeCAT2ConstraintBuilder::EdgeCAT2ConstraintBuilder(), otawa::ExeGraphBBTime< G >::ExeGraphBBTime(), otawa::FirstLastBuilder::FirstLastBuilder(), otawa::ipet::FlowFactConstraintBuilder::FlowFactConstraintBuilder(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::ipet::ILPSystemGetter::ILPSystemGetter(), otawa::LoopReductor::LoopReductor(), otawa::PCGBuilder::PCGBuilder(), otawa::PFGBuilder::PFGBuilder(), otawa::PostDominance::PostDominance(), otawa::PSTBuilder::PSTBuilder(), otawa::TextDecoder::TextDecoder(), otawa::ipet::TrivialDataCacheManager::TrivialDataCacheManager(), and otawa::VarTextDecoder::VarTextDecoder().
bool otawa::Processor::recordsStats (void) const inline protected inherited
Test if the statictics mode is activated.
Returns
True if the statistics mode is activated, false else.
Referenced by otawa::Processor::init(), otawa::Processor::process(), and otawa::CFGProcessor::processWorkSpace().
void otawa::Processor::recordStat (const AbstractFeature & feature, StatCollector * collector) protected inherited
Add a statistics collector to the current workspace collection.
The statistics object is tracked and linked to the feature. In case of the feature invalidation, the statistics information instance is purged of the statistics collector.
Parameters
feature Feature to link the collector to.
collector Statistics collector to add.
References otawa::StatInfo::add(), otawa::Processor::addCleaner(), otawa::Processor::isCollectingStats(), and otawa::Processor::workspace().
Referenced by otawa::CAT2OnlyConstraintBuilder::collectStats(), otawa::ipet::WCETComputation::collectStats(), and otawa::dcache::CatConstraintBuilder::collectStats().
void otawa::Processor::require (const AbstractFeature & feature) protected inherited
Usually called from a processor constructor, this method records a required feature for the work of the current processor.
Parameters
feature Required feature.
References otawa::Processor::_reg, otawa::AbstractRegistration::features, otawa::Monitor::flags, otawa::Processor::IS_ALLOCATED, otawa::Processor::isAllocated(), otawa::Processor::isPrepared(), and otawa::FeatureUsage::require.
Referenced by otawa::ipet::BasicConstraintsBuilder::BasicConstraintsBuilder(), otawa::CFGBuilder::CFGBuilder(), otawa::CFGCollector::CFGCollector(), otawa::CFGNormalizer::CFGNormalizer(), otawa::ContextTreeBuilder::ContextTreeBuilder(), otawa::ContextTreeByCFGBuilder::ContextTreeByCFGBuilder(), otawa::ContextualProcessor::ContextualProcessor(), otawa::DeadCodeAnalysis::DeadCodeAnalysis(), otawa::EdgeACSBuilder::EdgeACSBuilder(), otawa::EdgeCAT2Builder::EdgeCAT2Builder(), otawa::EdgeCAT2ConstraintBuilder::EdgeCAT2ConstraintBuilder(), otawa::FirstLastBuilder::FirstLastBuilder(), otawa::ipet::FlowFactConstraintBuilder::FlowFactConstraintBuilder(), otawa::LinkedBlocksDetector::LinkedBlocksDetector(), otawa::LoopReductor::LoopReductor(), otawa::PCGBuilder::PCGBuilder(), otawa::PFGBuilder::PFGBuilder(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::CAT2Builder::processCFG(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), otawa::PSTBuilder::PSTBuilder(), otawa::FeatureRequirer::require(), otawa::StackAnalysis::StackAnalysis(), otawa::TextDecoder::TextDecoder(), otawa::ipet::TrivialDataCacheManager::TrivialDataCacheManager(), otawa::ipet::WCETCountRecorder::WCETCountRecorder(), and otawa::script::Script::work().
void otawa::Processor::requireDyn (WorkSpace * ws, const PropList & props) protected virtual inherited
Method called after registration requirements to support dynamic requirements.
As a default, do nothing.
Parameters
ws Current workspace.
props Current properties.
Referenced by otawa::ipet::TrivialDataCacheManager::processBB().
MemArea otawa::FlowFactLoader::scanAddress (xom::Element * element, ContextualPath & path, bool call = false) throw (ProcessorException) private
Retrieve the address of an element (function, loop, ...) from its XML element.
Parameters
element Element to scan in.
path Context path.
call Location for a call is required.
Returns
Address of the element or null if there is an error.
References _fw, otawa::Symbol::address(), addressOf(), findCall(), otawa::Process::findSymbol(), otawa::Address::isNull(), otawa::MemArea::null, otawa::WorkSpace::process(), scanInt(), scanUInt(), otawa::Symbol::size(), otawa::cfgio::source(), and xline().
Referenced by scanIgnoreControl(), scanIgnoreSeq(), scanMemAccess(), scanMemSet(), scanMultiBranch(), scanMultiCall(), scanNoInline(), scanSetInlining(), scanValue(), scanXBody(), scanXCall(), scanXFun(), and scanXLoop().
Option< long > otawa::FlowFactLoader::scanBound (xom::Element * element, cstring name) throw (ProcessorException) private
Scan a a bound attribute.
Parameters
element Element to scan in.
name Name of the element.
Returns
Read element or none.
References otawa::Processor::name(), and xline().
Referenced by scanXLoop().
void otawa::FlowFactLoader::scanIgnoreControl (xom::Element * element, ContextualPath & cpath) private
Scan a ignorecontrol XML element.
Parameters
element ignorecontrol element
cpath contextual path
References otawa::ProgItem::address(), otawa::MemArea::address(), otawa::Process::findInstAt(), otawa::Inst::isControl(), otawa::MemArea::isNull(), otawa::MemArea::lastAddress(), onIgnoreControl(), onWarning(), otawa::WorkSpace::process(), scanAddress(), otawa::ProgItem::topAddress(), workSpace(), and xline().
Referenced by scanXBody().
void otawa::FlowFactLoader::scanIgnoreEntry (xom::Element * element) private
Called when an "ignore-entry" elemet is found.
Parameters
element Current element.
References otawa::Processor::name(), onIgnoreEntry(), onWarning(), and xline().
Referenced by scanXBody().
void otawa::FlowFactLoader::scanIgnoreSeq (xom::Element * element, ContextualPath & cpath) private
Scan a ignoreseq XML element.
Parameters
element ignoreseq element
cpath contextual path
References otawa::ProgItem::address(), otawa::MemArea::address(), otawa::Process::findInstAt(), otawa::Inst::isControl(), otawa::MemArea::isNull(), otawa::MemArea::lastAddress(), onIgnoreSeq(), onWarning(), otawa::WorkSpace::process(), scanAddress(), otawa::ProgItem::topAddress(), workSpace(), and xline().
Referenced by scanXBody().
Option< long > otawa::FlowFactLoader::scanInt (xom::Element * element, cstring name) throw (ProcessorException) private
Scan an integer attribute.
Parameters
element Element to scan in.
name Name of the element.
Returns
Read element or none.
References otawa::Processor::name(), and xline().
Referenced by scanAddress(), and scanValue().
void otawa::FlowFactLoader::scanMemAccess (xom::Element * element) private
Scan for a memory access instruction.
Parameters
element Element to look in.
References otawa::MemArea::address(), otawa::MemArea::join(), onError(), onMemoryAccess(), scanAddress(), otawa::MemArea::topAddress(), and xline().
Referenced by scanXBody().
void otawa::FlowFactLoader::scanMemSet (xom::Element * element) private
Load a memory set.
Parameters
element Element to get information from.
References otawa::MemArea::address(), otawa::Type::int16_type, otawa::Type::int32_type, otawa::Type::int64_type, otawa::Type::int8_type, otawa::Processor::name(), onError(), onMemSet(), scanAddress(), scanValue(), otawa::type(), otawa::Type::uint16_type, otawa::Type::uint32_type, otawa::Type::uint64_type, otawa::Type::uint8_type, and xline().
Referenced by scanXBody().
void otawa::FlowFactLoader::scanMultiBranch (xom::Element * element, ContextualPath & cpath) private
Scan a multibranch XML element composed of items with a different location each.
Parameters
element multibranch element
cpath contextual path
References otawa::ProgItem::address(), otawa::MemArea::address(), otawa::Process::findInstAt(), otawa::Inst::isBranch(), otawa::MemArea::isNull(), otawa::MemArea::lastAddress(), onMultiBranch(), onWarning(), otawa::WorkSpace::process(), scanAddress(), otawa::ProgItem::topAddress(), workSpace(), and xline().
Referenced by scanXBody().
void otawa::FlowFactLoader::scanMultiCall (xom::Element * element, ContextualPath & cpath) private
Scan a multicall XML element composed of items with a different location each.
Parameters
element multicall element
cpath contextual path
References otawa::ProgItem::address(), otawa::MemArea::address(), otawa::Process::findInstAt(), otawa::Inst::isCall(), otawa::MemArea::isNull(), otawa::MemArea::lastAddress(), onMultiCall(), onWarning(), otawa::WorkSpace::process(), scanAddress(), otawa::ProgItem::topAddress(), workSpace(), and xline().
Referenced by scanXBody().
void otawa::FlowFactLoader::scanNoInline (xom::Element * element, ContextualPath & cpath, bool no_inline) private
Scan a noinline/doinline XML element.
Parameters
element ignoreseq element
cpath contextual path
References otawa::ProgItem::address(), otawa::MemArea::address(), otawa::Process::findInstAt(), otawa::Inst::isControl(), otawa::MemArea::isNull(), otawa::MemArea::lastAddress(), onNoInline(), onWarning(), otawa::WorkSpace::process(), scanAddress(), otawa::ProgItem::topAddress(), workSpace(), and xline().
Referenced by scanXBody().
void otawa::FlowFactLoader::scanRegSet (xom::Element * element) private
Load a register set instruction.
Parameters
element Element to get information from.
References otawa::Processor::name(), onError(), onRegSet(), otawa::dfa::Value::parse(), scanValue(), and xline().
Referenced by scanXBody().
void otawa::FlowFactLoader::scanSetInlining (xom::Element * element, ContextualPath & cpath, bool policy) private
Scan a inlining-off/inlining-on XML element.
Parameters
element ignoreseq element
cpath contextual path
References otawa::ProgItem::address(), otawa::MemArea::address(), otawa::Process::findInstAt(), otawa::Inst::isControl(), otawa::MemArea::isNull(), otawa::MemArea::lastAddress(), onSetInlining(), onWarning(), otawa::WorkSpace::process(), scanAddress(), otawa::ProgItem::topAddress(), workSpace(), and xline().
Referenced by scanXBody().
Option< unsigned long > otawa::FlowFactLoader::scanUInt (xom::Element * element, cstring name) throw (ProcessorException) private
References otawa::Processor::name(), and xline().
Referenced by scanAddress().
dfa::Value otawa::FlowFactLoader::scanValue (xom::Element * element) private
Scan a value in the given element.
Parameters
element Element to scan value in.
References otawa::MemArea::address(), otawa::Address::offset(), onError(), scanAddress(), scanInt(), and xline().
Referenced by scanMemSet(), and scanRegSet().
void otawa::FlowFactLoader::scanXBody (xom::Element * body, ContextualPath & cpath) throw (ProcessorException) private
Supports an XML flow fact content.
Supported elements includes "loop", "function", "noreturn", "return", "nocall", "doinline", "noinline", "inlining-on", "inlining-off", "flowfacts", "ignore-entry", "multibranch", "multicall", "ignorecontrol", "ignoreseq", "mem-access", "mem-set", "reg-set".
Parameters
body Content of the file.
cpath Contextual path.
References otawa::MemArea::address(), otawa::Address::isNull(), otawa::Processor::name(), onNoCall(), onNoReturn(), onReturn(), onWarning(), scanAddress(), scanIgnoreControl(), scanIgnoreEntry(), scanIgnoreSeq(), scanMemAccess(), scanMemSet(), scanMultiBranch(), scanMultiCall(), scanNoInline(), scanRegSet(), scanSetInlining(), scanXFun(), scanXLoop(), otawa::Processor::warn(), and xline().
Referenced by loadXML(), and processWorkSpace().
void otawa::FlowFactLoader::scanXCall (xom::Element * element, ContextualPath & path) throw (ProcessorException) private
Scan a call element that may have possibly two forms:
contains a list of called functions,
contains a function content (compatibility with old syntax).
References _fw, otawa::MemArea::address(), otawa::ContextualStep::CALL, otawa::Process::findInstAt(), otawa::ContextualStep::FUNCTION, otawa::Address::isNull(), onWarning(), otawa::WorkSpace::process(), scanAddress(), scanXContent(), scanXFun(), and xline().
Referenced by scanXContent().
void otawa::FlowFactLoader::scanXConditional (xom::Element * element, ContextualPath & path) throw (ProcessorException) private
Called to scan an "if" element.
Parameters
element "if" element.
path Current contextual path.
References otawa::Processor::name(), and scanXContent().
Referenced by scanXContent().
void otawa::FlowFactLoader::scanXContent (xom::Element * element, ContextualPath & path) throw (ProcessorException) private
Scan the content of 'function' or of a 'loop'.
Parameters
element Container element.
path Current context path.
References otawa::Processor::name(), scanXCall(), scanXConditional(), scanXFun(), and scanXLoop().
Referenced by scanXCall(), scanXConditional(), scanXFun(), and scanXLoop().
void otawa::FlowFactLoader::scanXFun (xom::Element * element, ContextualPath & path) throw (ProcessorException) private
Scan a function XML element.
Parameters
element Element of the function.
path Context path to access the function.
References _fw, otawa::MemArea::address(), addressOf(), otawa::Process::findInstAt(), otawa::ContextualStep::FUNCTION, otawa::Address::isNull(), onWarning(), otawa::WorkSpace::process(), scanAddress(), scanXContent(), and xline().
Referenced by scanXBody(), scanXCall(), and scanXContent().
void otawa::FlowFactLoader::scanXLoop (xom::Element * element, ContextualPath & path) throw (ProcessorException) private
Scan a loop XML element.
Parameters
element Element of the loop.
path Context path to access the loop.
References _fw, otawa::MemArea::address(), otawa::Process::findInstAt(), otawa::Address::isNull(), otawa::clp::max(), onLoop(), onWarning(), otawa::WorkSpace::process(), scanAddress(), scanBound(), scanXContent(), otawa::Processor::warn(), and xline().
Referenced by scanXBody(), and scanXContent().
void otawa::FlowFactLoader::setup (WorkSpace * ws) protected virtual
This method is called before an anlysis to let the processor do some initialization.
Parameters
ws Processed workspace.
Reimplemented from otawa::Processor.
References otawa::dfa::INITIAL_STATE, and state.
void otawa::Monitor::setWorkspace (WorkSpace * workspace) inline protected inherited
Set the current workspace.
Parameters
workspace New current workspace.
template<class T > T* otawa::Processor::track (const AbstractFeature & feature, T * object) inline protected inherited
Referenced by otawa::SubCFGBuilder::cleanup(), otawa::StackAnalysis::cleanup(), otawa::DelayedBuilder::cleanup(), and otawa::CFGBuilder::processWorkSpace().
template<class T > void otawa::Processor::track (const AbstractFeature & feature, const Ref< T *, Identifier< T * > > & ref) inline protected inherited
Track the release of an allocated object assigned to an identifier relatively to the given feature.
When the feature is deleted, the object is fried and the identifier is removed. It is used as below:
track(MY_FEATURE, MY_ID(props) = value);
Parameters
feature Linked feature.
ref Reference to the identifier to remove.
template<class T > void otawa::Processor::track (const AbstractFeature & feature, const Ref< T *, const Identifier< T * > > & ref) inline protected inherited
Track the release of an allocated object assigned to an identifier relatively to the given feature.
When the feature is deleted, the object is fried and the identifier is removed. It is used as below:
track(MY_FEATURE, MY_ID(props) = value);
Parameters
feature Linked feature.
ref Reference to the identifier to remove.
void otawa::Processor::use (const AbstractFeature & feature) protected inherited
Usually called from a processor constructor, this method records a feature as used by the work of the current processor.
Parameters
feature Used feature.
References otawa::Processor::_reg, otawa::AbstractRegistration::features, otawa::Monitor::flags, otawa::Processor::IS_ALLOCATED, otawa::Processor::isAllocated(), otawa::Processor::isPrepared(), and otawa::FeatureUsage::use.
Referenced by otawa::Virtualizer::Virtualizer().
elm::Version otawa::Processor::version (void) const inline inherited
References otawa::PropList::EMPTY.
Referenced by otawa::Processor::process(), otawa::Processor::Processor(), and otawa::Processor::warn().
otawa::FlowFactLoader::void::util_fft_error (otawa::FlowFactLoader * loader, const char * msg) private
void otawa::Processor::warn (const String & message) protected inherited
Display a warning.
Parameters
message Message to display.
References otawa::Processor::COLLECT_STATS, otawa::Monitor::log, otawa::LOG, otawa::Processor::LOG, otawa::LOG_LEVEL, otawa::Processor::LOG_LEVEL, otawa::Processor::name(), otawa::Progress::null, otawa::OUTPUT, otawa::Processor::OUTPUT, otawa::Processor::PROGRESS, otawa::Processor::RUNTIME, otawa::Processor::STATS, otawa::Processor::TIMED, otawa::VERBOSE, otawa::Processor::VERBOSE, and otawa::Processor::version().
Referenced by otawa::CFGBuilder::addFile(), addressOf(), otawa::CFGBuilder::buildCFG(), otawa::VarTextDecoder::getInst(), load(), loadF4(), onWarning(), otawa::ets::FlowFactLoader::processAST(), otawa::ipet::FlowFactLoader::processBB(), otawa::CFGChecker::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::etime::StandardEventBuilder::processBB(), otawa::CFGNormalizer::processCFG(), otawa::CFGChecker::processCFG(), otawa::VarTextDecoder::processEntry(), otawa::VarTextDecoder::processWorkSpace(), otawa::FixedTextDecoder::processWorkSpace(), processWorkSpace(), otawa::Processor::processWorkSpace(), scanXBody(), scanXLoop(), otawa::ipet::TrivialInstCacheManager::setup(), otawa::CFGBuilder::setup(), and otawa::script::Script::work().
WorkSpace * otawa::Monitor::workspace (void) inline inherited
Get the current workspace.
Returns
Current workspace.
WorkSpace* otawa::FlowFactLoader::workSpace (void) const inline protected
References otawa::ot::address(), name, otawa::cfgio::target(), and otawa::type().
Referenced by addressOf(), onRegSet(), scanIgnoreControl(), scanIgnoreSeq(), scanMultiBranch(), scanMultiCall(), scanNoInline(), and scanSetInlining().
WorkSpace * otawa::Processor::workspace (void) const inline protected inherited
Get the current workspace.
Returns
Current workspace.
Referenced by otawa::CFGProcessor::doCleanUp(), otawa::PFGBuilder::finalizeBB(), findCall(), otawa::VarTextDecoder::getBytes(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::ipet::FlowFactLoader::lookLineAt(), otawa::etime::EdgeTimeBuilder::make(), otawa::DelayedBuilder::next(), onIgnoreEntry(), otawa::VarTextDecoder::processEntry(), otawa::Processor::recordStat(), otawa::DelayedBuilder::setup(), otawa::DelayedBuilder::size(), and otawa::CFGProcessor::str().
string otawa::FlowFactLoader::xline (xom::Node * element) private
Build an XML element position for user.
Parameters
element Current XML element.
Referenced by scanAddress(), scanBound(), scanIgnoreControl(), scanIgnoreEntry(), scanIgnoreSeq(), scanInt(), scanMemAccess(), scanMemSet(), scanMultiBranch(), scanMultiCall(), scanNoInline(), scanRegSet(), scanSetInlining(), scanUInt(), scanValue(), scanXBody(), scanXCall(), scanXFun(), and scanXLoop().
Member Data Documentation
WorkSpace* otawa::FlowFactLoader::_fw private
Referenced by addressOf(), onCheckSum(), onIgnoreControl(), onIgnoreSeq(), onLoop(), onMemoryAccess(), onMultiBranch(), onMultiCall(), onNoCall(), onNoInline(), onNoReturn(), onPreserve(), onReturn(), onSetInlining(), processWorkSpace(), scanAddress(), scanXCall(), scanXFun(), and scanXLoop().
bool otawa::FlowFactLoader::checksummed private
Referenced by load(), and onCheckSum().
Identifier< bool > otawa::Processor::COLLECT_STATS static inherited
This property allows to activate collection of statistics for the work of the current processor.
See also
StatInfo class.
Referenced by otawa::Processor::init(), and otawa::Processor::warn().
Path otawa::FlowFactLoader::current private
Referenced by load(), onError(), and onWarning().
const t::uint32 otawa::Monitor::CUSTOM_SHIFT = 16 static protected inherited
t::uint32 otawa::Monitor::flags protected inherited
Contains various bit flags.
Bits from 0 to CUSTOM_SHIFT - 1 are private while bits from CUSTOM_SHIFT to 31 may be customized. To build a bit mask for custom bit i, the CUSTOM_SHIFT may be used as below:
static const t::uint32 MY_MASK = 1 << (i + CUSTOM_SHIFT);
Referenced by otawa::Monitor::configure(), otawa::Processor::init(), otawa::Processor::invalidate(), otawa::Processor::prepare(), otawa::Processor::Processor(), otawa::Processor::provide(), otawa::Processor::require(), otawa::Processor::use(), and otawa::Processor::~Processor().
const t::uint32 otawa::Processor::IS_ALLOCATED = 0x04 << CUSTOM_SHIFT static protected inherited
Referenced by otawa::Processor::invalidate(), otawa::Processor::Processor(), otawa::Processor::provide(), otawa::Processor::require(), otawa::Processor::use(), and otawa::Processor::~Processor().
const t::uint32 otawa::Processor::IS_COLLECTING = 0x10 << CUSTOM_SHIFT static protected inherited
Referenced by otawa::Processor::init().
const t::uint32 otawa::Processor::IS_PREPARED = 0x08 << CUSTOM_SHIFT static protected inherited
Referenced by otawa::Processor::prepare().
const t::uint32 otawa::Processor::IS_TIMED = 0x01 << CUSTOM_SHIFT static protected inherited
Referenced by otawa::Processor::init().
const t::uint32 otawa::Monitor::IS_VERBOSE = 0x01 static protected inherited
Referenced by otawa::Monitor::configure().
bool otawa::FlowFactLoader::lib private
Referenced by addressOf(), onIgnoreEntry(), onLibrary(), and onNoReturn().
bool otawa::FlowFactLoader::lines_available private
Referenced by addressOf(), and processWorkSpace().
elm::io::Output otawa::Monitor::log inherited
Provide a stream to perform log output.
Should be used only when verbosity is activated.
Referenced by otawa::CFGBuilder::addCFG(), otawa::ipet::ConstraintLoader::addConstraint(), otawa::PFGBuilder::addFunction(), otawa::ccg::LBlockBuilder::addLBlock(), otawa::LBlockBuilder::addLBlock(), addressOf(), otawa::GraphBBTime< G >::analyzePathContext(), otawa::etime::EdgeTimeBuilder::applyFloppySplit(), otawa::etime::EdgeTimeBuilder::applyStrictSplit(), otawa::etime::EdgeTimeBuilder::applyWeightedSplit(), otawa::DelayedBuilder::buildBB(), otawa::CFGBuilder::buildCFG(), otawa::branch::BranchBuilder::categorize(), otawa::ipet::FlowFactLoader::cleanup(), otawa::ipet::TrivialDataCacheManager::configure(), otawa::ACSBuilder::configure(), otawa::Monitor::configure(), otawa::etime::EdgeTimeBuilder::displayConfs(), otawa::ipet::ConstraintLoader::error(), otawa::etime::EdgeTimeBuilder::genForOneCost(), otawa::ipet::ConstraintLoader::getBB(), otawa::VarTextDecoder::getInst(), otawa::ipet::ConstraintLoader::getVar(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::Processor::init(), load(), loadF4(), otawa::script::Script::makeConfig(), otawa::etime::EdgeTimeBuilder::makeSplit(), otawa::ipet::ConstraintLoader::newEdgeVar(), otawa::CFGBuilder::nextBB(), otawa::script::Script::onError(), onLoop(), onMemoryAccess(), onNoInline(), onReturn(), onSetInlining(), otawa::script::Script::onWarning(), otawa::Processor::process(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::branch::CondNumber::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::dcache::CLPBlockBuilder::processBB(), otawa::etime::StandardEventBuilder::processBB(), otawa::dcache::BlockBuilder::processBB(), otawa::GraphBBTime< G >::processBB(), otawa::CFGCheckSummer::processCFG(), otawa::CAT2Builder::processCFG(), otawa::ipet::ConstraintLoader::processCFG(), otawa::ContextualProcessor::processCFG(), otawa::BBProcessor::processCFG(), otawa::etime::EdgeTimeBuilder::processEdge(), otawa::VarTextDecoder::processEntry(), otawa::dcache::CATBuilder::processLBlockSet(), otawa::ACSMayBuilder::processLBlockSet(), otawa::CAT2Builder::processLBlockSet(), otawa::dcache::ACSBuilder::processLBlockSet(), otawa::etime::EdgeTimeBuilder::processSequence(), otawa::VarTextDecoder::processWorkSpace(), otawa::TextDecoder::processWorkSpace(), otawa::LBlockProcessor::processWorkSpace(), otawa::ipet::WCETComputation::processWorkSpace(), otawa::FixedTextDecoder::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), otawa::StackAnalysis::processWorkSpace(), otawa::branch::BranchBuilder::processWorkSpace(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::CFGProcessor::processWorkSpace(), otawa::Virtualizer::processWorkSpace(), otawa::clp::Analysis::processWorkSpace(), otawa::ilp::Output::setup(), otawa::CFGBuilder::setup(), otawa::BBRatioDisplayer::setup(), otawa::dcache::BlockBuilder::setup(), otawa::CFGBuilder::thisBB(), otawa::ipet::FlowFactLoader::transfer(), otawa::Virtualizer::virtualize(), otawa::Processor::warn(), and otawa::script::Script::work().
Identifier< elm::io::OutStream * > & otawa::Processor::LOG = otawa::LOG static inherited
This property identifier is used for setting the log stream used by the processor to write messages (information, warning, error).
Deprecated:
Referenced by otawa::Processor::init(), otawa::Manager::loadBin(), otawa::LiExeGraphBBTime::processBB(), and otawa::Processor::warn().
Identifier< Processor::log_level_t > & otawa::Processor::LOG_LEVEL = otawa::LOG_LEVEL static inherited
Property passed in the configuration property list of a processor to select the log level between LOG_PROC, LOG_CFG or LOG_BB.
Deprecated:
Referenced by otawa::Application::run(), and otawa::Processor::warn().
bool otawa::FlowFactLoader::mandatory private
Referenced by configure(), and loadF4().
genstruct::Vector<xom::Element *> otawa::FlowFactLoader::nodes private
Referenced by configure(), and processWorkSpace().
Monitor & otawa::Monitor::null = __null_mon static inherited
Monitor that output nothing.
Referenced by otawa::Monitor::configure().
elm::io::Output otawa::Monitor::out inherited
Provide a stream to perform output for the user.
Referenced by otawa::DelayedBuilder::buildEdges(), otawa::Monitor::configure(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::Processor::init(), otawa::ast::ASTLoader::onError(), otawa::dcache::operator<<(), otawa::CFGChecker::processBB(), otawa::etime::StandardEventBuilder::processBB(), otawa::hard::Dumper::processWorkSpace(), otawa::ccg::Builder::processWorkSpace(), otawa::SubCFGBuilder::SubCFGBuilder(), and otawa::Virtualizer::virtualize().
Identifier< elm::io::OutStream * > & otawa::Processor::OUTPUT = otawa::OUTPUT static inherited
This property identifier is used for setting the output stream used by the processor to write results.
Deprecated:
Referenced by otawa::Processor::init(), and otawa::Processor::warn().
genstruct::Vector<Path> otawa::FlowFactLoader::paths private
Referenced by configure(), and processWorkSpace().
Identifier< Progress * > otawa::Processor::PROGRESS static inherited
Install.
Referenced by otawa::Processor::init(), and otawa::Processor::warn().
Identifier<bool> otawa::Processor::RECURSIVE static inherited
Referenced by otawa::CFGProcessor::str().
p::declare otawa::FlowFactLoader::reg static
Initial value:
= p::init("otawa::util::FlowFactLoader", Version(1, 4, 0))
        .maker<FlowFactLoader>()
        .require(dfa::INITIAL_STATE_FEATURE)
        .provide(FLOW_FACTS_FEATURE)
        .provide(MKFF_PRESERVATION_FEATURE)
Referenced by onRegSet().
Identifier< elm::system::time_t > otawa::Processor::RUNTIME static inherited
This property identifier is used to store in the statistics of a processor the overall run time of the processor work.
Referenced by otawa::Processor::process(), and otawa::Processor::warn().
dfa::State* otawa::FlowFactLoader::state private
Referenced by onMemSet(), onRegSet(), and setup().
Identifier< PropList * > otawa::Processor::STATS static inherited
This property identifiers is used to pass a property list to the processor that will be used to store statistics about the performed work.
Implicitly, passing such a property activates the statistics recording facilities.
Referenced by otawa::Processor::init(), and otawa::Processor::warn().
PropList* otawa::Processor::stats protected inherited
Referenced by otawa::dcache::CATBuilder::cleanup(), otawa::tsim::Delta::cleanup(), otawa::Processor::init(), otawa::Processor::process(), and otawa::CFGProcessor::processWorkSpace().
Identifier< bool > otawa::Processor::TIMED static inherited
If the value of the associated property is true (default to false), time statistics will also be collected with other processor statistics.
Passing such a property without PROC_STATS has no effects.
Referenced by otawa::Processor::init(), and otawa::Processor::warn().
Identifier< bool > & otawa::Processor::VERBOSE = otawa::VERBOSE static inherited
This property activates the verbose mode of the processor: information about the processor work will be displayed.
Deprecated:
Referenced by otawa::Application::run(), otawa::Manager::setVerbosity(), and otawa::Processor::warn().
The documentation for this class was generated from the following files:
include/otawa/util/FlowFactLoader.h
src/prog/util_FlowFactLoader.cpp