Otawa: otawa::clp::Manager Class Reference
otawa::clp::Manager Class Reference
CLP Analysis
This class allows to exploit the result of a CLP analysis.
#include <otawa/data/clp/features.h>
Public Types
typedef t::uint32 step_t
Public Member Functions
Manager (WorkSpace *ws)
Create a manager for the current workspace.
step_t start (BasicBlock *bb)
Start the interpretation of a basic block.
step_t next (void)
Go to the next step in the interpretation of the basic block.
sem::inst sem (void)
Get the last interpreted semantic instruction.
Inst * inst (void)
Get the current interpreted machine instruction.
State * state (void)
Get the state result of the last interpretation.
int ipc (void)
Get the current semantic instruction PC.
Static Public Member Functions
static bool newSem (step_t s)
Test if the given step result contains the flag Manager::NEW_SEM.
static bool newPath (step_t s)
Test if the given step result contains the flag Manager::NEW_PATH.
static bool newInst (step_t s)
Test if the given step result contains the flag Manager::NEW_INST.
static bool isEnded (step_t s)
Static Public Attributes
static const step_t NEW_SEM = 0x01
static const step_t NEW_PATH = 0x02
static const step_t NEW_INST = 0x04
static const step_t ENDED = 0
Private Attributes
ClpProblem * p
BasicBlock::InstIter mi
clp::State s
clp::State * cs
int i
Detailed Description
This class allows to exploit the result of a CLP analysis.
Basically, it provide facility to traverse a basic block, semantic instruction by semantic instruction and to lookup the state.
Member Typedef Documentation
typedef t::uint32 otawa::clp::Manager::step_t
Constructor & Destructor Documentation
otawa::clp::Manager::Manager (WorkSpace * ws)
Create a manager for the current workspace.
Parameters
ws Workspace to work with.
References otawa::WorkSpace::process().
Referenced by isEnded().
Member Function Documentation
Inst * otawa::clp::Manager::inst (void)
Get the current interpreted machine instruction.
Returns
Current machine instruction.
Referenced by isEnded(), and otawa::dcache::CLPBlockBuilder::processBB().
int otawa::clp::Manager::ipc (void) inline
Get the current semantic instruction PC.
Returns
Current semantic instruction PC.
References i.
Referenced by otawa::dcache::CLPBlockBuilder::processBB().
static bool otawa::clp::Manager::isEnded (step_t s) inline static
References otawa::cfgio::bb(), inst(), Manager(), next(), s, sem(), start(), and state().
bool otawa::clp::Manager::newInst (step_t s) inline static
Test if the given step result contains the flag Manager::NEW_INST.
Returns
True if Manager::NEW_INST is set, false else.
References NEW_INST.
Referenced by otawa::dcache::CLPBlockBuilder::processBB().
bool otawa::clp::Manager::newPath (step_t s) inline static
Test if the given step result contains the flag Manager::NEW_PATH.
Returns
True if Manager::NEW_PATH is set, false else.
References NEW_PATH.
bool otawa::clp::Manager::newSem (step_t s) inline static
Test if the given step result contains the flag Manager::NEW_SEM.
Returns
True if Manager::NEW_SEM is set, false else.
References NEW_SEM.
Manager::step_t otawa::clp::Manager::next (void)
Go to the next step in the interpretation of the basic block.
This may causes:
Manager::NEW_SEM – just interpreting the next semantic instruction,
Manager::NEW_PATH – starting the interpretation of the next semantic path,
Manager::NEW_INST – starting the interpretation of the next machine instruction,
Manager::ENDED – to have exhausted any interpretation.
Returns
A OR'ed combination of NEW_SEM, NEW_PATH, NEW_INST, or the value ENDED.
Referenced by isEnded(), and otawa::dcache::CLPBlockBuilder::processBB().
sem::inst otawa::clp::Manager::sem (void)
Get the last interpreted semantic instruction.
Returns
Current semantic instruction.
Referenced by isEnded(), and otawa::dcache::CLPBlockBuilder::processBB().
Manager::step_t otawa::clp::Manager::start (BasicBlock * bb)
Start the interpretation of a basic block.
Parameters
bb Basic block to interpret.
References otawa::clp::STATE_IN().
Referenced by isEnded(), and otawa::dcache::CLPBlockBuilder::processBB().
State * otawa::clp::Manager::state (void)
Get the state result of the last interpretation.
Returns
Result state.
Referenced by isEnded(), and otawa::dcache::CLPBlockBuilder::processBB().
Member Data Documentation
clp::State * otawa::clp::Manager::cs private
const step_t otawa::clp::Manager::ENDED = 0 static
int otawa::clp::Manager::i private
Referenced by ipc().
BasicBlock::InstIter otawa::clp::Manager::mi private
const step_t otawa::clp::Manager::NEW_INST = 0x04 static
Referenced by newInst().
const step_t otawa::clp::Manager::NEW_PATH = 0x02 static
Referenced by newPath().
const step_t otawa::clp::Manager::NEW_SEM = 0x01 static
Referenced by newSem().
ClpProblem* otawa::clp::Manager::p private
clp::State otawa::clp::Manager::s private
Referenced by isEnded().
The documentation for this class was generated from the following files:
include/otawa/data/clp/features.h
src/prog/clp_analysis.cpp