Otawa: otawa::etime::Config Class Reference
otawa::etime::Config Class Reference
Represents a configuration for computing cost of a BB.
#include <otawa/etime/Config.h>
Public Member Functions
Config (void)
Config (t::uint32 bits)
Config (const Config &conf)
t::uint32 bits (void) const
void set (int n)
void clear (int n)
bool bit (int n) const
string toString (int n) const
Convert config to string.
Private Attributes
t::uint32 b
Detailed Description
Represents a configuration for computing cost of a BB.
Each bits represents the state of an event:
0 event not activated
1 event activated
Constructor & Destructor Documentation
otawa::etime::Config::Config (void) inline
otawa::etime::Config::Config (t::uint32 bits) inline
otawa::etime::Config::Config (const Config & conf) inline
Member Function Documentation
bool otawa::etime::Config::bit (int n) const inline
Referenced by toString().
t::uint32 otawa::etime::Config::bits (void) const inline
Referenced by otawa::etime::ConfigSet::negConst(), and otawa::etime::ConfigSet::posConst().
void otawa::etime::Config::clear (int n) inline
void otawa::etime::Config::set (int n) inline
string Config::toString (int n) const
Convert config to string.
Parameters
n Number of bits in the configuration.
Returns
String display of the configuration.
References bit().
Member Data Documentation
t::uint32 otawa::etime::Config::b private
The documentation for this class was generated from the following files:
include/otawa/etime/Config.h
src/etime/EdgeTimeBuilder.cpp