Otawa: otawa::hard::Platform Class Reference
otawa::hard::Platform Class Reference
Platform Description
This class records information about the architecture where the processed program will run.
#include <otawa/hard/Platform.h>
Classes
class Identification
Public Types
typedef elm::genstruct::Table< const hard::RegBank * > banks_t
Public Member Functions
Platform (const Identification &id, const PropList &props=PropList::EMPTY)
Build a platform from the given description.
Platform (cstring name, const Identification &id, const PropList &props=PropList::EMPTY)
Platform (const Platform &platform, const PropList &props=PropList::EMPTY)
Build a platform by cloning and reconfiguring the new platform.
const Identification & identification (void) const
Get identification of the current platform.
virtual bool accept (const Identification &id)
Check if the platform handle the given platform description.
bool accept (elm::CString name)
bool accept (const elm::String &name)
const banks_t & banks (void) const
int regCount (void) const
Get the count of registers in the current platform.
Register * findReg (int uniq) const
Find the register matching the given unique identifier.
const Register * findReg (const string &name) const
Find a register by its name.
virtual const Register * getSP (void) const
Get the register, usually (depending on the ABI), devoted to contain the stack pointer.
virtual const Register * getPC (void) const
Get the register containing the Program Counter.
const CacheConfiguration & cache (void) const
Get the cache configuration.
void loadCacheConfig (const elm::system::Path &path)
Load a cache configuration from the given path.
void loadCacheConfig (elm::xom::Element *element)
Load a cache configuration from an XML element.
const Memory & memory (void) const
void loadMemory (const elm::system::Path &path) throw (otawa::LoadException)
Load a memory configuration from the given path.
void loadMemory (elm::xom::Element *element) throw (otawa::LoadException)
Load a memory configuration from an XML element.
void loadProcessor (const elm::system::Path &path)
Load the processor configuration.
void loadProcessor (elm::xom::Element *element)
Load the processor configuration from the given element.
const Processor * processor (void) const
Get the current processor (possibly derivated from the current configuration).
const int pipelineDepth (void) const
Get the depth of the pipeline of the platform processor.
const string name (void) const
Get the string name of the identifier.
void print (elm::io::Output &out) const
Print the identifier.
virtual void print (elm::io::Output &output, const Property *prop) const
Print the value of the given property (accordint the property matches the given identifier).
void print (elm::io::Output &output, const Property &prop) const
virtual void printFormatted (io::Output &out, const Property *prop) const
Print the value of the given property in a formatted way, that is, possibly to perform re-scanning after.
void printFormatted (elm::io::Output &output, const Property &prop) const
virtual const Type & type (void) const
Get the identifier of data linked with this property.
virtual void fromString (PropList &props, const string &str) const
Get value of an identifier from a string and store it in the given property list.
virtual bool equals (const Property *prop1, const Property *prop2) const
Test if two properties are equal.
virtual Property * copy (Property &prop) const
Build a copy of the given property.
Property * copy (Property *prop) const
virtual void serialize (Property *prop, elm::serial2::Serializer &serializer)
Serialize the workspace to the current serializer.
virtual Property * unserialize (elm::serial2::Unserializer &unserializer)
Unserialize the workspace to the current unserializer.
Property * getProp (const AbstractIdentifier *id) const
Find a property by its identifier.
void setProp (Property *prop)
Set the property in the property list removing any double.
void setProp (const AbstractIdentifier *id)
void removeProp (const AbstractIdentifier *id)
Remove a property matching the given identifier.
void removeProp (const AbstractIdentifier &id)
Property * extractProp (const AbstractIdentifier *id)
Remove a property matching the given identifier and return it.
Property * extractProp (const AbstractIdentifier &id)
Remove a property matching the given identifier and return it.
void addProp (Property *prop)
Add property to the list without checking of duplication.
void removeAllProp (const AbstractIdentifier *id)
Remove all the properties matching the given identifier.
bool hasProp (const AbstractIdentifier &id) const
Test if the property list contains a property matching the given identifier.
void clearProps (void)
Remove all properties from the list.
void addProps (const PropList &props)
Add all properties from the given property list, in a reverse order.
Static Public Member Functions
static AbstractIdentifier * find (const string &name)
Find an abstract identifier by its name.
Static Public Attributes
static const elm::String ANY
Represents any architecture, platform, machine.
static const elm::String POWERPC
Represents the PowerPC architecture.
static const elm::String ELF
Represents the ELF ABI.
static const elm::String EABI
Represents the EABI ABI.
static const elm::String LINUX
Represents the Linux ABI.
static const elm::String LINUX_2_4
Represents the Linux 2.4 ABI.
static const elm::String LINUX_2_6
Represents the Linux 2.6 ABI.
static const elm::String MAC
Represents a Macintosh machine (seems to be too wide, must be refined).
static const elm::String SIM
Represents a simulator machine.
static const Identification ANY_PLATFORM
Represents any platform.
static const PropList EMPTY
This is an empty proplist for convenience.
Protected Member Functions
virtual ~Platform (void)
void setBanks (const banks_t &banks)
Set the list of banks for an actual platform.
void initProps (Property *prop, VarArg &args)
Add the properties found in the arguments (list of Property * ended by null) to the identifier properties.
void initProps (const PropList &props)
Initialize properties coming from the constructor.
Static Protected Attributes
static const banks_t null_banks
Empty register bank table.
Private Member Functions
void configure (const PropList &props)
Private Attributes
unsigned long flags
Identification id
const CacheConfiguration * _cache
Processor * _processor
const Memory * _memory
int depth
int rcnt
const banks_t * _banks
Static Private Attributes
static const unsigned long HAS_PROCESSOR = 0x00000001
static const unsigned long HAS_CACHE = 0x00000002
static const unsigned long HAS_MEMORY = 0x00000004
Friends
class otawa::Manager
Detailed Description
This class records information about the architecture where the processed program will run.
Member Typedef Documentation
typedef elm::genstruct::Table<const hard::RegBank *> otawa::hard::Platform::banks_t
Constructor & Destructor Documentation
otawa::hard::Platform::Platform (const Identification & id, const PropList & props = PropList::EMPTY)
Build a platform from the given description.
Parameters
_id Platform identification.
props Properties describing the platform.
References configure().
otawa::hard::Platform::Platform (cstring name, const Identification & id, const PropList & props = PropList::EMPTY)
References configure().
otawa::hard::Platform::Platform (const Platform & platform, const PropList & props = PropList::EMPTY)
Build a platform by cloning and reconfiguring the new platform.
Parameters
platform Platform to clone.
props Description properties.
References configure().
otawa::hard::Platform::~Platform (void) protected virtual
References _cache, _memory, _processor, flags, HAS_CACHE, HAS_MEMORY, and HAS_PROCESSOR.
Member Function Documentation
bool otawa::hard::Platform::accept (const Identification & _id) virtual
Check if the platform handle the given platform description.
Parameters
_id Platform identifier to check.
Returns
True if the platform accepts this kind of architecture.
References otawa::hard::Platform::Identification::abi(), ANY, ANY_PLATFORM, otawa::hard::Platform::Identification::architecture(), EABI, ELF, LINUX, LINUX_2_4, LINUX_2_6, MAC, otawa::hard::Platform::Identification::machine(), POWERPC, and SIM.
bool otawa::hard::Platform::accept (elm::CString name) inline
bool otawa::hard::Platform::accept (const elm::String & name) inline
void otawa::PropList::addProp (Property * prop) inherited
Add property to the list without checking of duplication.
Parameters
prop Property to add.
References otawa::Property::_next.
Referenced by otawa::Identifier< T >::add(), otawa::ast::ASTInfo::ASTInfo(), otawa::Identifier< otawa::arm::Info * >::copy(), otawa::AbstractIdentifier::initProps(), otawa::ContextualProperty::make(), otawa::script::Script::makeConfig(), otawa::ccg::Builder::processLBlockSet(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), and otawa::ContextualProperty::refProps().
void otawa::PropList::addProps (const PropList & props) inherited
Add all properties from the given property list, in a reverse order.
Parameters
props Property list to clone.
References otawa::Property::copy(), otawa::PropList::head, and otawa::Property::next().
Referenced by otawa::display::CFGDrawer::CFGDrawer(), otawa::display::GraphVizGraph::GraphVizGraph(), otawa::ParamFeature::instantiate(), otawa::Manager::loadXML(), otawa::display::GraphVizGraph::newEdge(), otawa::display::GraphVizGraph::newNode(), otawa::Process::Process(), otawa::display::GraphVizItem::setProps(), otawa::VirtualBasicBlock::VirtualBasicBlock(), and otawa::VirtualCFG::VirtualCFG().
const elm::genstruct::Table< const hard::RegBank * > & otawa::hard::Platform::banks (void) const inline
Referenced by otawa::ExeGraph< N >::build(), otawa::ParamExeGraph::ParamExeGraph(), otawa::ResourceList::ResourceList(), and setBanks().
const CacheConfiguration & otawa::hard::Platform::cache (void) const inline
Get the cache configuration.
Returns
Cache configuration.
Referenced by otawa::Process::cache(), configure(), otawa::EdgeCAT2Builder::processCFG(), otawa::EdgeCAT2ConstraintBuilder::processWorkSpace(), and otawa::EdgeACSBuilder::processWorkSpace().
void otawa::PropList::clearProps (void) inherited
Remove all properties from the list.
References otawa::Property::next().
Referenced by otawa::PSTBuilder::getVCFG(), otawa::display::GraphVizItem::setProps(), and otawa::WorkSpace::~WorkSpace().
void otawa::hard::Platform::configure (const PropList & props) private
References _cache, _memory, _processor, cache(), otawa::CACHE_CONFIG, otawa::CACHE_CONFIG_ELEMENT, otawa::Manager::CACHE_CONFIG_NAME, otawa::CACHE_CONFIG_PATH, otawa::CONFIG_ELEMENT, depth, flags, HAS_CACHE, HAS_MEMORY, HAS_PROCESSOR, loadCacheConfig(), loadMemory(), loadProcessor(), memory(), otawa::MEMORY_ELEMENT, otawa::Manager::MEMORY_NAME, otawa::MEMORY_OBJECT, otawa::MEMORY_PATH, otawa::Manager::OTAWA_NS, otawa::PIPELINE_DEPTH, otawa::PROCESSOR, otawa::PROCESSOR_ELEMENT, otawa::Manager::PROCESSOR_NAME, and otawa::PROCESSOR_PATH.
Referenced by Platform().
Property * otawa::AbstractIdentifier::copy (Property & prop) const virtual inherited
Build a copy of the given property.
Parameters
prop Property to copy.
Returns
Copy of the property.
Reimplemented in otawa::Identifier< T >, otawa::Identifier< otawa::ccg::Node * >, otawa::Identifier< typename Problem::Domain * >, otawa::Identifier< dfa::BitSet * >, otawa::Identifier< double >, otawa::Identifier< otawa::CFG * >, otawa::Identifier< otawa::ast::AST * >, otawa::Identifier< init_t >, otawa::Identifier< otawa::Microprocessor< ExeNode > * >, otawa::Identifier< otawa::ccg::Collection * >, otawa::Identifier< Domain * >, otawa::Identifier< AbstractParamProcessor * >, otawa::Identifier< otawa::CFGInfo * >, otawa::Identifier< BracketSet * >, otawa::Identifier< elm::io::OutStream * >, otawa::Identifier< otawa::StatInfo * >, otawa::Identifier< int >, otawa::Identifier< T * >, otawa::Identifier< otawa::PropList * >, otawa::Identifier< String >, otawa::Identifier< elm::system::time_t >, otawa::Identifier< display::kind_t >, otawa::Identifier< typename P::Domain * >, otawa::Identifier< Path >, otawa::Identifier< string >, otawa::Identifier< typename otawa::dfa::hai::FirstUnrollingFixPoint::FixPointState * >, otawa::Identifier< CString >, otawa::Identifier< elm::system::Path >, otawa::Identifier< otawa::PCG * >, otawa::Identifier< otawa::BasicBlock * >, otawa::Identifier< Processor * >, otawa::Identifier< otawa::tsim::TreePath< otawa::BasicBlock *, otawa::tsim::BBPath * > * >, otawa::Identifier< log_level_t >, otawa::Identifier< otawa::CEClass * >, otawa::Identifier< bool >, otawa::Identifier< otawa::AbstractParamIdentifier * >, otawa::Identifier< typename otawa::dfa::hai::WideningFixPoint::FixPointState * >, otawa::Identifier< otawa::Progress * >, otawa::Identifier< typename otawa::dfa::hai::DefaultFixPoint::FixPointState * >, otawa::Identifier< typename FixPoint::FixPointState * >, otawa::Identifier< otawa::Symbol * >, otawa::Identifier< otawa::display::ILPSystemAddon * >, otawa::Identifier< AbstractIdentifier * >, otawa::Identifier< elm::io::Output * >, and otawa::Identifier< otawa::arm::Info * >.
Referenced by otawa::AbstractIdentifier::printFormatted().
Property* otawa::AbstractIdentifier::copy (Property * prop) const inline inherited
References otawa::AbstractIdentifier::AbstractIdentifier(), otawa::AbstractIdentifier::copy(), otawa::AbstractIdentifier::initProps(), otawa::AbstractIdentifier::name(), otawa::AbstractIdentifier::serialize(), and otawa::AbstractIdentifier::unserialize().
Referenced by otawa::AbstractIdentifier::copy().
bool otawa::AbstractIdentifier::equals (const Property * prop1, const Property * prop2) const virtual inherited
Test if two properties are equal.
Parameters
prop1 First property.
prop2 Second property.
Returns
True if they are equal, false else.
Referenced by otawa::AbstractIdentifier::printFormatted().
Property * otawa::PropList::extractProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::script::Script::makeConfig().
Property * otawa::PropList::extractProp (const AbstractIdentifier & id) inline inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::PropList::extractProp().
Referenced by otawa::PropList::extractProp().
AbstractIdentifier * otawa::AbstractIdentifier::find (const string & name) static inherited
Find an abstract identifier by its name.
Parameters
name Name of the looked identifier.
Returns
Found identifier or null.
Referenced by otawa::ProcessorPlugin::getIdentifier(), and otawa::Application::run().
Register * otawa::hard::Platform::findReg (int uniq) const
Find the register matching the given unique identifier.
Parameters
uniq Unique identifier of the register.
Returns
Found register or null.
References _banks.
Referenced by otawa::se::SEReg::asString(), otawa::FlowFactLoader::onRegSet(), and otawa::clp::State::print().
const Register * otawa::hard::Platform::findReg (const string & name) const
Find a register by its name.
Parameters
name Name of the register to find.
Returns
Found register or null.
References _banks, and otawa::hard::Platform::Identification::name().
void otawa::AbstractIdentifier::fromString (PropList & props, const string & str) const virtual inherited
Get value of an identifier from a string and store it in the given property list.
Parameters
props Property list to store result into.
str String to get value from.
Reimplemented in otawa::Identifier< T >, otawa::Identifier< otawa::ccg::Node * >, otawa::Identifier< typename Problem::Domain * >, otawa::Identifier< dfa::BitSet * >, otawa::Identifier< double >, otawa::Identifier< otawa::CFG * >, otawa::Identifier< otawa::ast::AST * >, otawa::Identifier< init_t >, otawa::Identifier< otawa::Microprocessor< ExeNode > * >, otawa::Identifier< otawa::ccg::Collection * >, otawa::Identifier< Domain * >, otawa::Identifier< AbstractParamProcessor * >, otawa::Identifier< otawa::CFGInfo * >, otawa::Identifier< BracketSet * >, otawa::Identifier< elm::io::OutStream * >, otawa::Identifier< otawa::StatInfo * >, otawa::Identifier< int >, otawa::Identifier< T * >, otawa::Identifier< otawa::PropList * >, otawa::Identifier< String >, otawa::Identifier< elm::system::time_t >, otawa::Identifier< display::kind_t >, otawa::Identifier< typename P::Domain * >, otawa::Identifier< Path >, otawa::Identifier< string >, otawa::Identifier< typename otawa::dfa::hai::FirstUnrollingFixPoint::FixPointState * >, otawa::Identifier< CString >, otawa::Identifier< elm::system::Path >, otawa::Identifier< otawa::PCG * >, otawa::Identifier< otawa::BasicBlock * >, otawa::Identifier< Processor * >, otawa::Identifier< otawa::tsim::TreePath< otawa::BasicBlock *, otawa::tsim::BBPath * > * >, otawa::Identifier< log_level_t >, otawa::Identifier< otawa::CEClass * >, otawa::Identifier< bool >, otawa::Identifier< otawa::AbstractParamIdentifier * >, otawa::Identifier< typename otawa::dfa::hai::WideningFixPoint::FixPointState * >, otawa::Identifier< otawa::Progress * >, otawa::Identifier< typename otawa::dfa::hai::DefaultFixPoint::FixPointState * >, otawa::Identifier< typename FixPoint::FixPointState * >, otawa::Identifier< otawa::Symbol * >, otawa::Identifier< otawa::display::ILPSystemAddon * >, otawa::Identifier< AbstractIdentifier * >, otawa::Identifier< elm::io::Output * >, otawa::Identifier< otawa::arm::Info * >, and otawa::Identifier< T >.
References otawa::AbstractIdentifier::name().
Referenced by otawa::AbstractIdentifier::printFormatted().
const Register * otawa::hard::Platform::getPC (void) const virtual
Get the register containing the Program Counter.
Returns
PC register or null.
Property * otawa::PropList::getProp (const AbstractIdentifier * id) const inherited
Find a property by its identifier.
Parameters
id Identifier of the property to find.
Returns
Found property or null.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::Identifier< otawa::arm::Info * >::exists(), otawa::ContextualProperty::exists(), otawa::ContextualProperty::find(), otawa::Identifier< T >::get(), otawa::ContextualProperty::make(), otawa::ParamFeature::matches(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::print(), otawa::ContextualProperty::print(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), otawa::ContextualProperty::refProps(), otawa::Identifier< T >::set(), otawa::Identifier< T >::use(), and otawa::Identifier< T >::value().
const Register * otawa::hard::Platform::getSP (void) const virtual
Get the register, usually (depending on the ABI), devoted to contain the stack pointer.
Returns
SP register or null if none is defined.
Referenced by otawa::StackAnalysis::processWorkSpace(), and otawa::clp::Analysis::processWorkSpace().
bool otawa::PropList::hasProp (const AbstractIdentifier & id) const inline inherited
Test if the property list contains a property matching the given identifier.
Parameters
id Property identifier to look for.
Returns
True if the list contains the matching property, false else.
References otawa::p::print().
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::Monitor::configure(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::exists(), and otawa::Manager::setVerbosity().
const Identification & otawa::hard::Platform::identification (void) const inline
Get identification of the current platform.
Returns
Platform identification.
void otawa::AbstractIdentifier::initProps (Property * prop, VarArg & args) protected inherited
Add the properties found in the arguments (list of Property * ended by null) to the identifier properties.
Parameters
prop First property.
args Null-ended properties to scan.
References otawa::PropList::addProp(), and otawa::Property::next().
Referenced by otawa::AbstractIdentifier::AbstractIdentifier(), and otawa::AbstractIdentifier::copy().
void otawa::AbstractIdentifier::initProps (const PropList & props) protected inherited
Initialize properties coming from the constructor.
References otawa::IDENTIFIER_ID, and otawa::AbstractIdentifier::nam.
void otawa::hard::Platform::loadCacheConfig (const elm::system::Path & path)
Load a cache configuration from the given path.
Parameters
path Path to the cache configuration.
Exceptions
LoadException Throws if there is an error.
References _cache, flags, HAS_CACHE, and otawa::hard::CacheConfiguration::load().
Referenced by configure().
void otawa::hard::Platform::loadCacheConfig (elm::xom::Element * element)
Load a cache configuration from an XML element.
Parameters
element Element to read from.
Exceptions
LoadException Thrown if there is an error.
References _cache, flags, HAS_CACHE, and otawa::hard::CacheConfiguration::load().
void otawa::hard::Platform::loadMemory (const elm::system::Path & path) throw (otawa::LoadException)
Load a memory configuration from the given path.
Parameters
path Path to the memory configuration.
Exceptions
LoadException Throws if there is an error.
References _memory, flags, HAS_MEMORY, and otawa::hard::Memory::load().
Referenced by configure().
void otawa::hard::Platform::loadMemory (elm::xom::Element * element) throw (otawa::LoadException)
Load a memory configuration from an XML element.
Parameters
element Element to read from.
Exceptions
LoadException Thrown if there is an error.
References _memory, flags, HAS_MEMORY, and otawa::hard::Memory::load().
void otawa::hard::Platform::loadProcessor (const elm::system::Path & path)
Load the processor configuration.
Parameters
path Path to the file.
Exceptions
elm::io::IOException If a configuration file cannot be loaded.
References _processor, flags, HAS_PROCESSOR, and otawa::hard::Processor::load().
Referenced by configure().
void otawa::hard::Platform::loadProcessor (elm::xom::Element * element)
Load the processor configuration from the given element.
Parameters
element Element to use.
Exceptions
LoadException If the XML element is mal-formed.
References _processor, flags, HAS_PROCESSOR, and otawa::hard::Processor::load().
const Memory& otawa::hard::Platform::memory (void) const inline
Referenced by configure(), otawa::hard::Dumper::processWorkSpace(), and otawa::dcache::BlockBuilder::setup().
const elm::String & otawa::AbstractIdentifier::name (void) const inline inherited
Get the string name of the identifier.
Returns
Identifier name.
References otawa::AbstractIdentifier::nam, and otawa::AbstractIdentifier::print().
Referenced by otawa::AlternativeProcessor::AlternativeProcessor(), otawa::AbstractIdentifier::copy(), otawa::AbstractIdentifier::fromString(), otawa::ParamProcessor::instantiate(), otawa::WorkSpace::provide(), otawa::hard::Platform::Identification::split(), and otawa::ParamProcessor::AbstractMaker::~AbstractMaker().
const int otawa::hard::Platform::pipelineDepth (void) const inline
Get the depth of the pipeline of the platform processor.
Returns
Pipeline depth.
void otawa::AbstractIdentifier::print (elm::io::Output & out) const inherited
Print the identifier.
Parameters
out Output stream.
References otawa::AbstractIdentifier::nam.
Referenced by otawa::display::GraphVizItem::getPropertiesString(), and otawa::AbstractIdentifier::name().
void otawa::AbstractIdentifier::print (elm::io::Output & output, const Property * prop) const virtual inherited
Print the value of the given property (accordint the property matches the given identifier).
It is an error to call this method with a property matching a different identifier.
Use the print() method of a property instead.
Reimplemented in otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< otawa::ccg::Node * >, otawa::Identifier< typename Problem::Domain * >, otawa::Identifier< dfa::BitSet * >, otawa::Identifier< double >, otawa::Identifier< otawa::CFG * >, otawa::Identifier< otawa::ast::AST * >, otawa::Identifier< init_t >, otawa::Identifier< otawa::Microprocessor< ExeNode > * >, otawa::Identifier< otawa::ccg::Collection * >, otawa::Identifier< Domain * >, otawa::Identifier< AbstractParamProcessor * >, otawa::Identifier< otawa::CFGInfo * >, otawa::Identifier< BracketSet * >, otawa::Identifier< elm::io::OutStream * >, otawa::Identifier< otawa::StatInfo * >, otawa::Identifier< int >, otawa::Identifier< T * >, otawa::Identifier< otawa::PropList * >, otawa::Identifier< String >, otawa::Identifier< elm::system::time_t >, otawa::Identifier< display::kind_t >, otawa::Identifier< typename P::Domain * >, otawa::Identifier< Path >, otawa::Identifier< string >, otawa::Identifier< typename otawa::dfa::hai::FirstUnrollingFixPoint::FixPointState * >, otawa::Identifier< CString >, otawa::Identifier< elm::system::Path >, otawa::Identifier< otawa::PCG * >, otawa::Identifier< otawa::BasicBlock * >, otawa::Identifier< Processor * >, otawa::Identifier< otawa::tsim::TreePath< otawa::BasicBlock *, otawa::tsim::BBPath * > * >, otawa::Identifier< log_level_t >, otawa::Identifier< otawa::CEClass * >, otawa::Identifier< bool >, otawa::Identifier< otawa::AbstractParamIdentifier * >, otawa::Identifier< typename otawa::dfa::hai::WideningFixPoint::FixPointState * >, otawa::Identifier< otawa::Progress * >, otawa::Identifier< typename otawa::dfa::hai::DefaultFixPoint::FixPointState * >, otawa::Identifier< typename FixPoint::FixPointState * >, otawa::Identifier< otawa::Symbol * >, otawa::Identifier< otawa::display::ILPSystemAddon * >, otawa::Identifier< AbstractIdentifier * >, otawa::Identifier< elm::io::Output * >, and otawa::Identifier< otawa::arm::Info * >.
void otawa::AbstractIdentifier::print (elm::io::Output & output, const Property & prop) const inline inherited
References otawa::AbstractIdentifier::print(), and otawa::AbstractIdentifier::printFormatted().
Referenced by otawa::AbstractIdentifier::print().
void otawa::AbstractIdentifier::printFormatted (io::Output & out, const Property * prop) const virtual inherited
Print the value of the given property in a formatted way, that is, possibly to perform re-scanning after.
For example, string are quoted and special character escaped.
Parameters
out Output to use.
prop Property to display.
Reimplemented in otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< T >, otawa::Identifier< otawa::ccg::Node * >, otawa::Identifier< typename Problem::Domain * >, otawa::Identifier< dfa::BitSet * >, otawa::Identifier< double >, otawa::Identifier< otawa::CFG * >, otawa::Identifier< otawa::ast::AST * >, otawa::Identifier< init_t >, otawa::Identifier< otawa::Microprocessor< ExeNode > * >, otawa::Identifier< otawa::ccg::Collection * >, otawa::Identifier< Domain * >, otawa::Identifier< AbstractParamProcessor * >, otawa::Identifier< otawa::CFGInfo * >, otawa::Identifier< BracketSet * >, otawa::Identifier< elm::io::OutStream * >, otawa::Identifier< otawa::StatInfo * >, otawa::Identifier< int >, otawa::Identifier< T * >, otawa::Identifier< otawa::PropList * >, otawa::Identifier< String >, otawa::Identifier< elm::system::time_t >, otawa::Identifier< display::kind_t >, otawa::Identifier< typename P::Domain * >, otawa::Identifier< Path >, otawa::Identifier< string >, otawa::Identifier< typename otawa::dfa::hai::FirstUnrollingFixPoint::FixPointState * >, otawa::Identifier< CString >, otawa::Identifier< elm::system::Path >, otawa::Identifier< otawa::PCG * >, otawa::Identifier< otawa::BasicBlock * >, otawa::Identifier< Processor * >, otawa::Identifier< otawa::tsim::TreePath< otawa::BasicBlock *, otawa::tsim::BBPath * > * >, otawa::Identifier< log_level_t >, otawa::Identifier< otawa::CEClass * >, otawa::Identifier< bool >, otawa::Identifier< otawa::AbstractParamIdentifier * >, otawa::Identifier< typename otawa::dfa::hai::WideningFixPoint::FixPointState * >, otawa::Identifier< otawa::Progress * >, otawa::Identifier< typename otawa::dfa::hai::DefaultFixPoint::FixPointState * >, otawa::Identifier< typename FixPoint::FixPointState * >, otawa::Identifier< otawa::Symbol * >, otawa::Identifier< otawa::display::ILPSystemAddon * >, otawa::Identifier< AbstractIdentifier * >, otawa::Identifier< elm::io::Output * >, and otawa::Identifier< otawa::arm::Info * >.
Referenced by otawa::AbstractIdentifier::print().
void otawa::AbstractIdentifier::printFormatted (elm::io::Output & output, const Property & prop) const inline inherited
References otawa::AbstractIdentifier::copy(), otawa::AbstractIdentifier::equals(), otawa::AbstractIdentifier::fromString(), otawa::AbstractIdentifier::printFormatted(), and otawa::AbstractIdentifier::type().
Referenced by otawa::AbstractIdentifier::printFormatted().
Processor * otawa::hard::Platform::processor (void) const inline
Get the current processor (possibly derivated from the current configuration).
Returns
Current processor.
int otawa::hard::Platform::regCount (void) const inline
Get the count of registers in the current platform.
Returns
Count of registers.
References cache(), and name.
Referenced by otawa::ParExeGraph::createSequenceResources().
void otawa::PropList::removeAllProp (const AbstractIdentifier * id) inherited
Remove all the properties matching the given identifier.
Parameters
id Identifier of properties to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::LoopUnroller::unroll().
void otawa::PropList::removeProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier.
Parameters
id Identifier of the property to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::PSTBuilder::buildTree(), otawa::BBRemover< T >::clean(), otawa::CFGBuilder::cleanup(), otawa::display::CFGOutput::processCFG(), otawa::SubCFGBuilder::processWorkSpace(), otawa::Identifier< otawa::arm::Info * >::remove(), and otawa::ContextualPath::Ref< T >::remove().
void otawa::PropList::removeProp (const AbstractIdentifier & id) inline inherited
References otawa::PropList::removeProp().
Referenced by otawa::PropList::removeProp().
void otawa::AbstractIdentifier::serialize (Property * prop, elm::serial2::Serializer & serializer) virtual inherited
Serialize the workspace to the current serializer.
In the default implementation, do nothing.
Parameters
prop Property containing the value to serialize.
serializer Serializer to serialize to.
Referenced by otawa::AbstractIdentifier::copy().
void otawa::hard::Platform::setBanks (const banks_t & banks) protected
Set the list of banks for an actual platform.
Parameters
banks Table of register banks.
Note
This method is only accessible from derived class implementing an actual platform.
References _banks, banks(), and rcnt.
void otawa::PropList::setProp (Property * prop) inherited
Set the property in the property list removing any double.
Parameters
prop Property to set.
References otawa::Property::_next, otawa::Property::id(), and otawa::Property::next().
void otawa::PropList::setProp (const AbstractIdentifier * id) inline inherited
References otawa::PropList::setProp().
Referenced by otawa::PropList::setProp().
const Type & otawa::AbstractIdentifier::type (void) const virtual inherited
Get the identifier of data linked with this property.
It may return Type::no_type ever meaning that the identifier does not support type system or that it is just a flag without associated data.
Returns
Type of the associated data.
Reimplemented in otawa::Identifier< T >, otawa::Identifier< otawa::ccg::Node * >, otawa::Identifier< typename Problem::Domain * >, otawa::Identifier< dfa::BitSet * >, otawa::Identifier< double >, otawa::Identifier< otawa::CFG * >, otawa::Identifier< otawa::ast::AST * >, otawa::Identifier< init_t >, otawa::Identifier< otawa::Microprocessor< ExeNode > * >, otawa::Identifier< otawa::ccg::Collection * >, otawa::Identifier< Domain * >, otawa::Identifier< AbstractParamProcessor * >, otawa::Identifier< otawa::CFGInfo * >, otawa::Identifier< BracketSet * >, otawa::Identifier< elm::io::OutStream * >, otawa::Identifier< otawa::StatInfo * >, otawa::Identifier< int >, otawa::Identifier< T * >, otawa::Identifier< otawa::PropList * >, otawa::Identifier< String >, otawa::Identifier< elm::system::time_t >, otawa::Identifier< display::kind_t >, otawa::Identifier< typename P::Domain * >, otawa::Identifier< Path >, otawa::Identifier< string >, otawa::Identifier< typename otawa::dfa::hai::FirstUnrollingFixPoint::FixPointState * >, otawa::Identifier< CString >, otawa::Identifier< elm::system::Path >, otawa::Identifier< otawa::PCG * >, otawa::Identifier< otawa::BasicBlock * >, otawa::Identifier< Processor * >, otawa::Identifier< otawa::tsim::TreePath< otawa::BasicBlock *, otawa::tsim::BBPath * > * >, otawa::Identifier< log_level_t >, otawa::Identifier< otawa::CEClass * >, otawa::Identifier< bool >, otawa::Identifier< otawa::AbstractParamIdentifier * >, otawa::Identifier< typename otawa::dfa::hai::WideningFixPoint::FixPointState * >, otawa::Identifier< otawa::Progress * >, otawa::Identifier< typename otawa::dfa::hai::DefaultFixPoint::FixPointState * >, otawa::Identifier< typename FixPoint::FixPointState * >, otawa::Identifier< otawa::Symbol * >, otawa::Identifier< otawa::display::ILPSystemAddon * >, otawa::Identifier< AbstractIdentifier * >, otawa::Identifier< elm::io::Output * >, and otawa::Identifier< otawa::arm::Info * >.
References otawa::Type::no_type.
Referenced by otawa::AbstractIdentifier::printFormatted().
Property * otawa::AbstractIdentifier::unserialize (elm::serial2::Unserializer & unserializer) virtual inherited
Unserialize the workspace to the current unserializer.
In the default implementation, do nothing.
Parameters
unserializer Unserializer to unserialize to.
Returns
Property result of unserialization, null if the property cannot be unserialized.
Referenced by otawa::AbstractIdentifier::copy().
Friends And Related Function Documentation
friend class otawa::Manager friend
Member Data Documentation
const banks_t* otawa::hard::Platform::_banks private
Referenced by findReg(), and setBanks().
const CacheConfiguration* otawa::hard::Platform::_cache private
Referenced by configure(), loadCacheConfig(), and ~Platform().
const Memory* otawa::hard::Platform::_memory private
Referenced by configure(), loadMemory(), and ~Platform().
Processor* otawa::hard::Platform::_processor private
Referenced by configure(), loadProcessor(), and ~Platform().
const elm::String otawa::hard::Platform::ANY static
Represents any architecture, platform, machine.
Referenced by accept(), otawa::hard::Platform::Identification::matches(), and otawa::hard::Platform::Identification::split().
const Platform::Identification otawa::hard::Platform::ANY_PLATFORM static
Represents any platform.
Referenced by accept().
int otawa::hard::Platform::depth private
Referenced by configure().
const elm::String otawa::hard::Platform::EABI static
Represents the EABI ABI.
Referenced by accept().
const elm::String otawa::hard::Platform::ELF static
Represents the ELF ABI.
Referenced by accept().
const PropList otawa::PropList::EMPTY static inherited
This is an empty proplist for convenience.
Referenced by otawa::DynProcessor::configure(), otawa::ActualFeature::processor(), otawa::SilentFeature::SilentFeature(), otawa::Processor::version(), and otawa::display::Driver::~Driver().
unsigned long otawa::hard::Platform::flags private
Referenced by configure(), loadCacheConfig(), loadMemory(), loadProcessor(), and ~Platform().
const unsigned long otawa::hard::Platform::HAS_CACHE = 0x00000002 static private
Referenced by configure(), loadCacheConfig(), and ~Platform().
const unsigned long otawa::hard::Platform::HAS_MEMORY = 0x00000004 static private
Referenced by configure(), loadMemory(), and ~Platform().
const unsigned long otawa::hard::Platform::HAS_PROCESSOR = 0x00000001 static private
Referenced by configure(), loadProcessor(), and ~Platform().
Identification otawa::hard::Platform::id private
const elm::String otawa::hard::Platform::LINUX static
Represents the Linux ABI.
Referenced by accept().
const elm::String otawa::hard::Platform::LINUX_2_4 static
Represents the Linux 2.4 ABI.
Referenced by accept().
const elm::String otawa::hard::Platform::LINUX_2_6 static
Represents the Linux 2.6 ABI.
Referenced by accept().
const elm::String otawa::hard::Platform::MAC static
Represents a Macintosh machine (seems to be too wide, must be refined).
Referenced by accept().
const elm::genstruct::Table< const hard::RegBank * > otawa::hard::Platform::null_banks static protected
Empty register bank table.
const elm::String otawa::hard::Platform::POWERPC static
Represents the PowerPC architecture.
Referenced by accept().
int otawa::hard::Platform::rcnt private
Referenced by setBanks().
const elm::String otawa::hard::Platform::SIM static
Represents a simulator machine.
Referenced by accept().
The documentation for this class was generated from the following files:
include/otawa/hard/Platform.h
src/prog/hardware_Platform.cpp