Otawa: otawa::ExpNode Class Reference
otawa::ExpNode Class Reference
#include </home/yashas/otawa/linux-x86_64/otawa-core-build/otawa/src/prog/ExpNode.h>
Public Types
enum kind_t {
NONE, CST, VAR, POS,
NEG, ADD, SUB, MUL,
DIV
}
Public Member Functions
ExpNode (ilp::Var *v)
ExpNode (double cst)
ExpNode (kind_t kind, ExpNode *arg)
ExpNode (kind_t kind, ExpNode *arg1, ExpNode *arg2)
kind_t kind (void) const
ilp::Var * var (void) const
double cst (void) const
ExpNode * arg (void) const
ExpNode * arg1 (void) const
ExpNode * arg2 (void) const
Private Attributes
kind_t knd
union {
ExpNode * una
struct {
ExpNode * arg1
ExpNode * arg2
} bin
ilp::Var * var
double cst
} args
Member Enumeration Documentation
enum otawa::ExpNode::kind_t
Enumerator
NONE
CST
VAR
POS
NEG
ADD
SUB
MUL
DIV
Constructor & Destructor Documentation
otawa::ExpNode::ExpNode (ilp::Var * v) inline
References args, and var().
otawa::ExpNode::ExpNode (double cst) inline
References args, and cst().
otawa::ExpNode::ExpNode (kind_t kind, ExpNode * arg) inline
References arg(), args, knd, NEG, and POS.
otawa::ExpNode::ExpNode (kind_t kind, ExpNode * arg1, ExpNode * arg2) inline
References ADD, arg1(), arg2(), args, and knd.
Member Function Documentation
ExpNode * otawa::ExpNode::arg (void) const inline
References ADD, arg1(), arg2(), args, knd, NEG, and POS.
Referenced by ExpNode(), and otawa::ipet::ConstraintLoader::normalize().
ExpNode* otawa::ExpNode::arg1 (void) const inline
Referenced by arg(), and ExpNode().
ExpNode* otawa::ExpNode::arg2 (void) const inline
Referenced by arg(), and ExpNode().
double otawa::ExpNode::cst (void) const inline
Referenced by ExpNode(), and kind().
ExpNode::kind_t otawa::ExpNode::kind (void) const inline
References args, CST, cst(), knd, VAR, and var().
Referenced by otawa::ipet::ConstraintLoader::normalize().
ilp::Var* otawa::ExpNode::var (void) const inline
Referenced by ExpNode(), and kind().
Member Data Documentation
ExpNode * otawa::ExpNode::arg1 inline
Referenced by otawa::ipet::ConstraintLoader::normalize().
ExpNode * otawa::ExpNode::arg2 inline
Referenced by otawa::ipet::ConstraintLoader::normalize().
union { ... } otawa::ExpNode::args
Referenced by arg(), ExpNode(), and kind().
struct { ... } otawa::ExpNode::bin
double otawa::ExpNode::cst inline
Referenced by otawa::ipet::ConstraintLoader::normalize().
kind_t otawa::ExpNode::knd private
Referenced by arg(), ExpNode(), and kind().
ExpNode* otawa::ExpNode::una
ilp::Var * otawa::ExpNode::var inline
Referenced by otawa::ipet::ConstraintLoader::normalize().
The documentation for this class was generated from the following file:
src/prog/ExpNode.h