Otawa: otawa::Segment Class Reference
otawa::Segment Class Reference
Program Representation
In usual file format like ELF, COFF and so on, the program file is divided in segment according platform needs or memory propertes.
#include <otawa/prog/Segment.h>
Classes
class ItemIter
Public Types
typedef t::uint32 flags_t
Public Member Functions
Segment (CString name, address_t address, ot::size size, flags_t flags)
Build a segment with the given information.
CString name (void) const
Get tne name of the segment.
flags_t flags (void) const
Get flag information about the segment.
bool isExecutable (void) const
Test if the segment is executable.
bool isWritable (void) const
Test if the segment is writable.
bool isInitialized (void) const
Test if the segment is initialized.
address_t address (void) const
Get the base address of the segment.
ot::size size (void) const
Get the size of the segment.
address_t topAddress (void) const
ProgItem * findItemAt (const Address &addr)
Find an item by its address.
Inst * findInstAt (const Address &addr)
Find an instruction by its address.
bool contains (const Address &addr) const
Property * getProp (const AbstractIdentifier *id) const
Find a property by its identifier.
void setProp (Property *prop)
Set the property in the property list removing any double.
void setProp (const AbstractIdentifier *id)
void removeProp (const AbstractIdentifier *id)
Remove a property matching the given identifier.
void removeProp (const AbstractIdentifier &id)
Property * extractProp (const AbstractIdentifier *id)
Remove a property matching the given identifier and return it.
Property * extractProp (const AbstractIdentifier &id)
Remove a property matching the given identifier and return it.
void addProp (Property *prop)
Add property to the list without checking of duplication.
void removeAllProp (const AbstractIdentifier *id)
Remove all the properties matching the given identifier.
bool hasProp (const AbstractIdentifier &id) const
Test if the property list contains a property matching the given identifier.
void clearProps (void)
Remove all properties from the list.
void addProps (const PropList &props)
Add all properties from the given property list, in a reverse order.
void print (elm::io::Output &out) const
Display the current property list.
Static Public Attributes
static const flags_t EXECUTABLE = 0x01
Segment flags denoting an executable segment.
static const flags_t WRITABLE = 0x02
Segment flags denoting a writable segment.
static const flags_t INITIALIZED = 0x04
Segment flags denoting an initialzied segment.
static const PropList EMPTY
This is an empty proplist for convenience.
Protected Member Functions
virtual Inst * decode (address_t address)
Decode the instruction at the given address.
virtual ~Segment (void)
Protected destructor for avoiding implementation unexpected deletion.
void insert (ProgItem *item)
Insert the item in the list.
Private Attributes
flags_t _flags
CString _name
Address _address
ot::size _size
inhstruct::DLList items
ProgItem ** map
Friends
class File
Detailed Description
In usual file format like ELF, COFF and so on, the program file is divided in segment according platform needs or memory propertes.
Usually, we find a ".text" segment containing program code,
".data" containing initialized data, ".bss" containing uninitialized data, ".rodata" containing read-only data. Yet, more segments may be available.
Member Typedef Documentation
typedef t::uint32 otawa::Segment::flags_t
Constructor & Destructor Documentation
otawa::Segment::Segment (CString name, address_t address, ot::size size, flags_t flags)
Build a segment with the given information.
Parameters
name Segment name in the file format (".text", ".data", ...).
address Segment address in the process memory space.
size Segment size (in bytes).
flags As returned by the flags() accessor. A combination of WRITABLE, EXECUTABLE and INITIALIZED .
References map, and MAP_SIZE.
otawa::Segment::~Segment (void) protected virtual
Protected destructor for avoiding implementation unexpected deletion.
References items, and map.
Member Function Documentation
void otawa::PropList::addProp (Property * prop) inherited
Add property to the list without checking of duplication.
Parameters
prop Property to add.
References otawa::Property::_next.
Referenced by otawa::Identifier< T >::add(), otawa::ast::ASTInfo::ASTInfo(), otawa::Identifier< otawa::arm::Info * >::copy(), otawa::AbstractIdentifier::initProps(), otawa::ContextualProperty::make(), otawa::script::Script::makeConfig(), otawa::ccg::Builder::processLBlockSet(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), and otawa::ContextualProperty::refProps().
void otawa::PropList::addProps (const PropList & props) inherited
Add all properties from the given property list, in a reverse order.
Parameters
props Property list to clone.
References otawa::Property::copy(), otawa::PropList::head, and otawa::Property::next().
Referenced by otawa::display::CFGDrawer::CFGDrawer(), otawa::display::GraphVizGraph::GraphVizGraph(), otawa::ParamFeature::instantiate(), otawa::Manager::loadXML(), otawa::display::GraphVizGraph::newEdge(), otawa::display::GraphVizGraph::newNode(), otawa::Process::Process(), otawa::display::GraphVizItem::setProps(), otawa::VirtualBasicBlock::VirtualBasicBlock(), and otawa::VirtualCFG::VirtualCFG().
address_t otawa::Segment::address (void) const inline
Get the base address of the segment.
Returns
Base address of the segment or 0 if no address has been assigned to the segment.
Referenced by findItemAt(), insert(), and otawa::clp::operator<<().
void otawa::PropList::clearProps (void) inherited
Remove all properties from the list.
References otawa::Property::next().
Referenced by otawa::PSTBuilder::getVCFG(), otawa::display::GraphVizItem::setProps(), and otawa::WorkSpace::~WorkSpace().
bool otawa::Segment::contains (const Address & addr) const inline
References otawa::ot::address().
Inst * otawa::Segment::decode (address_t address) protected virtual
Decode the instruction at the given address.
This method must overriden by the ISA plugins to provide the actual decoding of the instruction. This method returns null as the default.
Parameters
address Address of the instruction to decode.
Returns
Decoded instruction or null if the address is invalid.
Referenced by findInstAt().
Property * otawa::PropList::extractProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::script::Script::makeConfig().
Property * otawa::PropList::extractProp (const AbstractIdentifier & id) inline inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::PropList::extractProp().
Referenced by otawa::PropList::extractProp().
Inst * otawa::Segment::findInstAt (const Address & addr)
Find an instruction by its address.
Parameters
addr Address to find an instruction for.
Returns
Found instruction or null.
References decode(), findItemAt(), insert(), and otawa::ProgItem::toInst().
ProgItem * otawa::Segment::findItemAt (const Address & addr)
Find an item by its address.
Parameters
addr Address to find an instruction for.
Returns
Found item or null.
References otawa::ProgItem::address(), address(), map, MAP_INDEX, otawa::ProgItem::next(), otawa::Address::page(), and topAddress().
Referenced by findInstAt().
int otawa::Segment::flags (void) const inline
Get flag information about the segment.
This flags are composed by OR'ing the constants EXECUTABLE, WRITABLE and INITIALIZED .
Returns
Flags value.
Property * otawa::PropList::getProp (const AbstractIdentifier * id) const inherited
Find a property by its identifier.
Parameters
id Identifier of the property to find.
Returns
Found property or null.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::Identifier< otawa::arm::Info * >::exists(), otawa::ContextualProperty::exists(), otawa::ContextualProperty::find(), otawa::Identifier< T >::get(), otawa::ContextualProperty::make(), otawa::ParamFeature::matches(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::print(), otawa::ContextualProperty::print(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), otawa::ContextualProperty::refProps(), otawa::Identifier< T >::set(), otawa::Identifier< T >::use(), and otawa::Identifier< T >::value().
bool otawa::PropList::hasProp (const AbstractIdentifier & id) const inline inherited
Test if the property list contains a property matching the given identifier.
Parameters
id Property identifier to look for.
Returns
True if the list contains the matching property, false else.
References otawa::p::print().
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::Monitor::configure(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::exists(), and otawa::Manager::setVerbosity().
void otawa::Segment::insert (ProgItem * item) protected
Insert the item in the list.
Parameters
item Item to insert.
References otawa::ProgItem::address(), address(), items, map, MAP_INDEX, otawa::ProgItem::next(), otawa::ProgItem::previous(), otawa::ProgItem::size(), otawa::ProgItem::topAddress(), and topAddress().
Referenced by findInstAt().
bool otawa::Segment::isExecutable (void) const inline
Test if the segment is executable.
Returns
True if the segment is executable, false else.
bool otawa::Segment::isInitialized (void) const inline
Test if the segment is initialized.
Returns
True if the segment is initialized, false else.
bool otawa::Segment::isWritable (void) const inline
Test if the segment is writable.
Returns
True if the segment is writable, false else.
CString otawa::Segment::name (void) const inline
Get tne name of the segment.
Returns
Name of the segment.
Referenced by otawa::CFGBuilder::buildCFG().
void otawa::PropList::print (elm::io::Output & out) const inherited
Display the current property list.
Parameters
out Output to use.
Referenced by otawa::Edge::kindName(), otawa::operator<<(), and otawa::ContextualProperty::print().
void otawa::PropList::removeAllProp (const AbstractIdentifier * id) inherited
Remove all the properties matching the given identifier.
Parameters
id Identifier of properties to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::LoopUnroller::unroll().
void otawa::PropList::removeProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier.
Parameters
id Identifier of the property to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::PSTBuilder::buildTree(), otawa::BBRemover< T >::clean(), otawa::CFGBuilder::cleanup(), otawa::display::CFGOutput::processCFG(), otawa::SubCFGBuilder::processWorkSpace(), otawa::Identifier< otawa::arm::Info * >::remove(), and otawa::ContextualPath::Ref< T >::remove().
void otawa::PropList::removeProp (const AbstractIdentifier & id) inline inherited
References otawa::PropList::removeProp().
Referenced by otawa::PropList::removeProp().
void otawa::PropList::setProp (Property * prop) inherited
Set the property in the property list removing any double.
Parameters
prop Property to set.
References otawa::Property::_next, otawa::Property::id(), and otawa::Property::next().
void otawa::PropList::setProp (const AbstractIdentifier * id) inline inherited
References otawa::PropList::setProp().
Referenced by otawa::PropList::setProp().
size_t otawa::Segment::size (void) const inline
Get the size of the segment.
Returns
Size of the segment.
address_t otawa::Segment::topAddress (void) const inline
Referenced by otawa::CFGBuilder::buildCFG(), findItemAt(), and insert().
Friends And Related Function Documentation
friend class File friend
Member Data Documentation
Address otawa::Segment::_address private
flags_t otawa::Segment::_flags private
CString otawa::Segment::_name private
ot::size otawa::Segment::_size private
const PropList otawa::PropList::EMPTY static inherited
This is an empty proplist for convenience.
Referenced by otawa::DynProcessor::configure(), otawa::ActualFeature::processor(), otawa::SilentFeature::SilentFeature(), otawa::Processor::version(), and otawa::display::Driver::~Driver().
otawa::Segment::EXECUTABLE = 0x01 static
Segment flags denoting an executable segment.
otawa::Segment::INITIALIZED = 0x04 static
Segment flags denoting an initialzied segment.
inhstruct::DLList otawa::Segment::items private
Referenced by insert(), otawa::Segment::ItemIter::ItemIter(), and ~Segment().
ProgItem** otawa::Segment::map private
Referenced by findItemAt(), insert(), Segment(), and ~Segment().
otawa::Segment::WRITABLE = 0x02 static
Segment flags denoting a writable segment.
The documentation for this class was generated from the following files:
include/otawa/prog/Segment.h
src/prog/prog_Segment.cpp