Otawa: otawa::hard::CacheConfiguration Class Reference
otawa::hard::CacheConfiguration Class Reference
Platform Description
This class represents the full configuration of caches of a processor.
#include <otawa/hard/CacheConfiguration.h>
Public Member Functions
CacheConfiguration (const Cache *inst_cache=0, const Cache *data_cache=0)
Build a new configuration from the passed cache.
virtual ~CacheConfiguration (void)
const Cache * instCache (void) const
Get the instruction cache.
const Cache * dataCache (void) const
Get the data cache.
bool hasInstCache (void) const
Check if some instruction is available (in a harvard or an unified architecture).
bool hasDataCache (void) const
Check if some data is available (in a harvard or an unified architecture).
bool isUnified (void) const
Check if the cache ois unified.
bool isHarvard (void) const
Check if the cache follows the Harvard architecture.
string cacheName (const Cache *cache) const
Compute name of the cache.
Static Public Member Functions
static CacheConfiguration * load (elm::xom::Element *element)
Load a cache configuration from the given element.
static CacheConfiguration * load (const elm::system::Path &path)
Load a cache configuration from an XML file.
Static Public Attributes
static const CacheConfiguration NO_CACHE
Useful constant representing a configuration without cache.
Protected Attributes
const Cache * icache
const Cache * dcache
Private Member Functions
SERIALIZABLE (CacheConfiguration, FIELD(icache)&FIELD(dcache))
Detailed Description
This class represents the full configuration of caches of a processor.
Constructor & Destructor Documentation
otawa::hard::CacheConfiguration::CacheConfiguration (const Cache * inst_cache = 0, const Cache * data_cache = 0) inline
Build a new configuration from the passed cache.
Build a cache configuration.
For creating a no-cache configuration, do not give any cache in argument. If you want to create an unified cache, pass the the same cache as inst_cache and data_cache.
Parameters
inst_cache Instruction cache.
data_cache Data cache.
icache Instruction cache.
dcache Data cache.
Note
To get an unified cache, use the same value for icache and dcache.
Referenced by load().
otawa::hard::CacheConfiguration::~CacheConfiguration (void) virtual
Member Function Documentation
string otawa::hard::CacheConfiguration::cacheName (const Cache * cache) const
Compute name of the cache.
Parameters
cache Cache to get name for.
Returns
Cache name.
References otawa::CACHE_CONFIG, otawa::CACHE_CONFIG_ELEMENT, otawa::CACHE_CONFIG_PATH, otawa::hard::CACHE_CONFIGURATION, otawa::hard::CACHE_CONFIGURATION_FEATURE, otawa::p::config, otawa::Processor::configure(), dataCache(), dcache, icache, instCache(), otawa::hard::L1_DCACHE, otawa::hard::L1_ICACHE, load(), otawa::p::init::maker(), otawa::hard::Cache::nextLevel(), otawa::p::init::provide(), and SERIALIZE().
const Cache * otawa::hard::CacheConfiguration::dataCache (void) const inline
Get the data cache.
Returns
Data cache.
Referenced by cacheName(), otawa::dcache::operator<<(), otawa::dcache::DirtyManager::t::print(), and otawa::ipet::TrivialDataCacheManager::processBB().
bool otawa::hard::CacheConfiguration::hasDataCache (void) const inline
Check if some data is available (in a harvard or an unified architecture).
Returns
True if a data cache data is available, false else.
bool otawa::hard::CacheConfiguration::hasInstCache (void) const inline
Check if some instruction is available (in a harvard or an unified architecture).
Returns
True if instruction cache is available, false else.
Referenced by otawa::ets::ACSComputation::applyProcess(), otawa::ets::ACSComputation::initialization(), and otawa::ets::ACSComputation::processWorkSpace().
const Cache * otawa::hard::CacheConfiguration::instCache (void) const inline
Get the instruction cache.
Returns
Instruction cache.
Referenced by cacheName(), otawa::ets::ACSComputation::initialization(), otawa::ParExeGraph::ParExeGraph(), otawa::ets::ACSComputation::processAST(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::EdgeCAT2Builder::processCFG(), otawa::LBlockProcessor::processWorkSpace(), otawa::EdgeCAT2ConstraintBuilder::processWorkSpace(), otawa::ets::ACSComputation::processWorkSpace(), otawa::EdgeACSBuilder::processWorkSpace(), otawa::ipet::TrivialInstCacheManager::setup(), otawa::ccg::LBlockBuilder::setup(), and otawa::LBlockBuilder::setup().
bool otawa::hard::CacheConfiguration::isHarvard (void) const inline
Check if the cache follows the Harvard architecture.
Returns
True if the cache follows the Harvard architecture, false else.
References cache().
bool otawa::hard::CacheConfiguration::isUnified (void) const inline
Check if the cache ois unified.
Returns
True if the cache is unified, false else.
Referenced by otawa::ets::ACSComputation::applyProcess(), otawa::ets::ACSComputation::initialization(), otawa::ipet::TrivialDataCacheManager::processBB(), and otawa::ets::ACSComputation::processWorkSpace().
CacheConfiguration * otawa::hard::CacheConfiguration::load (elm::xom::Element * element) static
Load a cache configuration from the given element.
Parameters
element Element to load from.
Returns
Built cache configuration.
References CacheConfiguration().
Referenced by cacheName(), and otawa::hard::Platform::loadCacheConfig().
CacheConfiguration * otawa::hard::CacheConfiguration::load (const elm::system::Path & path) static
Load a cache configuration from an XML file.
Parameters
path Path to the file.
Returns
Built cache configuration.
References CacheConfiguration().
otawa::hard::CacheConfiguration::SERIALIZABLE (CacheConfiguration , FIELD(icache)&FIELD(dcache)) private
Member Data Documentation
const Cache * otawa::hard::CacheConfiguration::dcache protected
Referenced by cacheName().
const Cache* otawa::hard::CacheConfiguration::icache protected
Referenced by cacheName().
const CacheConfiguration otawa::hard::CacheConfiguration::NO_CACHE static
Useful constant representing a configuration without cache.
The documentation for this class was generated from the following files:
include/otawa/hard/CacheConfiguration.h
src/prog/hardware_CacheConfiguration.cpp