Otawa: otawa::AccessedAddresses Class Reference
otawa::AccessedAddresses Class Reference
Memory Accesses
For each basic block, provide the list of performed memory accesses and their addresses.
#include <otawa/stack/AccessedAddress.h>
Public Member Functions
AccessedAddresses ()
~AccessedAddresses (void)
template<class C >
void set (const C &coll)
void clear (void)
int size (void) const
AccessedAddress * get (int index)
void print (io::Output &out) const
Private Attributes
int _size
AccessedAddress ** addrs
Detailed Description
For each basic block, provide the list of performed memory accesses and their addresses.
This class is designed to be build in an incremental way. Each analysis with the ability to produce a memory address can add its own contribution to this class.
Constructor & Destructor Documentation
otawa::AccessedAddresses::AccessedAddresses () inline
otawa::AccessedAddresses::~AccessedAddresses (void) inline
Member Function Documentation
void otawa::AccessedAddresses::clear (void) inline
AccessedAddress* otawa::AccessedAddresses::get (int index) inline
Referenced by otawa::dcache::BlockBuilder::processBB().
void otawa::AccessedAddresses::print (io::Output & out) const inline
Referenced by otawa::operator<<().
template<class C > void otawa::AccessedAddresses::set (const C & coll) inline
Referenced by otawa::stack::Manager::updatePath().
int otawa::AccessedAddresses::size (void) const inline
Referenced by otawa::dcache::BlockBuilder::processBB().
Member Data Documentation
int otawa::AccessedAddresses::_size private
AccessedAddress** otawa::AccessedAddresses::addrs private
The documentation for this class was generated from the following file:
include/otawa/stack/AccessedAddress.h