Otawa: otawa::se::SEAdd Class Reference
otawa::se::SEAdd Class Reference
Addition.
#include <otawa/data/clp/SymbolicExpr.h>
Public Member Functions
SEAdd (SymbExpr *a=NULL, SymbExpr *b=NULL, SymbExpr *parent=NULL)
Constructors.
SEAdd (const SEAdd &expr)
Copy constructor.
virtual SEAdd * copy (void)
Operators.
virtual SymbExpr & operator= (const SEAdd &expr)
Affectation operator.
virtual bool operator== (const SymbExpr &expr) const
Equality.
virtual String asString (const hard::Platform *pf=0)
Operation.
virtual void canonize (void)
Try to recursively transform the expression into it its canonized form.
bool operator!= (const SymbExpr &expr) const
Not equal operator.
op_t op (void) const
Accessors.
SymbExpr * a (void) const
SymbExpr * b (void) const
V val (void) const
SymbExpr * parent (void) const
void replace (SymbExpr *searched_se, SymbExpr *new_se)
Operation.
void print (io::Output &out, const hard::Platform *pf=0)
Output a string representation of the expression.
virtual Vector< V > used_reg (void)
Return the list of registers used (recursively) in this expression.
virtual Vector< V > used_addr (void)
Return the list of memory addresses used (recursively) in this expression.
void set_a (SymbExpr *a)
Setters.
void set_b (SymbExpr *b)
Set the second child expression (b)
void set_parent (SymbExpr *parent)
Set the reference to the parent of this.
Protected Attributes
op_t _op
Attributes.
SymbExpr * _a
SymbExpr * _b
V _val
SymbExpr * _parent
Detailed Description
Addition.
Constructor & Destructor Documentation
otawa::se::SEAdd::SEAdd (SymbExpr * a = NULL, SymbExpr * b = NULL, SymbExpr * parent = NULL) inline
Constructors.
Build a new Addition Symbolic Expression [+ a b]
Parameters
a is a pointer to the first child expression. This pointer will be used as is (no copy), so make sure you 'new' or '->copy()' the expression before.
b is a pointer to the second child expression. This pointer will be used as is (no copy), so make sure you 'new' or '->copy()' the expression before.
parent a pointer to the parent
otawa::se::SEAdd::SEAdd (const SEAdd & expr) inline
Copy constructor.
Parameters
expr the expression to copy
Member Function Documentation
SymbExpr* otawa::se::SymbExpr::a (void) const inline inherited
Returns
a pointer to the first child (a) of the expression (or NULL)
Referenced by otawa::se::SENeg::canonize(), canonize(), otawa::se::SECmp::canonize(), otawa::se::getFilterForAddr(), otawa::se::getFilterForReg(), otawa::se::FilterBuilder::makeFilters(), otawa::clp::operator<<(), otawa::se::SENeg::operator==(), operator==(), and otawa::se::SECmp::operator==().
String otawa::se::SEAdd::asString (const hard::Platform * pf = 0) virtual
Operation.
Returns
a string reprensentation of the expression
Reimplemented from otawa::se::SymbExpr.
References otawa::se::SymbExpr::_a, otawa::se::SymbExpr::_b, and otawa::se::SymbExpr::asString().
SymbExpr* otawa::se::SymbExpr::b (void) const inline inherited
Returns
a pointer to the second child (b) of the expression (or NULL)
Referenced by otawa::se::SENeg::canonize(), canonize(), otawa::se::SECmp::canonize(), otawa::se::getFilterForAddr(), otawa::se::getFilterForReg(), otawa::se::FilterBuilder::makeFilters(), otawa::clp::operator<<(), operator==(), and otawa::se::SECmp::operator==().
void otawa::se::SEAdd::canonize (void) virtual
Try to recursively transform the expression into it its canonized form.
Reimplemented from otawa::se::SymbExpr.
References otawa::se::SymbExpr::_a, otawa::se::SymbExpr::_b, otawa::se::SymbExpr::_parent, otawa::se::SymbExpr::a(), otawa::se::ADD, otawa::se::ADDR, otawa::se::SymbExpr::b(), otawa::se::SymbExpr::canonize(), canonize(), otawa::se::CONST, otawa::se::SymbExpr::copy(), otawa::se::SymbExpr::op(), otawa::se::REG, otawa::se::SymbExpr::set_a(), otawa::se::SymbExpr::set_b(), and otawa::se::SymbExpr::val().
Referenced by canonize().
SEAdd * otawa::se::SEAdd::copy (void) virtual
Operators.
Copy operator
Returns
a pointer to a copy of this
Reimplemented from otawa::se::SymbExpr.
References otawa::se::SymbExpr::_a, otawa::se::SymbExpr::_b, and otawa::se::SymbExpr::copy().
op_t otawa::se::SymbExpr::op (void) const inline inherited
Accessors.
Returns
the operator of the expression
Referenced by otawa::se::SENeg::canonize(), canonize(), otawa::se::SECmp::canonize(), otawa::se::getFilterForAddr(), otawa::se::getFilterForReg(), otawa::se::FilterBuilder::makeFilters(), otawa::clp::operator<<(), otawa::se::SEConst::operator==(), otawa::se::SEAddr::operator==(), otawa::se::SEReg::operator==(), otawa::se::SENeg::operator==(), operator==(), and otawa::se::SECmp::operator==().
bool otawa::se::SymbExpr::operator!= (const SymbExpr & expr) const inherited
Not equal operator.
Parameters
expr the expression to be compared with this
Returns
if the expression doesn't reprensents the same as expr
References otawa::se::SymbExpr::operator==().
SymbExpr & otawa::se::SEAdd::operator= (const SEAdd & expr) virtual
Affectation operator.
Parameters
expr the expression to be copied in this
Returns
this
References otawa::se::SymbExpr::_a, otawa::se::SymbExpr::_b, otawa::se::SymbExpr::_op, otawa::se::SymbExpr::set_a(), and otawa::se::SymbExpr::set_b().
bool otawa::se::SEAdd::operator== (const SymbExpr & expr) const virtual
Equality.
Parameters
expr the expression to be compared with this
Returns
if the expression reprensents the same as expr (recursively)
Reimplemented from otawa::se::SymbExpr.
References otawa::se::SymbExpr::_a, otawa::se::SymbExpr::_b, otawa::se::SymbExpr::_op, otawa::se::SymbExpr::a(), otawa::se::SymbExpr::b(), and otawa::se::SymbExpr::op().
SymbExpr* otawa::se::SymbExpr::parent (void) const inline inherited
Returns
a pointer to the parent of this (or NULL)
References otawa::p::print().
void otawa::se::SymbExpr::print (io::Output & out, const hard::Platform * pf = 0) inherited
Output a string representation of the expression.
Parameters
out the output channel
pf current plarform
References otawa::se::SymbExpr::asString().
Referenced by otawa::se::FilterBuilder::makeFilters(), and operator<<().
void otawa::se::SymbExpr::replace (SymbExpr * searched_se, SymbExpr * new_se) inherited
Operation.
Recursively replace in this the searched_se expression by new_se
Parameters
searched_se the researched expression
new_se the expression that will replace searched_se
new_se will be copied each time it replace a searched_se.
References otawa::se::SymbExpr::_a, otawa::se::SymbExpr::_b, otawa::se::SymbExpr::replace(), otawa::se::SymbExpr::set_a(), and otawa::se::SymbExpr::set_b().
Referenced by otawa::se::getFilterForAddr(), otawa::se::getFilterForReg(), otawa::se::FilterBuilder::makeFilters(), and otawa::se::SymbExpr::replace().
void otawa::se::SymbExpr::set_a (SymbExpr * a) inline inherited
Setters.
Set the first child expression (a)
Parameters
a a pointer to the new first child
A copy of a will be set as first child. If there was a first child in this expression, it will be delete, but after the copy of a (so it's safe to set_a() a child expression of this->a()).
References otawa::se::SymbExpr::copy(), and otawa::se::SymbExpr::set_parent().
Referenced by otawa::se::SENeg::canonize(), canonize(), otawa::se::SECmp::canonize(), otawa::se::SymbExpr::operator=(), otawa::se::SENeg::operator=(), operator=(), otawa::se::SECmp::operator=(), and otawa::se::SymbExpr::replace().
void otawa::se::SymbExpr::set_b (SymbExpr * b) inline inherited
Set the second child expression (b)
Parameters
b a pointer to the new second child
A copy of b will be set as second child. If there was a second child in this expression, it will be delete, but after the copy of b (so it's safe to set_b() a child expression of this->b()).
References otawa::se::SymbExpr::copy(), and otawa::se::SymbExpr::set_parent().
Referenced by otawa::se::SENeg::canonize(), canonize(), otawa::se::SECmp::canonize(), otawa::se::SymbExpr::operator=(), operator=(), otawa::se::SECmp::operator=(), and otawa::se::SymbExpr::replace().
void otawa::se::SymbExpr::set_parent (SymbExpr * parent) inline inherited
Set the reference to the parent of this.
Parameters
parent a pointer to the new parent.
Warning: this do not remove the reference to this in the old parent.
Referenced by otawa::se::SymbExpr::set_a(), and otawa::se::SymbExpr::set_b().
Vector< V > otawa::se::SymbExpr::used_addr (void) virtual inherited
Return the list of memory addresses used (recursively) in this expression.
Returns
a vector of int.
Reimplemented in otawa::se::SEAddr.
References otawa::se::SymbExpr::_a, otawa::se::SymbExpr::_b, and otawa::se::SymbExpr::used_addr().
Referenced by otawa::se::FilterBuilder::makeFilters(), and otawa::se::SymbExpr::used_addr().
Vector< V > otawa::se::SymbExpr::used_reg (void) virtual inherited
Return the list of registers used (recursively) in this expression.
Returns
a vector of int.
Reimplemented in otawa::se::SEReg.
References otawa::se::SymbExpr::_a, otawa::se::SymbExpr::_b, and otawa::se::SymbExpr::used_reg().
Referenced by otawa::se::FilterBuilder::makeFilters(), and otawa::se::SymbExpr::used_reg().
V otawa::se::SymbExpr::val (void) const inline inherited
Returns
the value of this expression
Referenced by otawa::se::SENeg::canonize(), canonize(), otawa::se::getFilterForAddr(), otawa::se::getFilterForReg(), otawa::se::FilterBuilder::makeFilters(), otawa::clp::operator<<(), otawa::se::SEConst::operator==(), otawa::se::SEAddr::operator==(), and otawa::se::SEReg::operator==().
Member Data Documentation
SymbExpr* otawa::se::SymbExpr::_a protected inherited
Referenced by otawa::se::SENeg::asString(), asString(), otawa::se::SymbExpr::canonize(), otawa::se::SENeg::canonize(), canonize(), otawa::se::SECmp::canonize(), otawa::se::SymbExpr::copy(), otawa::se::SENeg::copy(), copy(), otawa::se::SECmp::copy(), otawa::se::SECmp::logicalNot(), otawa::se::SymbExpr::operator=(), otawa::se::SENeg::operator=(), operator=(), otawa::se::SECmp::operator=(), otawa::se::SENeg::operator==(), operator==(), otawa::se::SECmp::operator==(), otawa::se::SymbExpr::replace(), otawa::se::SymbExpr::SymbExpr(), otawa::se::SymbExpr::used_addr(), and otawa::se::SymbExpr::used_reg().
SymbExpr* otawa::se::SymbExpr::_b protected inherited
Referenced by asString(), otawa::se::SymbExpr::canonize(), canonize(), otawa::se::SECmp::canonize(), otawa::se::SymbExpr::copy(), copy(), otawa::se::SECmp::copy(), otawa::se::SECmp::logicalNot(), otawa::se::SymbExpr::operator=(), operator=(), otawa::se::SECmp::operator=(), operator==(), otawa::se::SECmp::operator==(), otawa::se::SymbExpr::replace(), otawa::se::SymbExpr::SymbExpr(), otawa::se::SymbExpr::used_addr(), and otawa::se::SymbExpr::used_reg().
op_t otawa::se::SymbExpr::_op protected inherited
Attributes.
Referenced by otawa::se::SECmp::asString(), otawa::se::SECmp::canonize(), otawa::se::SymbExpr::copy(), otawa::se::SECmp::copy(), otawa::se::SECmp::logicalNot(), otawa::se::SymbExpr::operator=(), otawa::se::SEConst::operator=(), otawa::se::SEAddr::operator=(), otawa::se::SEReg::operator=(), otawa::se::SENeg::operator=(), operator=(), otawa::se::SECmp::operator=(), otawa::se::SymbExpr::operator==(), otawa::se::SEConst::operator==(), otawa::se::SEAddr::operator==(), otawa::se::SEReg::operator==(), otawa::se::SENeg::operator==(), operator==(), and otawa::se::SECmp::operator==().
SymbExpr* otawa::se::SymbExpr::_parent protected inherited
Referenced by otawa::se::SENeg::canonize(), and canonize().
V otawa::se::SymbExpr::_val protected inherited
Referenced by otawa::se::SEConst::asString(), otawa::se::SEAddr::asString(), otawa::se::SEReg::asString(), otawa::se::SymbExpr::copy(), otawa::se::SEConst::copy(), otawa::se::SEAddr::copy(), otawa::se::SEReg::copy(), otawa::se::SymbExpr::operator=(), otawa::se::SEConst::operator=(), otawa::se::SEAddr::operator=(), otawa::se::SEReg::operator=(), otawa::se::SEConst::operator==(), otawa::se::SEAddr::operator==(), otawa::se::SEReg::operator==(), otawa::se::SEAddr::used_addr(), and otawa::se::SEReg::used_reg().
The documentation for this class was generated from the following files:
include/otawa/data/clp/SymbolicExpr.h
src/prog/clp_symbolic_expr.cpp