Otawa: otawa::ParExeInst Class Reference
otawa::ParExeInst Class Reference
Parametric Execution Graph
Instruction as presented in the ParExeGraph.
#include <otawa/parexegraph/ParExeGraph.h>
Classes
class NodeIterator
class ProducingInstIterator
Public Member Functions
ParExeInst (Inst *inst, BasicBlock *bb, code_part_t part, int index)
Inst * inst ()
code_part_t codePart ()
int index ()
void setIndex (int index)
ParExeNode * firstNode ()
ParExeNode * node (int index)
void setFetchNode (ParExeNode *node)
void setExecNode (ParExeNode *node)
void setFirstFUNode (ParExeNode *node)
void setLastFUNode (ParExeNode *node)
ParExeNode * fetchNode ()
ParExeNode * execNode ()
ParExeNode * firstFUNode ()
ParExeNode * lastFUNode ()
void addProducingInst (ParExeInst *inst)
BasicBlock * basicBlock ()
void addNode (ParExeNode *node)
Relates a node to an instruction in the sequence.
void removeNode (ParExeNode *node)
void deleteNodes ()
Private Attributes
Inst * _inst
BasicBlock * _bb
code_part_t _part
int _index
elm::genstruct::Vector< ParExeNode * > _nodes
ParExeNode * _fetch_node
ParExeNode * _exec_node
ParExeNode * _first_fu_node
ParExeNode * _last_fu_node
elm::genstruct::Vector< ParExeInst * > _producing_insts
Detailed Description
Instruction as presented in the ParExeGraph.
See also
Parametric Execution Graph
Constructor & Destructor Documentation
otawa::ParExeInst::ParExeInst (Inst * inst, BasicBlock * bb, code_part_t part, int index) inline
Member Function Documentation
void otawa::ParExeInst::addNode (ParExeNode * node)
Relates a node to an instruction in the sequence.
References otawa::ParExeStage::category(), otawa::ParExeStage::FETCH, and otawa::ParExeNode::stage().
void otawa::ParExeInst::addProducingInst (ParExeInst * inst) inline
BasicBlock* otawa::ParExeInst::basicBlock () inline
code_part_t otawa::ParExeInst::codePart () inline
Referenced by otawa::ParExeNode::ParExeNode().
void otawa::ParExeInst::deleteNodes () inline
ParExeNode* otawa::ParExeInst::execNode () inline
ParExeNode* otawa::ParExeInst::fetchNode () inline
Referenced by otawa::etime::EdgeTimeBuilder::apply(), and otawa::etime::EdgeTimeBuilder::rollback().
ParExeNode* otawa::ParExeInst::firstFUNode () inline
ParExeNode* otawa::ParExeInst::firstNode (void) inline
int otawa::ParExeInst::index (void) inline
Referenced by otawa::ParExeNode::ParExeNode().
Inst* otawa::ParExeInst::inst (void) inline
Referenced by otawa::ParExeGraph::addEdgesForFetch(), otawa::ParExeGraph::addEdgesForMemoryOrder(), and otawa::ParExeGraph::pipeline().
ParExeNode* otawa::ParExeInst::lastFUNode () inline
ParExeNode* otawa::ParExeInst::node (int index) inline
void otawa::ParExeInst::removeNode (ParExeNode * node) inline
void otawa::ParExeInst::setExecNode (ParExeNode * node) inline
void otawa::ParExeInst::setFetchNode (ParExeNode * node) inline
void otawa::ParExeInst::setFirstFUNode (ParExeNode * node) inline
void otawa::ParExeInst::setIndex (int index) inline
void otawa::ParExeInst::setLastFUNode (ParExeNode * node) inline
Member Data Documentation
BasicBlock* otawa::ParExeInst::_bb private
ParExeNode* otawa::ParExeInst::_exec_node private
ParExeNode* otawa::ParExeInst::_fetch_node private
ParExeNode* otawa::ParExeInst::_first_fu_node private
int otawa::ParExeInst::_index private
Inst* otawa::ParExeInst::_inst private
ParExeNode* otawa::ParExeInst::_last_fu_node private
elm::genstruct::Vector<ParExeNode *> otawa::ParExeInst::_nodes private
code_part_t otawa::ParExeInst::_part private
elm::genstruct::Vector<ParExeInst *> otawa::ParExeInst::_producing_insts private
The documentation for this class was generated from the following files:
include/otawa/parexegraph/ParExeGraph.h
src/prog/parexegraph_ParExeGraph.cpp