Otawa: otawa::display::Driver Class Reference
otawa::display::Driver Class Reference abstract
ODisplay Library
A driver provides facilities to display a graph.
#include <otawa/display/Driver.h>
Public Member Functions
virtual ~Driver (void)
virtual Graph * newGraph (const PropList &defaultGraphStyle=PropList::EMPTY, const PropList &defaultNodeStyle=PropList::EMPTY, const PropList &defaultEdgeStyle=PropList::EMPTY) const =0
Creates a new graph with default styles given.
Static Public Member Functions
static Driver * find (string name="")
Find a driver by its name.
static Driver * find (kind_t kind)
Detailed Description
A driver provides facilities to display a graph.
The newGraph() method build a graph that may be populated according the needs of the graph to display.
See also
odisplay
Constructor & Destructor Documentation
virtual otawa::display::Driver::~Driver (void) inline virtual
References otawa::PropList::EMPTY.
Member Function Documentation
Driver * otawa::display::Driver::find (string name = "") static
Find a driver by its name.
Parameters
name Name of the driver to look for.
Returns
Driver matching the name or the default driver if an empty string is passed.
References otawa::display::graphviz_driver.
Referenced by otawa::display::AbstractDrawer::AbstractDrawer().
static Driver* otawa::display::Driver::find (kind_t kind) static
otawa::display::Driver::newGraph (const PropList & defaultGraphStyle = PropList::EMPTY, const PropList & defaultNodeStyle = PropList::EMPTY, const PropList & defaultEdgeStyle = PropList::EMPTY) const pure virtual
Creates a new graph with default styles given.
Parameters
defaultGraphStyle default properties for the graph Can be changed with the methods inherited from PropList
defaultNodeStyle default properties for the nodes Can be changed with the methods inherited from PropList
defaultEdgeStyle default properties for the edges Can be changed with the methods inherited from PropList
Returns
new graph created
Implemented in otawa::display::GraphVizDriver.
Referenced by otawa::display::AbstractDrawer::AbstractDrawer(), and otawa::display::CFGDrawer::CFGDrawer().
The documentation for this class was generated from the following files:
include/otawa/display/Driver.h
src/odisplay/display_Graph.cpp