Otawa: otawa::dfa::hai::UnrollingListener< P > Class Template Reference
otawa::dfa::hai::UnrollingListener< P > Class Template Reference
This listener gathers in an array the LUB of the in-states for all analyzed basic blocks.
#include <otawa/dfa/hai/UnrollingListener.h>
Public Types
typedef P Problem
Public Member Functions
UnrollingListener (WorkSpace *_fw, Problem &_prob)
~UnrollingListener ()
void blockInterpreted (const FirstUnrollingFixPoint< UnrollingListener > *fp, BasicBlock *bb, const typename Problem::Domain &in, const typename Problem::Domain &out, CFG *cur_cfg, elm::genstruct::Vector< Edge * > *callStack) const
void fixPointReached (const FirstUnrollingFixPoint< UnrollingListener > *fp, BasicBlock *bb)
This is called whenever a loop's fixpoint is reached.
Problem & getProb ()
Public Attributes
Problem::Domain *** results
Static Public Attributes
static Identifier< typename Problem::Domain * > BB_OUT_STATE
Private Attributes
WorkSpace * fw
Problem & prob
Detailed Description
template<class P>
class otawa::dfa::hai::UnrollingListener< P >
This listener gathers in an array the LUB of the in-states for all analyzed basic blocks.
At the end of the analysis, you can access result[CFGNUMBER][BBNUMBER] to obtain the in-state of the basic block BBNUMBER of cfg CFGNUMBER. Note: The listener merges the in-states corresonding to various iterations of the same BB. If you want to differentiate individual in-states (for example, BB3 first iteration and BB3 other iterations) you have to modify the blockInterpreted() method to take into account the iteration number, which can be obtained with FirstUnrollingFixPoint::getIter() method.
Member Typedef Documentation
template<class P> typedef P otawa::dfa::hai::UnrollingListener< P >::Problem
Constructor & Destructor Documentation
template<class P> otawa::dfa::hai::UnrollingListener< P >::UnrollingListener (WorkSpace * _fw, Problem & _prob) inline
References otawa::cfgio::cfg(), otawa::CFGCollection::count(), otawa::CFG::countBB(), otawa::dfa::hai::UnrollingListener< P >::fw, otawa::CFGCollection::get(), otawa::INVOLVED_CFGS, and otawa::dfa::hai::UnrollingListener< P >::prob.
template<class P> otawa::dfa::hai::UnrollingListener< P >::~UnrollingListener () inline
References otawa::cfgio::bb(), otawa::dfa::hai::UnrollingListener< P >::blockInterpreted(), otawa::cfgio::cfg(), otawa::CFGCollection::count(), otawa::CFG::countBB(), otawa::dfa::hai::UnrollingListener< P >::fixPointReached(), otawa::dfa::hai::UnrollingListener< P >::fw, otawa::CFGCollection::get(), otawa::INVOLVED_CFGS, and otawa::dfa::hai::UnrollingListener< P >::results.
Member Function Documentation
template<class Problem > void otawa::dfa::hai::UnrollingListener< Problem >::blockInterpreted (const FirstUnrollingFixPoint< UnrollingListener< P > > * fp, BasicBlock * bb, const typename Problem::Domain & in, const typename Problem::Domain & out, CFG * cur_cfg, elm::genstruct::Vector< Edge * > * callStack) const
References otawa::dfa::hai::UnrollingListener< P >::BB_OUT_STATE, otawa::CFG::label(), otawa::CFG::number(), otawa::BasicBlock::number(), otawa::dfa::hai::UnrollingListener< P >::prob, and otawa::dfa::hai::UnrollingListener< P >::results.
Referenced by otawa::dfa::hai::UnrollingListener< P >::~UnrollingListener().
template<class Problem > void otawa::dfa::hai::UnrollingListener< P >::fixPointReached (const FirstUnrollingFixPoint< UnrollingListener< P > > * fp, BasicBlock * bb)
This is called whenever a loop's fixpoint is reached.
Parameters
fp The FixPoint object
bb The loop header.
Referenced by otawa::dfa::hai::UnrollingListener< P >::~UnrollingListener().
template<class P> Problem& otawa::dfa::hai::UnrollingListener< P >::getProb () inline
References otawa::dfa::hai::UnrollingListener< P >::prob.
Member Data Documentation
template<class P> Identifier< typename Problem::Domain * > otawa::dfa::hai::UnrollingListener< Problem >::BB_OUT_STATE static
Referenced by otawa::dfa::hai::UnrollingListener< P >::blockInterpreted().
template<class P> WorkSpace* otawa::dfa::hai::UnrollingListener< P >::fw private
Referenced by otawa::dfa::hai::UnrollingListener< P >::UnrollingListener(), and otawa::dfa::hai::UnrollingListener< P >::~UnrollingListener().
template<class P> Problem& otawa::dfa::hai::UnrollingListener< P >::prob private
Referenced by otawa::dfa::hai::UnrollingListener< P >::blockInterpreted(), otawa::dfa::hai::UnrollingListener< P >::getProb(), and otawa::dfa::hai::UnrollingListener< P >::UnrollingListener().
template<class P> Problem::Domain*** otawa::dfa::hai::UnrollingListener< P >::results
Referenced by otawa::dfa::hai::UnrollingListener< P >::blockInterpreted(), otawa::ACSMayBuilder::processLBlockSet(), otawa::ACSBuilder::processLBlockSet(), otawa::dcache::ACSMayBuilder::processLBlockSet(), otawa::dcache::ACSBuilder::processLBlockSet(), otawa::branch::BranchBuilder::processWorkSpace(), and otawa::dfa::hai::UnrollingListener< P >::~UnrollingListener().
The documentation for this class was generated from the following files:
include/otawa/dfa/hai/UnrollingListener.h
src/prog/dfa_hai_UnrollingListener.cpp