Otawa: otawa::Edge Class Reference
otawa::Edge Class Reference
This class represents edges in the CFG representation.
#include <otawa/cfg/Edge.h>
Public Types
enum kind_t {
NONE = 0, TAKEN = 1, NOT_TAKEN = 2, CALL = 3,
VIRTUAL = 4, VIRTUAL_CALL = 5, VIRTUAL_RETURN = 6, EXN_CALL = 7,
EXN_RETURN = 8
}
Kind of the edge.
typedef enum otawa::Edge::kind_t kind_t
Public Member Functions
Edge (BasicBlock *source, BasicBlock *target, kind_t kind=TAKEN)
Build a new edge.
~Edge (void)
Delete an edge.
BasicBlock * source (void) const
BasicBlock * target (void) const
kind_t kind (void) const
CFG * calledCFG (void) const
Property * getProp (const AbstractIdentifier *id) const
Find a property by its identifier.
void setProp (Property *prop)
Set the property in the property list removing any double.
void setProp (const AbstractIdentifier *id)
void removeProp (const AbstractIdentifier *id)
Remove a property matching the given identifier.
void removeProp (const AbstractIdentifier &id)
Property * extractProp (const AbstractIdentifier *id)
Remove a property matching the given identifier and return it.
Property * extractProp (const AbstractIdentifier &id)
Remove a property matching the given identifier and return it.
void addProp (Property *prop)
Add property to the list without checking of duplication.
void removeAllProp (const AbstractIdentifier *id)
Remove all the properties matching the given identifier.
bool hasProp (const AbstractIdentifier &id) const
Test if the property list contains a property matching the given identifier.
void clearProps (void)
Remove all properties from the list.
void addProps (const PropList &props)
Add all properties from the given property list, in a reverse order.
void print (elm::io::Output &out) const
Display the current property list.
Static Public Member Functions
static cstring kindName (kind_t kind)
Get the name of a kind.
Static Public Attributes
static const PropList EMPTY
This is an empty proplist for convenience.
Private Member Functions
void toCall (void)
Transform this edge as a call edge.
Private Attributes
kind_t knd
BasicBlock * src
BasicBlock * tgt
Friends
class CFG
Detailed Description
This class represents edges in the CFG representation.
They allow hooking annotations.
Member Typedef Documentation
typedef enum otawa::Edge::kind_t otawa::Edge::kind_t
Member Enumeration Documentation
enum otawa::Edge::kind_t
Kind of the edge.
Enumerator
NONE
No meaning.
For syntactic use only.
TAKEN
Kind of an edge matching a branch instruction.
NOT_TAKEN
Kind of an edge matching the natural sequential control flow between a basic block and its successor.
CALL
Kind of an edge matching a sub-program call.
Edges of this kind provides a calledCFG() value.
VIRTUAL
Kind of an edge linking the virtual entry and exit basic blocks with other ones of the CFG.
Does not match any instruction in the sub-program.
VIRTUAL_CALL
Edges of this kind are only found in a virtual CFG.
They replace CALL edges whose CFG has been embedded.
VIRTUAL_RETURN
Edges of this kind are only found in a virtual CFG.
When a subprogram call is embedded in the main CFG, they link the last basic block of the called subprogram with the basic block successors of the calling basic block.
EXN_CALL
Edges of this kind are usually added after an analysis of the CFG to denote raise of exception (system call, error, etc).
The body of the exception handler is linked with an edge of type EXN_CALL while the return is linked with an edge of type EXN_RETURN.
EXN_RETURN
Constructor & Destructor Documentation
otawa::Edge::Edge (BasicBlock * source, BasicBlock * target, kind_t kind = TAKEN)
Build a new edge.
References otawa::BasicBlock::addInEdge(), otawa::BasicBlock::addOutEdge(), CALL, otawa::BasicBlock::cfg(), EDGE_Null, src, and tgt.
otawa::Edge::~Edge (void)
Delete an edge.
References CALL, knd, otawa::BasicBlock::removeInEdge(), otawa::BasicBlock::removeOutEdge(), src, and tgt.
Member Function Documentation
void otawa::PropList::addProp (Property * prop) inherited
Add property to the list without checking of duplication.
Parameters
prop Property to add.
References otawa::Property::_next.
Referenced by otawa::Identifier< T >::add(), otawa::ast::ASTInfo::ASTInfo(), otawa::Identifier< otawa::arm::Info * >::copy(), otawa::AbstractIdentifier::initProps(), otawa::ContextualProperty::make(), otawa::script::Script::makeConfig(), otawa::ccg::Builder::processLBlockSet(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), and otawa::ContextualProperty::refProps().
void otawa::PropList::addProps (const PropList & props) inherited
Add all properties from the given property list, in a reverse order.
Parameters
props Property list to clone.
References otawa::Property::copy(), otawa::PropList::head, and otawa::Property::next().
Referenced by otawa::display::CFGDrawer::CFGDrawer(), otawa::display::GraphVizGraph::GraphVizGraph(), otawa::ParamFeature::instantiate(), otawa::Manager::loadXML(), otawa::display::GraphVizGraph::newEdge(), otawa::display::GraphVizGraph::newNode(), otawa::Process::Process(), otawa::display::GraphVizItem::setProps(), otawa::VirtualBasicBlock::VirtualBasicBlock(), and otawa::VirtualCFG::VirtualCFG().
CFG* otawa::Edge::calledCFG (void) const inline
References CALL, otawa::ENTRY, knd, and tgt.
Referenced by otawa::DelayedBuilder::cloneEdge(), otawa::DelayedBuilder::insert(), kindName(), otawa::ipet::VarAssignment::makeEdgeVar(), otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing(), otawa::etime::EdgeTimeBuilder::processEdge(), and otawa::Virtualizer::virtualize().
void otawa::PropList::clearProps (void) inherited
Remove all properties from the list.
References otawa::Property::next().
Referenced by otawa::PSTBuilder::getVCFG(), otawa::display::GraphVizItem::setProps(), and otawa::WorkSpace::~WorkSpace().
Property * otawa::PropList::extractProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::script::Script::makeConfig().
Property * otawa::PropList::extractProp (const AbstractIdentifier & id) inline inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::PropList::extractProp().
Referenced by otawa::PropList::extractProp().
Property * otawa::PropList::getProp (const AbstractIdentifier * id) const inherited
Find a property by its identifier.
Parameters
id Identifier of the property to find.
Returns
Found property or null.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::Identifier< otawa::arm::Info * >::exists(), otawa::ContextualProperty::exists(), otawa::ContextualProperty::find(), otawa::Identifier< T >::get(), otawa::ContextualProperty::make(), otawa::ParamFeature::matches(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::print(), otawa::ContextualProperty::print(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), otawa::ContextualProperty::refProps(), otawa::Identifier< T >::set(), otawa::Identifier< T >::use(), and otawa::Identifier< T >::value().
bool otawa::PropList::hasProp (const AbstractIdentifier & id) const inline inherited
Test if the property list contains a property matching the given identifier.
Parameters
id Property identifier to look for.
Returns
True if the list contains the matching property, false else.
References otawa::p::print().
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::Monitor::configure(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::exists(), and otawa::Manager::setVerbosity().
kind_t otawa::Edge::kind (void) const inline
References knd.
Referenced by otawa::DelayedBuilder::cloneEdge(), otawa::DelayedBuilder::fix(), otawa::display::CFGOutput::genEdgeLabel(), otawa::DelayedBuilder::insert(), kindName(), otawa::ipet::VarAssignment::makeEdgeVar(), otawa::display::CFGDrawer::onEdge(), otawa::clp::operator<<(), otawa::BBStatCollector::processCFG(), otawa::ContextualProcessor::processCFG(), and otawa::etime::EdgeTimeBuilder::processEdge().
cstring otawa::Edge::kindName (kind_t kind) static
Get the name of a kind.
Parameters
kind Kind to get name of.
Returns
Kind name.
References CALL, calledCFG(), otawa::cfgio::edge(), kind(), otawa::CFG::label(), otawa::PropList::print(), source(), and target().
Referenced by otawa::cfgio::Output::processBB(), and otawa::CFGSaver::processBB().
void otawa::PropList::print (elm::io::Output & out) const inherited
Display the current property list.
Parameters
out Output to use.
Referenced by kindName(), otawa::operator<<(), and otawa::ContextualProperty::print().
void otawa::PropList::removeAllProp (const AbstractIdentifier * id) inherited
Remove all the properties matching the given identifier.
Parameters
id Identifier of properties to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::LoopUnroller::unroll().
void otawa::PropList::removeProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier.
Parameters
id Identifier of the property to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::PSTBuilder::buildTree(), otawa::BBRemover< T >::clean(), otawa::CFGBuilder::cleanup(), otawa::display::CFGOutput::processCFG(), otawa::SubCFGBuilder::processWorkSpace(), otawa::Identifier< otawa::arm::Info * >::remove(), and otawa::ContextualPath::Ref< T >::remove().
void otawa::PropList::removeProp (const AbstractIdentifier & id) inline inherited
References otawa::PropList::removeProp().
Referenced by otawa::PropList::removeProp().
void otawa::PropList::setProp (Property * prop) inherited
Set the property in the property list removing any double.
Parameters
prop Property to set.
References otawa::Property::_next, otawa::Property::id(), and otawa::Property::next().
void otawa::PropList::setProp (const AbstractIdentifier * id) inline inherited
References otawa::PropList::setProp().
Referenced by otawa::PropList::setProp().
BasicBlock* otawa::Edge::source (void) const inline
References src.
Referenced by otawa::ContextualProcessor::avoidingRecursive(), otawa::ContextualProcessor::enteringCall(), otawa::DelayedBuilder::fix(), otawa::PSTBuilder::getVCFG(), otawa::DelayedBuilder::insert(), otawa::dfa::hai::HalfAbsInt< FixPoint >::isEdgeDone(), kindName(), otawa::ipet::VarAssignment::makeEdgeVar(), otawa::clp::operator<<(), otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing(), otawa::BBStatCollector::processCFG(), otawa::ContextualProcessor::processCFG(), otawa::etime::EdgeTimeBuilder::processEdge(), otawa::BackwardCFGAdapter::sinkOf(), otawa::ForwardCFGAdapter::sourceOf(), and otawa::ai::CFGGraph::sourceOf().
BasicBlock* otawa::Edge::target (void) const inline
References tgt.
Referenced by otawa::etime::EdgeTimeBuilder::applyWeightedSplit(), otawa::ContextualProcessor::avoidingRecursive(), otawa::DelayedBuilder::cloneEdge(), otawa::ContextualProcessor::enteringCall(), otawa::PSTBuilder::getVCFG(), otawa::DelayedBuilder::insert(), otawa::Dominance::isBackEdge(), otawa::dfa::hai::HalfAbsInt< FixPoint >::isEdgeDone(), kindName(), otawa::ContextualProcessor::leavingCall(), otawa::ipet::VarAssignment::makeEdgeVar(), otawa::clp::operator<<(), otawa::BBStatCollector::processCFG(), otawa::ContextualProcessor::processCFG(), otawa::etime::EdgeTimeBuilder::processEdge(), otawa::LoopReductor::processWorkSpace(), otawa::ForwardCFGAdapter::sinkOf(), otawa::ai::CFGGraph::sinkOf(), and otawa::BackwardCFGAdapter::sourceOf().
void otawa::Edge::toCall (void) private
Transform this edge as a call edge.
References CALL, otawa::BasicBlock::FLAG_Call, otawa::BasicBlock::flags, knd, otawa::BasicBlock::removeInEdge(), src, and tgt.
Referenced by otawa::CFG::scan().
Friends And Related Function Documentation
friend class CFG friend
Member Data Documentation
const PropList otawa::PropList::EMPTY static inherited
This is an empty proplist for convenience.
Referenced by otawa::DynProcessor::configure(), otawa::ActualFeature::processor(), otawa::SilentFeature::SilentFeature(), otawa::Processor::version(), and otawa::display::Driver::~Driver().
kind_t otawa::Edge::knd private
Referenced by calledCFG(), kind(), toCall(), and ~Edge().
BasicBlock* otawa::Edge::src private
Referenced by Edge(), source(), toCall(), and ~Edge().
BasicBlock * otawa::Edge::tgt private
Referenced by calledCFG(), Edge(), target(), toCall(), and ~Edge().
The documentation for this class was generated from the following files:
include/otawa/cfg/Edge.h
src/prog/Edge.cpp