Otawa: otawa::ExeInst< N > Class Template Reference
otawa::ExeInst< N > Class Template Reference
An instruction represented in an ExeGraph.
#include <>>
Classes
class NodeIterator
Iterator on the list of nodes related to the instruction.
Public Member Functions
ExeInst (Inst *inst, BasicBlock *bb, typename ExeGraph< N >::code_part_t part, int index)
Constructor.
Inst * inst ()
ExeGraph< N >::code_part_t codePart ()
int index ()
void setIndex (int index)
Sets the instruction index.
void addNode (N *node)
Adds a node to the list of nodes related to this instruction.
void deleteNodes ()
Clears the list of nodes related to this instruction.
N * firstNode ()
N * lastNode ()
BasicBlock * basicBlock ()
Private Attributes
Inst * _inst
BasicBlock * _bb
int _index
ExeGraph< N >::code_part_t _part
elm::genstruct::DLList< N * > _nodes
Detailed Description
template<class N>
class otawa::ExeInst< N >
An instruction represented in an ExeGraph.
Parameters
Type of execution graph nodes.
Constructor & Destructor Documentation
template<class N> otawa::ExeInst< N >::ExeInst (Inst * inst, BasicBlock * bb, typename ExeGraph< N >::code_part_t part, int index) inline
Constructor.
Parameters
inst The instruction in the CFG.
bb The basic block it belongs to.
part The part (BEFORE_PROLOGUE, PROLOGUE, BODY, EPILOGUE) it belongs to.
index The index of the instruction in the execution graph.
Member Function Documentation
template<class N> void otawa::ExeInst< N >::addNode (N * node) inline
Adds a node to the list of nodes related to this instruction.
Parameters
node The node to add to the list of nodes related to the instruction.
template<class N> BasicBlock * otawa::ExeInst< N >::basicBlock (void) inline
Returns
Basic block that contains the instruction.
template<class N> ExeGraph< N >::code_part_t otawa::ExeInst< N >::codePart (void) inline
Returns
Code part (BEFORE_PROLOGUE, PROLOGUE, BODY or EPILOGUE).
Referenced by otawa::LiExeNode::LiExeNode().
template<class N> void otawa::ExeInst< N >::deleteNodes (void) inline
Clears the list of nodes related to this instruction.
template<class N> N * otawa::ExeInst< N >::firstNode (void) inline
Returns
First execution node related to the instruction.
template<class N> int otawa::ExeInst< N >::index (void) inline
Returns
Index of the instruction.
Referenced by otawa::ExeGraph< N >::build(), otawa::ExeGraph< N >::ExeNode::ExeNode(), otawa::ParamExeGraph::initDelays(), and otawa::ExeInst< otawa::ParamExeNode >::setIndex().
template<class N> Inst * otawa::ExeInst< N >::inst (void) inline
Returns
Instruction in the CFG.
Referenced by otawa::ExeGraph< N >::build().
template<class N> N * otawa::ExeInst< N >::lastNode (void) inline
Returns
Last execution node related to the instruction.
template<class N> void otawa::ExeInst< N >::setIndex (int index) inline
Sets the instruction index.
Parameters
index New instruction index.
Member Data Documentation
template<class N> BasicBlock* otawa::ExeInst< N >::_bb private
Referenced by otawa::ExeInst< otawa::ParamExeNode >::basicBlock().
template<class N> int otawa::ExeInst< N >::_index private
Referenced by otawa::ExeInst< otawa::ParamExeNode >::index().
template<class N> Inst* otawa::ExeInst< N >::_inst private
Referenced by otawa::ExeInst< otawa::ParamExeNode >::inst(), and otawa::ExeGraph< N >::ExeNode::inst().
template<class N> elm::genstruct::DLList<N *> otawa::ExeInst< N >::_nodes private
template<class N> ExeGraph<N>::code_part_t otawa::ExeInst< N >::_part private
Referenced by otawa::ExeInst< otawa::ParamExeNode >::codePart().
The documentation for this class was generated from the following files:
include/otawa/exegraph/ExeGraph.h
src/prog/exegraph_ExeGraph.cpp