Otawa: otawa::dfa::hai::DefaultFixPoint< Listener > Class Template Reference
otawa::dfa::hai::DefaultFixPoint< Listener > Class Template Reference
#include <otawa/dfa/hai/DefaultFixPoint.h>
Classes
class FixPointState
Public Types
typedef Listener::Problem Problem
typedef Problem::Domain Domain
Public Member Functions
DefaultFixPoint (Listener &_list)
~DefaultFixPoint ()
FixPointState * newState (void)
void init (HalfAbsInt< DefaultFixPoint > *_ai)
Is called by HalfAbsInt for fixpoint object initializeation.
void fixPoint (BasicBlock *bb, bool &fixpoint, Domain &in, bool firstTime) const
Main fixPoint function: is called by HalfAbsInt whenever the analysis reaches a loop header.
void markEdge (PropList *e, const Domain &s)
Marks a proplist (typically an edge) e with state s.
void unmarkEdge (PropList *e)
Unmark a proplist (typically an edge)
void updateEdge (Edge *edge, Domain &dom)
Domain * getMark (PropList *e)
Get the mark of a proplist (typically an edge)
const Domain & bottom (void) const
This function gets the bottom of the problem's lattice This is usually delegated to the Problem.
const Domain & entry (void) const
This function returns the entry state of the whole program to be analyzed.
void lub (Domain &a, const Domain &b) const
Performs operation: a = a lub b This is delegated to the Problem.
void assign (Domain &a, const Domain &b) const
Performs operation a = b This is delegated to the Problem.
bool equals (const Domain &a, const Domain &b) const
Tests a and b for equality.
void update (Domain &out, const Domain &in, BasicBlock *bb)
Is called whenever the analysis needs to get the Output state for a basic block, given its input state.
void blockInterpreted (BasicBlock *bb, const Domain &in, const Domain &out, CFG *cur_cfg, elm::genstruct::Vector< Edge * > *callStack) const
This listener is called whenever HalfAbsInt has processed a basic block.
void fixPointReached (BasicBlock *bb) const
This listener is called whenever a fixpoint is reached for a loop.
void enterContext (Domain &dom, BasicBlock *bb, hai_context_t ctx) const
This is called whenever we enter a loop.
void leaveContext (Domain &dom, BasicBlock *bb, hai_context_t ctx) const
This is called whenever we leave a loop.
Private Attributes
Problem & prob
Listener & list
HalfAbsInt< DefaultFixPoint > * ai
Static Private Attributes
static Identifier< Domain * > STATE
Member Typedef Documentation
template<class Listener> typedef Problem::Domain otawa::dfa::hai::DefaultFixPoint< Listener >::Domain
template<class Listener> typedef Listener::Problem otawa::dfa::hai::DefaultFixPoint< Listener >::Problem
Constructor & Destructor Documentation
template<class Listener> otawa::dfa::hai::DefaultFixPoint< Listener >::DefaultFixPoint (Listener & _list) inline
template<class Listener> otawa::dfa::hai::DefaultFixPoint< Listener >::~DefaultFixPoint () inline
Member Function Documentation
template<class Listener> void otawa::dfa::hai::DefaultFixPoint< Listener >::assign (Domain & a, const Domain & b) const inline
Performs operation a = b This is delegated to the Problem.
Parameters
a State a
b State b
References otawa::dfa::hai::DefaultFixPoint< Listener >::prob.
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::fixPoint(), and otawa::dfa::hai::DefaultFixPoint< Listener >::newState().
template<class Listener> void otawa::dfa::hai::DefaultFixPoint< Listener >::blockInterpreted (BasicBlock * bb, const Domain & in, const Domain & out, CFG * cur_cfg, elm::genstruct::Vector< Edge * > * callStack) const inline
This listener is called whenever HalfAbsInt has processed a basic block.
The listener must gather and store the information for the user. This is delegated to the Listener.
Parameters
bb The basic block
in The input state
out The output state
cur_cfg Current CFG.
References otawa::dfa::hai::DefaultFixPoint< Listener >::list.
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::newState().
template<class Listener > const Domain & otawa::dfa::hai::DefaultFixPoint< Listener >::bottom (void) const inline
This function gets the bottom of the problem's lattice This is usually delegated to the Problem.
Returns
Bottom
References otawa::dfa::hai::DefaultFixPoint< Listener >::prob.
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::fixPoint(), otawa::dfa::hai::DefaultFixPoint< Listener >::markEdge(), and otawa::dfa::hai::DefaultFixPoint< Listener >::newState().
template<class Listener > void otawa::dfa::hai::DefaultFixPoint< Listener >::enterContext (Domain & dom, BasicBlock * bb, hai_context_t ctx) const inline
This is called whenever we enter a loop.
Parameters
dom State (optionnally to be modified according to the new context)
bb Loop header
References otawa::dfa::hai::DefaultFixPoint< Listener >::prob.
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::newState().
template<class Listener > const Domain & otawa::dfa::hai::DefaultFixPoint< Listener >::entry (void) const inline
This function returns the entry state of the whole program to be analyzed.
This is usually delegated to the Problem.
Returns
Entry state
References otawa::dfa::hai::DefaultFixPoint< Listener >::prob.
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::newState().
template<class Listener> bool otawa::dfa::hai::DefaultFixPoint< Listener >::equals (const Domain & a, const Domain & b) const inline
Tests a and b for equality.
This is delegated to the Problem.
Parameters
a State a
b State b
Returns
True if equal
References otawa::dfa::hai::DefaultFixPoint< Listener >::prob.
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::newState().
template<class Listener > void otawa::dfa::hai::DefaultFixPoint< Listener >::fixPoint (BasicBlock * bb, bool & fixpoint, Domain & in, bool firstTime) const
Main fixPoint function: is called by HalfAbsInt whenever the analysis reaches a loop header.
Its purpose is to detect if the fixpoint's reached, and compute the new loop entry state. It may store state information into the HalfAbsInt's FixPointState object.
Parameters
bb loop header basic block
fixpoint fixPoint() must store True here when the fixpoint is reached.
in fixPoint() must store here the new loop entry state.
fistTime is True if it's the first time we call fixPoint for this loop.
References otawa::dfa::hai::DefaultFixPoint< Listener >::ai, otawa::dfa::hai::DefaultFixPoint< Listener >::assign(), otawa::dfa::hai::DefaultFixPoint< Listener >::bottom(), otawa::dfa::hai::DefaultFixPoint< Listener >::FixPointState::headerState, and otawa::dfa::hai::DefaultFixPoint< Listener >::prob.
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::newState().
template<class Listener > void otawa::dfa::hai::DefaultFixPoint< Listener >::fixPointReached (BasicBlock * bb) const inline
This listener is called whenever a fixpoint is reached for a loop.
This is delegated to the Listener.
Parameters
bb The loop header.
References otawa::dfa::hai::DefaultFixPoint< Listener >::list.
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::newState().
template<class Listener > Domain * otawa::dfa::hai::DefaultFixPoint< Listener >::getMark (PropList * e) inline
Get the mark of a proplist (typically an edge)
Parameters
e The proplist to getmark
References otawa::dfa::hai::DefaultFixPoint< Listener >::STATE.
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::newState().
template<class Listener > void otawa::dfa::hai::DefaultFixPoint< Listener >::init (util::HalfAbsInt< DefaultFixPoint< Listener > > * _ai) inline
Is called by HalfAbsInt for fixpoint object initializeation.
Parameters
_ai HalfAbsint object.
References otawa::dfa::hai::DefaultFixPoint< Listener >::ai.
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::newState().
template<class Listener > void otawa::dfa::hai::DefaultFixPoint< Listener >::leaveContext (Domain & dom, BasicBlock * bb, hai_context_t ctx) const inline
This is called whenever we leave a loop.
Parameters
dom State (optionally to be modified according to the new context)
bb Loop header
References otawa::dfa::hai::DefaultFixPoint< Listener >::prob.
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::newState().
template<class Listener> void otawa::dfa::hai::DefaultFixPoint< Listener >::lub (Domain & a, const Domain & b) const inline
Performs operation: a = a lub b This is delegated to the Problem.
with lub = Lowest Upper Bound.
Parameters
a State a
b State b
References otawa::dfa::hai::DefaultFixPoint< Listener >::prob.
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::newState().
template<class Listener > void otawa::dfa::hai::DefaultFixPoint< Listener >::markEdge (PropList * e, const Domain & s) inline
Marks a proplist (typically an edge) e with state s.
Parameters
e Proplist to mark
s State
References otawa::dfa::hai::DefaultFixPoint< Listener >::bottom(), otawa::dfa::hai::DefaultFixPoint< Listener >::prob, and otawa::dfa::hai::DefaultFixPoint< Listener >::STATE.
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::newState().
template<class Listener> FixPointState* otawa::dfa::hai::DefaultFixPoint< Listener >::newState (void) inline
References otawa::dfa::hai::DefaultFixPoint< Listener >::assign(), otawa::cfgio::bb(), otawa::dfa::hai::DefaultFixPoint< Listener >::blockInterpreted(), otawa::dfa::hai::DefaultFixPoint< Listener >::bottom(), otawa::cfgio::edge(), otawa::dfa::hai::DefaultFixPoint< Listener >::enterContext(), otawa::dfa::hai::DefaultFixPoint< Listener >::entry(), otawa::dfa::hai::DefaultFixPoint< Listener >::equals(), otawa::dfa::hai::DefaultFixPoint< Listener >::fixPoint(), otawa::dfa::hai::DefaultFixPoint< Listener >::fixPointReached(), otawa::dfa::hai::DefaultFixPoint< Listener >::FixPointState::FixPointState(), otawa::dfa::hai::DefaultFixPoint< Listener >::getMark(), otawa::dfa::hai::DefaultFixPoint< Listener >::init(), otawa::dfa::hai::DefaultFixPoint< Listener >::leaveContext(), otawa::dfa::hai::DefaultFixPoint< Listener >::lub(), otawa::dfa::hai::DefaultFixPoint< Listener >::markEdge(), otawa::dfa::hai::DefaultFixPoint< Listener >::STATE, otawa::dfa::hai::DefaultFixPoint< Listener >::unmarkEdge(), otawa::dfa::hai::DefaultFixPoint< Listener >::update(), and otawa::dfa::hai::DefaultFixPoint< Listener >::updateEdge().
template<class Listener > void otawa::dfa::hai::DefaultFixPoint< Listener >::unmarkEdge (PropList * e) inline
Unmark a proplist (typically an edge)
Parameters
e Proplist to unmark
References otawa::dfa::hai::DefaultFixPoint< Listener >::STATE.
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::newState().
template<class Listener> void otawa::dfa::hai::DefaultFixPoint< Listener >::update (Domain & out, const Domain & in, BasicBlock * bb) inline
Is called whenever the analysis needs to get the Output state for a basic block, given its input state.
This is delegated to the Problem.
Parameters
out Output state
in Input state
bb Basic Block
References otawa::dfa::hai::DefaultFixPoint< Listener >::prob.
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::newState().
template<class Listener > void otawa::dfa::hai::DefaultFixPoint< Listener >::updateEdge (Edge * edge, Domain & dom) inline
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::newState().
Member Data Documentation
template<class Listener> HalfAbsInt<DefaultFixPoint>* otawa::dfa::hai::DefaultFixPoint< Listener >::ai private
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::fixPoint(), and otawa::dfa::hai::DefaultFixPoint< Listener >::init().
template<class Listener> Listener& otawa::dfa::hai::DefaultFixPoint< Listener >::list private
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::blockInterpreted(), and otawa::dfa::hai::DefaultFixPoint< Listener >::fixPointReached().
template<class Listener> Problem& otawa::dfa::hai::DefaultFixPoint< Listener >::prob private
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::assign(), otawa::dfa::hai::DefaultFixPoint< Listener >::bottom(), otawa::dfa::hai::DefaultFixPoint< Listener >::enterContext(), otawa::dfa::hai::DefaultFixPoint< Listener >::entry(), otawa::dfa::hai::DefaultFixPoint< Listener >::equals(), otawa::dfa::hai::DefaultFixPoint< Listener >::fixPoint(), otawa::dfa::hai::DefaultFixPoint< Listener >::leaveContext(), otawa::dfa::hai::DefaultFixPoint< Listener >::lub(), otawa::dfa::hai::DefaultFixPoint< Listener >::markEdge(), and otawa::dfa::hai::DefaultFixPoint< Listener >::update().
template<class Listener> Identifier< typename Listener::Problem::Domain * > otawa::dfa::hai::DefaultFixPoint< Listener >::STATE static private
Referenced by otawa::dfa::hai::DefaultFixPoint< Listener >::getMark(), otawa::dfa::hai::DefaultFixPoint< Listener >::markEdge(), otawa::dfa::hai::DefaultFixPoint< Listener >::newState(), and otawa::dfa::hai::DefaultFixPoint< Listener >::unmarkEdge().
The documentation for this class was generated from the following files:
include/otawa/dfa/hai/DefaultFixPoint.h
src/prog/dfa_hai_DefaultFixPoint.cpp