Otawa: otawa::hard::Cache Class Reference
otawa::hard::Cache Class Reference
Platform Description
This class contains the configuration of a level of cache of processor.
#include <otawa/hard/Cache.h>
Classes
struct info_t
Public Types
enum replace_policy_t {
NONE = 0, OTHER = 1, LRU = 2, RANDOM = 3,
FIFO = 4, PLRU = 5
}
enum write_policy_t { WRITE_THROUGH = 0, WRITE_BACK = 1 }
typedef enum otawa::hard::Cache::replace_policy_t replace_policy_t
typedef enum otawa::hard::Cache::write_policy_t write_policity_t
typedef struct otawa::hard::Cache::info_t info_t
typedef t::uint32 block_t
typedef t::uint32 set_t
typedef t::uint32 tag_t
typedef t::uint32 offset_t
Public Member Functions
Cache (void)
Cache (const Cache &cache, const Cache *next=0)
Build a cache by cloning an existing cache and setting it in new cache configuration.
virtual ~Cache (void)
const Cache * nextLevel (void) const
Get the next level of cache.
ot::size cacheSize (void) const
Get the cache size.
ot::size blockSize (void) const
Get the block size.
int wayCount (void) const
Get the count of ways for associatives caches.
int setCount (void) const
int blockCount (void) const
replace_policy_t replacementPolicy (void) const
Get the replacement policy.
write_policy_t writePolicy (void) const
Get the write policy.
bool doesWriteAllocate (void) const
Set the behaviour about write allocation.
int missPenalty (void) const
Return the time penaly of a missed access to memory.
int writeBufferSize (void) const
Get the write buffer size of this cache (0 for no write buffer).
int readPortSize (void) const
Get the read port size of this cache (default to 1, must be non-null).
int writePortSize (void) const
Get the write port size of this cache (default to 1 for data cache).
int blockBits (void) const
Required bits count for a byte address in the block.
int setBits (void) const
int tagBits (void) const
Required bits count in the tag part of the address.
int wayBits (void) const
Get the number of bits to count the ways in set associative cache.
ot::mask blockMask (void) const
Mask for selecting the address of a byte in a block in a memory address.
ot::mask setMask (void) const
ot::mask tagMask (void) const
Mask for selecting the tag in a memory address.
offset_t offset (Address addr) const
Compute the offset of the accessed byte in the block from the memory address.
set_t set (Address addr) const
tag_t tag (Address addr) const
Compute the tag from the memory address.
block_t block (Address addr) const
Return the bits used for identifying uniquely a block, that is, tag and line number.
Address round (Address addr) const
Round the given address to the address of the container cache block.
void setAccessTime (int access_time)
Set the access time.
void setMissPenalty (int miss_penalty)
Set the miss penaly time.
void setBlockBits (int block_bits)
void setRowBits (int set_bits)
Set the row count as a number of bits.
void setWayBits (int way_bits)
Set the way count as a number of bits.
void setReplacePolicy (replace_policy_t replace)
Set the replace policy of the cache.
void setWritePolicy (write_policy_t write)
Set the write policy of the cache.
void setAllocate (bool allocate)
Set the allocation state.
void setWriteBufferSize (int write_buffer_size)
Set the write buffer size (0 for no write buffer).
void setReadPortSize (int read_port_size)
Set the read port size (at least 1).
void setWritePortSize (int write_port_size)
Set the write port size (at least 1).
int rowBits (void) const
Required bits count for a row index.
ot::mask lineMask (void) const
Mask for selecting the line number in a memory address.
ot::mask rowMask (void) const
ot::mask line (const Address &addr) const
Compute the line number from the memory address.
int rowCount (void) const
Get the count of rows.
Private Member Functions
SERIALIZABLE (Cache, field("access_time", _info.access_time, 1)&field("miss_penalty", _info.miss_penalty, 10)&field("block_bits", _info.block_bits, 4)&field("row_bits", _info.row_bits, 12)&field("way_bits", _info.way_bits, 0)&field("allocate", _info.allocate, false)&field("next", _next,(const Cache *) 0)&field("replace", _info.replace, LRU)&field("write_buffer_size", _info.write_buffer_size, 0)&field("read_port_size", _info.read_port_size, 1)&field("write_port_size", _info.write_port_size, 1)&field("write", _info.write, WRITE_THROUGH))
Private Attributes
info_t _info
const Cache * _next
Detailed Description
This class contains the configuration of a level of cache of processor.
It may represents direct-mapped or associative cache (with any associatvity level) using bits as block/line boundaries. Supported management policies (when they apply) are only LRU, FIFO, RANDOM and PLRU. Once built, a cache object is viewed as a read-only database.
Member Typedef Documentation
typedef t::uint32 otawa::hard::Cache::block_t
typedef struct otawa::hard::Cache::info_t otawa::hard::Cache::info_t
typedef t::uint32 otawa::hard::Cache::offset_t
typedef enum otawa::hard::Cache::replace_policy_t otawa::hard::Cache::replace_policy_t
typedef t::uint32 otawa::hard::Cache::set_t
typedef t::uint32 otawa::hard::Cache::tag_t
typedef enum otawa::hard::Cache::write_policy_t otawa::hard::Cache::write_policity_t
Member Enumeration Documentation
enum otawa::hard::Cache::replace_policy_t
Enumerator
NONE
OTHER
LRU
RANDOM
FIFO
PLRU
enum otawa::hard::Cache::write_policy_t
Enumerator
WRITE_THROUGH
WRITE_BACK
Constructor & Destructor Documentation
otawa::hard::Cache::Cache (void)
otawa::hard::Cache::Cache (const Cache & cache, const Cache * next = 0)
Build a cache by cloning an existing cache and setting it in new cache configuration.
Parameters
next Next level of cache (null if there is no more cache).
otawa::hard::Cache::~Cache (void) virtual
Member Function Documentation
mask_t otawa::hard::Cache::block (Address addr) const inline
Return the bits used for identifying uniquely a block, that is, tag and line number.
Parameters
addr Address to take block from.
Returns
Block part of the address.
References blockBits(), and otawa::Address::offset().
Referenced by otawa::ccg::LBlockBuilder::addLBlock(), otawa::LBlockBuilder::addLBlock(), otawa::dcache::CLPBlockBuilder::processBB(), and otawa::ccg::Builder::processLBlockSet().
int otawa::hard::Cache::blockBits (void) const inline
Required bits count for a byte address in the block.
Returns
Byte address bits in block.
References otawa::hard::Cache::info_t::block_bits.
Referenced by block(), blockSize(), cacheSize(), line(), lineMask(), otawa::ipet::TrivialInstCacheManager::processBB(), otawa::ccg::LBlockBuilder::processBB(), otawa::LBlockBuilder::processBB(), otawa::cat::CATBuilder::processLBlockSet(), otawa::ccg::ConstraintBuilder::processLBlockSet(), rowMask(), set(), setMask(), tag(), and tagBits().
int otawa::hard::Cache::blockCount (void) const inline
References otawa::hard::Cache::info_t::row_bits, and otawa::hard::Cache::info_t::way_bits.
mask_t otawa::hard::Cache::blockMask (void) const inline
Mask for selecting the address of a byte in a block in a memory address.
Returns
Byte address mask in the block.
References blockSize().
Referenced by otawa::ccg::LBlockBuilder::addLBlock(), otawa::LBlockBuilder::addLBlock(), offset(), otawa::ccg::LBlockBuilder::processBB(), otawa::LBlockBuilder::processBB(), otawa::dcache::BlockBuilder::processBB(), and tagMask().
size_t otawa::hard::Cache::blockSize (void) const inline
Get the block size.
Returns
Block size in bytes.
References blockBits().
Referenced by blockMask(), otawa::ets::ACSComputation::initialization(), otawa::ParExeGraph::ParExeGraph(), otawa::dcache::CLPBlockBuilder::processBB(), and round().
size_t otawa::hard::Cache::cacheSize (void) const inline
Get the cache size.
Returns
Cache size in bytes.
References blockBits(), rowBits(), and wayBits().
Referenced by otawa::dcache::BlockBuilder::processBB().
bool otawa::hard::Cache::doesWriteAllocate (void) const inline
Set the behaviour about write allocation.
Returns
Write-allocate if true, No-write-allocate else.
References otawa::hard::Cache::info_t::allocate.
mask_t otawa::hard::Cache::line (const Address & addr) const inline
Compute the line number from the memory address.
Parameters
addr Memory address to compute from.
Returns
Line number.
References blockBits(), lineMask(), and otawa::Address::offset().
Referenced by otawa::sim::AbstractCacheDriver::access(), otawa::ets::ACSComputation::initialization(), otawa::dcache::BlockBuilder::processBB(), and otawa::FirstLastBuilder::processCFG().
mask_t otawa::hard::Cache::lineMask (void) const inline
Mask for selecting the line number in a memory address.
Returns
Line number bits.
References blockBits(), and rowCount().
Referenced by line(), set(), and tagMask().
int otawa::hard::Cache::missPenalty (void) const inline
Return the time penaly of a missed access to memory.
Returns
Mise penalty in cycles.
References otawa::hard::Cache::info_t::miss_penalty.
Referenced by otawa::ipet::TrivialInstCacheManager::processBB(), otawa::cat::CATConstraintBuilder::processLBlockSet(), otawa::ccg::ConstraintBuilder::processLBlockSet(), otawa::EdgeCAT2ConstraintBuilder::processWorkSpace(), and otawa::CAT2ConstraintBuilder::processWorkSpace().
Cache * otawa::hard::Cache::nextLevel (void) const inline
Get the next level of cache.
Returns
Next cache level or null if there is no more cache.
References _next.
Referenced by otawa::hard::CacheConfiguration::cacheName().
mask_t otawa::hard::Cache::offset (Address addr) const inline
Compute the offset of the accessed byte in the block from the memory address.
Parameters
addr Memory address to compute from.
Returns
Accessed byte offset in the block.
References blockMask(), and otawa::Address::offset().
Referenced by otawa::ipet::TrivialInstCacheManager::processBB(), and otawa::dcache::CLPBlockBuilder::processBB().
int otawa::hard::Cache::readPortSize (void) const inline
Get the read port size of this cache (default to 1, must be non-null).
Returns
Read port size.
References otawa::hard::Cache::info_t::read_port_size.
Cache::replace_policy_t otawa::hard::Cache::replacementPolicy (void) const inline
Get the replacement policy.
Returns
Replacement policy.
References otawa::hard::Cache::info_t::replace.
Referenced by otawa::sim::AbstractCacheDriver::lookup(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::dcache::CLPBlockBuilder::setup(), and otawa::dcache::BlockBuilder::setup().
Address otawa::hard::Cache::round (Address addr) const inline
Round the given address to the address of the container cache block.
Parameters
addr Address to round.
Returns
Round address.
References otawa::hard::Cache::info_t::access_time, otawa::hard::Cache::info_t::allocate, otawa::hard::Cache::info_t::block_bits, blockSize(), otawa::Address::isNull(), otawa::hard::Cache::info_t::miss_penalty, otawa::Address::offset(), otawa::Address::page(), otawa::hard::Cache::info_t::read_port_size, otawa::hard::Cache::info_t::replace, setAccessTime(), setAllocate(), setBlockBits(), setMissPenalty(), setReadPortSize(), setReplacePolicy(), setRowBits(), setWayBits(), setWriteBufferSize(), setWritePolicy(), setWritePortSize(), otawa::hard::Cache::info_t::way_bits, otawa::hard::Cache::info_t::write, otawa::hard::Cache::info_t::write_buffer_size, and otawa::hard::Cache::info_t::write_port_size.
Referenced by otawa::ccg::LBlockBuilder::addLBlock(), otawa::LBlockBuilder::addLBlock(), and otawa::dcache::CLPBlockBuilder::processBB().
int otawa::hard::Cache::rowBits (void) const inline
Required bits count for a row index.
Returns
Line index bits.
References otawa::hard::Cache::info_t::row_bits.
Referenced by cacheSize(), rowCount(), setCount(), tag(), and tagBits().
int otawa::hard::Cache::rowCount (void) const inline
Get the count of rows.
Returns
Count of rows.
References ENUM(), and rowBits().
Referenced by otawa::ccg::LBlockBuilder::cleanup(), otawa::LBlockBuilder::cleanup(), otawa::sim::FIFOCacheDriver::FIFOCacheDriver(), lineMask(), otawa::dcache::DirtyManager::t::print(), otawa::dcache::CLPBlockBuilder::processBB(), otawa::CAT2Builder::processCFG(), otawa::EdgeCAT2Builder::processCFG(), otawa::FirstLastBuilder::processCFG(), otawa::ccg::Builder::processLBlockSet(), otawa::LBlockProcessor::processWorkSpace(), otawa::EdgeCAT2ConstraintBuilder::processWorkSpace(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), otawa::dcache::CATBuilder::processWorkSpace(), otawa::ACSMayBuilder::processWorkSpace(), otawa::LinkedBlocksDetector::processWorkSpace(), otawa::ets::ACSComputation::processWorkSpace(), otawa::cat::CATConstraintBuilder::processWorkSpace(), otawa::ACSBuilder::processWorkSpace(), otawa::cat::CATBuilder::processWorkSpace(), otawa::CAT2ConstraintBuilder::processWorkSpace(), otawa::ccg::ConstraintBuilder::processWorkSpace(), otawa::EdgeACSBuilder::processWorkSpace(), otawa::ccg::Builder::processWorkSpace(), otawa::dcache::ACSMayBuilder::processWorkSpace(), otawa::dcache::ACSBuilder::processWorkSpace(), rowMask(), setMask(), otawa::dcache::CLPBlockBuilder::setup(), otawa::LBlockBuilder::setup(), otawa::ccg::LBlockBuilder::setup(), and otawa::dcache::BlockBuilder::setup().
ot::mask otawa::hard::Cache::rowMask (void) const inline
References blockBits(), and rowCount().
otawa::hard::Cache::SERIALIZABLE (Cache , field("access_time", _info.access_time, 1)&field("miss_penalty", _info.miss_penalty, 10)&field("block_bits", _info.block_bits, 4)&field("row_bits", _info.row_bits, 12)&field("way_bits", _info.way_bits, 0)&field("allocate", _info.allocate, false)&field("next", _next,(const Cache *) 0)&field("replace", _info.replace, LRU)&field("write_buffer_size", _info.write_buffer_size, 0)&field("read_port_size", _info.read_port_size, 1)&field("write_port_size", _info.write_port_size, 1)&field("write", _info.write, WRITE_THROUGH)) private
set_t otawa::hard::Cache::set (Address addr) const inline
References blockBits(), and lineMask().
Referenced by otawa::ccg::LBlockBuilder::addLBlock(), otawa::LBlockBuilder::addLBlock(), otawa::dcache::BlockAccess::inSet(), otawa::LBlockBuilder::processBB(), otawa::ccg::LBlockBuilder::processBB(), and otawa::dcache::CLPBlockBuilder::processBB().
void otawa::hard::Cache::setAccessTime (int access_time)
Set the access time.
Parameters
access_time Access time in processor cycles.
References _info, and otawa::hard::Cache::info_t::access_time.
Referenced by round().
void otawa::hard::Cache::setAllocate (bool allocate)
Set the allocation state.
If true, the write operation also allocate a block. If false, no allocation arise.
Parameters
allocate Allocate state.
References _info, and otawa::hard::Cache::info_t::allocate.
Referenced by round().
int otawa::hard::Cache::setBits (void) const inline
References otawa::hard::Cache::info_t::row_bits.
void otawa::hard::Cache::setBlockBits (int block_bits)
References _info, and otawa::hard::Cache::info_t::block_bits.
Referenced by round().
int otawa::hard::Cache::setCount (void) const inline
References rowBits().
Referenced by otawa::dcache::BlockAccess::inSet().
ot::mask otawa::hard::Cache::setMask (void) const inline
References blockBits(), and rowCount().
void otawa::hard::Cache::setMissPenalty (int miss_penalty)
Set the miss penaly time.
Parameters
miss_penaly Miss penalty time in processor cycles.
References _info, and otawa::hard::Cache::info_t::miss_penalty.
Referenced by round().
void otawa::hard::Cache::setReadPortSize (int read_port_size)
Set the read port size (at least 1).
Parameters
read_port_size Read port size.
References _info, and otawa::hard::Cache::info_t::read_port_size.
Referenced by round().
void otawa::hard::Cache::setReplacePolicy (replace_policy_t replace)
Set the replace policy of the cache.
Parameters
replace Replace policy, one of OTHER, LRU, RANDOM, FIFO, PLRU.
References _info, OTHER, PLRU, and otawa::hard::Cache::info_t::replace.
Referenced by round().
void otawa::hard::Cache::setRowBits (int row_bits)
Set the row count as a number of bits.
The actual row count is 1 << row_bits.
Parameters
row_bits Row count in bits.
References _info, and otawa::hard::Cache::info_t::row_bits.
Referenced by round().
void otawa::hard::Cache::setWayBits (int way_bits)
Set the way count as a number of bits.
The actual way count is 1 << way_bits.
Parameters
way_bits Way count in bits.
References _info, and otawa::hard::Cache::info_t::way_bits.
Referenced by round().
void otawa::hard::Cache::setWriteBufferSize (int write_buffer_size)
Set the write buffer size (0 for no write buffer).
Parameters
write_buffer_size Write buffer size.
References _info, and otawa::hard::Cache::info_t::write_buffer_size.
Referenced by round().
void otawa::hard::Cache::setWritePolicy (write_policy_t write)
Set the write policy of the cache.
Parameters
write Write policy, one of WRITE_THROUGH or WRITE_BACK.
References _info, otawa::hard::Cache::info_t::write, WRITE_BACK, and WRITE_THROUGH.
Referenced by round().
void otawa::hard::Cache::setWritePortSize (int write_port_size)
Set the write port size (at least 1).
Parameters
read_write_size Write port size.
References _info, FIFO, LRU, NONE, OTHER, PLRU, RANDOM, SERIALIZE(), VALUE(), WRITE_BACK, otawa::hard::Cache::info_t::write_port_size, and WRITE_THROUGH.
Referenced by round().
mask_t otawa::hard::Cache::tag (Address addr) const inline
Compute the tag from the memory address.
Parameters
addr Memory address to compute from.
Returns
Tag.
References blockBits(), otawa::Address::offset(), and rowBits().
Referenced by otawa::sim::AbstractCacheDriver::access(), and otawa::dcache::BlockAccess::inSet().
int otawa::hard::Cache::tagBits (void) const inline
Required bits count in the tag part of the address.
Returns
Tag bits.
References blockBits(), and rowBits().
mask_t otawa::hard::Cache::tagMask (void) const inline
Mask for selecting the tag in a memory address.
Returns
Tag selection mask.
References blockMask(), and lineMask().
int otawa::hard::Cache::wayBits (void) const inline
Get the number of bits to count the ways in set associative cache.
This value is 1 for direct-mapped cache.
Returns
Way count bits.
References otawa::hard::Cache::info_t::way_bits.
Referenced by cacheSize(), and wayCount().
int otawa::hard::Cache::wayCount (void) const inline
Get the count of ways for associatives caches.
Returns
Way count.
References wayBits().
Referenced by otawa::sim::AbstractCacheDriver::access(), otawa::sim::DirectMappedCacheDriver::DirectMappedCacheDriver(), otawa::sim::AbstractCacheDriver::lookup(), otawa::ets::ACSComputation::processAST(), otawa::dcache::ACSMayBuilder::processLBlockSet(), and otawa::sim::FIFOCacheDriver::replace().
int otawa::hard::Cache::writeBufferSize (void) const inline
Get the write buffer size of this cache (0 for no write buffer).
Returns
Write buffer size.
References otawa::hard::Cache::info_t::write_buffer_size.
Cache::write_policy_t otawa::hard::Cache::writePolicy (void) const inline
Get the write policy.
Returns
Write policy.
References otawa::hard::Cache::info_t::write.
Referenced by otawa::ipet::TrivialDataCacheManager::processBB().
int otawa::hard::Cache::writePortSize (void) const inline
Get the write port size of this cache (default to 1 for data cache).
Returns
Write port size.
References otawa::hard::Cache::info_t::write_port_size.
Member Data Documentation
info_t otawa::hard::Cache::_info private
Referenced by setAccessTime(), setAllocate(), setBlockBits(), setMissPenalty(), setReadPortSize(), setReplacePolicy(), setRowBits(), setWayBits(), setWriteBufferSize(), setWritePolicy(), and setWritePortSize().
const Cache* otawa::hard::Cache::_next private
Referenced by nextLevel().
The documentation for this class was generated from the following files:
include/otawa/hard/Cache.h
src/prog/hardware_Cache.cpp
src/prog/hardware_PureCache.cpp