Otawa: otawa::dcache::MUSTProblem Class Reference
otawa::dcache::MUSTProblem Class Reference
Data Cache
The MUST problem provides the abstract interpretation of L1 data cache for the MUST case.
#include <otawa/dcache/ACSBuilder.h>
Classes
class Domain
Public Member Functions
MUSTProblem (int _size, int _set, WorkSpace *_fw, const hard::Cache *_cache, int _A)
Build a MUST problem.
const Domain & bottom (void) const
const Domain & entry (void) const
void lub (Domain &a, const Domain &b) const
void assign (Domain &a, const Domain &b) const
void assign (Domain &a, const ACS &b) const
bool equals (const Domain &a, const Domain &b) const
void update (Domain &out, const Domain &in, BasicBlock *bb)
void update (Domain &s, const BlockAccess &access)
Update for an access.
void purge (Domain &out, const BlockAccess &acc)
Perform a purge according to the given block access.
void enterContext (Domain &dom, BasicBlock *header, util::hai_context_t ctx)
void leaveContext (Domain &dom, BasicBlock *header, util::hai_context_t ctx)
Public Attributes
Domain callstate
Private Attributes
WorkSpace * fw
int set
const hard::Cache * cache
Domain bot
Domain ent
int size
Detailed Description
The MUST problem provides the abstract interpretation of L1 data cache for the MUST case.
It implements the concept AbstractDomain.
Constructor & Destructor Documentation
MUSTProblem::MUSTProblem (int _size, int _set, WorkSpace * _fw, const hard::Cache * _cache, int _A)
Build a MUST problem.
Parameters
_size Number of blocks.
_set Number of sets in the cache.
_fw Current workspace.
_cache Analyzed cache.
_A Associativity of the cache.
References otawa::dcache::ACS::empty(), and ent.
Member Function Documentation
void otawa::dcache::MUSTProblem::assign (Domain & a, const Domain & b) const inline
Referenced by otawa::dcache::MUSTPERS::assign(), otawa::dcache::MUSTPERS::MUSTPERS(), otawa::dcache::MUSTPERS::setMust(), and update().
void otawa::dcache::MUSTProblem::assign (Domain & a, const ACS & b) const inline
const MUSTProblem::Domain & MUSTProblem::bottom (void) const
References bot.
Referenced by otawa::dcache::MUSTPERS::MUSTPERS().
void otawa::dcache::MUSTProblem::enterContext (Domain & dom, BasicBlock * header, util::hai_context_t ctx) inline
Referenced by otawa::dcache::MUSTPERS::enterContext().
const MUSTProblem::Domain & MUSTProblem::entry (void) const
References ent.
Referenced by otawa::dcache::MUSTPERS::MUSTPERS().
bool otawa::dcache::MUSTProblem::equals (const Domain & a, const Domain & b) const inline
References otawa::cfgio::bb(), and otawa::dcache::ACS::equals().
Referenced by otawa::dcache::MUSTPERS::equals().
void otawa::dcache::MUSTProblem::leaveContext (Domain & dom, BasicBlock * header, util::hai_context_t ctx) inline
Referenced by otawa::dcache::MUSTPERS::leaveContext().
void otawa::dcache::MUSTProblem::lub (Domain & a, const Domain & b) const inline
Referenced by otawa::dcache::MUSTPERS::lub().
void MUSTProblem::purge (Domain & out, const BlockAccess & acc)
Perform a purge according to the given block access.
Parameters
out In-out domain.
acc Purging block access.
References otawa::dcache::BlockAccess::action(), otawa::dcache::BlockAccess::ANY, otawa::dcache::BlockAccess::BLOCK, otawa::dcache::BlockAccess::block(), otawa::dcache::ACS::empty(), otawa::dcache::Block::index(), otawa::dcache::BlockAccess::inRange(), otawa::dcache::BlockAccess::kind(), otawa::dcache::BlockAccess::PURGE, otawa::dcache::BlockAccess::RANGE, and otawa::dcache::Block::set().
Referenced by otawa::dcache::MUSTPERS::update(), and update().
void MUSTProblem::update (Domain & out, const Domain & in, BasicBlock * bb)
References assign(), and otawa::dcache::DATA_BLOCKS.
void MUSTProblem::update (Domain & s, const BlockAccess & access)
Update for an access.
References otawa::dcache::BlockAccess::action(), otawa::dcache::MUSTProblem::Domain::ageAll(), otawa::dcache::BlockAccess::ANY, otawa::dcache::BlockAccess::BLOCK, otawa::dcache::BlockAccess::block(), otawa::dcache::BlockAccess::first, otawa::dcache::Block::index(), otawa::dcache::MUSTProblem::Domain::inject(), otawa::dcache::BlockAccess::kind(), otawa::dcache::BlockAccess::last, otawa::dcache::BlockAccess::LOAD, MUST_DEBUG, otawa::clp::NONE, purge(), otawa::dcache::BlockAccess::PURGE, otawa::dcache::BlockAccess::RANGE, otawa::dcache::Block::set(), and otawa::dcache::BlockAccess::STORE.
Member Data Documentation
Domain otawa::dcache::MUSTProblem::bot private
Referenced by bottom().
const hard::Cache* otawa::dcache::MUSTProblem::cache private
Domain otawa::dcache::MUSTProblem::callstate
Domain otawa::dcache::MUSTProblem::ent private
Referenced by entry(), and MUSTProblem().
WorkSpace* otawa::dcache::MUSTProblem::fw private
int otawa::dcache::MUSTProblem::set private
int otawa::dcache::MUSTProblem::size private
The documentation for this class was generated from the following files:
include/otawa/dcache/ACSBuilder.h
src/dcache/dcache_ACSBuilder.cpp