Otawa: otawa::graph::Graph Class Reference
otawa::graph::Graph Class Reference
Graph Handling
This class represents a full graph with nodes and edges.
#include <otawa/graph/Graph.h>
Classes
class InIterator
class Iterator
A simple iterator on the nodes contained in a graph.
class OutIterator
Public Types
typedef otawa::graph::Node * Vertex
typedef otawa::graph::Edge * Edge
Public Member Functions
~Graph (void)
void remove (graph::Edge *edge)
Destroy an edge.
int count (void) const
bool contains (Node *item) const
bool isEmpty (void) const
operator bool (void) const
void clear (void)
void add (Node *node)
Add new node.
template<template< class _ > class C>
void addAll (const C< Node * > &items)
void remove (Node *node)
Remove a node from a graph.
template<template< class _ > class C>
void removeAll (const C< Node * > &items)
void remove (const Iterator &iter)
Node * sinkOf (graph::Edge *edge) const
int outDegree (Node *vertex) const
Get the out degree of the given vertex.
bool isSuccessorOf (Node *succ, Node *ref) const
Test if the vertex succ is successor of the vertex ref.
Node * sourceOf (graph::Edge *edge) const
int inDegree (Node *vertex) const
Get the in degree of the given vertex.
bool isPredecessorOf (Node *prev, Node *ref) const
Test if the vertex pred is predecessor of the vertex ref.
int indexOf (Node *vertex) const
Private Attributes
elm::genstruct::FragTable< Node * > nodes
Friends
class Node
class Edge
Detailed Description
This class represents a full graph with nodes and edges.
It is not usually used as is : it may be embedded in some other object representing a graph and the Node and Edge classes is redefined to be valued according the requirement of the represented graph.
Implemented concepts
otawa::concept::DiGraph
otawa::concept::BiDiGraph
otawa::concept::DiGraphWithIndexedVertex
Member Typedef Documentation
typedef otawa::graph::Edge* otawa::graph::Graph::Edge
typedef otawa::graph::Node* otawa::graph::Graph::Vertex
Constructor & Destructor Documentation
otawa::graph::Graph::~Graph (void)
Member Function Documentation
void otawa::graph::Graph::add (Node * node)
Add new node.
Parameters
node Node to add.
References otawa::graph::Node::_graph, and otawa::graph::Node::idx.
Referenced by otawa::GenGraph< ParamExeNode, otawa::ExeGraph::ExeEdge >::add(), and otawa::graph::Node::Node().
template<template< class _ > class C> void otawa::graph::Graph::addAll (const C< Node * > & items) inline
References otawa::sem::add(), and otawa::graph::Node::Successor::item().
Referenced by otawa::GenGraph< ParamExeNode, otawa::ExeGraph::ExeEdge >::addAll().
void otawa::graph::Graph::clear (void)
References otawa::cfgio::edge().
Referenced by otawa::GenGraph< ParamExeNode, otawa::ExeGraph::ExeEdge >::clear().
bool otawa::graph::Graph::contains (Node * item) const inline
int otawa::graph::Graph::count (void) const inline
int otawa::graph::Graph::inDegree (Node * vertex) const
Get the in degree of the given vertex.
Parameters
vertex Vertex to compute out degree for.
Returns
Out degree of the vertex.
References otawa::cfgio::edge().
int otawa::graph::Graph::indexOf (Node * vertex) const inline
References otawa::graph::Node::index().
bool otawa::graph::Graph::isEmpty (void) const inline
bool otawa::graph::Graph::isPredecessorOf (Node * pred, Node * ref) const
Test if the vertex pred is predecessor of the vertex ref.
Parameters
pred Predecessor vertex.
ref Reference vertex.
Returns
True if pred is predecessor, false else.
References otawa::cfgio::edge().
bool otawa::graph::Graph::isSuccessorOf (Node * succ, Node * ref) const
Test if the vertex succ is successor of the vertex ref.
Parameters
succ Successor vertex.
ref Reference vertex.
Returns
True if succ is successor, false else.
References otawa::cfgio::edge().
otawa::graph::Graph::operator bool (void) const inline
int otawa::graph::Graph::outDegree (Node * vertex) const
Get the out degree of the given vertex.
Parameters
vertex Vertex to compute out degree for.
Returns
Out degree of the vertex.
References otawa::cfgio::edge().
void otawa::graph::Graph::remove (graph::Edge * edge)
Destroy an edge.
Parameters
edge Edge to destroy.
References otawa::cfgio::edge(), otawa::graph::Node::ins, otawa::graph::Node::outs, otawa::graph::Edge::sedges, otawa::graph::Edge::src, otawa::graph::Edge::tedges, and otawa::graph::Edge::tgt.
Referenced by otawa::GenGraph< ParamExeNode, otawa::ExeGraph::ExeEdge >::remove().
void otawa::graph::Graph::remove (Node * node)
Remove a node from a graph.
Parameters
node Node to remove.
References otawa::graph::Node::_graph, otawa::graph::Node::graph(), otawa::graph::Node::idx, and otawa::graph::Node::unlink().
void otawa::graph::Graph::remove (const Iterator & iter) inline
template<template< class _ > class C> void otawa::graph::Graph::removeAll (const C< Node * > & items) inline
References otawa::graph::Node::Successor::item().
Referenced by otawa::GenGraph< ParamExeNode, otawa::ExeGraph::ExeEdge >::removeAll().
Node* otawa::graph::Graph::sinkOf (graph::Edge * edge) const inline
References otawa::graph::Edge::target().
Node* otawa::graph::Graph::sourceOf (graph::Edge * edge) const inline
References otawa::graph::Edge::source().
Friends And Related Function Documentation
friend class Edge friend
friend class Node friend
Member Data Documentation
elm::genstruct::FragTable<Node *> otawa::graph::Graph::nodes private
The documentation for this class was generated from the following files:
include/otawa/graph/Graph.h
src/prog/util_Graph.cpp