Otawa: otawa::BBStatCollector Class Reference
otawa::BBStatCollector Class Reference abstract
This class alleviates the work of building a statistics collector.
#include <otawa/stats/BBStatCollector.h>
Public Member Functions
BBStatCollector (WorkSpace *ws)
Build the BB statistics collector.
virtual void collect (Collector &collector)
Called to collect the statistics.
virtual cstring name (void) const =0
Name of the statistics (for human user, in english).
virtual cstring unit (void) const =0
Name of statistics unit (for human user, in english).
virtual bool isEnum (void) const =0
Test if the statistics concerns enumerated value.
virtual const cstring valueName (int value)=0
Get the name of an enumerated value (for human user, in english).
virtual int mergeContext (int v1, int v2)=0
This function allows to merge statistics of a same block in different contexts.
virtual int mergeAgreg (int v1, int v2)=0
This function allows to merge statistics when different blocks are aggregated.
Protected Member Functions
WorkSpace * ws (void) const
CFG * cfg (void) const
virtual int total (void)
Default implementation of a total as the sum of the total of each basic block (method total(BasicBlock *).
virtual void collect (Collector &collector, BasicBlock *bb)=0
This method is called for each basic block in the current workspace (except for syntactic entry and exit blocks).
virtual int total (BasicBlock *bb)
This method is automatically called on each basic block to compute the total() result as the sum of total of each basic block.
Private Member Functions
virtual void processCFG (Collector &collector, CFG *cfg)
void process (Collector &collector)
Process basic block of the current CFG.
Private Attributes
WorkSpace * _ws
CFG * _cfg
int _total
Detailed Description
This class alleviates the work of building a statistics collector.
It ensures the traversal of all basic blocks and calls collect() to let the inheriting class do specific work for a basic block.
Constructor & Destructor Documentation
otawa::BBStatCollector::BBStatCollector (WorkSpace * ws)
Build the BB statistics collector.
Parameters
ws Current workspace.
Member Function Documentation
CFG* otawa::BBStatCollector::cfg (void) const inline protected
References _cfg, otawa::cfgio::bb(), collect(), process(), processCFG(), and total().
Referenced by processCFG().
void otawa::BBStatCollector::collect (Collector & collector) virtual
Called to collect the statistics.
Parameters
collector Collector of statistics.
Implements otawa::StatCollector.
References _cfg, otawa::CFGCollection::count(), otawa::CFGCollection::get(), otawa::INVOLVED_CFGS, process(), and ws().
Referenced by cfg(), and processCFG().
void otawa::BBStatCollector::collect (Collector & collector, BasicBlock * bb) protected pure virtual
This method is called for each basic block in the current workspace (except for syntactic entry and exit blocks).
It must specialized by the inheriting class to provide specific work.
The methods ws(), cfg() and path() allows to get the current information about the processed blocks.
Parameters
collector The invoker collector to pass statistics information.
bb Current basic block.
bool otawa::StatCollector::isEnum (void) const pure virtual inherited
Test if the statistics concerns enumerated value.
If this method returns true, method valueName() can be called to collect names of enumerated values. The number of enumerated values is given by the total method.
Returns
True if the statistics are enumerated values.
int otawa::StatCollector::mergeAgreg (int v1, int v2) pure virtual inherited
This function allows to merge statistics when different blocks are aggregated.
int otawa::StatCollector::mergeContext (int v1, int v2) pure virtual inherited
This function allows to merge statistics of a same block in different contexts.
cstring otawa::StatCollector::name (void) const pure virtual inherited
Name of the statistics (for human user, in english).
void otawa::BBStatCollector::process (Collector & collector) private
Process basic block of the current CFG.
Parameters
collector Collector to use.
References _cfg, _ws, otawa::CFGCollection::count(), otawa::CFGCollection::get(), otawa::INVOLVED_CFGS, and processCFG().
Referenced by cfg(), and collect().
void otawa::BBStatCollector::processCFG (Collector & collector, CFG * cfg) private virtual
References _cfg, otawa::ProgItem::address(), otawa::BasicBlock::address(), otawa::cfgio::bb(), otawa::Edge::CALL, otawa::ContextualStep::CALL, otawa::CALLED_CFG, cfg(), collect(), otawa::BasicBlock::controlInst(), otawa::CFG::countBB(), otawa::cfgio::edge(), otawa::StatCollector::Collector::enter(), otawa::CFG::entry(), otawa::CFG::exit(), otawa::ContextualStep::FUNCTION, otawa::BasicBlock::isEntry(), otawa::Edge::kind(), otawa::StatCollector::Collector::leave(), otawa::Edge::NONE, otawa::Edge::NOT_TAKEN, otawa::BasicBlock::number(), otawa::Edge::source(), otawa::Edge::TAKEN, otawa::Edge::target(), otawa::Edge::VIRTUAL, otawa::Edge::VIRTUAL_CALL, otawa::Edge::VIRTUAL_RETURN, and otawa::VIRTUAL_RETURN_BLOCK.
Referenced by cfg(), and process().
int otawa::BBStatCollector::total (void) protected virtual
Default implementation of a total as the sum of the total of each basic block (method total(BasicBlock *).
It may be overriden if the default behavior does not match. As a default, entry and exit nodes are ignored.
Returns
Total of the statistics.
Implements otawa::StatCollector.
References _cfg, _total, _ws, otawa::cfgio::bb(), otawa::CFGCollection::count(), otawa::CFGCollection::get(), and otawa::INVOLVED_CFGS.
Referenced by cfg().
int otawa::BBStatCollector::total (BasicBlock * bb) protected virtual
This method is automatically called on each basic block to compute the total() result as the sum of total of each basic block.
This methodmust be overriden to provide a customized behaviour. As a default, it returns 0.
Parameters
bb Current basic block.
Returns
Total of the basic block.
cstring otawa::StatCollector::unit (void) const pure virtual inherited
Name of statistics unit (for human user, in english).
const cstring otawa::StatCollector::valueName (int value) pure virtual inherited
Get the name of an enumerated value (for human user, in english).
May only be called if isEnum() returns true.
Parameters
value Enumerated value.
Returns
Name of the enumerated value.
WorkSpace* otawa::BBStatCollector::ws (void) const inline protected
References _ws.
Referenced by collect().
Member Data Documentation
CFG* otawa::BBStatCollector::_cfg private
Referenced by cfg(), collect(), process(), processCFG(), and total().
int otawa::BBStatCollector::_total private
Referenced by total().
WorkSpace* otawa::BBStatCollector::_ws private
Referenced by process(), total(), and ws().
The documentation for this class was generated from the following files:
include/otawa/stats/BBStatCollector.h
src/prog/stats_BBStatCollector.cpp