Otawa: otawa::ParExeNode Class Reference
otawa::ParExeNode Class Reference
Parametric Execution Graph
A node of the ParExeGraph, that represents the crossing of an instruction inside a microprocessor stage.
#include <otawa/parexegraph/ParExeGraph.h>
Public Member Functions
ParExeNode (ParExeGraph *graph, ParExeStage *stage, ParExeInst *inst)
ParExeStage * stage (void)
ParExeInst * inst (void)
int latency ()
void setDefaultLatency (int lat)
void restoreDefaultLatency (void)
void setLatency (int latency)
void addProducer (ParExeNode *prod)
int numProducers (void)
ParExeNode * producer (int index)
void addContender (ParExeNode *cont)
elm::genstruct::DLList< elm::BitVector * > * contendersMasksList ()
elm::String name (void)
int delay (int index)
void setDelay (int index, int value)
void initContenders (int size)
int lateContenders (void)
void setLateContenders (int num)
elm::BitVector * possibleContenders (void)
void setContender (int index)
void buildContendersMasks ()
int index (void) const
bool hasSucc (void) const
bool hasPred (void) const
int countSucc (void) const
int countPred (void) const
bool isPredOf (const GenNode *node)
bool isSuccOf (const GenNode *node)
Protected Attributes
elm::genstruct::Vector< ParExeNode * > _producers
elm::genstruct::Vector< ParExeNode * > _contenders
elm::BitVector * _possible_contenders
elm::genstruct::DLList< elm::BitVector * > _contenders_masks_list
int _late_contenders
Private Attributes
ParExeStage * _pipeline_stage
ParExeInst * _inst
int _latency
int _default_latency
elm::String _name
elm::genstruct::AllocatedTable< int > * _delay
Detailed Description
A node of the ParExeGraph, that represents the crossing of an instruction inside a microprocessor stage.
See also
Parametric Execution Graph
Constructor & Destructor Documentation
otawa::ParExeNode::ParExeNode (ParExeGraph * graph, ParExeStage * stage, ParExeInst * inst) inline
References otawa::ParExeGraph::_first_node, otawa::ParExeGraph::_last_prologue_node, otawa::ParExeInst::codePart(), otawa::ParExeGraph::firstNode(), otawa::ParExeInst::index(), otawa::ParExeStage::name(), otawa::ParExeGraph::numInstructions(), otawa::ParExeGraph::numResources(), and otawa::PROLOGUE.
Member Function Documentation
void otawa::ParExeNode::addContender (ParExeNode * cont) inline
Referenced by otawa::ParExeGraph::findContendingNodes().
void otawa::ParExeNode::addProducer (ParExeNode * prod) inline
void otawa::ParExeNode::buildContendersMasks ()
elm::genstruct::DLList<elm::BitVector *>* otawa::ParExeNode::contendersMasksList () inline
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::countPred (void) const inline inherited
References otawa::graph::Node::countPred().
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::countSucc (void) const inline inherited
References otawa::graph::Node::countSucc().
int otawa::ParExeNode::delay (int index) inline
Referenced by otawa::ParExeGraph::analyze(), otawa::ParExeGraph::cost(), and otawa::ParExeGraph::delta().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::hasPred (void) const inline inherited
References otawa::graph::Node::hasPred().
Referenced by otawa::LiExeGraph::shadeNodes().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::hasSucc (void) const inline inherited
References otawa::graph::Node::hasSucc().
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::index (void) const inline inherited
References otawa::graph::Node::index().
Referenced by otawa::ParamExeGraph::cost().
void otawa::ParExeNode::initContenders (int size) inline
ParExeInst* otawa::ParExeNode::inst (void) inline
Referenced by otawa::ParExeGraph::addEdgesForDataDependencies(), otawa::ParExeGraph::addEdgesForFetch(), and otawa::ParExeGraph::addEdgesForMemoryOrder().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::isPredOf (const GenNode * node) inline inherited
References otawa::graph::Node::countPred().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::isSuccOf (const GenNode * node) inline inherited
References otawa::graph::Node::isSuccOf().
int otawa::ParExeNode::lateContenders (void) inline
int otawa::ParExeNode::latency (void) inline
Referenced by otawa::etime::EdgeTimeBuilder::apply(), and otawa::etime::EdgeTimeBuilder::rollback().
elm::String otawa::ParExeNode::name (void) inline
int otawa::ParExeNode::numProducers (void) inline
elm::BitVector* otawa::ParExeNode::possibleContenders (void) inline
ParExeNode* otawa::ParExeNode::producer (int index) inline
void otawa::ParExeNode::restoreDefaultLatency (void) inline
void otawa::ParExeNode::setContender (int index) inline
void otawa::ParExeNode::setDefaultLatency (int lat) inline
void otawa::ParExeNode::setDelay (int index, int value) inline
Referenced by otawa::ParExeGraph::initDelays().
void otawa::ParExeNode::setLateContenders (int num) inline
void otawa::ParExeNode::setLatency (int latency) inline
Referenced by otawa::etime::EdgeTimeBuilder::apply(), and otawa::etime::EdgeTimeBuilder::rollback().
ParExeStage* otawa::ParExeNode::stage (void) inline
Referenced by otawa::ParExeInst::addNode().
Member Data Documentation
elm::genstruct::Vector<ParExeNode *> otawa::ParExeNode::_contenders protected
elm::genstruct::DLList<elm::BitVector *> otawa::ParExeNode::_contenders_masks_list protected
int otawa::ParExeNode::_default_latency private
elm::genstruct::AllocatedTable<int>* otawa::ParExeNode::_delay private
ParExeInst* otawa::ParExeNode::_inst private
int otawa::ParExeNode::_late_contenders protected
int otawa::ParExeNode::_latency private
elm::String otawa::ParExeNode::_name private
ParExeStage* otawa::ParExeNode::_pipeline_stage private
elm::BitVector* otawa::ParExeNode::_possible_contenders protected
elm::genstruct::Vector<ParExeNode *> otawa::ParExeNode::_producers protected
The documentation for this class was generated from the following files:
include/otawa/parexegraph/ParExeGraph.h
src/prog/parexegraph_ParExeGraph.cpp