Otawa: otawa::display::AbstractDrawer Class Reference
otawa::display::AbstractDrawer Class Reference
ODisplay Library
Provides facilities to draw a graph.
#include <otawa/display/AbstractDrawer.h>
Classes
class Edge
An edge in a AbstractDrawer.
class Vertex
This class represents vertices in the AbstractDrawer.
Public Member Functions
AbstractDrawer (void)
Build a drawer with the default driver.
AbstractDrawer (Driver &driver)
Build a drawer with the given driver.
virtual ~AbstractDrawer (void)
void draw (void)
Launch the draw of the graph.
virtual void configure (Output &caption, TextStyle &text, FillStyle &fill)
This method may be overriden to provide a customized graph ledend.
Public Attributes
kind_t kind
String path
FillStyle page_fill
TextStyle page_text
ShapeStyle default_vertex
LineStyle default_edge_line
TextStyle default_edge_text
Private Attributes
Graph * graph
FragTable< Vertex * > vertices
FragTable< Edge * > edges
Detailed Description
Provides facilities to draw a graph.
The vertices and edges of the graph must be built from the classes AbstractDrawer::Vertex and AbstractDrawer::Edge.
AbstractDrawer is rarely used as is. You may prefer automatic graph drawing facilities based on AbstractDrawer provides by GenDrawer.
The drawing is configured using several publicly accessible member attributes:
kind Kind of drawing
path path of the file to create
page_fill page backrgound fill style
page_text page text style
default_vertex default vertex shape style
default_edge_line default edge line style
default_edge_text default edge label text style
Constructor & Destructor Documentation
otawa::display::AbstractDrawer::AbstractDrawer (void)
Build a drawer with the default driver.
Exceptions
display::Exception If there is no driver available.
References otawa::display::Driver::find(), graph, and otawa::display::Driver::newGraph().
otawa::display::AbstractDrawer::AbstractDrawer (Driver & driver)
Build a drawer with the given driver.
Parameters
driver Driver to use.
References graph, and otawa::display::Driver::newGraph().
virtual otawa::display::AbstractDrawer::~AbstractDrawer (void) inline virtual
Member Function Documentation
void otawa::display::AbstractDrawer::configure (Output & caption, TextStyle & text, FillStyle & fill) virtual
This method may be overriden to provide a customized graph ledend.
Parameters
out Graph caption.
text Graph caption text style to configure.
fill Graph background fill style to configure.
Reimplemented in otawa::display::GenDrawer< G, D >.
Referenced by draw(), otawa::display::AbstractDrawer::Vertex::setup(), and otawa::display::AbstractDrawer::Edge::setup().
void otawa::display::AbstractDrawer::draw (void)
Launch the draw of the graph.
References otawa::display::BODY, configure(), otawa::display::Graph::display(), otawa::cfgio::edge(), edges, graph, kind, otawa::display::OUTPUT_KIND, otawa::display::OUTPUT_PATH, page_fill, page_text, path, and vertices.
Referenced by otawa::display::CFGOutput::processCFG().
Member Data Documentation
LineStyle otawa::display::AbstractDrawer::default_edge_line
Referenced by otawa::display::AbstractDrawer::Edge::Edge().
TextStyle otawa::display::AbstractDrawer::default_edge_text
Referenced by otawa::display::AbstractDrawer::Edge::Edge(), and otawa::display::CFGOutput::processCFG().
ShapeStyle otawa::display::AbstractDrawer::default_vertex
Referenced by otawa::display::CFGOutput::processCFG(), and otawa::display::AbstractDrawer::Vertex::Vertex().
FragTable<Edge *> otawa::display::AbstractDrawer::edges private
Referenced by draw(), and otawa::display::AbstractDrawer::Edge::Edge().
Graph* otawa::display::AbstractDrawer::graph private
Referenced by AbstractDrawer(), draw(), otawa::display::AbstractDrawer::Edge::Edge(), and otawa::display::AbstractDrawer::Vertex::Vertex().
kind_t otawa::display::AbstractDrawer::kind
Referenced by draw(), and otawa::display::CFGOutput::processCFG().
FillStyle otawa::display::AbstractDrawer::page_fill
Referenced by draw().
TextStyle otawa::display::AbstractDrawer::page_text
Referenced by draw().
String otawa::display::AbstractDrawer::path
Referenced by draw(), and otawa::display::CFGOutput::processCFG().
FragTable<Vertex *> otawa::display::AbstractDrawer::vertices private
Referenced by draw(), and otawa::display::AbstractDrawer::Vertex::Vertex().
The documentation for this class was generated from the following files:
include/otawa/display/AbstractDrawer.h
src/odisplay/display_AbstractDrawer.cpp