Otawa: otawa::ExeGraph< N >::ExeEdge Class Reference
otawa::ExeGraph< N >::ExeEdge Class Reference
#include <otawa/exegraph/ExeGraph.h>
Public Types
enum edge_type_t { SOLID = 1, SLASHED = 2, NONE = 3 }
typedef enum otawa::ExeGraph::ExeEdge::edge_type_t edge_type_t_t
Public Member Functions
ExeEdge (N *source, N *target, edge_type_t type)
Constructor.
edge_type_t type (void)
elm::String name ()
Returns the name of the edge composed of the names of the source and target nodes separated by an arrow (e.g.
N * source (void) const
N * target (void) const
Private Attributes
edge_type_t _type
elm::String _name
Member Typedef Documentation
template<class N> typedef enum otawa::ExeGraph::ExeEdge::edge_type_t otawa::ExeGraph< N >::ExeEdge::edge_type_t_t
Member Enumeration Documentation
template<class N> enum otawa::ExeGraph::ExeEdge::edge_type_t
Enumerator
SOLID
SLASHED
NONE
Constructor & Destructor Documentation
template<class N> otawa::ExeGraph< N >::ExeEdge::ExeEdge (N * source, N * target, edge_type_t type) inline
Constructor.
Parameters
source The source node.
target The target node.
type The type of the edge.
References name, otawa::cfgio::source(), and otawa::cfgio::target().
Member Function Documentation
template<class N> elm::String otawa::ExeGraph< N >::ExeEdge::name (void) inline
Returns the name of the edge composed of the names of the source and target nodes separated by an arrow (e.g.
"CM(I1)->IF(I3)").
Returns
Edge name.
Referenced by otawa::ExeGraph< N >::build().
template<class N, class E> N* otawa::GenGraph< N, E >::GenEdge::source (void) const inline inherited
References OTAWA_GCAST, and otawa::graph::Edge::source().
template<class N, class E> N* otawa::GenGraph< N, E >::GenEdge::target (void) const inline inherited
References OTAWA_GCAST, and otawa::graph::Edge::target().
template<class N> ExeGraph< N >::ExeEdge::edge_type_t otawa::ExeGraph< N >::ExeEdge::type (void) inline
Returns
Edge type.
Member Data Documentation
template<class N> elm::String otawa::ExeGraph< N >::ExeEdge::_name private
template<class N> edge_type_t otawa::ExeGraph< N >::ExeEdge::_type private
The documentation for this class was generated from the following files:
include/otawa/exegraph/ExeGraph.h
src/prog/exegraph_ExeGraph.cpp