Otawa: otawa::display::GraphVizItem Class Reference
otawa::display::GraphVizItem Class Reference abstract
#include </home/yashas/otawa/linux-x86_64/otawa-core-build/otawa/src/odisplay/graphviz.h>
Public Member Functions
GraphVizItem ()
Used to set the default behaviour of properties listing to "INCLUDE".
virtual ~GraphVizItem (void)
virtual void setProps (const PropList &props)
virtual String attributes ()=0
calls attributes(const PropList& style) with the PropList containing the style of the item.
Protected Member Functions
virtual String getPropertiesString ()
Makes a string containing the values of all properties in _props separated by newlines.
virtual void printOthersAttributes (elm::io::Output &out)
Prints attributes after all the style PropList have been iterated.
virtual String attributes (const PropList &props)
Prints all attributes (styles) in a string, between brackets.
virtual bool printAttribute (elm::io::Output &out, const PropList::Iter &prop)
Process the Property given by the iterator pointing to it.
Protected Attributes
PropList _props
Properties of the attached object.
elm::genstruct::HashTable< const AbstractIdentifier *, int > _include
List of properties to print.
elm::genstruct::HashTable< const AbstractIdentifier *, int > _exclude
List of properties to hide.
bool _defaultInclude
true if the default is to include all properties
Detailed Description
Author
G. Cavaignac
This class is the superclass of all graphviz elements (Node, Edge & Graph)
Constructor & Destructor Documentation
otawa::display::GraphVizItem::GraphVizItem ()
Used to set the default behaviour of properties listing to "INCLUDE".
virtual otawa::display::GraphVizItem::~GraphVizItem (void) inline virtual
Member Function Documentation
String otawa::display::GraphVizItem::attributes (const PropList & style) protected virtual
Prints all attributes (styles) in a string, between brackets.
First iterates on the style PropList, calling printAttribute() for each property, and then, calls printOthersAttributes() to finish. This functions escapes all the newlines that have been appened in the functions printAttribute() and printOthersAttributes()
Parameters
style styles to be printed
Returns
String containing the attributes. For example: [color="red"]
References otawa::PropList::Iter::ended(), printAttribute(), printOthersAttributes(), and otawa::display::quoteNewlines().
otawa::display::GraphVizItem::attributes (void) pure virtual
calls attributes(const PropList& style) with the PropList containing the style of the item.
Generally, the proplist is the object itself, because it inherits from PropList
Implemented in otawa::display::GraphVizGraph, otawa::display::GraphVizEdge, and otawa::display::GraphVizNode.
Referenced by otawa::display::GraphVizNode::attributes(), otawa::display::GraphVizEdge::attributes(), and otawa::display::GraphVizGraph::attributes().
String otawa::display::GraphVizItem::getPropertiesString () protected virtual
Makes a string containing the values of all properties in _props separated by newlines.
Returns
string containing properties values
References _defaultInclude, _exclude, _include, _props, otawa::PropList::Iter::ended(), and otawa::AbstractIdentifier::print().
Referenced by otawa::display::GraphVizNode::printOthersAttributes(), and otawa::display::GraphVizEdge::printOthersAttributes().
bool otawa::display::GraphVizItem::printAttribute (elm::io::Output & out, const PropList::Iter & prop) protected virtual
Process the Property given by the iterator pointing to it.
Prints the value to the given output, or store the property for example (the property can be printed furthermore by printOthersAttributes())
Parameters
out output where to print when something have to be printed iterator on properties. Used to compare the identifier and to get the property value
Returns
true if something have been written on the output, false else
Reimplemented in otawa::display::GraphVizEdge, otawa::display::GraphVizNode, and otawa::display::GraphVizGraphElement.
References _defaultInclude, _exclude, _include, otawa::display::BACKGROUND, otawa::display::COLOR, otawa::display::DEFAULT, otawa::display::EXCLUDE, otawa::display::HREF, otawa::display::INCLUDE, and otawa::display::quoteSpecials().
Referenced by attributes(), and otawa::display::GraphVizGraphElement::printAttribute().
void otawa::display::GraphVizItem::printOthersAttributes (elm::io::Output & out) protected virtual
Prints attributes after all the style PropList have been iterated.
One can append endlines to the output
Parameters
out output where to print others attributes
Reimplemented in otawa::display::GraphVizGraph, otawa::display::GraphVizEdge, and otawa::display::GraphVizNode.
Referenced by attributes().
void otawa::display::GraphVizItem::setProps (const PropList & props) virtual
See also
Item::setProps(const PropList& props)
Reimplemented in otawa::display::GraphVizGraph, otawa::display::GraphVizEdge, and otawa::display::GraphVizNode.
References _props, otawa::PropList::addProps(), and otawa::PropList::clearProps().
Referenced by otawa::display::GraphVizNode::setProps(), otawa::display::GraphVizEdge::setProps(), and otawa::display::GraphVizGraph::setProps().
Member Data Documentation
bool otawa::display::GraphVizItem::_defaultInclude protected
true if the default is to include all properties
Referenced by getPropertiesString(), and printAttribute().
elm::genstruct::HashTable<const AbstractIdentifier*, int> otawa::display::GraphVizItem::_exclude protected
List of properties to hide.
If the key exists, exclude the property
Referenced by getPropertiesString(), and printAttribute().
elm::genstruct::HashTable<const AbstractIdentifier*, int> otawa::display::GraphVizItem::_include protected
List of properties to print.
If the key exists, include the property
Referenced by getPropertiesString(), and printAttribute().
PropList otawa::display::GraphVizItem::_props protected
Properties of the attached object.
Referenced by getPropertiesString(), and setProps().
The documentation for this class was generated from the following files:
src/odisplay/graphviz.h
src/odisplay/graphviz_Item.cpp