Otawa: otawa::sim::BBPathDriver Class Reference
otawa::sim::BBPathDriver Class Reference
#include <otawa/sim/BBPathDriver.h>
Public Member Functions
BBPathDriver (tsim::BBPath &bbpath)
virtual ~BBPathDriver ()
virtual Inst * firstInstruction (State &state)
virtual Inst * nextInstruction (State &state, Inst *inst)
This method is called each time the simulator needs the next instruction to execute.
virtual void terminateInstruction (State &state, Inst *inst)
This method is called when an instruction is terminated.
virtual Address lowerRead (void)
Get the lower read address of the last executed instruction.
virtual Address upperRead (void)
Get the upper read address of the last executed instruction.
virtual Address lowerWrite (void)
Get the lower written address of the last executed instruction.
virtual Address upperWrite (void)
Get the upper written address of the last executed instruction.
virtual void redirect (State &state, Inst *branch, bool direction)
virtual bool PredictBranch (State &state, Inst *branch, bool pred)
Private Attributes
tsim::BBPath::BBIterator bb_iter
BasicBlock::InstIter * inst_iter
bool ended
Constructor & Destructor Documentation
otawa::sim::BBPathDriver::BBPathDriver (tsim::BBPath & bbpath)
References bb_iter, ended, otawa::tsim::BBPath::BBIterator::ended(), inst_iter, otawa::tsim::BBPath::BBIterator::item(), and otawa::tsim::BBPath::BBIterator::next().
otawa::sim::BBPathDriver::~BBPathDriver () virtual
References inst_iter.
Member Function Documentation
Inst * otawa::sim::BBPathDriver::firstInstruction (State & state) virtual
References nextInstruction().
Address otawa::sim::Driver::lowerRead (void) virtual inherited
Get the lower read address of the last executed instruction.
Returns
Lower read address.
References otawa::Address::null.
Address otawa::sim::Driver::lowerWrite (void) virtual inherited
Get the lower written address of the last executed instruction.
Returns
Lower written address.
References otawa::Address::null.
Inst * otawa::sim::BBPathDriver::nextInstruction (State & state, Inst * inst) virtual
This method is called each time the simulator needs the next instruction to execute.
Parameters
state Current state of the simulator.
inst Next instruction proposed by the simulator. If the simulator does not handle the semantics of instructions, it is juste the next instruction.
Returns
Next instruction to execute or null if there is no more instruction to execute.
Implements otawa::sim::Driver.
References bb_iter, ended, otawa::BasicBlock::InstIter::ended(), otawa::tsim::BBPath::BBIterator::ended(), inst_iter, otawa::BasicBlock::InstIter::item(), otawa::tsim::BBPath::BBIterator::item(), otawa::BasicBlock::InstIter::next(), and otawa::tsim::BBPath::BBIterator::next().
Referenced by firstInstruction().
virtual bool otawa::sim::Driver::PredictBranch (State & state, Inst * branch, bool pred) inline virtual inherited
virtual void otawa::sim::Driver::redirect (State & state, Inst * branch, bool direction) inline virtual inherited
void otawa::sim::BBPathDriver::terminateInstruction (State & state, Inst * inst) virtual
This method is called when an instruction is terminated.
Parameters
state Current state of the simulator.
inst Terminated instruction.
Implements otawa::sim::Driver.
Address otawa::sim::Driver::upperRead (void) virtual inherited
Get the upper read address of the last executed instruction.
Returns
Upper read address.
References otawa::Address::null.
Address otawa::sim::Driver::upperWrite (void) virtual inherited
Get the upper written address of the last executed instruction.
Returns
Lower written address.
References otawa::Address::null.
Member Data Documentation
tsim::BBPath::BBIterator otawa::sim::BBPathDriver::bb_iter private
Referenced by BBPathDriver(), and nextInstruction().
bool otawa::sim::BBPathDriver::ended private
Referenced by BBPathDriver(), and nextInstruction().
BasicBlock::InstIter* otawa::sim::BBPathDriver::inst_iter private
Referenced by BBPathDriver(), nextInstruction(), and ~BBPathDriver().
The documentation for this class was generated from the following files:
include/otawa/sim/BBPathDriver.h
src/prog/sim_BBPathDriver.cpp