Otawa: otawa::ParamExeGraph::Resource Class Reference
otawa::ParamExeGraph::Resource Class Reference
#include <otawa/exegraph/ParamExeGraph.h>
Public Member Functions
Resource (elm::String name, resource_type_t type, int index, int offset)
elm::String name ()
resource_type_t type ()
int index ()
int offset ()
Private Attributes
elm::String _name
resource_type_t _type
int _index
int _offset
Constructor & Destructor Documentation
otawa::ParamExeGraph::Resource::Resource (elm::String name, resource_type_t type, int index, int offset) inline
Member Function Documentation
int otawa::ParamExeGraph::Resource::index (void) inline
Referenced by otawa::ParamExeGraph::cost(), and otawa::ParamExeGraph::Delta().
elm::String otawa::ParamExeGraph::Resource::name (void) inline
Referenced by otawa::ParamExeGraph::cost(), and otawa::ParamExeGraph::Delta().
int otawa::ParamExeGraph::Resource::offset (void) inline
Referenced by otawa::ParamExeGraph::Delta().
resource_type_t otawa::ParamExeGraph::Resource::type (void) inline
Referenced by otawa::ParamExeGraph::Delta().
Member Data Documentation
int otawa::ParamExeGraph::Resource::_index private
elm::String otawa::ParamExeGraph::Resource::_name private
int otawa::ParamExeGraph::Resource::_offset private
resource_type_t otawa::ParamExeGraph::Resource::_type private
The documentation for this class was generated from the following file:
include/otawa/exegraph/ParamExeGraph.h