Otawa: otawa::ParamExeGraph::InternalConflictResource Class Reference
otawa::ParamExeGraph::InternalConflictResource Class Reference
#include <otawa/exegraph/ParamExeGraph.h>
Public Member Functions
InternalConflictResource (elm::String name, ExeInst< ParamExeNode > *instruction, int index, int offset)
ExeInst< ParamExeNode > * instruction ()
void setNode (ParamExeNode *node)
ParamExeNode * node ()
elm::String name ()
resource_type_t type ()
int index ()
int offset ()
Private Attributes
ExeInst< ParamExeNode > * _instruction
ParamExeNode * _node
Constructor & Destructor Documentation
otawa::ParamExeGraph::InternalConflictResource::InternalConflictResource (elm::String name, ExeInst< ParamExeNode > * instruction, int index, int offset) inline
Member Function Documentation
int otawa::ParamExeGraph::Resource::index (void) inline inherited
Referenced by otawa::ParamExeGraph::cost(), and otawa::ParamExeGraph::Delta().
ExeInst<ParamExeNode>* otawa::ParamExeGraph::InternalConflictResource::instruction (void) inline
elm::String otawa::ParamExeGraph::Resource::name (void) inline inherited
Referenced by otawa::ParamExeGraph::cost(), and otawa::ParamExeGraph::Delta().
ParamExeNode* otawa::ParamExeGraph::InternalConflictResource::node () inline
int otawa::ParamExeGraph::Resource::offset (void) inline inherited
Referenced by otawa::ParamExeGraph::Delta().
void otawa::ParamExeGraph::InternalConflictResource::setNode (ParamExeNode * node) inline
resource_type_t otawa::ParamExeGraph::Resource::type (void) inline inherited
Referenced by otawa::ParamExeGraph::Delta().
Member Data Documentation
ExeInst<ParamExeNode>* otawa::ParamExeGraph::InternalConflictResource::_instruction private
ParamExeNode* otawa::ParamExeGraph::InternalConflictResource::_node private
The documentation for this class was generated from the following file:
include/otawa/exegraph/ParamExeGraph.h