Otawa: otawa::BBCleaner Class Reference
otawa::BBCleaner Class Reference abstract
Efficient implementation of a cleaner for properties found on a basic block.
#include <otawa/proc/BBProcessor.h>
Public Member Functions
BBCleaner (WorkSpace *_ws)
virtual void clean (void)
Protected Member Functions
virtual void clean (WorkSpace *ws, CFG *cfg, BasicBlock *bb)=0
Private Attributes
WorkSpace * ws
Detailed Description
Efficient implementation of a cleaner for properties found on a basic block.
Basic block cleaner simply removing an identifier from basic blocks.
To instantiate it, juste overload the process() methods
Parameters
T Type of property value.
Constructor & Destructor Documentation
otawa::BBCleaner::BBCleaner (WorkSpace * _ws) inline
References otawa::cfgio::bb(), and otawa::cfgio::cfg().
Member Function Documentation
void otawa::BBCleaner::clean (void) virtual
References otawa::cfgio::bb(), otawa::CFGProcessor::cfg(), otawa::INVOLVED_CFGS, and otawa::Processor::ws.
Referenced by otawa::BBDeletor< T >::clean().
virtual void otawa::BBCleaner::clean (WorkSpace * ws, CFG * cfg, BasicBlock * bb) protected pure virtual
Implemented in otawa::BBDeletor< T >, and otawa::BBRemover< T >.
Member Data Documentation
WorkSpace* otawa::BBCleaner::ws private
The documentation for this class was generated from the following files:
include/otawa/proc/BBProcessor.h
src/prog/proc_BBProcessor.cpp