Otawa: otawa::clp::Value Class Reference
otawa::clp::Value Class Reference
CLP Analysis
A set of values represented by a Circular Linear Progression.
#include <otawa/data/clp/ClpValue.h>
Public Member Functions
bool isConst (void) const
Value (kind_t kind=VAL, intn_t lower=0, intn_t delta=0, uintn_t mtimes=0)
Constructor for a new CLP.
Value (const Value &val)
Copy constructor.
Value (const int val)
Singleton constructor.
Value & operator= (const Value &val)
bool isTop (void) const
bool operator== (const Value &val) const
bool operator!= (const Value &val) const
Value operator+ (const Value &val) const
Value operator- (const Value &val) const
bool operator>= (const int val) const
kind_t kind (void) const
intn_t lower (void) const
intn_t upper (void) const
intn_t delta (void) const
uintn_t mtimes (void) const
bool isInf (void) const
bool direction (void) const
void PQValue (Value &p, Value &q)
Forms two CLP values which are the components of [base value, the value just before overflow] and [the value just after overflow, upper bound of this part].
intn_t start (void) const
intn_t stop (void) const
void add (const Value &val)
Add another set to the current one.
void sub (const Value &val)
Subtract anothe set to the current one.
void print (io::Output &out) const
Print a human representation of the CLP.
void shl (const Value &val)
Left shift the current value.
void shr (const Value &val)
Right shift the current value.
void _or (const Value &val)
Perform OR operator on values (modifying current one).
Value & join (const Value &val)
Join another set to the current one.
void widening (const Value &val)
Perform a widening to the infinite (to be filtred later)
void ffwidening (const Value &val, int loopBound)
Perform a widening, knowing flow facts for the loop.
Value & inter (const Value &val)
Intersection with the current value.
void reverse (void)
Reverse the CLP direction (swap upper and lower bounds, and use the opposite of delta as new delta).
bool swrap (void) const
bool uwrap (void) const
void ge (intn_t k)
Filter the current value with signed values greater than k.
void geu (uintn_t k)
Filter the current value with unsigned values greater than k.
void le (intn_t k)
Filter the current value with signed values lesser than k.
void leu (uintn_t k)
Filter the current value with unsigned values lesser than k.
void eq (uintn_t k)
void ne (uintn_t k)
void _and (const Value &val)
Perform AND on the current value.
void set (kind_t kind, intn_t lower, intn_t delta, uintn_t mtimes)
Set the values for the current object.
Static Public Attributes
static int and_threshold = 8
Find a file of 1 in a word.
static const Value none
Represents the bottom element.
static const Value bot
static const Value all
Represents the top element.
static const Value top
Private Member Functions
void check (void)
Private Attributes
kind_t _kind
intn_t _base
intn_t _delta
uintn_t _mtimes
Detailed Description
A set of values represented by a Circular Linear Progression.
Represents a CLP value.
Values are defined by a 3-tuple (lower, delta, mtimes) for 32bits numbers. A constant integer k is represented by (k, 0, 0) The Top element is represented by (0, 1, 2^32 - 1)
Constructor & Destructor Documentation
otawa::clp::Value::Value (kind_t kind = VAL, intn_t lower = 0, intn_t delta = 0, uintn_t mtimes = 0) inline
Constructor for a new CLP.
Parameters
kind the kind of the CLP
lower the lower bound
delta the delta
mtimes the number of time the delta is applied
otawa::clp::Value::Value (const Value & val) inline
Copy constructor.
otawa::clp::Value::Value (const int val) inline
Singleton constructor.
Parameters
val the single integer element of the CLP
Returns
the CLP (val, 0, 0)
Member Function Documentation
void otawa::clp::Value::_and (const Value & val)
Perform AND on the current value.
Parameters
val Value to perform AND on.
References otawa::clp::ALL, delta(), isConst(), lower(), mtimes(), otawa::clp::NONE, otawa::clp::UMAXn, and otawa::clp::VAL.
void otawa::clp::Value::_or (const Value & val)
Perform OR operator on values (modifying current one).
Parameters
val The value to OR with the current one.
References _base, otawa::clp::ALL, isConst(), kind(), and otawa::clp::NONE.
Referenced by otawa::clp::operator<<().
void otawa::clp::Value::add (const Value & val)
Add another set to the current one.
Parameters
val the value to add
References _base, _delta, _kind, _mtimes, otawa::clp::ALL, direction(), isInf(), otawa::clp::NONE, reverse(), otawa::se::reverse(), otawa::clp::UMAXn, and otawa::clp::VAL.
Referenced by operator+(), and otawa::clp::operator<<().
void otawa::clp::Value::check (void) inline private
intn_t otawa::clp::Value::delta (void) const inline
Referenced by _and(), otawa::se::SEConst::asString(), otawa::se::SEAddr::asString(), otawa::clp::operator<<(), and widening().
bool otawa::clp::Value::direction (void) const inline
References delta().
Referenced by add(), and inter().
void otawa::clp::Value::eq (uintn_t k)
void otawa::clp::Value::ffwidening (const Value & val, int loopBound)
Perform a widening, knowing flow facts for the loop.
Parameters
val the value of the next iteration state
loopBound the maximum number of iteration of the loop
References _base, _delta, _kind, _mtimes, otawa::clp::ALL, isConst(), otawa::clp::NONE, otawa::clp::UMAXn, and otawa::clp::VAL.
Referenced by otawa::clp::State::widening().
void otawa::clp::Value::ge (intn_t k)
Filter the current value with signed values greater than k.
Parameters
k Threshold.
References otawa::clp::MAXn, and otawa::clp::VAL.
Referenced by otawa::se::applyFilter().
void otawa::clp::Value::geu (uintn_t k)
Filter the current value with unsigned values greater than k.
Parameters
k Threshold.
References otawa::clp::UMAXn, and otawa::clp::VAL.
Referenced by otawa::se::applyFilter().
Value & otawa::clp::Value::inter (const Value & val)
Intersection with the current value.
Parameters
val the value to do the intersection with
References _base, _delta, _mtimes, direction(), inter(), isConst(), isTop(), join(), otawa::clp::lcm(), otawa::clp::min(), otawa::clp::NONE, PQValue(), reverse(), TRACE_INTERSECT, and otawa::clp::VAL.
Referenced by otawa::se::applyFilter(), and inter().
bool otawa::clp::Value::isConst (void) const inline
References delta().
Referenced by _and(), _or(), otawa::se::SEConst::asString(), otawa::se::SEAddr::asString(), otawa::se::SEReg::asString(), ffwidening(), otawa::clp::State::get(), otawa::se::getFilterForAddr(), otawa::se::getFilterForReg(), inter(), join(), otawa::se::FilterBuilder::makeFilters(), otawa::clp::operator<<(), otawa::clp::State::set(), shl(), shr(), and widening().
bool otawa::clp::Value::isInf (void) const inline
Referenced by add().
bool otawa::clp::Value::isTop (void) const inline
References otawa::clp::ALL.
Referenced by inter(), and otawa::clp::Analysis::processWorkSpace().
Value & otawa::clp::Value::join (const Value & val)
Join another set to the current one.
Parameters
val the value to be joined with
References _base, _delta, _kind, _mtimes, otawa::clp::ALL, isConst(), otawa::clp::min(), otawa::clp::NONE, start(), otawa::clp::umax(), otawa::clp::UMAXn, and otawa::clp::VAL.
Referenced by inter(), otawa::clp::State::join(), and otawa::dcache::CLPBlockBuilder::processBB().
kind_t otawa::clp::Value::kind (void) const inline
Referenced by _or(), otawa::se::SEConst::asString(), otawa::clp::State::equals(), otawa::clp::State::get(), otawa::clp::operator<<(), otawa::clp::State::print(), and otawa::clp::State::set().
void otawa::clp::Value::le (intn_t k)
Filter the current value with signed values lesser than k.
Parameters
k Threshold.
References otawa::clp::MAXn, and otawa::clp::MINn.
Referenced by otawa::se::applyFilter().
void otawa::clp::Value::leu (uintn_t k)
Filter the current value with unsigned values lesser than k.
Parameters
k Threshold.
References otawa::clp::VAL.
Referenced by otawa::se::applyFilter().
intn_t otawa::clp::Value::lower (void) const inline
Referenced by _and(), otawa::se::SEConst::asString(), otawa::se::SEAddr::asString(), otawa::se::SEReg::asString(), otawa::clp::State::get(), otawa::se::getFilterForReg(), otawa::se::FilterBuilder::makeFilters(), otawa::clp::operator<<(), and otawa::clp::State::set().
uintn_t otawa::clp::Value::mtimes (void) const inline
Referenced by _and(), otawa::se::SEConst::asString(), otawa::se::SEAddr::asString(), and otawa::clp::operator<<().
void otawa::clp::Value::ne (uintn_t k)
bool otawa::clp::Value::operator!= (const Value & val) const inline
References otawa::ilp::operator+(), and otawa::ilp::operator-().
Value otawa::clp::Value::operator+ (const Value & val) const
References add().
Value otawa::clp::Value::operator- (const Value & val) const
References sub().
Value& otawa::clp::Value::operator= (const Value & val) inline
References _base, _delta, _kind, and _mtimes.
bool otawa::clp::Value::operator== (const Value & val) const inline
References _base, _delta, _kind, and _mtimes.
bool otawa::clp::Value::operator>= (const int val) const inline
void otawa::clp::Value::PQValue (Value & p, Value & q)
Forms two CLP values which are the components of [base value, the value just before overflow] and [the value just after overflow, upper bound of this part].
Refer to the beginning of the section 6 of [Sen et Srikant, 2007].
Parameters
p the CLP value contains [base value, the value just before overflow]
q the CLP value contains [the value just after overflow, upper bound of this part]
References otawa::clp::MAXn, otawa::clp::MINn, set(), and otawa::clp::VAL.
Referenced by inter().
void otawa::clp::Value::print (io::Output & out) const
Print a human representation of the CLP.
Parameters
out the stream to output the representation
References otawa::clp::ALL, and otawa::clp::NONE.
Referenced by otawa::clp::operator<<().
void otawa::clp::Value::reverse (void)
Reverse the CLP direction (swap upper and lower bounds, and use the opposite of delta as new delta).
References otawa::clp::VAL.
Referenced by add(), and inter().
void otawa::clp::Value::set (kind_t kind, intn_t lower, intn_t delta, uintn_t mtimes) inline
Set the values for the current object.
Parameters
kind the kind of the object
lower the lower bound of the CLP
delta the step of the CLP
mtimes the number of times delta need to be added to get the max bound of the CLP
References delta(), and kind.
Referenced by PQValue().
void otawa::clp::Value::shl (const Value & val)
Left shift the current value.
Parameters
val the value to shift the current one with. Must be a positive constant.
References _base, otawa::clp::ALL, isConst(), otawa::clp::NONE, otawa::clp::UMAXn, and otawa::clp::VAL.
Referenced by otawa::clp::operator<<().
void otawa::clp::Value::shr (const Value & val)
Right shift the current value.
Parameters
val the value to shift the current one with. Must be a positive constant.
References _base, otawa::clp::ALL, isConst(), otawa::clp::NONE, otawa::clp::UMAXn, and otawa::clp::VAL.
Referenced by otawa::clp::operator<<().
intn_t otawa::clp::Value::start (void) const inline
Returns
the "start" of the CLP, i.e. the lower bound if delta >= 0, lower + delta * mtimes else.
Referenced by otawa::se::applyFilter(), join(), otawa::clp::operator<<(), and widening().
intn_t otawa::clp::Value::stop (void) const inline
Returns
the "stop" of the CLP, i.e. the upper bound if delta >= 0, lower else.
References otawa::sem::_or(), otawa::sem::add(), otawa::se::reverse(), otawa::sem::shl(), otawa::sem::shr(), and otawa::sem::sub().
Referenced by otawa::se::applyFilter(), and widening().
void otawa::clp::Value::sub (const Value & val)
Subtract anothe set to the current one.
Subtract another set to the current one.
Parameters
val the value to subtract
References _base, _delta, _kind, otawa::sem::add(), otawa::clp::ALL, and otawa::clp::NONE.
Referenced by operator-(), and otawa::clp::operator<<().
bool otawa::clp::Value::swrap (void) const inline
Referenced by otawa::se::applyFilter().
intn_t otawa::clp::Value::upper (void) const inline
bool otawa::clp::Value::uwrap (void) const inline
References otawa::sem::_and().
Referenced by otawa::se::applyFilter().
void otawa::clp::Value::widening (const Value & val)
Perform a widening to the infinite (to be filtred later)
Parameters
val the value of the next iteration state
References _base, _kind, otawa::clp::ALL, delta(), isConst(), otawa::clp::NONE, start(), stop(), and otawa::clp::UMAXn.
Member Data Documentation
intn_t otawa::clp::Value::_base private
Referenced by _or(), add(), ffwidening(), inter(), join(), operator=(), operator==(), shl(), shr(), sub(), and widening().
intn_t otawa::clp::Value::_delta private
Referenced by add(), ffwidening(), inter(), join(), operator=(), operator==(), and sub().
kind_t otawa::clp::Value::_kind private
Referenced by add(), ffwidening(), join(), operator=(), operator==(), sub(), and widening().
uintn_t otawa::clp::Value::_mtimes private
Referenced by add(), ffwidening(), inter(), join(), operator=(), and operator==().
const Value otawa::clp::Value::all static
Represents the top element.
Referenced by otawa::se::FilterBuilder::makeFilters(), and otawa::dcache::CLPBlockBuilder::processBB().
int otawa::clp::Value::and_threshold = 8 static
Find a file of 1 in a word.
Parameters
w Word to process.
n Number of bits to one.
Returns
True if one is found, false else. Threshold giving the maximum size of a CLP set to apply AND explicitly on the whole set (and rebuilding a new CLP value).
const Value otawa::clp::Value::bot static
const Value otawa::clp::Value::none static
Represents the bottom element.
Referenced by otawa::dcache::CLPBlockBuilder::processBB().
const Value otawa::clp::Value::top static
The documentation for this class was generated from the following files:
include/otawa/data/clp/ClpValue.h
src/prog/clp_analysis.cpp