Otawa: otawa::Application Class Reference
otawa::Application Class Reference
Application Writing
A class making easier the use of applications built on OTAWA.
#include <otawa/app/Application.h>
Public Member Functions
Application (cstring _program, Version _version=Version::ZERO, cstring _description="", cstring _author="", cstring _copyright="")
Build the application.
virtual ~Application (void)
int run (int argc, char **argv)
Run the application:
Protected Member Functions
virtual void prepare (PropList &props)
This method may be overriden by the child class in order to customize the building of configuration property list.
virtual void work (PropList &props) throw (elm::Exception)
This method must be overriden to implement the action of the application.
virtual void work (const string &entry, PropList &props) throw (elm::Exception)
This method must be overriden to give a special behaviour for each free argument of the command line (supposed to be the tasks entry points).
WorkSpace * workspace (void) const
Provide the current workspace.
void require (const AbstractFeature &feature)
Perform a require request on the current process with the current configuration property list (as configured in prepare()).
virtual void process (string arg)
If overriden, this method allows to provide a customized behaviour to the usual processing of free arguments.
bool isVerbose (void) const
const genstruct::Vector< string > arguments (void) const
Address parseAddress (const string &s) throw (otawa::Exception)
Parse a symbolic address and return it.
Private Attributes
option::BoolOption help
option::BoolOption verbose
option::ListOption< string > sets
option::ListOption< string > params
option::ListOption< string > ff
LogOption log_level
elm::system::Path path
genstruct::Vector< string > _args
PropList props
PropList * props2
int result
WorkSpace * ws
Detailed Description
A class making easier the use of applications built on OTAWA.
It automatically support for
–add-prop ID=VALUE – set a configuration property (passed to manager and other processors),
-f|–flowfacts PATH – select a flow fact file to load
-h|–help – option help display,
–load-param ID=VALUE – add a load parameter (passed to the manager load command)
-v|–verbose – verbose mode activation,
first argument as binary program,
following arguments as task entries.
Usually, it specialized according your application purpose:
#include <otawa/app/Application.h>
class MyApp: public Application {
public:
        MyApplication(void):
                        Application("my_application", ...),
                        option1(*this, ...),
                        option2(*this, ...)
                {
                        ...
                }
protected:
void work(PropList &props) throw(elm::Exception) {
                        // do_something useful on the opened workspace
                }
private:
                MyOption1 option1;
                MyOption2 option2;
                ...
};
OTAWA_RUN(MyApp)
Constructor & Destructor Documentation
otawa::Application::Application (cstring _program, Version _version = Version::ZERO, cstring _description = "", cstring _author = "", cstring _copyright = "")
Build the application.
Parameters
_program Program name.
_version Current version (optional).
_description Description of the application (optional).
_author Author identification.
_copyright Applied copyright.
otawa::Application::~Application (void) virtual
Member Function Documentation
const genstruct::Vector<string> otawa::Application::arguments (void) const inline protected
bool otawa::Application::isVerbose (void) const inline protected
References verbose().
Address otawa::Application::parseAddress (const string & s) throw (otawa::Exception) protected
Parse a symbolic address and return it.
Parameters
s Address string to parse.
Returns
Matching address.
Exceptions
otawa::Exception If the address cannot be resolved or parsed.
References otawa::SymAddress::parse(), otawa::SymAddress::toAddress(), and ws.
Referenced by work().
void otawa::Application::prepare (PropList & props) protected virtual
This method may be overriden by the child class in order to customize the building of configuration property list.
Parameters
props Property list to customize.
Referenced by run().
void otawa::Application::process (string arg) protected virtual
If overriden, this method allows to provide a customized behaviour to the usual processing of free arguments.
Parameters
arg Current argument.
References _args, and path.
void otawa::Application::require (const AbstractFeature & feature) protected
Perform a require request on the current process with the current configuration property list (as configured in prepare()).
Parameters
feature Feature to require.
References props2, otawa::WorkSpace::require(), and ws.
int otawa::Application::run (int argc, char ** argv)
Run the application:
scan the options from argc and argv,
open the workspace,
call the work() method.
Parameters
argc Argument count as passed to main().
argv Argument list as passed to main().
Returns
A return code adapted to the current OS.
References _args, otawa::Identifier< T >::add(), ff, otawa::AbstractIdentifier::find(), otawa::FLOW_FACTS_PATH, otawa::ProcessorPlugin::getIdentifier(), help, otawa::Manager::load(), otawa::LOAD_PARAM, log_level, otawa::Processor::LOG_LEVEL, otawa::MANAGER, name, params, path, prepare(), props, result, sets, verbose, otawa::Processor::VERBOSE, work(), and ws.
void otawa::Application::work (PropList & props) throw (elm::Exception) protected virtual
This method must be overriden to implement the action of the application.
As a default, it call the work(string, props) method for each free argument on a command line (supposed to be a task entry).
When this method is called, the program has been already loaded.
Exceptions
elm::Exception For any found error.
References _args, parseAddress(), props, props2, and otawa::TASK_ADDRESS.
Referenced by run().
void otawa::Application::work (const string & entry, PropList & props) throw (elm::Exception) protected virtual
This method must be overriden to give a special behaviour for each free argument of the command line (supposed to be the tasks entry points).
As a default, do nothing.
When this method is called, the program has already been loaded and the workspace is marked as having as entry point the one passed in argument: threfore the workspace is ready for computation.
Parameters
entry Task entry point name or any free argument.
Exceptions
elm::Exception For any found error.
WorkSpace * otawa::Application::workspace (void) const inline protected
Provide the current workspace.
Returns
Current workspace.
References otawa::p::require.
Member Data Documentation
genstruct::Vector<string> otawa::Application::_args private
Referenced by process(), run(), and work().
option::ListOption<string> otawa::Application::ff private
Referenced by run().
option::BoolOption otawa::Application::help private
Referenced by run().
LogOption otawa::Application::log_level private
Referenced by run().
option::ListOption<string> otawa::Application::params private
Referenced by run().
elm::system::Path otawa::Application::path private
Referenced by process(), and run().
PropList otawa::Application::props private
Referenced by run(), and work().
PropList* otawa::Application::props2 private
Referenced by require(), and work().
int otawa::Application::result private
Referenced by run().
option::ListOption<string> otawa::Application::sets private
Referenced by run().
option::BoolOption otawa::Application::verbose private
Referenced by run().
WorkSpace* otawa::Application::ws private
Referenced by parseAddress(), require(), and run().
The documentation for this class was generated from the following files:
include/otawa/app/Application.h
src/prog/app_Application.cpp