Otawa: otawa::MUSTProblem::Domain Class Reference
otawa::MUSTProblem::Domain Class Reference
#include <otawa/cache/cat2/MUSTProblem.h>
Public Member Functions
Domain (const int _size, const int _A)
~Domain ()
Domain (const Domain &source)
Domain & operator= (const Domain &src)
void glb (const Domain &dom)
void lub (const Domain &dom)
int getSize (void)
void addDamage (const int id, const int damage)
bool equals (const Domain &dom) const
void empty ()
bool contains (const int id)
void inject (const int id)
void print (elm::io::Output &output) const
int getAge (int id) const
void setAge (const int id, const int _age)
Public Attributes
int * age
Private Attributes
int A
int size
Constructor & Destructor Documentation
otawa::MUSTProblem::Domain::Domain (const int _size, const int _A) inline
References age, and size.
otawa::MUSTProblem::Domain::~Domain () inline
References age.
otawa::MUSTProblem::Domain::Domain (const Domain & source) inline
References age, and size.
Member Function Documentation
void otawa::MUSTProblem::Domain::addDamage (const int id, const int damage) inline
References age.
bool otawa::MUSTProblem::Domain::contains (const int id) inline
References age.
Referenced by otawa::PERSProblem::Item::inject(), inject(), otawa::MUSTPERS::Domain::mustContains(), otawa::EdgeCAT2Builder::processLBlockSet(), and otawa::CAT2Builder::processLBlockSet().
void otawa::MUSTProblem::Domain::empty () inline
References age, and size.
Referenced by otawa::MUSTPERS::Domain::empty(), and otawa::MUSTProblem::MUSTProblem().
bool otawa::MUSTProblem::Domain::equals (const Domain & dom) const inline
References A, age, and size.
Referenced by otawa::MUSTPERS::Domain::equals(), and otawa::MUSTProblem::equals().
int otawa::MUSTProblem::Domain::getAge (int id) const inline
References age.
int otawa::MUSTProblem::Domain::getSize (void) inline
References size.
Referenced by otawa::MUSTPERS::Domain::getSize().
void otawa::MUSTProblem::Domain::glb (const Domain & dom) inline
References A, age, and size.
void otawa::MUSTProblem::Domain::inject (const int id) inline
References age, contains(), and size.
Referenced by otawa::MUSTPERS::Domain::inject(), and otawa::MUSTProblem::update().
void otawa::MUSTProblem::Domain::lub (const Domain & dom) inline
References A, age, and size.
Referenced by otawa::MUSTPERS::Domain::lub(), and otawa::MUSTProblem::lub().
Domain& otawa::MUSTProblem::Domain::operator= (const Domain & src) inline
References A, age, and size.
void otawa::MUSTProblem::Domain::print (elm::io::Output & output) const inline
References age, and size.
Referenced by otawa::operator<<(), and otawa::MUSTPERS::Domain::print().
void otawa::MUSTProblem::Domain::setAge (const int id, const int _age) inline
References age.
Member Data Documentation
int otawa::MUSTProblem::Domain::A private
Referenced by equals(), glb(), lub(), and operator=().
int* otawa::MUSTProblem::Domain::age
Referenced by addDamage(), contains(), Domain(), empty(), equals(), getAge(), glb(), inject(), lub(), operator=(), print(), setAge(), and ~Domain().
int otawa::MUSTProblem::Domain::size private
Referenced by Domain(), empty(), equals(), getSize(), glb(), inject(), lub(), operator=(), and print().
The documentation for this class was generated from the following file:
include/otawa/cache/cat2/MUSTProblem.h