Otawa: otawa::dfa::State Class Reference
otawa::dfa::State Class Reference
Represents a value of the data state.
#include <otawa/dfa/State.h>
Classes
class MemIter
class RegIter
Public Types
typedef t::uint32 address_t
Public Member Functions
State (Process &process)
Build the initial state.
Process & process (void) const
void set (const hard::Register *reg, Value value)
Set the value of a register.
Value get (const hard::Register *reg) const
Get a register value.
void record (const MemCell &cell)
Record a configured memory item.
bool isInitialized (Address addr) const
Test if the current state contains initialized data.
void get (const Address &a, t::uint8 &v) const
Get a value from the initialized memory of the process.
void get (const Address &a, t::uint16 &v) const
Get a value from the initialized memory of the process.
void get (const Address &a, t::uint32 &v) const
Get a value from the initialized memory of the process.
void get (const Address &a, t::uint64 &v) const
Get a value from the initialized memory of the process.
void get (const Address &a, float &v) const
Get a value from the initialized memory of the process.
void get (const Address &a, double &v) const
Get a value from the initialized memory of the process.
void get (const Address &a, Address &v) const
Get a value from the initialized memory of the process.
Private Types
typedef avl::Map< const hard::Register *, Value > reg_map_t
typedef avl::Map< Address, MemCell > mem_map_t
Private Attributes
reg_map_t regs
stree::Tree< address_t, bool > mem
mem_map_t cmem
Process & proc
Detailed Description
Represents a value of the data state.
Data flow state.
Often used to describe the initial state as the join of the user external information on data state and from the initialized data state from the executable content.
Member Typedef Documentation
typedef t::uint32 otawa::dfa::State::address_t
typedef avl::Map<Address, MemCell> otawa::dfa::State::mem_map_t private
typedef avl::Map<const hard::Register *, Value> otawa::dfa::State::reg_map_t private
Constructor & Destructor Documentation
otawa::dfa::State::State (Process & process)
Build the initial state.
Parameters
process Current process.
References mem, and proc.
Referenced by record().
Member Function Documentation
Value otawa::dfa::State::get (const hard::Register * reg) const
Get a register value.
Parameters
reg Register to look for.
Returns
Found value or None value.
References regs.
void otawa::dfa::State::get (const Address & a, t::uint8 & v) const inline
Get a value from the initialized memory of the process.
Parameters
a Address to get value from.
v Returned value.
Warning
This function must only be called on an initialized address. Else unexpected result may arise.
References proc().
void otawa::dfa::State::get (const Address & a, t::uint16 & v) const inline
Get a value from the initialized memory of the process.
Parameters
a Address to get value from.
v Returned value.
Warning
This function must only be called on an initialized address. Else unexpected result may arise.
References proc().
void otawa::dfa::State::get (const Address & a, t::uint32 & v) const inline
Get a value from the initialized memory of the process.
Parameters
a Address to get value from.
v Returned value.
Warning
This function must only be called on an initialized address. Else unexpected result may arise.
References proc().
void otawa::dfa::State::get (const Address & a, t::uint64 & v) const inline
Get a value from the initialized memory of the process.
Parameters
a Address to get value from.
v Returned value.
Warning
This function must only be called on an initialized address. Else unexpected result may arise.
References proc().
void otawa::dfa::State::get (const Address & a, float & v) const inline
Get a value from the initialized memory of the process.
Parameters
a Address to get value from.
v Returned value.
Warning
This function must only be called on an initialized address. Else unexpected result may arise.
References proc().
void otawa::dfa::State::get (const Address & a, double & v) const inline
Get a value from the initialized memory of the process.
Parameters
a Address to get value from.
v Returned value.
Warning
This function must only be called on an initialized address. Else unexpected result may arise.
References proc().
void otawa::dfa::State::get (const Address & a, Address & v) const inline
Get a value from the initialized memory of the process.
Parameters
a Address to get value from.
v Returned value.
Warning
This function must only be called on an initialized address. Else unexpected result may arise.
References proc().
bool otawa::dfa::State::isInitialized (Address addr) const inline
Test if the current state contains initialized data.
Parameters
addr Address to test.
Returns
True if the data is initialized, false else.
References otawa::Address::offset().
Process& otawa::dfa::State::process (void) const inline
References proc().
void otawa::dfa::State::record (const MemCell & cell)
Record a configured memory item.
Parameters
cell Memory cell description to record.
References otawa::dfa::MemCell::address(), cmem, otawa::Processor::configure(), otawa::dfa::INITIAL_STATE, otawa::dfa::INITIAL_STATE_FEATURE, otawa::p::init::maker(), otawa::dfa::MEM_INIT, otawa::WorkSpace::process(), otawa::p::provide, record(), otawa::dfa::REG_INIT, set(), and State().
Referenced by otawa::FlowFactLoader::onMemSet(), and record().
void otawa::dfa::State::set (const hard::Register * reg, Value val)
Set the value of a register.
Parameters
reg Set register.
val Set value.
References regs.
Referenced by otawa::FlowFactLoader::onRegSet(), and record().
Member Data Documentation
mem_map_t otawa::dfa::State::cmem private
Referenced by record().
stree::Tree<address_t, bool> otawa::dfa::State::mem private
Referenced by State().
Process& otawa::dfa::State::proc private
Referenced by State().
reg_map_t otawa::dfa::State::regs private
Referenced by get(), and set().
The documentation for this class was generated from the following files:
include/otawa/dfa/State.h
src/prog/dfa_State.cpp