Otawa: otawa::SPAddress Class Reference
otawa::SPAddress Class Reference
Memory Accesses
Subclass of AccessedAddress, this class represents address with a constant offset relative to the stack pointer.
#include <otawa/stack/AccessedAddress.h>
Public Types
enum kind_t { ANY, SP, ABS }
Describe the different implementation of an accessed address.
Public Member Functions
SPAddress (Inst *instruction, bool is_store, t::int32 offset)
t::int32 offset (void) const
kind_t kind (void) const
Get the kind of the address.
bool isStore (void) const
Test if a store is performed on the accessed address.
bool isLoad (void) const
Test if a store is performed on the accessed address.
Inst * instruction (void) const
Get the instruction where this memory access applies.
void print (io::Output &out) const
Print the given address.
Private Attributes
t::int32 off
Detailed Description
Subclass of AccessedAddress, this class represents address with a constant offset relative to the stack pointer.
Any accessed address of kind AccessedAddress::SP can be cast in this class.
Member Enumeration Documentation
enum otawa::AccessedAddress::kind_t inherited
Describe the different implementation of an accessed address.
Enumerator
ANY
Represents the most imprecise memory access: it may potentially concern the full memory address space.
SP
Represents an stack pointer relative address with a constant offset.
Instances of this kind can be casted into SPAddress.
ABS
Represents an address defined by its absolute and constant value.
Instances of this kind can be casted into AbsAddress.
Constructor & Destructor Documentation
otawa::SPAddress::SPAddress (Inst * instruction, bool is_store, t::int32 offset) inline
Member Function Documentation
Inst * otawa::AccessedAddress::instruction (void) const inline inherited
Get the instruction where this memory access applies.
Returns
Instruction accessing the memory.
Referenced by otawa::dcache::BlockBuilder::processBB().
bool otawa::AccessedAddress::isLoad (void) const inline inherited
Test if a store is performed on the accessed address.
Returns
True if it is a store.
References otawa::sem::store().
bool otawa::AccessedAddress::isStore (void) const inline inherited
Test if a store is performed on the accessed address.
Returns
True if it is a store.
References otawa::sem::store().
Referenced by otawa::dcache::BlockBuilder::processBB().
AccessedAddress::kind_t otawa::AccessedAddress::kind (void) const inline inherited
Get the kind of the address.
According to this kind, this instance may be cast in the corresponding subclass of AccessedAddress.
Returns
Kind of address.
Referenced by otawa::dcache::BlockBuilder::processBB().
t::int32 otawa::SPAddress::offset (void) const inline
Referenced by otawa::AccessedAddress::print().
void otawa::AccessedAddress::print (io::Output & out) const inherited
Print the given address.
Parameters
out Output stream.
References otawa::AccessedAddress::ABS, otawa::ProgItem::address(), otawa::ot::address(), otawa::ADDRESS_ANALYSIS_FEATURE, otawa::ADDRESS_STATS, otawa::ADDRESSES, otawa::AccessedAddress::ANY, otawa::AccessedAddress::inst, otawa::AccessedAddress::knd, offset(), otawa::sign(), otawa::AccessedAddress::SP, and otawa::AccessedAddress::store.
Referenced by otawa::operator<<().
Member Data Documentation
t::int32 otawa::SPAddress::off private
The documentation for this class was generated from the following file:
include/otawa/stack/AccessedAddress.h