Otawa: otawa::MUSTProblem Class Reference
otawa::MUSTProblem Class Reference
#include <otawa/cache/cat2/MUSTProblem.h>
Classes
class Domain
Public Member Functions
MUSTProblem (const int _size, LBlockSet *_lbset, WorkSpace *_fw, const hard::Cache *_cache, const int _A)
~MUSTProblem ()
const Domain & bottom (void) const
const Domain & entry (void) const
void lub (Domain &a, const Domain &b) const
void assign (Domain &a, const Domain &b) const
bool equals (const Domain &a, const Domain &b) const
void update (Domain &out, const Domain &in, BasicBlock *bb)
void enterContext (Domain &dom, BasicBlock *header, hai_context_t ctx)
void leaveContext (Domain &dom, BasicBlock *header, hai_context_t ctx)
Public Attributes
Domain callstate
Private Attributes
LBlockSet * lbset
WorkSpace * fw
const int line
const hard::Cache * cache
Domain bot
Domain ent
Constructor & Destructor Documentation
MUSTProblem::MUSTProblem (const int _size, LBlockSet * _lbset, WorkSpace * _fw, const hard::Cache * _cache, const int _A)
References otawa::MUSTProblem::Domain::empty(), and ent.
MUSTProblem::~MUSTProblem ()
Member Function Documentation
void otawa::MUSTProblem::assign (Domain & a, const Domain & b) const inline
Referenced by otawa::MUSTPERS::MUSTPERS(), and update().
const MUSTProblem::Domain & MUSTProblem::bottom (void) const
References bot.
Referenced by otawa::MUSTPERS::MUSTPERS().
void otawa::MUSTProblem::enterContext (Domain & dom, BasicBlock * header, hai_context_t ctx) inline
Referenced by otawa::MUSTPERS::enterContext().
const MUSTProblem::Domain & MUSTProblem::entry (void) const
References ent.
Referenced by otawa::MUSTPERS::MUSTPERS().
bool otawa::MUSTProblem::equals (const Domain & a, const Domain & b) const inline
References otawa::cfgio::bb(), otawa::MUSTProblem::Domain::equals(), and update().
void otawa::MUSTProblem::leaveContext (Domain & dom, BasicBlock * header, hai_context_t ctx) inline
References otawa::operator<<().
Referenced by otawa::MUSTPERS::leaveContext().
void otawa::MUSTProblem::lub (Domain & a, const Domain & b) const inline
References otawa::MUSTProblem::Domain::lub().
void MUSTProblem::update (Domain & out, const Domain & in, BasicBlock * bb)
References assign(), otawa::LBlock::cacheblock(), otawa::MUSTProblem::Domain::inject(), otawa::LAST_LBLOCK, and line.
Referenced by equals().
Member Data Documentation
Domain otawa::MUSTProblem::bot private
Referenced by bottom().
const hard::Cache* otawa::MUSTProblem::cache private
Domain otawa::MUSTProblem::callstate
Domain otawa::MUSTProblem::ent private
Referenced by entry(), and MUSTProblem().
WorkSpace* otawa::MUSTProblem::fw private
LBlockSet* otawa::MUSTProblem::lbset private
const int otawa::MUSTProblem::line private
Referenced by update().
The documentation for this class was generated from the following files:
include/otawa/cache/cat2/MUSTProblem.h
src/prog/cache_MUSTProblem.cpp