Otawa: otawa::ContextualPath::Ref< T > Class Template Reference
otawa::ContextualPath::Ref< T > Class Template Reference
#include <otawa/prop/ContextualProperty.h>
Public Member Functions
Ref (const ContextualPath &_cp, PropList &_p, const Identifier< T > &_i)
Ref (const Ref< T > &r)
Ref< T > & operator= (const Ref< T > &r)
const ContextualPath & path (void) const
const PropList & proplist (void) const
const Identifier< T > & identifier (void) const
bool exists (void) const
const T & get (void) const
operator const T & (void) const
T operator-> (void) const
void print (io::Output &out)
const Ref & add (const T &value) const
void remove (void) const
T & ref (void) const
T & operator& (void) const
const Ref< T > & operator= (const T &value) const
Ref< T > & operator+= (const T &v) const
Ref< T > & operator-= (const T &v) const
Ref< T > & operator*= (const T &v) const
Ref< T > & operator/= (const T &v) const
Ref< T > & operator%= (const T &v) const
Ref< T > & operator&= (const T &v) const
Ref< T > & operator|= (const T &v) const
Ref< T > & operator^= (const T &v) const
Ref< T > & operator<<= (const T &v) const
Ref< T > & operator>>= (const T &v) const
Ref< T > & operator++ (void) const
Ref< T > & operator-- (void) const
Ref< T > & operator++ (int) const
Ref< T > & operator-- (int) const
Private Attributes
const ContextualPath & cp
PropList & p
const Identifier< T > & i
Constructor & Destructor Documentation
template<class T> otawa::ContextualPath::Ref< T >::Ref (const ContextualPath & _cp, PropList & _p, const Identifier< T > & _i) inline
template<class T> otawa::ContextualPath::Ref< T >::Ref (const Ref< T > & r) inline
Member Function Documentation
template<class T> const Ref& otawa::ContextualPath::Ref< T >::add (const T & value) const inline
References otawa::ContextualPath::Ref< T >::add(), and otawa::ContextualProperty::make().
Referenced by otawa::ContextualPath::Ref< T >::add().
template<class T> bool otawa::ContextualPath::Ref< T >::exists (void) const inline
References otawa::ContextualProperty::exists().
template<class T> const T& otawa::ContextualPath::Ref< T >::get (void) const inline
template<class T> const Identifier<T>& otawa::ContextualPath::Ref< T >::identifier (void) const inline
template<class T> otawa::ContextualPath::Ref< T >::operator const T & (void) const inline
template<class T> Ref<T>& otawa::ContextualPath::Ref< T >::operator%= (const T & v) const inline
template<class T> T& otawa::ContextualPath::Ref< T >::operator& (void) const inline
template<class T> Ref<T>& otawa::ContextualPath::Ref< T >::operator&= (const T & v) const inline
template<class T> Ref<T>& otawa::ContextualPath::Ref< T >::operator*= (const T & v) const inline
template<class T> Ref<T>& otawa::ContextualPath::Ref< T >::operator++ (void) const inline
template<class T> Ref<T>& otawa::ContextualPath::Ref< T >::operator++ (int) const inline
template<class T> Ref<T>& otawa::ContextualPath::Ref< T >::operator+= (const T & v) const inline
template<class T> Ref<T>& otawa::ContextualPath::Ref< T >::operator-- (void) const inline
template<class T> Ref<T>& otawa::ContextualPath::Ref< T >::operator-- (int) const inline
template<class T> Ref<T>& otawa::ContextualPath::Ref< T >::operator-= (const T & v) const inline
template<class T> T otawa::ContextualPath::Ref< T >::operator-> (void) const inline
template<class T> Ref<T>& otawa::ContextualPath::Ref< T >::operator/= (const T & v) const inline
template<class T> Ref<T>& otawa::ContextualPath::Ref< T >::operator<<= (const T & v) const inline
template<class T> Ref<T>& otawa::ContextualPath::Ref< T >::operator= (const Ref< T > & r) inline
References otawa::ContextualPath::Ref< T >::cp, otawa::ContextualPath::Ref< T >::i, and otawa::ContextualPath::Ref< T >::p.
template<class T> const Ref<T>& otawa::ContextualPath::Ref< T >::operator= (const T & value) const inline
template<class T> Ref<T>& otawa::ContextualPath::Ref< T >::operator>>= (const T & v) const inline
template<class T> Ref<T>& otawa::ContextualPath::Ref< T >::operator^= (const T & v) const inline
template<class T> Ref<T>& otawa::ContextualPath::Ref< T >::operator|= (const T & v) const inline
template<class T> const ContextualPath& otawa::ContextualPath::Ref< T >::path (void) const inline
template<class T> void otawa::ContextualPath::Ref< T >::print (io::Output & out) inline
References otawa::display::find().
template<class T> const PropList& otawa::ContextualPath::Ref< T >::proplist (void) const inline
template<class T> T& otawa::ContextualPath::Ref< T >::ref (void) const inline
References otawa::ContextualProperty::ref().
template<class T> void otawa::ContextualPath::Ref< T >::remove (void) const inline
References otawa::ContextualProperty::make(), and otawa::PropList::removeProp().
Member Data Documentation
template<class T> const ContextualPath& otawa::ContextualPath::Ref< T >::cp private
Referenced by otawa::ContextualPath::Ref< T >::operator=().
template<class T> const Identifier<T>& otawa::ContextualPath::Ref< T >::i private
Referenced by otawa::ContextualPath::Ref< T >::operator=().
template<class T> PropList& otawa::ContextualPath::Ref< T >::p private
Referenced by otawa::ContextualPath::Ref< T >::operator=().
The documentation for this class was generated from the following file:
include/otawa/prop/ContextualProperty.h