Otawa: otawa::BBDeletor< T > Class Template Reference
otawa::BBDeletor< T > Class Template Reference
Basic block cleaner removing an identifier and deleting its content.
#include <otawa/proc/BBProcessor.h>
Public Member Functions
BBDeletor (WorkSpace *ws, Identifier< T * > &identifier)
virtual ~BBDeletor (void)
virtual void clean (void)
Protected Member Functions
virtual void clean (WorkSpace *ws, CFG *cfg, BasicBlock *bb)
Protected Attributes
Identifier< T * > & id
Detailed Description
template<class T>
class otawa::BBDeletor< T >
Basic block cleaner removing an identifier and deleting its content.
Parameters
T Type of data pointed by the identifier.
Constructor & Destructor Documentation
template<class T > otawa::BBDeletor< T >::BBDeletor (WorkSpace * ws, Identifier< T * > & identifier) inline
template<class T > virtual otawa::BBDeletor< T >::~BBDeletor (void) inline virtual
Member Function Documentation
void otawa::BBCleaner::clean (void) virtual inherited
References otawa::cfgio::bb(), otawa::CFGProcessor::cfg(), otawa::INVOLVED_CFGS, and otawa::Processor::ws.
Referenced by otawa::BBDeletor< T >::clean().
template<class T > virtual void otawa::BBDeletor< T >::clean (WorkSpace * ws, CFG * cfg, BasicBlock * bb) inline protected virtual
Reimplemented from otawa::BBRemover< T >.
References otawa::BBCleaner::clean().
Member Data Documentation
template<class T > Identifier<T *>& otawa::BBDeletor< T >::id protected
The documentation for this class was generated from the following file:
include/otawa/proc/BBProcessor.h