Otawa: otawa::LabelAddress Class Reference
otawa::LabelAddress Class Reference
A label address formed by a label and a possible signed offset.
#include <otawa/util/SymAddress.h>
Public Member Functions
LabelAddress (string label, t::int32 offset=0)
virtual Address toAddress (WorkSpace *ws)
Expand the current symbolic address as an actual address in the given workspace.
virtual CFG * cfg (WorkSpace *ws)
Get the CFG matching the given address.
virtual void print (io::Output &out)
Print the symbolic address.
Static Public Member Functions
static SymAddress * parse (string str) throw (otawa::Exception)
Parse a symbolic address from a string.
Private Attributes
string _label
t::int32 _offset
Detailed Description
A label address formed by a label and a possible signed offset.
Constructor & Destructor Documentation
otawa::LabelAddress::LabelAddress (string label, t::int32 offset = 0)
Member Function Documentation
CFG * otawa::LabelAddress::cfg (WorkSpace * ws) virtual
Get the CFG matching the given address.
CFG_INFO_FEATURE should be available first.
Parameters
ws Workspace to look in.
Returns
Found CFG or null.
Implements otawa::SymAddress.
References otawa::CFG_INFO_FEATURE, otawa::WorkSpace::findInstAt(), otawa::CFGInfo::ID, otawa::WorkSpace::isProvided(), and toAddress().
SymAddress * otawa::SymAddress::parse (string str) throw (otawa::Exception) static inherited
Parse a symbolic address from a string.
Parameters
str String to parse.
Returns
Built symbolic address (deletion is delegated to the caller).
Exceptions
otawa::Exception Thrown if there is a parsing error.
References otawa::sem::neg().
Referenced by otawa::Application::parseAddress().
void otawa::LabelAddress::print (io::Output & out) virtual
Print the symbolic address.
Parameters
out Stream to output to.
Implements otawa::SymAddress.
References _label, and _offset.
Address otawa::LabelAddress::toAddress (WorkSpace * ws) virtual
Expand the current symbolic address as an actual address in the given workspace.
Parameters
ws Workspace to expand in.
Returns
Actual address.
Implements otawa::SymAddress.
References _label, _offset, otawa::Symbol::address(), otawa::Process::findSymbol(), otawa::Address::null, and otawa::WorkSpace::process().
Referenced by cfg().
Member Data Documentation
string otawa::LabelAddress::_label private
Referenced by print(), and toAddress().
t::int32 otawa::LabelAddress::_offset private
Referenced by print(), and toAddress().
The documentation for this class was generated from the following files:
include/otawa/util/SymAddress.h
src/prog/util_SymAddress.cpp