Otawa: otawa::hard::PureCache Class Reference
otawa::hard::PureCache Class Reference
Platform Description
#include <otawa/hard/PureCache.h>
Public Types
enum replace_policy_t {
NONE = 0, OTHER = 1, LRU = 2, RANDOM = 3,
FIFO = 4, PLRU = 5
}
typedef enum otawa::hard::PureCache::replace_policy_t replace_policy_t
Public Member Functions
PureCache (void)
virtual ~PureCache (void)
ot::size cacheSize (void) const
ot::size blockSize (void) const
int wayCount (void) const
int rowCount (void) const
int blockCount (void) const
replace_policy_t replacementPolicy (void) const
int blockBits (void) const
int rowBits (void) const
int tagBits (void) const
int wayBits (void) const
ot::mask blockMask (void) const
ot::mask lineMask (void) const
ot::mask tagMask (void) const
ot::mask offset (address_t addr) const
ot::mask line (address_t addr) const
ot::mask tag (address_t addr) const
ot::mask block (address_t addr) const
void setBlockBits (int block_bits)
void setRowBits (int set_bits)
Set the row count as a number of bits.
void setWayBits (int way_bits)
Set the way count as a number of bits.
void setReplacePolicy (replace_policy_t replace)
Set the replace policy of the cache.
Public Attributes
int block_bits
int row_bits
int way_bits
replace_policy_t replace
Private Member Functions
SERIALIZABLE (PureCache, DFIELD(block_bits, 4)&DFIELD(row_bits, 12)&DFIELD(way_bits, 0)&elm::field("replace", replace, LRU))
Private Attributes
const PureCache * _next
Member Typedef Documentation
typedef enum otawa::hard::PureCache::replace_policy_t otawa::hard::PureCache::replace_policy_t
Member Enumeration Documentation
enum otawa::hard::PureCache::replace_policy_t
Enumerator
NONE
OTHER
LRU
RANDOM
FIFO
PLRU
Constructor & Destructor Documentation
otawa::hard::PureCache::PureCache (void) inline
virtual otawa::hard::PureCache::~PureCache (void) inline virtual
References blockSize(), and cacheSize().
Member Function Documentation
ot::mask otawa::hard::PureCache::block (address_t addr) const inline
References blockBits(), ENUM(), and otawa::Address::offset().
Referenced by blockCount().
int otawa::hard::PureCache::blockBits (void) const inline
References block_bits.
Referenced by block(), blockCount(), blockSize(), cacheSize(), line(), lineMask(), tag(), and tagBits().
int otawa::hard::PureCache::blockCount (void) const inline
References block(), blockBits(), blockMask(), line(), lineMask(), offset(), replacementPolicy(), rowBits(), setBlockBits(), setReplacePolicy(), setRowBits(), setWayBits(), tag(), tagBits(), tagMask(), way_bits, and wayBits().
ot::mask otawa::hard::PureCache::blockMask (void) const inline
References blockSize().
Referenced by blockCount(), offset(), and tagMask().
ot::size otawa::hard::PureCache::blockSize (void) const inline
References blockBits().
Referenced by blockMask(), and ~PureCache().
ot::size otawa::hard::PureCache::cacheSize (void) const inline
References blockBits(), rowBits(), and wayBits().
Referenced by ~PureCache().
ot::mask otawa::hard::PureCache::line (address_t addr) const inline
References blockBits(), lineMask(), and otawa::Address::offset().
Referenced by blockCount().
ot::mask otawa::hard::PureCache::lineMask (void) const inline
References blockBits(), and rowCount().
Referenced by blockCount(), line(), and tagMask().
ot::mask otawa::hard::PureCache::offset (address_t addr) const inline
References blockMask(), and otawa::Address::offset().
Referenced by blockCount().
PureCache::replace_policy_t otawa::hard::PureCache::replacementPolicy (void) const inline
References replace.
Referenced by blockCount().
int otawa::hard::PureCache::rowBits (void) const inline
References row_bits.
Referenced by blockCount(), cacheSize(), rowCount(), tag(), and tagBits().
int otawa::hard::PureCache::rowCount (void) const inline
References rowBits().
Referenced by lineMask().
otawa::hard::PureCache::SERIALIZABLE (PureCache , DFIELD(block_bits, 4)&DFIELD(row_bits, 12)&DFIELD(way_bits, 0)&elm::field("replace", replace, LRU)) private
void otawa::hard::PureCache::setBlockBits (int block_bits)
Referenced by blockCount().
void otawa::hard::PureCache::setReplacePolicy (replace_policy_t replace)
Set the replace policy of the cache.
Parameters
replace Replace policy, one of OTHER, LRU, RANDOM, FIFO, PLRU.
References FIFO, LRU, NONE, OTHER, PLRU, RANDOM, SERIALIZE(), and VALUE().
Referenced by blockCount().
void otawa::hard::PureCache::setRowBits (int row_bits)
Set the row count as a number of bits.
The actual row count is 1 << row_bits.
Parameters
row_bits Row count in bits.
Referenced by blockCount().
void otawa::hard::PureCache::setWayBits (int way_bits)
Set the way count as a number of bits.
The actual way count is 1 << way_bits.
Parameters
way_bits Way count in bits.
Referenced by blockCount().
ot::mask otawa::hard::PureCache::tag (address_t addr) const inline
References blockBits(), otawa::Address::offset(), and rowBits().
Referenced by blockCount().
int otawa::hard::PureCache::tagBits (void) const inline
References blockBits(), and rowBits().
Referenced by blockCount().
ot::mask otawa::hard::PureCache::tagMask (void) const inline
References blockMask(), and lineMask().
Referenced by blockCount().
int otawa::hard::PureCache::wayBits (void) const inline
References way_bits.
Referenced by blockCount(), cacheSize(), and wayCount().
int otawa::hard::PureCache::wayCount (void) const inline
References wayBits().
Member Data Documentation
const PureCache* otawa::hard::PureCache::_next private
int otawa::hard::PureCache::block_bits
Referenced by blockBits().
replace_policy_t otawa::hard::PureCache::replace
Referenced by replacementPolicy().
int otawa::hard::PureCache::row_bits
Referenced by rowBits().
int otawa::hard::PureCache::way_bits
Referenced by blockCount(), and wayBits().
The documentation for this class was generated from the following files:
include/otawa/hard/PureCache.h
src/prog/hardware_PureCache.cpp