Otawa: otawa::ParamExeGraph Class Reference
otawa::ParamExeGraph Class Reference
#include <otawa/exegraph/ParamExeGraph.h>
Classes
class ExternalConflictIterator
class ExternalConflictResource
class FuResource
struct input_t
class InternalConflictIterator
class InternalConflictResource
class QueueResource
class RegResource
class Resource
class ResourceIterator
class StageResource
class StartResource
Public Types
enum resource_type_t {
STAGE, FU, QUEUE, REG,
EXTERNAL_CONFLICT, INTERNAL_CONFLICT, BLOCK_START, RES_TYPE_NUM
}
typedef class ParamExeNode Node
typedef struct otawa::ParamExeGraph::input_t input_t
enum code_part_t
typedef enum otawa::ExeGraph::code_part_t code_part_t
enum time_bound_t
enum time_step_t
typedef GenGraph< ParamExeNode, typename ExeGraph< ParamExeNode >::ExeEdge > Graph
Public Member Functions
ParamExeGraph (WorkSpace *fw, Microprocessor< ParamExeNode > *microprocessor, ExeSequence< ParamExeNode > *sequence, bool has_pred, Trace *_trace)
virtual void propagate ()
virtual void initDelays ()
virtual int Delta (ParamExeNode *a, Resource *res)
virtual void analyzeContentions ()
void clearTimesChanged ()
void setTimesChanged ()
bool timesChanged ()
void dump (elm::io::Output &dotFile)
void dumpSimple (elm::io::Output &dotFile)
int resourceCount ()
int instructionCount ()
int analyze ()
virtual int cost ()
int latestResourceIndex ()
elm::String delayName (int delay)
GenGraph< ParamExeNode, typename ExeGraph< ParamExeNode >::ExeEdge > * graph ()
void setEntryNode (ParamExeNode *node)
Sets the entry node (used for topological graph exploration).
ParamExeNode * entryNode (void)
virtual void build (WorkSpace *fw, Microprocessor< ParamExeNode > *microprocessor, ExeSequence< ParamExeNode > *sequence)
elm::String partName (code_part_t part)
void setFirstNode (code_part_t part, ParamExeNode *node)
void setLastNode (code_part_t part, ParamExeNode *node)
ParamExeNode * firstNode (code_part_t part)
ParamExeNode * lastNode (code_part_t part)
Protected Types
typedef struct otawa::ExeGraph::rename_table_t rename_table_t
Protected Attributes
bool _times_changed
int _resource_count
int _capacity
elm::genstruct::Vector< Resource * > _resources
elm::genstruct::Vector< Resource * > _internal_conflicts
elm::genstruct::Vector< Resource * > _external_conflicts
int _latest_resource_index
int _last_resource_index
bool _has_pred
ExeSequence< ParamExeNode > * _sequence
elm::genstruct::Vector< ParamExeNode * > _contending_nodes
bool res_dep [RES_TYPE_NUM]
int res_dep_impact [RES_TYPE_NUM]
ParamExeNode * _entry_node
ParamExeNode * _first_node [CODE_PARTS_NUMBER]
ParamExeNode * _last_node [CODE_PARTS_NUMBER]
Microprocessor< ParamExeNode > * _microprocessor
elm::String _part_name [CODE_PARTS_NUMBER]
GenGraph< ParamExeNode, ExeEdge > _graph
Private Attributes
Trace * _trace
Member Typedef Documentation
typedef enum otawa::ExeGraph::code_part_t otawa::ExeGraph< ParamExeNode >::code_part_t inherited
typedef GenGraph<ParamExeNode ,typename ExeGraph<ParamExeNode >::ExeEdge> otawa::ExeGraph< ParamExeNode >::Graph inherited
typedef struct otawa::ParamExeGraph::input_t otawa::ParamExeGraph::input_t
typedef class ParamExeNode otawa::ParamExeGraph::Node
typedef struct otawa::ExeGraph::rename_table_t otawa::ExeGraph< ParamExeNode >::rename_table_t protected inherited
Member Enumeration Documentation
enum otawa::ExeGraph::code_part_t inherited
enum otawa::ParamExeGraph::resource_type_t
Enumerator
STAGE
FU
QUEUE
REG
EXTERNAL_CONFLICT
INTERNAL_CONFLICT
BLOCK_START
RES_TYPE_NUM
enum otawa::ExeGraph::time_bound_t inherited
enum otawa::ExeGraph::time_step_t inherited
Constructor & Destructor Documentation
otawa::ParamExeGraph::ParamExeGraph (WorkSpace * fw, Microprocessor< ParamExeNode > * microprocessor, ExeSequence< ParamExeNode > * sequence, bool has_pred, Trace * _trace) inline
References _external_conflicts, _has_pred, _internal_conflicts, _last_resource_index, _latest_resource_index, _resources, _sequence, _trace, otawa::ParamExeGraph::RegResource::addUsingInst(), otawa::hard::Platform::banks(), otawa::sem::inst::inst(), otawa::Microprocessor< N >::operandProducingStage(), otawa::WorkSpace::platform(), and STAGE.
Member Function Documentation
int ParamExeGraph::analyze ()
References _capacity, otawa::ExeGraph< ParamExeNode >::_last_node, otawa::ExeGraph< ParamExeNode >::_microprocessor, analyzeContentions(), otawa::ExeGraph< ParamExeNode >::BODY, cost(), initDelays(), otawa::ExeGraph< ParamExeNode >::PROLOGUE, propagate(), res_dep, res_dep_impact, and RES_TYPE_NUM.
Referenced by instructionCount(), and otawa::ParamExeGraphBBTime::processBB().
void ParamExeGraph::analyzeContentions () virtual
References _capacity, otawa::ExeGraph< ParamExeNode >::_last_node, otawa::ExeGraph< ParamExeNode >::_microprocessor, _trace, otawa::sem::cont(), otawa::sem::inst::d(), otawa::sem::inst::inst(), otawa::ExeGraph< N >::ExeNode::inst(), otawa::L9, otawa::PipelineStage< N >::numberOfNodes(), otawa::ExeGraph< ParamExeNode >::PROLOGUE, and otawa::PipelineStage< N >::width().
Referenced by analyze().
virtual void otawa::ExeGraph< ParamExeNode >::build (WorkSpace * fw, Microprocessor< ParamExeNode > * microprocessor, ExeSequence< ParamExeNode > * sequence) virtual inherited
Parameters
fw The framework.
microprocessor The microprocessor.
sequence The sequence of instructions the graph should represent.
void otawa::ParamExeGraph::clearTimesChanged () inline
int ParamExeGraph::cost (void) virtual
References otawa::ExeGraph< ParamExeNode >::_last_node, _trace, BLOCK_START, otawa::ExeGraph< ParamExeNode >::BODY, otawa::ParamExeNode::d(), Delta(), otawa::ParamExeNode::e(), otawa::GenGraph< N, E >::GenNode::index(), otawa::ParamExeGraph::Resource::index(), otawa::L3, otawa::ParamExeGraph::Resource::name(), and QUEUE.
Referenced by analyze(), and instructionCount().
elm::String otawa::ParamExeGraph::delayName (int delay) inline
References EPSILON, and INFINITE_TIME.
Referenced by latestResourceIndex().
int ParamExeGraph::Delta (ParamExeNode * a, Resource * res) virtual
References otawa::ExeGraph< ParamExeNode >::_last_node, _latest_resource_index, _trace, otawa::ParamExeNode::contendersMasksList(), otawa::ParamExeNode::d(), delta(), otawa::ParamExeNode::e(), otawa::ParamExeGraph::Resource::index(), otawa::L8, otawa::ParamExeNode::lateContenders(), otawa::ExeGraph< N >::ExeNode::latency(), otawa::ParamExeGraph::Resource::name(), otawa::ExeGraph< N >::ExeNode::name(), otawa::ParamExeGraph::Resource::offset(), otawa::ExeGraph< N >::ExeNode::pipelineStage(), otawa::ExeGraph< ParamExeNode >::PROLOGUE, QUEUE, and otawa::ParamExeGraph::Resource::type().
Referenced by cost().
void ParamExeGraph::dump (elm::io::Output & dotFile)
References _external_conflicts, _internal_conflicts, _resources, _sequence, otawa::ot::address(), otawa::ExeGraph< ParamExeNode >::BODY, and otawa::sem::inst::inst().
Referenced by otawa::ParamExeGraphBBTime::processBB(), and timesChanged().
void ParamExeGraph::dumpSimple (elm::io::Output & dotFile)
References _sequence, otawa::ot::address(), otawa::ExeGraph< ParamExeNode >::BODY, otawa::sem::inst::inst(), otawa::instCategory(), and otawa::ExeGraph< ParamExeNode >::MIN.
Referenced by timesChanged().
ParamExeNode * otawa::ExeGraph< ParamExeNode >::entryNode (void) inline inherited
Returns
The entry node.
ParamExeNode * otawa::ExeGraph< ParamExeNode >::firstNode (code_part_t part) inline inherited
Parameters
part The code part.
Returns
The first node of the specified code part.
GenGraph<ParamExeNode , typename ExeGraph<ParamExeNode >::ExeEdge>* otawa::ExeGraph< ParamExeNode >::graph (void) inline inherited
Returns
The graph.
void ParamExeGraph::initDelays () virtual
References otawa::ExeGraph< ParamExeNode >::_first_node, BLOCK_START, otawa::ExeGraph< ParamExeNode >::BODY, otawa::Queue< N >::fillingStage(), FU, otawa::ExeInst< N >::index(), otawa::PipelineStage< N >::node(), otawa::ExeGraph< ParamExeNode >::PROLOGUE, QUEUE, REG, otawa::ParamExeNode::setE(), and STAGE.
Referenced by analyze().
int otawa::ParamExeGraph::instructionCount () inline
References analyze(), cost(), and otawa::ExeSequence< N >::length().
Referenced by otawa::ParamExeNode::ParamExeNode().
ParamExeNode * otawa::ExeGraph< ParamExeNode >::lastNode (code_part_t part) inline inherited
Parameters
part The code part.
Returns
The last node of the specified code part.
int otawa::ParamExeGraph::latestResourceIndex () inline
References _latest_resource_index, and delayName().
elm::String otawa::ExeGraph< ParamExeNode >::partName (code_part_t part) inline inherited
Returns
The name of the code part (BEFORE_PROLOGUE, PROLOGUE, BODY or EPILOGUE).
void ParamExeGraph::propagate () virtual
References otawa::ExeGraph< ParamExeNode >::_entry_node, and _last_resource_index.
Referenced by analyze().
int otawa::ParamExeGraph::resourceCount () inline
Referenced by otawa::ParamExeNode::ParamExeNode().
void otawa::ExeGraph< ParamExeNode >::setEntryNode (ParamExeNode * node) inline inherited
Sets the entry node (used for topological graph exploration).
Parameters
node The entry node.
void otawa::ExeGraph< ParamExeNode >::setFirstNode (code_part_t part, ParamExeNode * node) inline inherited
Parameters
part The code part.
node The first node of this code part. Sets the first node of the specified code part.
void otawa::ExeGraph< ParamExeNode >::setLastNode (code_part_t part, ParamExeNode * node) inline inherited
Parameters
part The code part.
node The last node of this code part. Sets the last node of the specified code part.
void otawa::ParamExeGraph::setTimesChanged () inline
Referenced by otawa::ParamExeNode::setContentionDelay(), otawa::ParamExeNode::setDelay(), and otawa::ParamExeNode::setInternalDelay().
bool otawa::ParamExeGraph::timesChanged () inline
References _times_changed, dump(), and dumpSimple().
Member Data Documentation
int otawa::ParamExeGraph::_capacity protected
Referenced by analyze(), and analyzeContentions().
elm::genstruct::Vector<ParamExeNode *> otawa::ParamExeGraph::_contending_nodes protected
ParamExeNode * otawa::ExeGraph< ParamExeNode >::_entry_node protected inherited
Referenced by propagate().
elm::genstruct::Vector<Resource *> otawa::ParamExeGraph::_external_conflicts protected
Referenced by dump(), and ParamExeGraph().
ParamExeNode * otawa::ExeGraph< ParamExeNode >::_first_node[CODE_PARTS_NUMBER] protected inherited
Referenced by initDelays().
GenGraph<ParamExeNode , ExeEdge> otawa::ExeGraph< ParamExeNode >::_graph protected inherited
bool otawa::ParamExeGraph::_has_pred protected
Referenced by ParamExeGraph().
elm::genstruct::Vector<Resource *> otawa::ParamExeGraph::_internal_conflicts protected
Referenced by dump(), and ParamExeGraph().
ParamExeNode * otawa::ExeGraph< ParamExeNode >::_last_node[CODE_PARTS_NUMBER] protected inherited
Referenced by analyze(), analyzeContentions(), cost(), and Delta().
int otawa::ParamExeGraph::_last_resource_index protected
Referenced by ParamExeGraph(), and propagate().
int otawa::ParamExeGraph::_latest_resource_index protected
Referenced by Delta(), latestResourceIndex(), and ParamExeGraph().
Microprocessor<ParamExeNode >* otawa::ExeGraph< ParamExeNode >::_microprocessor protected inherited
Referenced by analyze(), and analyzeContentions().
elm::String otawa::ExeGraph< ParamExeNode >::_part_name[CODE_PARTS_NUMBER] protected inherited
int otawa::ParamExeGraph::_resource_count protected
elm::genstruct::Vector<Resource *> otawa::ParamExeGraph::_resources protected
Referenced by dump(), and ParamExeGraph().
ExeSequence<ParamExeNode>* otawa::ParamExeGraph::_sequence protected
Referenced by dump(), dumpSimple(), and ParamExeGraph().
bool otawa::ParamExeGraph::_times_changed protected
Referenced by timesChanged().
Trace* otawa::ParamExeGraph::_trace private
Referenced by analyzeContentions(), cost(), Delta(), and ParamExeGraph().
bool otawa::ParamExeGraph::res_dep[RES_TYPE_NUM] protected
Referenced by analyze().
int otawa::ParamExeGraph::res_dep_impact[RES_TYPE_NUM] protected
Referenced by analyze().
The documentation for this class was generated from the following files:
include/otawa/exegraph/ParamExeGraph.h
src/prog/exegraph_ParamExeGraph.cpp