Otawa: otawa::p::init Class Reference
otawa::p::init Class Reference
#include <otawa/proc/Registration.h>
Public Member Functions
init (string name, Version version)
init (string name, Version version, AbstractRegistration &base)
init & require (const AbstractFeature &feature)
init & provide (const AbstractFeature &feature)
init & invalidate (const AbstractFeature &feature)
init & use (const AbstractFeature &feature)
init & config (AbstractIdentifier &id)
init & base (AbstractRegistration &base)
template<class T >
init & maker (void)
Private Attributes
string _name
Version _version
AbstractRegistration * _base
SLList< AbstractIdentifier * > configs
SLList< FeatureUsage > features
AbstractMaker * _maker
Friends
class declare
Constructor & Destructor Documentation
otawa::p::init::init (string name, Version version) inline
otawa::p::init::init (string name, Version version, AbstractRegistration & base) inline
Member Function Documentation
init& otawa::p::init::base (AbstractRegistration & base) inline
References base().
Referenced by base(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::etime::EdgeTimeBuilder::make(), otawa::operator<<(), otawa::dcache::operator<<(), otawa::CAT2Builder::processCFG(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), otawa::stack::Manager::updatePath(), and otawa::ipet::WCETCountRecorder::WCETCountRecorder().
init& otawa::p::init::config (AbstractIdentifier & id) inline
init& otawa::p::init::invalidate (const AbstractFeature & feature) inline
References otawa::FeatureUsage::invalidate.
template<class T > init& otawa::p::init::maker (void) inline
Referenced by otawa::hard::CacheConfiguration::cacheName(), otawa::CAT2NCBuilder::CAT2NCBuilder(), otawa::CFGCollector::CFGCollector(), otawa::branch::OnlyConsBuilder::configure(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::hard::Processor::instantiate(), otawa::etime::EdgeTimeBuilder::make(), makeAddress(), otawa::operator<<(), otawa::branch::operator<<(), otawa::dcache::operator<<(), otawa::clp::operator<<(), otawa::dcache::DirtyManager::t::print(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::CAT2Builder::processCFG(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), otawa::dfa::State::record(), otawa::StackAnalysis::StackAnalysis(), otawa::stack::Manager::updatePath(), otawa::Virtualizer::Virtualizer(), otawa::ipet::WCETCountRecorder::WCETCountRecorder(), and otawa::hard::Memory::worstWriteAccess().
init& otawa::p::init::provide (const AbstractFeature & feature) inline
References otawa::FeatureUsage::provide.
Referenced by otawa::hard::CacheConfiguration::cacheName(), otawa::CFGCollector::CFGCollector(), otawa::branch::OnlyConsBuilder::configure(), otawa::hard::Processor::instantiate(), otawa::branch::operator<<(), otawa::dcache::DirtyManager::t::print(), otawa::cat::CATBuilder::processWorkSpace(), and otawa::hard::Memory::worstWriteAccess().
init& otawa::p::init::require (const AbstractFeature & feature) inline
References otawa::FeatureUsage::require.
Referenced by otawa::CFGCollector::CFGCollector(), otawa::branch::OnlyConsBuilder::configure(), otawa::branch::operator<<(), otawa::dcache::DirtyManager::t::print(), and otawa::cat::CATBuilder::processWorkSpace().
init& otawa::p::init::use (const AbstractFeature & feature) inline
References otawa::FeatureUsage::use.
Friends And Related Function Documentation
friend class declare friend
Member Data Documentation
AbstractRegistration* otawa::p::init::_base private
AbstractMaker* otawa::p::init::_maker private
Referenced by otawa::p::declare::declare().
string otawa::p::init::_name private
Version otawa::p::init::_version private
SLList<AbstractIdentifier *> otawa::p::init::configs private
Referenced by otawa::p::declare::declare().
SLList<FeatureUsage> otawa::p::init::features private
Referenced by otawa::p::declare::declare().
The documentation for this class was generated from the following file:
include/otawa/proc/Registration.h