Otawa: otawa::ilp::model::model_cons Class Reference
otawa::ilp::model::model_cons Class Reference
#include <otawa/ilp/expr.h>
Public Member Functions
model_cons (const cons &c)
cons operator% (int t)
cons operator% (const Term &t)
cons operator% (const Expression &t)
operator cons (void) const
cons operator+ (int t)
cons operator+ (const Term &t)
cons operator+ (const Expression &e)
cons operator- (int t)
cons operator- (const Term &t)
cons operator- (const Expression &e)
cons operator+= (int t)
cons operator+= (const Term &t)
cons operator+= (const Expression &e)
cons operator-= (int t)
cons operator-= (const Term &t)
cons operator-= (const Expression &e)
cons operator== (const Term &t)
cons operator== (const Expression &f)
cons operator<= (const Term &t)
cons operator<= (const Expression &f)
cons operator< (const Term &t)
cons operator< (const Expression &f)
cons operator>= (const Term &t)
cons operator>= (const Expression &f)
cons operator> (const Term &t)
cons operator> (const Expression &f)
Constraint * operator& (void) const
Constraint * operator-> (void) const
void free (void)
Constructor & Destructor Documentation
otawa::ilp::model::model_cons::model_cons (const cons & c) inline
Member Function Documentation
void otawa::ilp::cons::free (void) inline inherited
otawa::ilp::model::model_cons::operator cons (void) const inline
cons otawa::ilp::model::model_cons::operator% (int t) inline
References otawa::ilp::cons::operator+().
cons otawa::ilp::model::model_cons::operator% (const Term & t) inline
References otawa::ilp::cons::operator+().
cons otawa::ilp::model::model_cons::operator% (const Expression & t) inline
References otawa::ilp::cons::operator+().
Constraint* otawa::ilp::cons::operator& (void) const inline inherited
cons otawa::ilp::cons::operator+ (int t) inline inherited
References otawa::ilp::Constraint::add().
Referenced by operator%().
cons otawa::ilp::cons::operator+ (const Term & t) inline inherited
References otawa::ilp::Constraint::add().
cons otawa::ilp::cons::operator+ (const Expression & e) inline inherited
References otawa::ilp::Constraint::add().
cons otawa::ilp::cons::operator+= (int t) inline inherited
References otawa::ilp::Constraint::add().
cons otawa::ilp::cons::operator+= (const Term & t) inline inherited
References otawa::ilp::Constraint::add().
cons otawa::ilp::cons::operator+= (const Expression & e) inline inherited
References otawa::ilp::Constraint::add().
cons otawa::ilp::cons::operator- (int t) inline inherited
References otawa::ilp::Constraint::sub().
cons otawa::ilp::cons::operator- (const Term & t) inline inherited
References otawa::ilp::Constraint::sub().
cons otawa::ilp::cons::operator- (const Expression & e) inline inherited
References otawa::ilp::Constraint::sub().
cons otawa::ilp::cons::operator-= (int t) inline inherited
References otawa::ilp::Constraint::sub().
cons otawa::ilp::cons::operator-= (const Term & t) inline inherited
References otawa::ilp::Constraint::sub().
cons otawa::ilp::cons::operator-= (const Expression & e) inline inherited
References otawa::ilp::Constraint::sub().
Constraint* otawa::ilp::cons::operator-> (void) const inline inherited
cons otawa::ilp::cons::operator< (const Term & t) inline inherited
References otawa::ilp::Constraint::LT.
cons otawa::ilp::cons::operator< (const Expression & f) inline inherited
References otawa::ilp::Constraint::LT.
cons otawa::ilp::cons::operator<= (const Term & t) inline inherited
References otawa::ilp::Constraint::LE.
cons otawa::ilp::cons::operator<= (const Expression & f) inline inherited
References otawa::ilp::Constraint::LE.
cons otawa::ilp::cons::operator== (const Term & t) inline inherited
References otawa::ilp::Constraint::EQ.
cons otawa::ilp::cons::operator== (const Expression & f) inline inherited
References otawa::ilp::Constraint::EQ.
cons otawa::ilp::cons::operator> (const Term & t) inline inherited
References otawa::ilp::Constraint::GT.
cons otawa::ilp::cons::operator> (const Expression & f) inline inherited
References otawa::ilp::Constraint::GT.
cons otawa::ilp::cons::operator>= (const Term & t) inline inherited
References otawa::ilp::Constraint::GE.
cons otawa::ilp::cons::operator>= (const Expression & f) inline inherited
References otawa::ilp::Constraint::GE.
The documentation for this class was generated from the following file:
include/otawa/ilp/expr.h