Otawa: otawa::ResourceList Class Reference
otawa::ResourceList Class Reference
#include <otawa/parexegraph/Resource.h>
Classes
class ResourceIterator
Public Member Functions
ResourceList (WorkSpace *ws, ParExeProc *proc)
int numResources ()
Private Attributes
elm::genstruct::Vector< Resource * > _resources
Constructor & Destructor Documentation
otawa::ResourceList::ResourceList (WorkSpace * ws, ParExeProc * proc)
References _resources, otawa::hard::Platform::banks(), otawa::hard::RegBank::count(), otawa::ParExeStage::EXECUTE, otawa::ParExePipeline::firstStage(), otawa::hard::RegBank::get(), otawa::ParExeStage::IN_ORDER, otawa::hard::RegBank::name(), otawa::ParExeStage::name(), otawa::ParExePipeline::numStages(), otawa::ParExeProc::pipeline(), otawa::WorkSpace::platform(), otawa::Resource::STAGE, and otawa::ParExeStage::width().
Member Function Documentation
int otawa::ResourceList::numResources () inline
Member Data Documentation
elm::genstruct::Vector<Resource *> otawa::ResourceList::_resources private
Referenced by ResourceList().
The documentation for this class was generated from the following files:
include/otawa/parexegraph/Resource.h
src/prog/parexegraph_Resource.cpp