Otawa: otawa::loader::old_gliss::Process Class Reference
otawa::loader::old_gliss::Process Class Reference abstract
#include <otawa/loader/old_gliss/Process.h>
Public Member Functions
Process (Manager *manager, Loader *loader, hard::Platform *platform, const PropList &props=PropList::EMPTY)
void * state (void) const
virtual hard::Platform * platform (void)
Get the platform of the process.
virtual Inst * start (void)
Get the address of the first instruction of the program.
virtual File * loadFile (elm::CString path)
virtual Loader * loader (void) const
Get the loader that has created this process.
virtual void get (Address at, signed char &val)
virtual void get (Address at, unsigned char &val)
virtual void get (Address at, signed short &val)
virtual void get (Address at, unsigned short &val)
virtual void get (Address at, signed long &val)
virtual void get (Address at, unsigned long &val)
virtual void get (Address at, signed long long &val)
virtual void get (Address at, unsigned long long &val)
virtual void get (Address at, Address &val)
Get an address value from the process.
virtual void get (Address at, string &str)
virtual void get (Address at, char *buf, int size)
Get a byte block value from the process.
virtual Option< Pair< cstring, int > > getSourceLine (Address addr) throw (UnsupportedFeatureException)
Get the source file and the line matching the given address.
virtual void getAddresses (cstring file, int line, Vector< Pair< Address, Address > > &addresses) throw (UnsupportedFeatureException)
Get the list of addresses implementing the given (source, line) pair.
Manager * manager (void)
Get the manager owning this process.
virtual const hard::CacheConfiguration & cache (void)
Get the cache hierarchy of the current processor.
virtual Inst * findInstAt (address_t addr)
Find the instruction at the given address.
virtual Inst * findInstAt (const string &label)
find the instruction at the given label if the label matches a code segment.
virtual address_t findLabel (const string &label)
Find the address of the given label.
File * program (void) const
Get the program file, that is, the startup executable of the process.
virtual int instSize (void) const =0
Get the instruction size.
virtual Processor * decoder (void)
Get a decoder usuful to decode instructions.
Symbol * findSymbol (const string &name)
Find the symbol matching the given name.
Symbol * findSymbolAt (const Address &address)
Find a symbol by its address.
virtual Address initialSP (void) const
Get the initial address of the stack pointer.
virtual Inst * newNOp (Address addr=Address::null)
Build a NOP instruction at the given address.
virtual void deleteNop (Inst *inst)
Delete a NOP instruction previously allocated by NewOP().
virtual int maxTemp (void) const
Get the maximum number of temporaries used in the semantics instruction block.
virtual void get (Address at, t::int8 &val)
Get a signed byte value from the process.
virtual void get (Address at, t::uint8 &val)
Get an unsigned byte value from the process.
virtual void get (Address at, t::int16 &val)
Get a signed half-word value from the process.
virtual void get (Address at, t::uint16 &val)
Get a unsigned half-word value from the process.
virtual void get (Address at, t::int32 &val)
Get a signed word value from the process.
virtual void get (Address at, t::uint32 &val)
Get a unsigned word value from the process.
virtual void get (Address at, t::int64 &val)
Get a signed long word value from the process.
virtual void get (Address at, t::uint64 &val)
Get a unsigned long word value from the process.
virtual void get (Address at, float &val)
Get a float value from the process.
virtual void get (Address at, double &val)
Get a double value from the process.
virtual void get (Address at, long double &val)
Get a long double value from the process.
virtual SimState * newState (void)
Get a fresh startup state of the process for functional simulation.
virtual sim::Simulator * simulator (void)
Find the simulator used for the current process.
File * loadProgram (elm::CString path)
Load the program file.
virtual Address defaultStack (void) const
Get a default address for the stack top.
virtual void semInit (sem::Block &block) const
Provide semantic sequence to initialize the environment before performing static analysis.
Property * getProp (const AbstractIdentifier *id) const
Find a property by its identifier.
void setProp (Property *prop)
Set the property in the property list removing any double.
void setProp (const AbstractIdentifier *id)
void removeProp (const AbstractIdentifier *id)
Remove a property matching the given identifier.
void removeProp (const AbstractIdentifier &id)
Property * extractProp (const AbstractIdentifier *id)
Remove a property matching the given identifier and return it.
Property * extractProp (const AbstractIdentifier &id)
Remove a property matching the given identifier and return it.
void addProp (Property *prop)
Add property to the list without checking of duplication.
void removeAllProp (const AbstractIdentifier *id)
Remove all the properties matching the given identifier.
bool hasProp (const AbstractIdentifier &id) const
Test if the property list contains a property matching the given identifier.
void clearProps (void)
Remove all properties from the list.
void addProps (const PropList &props)
Add all properties from the given property list, in a reverse order.
void print (elm::io::Output &out) const
Display the current property list.
Public Attributes
Inst * _start
hard::Platform * _platform
void * _state
void * _memory
int argc
char ** argv
char ** envp
Loader * _loader
Static Public Attributes
static const PropList EMPTY
This is an empty proplist for convenience.
Protected Member Functions
virtual Inst * decode (address_t addr)=0
virtual void * memory (void)=0
void addFile (File *file)
Add the given file to the list of files.
void provide (AbstractFeature &feature)
This method let provide feature from the loader / processors.
Friends
class Segment
Constructor & Destructor Documentation
otawa::loader::old_gliss::Process::Process (Manager * manager, Loader * loader, hard::Platform * platform, const PropList & props = PropList::EMPTY)
Member Function Documentation
void otawa::Process::addFile (File * file) protected inherited
Add the given file to the list of files.
The first added file is considered as the program file.
Parameters
file Added file.
Note
After this call, the process is the owner of the file and will released it at deletion time.
References otawa::Process::files, and otawa::Process::prog.
Referenced by otawa::Process::Process().
void otawa::PropList::addProp (Property * prop) inherited
Add property to the list without checking of duplication.
Parameters
prop Property to add.
References otawa::Property::_next.
Referenced by otawa::Identifier< T >::add(), otawa::ast::ASTInfo::ASTInfo(), otawa::Identifier< otawa::arm::Info * >::copy(), otawa::AbstractIdentifier::initProps(), otawa::ContextualProperty::make(), otawa::script::Script::makeConfig(), otawa::ccg::Builder::processLBlockSet(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), and otawa::ContextualProperty::refProps().
void otawa::PropList::addProps (const PropList & props) inherited
Add all properties from the given property list, in a reverse order.
Parameters
props Property list to clone.
References otawa::Property::copy(), otawa::PropList::head, and otawa::Property::next().
Referenced by otawa::display::CFGDrawer::CFGDrawer(), otawa::display::GraphVizGraph::GraphVizGraph(), otawa::ParamFeature::instantiate(), otawa::Manager::loadXML(), otawa::display::GraphVizGraph::newEdge(), otawa::display::GraphVizGraph::newNode(), otawa::Process::Process(), otawa::display::GraphVizItem::setProps(), otawa::VirtualBasicBlock::VirtualBasicBlock(), and otawa::VirtualCFG::VirtualCFG().
const hard::CacheConfiguration & otawa::Process::cache (void) virtual inherited
Get the cache hierarchy of the current processor.
The cachers are ordered according the index in the vector.
Returns
Cache hierarchy.
References otawa::hard::Platform::cache(), and otawa::Process::platform().
void otawa::PropList::clearProps (void) inherited
Remove all properties from the list.
References otawa::Property::next().
Referenced by otawa::PSTBuilder::getVCFG(), otawa::display::GraphVizItem::setProps(), and otawa::WorkSpace::~WorkSpace().
virtual Inst* otawa::loader::old_gliss::Process::decode (address_t addr) protected pure virtual
Processor * otawa::Process::decoder (void) virtual inherited
Get a decoder usuful to decode instructions.
May be overriden to give instruction set architecture dependent decoders.
Returns
Instruction decoder or null if none is defined.
Referenced by otawa::TextDecoder::processWorkSpace().
Address otawa::Process::defaultStack (void) const virtual inherited
Get a default address for the stack top.
Returns
Default address of stack top.
Referenced by otawa::clp::Analysis::processWorkSpace(), and otawa::dcache::BlockBuilder::setup().
void otawa::Process::deleteNop (Inst * inst) virtual inherited
Delete a NOP instruction previously allocated by NewOP().
Parameters
inst Instruction to delete.
Property * otawa::PropList::extractProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::script::Script::makeConfig().
Property * otawa::PropList::extractProp (const AbstractIdentifier & id) inline inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::PropList::extractProp().
Referenced by otawa::PropList::extractProp().
Inst * otawa::Process::findInstAt (address_t addr) virtual inherited
Find the instruction at the given address.
Parameters
addr Address of instruction to retrieve.
Returns
Found instruction or null if it cannot be found.
Parameters
addr Address to look at.
Returns
Instruction at the given address or null if it cannot be found.
Referenced by otawa::PFGBuilder::addFunction(), otawa::CFGInfo::findCFG(), otawa::Process::findInstAt(), otawa::DelayedBuilder::next(), otawa::FlowFactLoader::onIgnoreControl(), otawa::FlowFactLoader::onIgnoreSeq(), otawa::FlowFactLoader::onLoop(), otawa::FlowFactLoader::onMemoryAccess(), otawa::FlowFactLoader::onMultiBranch(), otawa::FlowFactLoader::onMultiCall(), otawa::FlowFactLoader::onNoCall(), otawa::FlowFactLoader::onNoInline(), otawa::FlowFactLoader::onNoReturn(), otawa::FlowFactLoader::onPreserve(), otawa::FlowFactLoader::onReturn(), otawa::FlowFactLoader::onSetInlining(), otawa::FlowFactLoader::scanIgnoreControl(), otawa::FlowFactLoader::scanIgnoreSeq(), otawa::FlowFactLoader::scanMultiBranch(), otawa::FlowFactLoader::scanMultiCall(), otawa::FlowFactLoader::scanNoInline(), otawa::FlowFactLoader::scanSetInlining(), otawa::FlowFactLoader::scanXCall(), otawa::FlowFactLoader::scanXFun(), otawa::FlowFactLoader::scanXLoop(), and otawa::DelayedBuilder::size().
Inst * otawa::Process::findInstAt (const string & label) virtual inherited
find the instruction at the given label if the label matches a code segment.
Parameters
label Label to look for.
Returns
Matching instruction or null.
References otawa::Process::findInstAt(), and otawa::Process::findLabel().
address_t otawa::Process::findLabel (const string & label) virtual inherited
Find the address of the given label.
For performing it, it looks iteratively one each file of the process until finding it.
Parameters
label Label to find.
Returns
Found address or null.
References otawa::Address::null.
Referenced by otawa::FlowFactLoader::addressOf(), and otawa::Process::findInstAt().
Symbol * otawa::Process::findSymbol (const string & name) inherited
Find the symbol matching the given name.
Parameters
name Symbol name to look for.
Returns
Found symbol or null.
Referenced by otawa::FlowFactLoader::scanAddress(), and otawa::LabelAddress::toAddress().
Symbol * otawa::Process::findSymbolAt (const Address & address) inherited
Find a symbol by its address.
Parameters
address Address of the looked symbol.
Returns
Found symbol or null.
References otawa::Symbol::DATA, otawa::Symbol::FUNCTION, otawa::Address::offset(), and otawa::Process::smap.
virtual void otawa::loader::old_gliss::Process::get (Address at, signed char & val) virtual
virtual void otawa::loader::old_gliss::Process::get (Address at, unsigned char & val) virtual
virtual void otawa::loader::old_gliss::Process::get (Address at, signed short & val) virtual
virtual void otawa::loader::old_gliss::Process::get (Address at, unsigned short & val) virtual
virtual void otawa::loader::old_gliss::Process::get (Address at, signed long & val) virtual
virtual void otawa::loader::old_gliss::Process::get (Address at, unsigned long & val) virtual
virtual void otawa::loader::old_gliss::Process::get (Address at, signed long long & val) virtual
virtual void otawa::loader::old_gliss::Process::get (Address at, unsigned long long & val) virtual
virtual void otawa::loader::old_gliss::Process::get (Address at, Address & val) virtual
Get an address value from the process.
Parameters
at Address of the value to get.
val Got value.
Exceptions
UnsupportedFeatureException if this method is called but the loader does not provide this feature.
OutOfMemStaticException if the given address does not point to a static segment of the executable file.
Warning
To use this method, you must assert that the MEMORY_ACCESS_FEATURE is provided.
Reimplemented from otawa::Process.
virtual void otawa::loader::old_gliss::Process::get (Address at, string & str) virtual
Reimplemented from otawa::Process.
virtual void otawa::loader::old_gliss::Process::get (Address at, char * buf, int size) virtual
Get a byte block value from the process.
Parameters
at Address of the value to get.
buf Buffer to store block to.
size Size of block.
Exceptions
UnsupportedFeatureException if this method is called but the loader does not provide this feature.
OutOfMemStaticException if the given address does not point to a static segment of the executable file.
Warning
To use this method, you must assert that the MEMORY_ACCESS_FEATURE is provided.
Reimplemented from otawa::Process.
void otawa::Process::get (Address at, t::int8 & val) virtual inherited
Get a signed byte value from the process.
Parameters
at Address of the value to get.
val Got value.
Exceptions
UnsupportedFeatureException if this method is called but the loader does not provide this feature.
OutOfMemStaticException if the given address does not point to a static segment of the executable file.
Warning
To use this method, you must assert that the MEMORY_ACCESS_FEATURE is provided.
References otawa::MEMORY_ACCESS_FEATURE.
Referenced by otawa::Process::get(), otawa::VarTextDecoder::getBytes(), otawa::stack::Value::join(), and otawa::CFGCheckSummer::processCFG().
void otawa::Process::get (Address at, t::uint8 & val) virtual inherited
Get an unsigned byte value from the process.
Parameters
at Address of the value to get.
val Got value.
Exceptions
UnsupportedFeatureException if this method is called but the loader does not provide this feature.
OutOfMemStaticException if the given address does not point to a static segment of the executable file.
Warning
To use this method, you must assert that the MEMORY_ACCESS_FEATURE is provided.
References otawa::MEMORY_ACCESS_FEATURE.
void otawa::Process::get (Address at, t::int16 & val) virtual inherited
Get a signed half-word value from the process.
Parameters
at Address of the value to get.
val Got value.
Exceptions
UnsupportedFeatureException if this method is called but the loader does not provide this feature.
OutOfMemStaticException if the given address does not point to a static segment of the executable file.
Warning
To use this method, you must assert that the MEMORY_ACCESS_FEATURE is provided.
References otawa::MEMORY_ACCESS_FEATURE.
void otawa::Process::get (Address at, t::uint16 & val) virtual inherited
Get a unsigned half-word value from the process.
Parameters
at Address of the value to get.
val Got value.
Exceptions
UnsupportedFeatureException if this method is called but the loader does not provide this feature.
OutOfMemStaticException if the given address does not point to a static segment of the executable file.
Warning
To use this method, you must assert that the MEMORY_ACCESS_FEATURE is provided.
References otawa::MEMORY_ACCESS_FEATURE.
void otawa::Process::get (Address at, t::int32 & val) virtual inherited
Get a signed word value from the process.
Parameters
at Address of the value to get.
val Got value.
Exceptions
UnsupportedFeatureException if this method is called but the loader does not provide this feature.
OutOfMemStaticException if the given address does not point to a static segment of the executable file.
Warning
To use this method, you must assert that the MEMORY_ACCESS_FEATURE is provided.
References otawa::MEMORY_ACCESS_FEATURE.
void otawa::Process::get (Address at, t::uint32 & val) virtual inherited
Get a unsigned word value from the process.
Parameters
at Address of the value to get.
val Got value.
Exceptions
UnsupportedFeatureException if this method is called but the loader does not provide this feature.
OutOfMemStaticException if the given address does not point to a static segment of the executable file.
Warning
To use this method, you must assert that the MEMORY_ACCESS_FEATURE is provided.
References otawa::MEMORY_ACCESS_FEATURE.
void otawa::Process::get (Address at, t::int64 & val) virtual inherited
Get a signed long word value from the process.
Parameters
at Address of the value to get.
val Got value.
Exceptions
UnsupportedFeatureException if this method is called but the loader does not provide this feature.
OutOfMemStaticException if the given address does not point to a static segment of the executable file.
Warning
To use this method, you must assert that the MEMORY_ACCESS_FEATURE is provided.
References otawa::MEMORY_ACCESS_FEATURE.
void otawa::Process::get (Address at, t::uint64 & val) virtual inherited
Get a unsigned long word value from the process.
Parameters
at Address of the value to get.
val Got value.
Exceptions
UnsupportedFeatureException if this method is called but the loader does not provide this feature.
OutOfMemStaticException if the given address does not point to a static segment of the executable file.
Warning
To use this method, you must assert that the MEMORY_ACCESS_FEATURE is provided.
References otawa::MEMORY_ACCESS_FEATURE.
void otawa::Process::get (Address at, float & val) virtual inherited
Get a float value from the process.
Parameters
at Address of the value to get.
val Got value.
Exceptions
UnsupportedFeatureException if this method is called but the loader does not provide this feature.
OutOfMemStaticException if the given address does not point to a static segment of the executable file.
Warning
To use this method, you must assert that the MEMORY_ACCESS_FEATURE is provided.
References otawa::MEMORY_ACCESS_FEATURE.
void otawa::Process::get (Address at, double & val) virtual inherited
Get a double value from the process.
Parameters
at Address of the value to get.
val Got value.
Exceptions
UnsupportedFeatureException if this method is called but the loader does not provide this feature.
OutOfMemStaticException if the given address does not point to a static segment of the executable file.
Warning
To use this method, you must assert that the MEMORY_ACCESS_FEATURE is provided.
References otawa::MEMORY_ACCESS_FEATURE.
void otawa::Process::get (Address at, long double & val) virtual inherited
Get a long double value from the process.
Parameters
at Address of the value to get.
val Got value.
Exceptions
UnsupportedFeatureException if this method is called but the loader does not provide this feature.
OutOfMemStaticException if the given address does not point to a static segment of the executable file.
Warning
To use this method, you must assert that the MEMORY_ACCESS_FEATURE is provided.
References otawa::Process::get(), and otawa::MEMORY_ACCESS_FEATURE.
virtual void otawa::loader::old_gliss::Process::getAddresses (cstring file, int line, Vector< Pair< Address, Address > > & addresses) throw (UnsupportedFeatureException) virtual
Get the list of addresses implementing the given (source, line) pair.
Parameters
file Looked source file.
line Looked source line.
addresses Output parameter containing the list of address ranges matching the given line. This vector is empty if the source (file, line) cannot be found.
Exceptions
UnsupportedFeatureException If this function is called and the feature SOURCE_LINE_FEATURE is not implemented.
Reimplemented from otawa::Process.
Referenced by state().
Property * otawa::PropList::getProp (const AbstractIdentifier * id) const inherited
Find a property by its identifier.
Parameters
id Identifier of the property to find.
Returns
Found property or null.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::Identifier< otawa::arm::Info * >::exists(), otawa::ContextualProperty::exists(), otawa::ContextualProperty::find(), otawa::Identifier< T >::get(), otawa::ContextualProperty::make(), otawa::ParamFeature::matches(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::print(), otawa::ContextualProperty::print(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), otawa::ContextualProperty::refProps(), otawa::Identifier< T >::set(), otawa::Identifier< T >::use(), and otawa::Identifier< T >::value().
virtual Option<Pair<cstring, int> > otawa::loader::old_gliss::Process::getSourceLine (Address addr) throw (UnsupportedFeatureException) virtual
Get the source file and the line matching the given address.
Parameters
addr Address to get source and line.
Returns
Optional (file, line) pair if the address is found.
Exceptions
UnsupportedFeatureException If this function is called and the feature SOURCE_LINE_FEATURE is not implemented.
Reimplemented from otawa::Process.
Referenced by state().
bool otawa::PropList::hasProp (const AbstractIdentifier & id) const inline inherited
Test if the property list contains a property matching the given identifier.
Parameters
id Property identifier to look for.
Returns
True if the list contains the matching property, false else.
References otawa::p::print().
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::Monitor::configure(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::exists(), and otawa::Manager::setVerbosity().
Address otawa::Process::initialSP (void) const virtual inherited
Get the initial address of the stack pointer.
If the program is embedded, this call does not return any meaningful value as the value is initialized at the program start. For program running in a rich OS environment, this is the value of the stack pointer after the OS has filled environment and program arguments.
Returns
Initial stack pointer address.
References otawa::Address::null.
int otawa::Process::instSize (void) const pure virtual inherited
Get the instruction size.
Returns
Instruction size or 0 for variable instruction size.
Referenced by otawa::VarTextDecoder::getInst(), otawa::ParExeGraph::ParExeGraph(), otawa::TextDecoder::processWorkSpace(), and otawa::FixedTextDecoder::setup().
virtual Loader* otawa::loader::old_gliss::Process::loader (void) const virtual
Get the loader that has created this process.
The result may be null.
Returns
Loader that created this process.
Reimplemented from otawa::Process.
Referenced by state().
virtual File* otawa::loader::old_gliss::Process::loadFile (elm::CString path) virtual
Implements otawa::Process.
Referenced by state().
File * otawa::Process::loadProgram (elm::CString path) inherited
Load the program file.
References otawa::Process::loadFile(), and otawa::Process::prog.
Manager * otawa::Process::manager (void) inline inherited
Get the manager owning this process.
Returns
Process manager.
References cache().
Referenced by otawa::ipet::ILPSystemGetter::processWorkSpace(), and otawa::Process::simulator().
int otawa::Process::maxTemp (void) const virtual inherited
Get the maximum number of temporaries used in the semantics instruction block.
Returns
Maximum number of temporaries.
virtual void* otawa::loader::old_gliss::Process::memory (void) protected pure virtual
Inst * otawa::Process::newNOp (Address addr = Address::null) virtual inherited
Build a NOP instruction at the given address.
Parameters
addr Address of the instruction (default to null address).
Returns
Built NOP instruction (must fried by deleteNop() call).
SimState * otawa::Process::newState (void) virtual inherited
Get a fresh startup state of the process for functional simulation.
Returns
Startup state, possibly null if the process does not support functional simulation/
virtual hard::Platform* otawa::loader::old_gliss::Process::platform (void) virtual
Get the platform of the process.
Returns
Process platform.
Implements otawa::Process.
Referenced by state().
void otawa::PropList::print (elm::io::Output & out) const inherited
Display the current property list.
Parameters
out Output to use.
Referenced by otawa::Edge::kindName(), otawa::operator<<(), and otawa::ContextualProperty::print().
File * otawa::Process::program (void) const inline inherited
Get the program file, that is, the startup executable of the process.
Returns
Program file.
References otawa::ot::address(), and name.
Referenced by otawa::ast::ASTLoader::findLabel(), otawa::ProcessException::message(), otawa::operator<<(), otawa::clp::operator<<(), otawa::ipet::ConstraintLoader::processCFG(), otawa::CFGBuilder::processWorkSpace(), otawa::ast::ASTLoader::processWorkSpace(), otawa::display::ILPSystemDisplayer::processWorkSpace(), otawa::FlowFactLoader::processWorkSpace(), and otawa::script::Script::work().
void otawa::Process::provide (AbstractFeature & feature) protected inherited
This method let provide feature from the loader / processors.
References otawa::Process::provided.
void otawa::PropList::removeAllProp (const AbstractIdentifier * id) inherited
Remove all the properties matching the given identifier.
Parameters
id Identifier of properties to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::LoopUnroller::unroll().
void otawa::PropList::removeProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier.
Parameters
id Identifier of the property to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::PSTBuilder::buildTree(), otawa::BBRemover< T >::clean(), otawa::CFGBuilder::cleanup(), otawa::display::CFGOutput::processCFG(), otawa::SubCFGBuilder::processWorkSpace(), otawa::Identifier< otawa::arm::Info * >::remove(), and otawa::ContextualPath::Ref< T >::remove().
void otawa::PropList::removeProp (const AbstractIdentifier & id) inline inherited
References otawa::PropList::removeProp().
Referenced by otawa::PropList::removeProp().
void otawa::Process::semInit (sem::Block & block) const virtual inherited
Provide semantic sequence to initialize the environment before performing static analysis.
As a default, do nothing.
Referenced by otawa::sem::PathIter::start().
void otawa::PropList::setProp (Property * prop) inherited
Set the property in the property list removing any double.
Parameters
prop Property to set.
References otawa::Property::_next, otawa::Property::id(), and otawa::Property::next().
void otawa::PropList::setProp (const AbstractIdentifier * id) inline inherited
References otawa::PropList::setProp().
Referenced by otawa::PropList::setProp().
sim::Simulator * otawa::Process::simulator (void) virtual inherited
Find the simulator used for the current process.
Returns
A simulator for the current process or null if none is found.
References otawa::Manager::findSimulator(), otawa::Process::manager(), name, otawa::SIMULATOR, and otawa::SIMULATOR_NAME.
Referenced by otawa::tsim::BBTimeSimulator::setup(), and otawa::tsim::BBPath::simulate().
virtual Inst* otawa::loader::old_gliss::Process::start (void) virtual
Get the address of the first instruction of the program.
Returns
Address of the first instruction of the program or null if it unknown.
Implements otawa::Process.
Referenced by state().
void* otawa::loader::old_gliss::Process::state (void) const inline
References _state, getAddresses(), getSourceLine(), loader(), loadFile(), platform(), and start().
Friends And Related Function Documentation
friend class Segment friend
Member Data Documentation
Loader* otawa::loader::old_gliss::Process::_loader
void* otawa::loader::old_gliss::Process::_memory
hard::Platform* otawa::loader::old_gliss::Process::_platform
Inst* otawa::loader::old_gliss::Process::_start
void* otawa::loader::old_gliss::Process::_state
Referenced by state().
int otawa::loader::old_gliss::Process::argc
char** otawa::loader::old_gliss::Process::argv
const PropList otawa::PropList::EMPTY static inherited
This is an empty proplist for convenience.
Referenced by otawa::DynProcessor::configure(), otawa::ActualFeature::processor(), otawa::SilentFeature::SilentFeature(), otawa::Processor::version(), and otawa::display::Driver::~Driver().
char ** otawa::loader::old_gliss::Process::envp
The documentation for this class was generated from the following file:
include/otawa/loader/old_gliss/Process.h