Otawa: otawa::ilp::Constraint Class Reference
otawa::ilp::Constraint Class Reference abstract
ILP -- Integer Linear Programming
This class is used to represent constraints in an ILP system with the following form:
#include <otawa/ilp/Constraint.h>
Classes
class TermIterator
Public Types
enum comparator_t {
UNDEF = -3, LT = -2, LE = -1, EQ = 0,
GE = 1, GT = 2
}
typedef otawa::ilp::Term Term
typedef enum otawa::ilp::Constraint::comparator_t comparator_t
Public Member Functions
virtual ~Constraint (void)
virtual double coefficient (Var *var=0) const =0
Get the coefficient for the given variable.
virtual double constant (void) const =0
virtual comparator_t comparator (void) const =0
Get the constraint comparator.
virtual const string & label (void) const =0
virtual void add (double coef, Var *var=0)=0
Add a term to the constraint to the left part of constraint.
virtual void sub (double coef, Var *var=0)=0
Substact a factor from the constraint.
virtual elm::datastruct::IteratorInst< Term > * terms (void)=0
void addLeft (double coef, Var *var=0)
Add a factor on the left side.
void addRight (double coef, Var *var=0)
Add a factor on the right side.
virtual void setComparator (comparator_t comp)=0
virtual void setLabel (const string &label)=0
void add (const Term &t)
void sub (const Term &t)
void add (const Expression &e)
void Constraint::setComparator(comparator_t comp); Change the comparator of the constraint.
void sub (const Expression &e)
Subtract an expression from the left part of the constraint.
Detailed Description
This class is used to represent constraints in an ILP system with the following form:
c1*x1 + c2*x2 + ... + cn*xn (=|<|>|<=|>=) k
c1, c2, ..., cn are the coefficients of terms.
x1, x2, ..., xn are the variables of terms.
c1*x1, c2*x2, ..., cn*xn are called the terms.
k is the constant part.
Member Typedef Documentation
typedef enum otawa::ilp::Constraint::comparator_t otawa::ilp::Constraint::comparator_t
typedef otawa::ilp::Term otawa::ilp::Constraint::Term
Member Enumeration Documentation
enum otawa::ilp::Constraint::comparator_t
Enumerator
UNDEF
LT
LE
EQ
GE
GT
Constructor & Destructor Documentation
virtual otawa::ilp::Constraint::~Constraint (void) inline virtual
References add(), coefficient(), comparator(), constant(), label(), sub(), and terms().
Member Function Documentation
void otawa::ilp::Constraint::add (double coef, Var * var = 0) pure virtual
Add a term to the constraint to the left part of constraint.
If var is null, sum the coefficient to the right part of the constraint.
Parameters
coef Coefficient of the factor.
var Variable of the factor. When null, modify the constant.
Implemented in otawa::ilp::ConstraintImpl, and otawa::ilp::AbstractConstraint.
Referenced by add(), otawa::ipet::ConstraintLoader::addConstraint(), addLeft(), addRight(), otawa::ilp::cons::operator+(), otawa::ilp::cons::operator+=(), otawa::cat::CATConstraintBuilder::processLBlockSet(), otawa::ccg::ConstraintBuilder::processLBlockSet(), sub(), and ~Constraint().
void otawa::ilp::Constraint::add (const Term & t) inline
References add(), otawa::ilp::Term::fst, and otawa::ilp::Term::snd.
Referenced by add().
void otawa::ilp::Constraint::add (const Expression & e)
void Constraint::setComparator(comparator_t comp); Change the comparator of the constraint.
Parameters
comp Comparator to set.
Since
ILP interface 1.2.0 void Constraint::setLabel(const string& label); Change the label of the constraint.
Parameters
label Label to set.
Since
ILP interface 1.2.0 Add an expression to the left part of the constraint.
Parameters
e Added expression.
References add().
void otawa::ilp::Constraint::addLeft (double coef, Var * var = 0) inline
Add a factor on the left side.
Parameters
coef Coefficient of the factor.
var Variable of the factor.
References add().
Referenced by otawa::ccg::ConstraintBuilder::addConstraintHeader(), otawa::etime::EdgeTimeBuilder::contributeSplit(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::ipet::CachePenaltiesObjectFunctionBuilder::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::tsim::Delta::processBBPath(), otawa::cat::CATConstraintBuilder::processLBlockSet(), otawa::ccg::ConstraintBuilder::processLBlockSet(), otawa::EdgeCAT2ConstraintBuilder::processWorkSpace(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), and otawa::dcache::CatConstraintBuilder::processWorkSpace().
void otawa::ilp::Constraint::addRight (double coef, Var * var = 0) inline
Add a factor on the right side.
Parameters
coef Coefficient of the factor.
var Variable of the factor.
References add(), label(), setComparator(), and setLabel().
Referenced by otawa::ccg::ConstraintBuilder::addConstraintHeader(), otawa::etime::EdgeTimeBuilder::contributeSplit(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::etime::EventCollector::make(), otawa::ipet::CachePenaltiesObjectFunctionBuilder::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::tsim::Delta::processBBPath(), otawa::cat::CATConstraintBuilder::processLBlockSet(), otawa::ccg::ConstraintBuilder::processLBlockSet(), otawa::EdgeCAT2ConstraintBuilder::processWorkSpace(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), and otawa::dcache::CatConstraintBuilder::processWorkSpace().
double otawa::ilp::Constraint::coefficient (Var * var = 0) const pure virtual
Get the coefficient for the given variable.
Parameters
var Variable to get the coefficent of. Null variable allows getting the constant part.
Returns
Variable coefficient.
Implemented in otawa::ilp::AbstractConstraint.
Referenced by ~Constraint().
Constraint::comparator_t otawa::ilp::Constraint::comparator (void) const pure virtual
Get the constraint comparator.
Returns
Constraint comparator.
Implemented in otawa::ilp::ConstraintImpl, and otawa::ilp::AbstractConstraint.
Referenced by otawa::display::ILPSystemDisplayer::displayCons(), otawa::ilp::System::dumpLPSolve(), and ~Constraint().
virtual double otawa::ilp::Constraint::constant (void) const pure virtual
Implemented in otawa::ilp::ConstraintImpl, and otawa::ilp::AbstractConstraint.
Referenced by otawa::display::ILPSystemDisplayer::displayCons(), otawa::ilp::System::dumpLPSolve(), and ~Constraint().
virtual const string& otawa::ilp::Constraint::label (void) const pure virtual
Implemented in otawa::ilp::ConstraintImpl, and otawa::ilp::AbstractConstraint.
Referenced by addRight(), otawa::display::ILPSystemDisplayer::displayCons(), otawa::ilp::System::dumpLPSolve(), and ~Constraint().
virtual void otawa::ilp::Constraint::setComparator (comparator_t comp) pure virtual
Referenced by addRight().
virtual void otawa::ilp::Constraint::setLabel (const string & label) pure virtual
Implemented in otawa::ilp::AbstractConstraint.
Referenced by addRight(), and otawa::ilp::model::operator()().
void otawa::ilp::Constraint::sub (double coef, Var * var = 0) pure virtual
Substact a factor from the constraint.
Parameters
coef Coefficient of the factor.
var Variable of the factor.
Implemented in otawa::ilp::ConstraintImpl, and otawa::ilp::AbstractConstraint.
Referenced by otawa::ilp::cons::operator-(), otawa::ilp::cons::operator-=(), sub(), and ~Constraint().
void otawa::ilp::Constraint::sub (const Term & t) inline
References add(), otawa::ilp::Term::fst, otawa::ilp::Term::snd, and sub().
Referenced by sub().
void otawa::ilp::Constraint::sub (const Expression & e)
Subtract an expression from the left part of the constraint.
Parameters
e Subtracted expression.
References sub().
virtual elm::datastruct::IteratorInst<Term>* otawa::ilp::Constraint::terms (void) pure virtual
Implemented in otawa::ilp::ConstraintImpl, and otawa::ilp::AbstractConstraint.
Referenced by otawa::ilp::System::dumpLPSolve(), and ~Constraint().
The documentation for this class was generated from the following files:
include/otawa/ilp/Constraint.h
src/prog/ilp_Constraint.cpp