Otawa: otawa::dfa::hai::WideningListener< P > Class Template Reference
otawa::dfa::hai::WideningListener< P > Class Template Reference
This listener gathers in an array the LUB of the in-states for all analyzed basic blocks.
#include <otawa/dfa/hai/WideningListener.h>
Public Types
typedef P Problem
Public Member Functions
WideningListener (WorkSpace *_fw, Problem &_prob, bool _store_out=false)
~WideningListener ()
void blockInterpreted (const WideningFixPoint< WideningListener > *fp, BasicBlock *bb, const typename Problem::Domain &in, const typename Problem::Domain &out, CFG *cur_cfg, elm::genstruct::Vector< Edge * > *callStack) const
This is called whenever a block is processed.
void fixPointReached (const WideningFixPoint< WideningListener > *fp, BasicBlock *bb)
This is called whenever a loop's fixpoint is reached.
Problem & getProb ()
Public Attributes
Problem::Domain *** results
Problem::Domain *** results_out
Static Public Attributes
static Identifier< typename Problem::Domain * > BB_OUT_STATE
PRIVATE - DO NOT USE.
Private Attributes
WorkSpace * fw
Problem & prob
bool store_out
Detailed Description
template<class P>
class otawa::dfa::hai::WideningListener< P >
This listener gathers in an array the LUB of the in-states for all analyzed basic blocks.
At the end of the analysis, you can access result[CFGNUMBER][BBNUMBER] to obtain the in-state of the basic block BBNUMBER of cfg CFGNUMBER.
Member Typedef Documentation
template<class P > typedef P otawa::dfa::hai::WideningListener< P >::Problem
Constructor & Destructor Documentation
template<class P > otawa::dfa::hai::WideningListener< P >::WideningListener (WorkSpace * _fw, Problem & _prob, bool _store_out = false) inline
References otawa::cfgio::cfg(), otawa::CFGCollection::count(), otawa::CFG::countBB(), otawa::dfa::hai::WideningListener< P >::fw, otawa::CFGCollection::get(), otawa::INVOLVED_CFGS, otawa::dfa::hai::WideningListener< P >::prob, and otawa::dfa::hai::WideningListener< P >::store_out.
template<class P > otawa::dfa::hai::WideningListener< P >::~WideningListener () inline
References otawa::cfgio::bb(), otawa::dfa::hai::WideningListener< P >::blockInterpreted(), otawa::cfgio::cfg(), otawa::CFGCollection::count(), otawa::CFG::countBB(), otawa::dfa::hai::WideningListener< P >::fixPointReached(), otawa::dfa::hai::WideningListener< P >::fw, otawa::CFGCollection::get(), otawa::INVOLVED_CFGS, otawa::dfa::hai::WideningListener< P >::results, otawa::dfa::hai::WideningListener< P >::results_out, and otawa::dfa::hai::WideningListener< P >::store_out.
Member Function Documentation
template<class Problem > void otawa::dfa::hai::WideningListener< P >::blockInterpreted (const WideningFixPoint< WideningListener< P > > * fp, BasicBlock * bb, const typename Problem::Domain & in, const typename Problem::Domain & out, CFG * cur_cfg, elm::genstruct::Vector< Edge * > * callStack) const
This is called whenever a block is processed.
In the WideningListener, we do the LUB of all the in-states of each block.
Parameters
fp The FixPoint object
bb The Basic Block
in In-state
out Out-state (not used in this class)
cur_cfg Current CFG
References otawa::dfa::hai::WideningListener< P >::BB_OUT_STATE, otawa::CFG::number(), otawa::BasicBlock::number(), otawa::dfa::hai::WideningListener< P >::prob, otawa::dfa::hai::WideningListener< P >::results, otawa::dfa::hai::WideningListener< P >::results_out, and otawa::dfa::hai::WideningListener< P >::store_out.
Referenced by otawa::dfa::hai::WideningListener< P >::~WideningListener().
template<class Problem > void otawa::dfa::hai::WideningListener< P >::fixPointReached (const WideningFixPoint< WideningListener< P > > * fp, BasicBlock * bb)
This is called whenever a loop's fixpoint is reached.
Parameters
fp The FixPoint object
bb The loop header.
Referenced by otawa::dfa::hai::WideningListener< P >::~WideningListener().
template<class P > Problem& otawa::dfa::hai::WideningListener< P >::getProb () inline
References otawa::dfa::hai::WideningListener< P >::prob.
Member Data Documentation
template<class P > Identifier< typename Problem::Domain * > otawa::dfa::hai::WideningListener< Problem >::BB_OUT_STATE static
PRIVATE - DO NOT USE.
Referenced by otawa::dfa::hai::WideningListener< P >::blockInterpreted().
template<class P > WorkSpace* otawa::dfa::hai::WideningListener< P >::fw private
Referenced by otawa::dfa::hai::WideningListener< P >::WideningListener(), and otawa::dfa::hai::WideningListener< P >::~WideningListener().
template<class P > Problem& otawa::dfa::hai::WideningListener< P >::prob private
Referenced by otawa::dfa::hai::WideningListener< P >::blockInterpreted(), otawa::dfa::hai::WideningListener< P >::getProb(), and otawa::dfa::hai::WideningListener< P >::WideningListener().
template<class P > Problem::Domain*** otawa::dfa::hai::WideningListener< P >::results
Referenced by otawa::dfa::hai::WideningListener< P >::blockInterpreted(), and otawa::dfa::hai::WideningListener< P >::~WideningListener().
template<class P > Problem::Domain*** otawa::dfa::hai::WideningListener< P >::results_out
Referenced by otawa::dfa::hai::WideningListener< P >::blockInterpreted(), and otawa::dfa::hai::WideningListener< P >::~WideningListener().
template<class P > bool otawa::dfa::hai::WideningListener< P >::store_out private
Referenced by otawa::dfa::hai::WideningListener< P >::blockInterpreted(), otawa::dfa::hai::WideningListener< P >::WideningListener(), and otawa::dfa::hai::WideningListener< P >::~WideningListener().
The documentation for this class was generated from the following files:
include/otawa/dfa/hai/WideningListener.h
src/prog/dfa_hai_WideningListener.cpp