Otawa: otawa::CachePenalty Class Reference
otawa::CachePenalty Class Reference
This class can be used to express the penalties due to the instruction cache.
#include <otawa/cache/cat2/CachePenalty.h>
Public Types
enum cache_penalty_type_t { MISS, MISS_MISS, HIT_MISS, x_HIT }
Public Member Functions
CachePenalty ()
void setHeader (int index, BasicBlock *bb)
BasicBlock * header (int index)
void setPenalty (cache_penalty_type_t type, int value)
int penalty (cache_penalty_type_t type)
void dump (elm::io::Output &out)
Private Attributes
BasicBlock * _header [2]
int _penalty [4]
Detailed Description
This class can be used to express the penalties due to the instruction cache.
Member Enumeration Documentation
enum otawa::CachePenalty::cache_penalty_type_t
Enumerator
MISS
MISS_MISS
HIT_MISS
x_HIT
Constructor & Destructor Documentation
otawa::CachePenalty::CachePenalty () inline
Member Function Documentation
void otawa::CachePenalty::dump (elm::io::Output & out) inline
References HIT_MISS, otawa::ICACHE_PENALTY, MISS, MISS_MISS, otawa::BasicBlock::number(), and x_HIT.
Referenced by otawa::GraphBBTime< G >::analyzePathContext().
BasicBlock* otawa::CachePenalty::header (int index) inline
Referenced by otawa::GraphBBTime< G >::analyzePathContext(), and otawa::ipet::CachePenaltiesObjectFunctionBuilder::processBB().
int otawa::CachePenalty::penalty (cache_penalty_type_t type) inline
References otawa::type().
Referenced by otawa::GraphBBTime< G >::analyzePathContext(), and otawa::ipet::CachePenaltiesObjectFunctionBuilder::processBB().
void otawa::CachePenalty::setHeader (int index, BasicBlock * bb) inline
References otawa::cfgio::bb().
Referenced by otawa::GraphBBTime< G >::analyzePathContext().
void otawa::CachePenalty::setPenalty (cache_penalty_type_t type, int value) inline
References otawa::type().
Referenced by otawa::GraphBBTime< G >::analyzePathContext().
Member Data Documentation
BasicBlock* otawa::CachePenalty::_header[2] private
int otawa::CachePenalty::_penalty[4] private
The documentation for this class was generated from the following file:
include/otawa/cache/cat2/CachePenalty.h