Otawa: otawa::ProcessorPlugin Class Reference
otawa::ProcessorPlugin Class Reference
This class must implemented by plugins containing processor, features and identifiers.
#include <otawa/proc/ProcessorPlugin.h>
Public Member Functions
ProcessorPlugin (cstring name, const elm::Version &version, const elm::Version &plugger_version)
Build a new processor plugin.
~ProcessorPlugin (void)
virtual elm::genstruct::Table< AbstractRegistration * > & processors (void) const
This method must return the table of all processor available in the plugin.
Static Public Member Functions
static void addPath (const elm::system::Path &path)
Add a path to the list of looked paths.
static void removePath (const elm::system::Path &path)
Remove the given path from the looked path.
static ProcessorPlugin * get (string name)
Find a plugin by its name.
static Processor * getProcessor (cstring name)
Get a processor by its name, possibly loading required plugin.
static AbstractFeature * getFeature (cstring name)
Find a feature by its name, possibly loading a plugin.
static AbstractIdentifier * getIdentifier (cstring name)
Find an identifier by its name possibly loading a plugin to get it.
static void setErrorHandler (ErrorHandler *error_handler)
Set an error handler for the processor resolution plugger.
static ErrorHandler * getErrorHandler (void)
Get the error handler of the processor resolution plugger.
Static Private Member Functions
static void init (void)
Initialize the plugger.
Detailed Description
This class must implemented by plugins containing processor, features and identifiers.
Constructor & Destructor Documentation
otawa::ProcessorPlugin::ProcessorPlugin (cstring name, const elm::Version & version, const elm::Version & plugger_version)
Build a new processor plugin.
Parameters
name Name of the plugin (may be full-qualified C++ name with "::" or canonical name with "/").
version Version of the plugin.
plugger_version Version for the plugger interface (OTAWA_PROC_VERSION).
otawa::ProcessorPlugin::~ProcessorPlugin (void)
Member Function Documentation
void otawa::ProcessorPlugin::addPath (const elm::system::Path & path) static
Add a path to the list of looked paths.
Parameters
path Path to add.
References init().
Referenced by otawa::script::Script::work().
ProcessorPlugin * otawa::ProcessorPlugin::get (string name) static
Find a plugin by its name.
The looked directories are, in order, "$PWD/.otawa/proc", "$HOME/.otawa/proc" or "$OTAWA_INSTALL_DIRECTORY/lib/otawa/proc". The full path name of the processor class must be passed in the name, something composed of "comp1::comp2::...::compn". First, a module whose path is by replacing in processor name "::" by "/" is looked. If not found, the last component of the path is removed and the obtained path is looked again for module. This process continue until the module is found or the path becomes empty resulting in a linkage failure.
Parameters
name Full-qualified name of the processor.
Returns
Built processor or null if the processor cannot be found.
References init().
ErrorHandler * otawa::ProcessorPlugin::getErrorHandler (void) static
Get the error handler of the processor resolution plugger.
Returns
Current error handler.
Referenced by otawa::script::Script::processWorkSpace().
AbstractFeature * otawa::ProcessorPlugin::getFeature (cstring name) static
Find a feature by its name, possibly loading a plugin.
Parameters
name Name of the looked feature.
Returns
Found feature or null.
References getIdentifier(), and otawa::IS_FEATURE.
Referenced by otawa::DynFeature::init().
AbstractIdentifier * otawa::ProcessorPlugin::getIdentifier (cstring name) static
Find an identifier by its name possibly loading a plugin to get it.
Parameters
name Name of the identifier.
Returns
Found identifier or null.
References otawa::AbstractIdentifier::find().
Referenced by otawa::XSLTScript::fillProps(), getFeature(), otawa::DynIdentifier< T >::id(), otawa::hard::Processor::instantiate(), otawa::script::Script::makeConfig(), and otawa::Application::run().
Processor * otawa::ProcessorPlugin::getProcessor (cstring name) static
Get a processor by its name, possibly loading required plugin.
Parameters
name Name of the looked processor.
Returns
An instance of the processor or NULL if it cannot be found.
References otawa::Registry::find(), otawa::AbstractRegistration::make(), and name.
Referenced by otawa::DynProcessor::DynProcessor().
void otawa::ProcessorPlugin::init (void) static private
Initialize the plugger.
References CSTR, otawa::MANAGER, and otawa::Manager::prefixPath().
Referenced by addPath(), get(), and removePath().
elm::genstruct::Table< AbstractRegistration * > & otawa::ProcessorPlugin::processors (void) const virtual
This method must return the table of all processor available in the plugin.
Returns
Table of available processors.
References elm::dtd::empty.
void otawa::ProcessorPlugin::removePath (const elm::system::Path & path) static
Remove the given path from the looked path.
Parameters
path Path to remove.
References init().
void otawa::ProcessorPlugin::setErrorHandler (ErrorHandler * error_handler) static
Set an error handler for the processor resolution plugger.
Parameters
error_handler New error handler.
Referenced by otawa::script::Script::processWorkSpace().
The documentation for this class was generated from the following files:
include/otawa/proc/ProcessorPlugin.h
src/prog/proc_ProcessorPlugin.cpp