Otawa: otawa::cat::CATProblem Class Reference
otawa::cat::CATProblem Class Reference
#include <otawa/cat/CATDFA.h>
Public Types
typedef CATDomain domain_t
Public Member Functions
CATDomain * empty (void)
CATDomain * gen (CFG *cfg, BasicBlock *bb)
CATDomain * preserve (CFG *cfg, BasicBlock *bb)
void free (CATDomain *d)
CATProblem (LBlockSet *point, int _size, const hard::Cache *mem, WorkSpace *_fw)
Private Attributes
LBlockSet * lines
const hard::Cache * cach
WorkSpace * fw
int size
Static Private Attributes
static int vars = 0
Member Typedef Documentation
typedef CATDomain otawa::cat::CATProblem::domain_t
Constructor & Destructor Documentation
otawa::cat::CATProblem::CATProblem (LBlockSet * point, int _size, const hard::Cache * mem, WorkSpace * _fw) inline
Member Function Documentation
CATDomain* otawa::cat::CATProblem::empty (void) inline
References otawa::cfgio::bb(), otawa::cat::CATDomain::CATDomain(), otawa::cfgio::cfg(), and otawa::cat::CATDomain::reset().
void otawa::cat::CATProblem::free (CATDomain * d) inline
CATDomain * otawa::cat::CATProblem::gen (CFG * cfg, BasicBlock * bb)
References otawa::dfa::BitSet::add(), otawa::ot::address(), otawa::dfa::BitSet::count(), and otawa::BasicBlock::isEntry().
CATDomain * otawa::cat::CATProblem::preserve (CFG * cfg, BasicBlock * bb)
References otawa::dfa::BitSet::complement(), otawa::dfa::BitSet::fill(), otawa::cat::CATBuilder::NON_CONFLICT, and otawa::dfa::BitSet::remove().
Member Data Documentation
const hard::Cache* otawa::cat::CATProblem::cach private
WorkSpace* otawa::cat::CATProblem::fw private
LBlockSet* otawa::cat::CATProblem::lines private
int otawa::cat::CATProblem::size private
int otawa::cat::CATProblem::vars = 0 static private
The documentation for this class was generated from the following files:
include/otawa/cat/CATDFA.h
src/cat/cat_CATDFA.cpp