Otawa: otawa::ast::ASTInfo Class Reference
otawa::ast::ASTInfo Class Reference
AST Plugin
This class stores all the function known for the current framework.
#include <otawa/ast/ASTInfo.h>
Classes
class Iterator
Public Member Functions
~ASTInfo (void)
FunAST * getFunction (Inst *inst)
Find the function at the given instruction.
void add (FunAST *fun)
Add a function to the AST information.
Option< FunAST * > get (const string &name)
Property * getProp (const AbstractIdentifier *id) const
Find a property by its identifier.
void setProp (Property *prop)
Set the property in the property list removing any double.
void setProp (const AbstractIdentifier *id)
void removeProp (const AbstractIdentifier *id)
Remove a property matching the given identifier.
void removeProp (const AbstractIdentifier &id)
Property * extractProp (const AbstractIdentifier *id)
Remove a property matching the given identifier and return it.
Property * extractProp (const AbstractIdentifier &id)
Remove a property matching the given identifier and return it.
void addProp (Property *prop)
Add property to the list without checking of duplication.
void removeAllProp (const AbstractIdentifier *id)
Remove all the properties matching the given identifier.
bool hasProp (const AbstractIdentifier &id) const
Test if the property list contains a property matching the given identifier.
void clearProps (void)
Remove all properties from the list.
void addProps (const PropList &props)
Add all properties from the given property list, in a reverse order.
void print (elm::io::Output &out) const
Display the current property list.
Static Public Member Functions
static ASTInfo * getInfo (WorkSpace *ws)
Find or create the AST information attached to the given process.
Static Public Attributes
static const PropList EMPTY
This is an empty proplist for convenience.
Private Member Functions
friend int::heptane_parse (void)
ASTInfo (WorkSpace *ws)
Build an new AST info linked to the given framework.
Private Attributes
elm::genstruct::Vector< FunAST * > funs
elm::genstruct::HashTable< String, FunAST * > _map
Friends
class CallAST
class FunAST
class GenericProperty< ASTInfo * >
Detailed Description
This class stores all the function known for the current framework.
It provides list access name mapped access.
Constructor & Destructor Documentation
otawa::ast::ASTInfo::~ASTInfo (void)
References funs.
otawa::ast::ASTInfo::ASTInfo (WorkSpace * ws) private
Build an new AST info linked to the given framework.
Parameters
ws Workspace to link to.
References otawa::PropList::addProp(), and otawa::ast::INFO.
Referenced by getInfo().
Member Function Documentation
void otawa::ast::ASTInfo::add (FunAST * fun)
Add a function to the AST information.
Parameters
fun Function to add.
References _map, funs, otawa::ast::FunAST::name(), and name.
Referenced by otawa::ast::FunAST::FunAST(), and otawa::ast::ASTInfo::Iterator::Iterator().
void otawa::PropList::addProp (Property * prop) inherited
Add property to the list without checking of duplication.
Parameters
prop Property to add.
References otawa::Property::_next.
Referenced by otawa::Identifier< T >::add(), ASTInfo(), otawa::Identifier< otawa::arm::Info * >::copy(), otawa::AbstractIdentifier::initProps(), otawa::ContextualProperty::make(), otawa::script::Script::makeConfig(), otawa::ccg::Builder::processLBlockSet(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), and otawa::ContextualProperty::refProps().
void otawa::PropList::addProps (const PropList & props) inherited
Add all properties from the given property list, in a reverse order.
Parameters
props Property list to clone.
References otawa::Property::copy(), otawa::PropList::head, and otawa::Property::next().
Referenced by otawa::display::CFGDrawer::CFGDrawer(), otawa::display::GraphVizGraph::GraphVizGraph(), otawa::ParamFeature::instantiate(), otawa::Manager::loadXML(), otawa::display::GraphVizGraph::newEdge(), otawa::display::GraphVizGraph::newNode(), otawa::Process::Process(), otawa::display::GraphVizItem::setProps(), otawa::VirtualBasicBlock::VirtualBasicBlock(), and otawa::VirtualCFG::VirtualCFG().
void otawa::PropList::clearProps (void) inherited
Remove all properties from the list.
References otawa::Property::next().
Referenced by otawa::PSTBuilder::getVCFG(), otawa::display::GraphVizItem::setProps(), and otawa::WorkSpace::~WorkSpace().
Property * otawa::PropList::extractProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::script::Script::makeConfig().
Property * otawa::PropList::extractProp (const AbstractIdentifier & id) inline inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::PropList::extractProp().
Referenced by otawa::PropList::extractProp().
Option<FunAST *> otawa::ast::ASTInfo::get (const string & name) inline
References _map, and name.
Referenced by otawa::ets::ACSComputation::applyProcess(), otawa::ets::CacheHitComputation::computation(), otawa::ets::CacheMissComputation::computation(), otawa::ets::CacheFirstMissComputation::computation(), otawa::ets::WCETComputation::computation(), otawa::ets::ACSComputation::initialization(), otawa::ets::FlowFactLoader::processAST(), and otawa::ets::TrivialAstBlockTime::processAST().
FunAST * otawa::ast::ASTInfo::getFunction (Inst * inst)
Find the function at the given instruction.
If no functions exsists, return a new created function.
Parameters
inst First instruction of the function.
Returns
Found or created AST function.
References otawa::ast::FUN, and FunAST.
Referenced by otawa::ast::CallAST::CallAST(), and otawa::ast::ASTLoader::makeBlock().
ASTInfo * otawa::ast::ASTInfo::getInfo (WorkSpace * ws) static
Find or create the AST information attached to the given process.
Parameters
ws Workspace to look in.
Returns
AST information of the process.
References ASTInfo(), and otawa::ast::INFO.
Referenced by otawa::ast::ASTLoader::makeBlock(), and otawa::ast::FunProcessor::processWorkSpace().
Property * otawa::PropList::getProp (const AbstractIdentifier * id) const inherited
Find a property by its identifier.
Parameters
id Identifier of the property to find.
Returns
Found property or null.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::Identifier< otawa::arm::Info * >::exists(), otawa::ContextualProperty::exists(), otawa::ContextualProperty::find(), otawa::Identifier< T >::get(), otawa::ContextualProperty::make(), otawa::ParamFeature::matches(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::print(), otawa::ContextualProperty::print(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), otawa::ContextualProperty::refProps(), otawa::Identifier< T >::set(), otawa::Identifier< T >::use(), and otawa::Identifier< T >::value().
bool otawa::PropList::hasProp (const AbstractIdentifier & id) const inline inherited
Test if the property list contains a property matching the given identifier.
Parameters
id Property identifier to look for.
Returns
True if the list contains the matching property, false else.
References otawa::p::print().
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::Monitor::configure(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::exists(), and otawa::Manager::setVerbosity().
otawa::ast::ASTInfo::int::heptane_parse (void) private
void otawa::PropList::print (elm::io::Output & out) const inherited
Display the current property list.
Parameters
out Output to use.
Referenced by otawa::Edge::kindName(), otawa::operator<<(), and otawa::ContextualProperty::print().
void otawa::PropList::removeAllProp (const AbstractIdentifier * id) inherited
Remove all the properties matching the given identifier.
Parameters
id Identifier of properties to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::LoopUnroller::unroll().
void otawa::PropList::removeProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier.
Parameters
id Identifier of the property to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::PSTBuilder::buildTree(), otawa::BBRemover< T >::clean(), otawa::CFGBuilder::cleanup(), otawa::display::CFGOutput::processCFG(), otawa::SubCFGBuilder::processWorkSpace(), otawa::Identifier< otawa::arm::Info * >::remove(), and otawa::ContextualPath::Ref< T >::remove().
void otawa::PropList::removeProp (const AbstractIdentifier & id) inline inherited
References otawa::PropList::removeProp().
Referenced by otawa::PropList::removeProp().
void otawa::PropList::setProp (Property * prop) inherited
Set the property in the property list removing any double.
Parameters
prop Property to set.
References otawa::Property::_next, otawa::Property::id(), and otawa::Property::next().
void otawa::PropList::setProp (const AbstractIdentifier * id) inline inherited
References otawa::PropList::setProp().
Referenced by otawa::PropList::setProp().
Friends And Related Function Documentation
friend class CallAST friend
friend class FunAST friend
Referenced by getFunction().
friend class GenericProperty< ASTInfo * > friend
Member Data Documentation
elm::genstruct::HashTable<String, FunAST *> otawa::ast::ASTInfo::_map private
Referenced by add(), and get().
const PropList otawa::PropList::EMPTY static inherited
This is an empty proplist for convenience.
Referenced by otawa::DynProcessor::configure(), otawa::ActualFeature::processor(), otawa::SilentFeature::SilentFeature(), otawa::Processor::version(), and otawa::display::Driver::~Driver().
elm::genstruct::Vector<FunAST *> otawa::ast::ASTInfo::funs private
Referenced by add(), and ~ASTInfo().
The documentation for this class was generated from the following files:
include/otawa/ast/ASTInfo.h
src/ast/ASTInfo.cpp