Otawa: otawa::sim::BasicBlockDriver Class Reference
otawa::sim::BasicBlockDriver Class Reference
This class is a simulator Driver that executes the instruction sequence found in a basic block.
#include <>>
Public Member Functions
BasicBlockDriver (BasicBlock *bb)
BasicBlockDriver constructor.
virtual Inst * nextInstruction (State &state, Inst *inst)
This method is called each time the simulator needs the next instruction to execute.
virtual void terminateInstruction (State &state, Inst *inst)
This method is called when an instruction is terminated.
virtual Address lowerRead (void)
Get the lower read address of the last executed instruction.
virtual Address upperRead (void)
Get the upper read address of the last executed instruction.
virtual Address lowerWrite (void)
Get the lower written address of the last executed instruction.
virtual Address upperWrite (void)
Get the upper written address of the last executed instruction.
virtual void redirect (State &state, Inst *branch, bool direction)
virtual bool PredictBranch (State &state, Inst *branch, bool pred)
Private Attributes
BasicBlock::InstIter inst
Detailed Description
This class is a simulator Driver that executes the instruction sequence found in a basic block.
Constructor & Destructor Documentation
otawa::sim::BasicBlockDriver::BasicBlockDriver (BasicBlock * bb) inline
BasicBlockDriver constructor.
Parameters
bb Basic block to simulate.
Member Function Documentation
Address otawa::sim::Driver::lowerRead (void) virtual inherited
Get the lower read address of the last executed instruction.
Returns
Lower read address.
References otawa::Address::null.
Address otawa::sim::Driver::lowerWrite (void) virtual inherited
Get the lower written address of the last executed instruction.
Returns
Lower written address.
References otawa::Address::null.
Inst * otawa::sim::BasicBlockDriver::nextInstruction (State & state, Inst * inst) virtual
This method is called each time the simulator needs the next instruction to execute.
Parameters
state Current state of the simulator.
inst Next instruction proposed by the simulator. If the simulator does not handle the semantics of instructions, it is juste the next instruction.
Returns
Next instruction to execute or null if there is no more instruction to execute.
Implements otawa::sim::Driver.
References otawa::BasicBlock::InstIter::ended(), inst, otawa::BasicBlock::InstIter::next(), and otawa::sim::State::stop().
virtual bool otawa::sim::Driver::PredictBranch (State & state, Inst * branch, bool pred) inline virtual inherited
virtual void otawa::sim::Driver::redirect (State & state, Inst * branch, bool direction) inline virtual inherited
void otawa::sim::BasicBlockDriver::terminateInstruction (State & state, Inst * inst) virtual
This method is called when an instruction is terminated.
Parameters
state Current state of the simulator.
inst Terminated instruction.
Implements otawa::sim::Driver.
Address otawa::sim::Driver::upperRead (void) virtual inherited
Get the upper read address of the last executed instruction.
Returns
Upper read address.
References otawa::Address::null.
Address otawa::sim::Driver::upperWrite (void) virtual inherited
Get the upper written address of the last executed instruction.
Returns
Lower written address.
References otawa::Address::null.
Member Data Documentation
BasicBlock::InstIter otawa::sim::BasicBlockDriver::inst private
Referenced by nextInstruction().
The documentation for this class was generated from the following files:
include/otawa/sim/BasicBlockDriver.h
src/prog/sim_BasicBlockDriver.cpp