Otawa: otawa::Property Class Reference
otawa::Property Class Reference
Properties System
A property associates a data with an identifier.
#include <otawa/prop/PropList.h>
Public Member Functions
Property (const AbstractIdentifier *id)
Build a new property with the given identifier.
Property (const AbstractIdentifier &id)
build a property from a static identifier.
Property (elm::CString name)
Build a property with the name of its identifier.
const AbstractIdentifier * id (void) const
Get the identifier code of the property.
Property * next (void) const
Get the next property.
template<class T >
const T & get (void) const
template<class T >
void set (const T &value)
virtual void print (elm::io::Output &out) const
Print the given property, that is, the identifier and its value if any.
Static Public Member Functions
static const AbstractIdentifier * getID (elm::CString name)
Allocate a new identifier matching the given name.
Protected Member Functions
virtual ~Property (void)
Virtual destructor for allowing destruction of any stored data.
virtual Property * copy (void)
This method is called when a property is copied.
Private Attributes
Property * _next
const AbstractIdentifier * _id
Friends
class PropList
Detailed Description
A property associates a data with an identifier.
They are stored in ProgObject and allow storage and retrieval of any data. For efficiency purpose, they use integer identifier that are associated with string names.
Constructor & Destructor Documentation
otawa::Property::~Property (void) inline protected virtual
Virtual destructor for allowing destruction of any stored data.
otawa::Property::Property (const AbstractIdentifier * _id) inline
Build a new property with the given identifier.
Parameters
_id Identifier of the property.
otawa::Property::Property (const AbstractIdentifier & _id) inline
build a property from a static identifier.
Parameters
_id Property identifier.
otawa::Property::Property (elm::CString name) inline
Build a property with the name of its identifier.
Parameters
name Name of the identifier.
Member Function Documentation
Property * otawa::Property::copy (void) inline protected virtual
This method is called when a property is copied.
It may be specialized by Property class children.
Returns
Copy of the current property.
Reimplemented in otawa::LockedProperty< T >, and otawa::GenericProperty< T >.
References name.
Referenced by otawa::PropList::addProps(), and otawa::ContextualProperty::refProps().
template<class T > const T & otawa::Property::get (void) const inline
const AbstractIdentifier * otawa::Property::getID (elm::CString name) static
Allocate a new identifier matching the given name.
Note that, if an identifier exists with the same name, its code will be returned ensuring consistency between name and code for identifiers.
Parameters
name Name of the identifier.
Returns
Allocated identifier code.
References otawa::display::find().
const Identifier * otawa::Property::id (void) const inline
Get the identifier code of the property.
Returns
Identifier code.
Referenced by otawa::GenericProperty< T >::copy(), otawa::LockedProperty< T >::copy(), and otawa::PropList::setProp().
Property * otawa::Property::next (void) const inline
Get the next property.
Returns
Next property.
References otawa::p::print().
Referenced by otawa::PropList::addProps(), otawa::PropList::clearProps(), otawa::PropList::extractProp(), otawa::PropList::getProp(), otawa::AbstractIdentifier::initProps(), otawa::PropList::Iter::next(), otawa::PropList::removeAllProp(), otawa::PropList::removeProp(), and otawa::PropList::setProp().
void otawa::Property::print (elm::io::Output & out) const virtual
Print the given property, that is, the identifier and its value if any.
Parameters
out Output to use.
References otawa::END().
Referenced by otawa::operator<<().
template<class T > void otawa::Property::set (const T & value) inline
References otawa::GenericProperty< T >::value().
Friends And Related Function Documentation
friend class PropList friend
Member Data Documentation
const AbstractIdentifier* otawa::Property::_id private
Property* otawa::Property::_next mutable private
Referenced by otawa::PropList::addProp(), otawa::PropList::extractProp(), otawa::PropList::getProp(), otawa::PropList::removeAllProp(), otawa::PropList::removeProp(), and otawa::PropList::setProp().
The documentation for this class was generated from the following files:
include/otawa/prop/PropList.h
include/otawa/prop/Property.h
src/prog/prop_PropList.cpp