Otawa: otawa::dfa::XCFGVisitor< P > Class Template Reference
otawa::dfa::XCFGVisitor< P > Class Template Reference
This class implements the visitor concept of XIterativeDFA class and allows applying an analysis on a collection of CFG in a flow-insensitive way.
#include <otawa/dfa/XCFGVisitor.h>
Classes
struct node_t
Public Types
typedef P::domain_t domain_t
typedef Pair< CFG *, BasicBlock * > key_t
Public Member Functions
XCFGVisitor (const CFGCollection &cfgs, P &domain)
Build the visitor to apply on the given domain and CFG collection.
~XCFGVisitor (void)
domain_t * empty (void)
void free (domain_t *d)
domain_t * gen (int node)
domain_t * preserve (int node)
int index (const key_t &key)
int size (void)
void visitPreds (XIterativeDFA< XCFGVisitor< P > > &engine, int node)
void visitSuccs (XIterativeDFA< XCFGVisitor< P > > &engine, int node)
Private Types
typedef struct otawa::dfa::XCFGVisitor::node_t node_t
Private Attributes
P & dom
const CFGCollection & cfgs
FragTable< node_t > nodes
int * offs
Vector< int > * preds
Detailed Description
template<class P>
class otawa::dfa::XCFGVisitor< P >
This class implements the visitor concept of XIterativeDFA class and allows applying an analysis on a collection of CFG in a flow-insensitive way.
Parameters
P Problem to resolve.
The problem concept must implements the following concept:
       typedef domain_t;                                                       // domain type
domain_t *empty(void);                                         // return an empty domain
       domain_t *gen(CFG *cfg, BasicBlock *bb);        // return the GEN value
    domain_t *kill(CFG *cfg, BasicBlock *bb);  // return the KILL value
    void free(domain_t *d);                                            // free the given domain
The domain_t type must implements the following concept:
    void reset(void);                  // reset the domain
void join(domain_t *d);                // join between current domain and given one.
void meet(domain_t *d);                // meet between current domain and given one.
    bool equals(domain_t *d);  // test if both domains are equals
Member Typedef Documentation
template<class P> typedef P::domain_t otawa::dfa::XCFGVisitor< P >::domain_t
template<class P> typedef Pair<CFG *, BasicBlock *> otawa::dfa::XCFGVisitor< P >::key_t
template<class P> typedef struct otawa::dfa::XCFGVisitor::node_t otawa::dfa::XCFGVisitor< P >::node_t private
Constructor & Destructor Documentation
template<class P> otawa::dfa::XCFGVisitor< P >::XCFGVisitor (const CFGCollection & cfgs, P & domain)
Build the visitor to apply on the given domain and CFG collection.
Parameters
cfgs CFG collection to work on.
problem Problem to resolve.
References otawa::cfgio::bb(), otawa::Edge::CALL, otawa::cfgio::called(), otawa::cfgio::cfg(), otawa::dfa::XCFGVisitor< P >::cfgs, otawa::cfgio::edge(), otawa::dfa::INDEX, otawa::dfa::XCFGVisitor< P >::nodes, otawa::BasicBlock::number(), otawa::dfa::XCFGVisitor< P >::offs, and otawa::dfa::XCFGVisitor< P >::preds.
template<class D > otawa::dfa::XCFGVisitor< D >::~XCFGVisitor (void)
References otawa::cfgio::cfg(), otawa::dfa::XCFGVisitor< P >::cfgs, otawa::dfa::XCFGVisitor< P >::offs, and otawa::dfa::XCFGVisitor< P >::preds.
Member Function Documentation
template<class P> domain_t* otawa::dfa::XCFGVisitor< P >::empty (void) inline
template<class P> void otawa::dfa::XCFGVisitor< P >::free (domain_t * d) inline
template<class P> domain_t* otawa::dfa::XCFGVisitor< P >::gen (int node) inline
References otawa::cfgio::bb(), and otawa::cfgio::cfg().
template<class P> int otawa::dfa::XCFGVisitor< P >::index (const key_t & key) inline
References otawa::dfa::INDEX, and otawa::INDEX.
template<class P> domain_t* otawa::dfa::XCFGVisitor< P >::preserve (int node) inline
References otawa::cfgio::bb(), and otawa::cfgio::cfg().
template<class P> int otawa::dfa::XCFGVisitor< P >::size (void) inline
template<class P> void otawa::dfa::XCFGVisitor< D >::visitPreds (XIterativeDFA< XCFGVisitor< P > > & engine, int node)
References otawa::dfa::XCFGVisitor< P >::node_t::bb, otawa::dfa::XCFGVisitor< P >::node_t::cfg, otawa::cfgio::edge(), otawa::dfa::XCFGVisitor< P >::node_t::from, otawa::BasicBlock::isEntry(), otawa::dfa::XCFGVisitor< P >::nodes, otawa::dfa::XCFGVisitor< P >::offs, and otawa::dfa::XCFGVisitor< P >::preds.
template<class P> void otawa::dfa::XCFGVisitor< D >::visitSuccs (XIterativeDFA< XCFGVisitor< P > > & engine, int node)
Member Data Documentation
template<class P> const CFGCollection& otawa::dfa::XCFGVisitor< P >::cfgs private
Referenced by otawa::dfa::XCFGVisitor< P >::XCFGVisitor(), and otawa::dfa::XCFGVisitor< P >::~XCFGVisitor().
template<class P> P& otawa::dfa::XCFGVisitor< P >::dom private
template<class P> FragTable<node_t> otawa::dfa::XCFGVisitor< P >::nodes private
Referenced by otawa::dfa::XCFGVisitor< P >::visitPreds(), and otawa::dfa::XCFGVisitor< P >::XCFGVisitor().
template<class P> int* otawa::dfa::XCFGVisitor< P >::offs private
Referenced by otawa::dfa::XCFGVisitor< P >::visitPreds(), otawa::dfa::XCFGVisitor< P >::XCFGVisitor(), and otawa::dfa::XCFGVisitor< P >::~XCFGVisitor().
template<class P> Vector<int>* otawa::dfa::XCFGVisitor< P >::preds private
Referenced by otawa::dfa::XCFGVisitor< P >::visitPreds(), otawa::dfa::XCFGVisitor< P >::XCFGVisitor(), and otawa::dfa::XCFGVisitor< P >::~XCFGVisitor().
The documentation for this class was generated from the following files:
include/otawa/dfa/XCFGVisitor.h
src/prog/dfa_XCFGVisitor.cpp