Otawa: otawa::XSLTScript Class Reference
otawa::XSLTScript Class Reference
This class provides a simple way to implement OTAWA script.
#include <otawa/util/XSLTScript.h>
Public Member Functions
XSLTScript (const elm::system::Path &path, Monitor &monitor=elm::monitor, bool verbosity=false) throw (otawa::Exception)
virtual ~XSLTScript (void)
xom::Document * document (void) const
void setConfiguration (cstring name="configuration")
Prepare the configuration of the script (in term of XSLT parameters).
void setConfiguration (xom::Element *element)
Prepare the configuration of the script (in term of XSLT parameters).
void addParam (string name, String value)
Add a parameter to the script.
void addParams (const PropList &props, Identifier< string > &id)
Look for parameter in the given property list.
void addParams (const PropList &props, Identifier< Pair< string, string > > &id)
Look for parameter in the given property list.
void transform (void) throw (otawa::Exception)
Perform the transformation.
void fillProps (PropList &props, xom::Element *element)
Fill the given property list with the property definitions found in the given element.
void fillProps (PropList &props, cstring name)
Fill the given property list with the property definitions found in the named element (at the top level).
Private Types
enum { ERROR, OPENED, TRANSFORMED }
Private Member Functions
void onWarning (xom::Node *node, const string &msg)
Handle an error.
void onError (xom::Node *node, const string &msg)
Handle an error.
Private Attributes
xom::Document * doc
xom::Document * xsl
xom::Element * temp
enum otawa::XSLTScript:: { ... } state
genstruct::Vector< Pair< string, string > > params
bool configured
bool verbose
Detailed Description
This class provides a simple way to implement OTAWA script.
Its behaviour may be easily customized to use the whole or a part of the OTAWA script format.
Parameters
path Path of the script.
monitor Monitor for IO.
verbosity Verbose messages if true.
Member Enumeration Documentation
anonymous enum private
Enumerator
ERROR
OPENED
TRANSFORMED
Constructor & Destructor Documentation
otawa::XSLTScript::XSLTScript (const elm::system::Path & path, Monitor & monitor = elm::monitor, bool verbosity = false) throw (otawa::Exception)
otawa::XSLTScript::~XSLTScript (void) virtual
Member Function Documentation
void otawa::XSLTScript::addParam (string name, String value)
Add a parameter to the script.
Parameters
name Parameter name.
value Paramater value.
void otawa::XSLTScript::addParams (const PropList & props, Identifier< string > & id)
Look for parameter in the given property list.
The parameters are retrieved from the property list using the identifier id that must be of type Identifier<string>. The parameter is represented in the form ID=VALUE.
Parameters
props Property list to look in.
id Property identifier.
Referenced by otawa::Manager::loadBin().
void otawa::XSLTScript::addParams (const PropList & props, Identifier< Pair< string, string > > & id)
Look for parameter in the given property list.
The parameters are retrieved from the property list using the identifier id that must be of type Identifier<Pair<string, string> >. First member of the pair is the identifier, the second the value.
Parameters
props Property list to look in.
id Property identifier.
xom::Document* otawa::XSLTScript::document (void) const inline
References name.
void otawa::XSLTScript::fillProps (PropList & props, xom::Element * element)
Fill the given property list with the property definitions found in the given element.
Parameters
props Property list to fill.
element Element to look property definition nin.
References otawa::p::config, otawa::ProcessorPlugin::getIdentifier(), name, and verbose().
Referenced by otawa::Manager::loadBin().
void otawa::XSLTScript::fillProps (PropList & props, cstring name)
Fill the given property list with the property definitions found in the named element (at the top level).
If the element does not exist, do nothing.
Parameters
props Property list to fill.
name Element name to look property definition nin.
References verbose().
void otawa::XSLTScript::onError (xom::Node * node, const string & msg) private
Handle an error.
Parameters
node Node causing the error.
msg Message to display.
void otawa::XSLTScript::onWarning (xom::Node * node, const string & msg) private
Handle an error.
Parameters
node Node causing the error.
msg Message to display.
void otawa::XSLTScript::setConfiguration (cstring name = "configuration")
Prepare the configuration of the script (in term of XSLT parameters).
Only allowed when the script document is opened but not transformed. Fails silently if no configuration is found.
Parameters
name Name of the top-level tag containing the configuration.
Referenced by otawa::Manager::loadBin().
void otawa::XSLTScript::setConfiguration (xom::Element * element)
Prepare the configuration of the script (in term of XSLT parameters).
Parameters
element Element to look in for items.
References name, and verbose().
void otawa::XSLTScript::transform (void) throw (otawa::Exception)
Perform the transformation.
References elm::dtd::empty, and verbose().
Referenced by otawa::Manager::loadBin().
Member Data Documentation
bool otawa::XSLTScript::configured private
xom::Document* otawa::XSLTScript::doc private
genstruct::Vector<Pair<string, string> > otawa::XSLTScript::params private
enum { ... } otawa::XSLTScript::state
xom::Element* otawa::XSLTScript::temp private
bool otawa::XSLTScript::verbose private
xom::Document * otawa::XSLTScript::xsl private
The documentation for this class was generated from the following files:
include/otawa/util/XSLTScript.h
src/prog/util_XSLTScript.cpp