Otawa: otawa::Manager Class Reference
otawa::Manager Class Reference
Program Representation
The manager class providesfacilities for storing, grouping and retrieving shared resources like loaders and platforms.
#include <otawa/prog/Manager.h>
Public Member Functions
Manager (void)
Manager builder.
~Manager (void)
Delete all used resources.
Loader * findLoader (elm::CString name)
Find the loader matching the given name.
sim::Simulator * findSimulator (elm::CString name)
Find the simulator matching the given name.
WorkSpace * load (const elm::system::Path &path, const PropList &props=PropList::EMPTY)
Load a file with the given path and the given properties.
WorkSpace * load (const PropList &props=PropList::EMPTY)
Load a computation configuration from the given properties.
WorkSpace * load (xom::Element *elem, const PropList &props=PropList::EMPTY)
Load the framework from an XML configuration.
ilp::System * newILPSystem (String plugin="")
Make an ILP system from the given plugin or from a named plugin.
elm::system::Path retrieveConfig (const elm::system::Path &path)
Retrieve the file XXX-config.xml matching the path of the given binary.
Loader * findFileLoader (const elm::system::Path &path)
Look for loader of the given path.
Static Public Member Functions
static elm::system::Path prefixPath (void)
Get the prefix path of the OTAWA installation, that is, the installation directory path that allows to retrieve other file resources of OTAWA.
static String buildPaths (cstring kind, string paths="")
Static Public Attributes
static const cstring OTAWA_NS = "http://www.irit.fr/recherches/ARCHI/MARCH"
Namespace of otawa elements in an OTAWA configuration file.
static const cstring OTAWA_NAME = "otawa"
Name of the top element in an OTAWA configuration file.
static const cstring PROCESSOR_NAME = "processor"
Name of the part describing a processor configuration in an OTAWA configuration file.
static const cstring CACHE_CONFIG_NAME = "cache-config"
Name of the XML element containing the cache configuration.
static const cstring MEMORY_NAME = "memory"
Name of the XML element containing the memory configuration.
static const cstring COMPILATION_DATE = OTAWA_DATE
Compilation date of this OTAWA library.
static const cstring VERSION = OTAWA_VERSION
Current version of sources OTAWA (VCS version).
static const cstring RELEASE_VERSION = _RELEASE_VERSION
Current release version of sources OTAWA.
Private Member Functions
WorkSpace * loadBin (const elm::system::Path &path, const PropList &props)
Load a binary file.
WorkSpace * loadXML (const elm::system::Path &path, const PropList &props)
Load an XML configuration file.
bool isVerbose (void)
void setVerbosity (const PropList &props)
void resetVerbosity (void)
Private Attributes
genstruct::Vector< hard::Platform * > platforms
elm::system::Plugger ilp_plugger
elm::system::Plugger loader_plugger
elm::system::Plugger sim_plugger
int verbose
Friends
class WorkSpace
Detailed Description
The manager class providesfacilities for storing, grouping and retrieving shared resources like loaders and platforms.
Constructor & Destructor Documentation
otawa::Manager::Manager (void)
Manager builder.
Install the PPC GLISS loader.
References resetVerbosity().
otawa::Manager::~Manager (void)
Delete all used resources.
References platforms.
Member Function Documentation
String otawa::Manager::buildPaths (cstring kind, string paths = "") static
References kind.
Referenced by prefixPath().
Loader * otawa::Manager::findFileLoader (const elm::system::Path & path)
Look for loader of the given path.
Parameters
path Path to the looked file.
Returns
Found loader or NULL.
References findLoader(), isVerbose(), loader_plugger, name, and resetVerbosity().
Referenced by retrieveConfig().
Loader * otawa::Manager::findLoader (elm::CString name)
Find the loader matching the given name.
Parameters
name Name of the loader to find.
Returns
Found loader or null.
Note
This function should also perform dynamic loading of shared library.
References loader_plugger.
Referenced by findFileLoader(), and loadBin().
sim::Simulator * otawa::Manager::findSimulator (elm::CString name)
Find the simulator matching the given name.
Parameters
name Name of the simulator to load.
References sim_plugger.
Referenced by otawa::Process::simulator().
bool otawa::Manager::isVerbose (void) private
References verbose().
Referenced by findFileLoader(), loadBin(), and loadXML().
WorkSpace * otawa::Manager::load (const elm::system::Path & path, const PropList & props = PropList::EMPTY)
Load a file with the given path and the given properties.
Parameters
path Path of the file to load.
props Configuration properties.
Returns
The loaded workspace or null.
The configuration properties may be :
ARGC,
ARGV,
CACHE_CONFIG,
CACHE_CONFIG_ELEMENT,
CACHE_CONFIG_PATH,
CONFIG_ELEMENT (experimental),
CONFIG_PATH (experimental),
ENVP,
LOAD_PARAM,
LOADER,
LOADER_NAME,
NO_STACK,
NO_SYSTEM,
MEMORY_ELEMENT
MEMORY_OBJECT
MEMORY_PATH
PIPELINE_DEPTH,
PLATFORM,
PLATFORM_NAME,
PROCESSOR,
PROCESSOR_ELEMENT,
PROCESSOR_PATH,
SIMULATOR,
SIMULATOR_NAME,
TASK_ADDRESS,
TASK_ENTRY.
This call try to link a plugin matching the Instruction Set Architecture of the loaded binary file. This plugin is looked in the following directories:
$HOME/.otawa/loader
$PWD/.otawa/loader
<installation directory>="">/lib/otawa/loader
The two first cases let the user to provide their own plugin for, as an example, to develop a new loader plugin.
References otawa::CONFIG_ELEMENT, loadBin(), loadXML(), and setVerbosity().
Referenced by load(), and otawa::Application::run().
WorkSpace * otawa::Manager::load (const PropList & props = PropList::EMPTY)
Load a computation configuration from the given properties.
Parameters
props Configuration properties.
Returns
Load workspace.
Exceptions
LoadException Error during load.
References otawa::CONFIG_ELEMENT, otawa::CONFIG_PATH, load(), and resetVerbosity().
WorkSpace * otawa::Manager::load (xom::Element * elem, const PropList & props = PropList::EMPTY)
Load the framework from an XML configuration.
Parameters
elem Top element of the configuration.
props Configuration properties.
Returns
Built workspace.
Exceptions
LoadException Error during load.
References loadBin(), and resetVerbosity().
WorkSpace * otawa::Manager::loadBin (const elm::system::Path & path, const PropList & props) private
Load a binary file.
Parameters
path Path to the binary file.
props Configuration properties.
Returns
Built framework.
Exceptions
LoadException Error during load.
References otawa::XSLTScript::addParams(), otawa::XSLTScript::fillProps(), findLoader(), isVerbose(), otawa::Loader::load(), otawa::LOAD_PARAM, otawa::LOADER, otawa::LOADER_NAME, loader_plugger, otawa::Processor::LOG, name, prefixPath(), resetVerbosity(), otawa::XSLTScript::setConfiguration(), setVerbosity(), otawa::XSLTScript::transform(), and WorkSpace.
Referenced by load(), and loadXML().
WorkSpace * otawa::Manager::loadXML (const elm::system::Path & path, const PropList & props) private
Load an XML configuration file.
Parameters
path Path of the XML file.
props Property to install the configuration in.
Returns
Loaded workspace.
Exceptions
LoadException Error during load.
References otawa::PropList::addProps(), otawa::CONFIG_ELEMENT, isVerbose(), loadBin(), OTAWA_NS, resetVerbosity(), and setVerbosity().
Referenced by load().
ilp::System * otawa::Manager::newILPSystem (String plugin = "")
Make an ILP system from the given plugin or from a named plugin.
Parameters
name Name of the plugin to use or an empty string for the default plugin.
Returns
A new ILP system ready to use or null (plugin not available).
References ilp_plugger, and otawa::ilp::ILPPlugin::newSystem().
Referenced by otawa::WorkSpace::newILPSystem(), and otawa::ipet::ILPSystemGetter::processWorkSpace().
elm::system::Path otawa::Manager::prefixPath (void) static
Get the prefix path of the OTAWA installation, that is, the installation directory path that allows to retrieve other file resources of OTAWA.
Returns
Prefix path.
References otawa::ARGC, otawa::ARGV, buildPaths(), otawa::CACHE_CONFIG, otawa::CACHE_CONFIG_ELEMENT, otawa::CACHE_CONFIG_PATH, otawa::CONFIG_ELEMENT, otawa::CONFIG_PATH, otawa::ENVP, otawa::LOADER, otawa::LOADER_NAME, otawa::MEMORY_ELEMENT, otawa::MEMORY_OBJECT, otawa::MEMORY_PATH, otawa::NO_RETURN_FUNCTION, otawa::NO_STACK, otawa::NO_SYSTEM, otawa::Address::null, otawa::PIPELINE_DEPTH, otawa::PLATFORM, otawa::PLATFORM_IDENTFIER, otawa::PLATFORM_NAME, otawa::PROCESSOR, otawa::PROCESSOR_ELEMENT, otawa::PROCESSOR_ID, otawa::PROCESSOR_PATH, otawa::SIMULATOR, otawa::SIMULATOR_NAME, otawa::TASK_ADDRESS, and otawa::TASK_ENTRY.
Referenced by otawa::ProcessorPlugin::init(), and loadBin().
void otawa::Manager::resetVerbosity (void) private
References verbose().
Referenced by findFileLoader(), load(), loadBin(), loadXML(), and Manager().
elm::system::Path otawa::Manager::retrieveConfig (const elm::system::Path & path)
Retrieve the file XXX-config.xml matching the path of the given binary.
XXX is usually the name of the instruction set.
Parameters
Path to the binary.
Returns
Path to the configuration file if any, false else.
References findFileLoader().
void otawa::Manager::setVerbosity (const PropList & props) private
References otawa::PropList::hasProp(), otawa::Processor::VERBOSE, and verbose().
Referenced by load(), loadBin(), and loadXML().
Friends And Related Function Documentation
friend class WorkSpace friend
Referenced by loadBin().
Member Data Documentation
const CString otawa::Manager::CACHE_CONFIG_NAME = "cache-config" static
Name of the XML element containing the cache configuration.
Referenced by otawa::hard::Platform::configure().
const cstring otawa::Manager::COMPILATION_DATE = OTAWA_DATE static
Compilation date of this OTAWA library.
elm::system::Plugger otawa::Manager::ilp_plugger private
Referenced by newILPSystem().
elm::system::Plugger otawa::Manager::loader_plugger private
Referenced by findFileLoader(), findLoader(), and loadBin().
const CString otawa::Manager::MEMORY_NAME = "memory" static
Name of the XML element containing the memory configuration.
Referenced by otawa::hard::Platform::configure().
const CString otawa::Manager::OTAWA_NAME = "otawa" static
Name of the top element in an OTAWA configuration file.
const CString otawa::Manager::OTAWA_NS = "http://www.irit.fr/recherches/ARCHI/MARCH" static
Namespace of otawa elements in an OTAWA configuration file.
Referenced by otawa::hard::Platform::configure(), and loadXML().
genstruct::Vector<hard::Platform *> otawa::Manager::platforms private
Referenced by ~Manager().
const CString otawa::Manager::PROCESSOR_NAME = "processor" static
Name of the part describing a processor configuration in an OTAWA configuration file.
Referenced by otawa::hard::Platform::configure().
const cstring otawa::Manager::RELEASE_VERSION = _RELEASE_VERSION static
Current release version of sources OTAWA.
elm::system::Plugger otawa::Manager::sim_plugger private
Referenced by findSimulator().
int otawa::Manager::verbose private
const cstring otawa::Manager::VERSION = OTAWA_VERSION static
Current version of sources OTAWA (VCS version).
The documentation for this class was generated from the following files:
include/otawa/prog/Manager.h
src/prog/manager.cpp