Otawa: otawa::ParamExeNode Class Reference
otawa::ParamExeNode Class Reference
#include <otawa/exegraph/ParamExeGraph.h>
Public Member Functions
ParamExeNode (ExeGraph< ParamExeNode > *graph, PipelineStage< ParamExeNode > *stage, ExeInst< ParamExeNode > *inst)
elm::genstruct::SLList< elm::BitVector * > * contendersMasksList ()
elm::BitVector * possibleContenders ()
int lateContenders ()
void setLateContenders (int num)
void initContenders (int size)
bool isContender (int index)
void setContender (int index)
int contendersNumber ()
void buildContendersMasks ()
void addConflict (ParamExeGraph::InternalConflictResource *conflict)
elm::genstruct::SLList< ParamExeGraph::InternalConflictResource * > * conflictList ()
void setStageNumber (int number)
int stageNumber ()
bool hasContenders ()
int d (int index, ExeGraph< ParamExeNode >::time_bound_t bound)
int d (int index)
bool e (int index)
void setD (int index, int value, ExeGraph< ParamExeNode >::time_bound_t bound)
void setD (int index, int value)
void setE (int index, bool value)
int maxContentionDelay ()
void setMaxContentionDelay (int value)
int minContentionDelay ()
void setMinContentionDelay (int value)
int delay (int index, ExeGraph< ParamExeNode >::time_bound_t bound)
bool contentionDep (int index)
int internalDelay (ExeGraph< ParamExeNode >::time_bound_t bound)
int contentionDelay (ExeGraph< ParamExeNode >::time_bound_t bound)
void setDelay (int index, ExeGraph< ParamExeNode >::time_bound_t bound, int delay)
void setContentionDep (int index)
void setInternalDelay (ExeGraph< ParamExeNode >::time_bound_t bound, int delay)
void setContentionDelay (ExeGraph< ParamExeNode >::time_bound_t bound, int delay)
PipelineStage< N > * pipelineStage (void)
ExeInst< N > * inst (void)
int latency ()
int latency (time_bound_t bound)
void setLatency (time_bound_t bound, int latency)
bool needsOperands (void)
void setNeedsOperands (bool val)
Sets whether the node depends on input operands.
bool producesOperands (void)
void setProducesOperands (bool val)
Sets whether the node produces output operands.
void addContender (N *cont)
Adds a contender to the lists of contenders for the node.
elm::genstruct::Vector< N * > * contenders ()
elm::String name ()
Returns the name of the node, composed of the name of the pipeline stage and the name of the instruction (e.g.
int index (void) const
bool hasSucc (void) const
bool hasPred (void) const
int countSucc (void) const
int countPred (void) const
bool isPredOf (const GenNode *node)
bool isSuccOf (const GenNode *node)
Protected Attributes
elm::genstruct::Vector< N * > _contenders
Private Attributes
ParamExeGraph * _graph
elm::genstruct::AllocatedTable< int > * _d [ExeGraph< ParamExeNode >::BOUNDS]
int _max_contention_delay
int _min_contention_delay
int _stage_number
elm::genstruct::AllocatedTable< bool > * _contention_dep
elm::genstruct::AllocatedTable< int > * _delay [ExeGraph< ParamExeNode >::BOUNDS]
int _internal_delay [ExeGraph< ParamExeNode >::BOUNDS]
int _contention_delay [ExeGraph< ParamExeNode >::BOUNDS]
elm::genstruct::SLList< ParamExeGraph::InternalConflictResource * > _contenders_list
elm::BitVector * _possible_contenders
elm::genstruct::SLList< elm::BitVector * > _contenders_masks_list
int _late_contenders
Constructor & Destructor Documentation
otawa::ParamExeNode::ParamExeNode (ExeGraph< ParamExeNode > * graph, PipelineStage< ParamExeNode > * stage, ExeInst< ParamExeNode > * inst) inline
References _contention_delay, _contention_dep, _d, _delay, _graph, _internal_delay, _max_contention_delay, _min_contention_delay, INFINITE_TIME, otawa::ParamExeGraph::instructionCount(), otawa::ExeGraph< N >::ExeNode::pipelineStage(), and otawa::ParamExeGraph::resourceCount().
Member Function Documentation
void otawa::ParamExeNode::addConflict (ParamExeGraph::InternalConflictResource * conflict) inline
template<class N> void otawa::ExeGraph< N >::ExeNode::addContender (N * cont) inline inherited
Adds a contender to the lists of contenders for the node.
Parameters
cont The new contender for the node.
void ParamExeNode::buildContendersMasks ()
elm::genstruct::SLList<ParamExeGraph::InternalConflictResource *>* otawa::ParamExeNode::conflictList () inline
template<class N> elm::genstruct::Vector< N * > * otawa::ExeGraph< N >::ExeNode::contenders (void) inline inherited
Returns
The list of contenders of the node.
elm::genstruct::SLList<elm::BitVector *>* otawa::ParamExeNode::contendersMasksList () inline
Referenced by otawa::ParamExeGraph::Delta().
int otawa::ParamExeNode::contendersNumber () inline
int otawa::ParamExeNode::contentionDelay (ExeGraph< ParamExeNode >::time_bound_t bound) inline
bool otawa::ParamExeNode::contentionDep (int index) inline
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::countPred (void) const inline inherited
References otawa::graph::Node::countPred().
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::countSucc (void) const inline inherited
References otawa::graph::Node::countSucc().
int otawa::ParamExeNode::d (int index, ExeGraph< ParamExeNode >::time_bound_t bound) inline
Referenced by otawa::ParamExeGraph::cost(), and otawa::ParamExeGraph::Delta().
int otawa::ParamExeNode::d (int index) inline
int otawa::ParamExeNode::delay (int index, ExeGraph< ParamExeNode >::time_bound_t bound) inline
bool otawa::ParamExeNode::e (int index) inline
Referenced by otawa::ParamExeGraph::cost(), and otawa::ParamExeGraph::Delta().
bool otawa::ParamExeNode::hasContenders () inline
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::hasPred (void) const inline inherited
References otawa::graph::Node::hasPred().
Referenced by otawa::LiExeGraph::shadeNodes().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::hasSucc (void) const inline inherited
References otawa::graph::Node::hasSucc().
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::index (void) const inline inherited
References otawa::graph::Node::index().
Referenced by otawa::ParamExeGraph::cost().
void otawa::ParamExeNode::initContenders (int size) inline
template<class N> ExeInst< N > * otawa::ExeGraph< N >::ExeNode::inst (void) inline inherited
Returns
The instruction the node is related to.
References otawa::ExeInst< N >::_inst.
Referenced by otawa::ParamExeGraph::analyzeContentions(), otawa::LiExeGraph::maxTimeToNode(), otawa::LiExeGraph::nodeEarliestTimes(), and otawa::LiExeGraph::nodeLatestTimes().
int otawa::ParamExeNode::internalDelay (ExeGraph< ParamExeNode >::time_bound_t bound) inline
bool otawa::ParamExeNode::isContender (int index) inline
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::isPredOf (const GenNode * node) inline inherited
References otawa::graph::Node::countPred().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::isSuccOf (const GenNode * node) inline inherited
References otawa::graph::Node::isSuccOf().
int otawa::ParamExeNode::lateContenders () inline
Referenced by otawa::ParamExeGraph::Delta().
template<class N> int otawa::ExeGraph< N >::ExeNode::latency () inline inherited
Returns
The minimum node latency.
Referenced by otawa::LiExeGraph::analyze(), otawa::ParamExeGraph::Delta(), otawa::LiExeGraph::latestTimes(), otawa::LiExeGraph::maxTimeToNode(), otawa::LiExeGraph::nodeEarliestTimes(), and otawa::LiExeGraph::nodeLatestTimes().
template<class N> int otawa::ExeGraph< N >::ExeNode::latency (time_bound_t bound) inline inherited
Parameters
bound A time bound (MIN or MAX).
Returns
The node latency.
int otawa::ParamExeNode::maxContentionDelay () inline
int otawa::ParamExeNode::minContentionDelay () inline
template<class N> elm::String otawa::ExeGraph< N >::ExeNode::name (void) inline inherited
Returns the name of the node, composed of the name of the pipeline stage and the name of the instruction (e.g.
"CM(I8)").
Returns
Node name.
Referenced by otawa::ParamExeGraph::Delta().
template<class N> bool otawa::ExeGraph< N >::ExeNode::needsOperands (void) inline inherited
Returns
Whether the node depends on input operands.
template<class N> PipelineStage< N > otawa::ExeGraph< N >::ExeNode::pipelineStage (void) inline inherited
Returns
The pipeline stage the node is related to.
Referenced by otawa::ParamExeGraph::Delta(), otawa::LiExeGraph::nodeEarliestTimes(), otawa::LiExeGraph::nodeLatestTimes(), and ParamExeNode().
elm::BitVector* otawa::ParamExeNode::possibleContenders () inline
template<class N> bool otawa::ExeGraph< N >::ExeNode::producesOperands (void) inline inherited
Returns
Whether the node produces output operands.
void otawa::ParamExeNode::setContender (int index) inline
void otawa::ParamExeNode::setContentionDelay (ExeGraph< ParamExeNode >::time_bound_t bound, int delay) inline
References otawa::ParamExeGraph::setTimesChanged().
void otawa::ParamExeNode::setContentionDep (int index) inline
void otawa::ParamExeNode::setD (int index, int value, ExeGraph< ParamExeNode >::time_bound_t bound) inline
void otawa::ParamExeNode::setD (int index, int value) inline
void otawa::ParamExeNode::setDelay (int index, ExeGraph< ParamExeNode >::time_bound_t bound, int delay) inline
References otawa::ParamExeGraph::setTimesChanged().
void otawa::ParamExeNode::setE (int index, bool value) inline
Referenced by otawa::ParamExeGraph::initDelays().
void otawa::ParamExeNode::setInternalDelay (ExeGraph< ParamExeNode >::time_bound_t bound, int delay) inline
References otawa::ParamExeGraph::setTimesChanged().
void otawa::ParamExeNode::setLateContenders (int num) inline
template<class N> void otawa::ExeGraph< N >::ExeNode::setLatency (time_bound_t bound, int latency) inline inherited
Parameters
bound A time bound (MIN or MAX).
latency The new value of the latency.
void otawa::ParamExeNode::setMaxContentionDelay (int value) inline
void otawa::ParamExeNode::setMinContentionDelay (int value) inline
template<class N> void otawa::ExeGraph< N >::ExeNode::setNeedsOperands (bool val) inline inherited
Sets whether the node depends on input operands.
template<class N> void otawa::ExeGraph< N >::ExeNode::setProducesOperands (bool val) inline inherited
Sets whether the node produces output operands.
void otawa::ParamExeNode::setStageNumber (int number) inline
int otawa::ParamExeNode::stageNumber () inline
Member Data Documentation
template<class N> elm::genstruct::Vector<N *> otawa::ExeGraph< N >::ExeNode::_contenders protected inherited
elm::genstruct::SLList<ParamExeGraph::InternalConflictResource *> otawa::ParamExeNode::_contenders_list private
elm::genstruct::SLList<elm::BitVector *> otawa::ParamExeNode::_contenders_masks_list private
int otawa::ParamExeNode::_contention_delay[ExeGraph< ParamExeNode >::BOUNDS] private
Referenced by ParamExeNode().
elm::genstruct::AllocatedTable<bool>* otawa::ParamExeNode::_contention_dep private
Referenced by ParamExeNode().
elm::genstruct::AllocatedTable<int>* otawa::ParamExeNode::_d[ExeGraph< ParamExeNode >::BOUNDS] private
Referenced by ParamExeNode().
elm::genstruct::AllocatedTable<int>* otawa::ParamExeNode::_delay[ExeGraph< ParamExeNode >::BOUNDS] private
Referenced by ParamExeNode().
ParamExeGraph* otawa::ParamExeNode::_graph private
Referenced by ParamExeNode().
int otawa::ParamExeNode::_internal_delay[ExeGraph< ParamExeNode >::BOUNDS] private
Referenced by ParamExeNode().
int otawa::ParamExeNode::_late_contenders private
int otawa::ParamExeNode::_max_contention_delay private
Referenced by ParamExeNode().
int otawa::ParamExeNode::_min_contention_delay private
Referenced by ParamExeNode().
elm::BitVector* otawa::ParamExeNode::_possible_contenders private
int otawa::ParamExeNode::_stage_number private
The documentation for this class was generated from the following files:
include/otawa/exegraph/ParamExeGraph.h
src/prog/exegraph_ParamExeGraph.cpp