Otawa: otawa::GenGraph< N, E >::GenNode Class Reference
otawa::GenGraph< N, E >::GenNode Class Reference
#include <otawa/graph/GenGraph.h>
Public Member Functions
int index (void) const
bool hasSucc (void) const
bool hasPred (void) const
int countSucc (void) const
int countPred (void) const
bool isPredOf (const GenNode *node)
bool isSuccOf (const GenNode *node)
Protected Member Functions
GenNode (graph::Graph *graph=0)
virtual ~GenNode (void)
Private Member Functions
Graph * graph (void) const
Get the container graph if any.
bool isPredOf (const Node *node)
Test if the current node is a predecessor of the given one.
bool isSuccOf (const Node *node)
Test if the current node is a successor of the given one.
Friends
class GenGraph< N, E >
Constructor & Destructor Documentation
template<class N, class E> otawa::GenGraph< N, E >::GenNode::GenNode (graph::Graph * graph = 0) inline protected
template<class N, class E> virtual otawa::GenGraph< N, E >::GenNode::~GenNode (void) inline protected virtual
Member Function Documentation
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::countPred (void) const inline
References otawa::graph::Node::countPred().
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::countSucc (void) const inline
References otawa::graph::Node::countSucc().
Graph * otawa::graph::Node::graph (void) const inline inherited
Get the container graph if any.
Returns
Container graph or null.
References otawa::graph::Node::_graph.
Referenced by otawa::graph::Edge::Edge(), and otawa::graph::Graph::remove().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::hasPred (void) const inline
References otawa::graph::Node::hasPred().
Referenced by otawa::LiExeGraph::shadeNodes().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::hasSucc (void) const inline
References otawa::graph::Node::hasSucc().
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::index (void) const inline
References otawa::graph::Node::index().
Referenced by otawa::ParamExeGraph::cost().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::isPredOf (const GenNode * node) inline
References otawa::graph::Node::countPred().
bool otawa::graph::Node::isPredOf (const Node * node) inline inherited
Test if the current node is a predecessor of the given one.
Parameters
node Node to test.
Returns
True if the current is a predecessor, false else.
Referenced by otawa::graph::Node::countPred().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::isSuccOf (const GenNode * node) inline
References otawa::graph::Node::isSuccOf().
bool otawa::graph::Node::isSuccOf (const Node * node) inline inherited
Test if the current node is a successor of the given one.
Parameters
node Node to test.
Returns
True if the current is a successor, false else.
Referenced by otawa::graph::Node::countPred(), and otawa::GenGraph< N, E >::GenNode::isSuccOf().
Friends And Related Function Documentation
template<class N, class E> friend class GenGraph< N, E > friend
The documentation for this class was generated from the following file:
include/otawa/graph/GenGraph.h