Otawa: otawa::sem::Printer Class Reference
otawa::sem::Printer Class Reference
Semantic Instructions
Printer class for semantic instructions (resolve the generic register value to the their real platform name).
#include <otawa/sem/inst.h>
Public Member Functions
Printer (const hard::Platform *platform=0)
void print (elm::io::Output &out, const Block &block) const
Print the given block.
void print (elm::io::Output &out, const inst &inst) const
Print the given instruction.
Private Attributes
const hard::Platform * pf
Detailed Description
Printer class for semantic instructions (resolve the generic register value to the their real platform name).
Constructor & Destructor Documentation
otawa::sem::Printer::Printer (const hard::Platform * platform = 0) inline
Member Function Documentation
void Printer::print (elm::io::Output & out, const Block & block) const
Print the given block.
Parameters
out Output stream to use.
block Block to output.
References otawa::p::print().
Referenced by otawa::sem::inst::print(), and otawa::sem::Block::print().
void Printer::print (elm::io::Output & out, const inst & inst) const
Print the given instruction.
Parameters
out Output stream to use.
inst Semantics instruction to output.
References otawa::sem::inst::a, otawa::se::ADD, otawa::sem::AND, otawa::sem::ASR, otawa::sem::inst::b, otawa::etime::BRANCH, otawa::se::CMP, otawa::se::CMPU, otawa::sem::inst::cond(), otawa::sem::CONT, otawa::sem::inst::cst, otawa::sem::inst::d(), otawa::DIV, otawa::sem::DIVU, otawa::sem::IF, otawa::sem::inst::jump(), otawa::sem::LOAD, otawa::clp::max(), otawa::sem::MOD, otawa::sem::MODU, otawa::MUL, otawa::sem::MULH, otawa::sem::MULU, otawa::se::NEG, otawa::sem::NOT, otawa::sem::inst::op, otawa::se::OR, otawa::sem::SCRATCH, otawa::sem::SET, otawa::sem::SETI, otawa::sem::SETP, otawa::sem::SHL, otawa::sem::SHR, otawa::sem::SPEC, otawa::sem::inst::sr(), otawa::sem::STORE, otawa::sem::SUB, otawa::sem::TRAP, otawa::sem::inst::type(), and otawa::sem::XOR.
Member Data Documentation
const hard::Platform* otawa::sem::Printer::pf private
The documentation for this class was generated from the following files:
include/otawa/sem/inst.h
src/prog/sem.cpp