Otawa: otawa::Processor Class Reference
otawa::Processor Class Reference
Processor Layer
The processor class is implemented by all code processor.
#include <otawa/proc/Processor.h>
Classes
class Deletor
class Remover
Public Types
enum log_level_t {
LOG_NONE = 0, LOG_PROC = 1, LOG_FILE = 2, LOG_DEPS = LOG_FILE,
LOG_FUN = 3, LOG_CFG = LOG_FUN, LOG_BLOCK = 4, LOG_BB = LOG_BLOCK,
LOG_INST = 5
}
typedef enum otawa::Monitor::log_level_t log_level_t
Public Member Functions
Processor (void)
Build a simple anonymous processor.
Processor (AbstractRegistration &registration)
For internal use only.
Processor (String name, Version version)
Build a new processor with name and version.
Processor (String name, Version version, AbstractRegistration &registration)
For internal use only.
virtual ~Processor (void)
elm::String name (void) const
elm::Version version (void) const
virtual void configure (const PropList &props)
This method may be called for configuring a processor thanks to information passed in the property list.
void process (WorkSpace *ws, const PropList &props=PropList::EMPTY)
Execute the code processor on the given framework.
Processor (const PropList &props)
Build a new processor.
Processor (elm::String name, elm::Version version, const PropList &props)
Build a new processor with name and version.
WorkSpace * workspace (void)
Get the current workspace.
bool isVerbose (void) const
Test if the verbosity is activated.
bool logFor (log_level_t tested) const
Test if the given log level is activated or not.
log_level_t logLevel (void) const
Public Attributes
elm::io::Output out
Provide a stream to perform output for the user.
elm::io::Output log
Provide a stream to perform log output.
Static Public Attributes
static MetaRegistration reg
static Identifier< PropList * > STATS
This property identifiers is used to pass a property list to the processor that will be used to store statistics about the performed work.
static Identifier< bool > TIMED
If the value of the associated property is true (default to false), time statistics will also be collected with other processor statistics.
static Identifier< bool > RECURSIVE
static Identifier< Progress * > PROGRESS
Install.
static Identifier< bool > COLLECT_STATS
This property allows to activate collection of statistics for the work of the current processor.
static Identifier< elm::io::OutStream * > & OUTPUT = otawa::OUTPUT
This property identifier is used for setting the output stream used by the processor to write results.
static Identifier< elm::io::OutStream * > & LOG = otawa::LOG
This property identifier is used for setting the log stream used by the processor to write messages (information, warning, error).
static Identifier< bool > & VERBOSE = otawa::VERBOSE
This property activates the verbose mode of the processor: information about the processor work will be displayed.
static Identifier< log_level_t > & LOG_LEVEL = otawa::LOG_LEVEL
Property passed in the configuration property list of a processor to select the log level between LOG_PROC, LOG_CFG or LOG_BB.
static Identifier< elm::system::time_t > RUNTIME
This property identifier is used to store in the statistics of a processor the overall run time of the processor work.
static Monitor & null = __null_mon
Monitor that output nothing.
Protected Member Functions
bool isTimed (void) const
Test if the timed mode is activated (recording of timings in the statistics).
bool recordsStats (void) const
Test if the statictics mode is activated.
bool isAllocated (void) const
bool isPrepared (void) const
bool isCollectingStats (void) const
void require (const AbstractFeature &feature)
Usually called from a processor constructor, this method records a required feature for the work of the current processor.
void provide (const AbstractFeature &feature)
Usually called from a processor constructor, this method records a feature provided by the work of the current processor.
void invalidate (const AbstractFeature &feature)
Usually called from a processor constructor, this method records a feature invalidated by the work of the current processor.
void use (const AbstractFeature &feature)
Usually called from a processor constructor, this method records a feature as used by the work of the current processor.
void warn (const String &message)
Display a warning.
WorkSpace * workspace (void) const
Get the current workspace.
Progress & progress (void)
Get the current progress handler.
void recordStat (const AbstractFeature &feature, StatCollector *collector)
Add a statistics collector to the current workspace collection.
void addCleaner (const AbstractFeature &feature, Cleaner *cleaner)
Add a cleaner for the given feature.
template<class T >
void addRemover (const AbstractFeature &feature, const Ref< T, Identifier< T > > &ref)
template<class T >
void addDeletor (const AbstractFeature &feature, const Ref< T *, Identifier< T * > > &ref)
virtual void prepare (WorkSpace *ws)
This method called to let the processor customize its requirements according to some generic feature.
virtual void processWorkSpace (WorkSpace *ws)
Process the given framework.
virtual void setup (WorkSpace *ws)
This method is called before an anlysis to let the processor do some initialization.
virtual void cleanup (WorkSpace *ws)
This method is called after the end of the processor analysis to let it do some clean up.
virtual void collectStats (WorkSpace *ws)
This method is invoked if the user has required to collect statistics about the processor.
virtual void processFrameWork (WorkSpace *fw)
Process the given workspace.
template<class T >
T * track (const AbstractFeature &feature, T *object)
template<class T >
void track (const AbstractFeature &feature, const Ref< T *, Identifier< T * > > &ref)
Track the release of an allocated object assigned to an identifier relatively to the given feature.
template<class T >
void track (const AbstractFeature &feature, const Ref< T *, const Identifier< T * > > &ref)
Track the release of an allocated object assigned to an identifier relatively to the given feature.
virtual void requireDyn (WorkSpace *ws, const PropList &props)
Method called after registration requirements to support dynamic requirements.
void setWorkspace (WorkSpace *workspace)
Set the current workspace.
Protected Attributes
PropList * stats
t::uint32 flags
Contains various bit flags.
Static Protected Attributes
static const t::uint32 IS_TIMED = 0x01 << CUSTOM_SHIFT
static const t::uint32 IS_ALLOCATED = 0x04 << CUSTOM_SHIFT
static const t::uint32 IS_PREPARED = 0x08 << CUSTOM_SHIFT
static const t::uint32 IS_COLLECTING = 0x10 << CUSTOM_SHIFT
static const t::uint32 IS_VERBOSE = 0x01
static const t::uint32 CUSTOM_SHIFT = 16
Private Types
typedef Pair< const AbstractFeature *, Cleaner * > clean_t
typedef elm::genstruct::SLList< clean_t > clean_list_t
Private Member Functions
void init (const PropList &props)
Private Attributes
AbstractRegistration * _reg
WorkSpace * ws
clean_list_t cleaners
Progress * _progress
Friends
class FeatureRequirer
Detailed Description
The processor class is implemented by all code processor.
At this level, the argument can only be the full framework. Look at sub-classes for more accurate processors.
Configuration
Processor::OUTPUT,
Processor::LOG,
Processor::VERBOSE,
Processor::STATS,
Processor::TIMED,
Processor::LOG_LEVEL.
Statistics The statistics are recorded in the property list passed by Processor::STATS.
Processor::RUNTIME.
Verbosity OTAWA provides two way to activate verbosity in code processors.
passing the Processor::VERBOSE to the processor property list
define the environment variable "OTAWA_VERBOSE"
Member Typedef Documentation
typedef elm::genstruct::SLList<clean_t> otawa::Processor::clean_list_t private
typedef Pair<const AbstractFeature *, Cleaner *> otawa::Processor::clean_t private
typedef enum otawa::Monitor::log_level_t otawa::Monitor::log_level_t inherited
Member Enumeration Documentation
enum otawa::Monitor::log_level_t inherited
Enumerator
LOG_NONE
LOG_PROC
LOG_FILE
LOG_DEPS
LOG_FUN
LOG_CFG
LOG_BLOCK
LOG_BB
LOG_INST
Constructor & Destructor Documentation
otawa::Processor::Processor (void)
Build a simple anonymous processor.
References otawa::AbstractRegistration::_base, _reg, otawa::Monitor::flags, IS_ALLOCATED, and reg.
Referenced by otawa::ipet::TrivialDataCacheManager::processBB(), and otawa::CAT2Builder::processCFG().
otawa::Processor::Processor (AbstractRegistration & registration)
For internal use only.
References _reg, and otawa::registration().
otawa::Processor::Processor (String name, Version version)
Build a new processor with name and version.
Parameters
name Processor name.
version Processor version.
Deprecated:
References otawa::AbstractRegistration::_base, otawa::AbstractRegistration::_name, _reg, otawa::AbstractRegistration::_version, otawa::Monitor::flags, IS_ALLOCATED, name(), reg, and version().
otawa::Processor::Processor (String name, Version version, AbstractRegistration & registration)
For internal use only.
References otawa::AbstractRegistration::_base, otawa::AbstractRegistration::_name, _reg, otawa::AbstractRegistration::_version, otawa::Monitor::flags, IS_ALLOCATED, name(), otawa::registration(), and version().
otawa::Processor::~Processor (void) virtual
References _reg, otawa::Monitor::flags, and IS_ALLOCATED.
otawa::Processor::Processor (const PropList & props)
Build a new processor.
Parameters
Configuration properties.
Deprecated:
Configuration must be passed at the process() call.
References otawa::AbstractRegistration::_base, _reg, otawa::Monitor::flags, init(), IS_ALLOCATED, and reg.
otawa::Processor::Processor (elm::String name, elm::Version version, const PropList & props)
Build a new processor with name and version.
Parameters
name Processor name.
version Processor version.
props Configuration properties.
Deprecated:
Configuration must be passed at the process() call.
References otawa::AbstractRegistration::_base, otawa::AbstractRegistration::_name, _reg, otawa::AbstractRegistration::_version, otawa::Monitor::flags, init(), IS_ALLOCATED, name(), reg, and version().
Member Function Documentation
void otawa::Processor::addCleaner (const AbstractFeature & feature, Cleaner * cleaner) inline protected
Add a cleaner for the given feature.
A cleaner is an object with a virtual destructor that is called when the associated feature is removed: this let the processor to release and clean up the resources it allocated to implement the provided features.
Parameters
feature Feature the cleaner apply to.
cleaner Cleaner to add.
Referenced by otawa::DelayedBuilder::cleanup(), otawa::StackAnalysis::cleanup(), otawa::Dominance::processCFG(), otawa::clp::Analysis::processWorkSpace(), and recordStat().
template<class T > void otawa::Processor::addDeletor (const AbstractFeature & feature, const Ref< T *, Identifier< T * > > & ref) inline protected
Referenced by otawa::Virtualizer::cleanup().
template<class T > void otawa::Processor::addRemover (const AbstractFeature & feature, const Ref< T, Identifier< T > > & ref) inline protected
Referenced by otawa::Virtualizer::cleanup().
void otawa::Processor::cleanup (WorkSpace * ws) protected virtual
This method is called after the end of the processor analysis to let it do some clean up.
Parameters
ws Workspace to work on.
Reimplemented in otawa::AccessedAddressFromStack, otawa::Virtualizer, otawa::tsim::Delta, otawa::CFGSaver, otawa::DelayedBuilder, otawa::etime::EdgeTimeBuilder, otawa::StackAnalysis, otawa::LBlockBuilder, otawa::ccg::LBlockBuilder, otawa::SubCFGBuilder, otawa::dcache::CLPBlockBuilder, otawa::ipet::VarAssignment, otawa::BBRatioDisplayer, otawa::branch::CondNumber, otawa::CFGBuilder, otawa::tsim::BBTimeSimulator, otawa::LoopUnroller, otawa::CFGChecker, otawa::dcache::CATBuilder, otawa::ilp::Output, otawa::CFGCollector, otawa::ipet::FlowFactLoader, otawa::ipet::TrivialInstCacheManager, and otawa::ipet::WCETCountRecorder.
Referenced by process().
void otawa::Processor::collectStats (WorkSpace * ws) protected virtual
This method is invoked if the user has required to collect statistics about the processor.
In its default implementation, this method does nothing but it may be customized if the current implementation provides statistics. It is called after the main computation of the processor.
Statistics must be objects inheriting from the class StatCollector and recorded with method recordStat().
Parameters
ws Current workspace.
Reimplemented in otawa::dcache::CatConstraintBuilder, otawa::ipet::WCETComputation, and otawa::CAT2OnlyConstraintBuilder.
Referenced by process().
void otawa::Processor::configure (const PropList & props) virtual
This method may be called for configuring a processor thanks to information passed in the property list.
Parameters
props Configuration information.
Reimplemented in otawa::GraphBBTime< G >, otawa::GraphBBTime< ParExeGraph >, otawa::AccessedAddressFromStack, otawa::dcache::ACSBuilder, otawa::dcache::ACSMayBuilder, otawa::FlowFactLoader, otawa::script::Script, otawa::tsim::Delta, otawa::ipet::ConstraintLoader, otawa::EdgeACSBuilder, otawa::bpred::BPredProcessor, otawa::display::ILPSystemDisplayer, otawa::display::CFGOutput, otawa::ccg::ConstraintBuilder, otawa::Virtualizer, otawa::ipet::VarAssignment, otawa::EdgeCAT2Builder, otawa::ipet::BasicConstraintsBuilder, otawa::etime::StandardEventBuilder, otawa::ACSBuilder, otawa::dcache::BlockBuilder, otawa::ipet::ILPSystemGetter, otawa::CAT2Builder, otawa::cat::CATConstraintBuilder, otawa::clp::Analysis, otawa::branch::OnlyConsBuilder, otawa::BBRatioDisplayer, otawa::LinkedBlocksDetector, otawa::CFGBuilder, otawa::SubCFGBuilder, otawa::CFGProcessor, otawa::StackAnalysis, otawa::ACSMayBuilder, otawa::etime::EdgeTimeBuilder, otawa::dcache::CatConstraintBuilder, otawa::StackAnalysis, otawa::ipet::FlowFactConstraintBuilder, otawa::CFGSaver, otawa::CFGChecker, otawa::dcache::CATBuilder, otawa::ipet::TrivialBBTime, otawa::EdgeCAT2ConstraintBuilder, otawa::CFGCollector, otawa::CAT2OnlyConstraintBuilder, otawa::ilp::Output, otawa::CFGNormalizer, otawa::ipet::CachePenaltiesObjectFunctionBuilder, and otawa::TextDecoder.
References otawa::Monitor::configure(), and init().
Referenced by otawa::hard::CacheConfiguration::cacheName(), otawa::TextDecoder::configure(), otawa::ilp::Output::configure(), otawa::CAT2OnlyConstraintBuilder::configure(), otawa::CFGCollector::configure(), otawa::EdgeCAT2ConstraintBuilder::configure(), otawa::dcache::CATBuilder::configure(), otawa::StackAnalysis::configure(), otawa::dcache::CatConstraintBuilder::configure(), otawa::ets::TrivialAstBlockTime::configure(), otawa::ACSMayBuilder::configure(), otawa::CFGBuilder::configure(), otawa::SubCFGBuilder::configure(), otawa::CFGProcessor::configure(), otawa::LinkedBlocksDetector::configure(), otawa::cat::CATConstraintBuilder::configure(), otawa::clp::Analysis::configure(), otawa::ACSBuilder::configure(), otawa::ipet::ILPSystemGetter::configure(), otawa::Virtualizer::configure(), otawa::ccg::ConstraintBuilder::configure(), otawa::display::ILPSystemDisplayer::configure(), otawa::EdgeACSBuilder::configure(), otawa::script::Script::configure(), otawa::FlowFactLoader::configure(), otawa::dcache::ACSMayBuilder::configure(), otawa::dcache::ACSBuilder::configure(), otawa::hard::Processor::instantiate(), process(), otawa::CAT2Builder::processCFG(), otawa::dfa::State::record(), and otawa::hard::Memory::worstWriteAccess().
void otawa::Processor::init (const PropList & props) private
References _progress, COLLECT_STATS, otawa::Monitor::flags, IS_COLLECTING, IS_TIMED, otawa::Monitor::log, LOG, otawa::Monitor::LOG_PROC, otawa::Monitor::logFor(), otawa::Monitor::out, OUTPUT, PROGRESS, recordsStats(), STATS, stats, and TIMED.
Referenced by otawa::StackAnalysis::configure(), otawa::clp::Analysis::configure(), configure(), and Processor().
void otawa::Processor::invalidate (const AbstractFeature & feature) protected
Usually called from a processor constructor, this method records a feature invalidated by the work of the current processor.
Parameters
feature Invalidated feature.
References _reg, otawa::AbstractRegistration::features, otawa::Monitor::flags, otawa::FeatureUsage::invalidate, IS_ALLOCATED, isAllocated(), and isPrepared().
Referenced by otawa::LoopReductor::LoopReductor().
bool otawa::Processor::isAllocated (void) const inline protected
Referenced by invalidate(), provide(), require(), and use().
bool otawa::Processor::isCollectingStats (void) const inline protected
References otawa::p::invalidate, otawa::p::provide, otawa::p::require, and otawa::p::use.
Referenced by process(), and recordStat().
bool otawa::Processor::isPrepared (void) const inline protected
Referenced by invalidate(), process(), provide(), require(), and use().
bool otawa::Processor::isTimed (void) const inline protected
Test if the timed mode is activated (recording of timings in the statistics).
Returns
True if timed mode is activated, false else.
Note
If statistics are not activated, this method returns ever false.
Referenced by process().
bool otawa::Monitor::isVerbose (void) const inline inherited
Test if the verbosity is activated.
Returns
True if verbosity is activated, false else.
Referenced by otawa::ccg::LBlockBuilder::addLBlock(), otawa::LBlockBuilder::addLBlock(), otawa::GraphBBTime< G >::analyzePathContext(), otawa::etime::EdgeTimeBuilder::applyFloppySplit(), otawa::etime::EdgeTimeBuilder::applyStrictSplit(), otawa::etime::EdgeTimeBuilder::applyWeightedSplit(), otawa::etime::EdgeTimeBuilder::makeSplit(), otawa::GraphBBTime< G >::processBB(), otawa::etime::EdgeTimeBuilder::processSequence(), and otawa::dcache::BlockBuilder::setup().
bool otawa::Monitor::logFor (log_level_t tested) const inline inherited
Test if the given log level is activated or not.
Parameters
tested Tested log level.
Returns
True if the log level is activated, false else.
Referenced by otawa::CFGBuilder::addCFG(), otawa::ipet::ConstraintLoader::addConstraint(), otawa::PFGBuilder::addFunction(), otawa::FlowFactLoader::addressOf(), otawa::etime::EdgeTimeBuilder::applyWeightedSplit(), otawa::DelayedBuilder::buildBB(), otawa::CFGBuilder::buildCFG(), otawa::DelayedBuilder::buildEdges(), otawa::branch::BranchBuilder::categorize(), otawa::ipet::FlowFactLoader::cleanup(), otawa::dcache::CATBuilder::cleanup(), otawa::DelayedBuilder::cloneEdge(), otawa::CAT2Builder::configure(), otawa::ACSBuilder::configure(), otawa::etime::EdgeTimeBuilder::genForOneCost(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), init(), otawa::FlowFactLoader::load(), otawa::FlowFactLoader::loadF4(), otawa::script::Script::makeConfig(), otawa::CFGBuilder::nextBB(), otawa::FlowFactLoader::onLoop(), otawa::FlowFactLoader::onMemoryAccess(), otawa::FlowFactLoader::onNoInline(), otawa::FlowFactLoader::onReturn(), otawa::FlowFactLoader::onSetInlining(), process(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::branch::CondNumber::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::dcache::CLPBlockBuilder::processBB(), otawa::etime::StandardEventBuilder::processBB(), otawa::dcache::BlockBuilder::processBB(), otawa::CFGCheckSummer::processCFG(), otawa::EdgeProcessor::processCFG(), otawa::CAT2Builder::processCFG(), otawa::display::CFGOutput::processCFG(), otawa::ipet::ConstraintLoader::processCFG(), otawa::ContextualProcessor::processCFG(), otawa::BBProcessor::processCFG(), otawa::etime::EdgeTimeBuilder::processEdge(), otawa::VarTextDecoder::processEntry(), otawa::dcache::CATBuilder::processLBlockSet(), otawa::ACSMayBuilder::processLBlockSet(), otawa::CAT2Builder::processLBlockSet(), otawa::dcache::ACSBuilder::processLBlockSet(), otawa::etime::EdgeTimeBuilder::processSequence(), otawa::VarTextDecoder::processWorkSpace(), otawa::TextDecoder::processWorkSpace(), otawa::LBlockProcessor::processWorkSpace(), otawa::FixedTextDecoder::processWorkSpace(), otawa::ipet::WCETComputation::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), otawa::PFGBuilder::processWorkSpace(), otawa::StackAnalysis::processWorkSpace(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::branch::BranchBuilder::processWorkSpace(), otawa::CFGProcessor::processWorkSpace(), otawa::Virtualizer::processWorkSpace(), otawa::clp::Analysis::processWorkSpace(), otawa::script::Script::processWorkSpace(), otawa::ilp::Output::setup(), otawa::CFGBuilder::setup(), otawa::BBRatioDisplayer::setup(), otawa::dcache::BlockBuilder::setup(), otawa::CFGBuilder::thisBB(), otawa::ipet::FlowFactLoader::transfer(), otawa::Virtualizer::virtualize(), and otawa::script::Script::work().
log_level_t otawa::Monitor::logLevel (void) const inline inherited
Referenced by otawa::script::Script::declareGlobals().
elm::String otawa::Processor::name (void) const inline
Referenced by otawa::Loader::check(), otawa::CFGCollector::configure(), otawa::display::ILPSystemDisplayer::displayVar(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::script::Script::makeConfig(), otawa::display::ILPSystemDisplayer::nameOf(), otawa::FlowFactLoader::onCheckSum(), process(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::ccg::ConstraintBuilder::processLBlockSet(), Processor(), otawa::ipet::WCETComputation::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), otawa::FlowFactLoader::scanBound(), otawa::FlowFactLoader::scanIgnoreEntry(), otawa::FlowFactLoader::scanInt(), otawa::FlowFactLoader::scanMemSet(), otawa::FlowFactLoader::scanRegSet(), otawa::FlowFactLoader::scanUInt(), otawa::FlowFactLoader::scanXBody(), otawa::FlowFactLoader::scanXConditional(), otawa::FlowFactLoader::scanXContent(), warn(), and otawa::script::Script::work().
void otawa::Processor::prepare (WorkSpace * ws) protected virtual
This method called to let the processor customize its requirements according to some generic feature.
When overload, the original method MUST be called at the end of the custom overriding implementation.
Parameters
ws Current workspace.
References otawa::Monitor::flags, IS_PREPARED, otawa::StatInfo::remove(), and ws.
Referenced by process(), and otawa::ipet::TrivialDataCacheManager::processBB().
void otawa::Processor::process (WorkSpace * fw, const PropList & props = PropList::EMPTY)
Execute the code processor on the given framework.
Parameters
fw Workspace to work on.
props Configuration properties.
References _reg, cleaners, cleanup(), collectStats(), configure(), otawa::WorkSpace::getDependency(), otawa::FeatureUsage::invalidate, otawa::WorkSpace::invalidate(), otawa::WorkSpace::isCancelled(), isCollectingStats(), isPrepared(), otawa::WorkSpace::isProvided(), isTimed(), kind, otawa::Monitor::log, otawa::Monitor::LOG_CFG, otawa::Monitor::LOG_DEPS, otawa::Monitor::LOG_PROC, otawa::Monitor::logFor(), otawa::AbstractRegistration::name(), name(), prepare(), processWorkSpace(), otawa::FeatureUsage::provide, otawa::WorkSpace::provide(), recordsStats(), otawa::FeatureUsage::require, otawa::WorkSpace::require(), RUNTIME, setup(), stats, otawa::FeatureUsage::use, otawa::AbstractRegistration::uses(), version(), and ws.
Referenced by otawa::PFGBuilder::finalizeBB(), otawa::WorkSpace::getCFGInfo(), otawa::FlowFactLoader::onIgnoreEntry(), otawa::SilentFeature::process(), otawa::ActualFeature::process(), otawa::Feature< T, C >::process(), otawa::p::feature::process(), otawa::TextDecoder::processWorkSpace(), otawa::cat::CATBuilder::processWorkSpace(), and otawa::DelayedBuilder::setup().
void otawa::Processor::processFrameWork (WorkSpace * fw) protected virtual
Process the given workspace.
Parameters
fw Workspace to process.
Deprecated:
Use processWorkSpace() instead.
Referenced by processWorkSpace().
void otawa::Processor::processWorkSpace (WorkSpace * fw) protected virtual
Process the given framework.
Parameters
fw Framework to process.
Deprecated:
Use processWorkSpace() instead.
Reimplemented in otawa::NoProcessor, otawa::GraphBBTime< G >, otawa::GraphBBTime< ParExeGraph >, otawa::dcache::ACSBuilder, otawa::dcache::ACSMayBuilder, otawa::FlowFactLoader, otawa::ContextTreeBuilder, otawa::script::Script, otawa::clp::Analysis, otawa::display::ILPSystemDisplayer, otawa::ccg::Builder, otawa::ast::ASTLoader, otawa::EdgeACSBuilder, otawa::Virtualizer, otawa::ExeGraphBBTime< G >, otawa::ExeGraphBBTime< LiExeGraph >, otawa::ExeGraphBBTime< ParamExeGraph >, otawa::ccg::ConstraintBuilder, otawa::CFGProcessor, otawa::CAT2ConstraintBuilder, otawa::cat::CATBuilder, otawa::ipet::BasicConstraintsBuilder, otawa::StackAnalysis, otawa::branch::BranchBuilder, otawa::ACSBuilder, otawa::CFGCollector, otawa::DelayedBuilder, otawa::SubCFGBuilder, otawa::ipet::ILPSystemGetter, otawa::cat::CATConstraintBuilder, otawa::CFGSaver, otawa::StackAnalysis, otawa::LoopReductor, otawa::LoopUnroller, otawa::ets::ACSComputation, otawa::LinkedBlocksDetector, otawa::ACSMayBuilder, otawa::PFGBuilder, otawa::CFGBuilder, otawa::dcache::CatConstraintBuilder, otawa::ast::FunProcessor, otawa::cfgio::Output, otawa::CAT2OnlyConstraintBuilder, otawa::dcache::CATBuilder, otawa::ilp::Output, otawa::ipet::WCETComputation, otawa::FixedTextDecoder, otawa::DeadCodeAnalysis, otawa::hard::Dumper, otawa::EdgeCAT2ConstraintBuilder, otawa::PCGBuilder, otawa::LBlockProcessor, otawa::TextDecoder, otawa::VarTextDecoder, and otawa::FunProcessor.
References processFrameWork(), and warn().
Referenced by process().
Progress & otawa::Processor::progress (void) inline protected
Get the current progress handler.
Returns
Progress handler.
void otawa::Processor::provide (const AbstractFeature & feature) protected
Usually called from a processor constructor, this method records a feature provided by the work of the current processor.
Parameters
feature Provided feature.
References _reg, otawa::AbstractRegistration::features, otawa::Monitor::flags, IS_ALLOCATED, isAllocated(), isPrepared(), and otawa::FeatureUsage::provide.
Referenced by otawa::ipet::BasicConstraintsBuilder::BasicConstraintsBuilder(), otawa::CFGBuilder::CFGBuilder(), otawa::CFGCheckSummer::CFGCheckSummer(), otawa::CFGCollector::CFGCollector(), otawa::CFGNormalizer::CFGNormalizer(), otawa::ContextTreeBuilder::ContextTreeBuilder(), otawa::ContextTreeByCFGBuilder::ContextTreeByCFGBuilder(), otawa::DeadCodeAnalysis::DeadCodeAnalysis(), otawa::Dominance::Dominance(), otawa::EdgeACSBuilder::EdgeACSBuilder(), otawa::EdgeCAT2Builder::EdgeCAT2Builder(), otawa::EdgeCAT2ConstraintBuilder::EdgeCAT2ConstraintBuilder(), otawa::ExeGraphBBTime< G >::ExeGraphBBTime(), otawa::FirstLastBuilder::FirstLastBuilder(), otawa::ipet::FlowFactConstraintBuilder::FlowFactConstraintBuilder(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::ipet::ILPSystemGetter::ILPSystemGetter(), otawa::LoopReductor::LoopReductor(), otawa::PCGBuilder::PCGBuilder(), otawa::PFGBuilder::PFGBuilder(), otawa::PostDominance::PostDominance(), otawa::PSTBuilder::PSTBuilder(), otawa::TextDecoder::TextDecoder(), otawa::ipet::TrivialDataCacheManager::TrivialDataCacheManager(), and otawa::VarTextDecoder::VarTextDecoder().
bool otawa::Processor::recordsStats (void) const inline protected
Test if the statictics mode is activated.
Returns
True if the statistics mode is activated, false else.
Referenced by init(), process(), and otawa::CFGProcessor::processWorkSpace().
void otawa::Processor::recordStat (const AbstractFeature & feature, StatCollector * collector) protected
Add a statistics collector to the current workspace collection.
The statistics object is tracked and linked to the feature. In case of the feature invalidation, the statistics information instance is purged of the statistics collector.
Parameters
feature Feature to link the collector to.
collector Statistics collector to add.
References otawa::StatInfo::add(), addCleaner(), isCollectingStats(), and workspace().
Referenced by otawa::CAT2OnlyConstraintBuilder::collectStats(), otawa::ipet::WCETComputation::collectStats(), and otawa::dcache::CatConstraintBuilder::collectStats().
void otawa::Processor::require (const AbstractFeature & feature) protected
Usually called from a processor constructor, this method records a required feature for the work of the current processor.
Parameters
feature Required feature.
References _reg, otawa::AbstractRegistration::features, otawa::Monitor::flags, IS_ALLOCATED, isAllocated(), isPrepared(), and otawa::FeatureUsage::require.
Referenced by otawa::ipet::BasicConstraintsBuilder::BasicConstraintsBuilder(), otawa::CFGBuilder::CFGBuilder(), otawa::CFGCollector::CFGCollector(), otawa::CFGNormalizer::CFGNormalizer(), otawa::ContextTreeBuilder::ContextTreeBuilder(), otawa::ContextTreeByCFGBuilder::ContextTreeByCFGBuilder(), otawa::ContextualProcessor::ContextualProcessor(), otawa::DeadCodeAnalysis::DeadCodeAnalysis(), otawa::EdgeACSBuilder::EdgeACSBuilder(), otawa::EdgeCAT2Builder::EdgeCAT2Builder(), otawa::EdgeCAT2ConstraintBuilder::EdgeCAT2ConstraintBuilder(), otawa::FirstLastBuilder::FirstLastBuilder(), otawa::ipet::FlowFactConstraintBuilder::FlowFactConstraintBuilder(), otawa::LinkedBlocksDetector::LinkedBlocksDetector(), otawa::LoopReductor::LoopReductor(), otawa::PCGBuilder::PCGBuilder(), otawa::PFGBuilder::PFGBuilder(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::CAT2Builder::processCFG(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), otawa::PSTBuilder::PSTBuilder(), otawa::FeatureRequirer::require(), otawa::StackAnalysis::StackAnalysis(), otawa::TextDecoder::TextDecoder(), otawa::ipet::TrivialDataCacheManager::TrivialDataCacheManager(), otawa::ipet::WCETCountRecorder::WCETCountRecorder(), and otawa::script::Script::work().
void otawa::Processor::requireDyn (WorkSpace * ws, const PropList & props) protected virtual
Method called after registration requirements to support dynamic requirements.
As a default, do nothing.
Parameters
ws Current workspace.
props Current properties.
Referenced by otawa::ipet::TrivialDataCacheManager::processBB().
void otawa::Processor::setup (WorkSpace * ws) protected virtual
This method is called before an anlysis to let the processor do some initialization.
Parameters
ws Processed workspace.
Reimplemented in otawa::AccessedAddressFromStack, otawa::FlowFactLoader, otawa::clp::Analysis, otawa::display::ILPSystemDisplayer, otawa::tsim::Delta, otawa::dcache::BlockBuilder, otawa::EdgeCAT2Builder, otawa::etime::StandardEventBuilder, otawa::LBlockBuilder, otawa::ccg::LBlockBuilder, otawa::dcache::CLPBlockBuilder, otawa::etime::EdgeTimeBuilder, otawa::ipet::FlowFactConstraintBuilder, otawa::ipet::VarAssignment, otawa::BBRatioDisplayer, otawa::branch::CondNumber, otawa::CAT2Builder, otawa::CFGBuilder, otawa::DelayedBuilder, otawa::tsim::BBTimeSimulator, otawa::CFGSaver, otawa::CFGChecker, otawa::dcache::WCETFunctionBuilder, otawa::FixedTextDecoder, otawa::EdgeCAT2ConstraintBuilder, otawa::ilp::Output, otawa::ipet::FlowFactLoader, otawa::ipet::TrivialInstCacheManager, and otawa::ipet::WCETCountRecorder.
Referenced by process().
void otawa::Monitor::setWorkspace (WorkSpace * workspace) inline protected inherited
Set the current workspace.
Parameters
workspace New current workspace.
template<class T > T* otawa::Processor::track (const AbstractFeature & feature, T * object) inline protected
Referenced by otawa::SubCFGBuilder::cleanup(), otawa::StackAnalysis::cleanup(), otawa::DelayedBuilder::cleanup(), and otawa::CFGBuilder::processWorkSpace().
template<class T > void otawa::Processor::track (const AbstractFeature & feature, const Ref< T *, Identifier< T * > > & ref) inline protected
Track the release of an allocated object assigned to an identifier relatively to the given feature.
When the feature is deleted, the object is fried and the identifier is removed. It is used as below:
track(MY_FEATURE, MY_ID(props) = value);
Parameters
feature Linked feature.
ref Reference to the identifier to remove.
template<class T > void otawa::Processor::track (const AbstractFeature & feature, const Ref< T *, const Identifier< T * > > & ref) inline protected
Track the release of an allocated object assigned to an identifier relatively to the given feature.
When the feature is deleted, the object is fried and the identifier is removed. It is used as below:
track(MY_FEATURE, MY_ID(props) = value);
Parameters
feature Linked feature.
ref Reference to the identifier to remove.
void otawa::Processor::use (const AbstractFeature & feature) protected
Usually called from a processor constructor, this method records a feature as used by the work of the current processor.
Parameters
feature Used feature.
References _reg, otawa::AbstractRegistration::features, otawa::Monitor::flags, IS_ALLOCATED, isAllocated(), isPrepared(), and otawa::FeatureUsage::use.
Referenced by otawa::Virtualizer::Virtualizer().
elm::Version otawa::Processor::version (void) const inline
References otawa::PropList::EMPTY.
Referenced by process(), Processor(), and warn().
void otawa::Processor::warn (const String & message) protected
Display a warning.
Parameters
message Message to display.
References COLLECT_STATS, otawa::Monitor::log, otawa::LOG, LOG, otawa::LOG_LEVEL, LOG_LEVEL, name(), otawa::Progress::null, otawa::OUTPUT, OUTPUT, PROGRESS, RUNTIME, STATS, TIMED, otawa::VERBOSE, VERBOSE, and version().
Referenced by otawa::CFGBuilder::addFile(), otawa::FlowFactLoader::addressOf(), otawa::CFGBuilder::buildCFG(), otawa::VarTextDecoder::getInst(), otawa::FlowFactLoader::load(), otawa::FlowFactLoader::loadF4(), otawa::FlowFactLoader::onWarning(), otawa::ets::FlowFactLoader::processAST(), otawa::ipet::FlowFactLoader::processBB(), otawa::CFGChecker::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::etime::StandardEventBuilder::processBB(), otawa::CFGNormalizer::processCFG(), otawa::CFGChecker::processCFG(), otawa::VarTextDecoder::processEntry(), otawa::VarTextDecoder::processWorkSpace(), otawa::FixedTextDecoder::processWorkSpace(), otawa::FlowFactLoader::processWorkSpace(), processWorkSpace(), otawa::FlowFactLoader::scanXBody(), otawa::FlowFactLoader::scanXLoop(), otawa::ipet::TrivialInstCacheManager::setup(), otawa::CFGBuilder::setup(), and otawa::script::Script::work().
WorkSpace * otawa::Monitor::workspace (void) inline inherited
Get the current workspace.
Returns
Current workspace.
WorkSpace * otawa::Processor::workspace (void) const inline protected
Get the current workspace.
Returns
Current workspace.
Referenced by otawa::CFGProcessor::doCleanUp(), otawa::PFGBuilder::finalizeBB(), otawa::FlowFactLoader::findCall(), otawa::VarTextDecoder::getBytes(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::ipet::FlowFactLoader::lookLineAt(), otawa::etime::EdgeTimeBuilder::make(), otawa::DelayedBuilder::next(), otawa::FlowFactLoader::onIgnoreEntry(), otawa::VarTextDecoder::processEntry(), recordStat(), otawa::DelayedBuilder::setup(), otawa::DelayedBuilder::size(), and otawa::CFGProcessor::str().
Friends And Related Function Documentation
friend class FeatureRequirer friend
Member Data Documentation
Progress* otawa::Processor::_progress private
Referenced by init().
AbstractRegistration* otawa::Processor::_reg private
Referenced by invalidate(), process(), otawa::ipet::TrivialDataCacheManager::processBB(), Processor(), provide(), require(), use(), and ~Processor().
clean_list_t otawa::Processor::cleaners private
Referenced by process().
Identifier< bool > otawa::Processor::COLLECT_STATS static
This property allows to activate collection of statistics for the work of the current processor.
See also
StatInfo class.
Referenced by init(), and warn().
const t::uint32 otawa::Monitor::CUSTOM_SHIFT = 16 static protected inherited
t::uint32 otawa::Monitor::flags protected inherited
Contains various bit flags.
Bits from 0 to CUSTOM_SHIFT - 1 are private while bits from CUSTOM_SHIFT to 31 may be customized. To build a bit mask for custom bit i, the CUSTOM_SHIFT may be used as below:
static const t::uint32 MY_MASK = 1 << (i + CUSTOM_SHIFT);
Referenced by otawa::Monitor::configure(), init(), invalidate(), prepare(), Processor(), provide(), require(), use(), and ~Processor().
const t::uint32 otawa::Processor::IS_ALLOCATED = 0x04 << CUSTOM_SHIFT static protected
Referenced by invalidate(), Processor(), provide(), require(), use(), and ~Processor().
const t::uint32 otawa::Processor::IS_COLLECTING = 0x10 << CUSTOM_SHIFT static protected
Referenced by init().
const t::uint32 otawa::Processor::IS_PREPARED = 0x08 << CUSTOM_SHIFT static protected
Referenced by prepare().
const t::uint32 otawa::Processor::IS_TIMED = 0x01 << CUSTOM_SHIFT static protected
Referenced by init().
const t::uint32 otawa::Monitor::IS_VERBOSE = 0x01 static protected inherited
Referenced by otawa::Monitor::configure().
elm::io::Output otawa::Monitor::log inherited
Provide a stream to perform log output.
Should be used only when verbosity is activated.
Referenced by otawa::CFGBuilder::addCFG(), otawa::ipet::ConstraintLoader::addConstraint(), otawa::PFGBuilder::addFunction(), otawa::ccg::LBlockBuilder::addLBlock(), otawa::LBlockBuilder::addLBlock(), otawa::FlowFactLoader::addressOf(), otawa::GraphBBTime< G >::analyzePathContext(), otawa::etime::EdgeTimeBuilder::applyFloppySplit(), otawa::etime::EdgeTimeBuilder::applyStrictSplit(), otawa::etime::EdgeTimeBuilder::applyWeightedSplit(), otawa::DelayedBuilder::buildBB(), otawa::CFGBuilder::buildCFG(), otawa::branch::BranchBuilder::categorize(), otawa::ipet::FlowFactLoader::cleanup(), otawa::ipet::TrivialDataCacheManager::configure(), otawa::ACSBuilder::configure(), otawa::Monitor::configure(), otawa::etime::EdgeTimeBuilder::displayConfs(), otawa::ipet::ConstraintLoader::error(), otawa::etime::EdgeTimeBuilder::genForOneCost(), otawa::ipet::ConstraintLoader::getBB(), otawa::VarTextDecoder::getInst(), otawa::ipet::ConstraintLoader::getVar(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), init(), otawa::FlowFactLoader::load(), otawa::FlowFactLoader::loadF4(), otawa::script::Script::makeConfig(), otawa::etime::EdgeTimeBuilder::makeSplit(), otawa::ipet::ConstraintLoader::newEdgeVar(), otawa::CFGBuilder::nextBB(), otawa::script::Script::onError(), otawa::FlowFactLoader::onLoop(), otawa::FlowFactLoader::onMemoryAccess(), otawa::FlowFactLoader::onNoInline(), otawa::FlowFactLoader::onReturn(), otawa::FlowFactLoader::onSetInlining(), otawa::script::Script::onWarning(), process(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::branch::CondNumber::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::dcache::CLPBlockBuilder::processBB(), otawa::etime::StandardEventBuilder::processBB(), otawa::dcache::BlockBuilder::processBB(), otawa::GraphBBTime< G >::processBB(), otawa::CFGCheckSummer::processCFG(), otawa::CAT2Builder::processCFG(), otawa::ipet::ConstraintLoader::processCFG(), otawa::ContextualProcessor::processCFG(), otawa::BBProcessor::processCFG(), otawa::etime::EdgeTimeBuilder::processEdge(), otawa::VarTextDecoder::processEntry(), otawa::dcache::CATBuilder::processLBlockSet(), otawa::ACSMayBuilder::processLBlockSet(), otawa::CAT2Builder::processLBlockSet(), otawa::dcache::ACSBuilder::processLBlockSet(), otawa::etime::EdgeTimeBuilder::processSequence(), otawa::VarTextDecoder::processWorkSpace(), otawa::TextDecoder::processWorkSpace(), otawa::LBlockProcessor::processWorkSpace(), otawa::ipet::WCETComputation::processWorkSpace(), otawa::FixedTextDecoder::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), otawa::StackAnalysis::processWorkSpace(), otawa::branch::BranchBuilder::processWorkSpace(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::CFGProcessor::processWorkSpace(), otawa::Virtualizer::processWorkSpace(), otawa::clp::Analysis::processWorkSpace(), otawa::ilp::Output::setup(), otawa::CFGBuilder::setup(), otawa::BBRatioDisplayer::setup(), otawa::dcache::BlockBuilder::setup(), otawa::CFGBuilder::thisBB(), otawa::ipet::FlowFactLoader::transfer(), otawa::Virtualizer::virtualize(), warn(), and otawa::script::Script::work().
Identifier< elm::io::OutStream * > & otawa::Processor::LOG = otawa::LOG static
This property identifier is used for setting the log stream used by the processor to write messages (information, warning, error).
Deprecated:
Referenced by init(), otawa::Manager::loadBin(), otawa::LiExeGraphBBTime::processBB(), and warn().
Identifier< Processor::log_level_t > & otawa::Processor::LOG_LEVEL = otawa::LOG_LEVEL static
Property passed in the configuration property list of a processor to select the log level between LOG_PROC, LOG_CFG or LOG_BB.
Deprecated:
Referenced by otawa::Application::run(), and warn().
Monitor & otawa::Monitor::null = __null_mon static inherited
Monitor that output nothing.
Referenced by otawa::Monitor::configure().
elm::io::Output otawa::Monitor::out inherited
Provide a stream to perform output for the user.
Referenced by otawa::DelayedBuilder::buildEdges(), otawa::Monitor::configure(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), init(), otawa::ast::ASTLoader::onError(), otawa::dcache::operator<<(), otawa::CFGChecker::processBB(), otawa::etime::StandardEventBuilder::processBB(), otawa::hard::Dumper::processWorkSpace(), otawa::ccg::Builder::processWorkSpace(), otawa::SubCFGBuilder::SubCFGBuilder(), and otawa::Virtualizer::virtualize().
Identifier< elm::io::OutStream * > & otawa::Processor::OUTPUT = otawa::OUTPUT static
This property identifier is used for setting the output stream used by the processor to write results.
Deprecated:
Referenced by init(), and warn().
Identifier< Progress * > otawa::Processor::PROGRESS static
Install.
Referenced by init(), and warn().
Identifier<bool> otawa::Processor::RECURSIVE static
Referenced by otawa::CFGProcessor::str().
MetaRegistration otawa::Processor::reg static
Referenced by otawa::operator<<(), otawa::dcache::operator<<(), otawa::CAT2Builder::processCFG(), and Processor().
Identifier< elm::system::time_t > otawa::Processor::RUNTIME static
This property identifier is used to store in the statistics of a processor the overall run time of the processor work.
Referenced by process(), and warn().
Identifier< PropList * > otawa::Processor::STATS static
This property identifiers is used to pass a property list to the processor that will be used to store statistics about the performed work.
Implicitly, passing such a property activates the statistics recording facilities.
Referenced by init(), and warn().
PropList* otawa::Processor::stats protected
Referenced by otawa::dcache::CATBuilder::cleanup(), otawa::tsim::Delta::cleanup(), init(), process(), and otawa::CFGProcessor::processWorkSpace().
Identifier< bool > otawa::Processor::TIMED static
If the value of the associated property is true (default to false), time statistics will also be collected with other processor statistics.
Passing such a property without PROC_STATS has no effects.
Referenced by init(), and warn().
Identifier< bool > & otawa::Processor::VERBOSE = otawa::VERBOSE static
This property activates the verbose mode of the processor: information about the processor work will be displayed.
Deprecated:
Referenced by otawa::Application::run(), otawa::Manager::setVerbosity(), and warn().
WorkSpace* otawa::Processor::ws private
Referenced by otawa::AlternativeProcessor::AlternativeSet::add(), otawa::LBlockProcessor::cache(), otawa::BBCleaner::clean(), prepare(), process(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::CAT2Builder::processCFG(), otawa::StackAnalysis::processWorkSpace(), otawa::FlowFactLoader::processWorkSpace(), otawa::GraphBBTime< G >::processWorkSpace(), and otawa::bpred::BPredProcessor::setBit().
The documentation for this class was generated from the following files:
include/otawa/proc/Processor.h
src/prog/proc_Processor.cpp