Otawa: otawa::loader::new_gliss::Inst Class Reference
otawa::loader::new_gliss::Inst Class Reference abstract
#include <otawa/loader/new_gliss/Inst.h>
Public Types
typedef elm::t::uint32 kind_t
Public Member Functions
Inst (Process &process, kind_t kind, address_t addr)
Process & process (void) const
virtual void dump (io::Output &out)
Output a displayable representation of the instruction.
virtual kind_t kind (void)
Get the kind of the current instruction.
virtual const elm::genstruct::Table< hard::Register * > & readRegs (void)
Get the registers read by the instruction.
virtual const elm::genstruct::Table< hard::Register * > & writtenRegs (void)
Get the registers written by the instruction.
virtual address_t address (void) const
Get the address of the item .
Inst * nextInst (void) const
Inst * prevInst (void) const
bool meets (kind_t mask)
bool oneOf (kind_t mask)
bool noneOf (kind_t mask)
bool isIntern (void)
Test if the instruction neither access memory, nor modify control flow.
bool isMem (void)
Test if the instruction access memory.
bool isControl (void)
Test if the instruction changes the control flow.
bool isLoad (void)
Test if the instruction is a load, that is, it performs only one simple memory read.
bool isStore (void)
Test if the instruction is a store, that is, it performs only one simple memory write.
bool isBranch (void)
Test if the instruction is a branch, that is, it changes the control flow but performs neither a memory access, nor a context storage.
bool isCall (void)
Test if the instruction is a sub-program call, that is, it changes the control flow but stores the current state for allowing performing a return.
bool isReturn (void)
Test if the instruction is a sub-program return, that is, it modifies the control flow retrieving its context from a preceding call instruction.
bool isConditional (void)
Test if this instruction is conditional.
bool isMulti (void)
Test if the instruction is multi-memory accesss load / store.
bool isSpecial (void)
Test if the instruction is a complex special instruction.
bool isMul (void)
Test if the instruction is a multiplication.
bool isDiv (void)
Test if the instruction is a division.
bool isIndirect (void)
bool isUnknown (void)
Test if an instruction is unknown.
bool isAtomic (void)
Test if the instruction is an atomic synchronization instruction, that is, performing an atomic read-write memory.
bool isBundle (void)
On VLIW architecture, mark an instruction that is part of a bundle but not last instruction.
bool isBundleEnd (void)
On VLIW architecture, mark an instruction that is the last instruction of a bundle.
virtual Inst * target (void)
Get the target of the branch.
virtual Type * type (void)
virtual void semInsts (sem::Block &block)
Return a list of semantics pseudo-instruction representing the effect of the instruction.
virtual int semInsts (sem::Block &block, int temp)
Same as Inst::semInsts(sem::Block& block) to transform a machine instruction into machine instructions but temp is used as a base to encode temporaries.
virtual int semWriteBack (sem::Block &block, int temp)
VLIW instructions of a bundle perform read and write-back of registers in parallel.
virtual delayed_t delayType (void)
For a branch instruction, returns the type of management for delay slots.
virtual int delaySlots (void)
For a branch instruction, returns the number of delayed instructions.
virtual void readRegSet (RegSet &set)
Get the list of register read by the instruction.
virtual void writeRegSet (RegSet &set)
Get the list of register written by the instruction.
virtual Inst * toInst (void)
Return the instruction matching the current item.
virtual int multiCount (void)
This function is only defined for ISA supporting the IS_MULTI attribute.
ProgItem * next (void) const
Get the next program item.
ProgItem * previous (void) const
Get the previous program item.
virtual t::uint32 size (void) const =0
Get the size of the item in bytes.
address_t topAddress (void) const
Compute the address of the item immediately following the current item.
Property * getProp (const AbstractIdentifier *id) const
Find a property by its identifier.
void setProp (Property *prop)
Set the property in the property list removing any double.
void setProp (const AbstractIdentifier *id)
void removeProp (const AbstractIdentifier *id)
Remove a property matching the given identifier.
void removeProp (const AbstractIdentifier &id)
Property * extractProp (const AbstractIdentifier *id)
Remove a property matching the given identifier and return it.
Property * extractProp (const AbstractIdentifier &id)
Remove a property matching the given identifier and return it.
void addProp (Property *prop)
Add property to the list without checking of duplication.
void removeAllProp (const AbstractIdentifier *id)
Remove all the properties matching the given identifier.
bool hasProp (const AbstractIdentifier &id) const
Test if the property list contains a property matching the given identifier.
void clearProps (void)
Remove all properties from the list.
void addProps (const PropList &props)
Add all properties from the given property list, in a reverse order.
void print (elm::io::Output &out) const
Display the current property list.
Static Public Attributes
static const kind_t IS_COND = 0x00001
Mask of a conditional instruction of an instruction kind.
static const kind_t IS_CONTROL = 0x00002
Mask of a control instruction.
static const kind_t IS_CALL = 0x00004
Mask of a call instruction.
static const kind_t IS_RETURN = 0x00008
Mask of a return instruction.
static const kind_t IS_MEM = 0x00010
Mask of an instruction accessing the memory.
static const kind_t IS_LOAD = 0x00020
Mask of an instruction performing a memory load.
static const kind_t IS_STORE = 0x00040
static const kind_t IS_INT = 0x00080
Mask of an instruction processing integer.
static const kind_t IS_FLOAT = 0x00100
Mask of an instruction processing floats.
static const kind_t IS_ALU = 0x00200
Mask of an instruction performing a computation.
static const kind_t IS_MUL = 0x00400
Mask of a multiplication instruction.
static const kind_t IS_DIV = 0x00800
Mask of a division instruction.
static const kind_t IS_SHIFT = 0x01000
Mask of an instruction performing a shift (this includes logicial shifts, arithmetic shifts and rotations).
static const kind_t IS_TRAP = 0x02000
Mask of a trap instruction.
static const kind_t IS_INTERN = 0x04000
Mask of an instruction performing setup internal to the processor.
static const kind_t IS_MULTI = 0x08000
This mask denotes an instructions that perform multi-value store or load.
static const kind_t IS_SPECIAL = 0x10000
This mask denotes an instruction that is processed in a special way in the pipeline.
static const kind_t IS_INDIRECT = 0x10000
static const kind_t IS_UNKNOWN = 0x20000
This mask denotes an unknown instruction: its opcode does not match any known instruction in the loader.
static const kind_t IS_ATOMIC = 0x40000
static const kind_t IS_BUNDLE = 0x80000
Applied on a VLIW architecture, marks instructions part of a bundle but not at end of the bundle.
static Inst & null = static_null
Null instruction with null address and null size (no kind).
static const PropList EMPTY
This is an empty proplist for convenience.
Protected Member Functions
virtual void decodeRegs (void)
void insertPseudo (ProgItem *pos)
Protected Attributes
kind_t _kind
elm::genstruct::AllocatedTable< hard::Register * > in_regs
elm::genstruct::AllocatedTable< hard::Register * > out_regs
Static Protected Attributes
static const unsigned long REGS_DONE = 0x80000000
static const unsigned long TARGET_DONE = 0x40000000
static const unsigned long MASK = REGS_DONE | TARGET_DONE
static const elm::genstruct::Table< hard::Register * > no_regs
A table containing no sets.
Private Attributes
address_t addr
Process & proc
Member Typedef Documentation
typedef elm::t::uint32 otawa::Inst::kind_t inherited
Constructor & Destructor Documentation
otawa::loader::new_gliss::Inst::Inst (Process & process, kind_t kind, address_t addr)
Member Function Documentation
void otawa::PropList::addProp (Property * prop) inherited
Add property to the list without checking of duplication.
Parameters
prop Property to add.
References otawa::Property::_next.
Referenced by otawa::Identifier< T >::add(), otawa::ast::ASTInfo::ASTInfo(), otawa::Identifier< otawa::arm::Info * >::copy(), otawa::AbstractIdentifier::initProps(), otawa::ContextualProperty::make(), otawa::script::Script::makeConfig(), otawa::ccg::Builder::processLBlockSet(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), and otawa::ContextualProperty::refProps().
void otawa::PropList::addProps (const PropList & props) inherited
Add all properties from the given property list, in a reverse order.
Parameters
props Property list to clone.
References otawa::Property::copy(), otawa::PropList::head, and otawa::Property::next().
Referenced by otawa::display::CFGDrawer::CFGDrawer(), otawa::display::GraphVizGraph::GraphVizGraph(), otawa::ParamFeature::instantiate(), otawa::Manager::loadXML(), otawa::display::GraphVizGraph::newEdge(), otawa::display::GraphVizGraph::newNode(), otawa::Process::Process(), otawa::display::GraphVizItem::setProps(), otawa::VirtualBasicBlock::VirtualBasicBlock(), and otawa::VirtualCFG::VirtualCFG().
virtual address_t otawa::loader::new_gliss::Inst::address (void) const virtual
Get the address of the item .
Returns
Address of the item or address 0 if none is assigned.
Note
In workstation systems, it is commonly accepted that the address 0 is ever invalid because it is the usual value of NULL in C. It should also work the same for embedded systems.
Implements otawa::ProgItem.
Referenced by process().
void otawa::PropList::clearProps (void) inherited
Remove all properties from the list.
References otawa::Property::next().
Referenced by otawa::PSTBuilder::getVCFG(), otawa::display::GraphVizItem::setProps(), and otawa::WorkSpace::~WorkSpace().
virtual void otawa::loader::new_gliss::Inst::decodeRegs (void) protected virtual
int otawa::Inst::delaySlots (void) virtual inherited
For a branch instruction, returns the number of delayed instructions.
As a default, return 0.
Returns
Number of delayed instructions.
delayed_t otawa::Inst::delayType (void) virtual inherited
For a branch instruction, returns the type of management for delay slots.
As a default, consider there is no delay slots.
Returns
Type of management of delay slots.
Note
Branches without delay slots does not need to overload this method.
References otawa::DELAYED_None.
virtual void otawa::loader::new_gliss::Inst::dump (io::Output & out) virtual
Output a displayable representation of the instruction.
The implementation of this method is not mandatory.
Parameters
out Output channel to use.
Reimplemented from otawa::Inst.
Referenced by process().
Property * otawa::PropList::extractProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::script::Script::makeConfig().
Property * otawa::PropList::extractProp (const AbstractIdentifier & id) inline inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::PropList::extractProp().
Referenced by otawa::PropList::extractProp().
Property * otawa::PropList::getProp (const AbstractIdentifier * id) const inherited
Find a property by its identifier.
Parameters
id Identifier of the property to find.
Returns
Found property or null.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::Identifier< otawa::arm::Info * >::exists(), otawa::ContextualProperty::exists(), otawa::ContextualProperty::find(), otawa::Identifier< T >::get(), otawa::ContextualProperty::make(), otawa::ParamFeature::matches(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::print(), otawa::ContextualProperty::print(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), otawa::ContextualProperty::refProps(), otawa::Identifier< T >::set(), otawa::Identifier< T >::use(), and otawa::Identifier< T >::value().
bool otawa::PropList::hasProp (const AbstractIdentifier & id) const inline inherited
Test if the property list contains a property matching the given identifier.
Parameters
id Property identifier to look for.
Returns
True if the list contains the matching property, false else.
References otawa::p::print().
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::Monitor::configure(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::exists(), and otawa::Manager::setVerbosity().
void otawa::ProgItem::insertPseudo (ProgItem * pos) inline protected inherited
bool otawa::Inst::isAtomic (void) inline inherited
Test if the instruction is an atomic synchronization instruction, that is, performing an atomic read-write memory.
Returns
True if it is an synchronization function.
bool otawa::Inst::isBranch (void) inline inherited
Test if the instruction is a branch, that is, it changes the control flow but performs neither a memory access, nor a context storage.
Referenced by otawa::FlowFactLoader::scanMultiBranch().
bool otawa::Inst::isBundle (void) inline inherited
On VLIW architecture, mark an instruction that is part of a bundle but not last instruction.
Returns
True if it is a not bundle-ending instruction, false else.
See also
Inst::IS_BUNDLE, Inst::isBundleEnd()
bool otawa::Inst::isBundleEnd (void) inline inherited
On VLIW architecture, mark an instruction that is the last instruction of a bundle.
Returns
True if it is a bundle-ending instruction, false else.
See also
Inst::IS_BUNDLE, Inst::isBundle.
References otawa::cfgio::target(), and otawa::type().
bool otawa::Inst::isCall (void) inline inherited
Test if the instruction is a sub-program call, that is, it changes the control flow but stores the current state for allowing performing a return.
Returns
True if it is a sub-program call.
Referenced by otawa::PFGBuilder::addFunction(), otawa::CFGBuilder::buildCFG(), otawa::ipet::FlowFactLoader::enteringCall(), otawa::Virtualizer::enteringCall(), otawa::FlowFactLoader::findCall(), makeAddress(), and otawa::FlowFactLoader::scanMultiCall().
bool otawa::Inst::isConditional (void) inline inherited
Test if this instruction is conditional.
Returns
True if the instruction is conditional, false else.
Referenced by otawa::PFGBuilder::addFunction(), otawa::CFGBuilder::buildCFG(), otawa::branch::CondNumber::processBB(), otawa::etime::StandardEventBuilder::processBB(), and otawa::branch::ConsBuilder::processBB().
bool otawa::Inst::isControl (void) inline inherited
Test if the instruction changes the control flow.
Returns
True if control may be modified.
Referenced by otawa::PFGBuilder::addFunction(), otawa::CFGBuilder::buildCFG(), makeAddress(), otawa::FlowFactLoader::scanIgnoreControl(), otawa::FlowFactLoader::scanIgnoreSeq(), otawa::FlowFactLoader::scanNoInline(), and otawa::FlowFactLoader::scanSetInlining().
bool otawa::Inst::isDiv (void) inline inherited
Test if the instruction is a division.
Returns
True if it is a division, false else.
See also
Inst::IS_DIV
bool otawa::Inst::isIndirect (void) inline inherited
Referenced by otawa::branch::CondNumber::processBB(), and otawa::branch::ConsBuilder::processBB().
bool otawa::Inst::isIntern (void) inline inherited
Test if the instruction neither access memory, nor modify control flow.
Returns
True if the instruction is internal.
bool otawa::Inst::isLoad (void) inline inherited
Test if the instruction is a load, that is, it performs only one simple memory read.
Returns
True if it is a load.
Referenced by otawa::ParExeGraph::addEdgesForMemoryOrder().
bool otawa::Inst::isMem (void) inline inherited
Test if the instruction access memory.
Returns
True if it perform memory access.
bool otawa::Inst::isMul (void) inline inherited
Test if the instruction is a multiplication.
Returns
True if it is a multiplication, false else.
See also
Inst::IS_MUL
bool otawa::Inst::isMulti (void) inline inherited
Test if the instruction is multi-memory accesss load / store.
Returns
True if it is multi-memory accesses, false else.
See also
IS_MULTI
bool otawa::Inst::isReturn (void) inline inherited
Test if the instruction is a sub-program return, that is, it modifies the control flow retrieving its context from a preceding call instruction.
Returns
True if it is a sub-program return.
Referenced by otawa::PFGBuilder::addFunction(), and makeAddress().
bool otawa::Inst::isSpecial (void) inline inherited
Test if the instruction is a complex special instruction.
Returns
True if it is a complex special instruction, false else.
See also
IS_SPECIAL
bool otawa::Inst::isStore (void) inline inherited
Test if the instruction is a store, that is, it performs only one simple memory write.
Returns
True if it is a store.
Referenced by otawa::ParExeGraph::addEdgesForMemoryOrder().
bool otawa::Inst::isUnknown (void) inline inherited
Test if an instruction is unknown.
Returns
True if it is unknown, false else.
See also
Inst::IS_UNKNOWN
Referenced by otawa::VarTextDecoder::getInst().
virtual kind_t otawa::loader::new_gliss::Inst::kind (void) virtual
Get the kind of the current instruction.
In fact, the kind is composed as bit array representing an instruction property.
Returns
The kind of the instruction.
Implements otawa::Inst.
Referenced by process().
bool otawa::Inst::meets (kind_t mask) inline inherited
References kind.
int otawa::Inst::multiCount (void) virtual inherited
This function is only defined for ISA supporting the IS_MULTI attribute.
It returns the number of stored during the multi-memory access (in term of memory accesses).
Returns
Number of memory accesses.
References otawa::ProgItem::address(), otawa::Inst::kind(), otawa::Address::null, otawa::Inst::null, otawa::ProgItem::size(), otawa::static_null, and otawa::Inst::toInst().
ProgItem * otawa::ProgItem::next (void) const inherited
Get the next program item.
Returns
Next program item, null at the end of the list.
Referenced by otawa::Segment::findItemAt(), otawa::Segment::insert(), and otawa::Segment::ItemIter::next().
Inst* otawa::Inst::nextInst (void) const inline inherited
References otawa::ProgItem::toInst().
Referenced by otawa::PFGBuilder::addFunction(), otawa::ast::ASTLoader::makeBlock(), otawa::DelayedBuilder::makeNOp(), otawa::DelayedBuilder::next(), otawa::CFGBuilder::nextBB(), and otawa::DelayedBuilder::size().
bool otawa::Inst::noneOf (kind_t mask) inline inherited
bool otawa::Inst::oneOf (kind_t mask) inline inherited
References kind.
Inst* otawa::Inst::prevInst (void) const inline inherited
References kind, and otawa::ProgItem::toInst().
Referenced by otawa::WorkSpace::format(), and otawa::ast::ASTLoader::makeBlock().
ProgItem * otawa::ProgItem::previous (void) const inherited
Get the previous program item.
Returns
Previous program item, null at the begin of the list.
Referenced by otawa::Segment::insert().
void otawa::PropList::print (elm::io::Output & out) const inherited
Display the current property list.
Parameters
out Output to use.
Referenced by otawa::Edge::kindName(), otawa::operator<<(), and otawa::ContextualProperty::print().
Process& otawa::loader::new_gliss::Inst::process (void) const inline
References address(), dump(), kind(), proc, readRegs(), and writtenRegs().
virtual const elm::genstruct::Table<hard::Register *>& otawa::loader::new_gliss::Inst::readRegs (void) virtual
Get the registers read by the instruction.
Returns
Read register table.
Warning
This method is only implemented when the owner loader asserts the REGISTER_USAGE_FEATURE.
Reimplemented from otawa::Inst.
Referenced by process().
void otawa::Inst::readRegSet (RegSet & set) virtual inherited
Get the list of register read by the instruction.
Parameters
set Set filled with platform numbers of read registers.
References otawa::sem::add(), and otawa::Inst::readRegs().
Referenced by otawa::hard::Processor::execute().
void otawa::PropList::removeAllProp (const AbstractIdentifier * id) inherited
Remove all the properties matching the given identifier.
Parameters
id Identifier of properties to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::LoopUnroller::unroll().
void otawa::PropList::removeProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier.
Parameters
id Identifier of the property to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::PSTBuilder::buildTree(), otawa::BBRemover< T >::clean(), otawa::CFGBuilder::cleanup(), otawa::display::CFGOutput::processCFG(), otawa::SubCFGBuilder::processWorkSpace(), otawa::Identifier< otawa::arm::Info * >::remove(), and otawa::ContextualPath::Ref< T >::remove().
void otawa::PropList::removeProp (const AbstractIdentifier & id) inline inherited
References otawa::PropList::removeProp().
Referenced by otawa::PropList::removeProp().
void otawa::Inst::semInsts (sem::Block & block) virtual inherited
Return a list of semantics pseudo-instruction representing the effect of the instruction.
Parameters
block Block to write semantics instruction to. An empty vector means there is no operation.
Note
The passed block is not cleared by the method that accumulates instructions allowing to wholly translates parts of code.
Referenced by otawa::se::FilterBuilder::iterateBranchPaths(), otawa::stack::operator<<(), otawa::clp::operator<<(), otawa::Inst::semInsts(), and otawa::sem::PathIter::start().
int otawa::Inst::semInsts (sem::Block & block, int temp) virtual inherited
Same as Inst::semInsts(sem::Block& block) to transform a machine instruction into machine instructions but temp is used as a base to encode temporaries.
This is used for VLIW where instructions are executed in parallel and register write-back only occurs at end of the semantic instructions.
Parameters
block Block to translate instruction in.
temp Base number for temporaries used for write-back register saving.
Returns
Number of used temporaries for write-back.
See also
proc_vliw
References otawa::Inst::semInsts().
int otawa::Inst::semWriteBack (sem::Block & block, int temp) virtual inherited
VLIW instructions of a bundle perform read and write-back of registers in parallel.
This is mimicked in OTAWA by concatenating semantic instructions of each machine instruction and only writing into temporaries. by this method.
Parameters
block Block to fill with write-back semantic instructions.
temp Base number for temporaries used for write-back register saving.
Returns
Number of temporaries used by this instruction.
See also
VLIW Support
void otawa::PropList::setProp (Property * prop) inherited
Set the property in the property list removing any double.
Parameters
prop Property to set.
References otawa::Property::_next, otawa::Property::id(), and otawa::Property::next().
void otawa::PropList::setProp (const AbstractIdentifier * id) inline inherited
References otawa::PropList::setProp().
Referenced by otawa::PropList::setProp().
size_t otawa::ProgItem::size (void) const pure virtual inherited
Get the size of the item in bytes.
Returns
Size of the item.
Referenced by otawa::Segment::insert(), otawa::DelayedBuilder::makeNOp(), otawa::Inst::multiCount(), otawa::DelayedBuilder::size(), and otawa::ProgItem::topAddress().
Inst * otawa::Inst::target (void) virtual inherited
Get the target of the branch.
Returns
Target address of the branch.
Reimplemented in otawa::loader::old_gliss::BranchInst, and otawa::loader::new_gliss::BranchInst.
Referenced by otawa::PFGBuilder::addFunction(), otawa::CFGBuilder::buildCFG(), makeAddress(), and otawa::VarTextDecoder::processEntry().
Inst * otawa::Inst::toInst (void) virtual inherited
Return the instruction matching the current item.
Returns
Matching instruction or null if the current program item is not an instruction.
Reimplemented from otawa::ProgItem.
Referenced by otawa::Inst::multiCount().
address_t otawa::ProgItem::topAddress (void) const inline inherited
Compute the address of the item immediately following the current item.
Returns
Top address of the item.
References otawa::ProgItem::address(), otawa::ProgItem::size(), and otawa::ProgItem::toInst().
Referenced by otawa::ParExeGraph::addEdgesForFetch(), otawa::FlowFactLoader::findCall(), otawa::VarTextDecoder::getInst(), otawa::Segment::insert(), makeAddress(), otawa::DelayedBuilder::next(), otawa::FlowFactLoader::scanIgnoreControl(), otawa::FlowFactLoader::scanIgnoreSeq(), otawa::FlowFactLoader::scanMultiBranch(), otawa::FlowFactLoader::scanMultiCall(), otawa::FlowFactLoader::scanNoInline(), otawa::FlowFactLoader::scanSetInlining(), and otawa::DelayedBuilder::size().
Type * otawa::Inst::type (void) virtual inherited
Deprecated:
Get the type of the accessed object.
Returns
Accessed data type.
void otawa::Inst::writeRegSet (RegSet & set) virtual inherited
Get the list of register written by the instruction.
Parameters
set Set filled with platform numbers of written registers.
References otawa::sem::add(), and otawa::Inst::writtenRegs().
Referenced by otawa::hard::Processor::execute().
virtual const elm::genstruct::Table<hard::Register *>& otawa::loader::new_gliss::Inst::writtenRegs (void) virtual
Get the registers written by the instruction.
Returns
Read register table.
Warning
This method is only implemented when the owner loader asserts the REGISTER_USAGE_FEATURE.
Reimplemented from otawa::Inst.
Referenced by process().
Member Data Documentation
kind_t otawa::loader::new_gliss::Inst::_kind protected
address_t otawa::loader::new_gliss::Inst::addr private
const PropList otawa::PropList::EMPTY static inherited
This is an empty proplist for convenience.
Referenced by otawa::DynProcessor::configure(), otawa::ActualFeature::processor(), otawa::SilentFeature::SilentFeature(), otawa::Processor::version(), and otawa::display::Driver::~Driver().
elm::genstruct::AllocatedTable<hard::Register *> otawa::loader::new_gliss::Inst::in_regs protected
otawa::Inst::IS_ALU = 0x00200 static inherited
Mask of an instruction performing a computation.
Note
Memory accesses with a computed address must have this bit set.
Referenced by elm::serial2::__unserialize().
const kind_t otawa::Inst::IS_ATOMIC = 0x40000 static inherited
otawa::Inst::IS_BUNDLE = 0x80000 static inherited
Applied on a VLIW architecture, marks instructions part of a bundle but not at end of the bundle.
otawa::Inst::IS_CALL = 0x00004 static inherited
Mask of a call instruction.
Referenced by elm::serial2::__unserialize().
otawa::Inst::IS_COND = 0x00001 static inherited
Mask of a conditional instruction of an instruction kind.
Note that conditional property is not bound to branch but may also be found in guarded instructions.
Referenced by elm::serial2::__unserialize().
otawa::Inst::IS_CONTROL = 0x00002 static inherited
Mask of a control instruction.
Referenced by elm::serial2::__unserialize().
otawa::Inst::IS_DIV = 0x00800 static inherited
Mask of a division instruction.
Referenced by elm::serial2::__unserialize().
otawa::Inst::IS_FLOAT = 0x00100 static inherited
Mask of an instruction processing floats.
Note
Conversion instruction must have both masks IS_INT and IS_FLOAT.
Referenced by elm::serial2::__unserialize().
const kind_t otawa::Inst::IS_INDIRECT = 0x10000 static inherited
otawa::Inst::IS_INT = 0x00080 static inherited
Mask of an instruction processing integer.
Note
Conversion instruction must have both masks IS_INT and IS_FLOAT.
Referenced by elm::serial2::__unserialize().
otawa::Inst::IS_INTERN = 0x04000 static inherited
Mask of an instruction performing setup internal to the processor.
Referenced by elm::serial2::__unserialize().
otawa::Inst::IS_LOAD = 0x00020 static inherited
Mask of an instruction performing a memory load.
Referenced by elm::serial2::__unserialize().
otawa::Inst::IS_MEM = 0x00010 static inherited
Mask of an instruction accessing the memory.
Referenced by elm::serial2::__unserialize().
otawa::Inst::IS_MUL = 0x00400 static inherited
Mask of a multiplication instruction.
Referenced by elm::serial2::__unserialize().
otawa::Inst::IS_MULTI = 0x08000 static inherited
This mask denotes an instructions that perform multi-value store or load.
For example, the "ldmfd" or "stmfd" in the ARM ISA.
otawa::Inst::IS_RETURN = 0x00008 static inherited
Mask of a return instruction.
Referenced by elm::serial2::__unserialize().
otawa::Inst::IS_SHIFT = 0x01000 static inherited
Mask of an instruction performing a shift (this includes logicial shifts, arithmetic shifts and rotations).
Referenced by elm::serial2::__unserialize().
otawa::Inst::IS_SPECIAL = 0x10000 static inherited
This mask denotes an instruction that is processed in a special way in the pipeline.
This concerns very complex instruction usually found in old CISC processors.
const kind_t otawa::Inst::IS_STORE = 0x00040 static inherited
Referenced by elm::serial2::__unserialize().
otawa::Inst::IS_TRAP = 0x02000 static inherited
Mask of a trap instruction.
It may be a programmed interruption, a system call, a debugging break or any control instruction whose control target is computed by the system.
Referenced by elm::serial2::__unserialize().
otawa::Inst::IS_UNKNOWN = 0x20000 static inherited
This mask denotes an unknown instruction: its opcode does not match any known instruction in the loader.
This may denotes either a limitation of the loader, or an execution path error in the program decoding.
const unsigned long otawa::loader::new_gliss::Inst::MASK = REGS_DONE | TARGET_DONE static protected
const elm::genstruct::Table< hard::Register * > otawa::Inst::no_regs static protected inherited
A table containing no sets.
Inst & otawa::Inst::null = static_null static inherited
Null instruction with null address and null size (no kind).
Referenced by otawa::Inst::multiCount().
elm::genstruct::AllocatedTable<hard::Register *> otawa::loader::new_gliss::Inst::out_regs protected
Process& otawa::loader::new_gliss::Inst::proc private
Referenced by process().
const unsigned long otawa::loader::new_gliss::Inst::REGS_DONE = 0x80000000 static protected
const unsigned long otawa::loader::new_gliss::Inst::TARGET_DONE = 0x40000000 static protected
The documentation for this class was generated from the following file:
include/otawa/loader/new_gliss/Inst.h