Otawa: otawa::CodeBasicBlock Class Reference
otawa::CodeBasicBlock Class Reference
Represent a basic block in the strictess meaning: a sequence of instructions containing no branch, or branch target except for the last instruction that may be a branch.
#include <otawa/cfg/BasicBlock.h>
Public Types
typedef InstIter InstIterator
Public Member Functions
CodeBasicBlock (Inst *head, t::size size=0)
Build a basic block from its container code and its sequence of instructions.
void set (Inst *_first, t::size size)
void setSize (t::size size)
void setFirst (Inst *_first)
void setReturn (void)
void setCall (void)
void setCond (void)
void setUnknown (void)
bool isCall (void) const
Test if the basic block is ended by a call to a sub-program.
bool isReturn (void) const
Test if the basic block is ended by a sub-program return.
bool isTargetUnknown (void) const
Test if the target of the branch instruction of this basic block is known or not.
bool isEntry (void) const
Test if the basic block is the CFG entry.
bool isExit (void) const
Test if the basic block is the CFG exit.
bool isEnd (void) const
Test if the basic block is the CFG end, entry or exit.
bool isConditional (void) const
Test if the BB is ended by a conditional branch.
Address address (void) const
Address topAddress (void) const
virtual int countInsts (void) const
Count the number of instructions in the basic block.
t::uint32 size (void) const
Get the size of the basic block.
bool isVirtual (void) const
unsigned long getFlags (void) const
int number (void) const
Get the number hooked on this basic block, that is, value of ID_Index property.
CFG * cfg (void)
Inst * firstInst (void) const
Inst * lastInst (void) const
Get the last instruction of a basic block.
Inst * controlInst (void) const
Find the last control instruction of the basic block.
void print (io::Output &out) const
Print the reference for a basic block.
void print (elm::io::Output &out) const
Display the current property list.
void addInEdge (Edge *edge)
Add an input edge to the basic block input list.
void addOutEdge (Edge *edge)
Add an output edge to the basic block output list.
void removeInEdge (Edge *edge)
Remove an input edge from the basic block input list.
void removeOutEdge (Edge *edge)
Remove an output edge from the basic block output list.
BasicBlock * getTaken (void)
Get the target basic block if the last branch instruction is taken.
BasicBlock * getNotTaken (void)
Get the following basic block if the last branch instruction is not taken.
t::uint32 getBlockSize (void) const
Compute the size of the basic block.
int countInstructions (void) const
Property * getProp (const AbstractIdentifier *id) const
Find a property by its identifier.
void setProp (Property *prop)
Set the property in the property list removing any double.
void setProp (const AbstractIdentifier *id)
void removeProp (const AbstractIdentifier *id)
Remove a property matching the given identifier.
void removeProp (const AbstractIdentifier &id)
Property * extractProp (const AbstractIdentifier *id)
Remove a property matching the given identifier and return it.
Property * extractProp (const AbstractIdentifier &id)
Remove a property matching the given identifier and return it.
void addProp (Property *prop)
Add property to the list without checking of duplication.
void removeAllProp (const AbstractIdentifier *id)
Remove all the properties matching the given identifier.
bool hasProp (const AbstractIdentifier &id) const
Test if the property list contains a property matching the given identifier.
void clearProps (void)
Remove all properties from the list.
void addProps (const PropList &props)
Add all properties from the given property list, in a reverse order.
Public Attributes
Inst * first
t::size _size
unsigned long flags
elm::genstruct::SLList< Edge * > ins
elm::genstruct::SLList< Edge * > outs
CFG * _cfg
Static Public Attributes
static Identifier< BasicBlock * > ID
Identifier of the basic block pseudo-instruction.
static const PropList EMPTY
This is an empty proplist for convenience.
Protected Member Functions
void setTaken (BasicBlock *bb)
Set the target basic block of the branch last instruction.
void setNotTaken (BasicBlock *bb)
Set the following basic block.
Static Protected Attributes
static const unsigned long FLAG_Call = 0x01
static const unsigned long FLAG_Unknown = 0x02
static const unsigned long FLAG_Return = 0x04
static const unsigned long FLAG_Entry = 0x08
static const unsigned long FLAG_Exit = 0x10
static const unsigned long FLAG_Virtual = 0x20
static const unsigned long FLAG_Cond = 0x40
static BasicBlock & null_bb = null_bb_inst
Friends
class CFGInfo
Detailed Description
Represent a basic block in the strictess meaning: a sequence of instructions containing no branch, or branch target except for the last instruction that may be a branch.
Unconditionnal branches are viewed as normal branch in this definition.
Member Typedef Documentation
typedef InstIter otawa::BasicBlock::InstIterator inherited
Constructor & Destructor Documentation
otawa::CodeBasicBlock::CodeBasicBlock (Inst * inst, t::size size = 0)
Build a basic block from its container code and its sequence of instructions.
Parameters
inst First instruction of the basic block. The basic block lay from this instruction to the next basic block head or end of code.
References otawa::BasicBlock::flags, otawa::LABEL, and otawa::BasicBlock::size().
Member Function Documentation
void otawa::BasicBlock::addInEdge (Edge * edge) inline inherited
Add an input edge to the basic block input list.
Parameters
edge Edge to add.
References otawa::BasicBlock::ins.
Referenced by otawa::Edge::Edge().
void otawa::BasicBlock::addOutEdge (Edge * edge) inline inherited
Add an output edge to the basic block output list.
Parameters
edge Edge to add.
References otawa::BasicBlock::outs.
Referenced by otawa::Edge::Edge().
void otawa::PropList::addProp (Property * prop) inherited
Add property to the list without checking of duplication.
Parameters
prop Property to add.
References otawa::Property::_next.
Referenced by otawa::Identifier< T >::add(), otawa::ast::ASTInfo::ASTInfo(), otawa::Identifier< otawa::arm::Info * >::copy(), otawa::AbstractIdentifier::initProps(), otawa::ContextualProperty::make(), otawa::script::Script::makeConfig(), otawa::ccg::Builder::processLBlockSet(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), and otawa::ContextualProperty::refProps().
void otawa::PropList::addProps (const PropList & props) inherited
Add all properties from the given property list, in a reverse order.
Parameters
props Property list to clone.
References otawa::Property::copy(), otawa::PropList::head, and otawa::Property::next().
Referenced by otawa::display::CFGDrawer::CFGDrawer(), otawa::display::GraphVizGraph::GraphVizGraph(), otawa::ParamFeature::instantiate(), otawa::Manager::loadXML(), otawa::display::GraphVizGraph::newEdge(), otawa::display::GraphVizGraph::newNode(), otawa::Process::Process(), otawa::display::GraphVizItem::setProps(), otawa::VirtualBasicBlock::VirtualBasicBlock(), and otawa::VirtualCFG::VirtualCFG().
Address otawa::BasicBlock::address (void) const inline inherited
References otawa::ProgItem::address(), and otawa::BasicBlock::first.
Referenced by otawa::CFGBuilder::addCFG(), otawa::LBlockBuilder::addLBlock(), otawa::ccg::LBlockBuilder::addLBlock(), otawa::CFG::address(), otawa::CFGBuilder::buildCFG(), otawa::Dominance::dominates(), otawa::ipet::FlowFactLoader::enteringCall(), otawa::Virtualizer::enteringCall(), otawa::DelayedBuilder::fix(), otawa::ipet::VarAssignment::makeEdgeVar(), otawa::ipet::VarAssignment::makeNodeVar(), otawa::CFG::name(), otawa::CFGBuilder::nextBB(), otawa::BasicBlock::print(), otawa::ipet::TrivialInstCacheManager::processBB(), otawa::ipet::FlowFactLoader::processBB(), otawa::ParamExeGraphBBTime::processBB(), otawa::ipet::BasicObjectFunctionBuilder::processBB(), otawa::cfgio::Output::processBB(), otawa::CFGChecker::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::ccg::LBlockBuilder::processBB(), otawa::LBlockBuilder::processBB(), otawa::CFGSaver::processBB(), otawa::ipet::BasicConstraintsBuilder::processBB(), otawa::BBRatioDisplayer::processBB(), otawa::GraphBBTime< G >::processBB(), otawa::BBStatCollector::processCFG(), otawa::LoopReductor::processWorkSpace(), otawa::CFG::scan(), otawa::BasicBlock::Bundle::size(), otawa::CFGBuilder::thisBB(), and otawa::BasicBlock::topAddress().
CFG* otawa::BasicBlock::cfg (void) inline inherited
References otawa::BasicBlock::_cfg.
Referenced by otawa::ccg::ConstraintBuilder::addConstraintHeader(), otawa::DelayedBuilder::buildBB(), otawa::DelayedBuilder::cloneEdge(), otawa::etime::EdgeTimeBuilder::contributeSplit(), otawa::Dominance::dominates(), otawa::Edge::Edge(), otawa::cfgio::Output::id(), otawa::DelayedBuilder::insert(), otawa::DelayedBuilder::makeEdge(), otawa::PostDominance::postDominates(), otawa::etime::EdgeTimeBuilder::processEdge(), and otawa::ccg::ConstraintBuilder::processLBlockSet().
void otawa::PropList::clearProps (void) inherited
Remove all properties from the list.
References otawa::Property::next().
Referenced by otawa::PSTBuilder::getVCFG(), otawa::display::GraphVizItem::setProps(), and otawa::WorkSpace::~WorkSpace().
Inst * otawa::BasicBlock::controlInst (void) const inherited
Find the last control instruction of the basic block.
This is usually the last one but (1) delayed-branch architecture insert instructions after the control and (2) OTAWA CFG configuration system may make merge different blocks or ignore some control instructions. If no control is found, return the last instruction.
Returns
Last control instruction.
Referenced by otawa::BasicBlock::firstInst(), otawa::etime::EdgeTimeBuilder::getBranchNode(), otawa::CFGChecker::processBB(), otawa::etime::StandardEventBuilder::processBB(), and otawa::BBStatCollector::processCFG().
int otawa::BasicBlock::countInstructions (void) const inline inherited
References otawa::BasicBlock::countInsts().
Referenced by otawa::PathContext::addBlock(), otawa::LiExeGraphBBTime::buildEpilogueList(), otawa::ParamExeGraphBBTime::buildPrologueList(), otawa::LiExeGraphBBTime::buildPrologueList(), otawa::PathContext::PathContext(), otawa::ParamExeGraphBBTime::processBB(), otawa::LiExeGraphBBTime::processBB(), otawa::GraphBBTime< G >::processBB(), and otawa::tsim::Delta::processCFG().
int otawa::BasicBlock::countInsts (void) const virtual inherited
Count the number of instructions in the basic block.
Returns
Number of instruction in the basic block.
Referenced by otawa::BasicBlock::countInstructions(), otawa::ipet::TrivialBBTime::processBB(), and otawa::BasicBlock::topAddress().
Property * otawa::PropList::extractProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::script::Script::makeConfig().
Property * otawa::PropList::extractProp (const AbstractIdentifier & id) inline inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::PropList::extractProp().
Referenced by otawa::PropList::extractProp().
Inst* otawa::BasicBlock::firstInst (void) const inline inherited
References otawa::BasicBlock::controlInst(), otawa::BasicBlock::first, otawa::BasicBlock::lastInst(), and otawa::BasicBlock::print().
Referenced by otawa::BasicBlock::BundleIter::BundleIter(), otawa::EndBasicBlock::EndBasicBlock(), otawa::DelayedBuilder::fix(), otawa::BasicBlock::InstIter::InstIter(), otawa::CFG::label(), otawa::ipet::FlowFactLoader::processBB(), otawa::LBlockBuilder::processBB(), otawa::ccg::LBlockBuilder::processBB(), and otawa::VirtualBasicBlock::VirtualBasicBlock().
size_t otawa::BasicBlock::getBlockSize (void) const inline inherited
Compute the size of the basic block.
Returns
Size of basic block.
Deprecated:
See BasicBlock::size().
References otawa::BasicBlock::size().
unsigned long otawa::BasicBlock::getFlags (void) const inline inherited
References otawa::BasicBlock::flags.
Referenced by otawa::VirtualBasicBlock::VirtualBasicBlock().
BasicBlock * otawa::BasicBlock::getNotTaken (void) inherited
Get the following basic block if the last branch instruction is not taken.
Returns
Following basic block or null if the last instruction is a sub-program return.
Deprecated:
{Use Edge class instead.}
References otawa::cfgio::edge(), and EDGE_NotTaken.
Property * otawa::PropList::getProp (const AbstractIdentifier * id) const inherited
Find a property by its identifier.
Parameters
id Identifier of the property to find.
Returns
Found property or null.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::Identifier< otawa::arm::Info * >::exists(), otawa::ContextualProperty::exists(), otawa::ContextualProperty::find(), otawa::Identifier< T >::get(), otawa::ContextualProperty::make(), otawa::ParamFeature::matches(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::print(), otawa::ContextualProperty::print(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), otawa::ContextualProperty::refProps(), otawa::Identifier< T >::set(), otawa::Identifier< T >::use(), and otawa::Identifier< T >::value().
BasicBlock * otawa::BasicBlock::getTaken (void) inherited
Get the target basic block if the last branch instruction is taken.
Returns
Target basic block or null if the last instruction is not a branch.
Deprecated:
{Use Edge class instead.}
References otawa::cfgio::edge(), EDGE_Call, and EDGE_Taken.
bool otawa::PropList::hasProp (const AbstractIdentifier & id) const inline inherited
Test if the property list contains a property matching the given identifier.
Parameters
id Property identifier to look for.
Returns
True if the list contains the matching property, false else.
References otawa::p::print().
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::Monitor::configure(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::exists(), and otawa::Manager::setVerbosity().
bool otawa::BasicBlock::isCall (void) const inline inherited
Test if the basic block is ended by a call to a sub-program.
Returns
True if the basic block is call, false else.
References otawa::BasicBlock::FLAG_Call, and otawa::BasicBlock::flags.
Referenced by otawa::ContextTree::addBB().
bool otawa::BasicBlock::isConditional (void) const inline inherited
Test if the BB is ended by a conditional branch.
Returns
True if the BB is ended by a conditional branch, false else.
References otawa::BasicBlock::FLAG_Cond, and otawa::BasicBlock::flags.
Referenced by otawa::ipet::BasicConstraintsBuilder::processBB().
bool otawa::BasicBlock::isEnd (void) const inline inherited
Test if the basic block is the CFG end, entry or exit.
Returns
True if the current BB is the CFG end.
References otawa::BasicBlock::FLAG_Entry, otawa::BasicBlock::FLAG_Exit, and otawa::BasicBlock::flags.
Referenced by otawa::BasicBlock::BundleIter::BundleIter(), otawa::display::CFGOutput::genBBLabel(), otawa::BasicBlock::InstIter::InstIter(), otawa::clp::operator<<(), otawa::ipet::FlowFactLoader::processBB(), otawa::dcache::WCETFunctionBuilder::processBB(), otawa::cfgio::Output::processBB(), otawa::LBlockBuilder::processBB(), otawa::ccg::LBlockBuilder::processBB(), otawa::CFGSaver::processBB(), otawa::etime::EdgeTimeBuilder::processBB(), otawa::dcache::CLPBlockBuilder::processBB(), otawa::BBRatioDisplayer::processBB(), otawa::etime::StandardEventBuilder::processBB(), otawa::SubCFGBuilder::SubCFGBuilder(), and otawa::stack::Manager::updatePath().
bool otawa::BasicBlock::isEntry (void) const inline inherited
Test if the basic block is the CFG entry.
Returns
True if the current BB is the CFG entry.
References otawa::BasicBlock::FLAG_Entry, and otawa::BasicBlock::flags.
Referenced by otawa::ipet::FlowFactLoader::enteringCall(), otawa::Virtualizer::enteringCall(), otawa::GraphBBTime< G >::FillSequence(), otawa::ccg::Problem::gen(), otawa::cat::CATProblem::gen(), otawa::display::CFGOutput::genBBLabel(), otawa::dfa::hai::HalfAbsInt< FixPoint >::inputProcessing(), otawa::BasicBlock::print(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::ipet::CachePenaltiesObjectFunctionBuilder::processBB(), otawa::tsim::TimeDeltaObjectFunctionModifier::processBB(), otawa::ipet::BasicObjectFunctionBuilder::processBB(), otawa::CFGChecker::processBB(), otawa::ipet::BasicConstraintsBuilder::processBB(), otawa::BBStatCollector::processCFG(), otawa::etime::EdgeTimeBuilder::processEdge(), otawa::LoopUnroller::unroll(), and otawa::dfa::XCFGVisitor< P >::visitPreds().
bool otawa::BasicBlock::isExit (void) const inline inherited
Test if the basic block is the CFG exit.
Returns
True if the current BB is the CFG exit.
References otawa::BasicBlock::FLAG_Exit, and otawa::BasicBlock::flags.
Referenced by otawa::GraphBBTime< G >::FillSequence(), otawa::display::CFGOutput::genBBLabel(), otawa::ipet::FlowFactLoader::leavingCall(), otawa::Virtualizer::leavingCall(), otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing(), otawa::BasicBlock::print(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::ipet::CachePenaltiesObjectFunctionBuilder::processBB(), otawa::ipet::BasicObjectFunctionBuilder::processBB(), otawa::CFGChecker::processBB(), otawa::ipet::BasicConstraintsBuilder::processBB(), and otawa::LoopUnroller::unroll().
bool otawa::BasicBlock::isReturn (void) const inline inherited
Test if the basic block is ended by a sub-program return.
Returns
True if it is a sub-program return, false else.
References otawa::BasicBlock::FLAG_Return, and otawa::BasicBlock::flags.
Referenced by otawa::CFG::scan().
bool otawa::BasicBlock::isTargetUnknown (void) const inline inherited
Test if the target of the branch instruction of this basic block is known or not.
Unknown branch target is usually to a non-constant branch address. Remark that sub-program return is not viewed as an unknown branch target.
Returns
True if the branch target is unknown, false else.
References otawa::BasicBlock::FLAG_Unknown, and otawa::BasicBlock::flags.
Referenced by otawa::CFGChecker::processBB().
bool otawa::BasicBlock::isVirtual (void) const inline inherited
References otawa::BasicBlock::FLAG_Virtual, and otawa::BasicBlock::flags.
Referenced by otawa::VirtualBasicBlock::VirtualBasicBlock().
Inst * otawa::BasicBlock::lastInst (void) const inherited
Get the last instruction of a basic block.
Returns
Last instruction (or NULL if the basic block is an end).
Referenced by otawa::ipet::FlowFactLoader::enteringCall(), otawa::Virtualizer::enteringCall(), otawa::BasicBlock::firstInst(), otawa::CFGChecker::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::branch::CondNumber::processBB(), otawa::branch::ConsBuilder::processBB(), and otawa::BranchProblem::update().
int otawa::BasicBlock::number (void) const inline inherited
Get the number hooked on this basic block, that is, value of ID_Index property.
Returns
Number of the basic block or -1 if there is no number hooked.
References otawa::INDEX.
Referenced by otawa::GraphBBTime< G >::analyzePathContext(), otawa::dfa::hai::UnrollingListener< P >::blockInterpreted(), otawa::dfa::hai::DefaultListener< P >::blockInterpreted(), otawa::dfa::hai::WideningListener< P >::blockInterpreted(), otawa::dfa::IterativeDFA< Problem, Set, Iter >::compute(), otawa::etime::EdgeTimeBuilder::contributeSplit(), otawa::Dominance::dominates(), otawa::CachePenalty::dump(), otawa::PathContext::dump(), otawa::PSTBuilder::getVCFG(), otawa::cfgio::Output::id(), otawa::display::CFGAdapter::Vertex::index(), otawa::ForwardCFGAdapter::index(), otawa::BackwardCFGAdapter::index(), otawa::ai::CFGGraph::index(), otawa::ipet::VarAssignment::makeEdgeVar(), otawa::ipet::VarAssignment::makeNodeVar(), otawa::stack::operator<<(), otawa::PostDominance::postDominates(), otawa::BasicBlock::print(), otawa::ipet::CachePenaltiesObjectFunctionBuilder::processBB(), otawa::ParamExeGraphBBTime::processBB(), otawa::ipet::BasicObjectFunctionBuilder::processBB(), otawa::cfgio::Output::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::branch::CondNumber::processBB(), otawa::BBRatioDisplayer::processBB(), otawa::LiExeGraphBBTime::processBB(), otawa::GraphBBTime< G >::processBB(), otawa::BBStatCollector::processCFG(), otawa::cat::CATConstraintBuilder::processLBlockSet(), otawa::ccg::ConstraintBuilder::processLBlockSet(), otawa::etime::EdgeTimeBuilder::processSequence(), otawa::display::CFGAdapter::VertexMap< T >::put(), otawa::SubCFGBuilder::SubCFGBuilder(), otawa::dfa::hai::HalfAbsInt< FixPoint >::tryAddToWorkList(), and otawa::dfa::XCFGVisitor< P >::XCFGVisitor().
void otawa::PropList::print (elm::io::Output & out) const inherited
Display the current property list.
Parameters
out Output to use.
Referenced by otawa::Edge::kindName(), otawa::operator<<(), and otawa::ContextualProperty::print().
void otawa::BasicBlock::print (io::Output & out) const inherited
Print the reference for a basic block.
Parameters
out Output stream.
References otawa::BasicBlock::address(), otawa::BasicBlock::isEntry(), otawa::BasicBlock::isExit(), and otawa::BasicBlock::number().
Referenced by otawa::BasicBlock::firstInst(), and otawa::operator<<().
void otawa::PropList::removeAllProp (const AbstractIdentifier * id) inherited
Remove all the properties matching the given identifier.
Parameters
id Identifier of properties to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::LoopUnroller::unroll().
void otawa::BasicBlock::removeInEdge (Edge * edge) inline inherited
Remove an input edge from the basic block input list.
Parameters
edge Edge to remove.
References otawa::BasicBlock::ins.
Referenced by otawa::Edge::toCall(), and otawa::Edge::~Edge().
void otawa::BasicBlock::removeOutEdge (Edge * edge) inline inherited
Remove an output edge from the basic block output list.
Parameters
edge Edge to remove.
References otawa::BasicBlock::outs.
Referenced by otawa::Edge::~Edge().
void otawa::PropList::removeProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier.
Parameters
id Identifier of the property to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::PSTBuilder::buildTree(), otawa::BBRemover< T >::clean(), otawa::CFGBuilder::cleanup(), otawa::display::CFGOutput::processCFG(), otawa::SubCFGBuilder::processWorkSpace(), otawa::Identifier< otawa::arm::Info * >::remove(), and otawa::ContextualPath::Ref< T >::remove().
void otawa::PropList::removeProp (const AbstractIdentifier & id) inline inherited
References otawa::PropList::removeProp().
Referenced by otawa::PropList::removeProp().
void otawa::CodeBasicBlock::set (Inst * _first, t::size size) inline
References otawa::BasicBlock::_size, otawa::BasicBlock::first, and otawa::BasicBlock::size().
void otawa::CodeBasicBlock::setCall (void) inline
References otawa::BasicBlock::FLAG_Call, otawa::BasicBlock::FLAG_Return, and otawa::BasicBlock::flags.
void otawa::CodeBasicBlock::setCond (void) inline
References otawa::BasicBlock::FLAG_Cond, and otawa::BasicBlock::flags.
void otawa::CodeBasicBlock::setFirst (Inst * _first) inline
References otawa::BasicBlock::first.
void otawa::BasicBlock::setNotTaken (BasicBlock * bb) protected inherited
Set the following basic block.
Parameters
bb New following basic block.
Deprecated:
{Use Edge class instead.}
References otawa::BasicBlock::Edge, and EDGE_NotTaken.
void otawa::PropList::setProp (Property * prop) inherited
Set the property in the property list removing any double.
Parameters
prop Property to set.
References otawa::Property::_next, otawa::Property::id(), and otawa::Property::next().
void otawa::PropList::setProp (const AbstractIdentifier * id) inline inherited
References otawa::PropList::setProp().
Referenced by otawa::PropList::setProp().
void otawa::CodeBasicBlock::setReturn (void) inline
References otawa::BasicBlock::FLAG_Call, otawa::BasicBlock::FLAG_Return, and otawa::BasicBlock::flags.
void otawa::CodeBasicBlock::setSize (t::size size) inline
References otawa::BasicBlock::_size, and otawa::BasicBlock::size().
Referenced by otawa::DelayedBuilder::buildBB(), otawa::CFGBuilder::buildCFG(), otawa::DelayedBuilder::makeBB(), and otawa::DelayedBuilder::makeNOp().
void otawa::BasicBlock::setTaken (BasicBlock * bb) protected inherited
Set the target basic block of the branch last instruction.
Parameters
bb New target basic block.
Deprecated:
{Use Edge class instead.}
References otawa::BasicBlock::Edge, and EDGE_Taken.
void otawa::CodeBasicBlock::setUnknown (void) inline
References otawa::BasicBlock::FLAG_Unknown, and otawa::BasicBlock::flags.
size_t otawa::BasicBlock::size (void) const inline inherited
Get the size of the basic block.
Returns
Size of basic block.
References otawa::BasicBlock::_size.
Referenced by otawa::ccg::LBlockBuilder::addLBlock(), otawa::LBlockBuilder::addLBlock(), otawa::CFGBuilder::buildCFG(), CodeBasicBlock(), otawa::BasicBlock::getBlockSize(), otawa::ipet::TrivialInstCacheManager::processBB(), otawa::cfgio::Output::processBB(), otawa::ccg::LBlockBuilder::processBB(), otawa::LBlockBuilder::processBB(), otawa::CFGSaver::processBB(), otawa::BBRatioDisplayer::processBB(), set(), setSize(), otawa::BasicBlock::topAddress(), and otawa::VirtualBasicBlock::VirtualBasicBlock().
Address otawa::BasicBlock::topAddress (void) const inline inherited
References otawa::BasicBlock::address(), otawa::BasicBlock::countInsts(), and otawa::BasicBlock::size().
Referenced by otawa::BasicBlock::BundleIter::BundleIter(), otawa::BasicBlock::InstIter::InstIter(), otawa::BBRatioDisplayer::processBB(), and otawa::BasicBlock::Bundle::size().
Friends And Related Function Documentation
friend class CFGInfo friend
Member Data Documentation
CFG* otawa::BasicBlock::_cfg inherited
Referenced by otawa::VirtualCFG::addBB(), otawa::BasicBlock::BasicBlock(), otawa::BasicBlock::cfg(), and otawa::VirtualCFG::VirtualCFG().
t::size otawa::BasicBlock::_size inherited
Referenced by otawa::BasicBlock::BasicBlock(), set(), setSize(), otawa::BasicBlock::size(), and otawa::VirtualBasicBlock::VirtualBasicBlock().
const PropList otawa::PropList::EMPTY static inherited
This is an empty proplist for convenience.
Referenced by otawa::DynProcessor::configure(), otawa::ActualFeature::processor(), otawa::SilentFeature::SilentFeature(), otawa::Processor::version(), and otawa::display::Driver::~Driver().
Inst* otawa::BasicBlock::first inherited
Referenced by otawa::BasicBlock::address(), otawa::BasicBlock::BasicBlock(), otawa::EndBasicBlock::EndBasicBlock(), otawa::BasicBlock::firstInst(), set(), setFirst(), and otawa::VirtualBasicBlock::VirtualBasicBlock().
const unsigned long otawa::BasicBlock::FLAG_Call = 0x01 static protected inherited
Referenced by otawa::CFGBuilder::buildCFG(), otawa::BasicBlock::isCall(), otawa::CFG::scan(), setCall(), setReturn(), and otawa::Edge::toCall().
const unsigned long otawa::BasicBlock::FLAG_Cond = 0x40 static protected inherited
Referenced by otawa::CFGBuilder::buildCFG(), otawa::BasicBlock::isConditional(), and setCond().
const unsigned long otawa::BasicBlock::FLAG_Entry = 0x08 static protected inherited
Referenced by otawa::BasicBlock::isEnd(), and otawa::BasicBlock::isEntry().
const unsigned long otawa::BasicBlock::FLAG_Exit = 0x10 static protected inherited
Referenced by otawa::BasicBlock::isEnd(), and otawa::BasicBlock::isExit().
const unsigned long otawa::BasicBlock::FLAG_Return = 0x04 static protected inherited
Referenced by otawa::CFGBuilder::buildCFG(), otawa::BasicBlock::isReturn(), setCall(), and setReturn().
const unsigned long otawa::BasicBlock::FLAG_Unknown = 0x02 static protected inherited
Referenced by otawa::CFGBuilder::buildCFG(), otawa::BasicBlock::isTargetUnknown(), and setUnknown().
const unsigned long otawa::BasicBlock::FLAG_Virtual = 0x20 static protected inherited
Referenced by otawa::BasicBlock::isVirtual(), and otawa::VirtualBasicBlock::VirtualBasicBlock().
unsigned long otawa::BasicBlock::flags inherited
Referenced by otawa::BasicBlock::BasicBlock(), otawa::CFGBuilder::buildCFG(), CodeBasicBlock(), otawa::EndBasicBlock::EndBasicBlock(), otawa::BasicBlock::getFlags(), otawa::BasicBlock::isCall(), otawa::BasicBlock::isConditional(), otawa::BasicBlock::isEnd(), otawa::BasicBlock::isEntry(), otawa::BasicBlock::isExit(), otawa::BasicBlock::isReturn(), otawa::BasicBlock::isTargetUnknown(), otawa::BasicBlock::isVirtual(), setCall(), setCond(), setReturn(), setUnknown(), otawa::Edge::toCall(), and otawa::VirtualBasicBlock::VirtualBasicBlock().
Identifier< BasicBlock * > otawa::BasicBlock::ID static inherited
Identifier of the basic block pseudo-instruction.
elm::genstruct::SLList<Edge *> otawa::BasicBlock::ins inherited
Referenced by otawa::BasicBlock::addInEdge(), and otawa::BasicBlock::removeInEdge().
BasicBlock & otawa::BasicBlock::null_bb = null_bb_inst static protected inherited
Referenced by otawa::EndBasicBlock::EndBasicBlock().
elm::genstruct::SLList<Edge *> otawa::BasicBlock::outs inherited
Referenced by otawa::BasicBlock::addOutEdge(), and otawa::BasicBlock::removeOutEdge().
The documentation for this class was generated from the following files:
include/otawa/cfg/BasicBlock.h
src/prog/BasicBlock.cpp