Otawa: otawa::Loader Class Reference
otawa::Loader Class Reference abstract
This interface is implemented by all objects that may build and provide a process.
#include <otawa/prog/Loader.h>
Public Member Functions
Loader (CString name, Version version, Version plugger_version, const elm::system::Plugin::aliases_t &aliases=elm::system::Plugin::aliases_t::EMPTY)
virtual CString getName (void) const =0
Get the name of the loader.
virtual Process * load (Manager *man, CString path, const PropList &props)=0
Load the file matching the given path with the given properties.
virtual Process * create (Manager *man, const PropList &props)=0
Build a new empty process matching the given properties.
void check (WorkSpace *ws, cstring name, const Version &version)
Check the loader used in the given workspace matches the given name and version.
Protected Member Functions
virtual ~Loader (void)
Virtual destructor for destruction customization.
Friends
class Manager
Detailed Description
This interface is implemented by all objects that may build and provide a process.
Many kind of loader may exists from the simple binary loader to the complex program builder.
The loader may put on the created processes zero or several of the following features according the machine-level feature provided:
FLOAT_MEMORY_ACCESS_FEATURE
MEMORY_ACCESS_FEATURE
REGISTER_USAGE_FEATURE
STACK_USAGE_FEATURE
Constructor & Destructor Documentation
Loader::~Loader (void) inline protected virtual
Virtual destructor for destruction customization.
References otawa::sem::load(), and name.
otawa::Loader::Loader (CString name, Version version, Version plugger_version, const elm::system::Plugin::aliases_t & aliases = elm::system::Plugin::aliases_t::EMPTY)
Member Function Documentation
void Loader::check (WorkSpace * ws, cstring name, const Version & version)
Check the loader used in the given workspace matches the given name and version.
Parameters
ws Current workspace.
name Name to check.
version Version to check.
Exceptions
otawa::Exception If the loader does not match.
References otawa::Process::loader(), otawa::Processor::name(), and otawa::WorkSpace::process().
Process * Loader::create (Manager * man, const PropList & props) pure virtual
Build a new empty process matching the given properties.
Parameters
man Caller manager.
props Properties describing the process.
Returns
Created process.
Exceptions
UnsupportedPlatformException Loader does not handle
CString Loader::getName (void) const pure virtual
Get the name of the loader.
Returns
Name of the loader.
Process * Loader::load (Manager * man, CString path, const PropList & props) pure virtual
Load the file matching the given path with the given properties.
The exact type of the file and of the properties depends upon the underlying loader.
Parameters
man Caller manager.
path Path to the file to load.
props Property for loading.
Returns
Process containing the loaded file.
Exceptions
LoadException Error during the load.
UnsupportedPlatformException Loader does not handle this platform.
Referenced by otawa::Manager::loadBin().
Friends And Related Function Documentation
friend class Manager friend
The documentation for this class was generated from the following files:
include/otawa/prog/Loader.h
src/prog/Loader.cpp