Otawa: otawa::LiExeNode Class Reference
otawa::LiExeNode Class Reference
#include <otawa/exegraph/LiExeGraph.h>
Public Member Functions
LiExeNode (ExeGraph< LiExeNode > *graph, PipelineStage< LiExeNode > *stage, ExeInst< LiExeNode > *inst)
Builds an execution node tuned for Li's algorithm.
int time (ExeGraph< LiExeNode >::time_step_t step, ExeGraph< LiExeNode >::time_bound_t bound)
void setTime (ExeGraph< LiExeNode >::time_step_t step, ExeGraph< LiExeNode >::time_bound_t bound, int time)
void shade (void)
Marks the node as "shaded" (see Li's algorithm)
bool isShaded (void)
PipelineStage< N > * pipelineStage (void)
ExeInst< N > * inst (void)
int latency ()
int latency (time_bound_t bound)
void setLatency (time_bound_t bound, int latency)
bool needsOperands (void)
void setNeedsOperands (bool val)
Sets whether the node depends on input operands.
bool producesOperands (void)
void setProducesOperands (bool val)
Sets whether the node produces output operands.
void addContender (N *cont)
Adds a contender to the lists of contenders for the node.
elm::genstruct::Vector< N * > * contenders ()
elm::String name ()
Returns the name of the node, composed of the name of the pipeline stage and the name of the instruction (e.g.
int index (void) const
bool hasSucc (void) const
bool hasPred (void) const
int countSucc (void) const
int countPred (void) const
bool isPredOf (const GenNode *node)
bool isSuccOf (const GenNode *node)
Protected Attributes
elm::genstruct::Vector< N * > _contenders
Private Attributes
int _time [ExeGraph< LiExeNode >::STEPS][ExeGraph< LiExeNode >::BOUNDS]
bool _shaded
LiExeGraph * _graph
Constructor & Destructor Documentation
LiExeNode::LiExeNode (ExeGraph< LiExeNode > * graph, PipelineStage< LiExeNode > * stage, ExeInst< LiExeNode > * inst) inline
Builds an execution node tuned for Li's algorithm.
Parameters
graph The execution graph that contains the node. aram stage The pipeline stage the node is related to.
inst The instruction the node is related to.
References otawa::ExeInst< N >::codePart(), INFINITE_TIME, otawa::PipelineStage< N >::minLatency(), and setTime().
Member Function Documentation
template<class N> void otawa::ExeGraph< N >::ExeNode::addContender (N * cont) inline inherited
Adds a contender to the lists of contenders for the node.
Parameters
cont The new contender for the node.
template<class N> elm::genstruct::Vector< N * > * otawa::ExeGraph< N >::ExeNode::contenders (void) inline inherited
Returns
The list of contenders of the node.
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::countPred (void) const inline inherited
References otawa::graph::Node::countPred().
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::countSucc (void) const inline inherited
References otawa::graph::Node::countSucc().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::hasPred (void) const inline inherited
References otawa::graph::Node::hasPred().
Referenced by otawa::LiExeGraph::shadeNodes().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::hasSucc (void) const inline inherited
References otawa::graph::Node::hasSucc().
template<class N, class E> int otawa::GenGraph< N, E >::GenNode::index (void) const inline inherited
References otawa::graph::Node::index().
Referenced by otawa::ParamExeGraph::cost().
template<class N> ExeInst< N > * otawa::ExeGraph< N >::ExeNode::inst (void) inline inherited
Returns
The instruction the node is related to.
References otawa::ExeInst< N >::_inst.
Referenced by otawa::ParamExeGraph::analyzeContentions(), otawa::LiExeGraph::maxTimeToNode(), otawa::LiExeGraph::nodeEarliestTimes(), and otawa::LiExeGraph::nodeLatestTimes().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::isPredOf (const GenNode * node) inline inherited
References otawa::graph::Node::countPred().
LiExeNode::isShaded (void) inline
Returns
Whether the node is shaded or not.
References _shaded.
Referenced by otawa::LiExeGraph::nodeLatestTimes().
template<class N, class E> bool otawa::GenGraph< N, E >::GenNode::isSuccOf (const GenNode * node) inline inherited
References otawa::graph::Node::isSuccOf().
template<class N> int otawa::ExeGraph< N >::ExeNode::latency () inline inherited
Returns
The minimum node latency.
Referenced by otawa::LiExeGraph::analyze(), otawa::ParamExeGraph::Delta(), otawa::LiExeGraph::latestTimes(), otawa::LiExeGraph::maxTimeToNode(), otawa::LiExeGraph::nodeEarliestTimes(), and otawa::LiExeGraph::nodeLatestTimes().
template<class N> int otawa::ExeGraph< N >::ExeNode::latency (time_bound_t bound) inline inherited
Parameters
bound A time bound (MIN or MAX).
Returns
The node latency.
template<class N> elm::String otawa::ExeGraph< N >::ExeNode::name (void) inline inherited
Returns the name of the node, composed of the name of the pipeline stage and the name of the instruction (e.g.
"CM(I8)").
Returns
Node name.
Referenced by otawa::ParamExeGraph::Delta().
template<class N> bool otawa::ExeGraph< N >::ExeNode::needsOperands (void) inline inherited
Returns
Whether the node depends on input operands.
template<class N> PipelineStage< N > otawa::ExeGraph< N >::ExeNode::pipelineStage (void) inline inherited
Returns
The pipeline stage the node is related to.
Referenced by otawa::ParamExeGraph::Delta(), otawa::LiExeGraph::nodeEarliestTimes(), otawa::LiExeGraph::nodeLatestTimes(), and otawa::ParamExeNode::ParamExeNode().
template<class N> bool otawa::ExeGraph< N >::ExeNode::producesOperands (void) inline inherited
Returns
Whether the node produces output operands.
template<class N> void otawa::ExeGraph< N >::ExeNode::setLatency (time_bound_t bound, int latency) inline inherited
Parameters
bound A time bound (MIN or MAX).
latency The new value of the latency.
template<class N> void otawa::ExeGraph< N >::ExeNode::setNeedsOperands (bool val) inline inherited
Sets whether the node depends on input operands.
template<class N> void otawa::ExeGraph< N >::ExeNode::setProducesOperands (bool val) inline inherited
Sets whether the node produces output operands.
LiExeNode::setTime (ExeGraph< LiExeNode >::time_step_t step, ExeGraph< LiExeNode >::time_bound_t bound, int time) inline
Parameters
step Time step (READY, START, FINISH)
bound Time bound (MIN, MAX)
time The node new time value. Sets the new node time value.
References _graph, _time, otawa::LiExeGraph::setTimesChanged(), and time().
Referenced by otawa::LiExeGraph::earliestTimes(), otawa::LiExeGraph::latestTimes(), LiExeNode(), otawa::LiExeGraph::nodeEarliestTimes(), otawa::LiExeGraph::nodeLatestTimes(), and time().
LiExeNode::shade (void) inline
Marks the node as "shaded" (see Li's algorithm)
LiExeNode::time (ExeGraph< LiExeNode >::time_step_t step, ExeGraph< LiExeNode >::time_bound_t bound) inline
Parameters
step Time step (READY, START, FINISH)
bound Time bound (MIN, MAX)
Returns
The node time
References setTime().
Referenced by otawa::LiExeGraph::analyze(), otawa::LiExeGraph::nodeEarliestTimes(), otawa::LiExeGraph::nodeLatestTimes(), otawa::LiExeGraph::separated(), setTime(), otawa::LiExeGraph::shadeNodes(), and otawa::LiExeGraph::timeName().
Member Data Documentation
template<class N> elm::genstruct::Vector<N *> otawa::ExeGraph< N >::ExeNode::_contenders protected inherited
LiExeGraph* otawa::LiExeNode::_graph private
Referenced by setTime().
bool otawa::LiExeNode::_shaded private
Referenced by isShaded().
int otawa::LiExeNode::_time[ExeGraph< LiExeNode >::STEPS][ExeGraph< LiExeNode >::BOUNDS] private
Referenced by setTime().
The documentation for this class was generated from the following files:
include/otawa/exegraph/LiExeGraph.h
src/prog/exegraph_LiExeGraph.cpp