Otawa: otawa::dcache::MUSTProblem::Domain Class Reference
otawa::dcache::MUSTProblem::Domain Class Reference
#include <otawa/dcache/ACSBuilder.h>
Public Member Functions
Domain (const int _size, const int _A)
Domain (const Domain &source)
Domain (const ACS &source)
Domain & operator= (const ACS &d)
void addDamage (const int id, const int damage)
void inject (const int id)
void ageAll (void)
int getSize (void) const
Get the number of blocks of the ACS.
int getA (void) const
bool equals (const ACS &dom) const
Test if two ACS are equals.
void empty (void)
Set all block to age -1.
bool contains (const int id) const
Test if a block is in the ACS , that is, its each age is in the interval [0, A[ where A is the associativity of the cache.
void print (elm::io::Output &output) const
Print the ACS.
int getAge (int id) const
Get the age of a block.
void setAge (const int id, const int _age)
Change the age of a block.
void set (const ACS &dom)
Set the ages of the given ACS to the current one.
const int & operator[] (int i) const
int & operator[] (int i)
Protected Attributes
int A
int size
int * age
Constructor & Destructor Documentation
otawa::dcache::MUSTProblem::Domain::Domain (const int _size, const int _A) inline
otawa::dcache::MUSTProblem::Domain::Domain (const Domain & source) inline
otawa::dcache::MUSTProblem::Domain::Domain (const ACS & source) inline
Member Function Documentation
void otawa::dcache::MUSTProblem::Domain::addDamage (const int id, const int damage) inline
void otawa::dcache::MUSTProblem::Domain::ageAll (void) inline
Referenced by otawa::dcache::MUSTPERS::ageAll(), and otawa::dcache::MUSTProblem::update().
bool otawa::dcache::ACS::contains (const int id) const inline inherited
Test if a block is in the ACS , that is, its each age is in the interval [0, A[ where A is the associativity of the cache.
Parameters
id Number of the tested block.
Returns
True if it is in the cache, false else.
Referenced by otawa::dcache::PERSProblem::Item::inject(), otawa::dcache::PERSProblem::Item::isPersistent(), and otawa::dcache::CATBuilder::processLBlockSet().
void otawa::dcache::ACS::empty (void) inline inherited
Set all block to age -1.
Referenced by otawa::dcache::PERSProblem::Domain::enterContext(), otawa::dcache::MAYProblem::MAYProblem(), otawa::dcache::MUSTProblem::MUSTProblem(), otawa::dcache::MUSTProblem::purge(), and otawa::dcache::PERSProblem::Domain::~Domain().
bool otawa::dcache::ACS::equals (const ACS & acs) const inline inherited
Test if two ACS are equals.
Parameters
acs ACS to compare the current one with.
Returns
True if both ACS are equal, false else.
References otawa::dcache::ACS::A, otawa::dcache::ACS::age, and otawa::dcache::ACS::size.
Referenced by otawa::dcache::MUSTProblem::equals(), and otawa::dcache::MAYProblem::equals().
int otawa::dcache::ACS::getA (void) const inline inherited
Referenced by otawa::dcache::PERSProblem::purge().
int otawa::dcache::ACS::getAge (int id) const inline inherited
Get the age of a block.
Parameters
Number of the block.
Returns
Block age.
int otawa::dcache::ACS::getSize (void) const inline inherited
Get the number of blocks of the ACS.
Returns
Number of blocks.
Referenced by otawa::dcache::PERSProblem::purge().
void otawa::dcache::MUSTProblem::Domain::inject (const int id) inline
Referenced by otawa::dcache::MUSTPERS::inject(), and otawa::dcache::MUSTProblem::update().
Domain& otawa::dcache::MUSTProblem::Domain::operator= (const ACS & d) inline
const int& otawa::dcache::ACS::operator[] (int i) const inline inherited
int& otawa::dcache::ACS::operator[] (int i) inline inherited
void otawa::dcache::ACS::print (elm::io::Output & output) const inherited
Print the ACS.
Parameters
out Stream to output to.
Referenced by otawa::dcache::operator<<(), otawa::dcache::MUSTPERS::print(), and otawa::dcache::PERSProblem::Domain::refresh().
void otawa::dcache::ACS::set (const ACS & acs) inline inherited
Set the ages of the given ACS to the current one.
Parameters
acs ACS to set.
void otawa::dcache::ACS::setAge (const int id, const int _age) inline inherited
Change the age of a block.
Parameters
id Block number.
age New age to set.
Member Data Documentation
int otawa::dcache::ACS::A protected inherited
Referenced by otawa::dcache::PERSProblem::Item::equals(), otawa::dcache::ACS::equals(), otawa::dcache::PERSProblem::Item::isWiped(), otawa::dcache::PERSProblem::Item::lub(), and otawa::dcache::MAYProblem::Domain::lub().
int* otawa::dcache::ACS::age protected inherited
Referenced by otawa::dcache::ACS::ACS(), otawa::dcache::PERSProblem::Item::equals(), otawa::dcache::ACS::equals(), otawa::dcache::PERSProblem::Item::isWiped(), otawa::dcache::PERSProblem::Item::lub(), otawa::dcache::MAYProblem::Domain::lub(), and otawa::dcache::PERSProblem::Item::refresh().
int otawa::dcache::ACS::size protected inherited
Referenced by otawa::dcache::PERSProblem::Item::equals(), otawa::dcache::ACS::equals(), otawa::dcache::PERSProblem::Item::lub(), otawa::dcache::MAYProblem::Domain::lub(), and otawa::dcache::PERSProblem::Item::refresh().
The documentation for this class was generated from the following file:
include/otawa/dcache/ACSBuilder.h