Otawa: otawa::AbsoluteAddress Class Reference
otawa::AbsoluteAddress Class Reference
Symbolic address as an absolute address.
#include <otawa/util/SymAddress.h>
Public Member Functions
AbsoluteAddress (Address addr)
virtual Address toAddress (WorkSpace *ws)
Expand the current symbolic address as an actual address in the given workspace.
virtual CFG * cfg (WorkSpace *ws)
Get the CFG matching the given address.
virtual void print (io::Output &out)
Print the symbolic address.
Static Public Member Functions
static SymAddress * parse (string str) throw (otawa::Exception)
Parse a symbolic address from a string.
Private Attributes
Address _addr
Detailed Description
Symbolic address as an absolute address.
Constructor & Destructor Documentation
otawa::AbsoluteAddress::AbsoluteAddress (Address addr)
Member Function Documentation
CFG * otawa::AbsoluteAddress::cfg (WorkSpace * ws) virtual
Get the CFG matching the given address.
CFG_INFO_FEATURE should be available first.
Parameters
ws Workspace to look in.
Returns
Found CFG or null.
Implements otawa::SymAddress.
References _addr, otawa::CFG_INFO_FEATURE, otawa::WorkSpace::findInstAt(), otawa::CFGInfo::ID, and otawa::WorkSpace::isProvided().
SymAddress * otawa::SymAddress::parse (string str) throw (otawa::Exception) static inherited
Parse a symbolic address from a string.
Parameters
str String to parse.
Returns
Built symbolic address (deletion is delegated to the caller).
Exceptions
otawa::Exception Thrown if there is a parsing error.
References otawa::sem::neg().
Referenced by otawa::Application::parseAddress().
void otawa::AbsoluteAddress::print (io::Output & out) virtual
Print the symbolic address.
Parameters
out Stream to output to.
Implements otawa::SymAddress.
References _addr.
Address otawa::AbsoluteAddress::toAddress (WorkSpace * ws) virtual
Expand the current symbolic address as an actual address in the given workspace.
Parameters
ws Workspace to expand in.
Returns
Actual address.
Implements otawa::SymAddress.
References _addr.
Member Data Documentation
Address otawa::AbsoluteAddress::_addr private
Referenced by cfg(), print(), and toAddress().
The documentation for this class was generated from the following files:
include/otawa/util/SymAddress.h
src/prog/util_SymAddress.cpp