Otawa: otawa::dcache::PERSProblem::Domain Class Reference
otawa::dcache::PERSProblem::Domain Class Reference
#include <otawa/dcache/PERSProblem.h>
Public Member Functions
Domain (const int _size, const int _A)
Domain (const Domain &source)
~Domain (void)
Domain & operator= (const Domain &src)
Assignement of persistence analysis ACS.
void lub (const Domain &dom)
Compute the join of the current value with the given one and the result is left in the current ACS.
void lub (const Item &item)
Special LUB: do the lub of each Item in current domain with item passed as parameter.
bool equals (const Domain &dom) const
Test if two ACS are equals.
void empty (void)
Empty the domain.
void setToBottom (void)
Set the bottom value in the ACS.
Item & getWhole (void)
bool contains (const int id, const int index)
void inject (MUSTProblem::Domain *must, const int id)
Consider that the designed block is accessed.
bool isWiped (const int id, const int index)
int getAge (const int id, const int index) const
bool isPersistent (const int id, const int index)
void addDamage (const int id, const int index, int damage)
void addDamage (const int id, int damage)
In partial analysis, add age damage to the given block.
void refresh (const int id, const int index, int newage)
void refresh (const int id, int newage)
Refresh a block to the given age (if required).
void print (elm::io::Output &output) const
Display the ACS.
void enterContext (void)
Called when a loop context is entered to add a level.
void leaveContext (void)
Called when a loop context is left to remove the top-level.
int length (void) const
Item & getItem (const int idx) const
void ageAll (void)
Consider that an unknown access is performed and, therefore, all blocks must be aged.
void setNotBottom (void)
void set (const ACS &w, const genstruct::Table< ACS * > &d)
Private Attributes
Item whole
genstruct::Vector< Item * > data
bool isBottom
Constructor & Destructor Documentation
otawa::dcache::PERSProblem::Domain::Domain (const int _size, const int _A) inline
otawa::dcache::PERSProblem::Domain::Domain (const Domain & source) inline
References data.
otawa::dcache::PERSProblem::Domain::~Domain (void) inline
References otawa::dcache::ACS::empty(), otawa::dcache::PERSProblem::Item::equals(), otawa::dcache::PERSProblem::Item::lub(), and otawa::dcache::PERSProblem::Item::operator=().
Member Function Documentation
void otawa::dcache::PERSProblem::Domain::addDamage (const int id, const int index, int damage) inline
References otawa::dcache::PERSProblem::Item::addDamage().
void otawa::dcache::PERSProblem::Domain::addDamage (const int id, int damage)
In partial analysis, add age damage to the given block.
Parameters
id Identity of the aged block.
damage Damage value.
void otawa::dcache::PERSProblem::Domain::ageAll (void)
Consider that an unknown access is performed and, therefore, all blocks must be aged.
Referenced by otawa::dcache::MUSTPERS::ageAll().
bool otawa::dcache::PERSProblem::Domain::contains (const int id, const int index) inline
References contains(), and otawa::dcache::PERSProblem::Item::inject().
Referenced by contains().
void otawa::dcache::PERSProblem::Domain::empty (void)
Empty the domain.
Referenced by otawa::dcache::MUSTPERS::emptyPers(), and otawa::dcache::PERSProblem::PERSProblem().
void otawa::dcache::PERSProblem::Domain::enterContext (void)
Called when a loop context is entered to add a level.
References otawa::dcache::ACS::empty().
Referenced by otawa::dcache::PERSProblem::enterContext(), and otawa::dcache::PERSProblem::PERSProblem().
bool otawa::dcache::PERSProblem::Domain::equals (const Domain & dom) const
Test if two ACS are equals.
Parameters
dom ACS to compare with.
Returns
True if they are equal, false else.
References data, otawa::dcache::MUSTPERS::equals(), isBottom, and whole.
Referenced by otawa::dcache::PERSProblem::equals().
int otawa::dcache::PERSProblem::Domain::getAge (const int id, const int index) const inline
References getAge().
Referenced by getAge().
Item& otawa::dcache::PERSProblem::Domain::getItem (const int idx) const inline
References otawa::dcache::PERSProblem::Item::ageAll().
Referenced by otawa::dcache::ACSBuilder::processLBlockSet(), and otawa::dcache::PERSProblem::purge().
Item& otawa::dcache::PERSProblem::Domain::getWhole (void) inline
Referenced by otawa::dcache::ACSBuilder::processLBlockSet(), and otawa::dcache::PERSProblem::purge().
void otawa::dcache::PERSProblem::Domain::inject (MUSTProblem::Domain * must, const int id)
Consider that the designed block is accessed.
Parameters
must Must ACS (useful to work-around a bug in the original persistence analysis).
id Identity of the accessed block.
References otawa::dcache::MUSTPERS::inject().
Referenced by otawa::dcache::MUSTPERS::inject().
bool otawa::dcache::PERSProblem::Domain::isPersistent (const int id, const int index) inline
References isPersistent().
Referenced by isPersistent(), and otawa::dcache::CATBuilder::processLBlockSet().
bool otawa::dcache::PERSProblem::Domain::isWiped (const int id, const int index) inline
References isWiped().
Referenced by isWiped().
void otawa::dcache::PERSProblem::Domain::leaveContext (void)
Called when a loop context is left to remove the top-level.
References otawa::dcache::ENTRY_PERS_ACS, otawa::dcache::LEVEL_PERS_ACS, otawa::dcache::PERS_ACS, and otawa::dcache::PERS_ACS_FEATURE.
Referenced by otawa::dcache::PERSProblem::leaveContext().
int otawa::dcache::PERSProblem::Domain::length (void) const inline
Referenced by otawa::dcache::CATBuilder::processLBlockSet(), otawa::dcache::ACSBuilder::processLBlockSet(), and otawa::dcache::PERSProblem::purge().
void otawa::dcache::PERSProblem::Domain::lub (const Domain & dom)
Compute the join of the current value with the given one and the result is left in the current ACS.
Parameters
dom ACS to join with.
References data, isBottom, otawa::dcache::MUSTPERS::lub(), and whole.
Referenced by otawa::dcache::PERSProblem::lub().
void otawa::dcache::PERSProblem::Domain::lub (const Item & item)
Special LUB: do the lub of each Item in current domain with item passed as parameter.
Used for the partial analysis
References otawa::dcache::MUSTPERS::lub().
PERSProblem::Domain & otawa::dcache::PERSProblem::Domain::operator= (const Domain & src)
Assignement of persistence analysis ACS.
Parameters
src Assigning domain.
Returns
Assigned domain.
References data, isBottom, and whole.
void otawa::dcache::PERSProblem::Domain::print (elm::io::Output & output) const
Display the ACS.
Parameters
output Stream to output to.
Referenced by otawa::dcache::operator<<(), and otawa::dcache::MUSTPERS::print().
void otawa::dcache::PERSProblem::Domain::refresh (const int id, const int index, int newage) inline
References otawa::dcache::PERSProblem::enterContext(), otawa::dcache::PERSProblem::leaveContext(), otawa::dcache::ACS::print(), and otawa::dcache::PERSProblem::Item::refresh().
void otawa::dcache::PERSProblem::Domain::refresh (const int id, int newage)
Refresh a block to the given age (if required).
Parameters
id Refreshed block.
newage Maximal new age of the block.
void otawa::dcache::PERSProblem::Domain::set (const ACS & w, const genstruct::Table< ACS * > & d) inline
References otawa::dcache::PERSProblem::Item::Item(), and otawa::clp::min().
Referenced by otawa::dcache::MUSTPERS::setPers().
void otawa::dcache::PERSProblem::Domain::setNotBottom (void) inline
void otawa::dcache::PERSProblem::Domain::setToBottom (void)
Set the bottom value in the ACS.
Referenced by otawa::dcache::PERSProblem::PERSProblem().
Member Data Documentation
genstruct::Vector<Item*> otawa::dcache::PERSProblem::Domain::data private
Referenced by Domain(), equals(), lub(), and operator=().
bool otawa::dcache::PERSProblem::Domain::isBottom private
Referenced by equals(), lub(), and operator=().
Item otawa::dcache::PERSProblem::Domain::whole private
Referenced by equals(), lub(), and operator=().
The documentation for this class was generated from the following files:
include/otawa/dcache/PERSProblem.h
src/dcache/dcache_ACSBuilder.cpp