Otawa: otawa::MAYBranch::Domain Class Reference
otawa::MAYBranch::Domain Class Reference
#include <otawa/branch/BranchProblem.h>
Public Member Functions
Domain (const int _size, const int _A)
~Domain ()
Domain (const Domain &source)
Domain & operator= (const Domain &src)
void lub (const Domain &dom)
int getSize (void)
bool equals (const Domain &dom) const
void empty ()
bool contains (const int id)
void inject (const int id)
void print (elm::io::Output &output) const
int getAge (int id) const
void setAge (const int id, const int _age)
Public Attributes
int * age
Private Attributes
int A
int size
Constructor & Destructor Documentation
otawa::MAYBranch::Domain::Domain (const int _size, const int _A) inline
References otawa::MUSTBranch::Domain::age, and otawa::MUSTBranch::Domain::size.
otawa::MAYBranch::Domain::~Domain () inline
References otawa::MUSTBranch::Domain::age.
otawa::MAYBranch::Domain::Domain (const Domain & source) inline
References otawa::MUSTBranch::Domain::age, age, and otawa::MUSTBranch::Domain::size.
Member Function Documentation
bool otawa::MAYBranch::Domain::contains (const int id) inline
References otawa::MUSTBranch::Domain::age.
Referenced by otawa::branch::BranchBuilder::categorize().
void otawa::MAYBranch::Domain::empty () inline
References otawa::MUSTBranch::Domain::age, and otawa::MUSTBranch::Domain::size.
Referenced by otawa::BranchProblem::Domain::empty(), and otawa::MAYBranch::MAYBranch().
bool otawa::MAYBranch::Domain::equals (const Domain & dom) const inline
References A, otawa::MUSTBranch::Domain::age, age, otawa::MUSTBranch::Domain::size, and size.
Referenced by otawa::MAYBranch::equals(), and otawa::BranchProblem::Domain::equals().
int otawa::MAYBranch::Domain::getAge (int id) const inline
References otawa::MUSTBranch::Domain::age.
int otawa::MAYBranch::Domain::getSize (void) inline
References otawa::MUSTBranch::Domain::size.
void otawa::MAYBranch::Domain::inject (const int id) inline
References otawa::MUSTBranch::Domain::age, otawa::MUSTBranch::Domain::contains(), and otawa::MUSTBranch::Domain::size.
Referenced by otawa::BranchProblem::Domain::inject().
void otawa::MAYBranch::Domain::lub (const Domain & dom) inline
References A, otawa::MUSTBranch::Domain::age, age, otawa::MUSTBranch::Domain::size, and size.
Referenced by otawa::MAYBranch::lub(), and otawa::BranchProblem::Domain::lub().
Domain& otawa::MAYBranch::Domain::operator= (const Domain & src) inline
References A, otawa::MUSTBranch::Domain::age, age, otawa::MUSTBranch::Domain::size, and size.
void otawa::MAYBranch::Domain::print (elm::io::Output & output) const inline
References otawa::MUSTBranch::Domain::age, and otawa::MUSTBranch::Domain::size.
Referenced by otawa::BranchProblem::Domain::print().
void otawa::MAYBranch::Domain::setAge (const int id, const int _age) inline
References otawa::MUSTBranch::Domain::age.
Member Data Documentation
int otawa::MAYBranch::Domain::A private
Referenced by equals(), lub(), and operator=().
int* otawa::MAYBranch::Domain::age
Referenced by Domain(), equals(), lub(), and operator=().
int otawa::MAYBranch::Domain::size private
Referenced by equals(), lub(), and operator=().
The documentation for this class was generated from the following file:
include/otawa/branch/BranchProblem.h