Otawa: otawa::etime::EdgeTimeBuilder::EventComparator Class Reference
otawa::etime::EdgeTimeBuilder::EventComparator Class Reference
Static Public Member Functions
static int compare (const event_t &e1, const event_t &e2)
Member Function Documentation
static int otawa::etime::EdgeTimeBuilder::EventComparator::compare (const event_t & e1, const event_t & e2) inline static
References otawa::etime::EdgeTimeBuilder::apply(), otawa::etime::EdgeTimeBuilder::countVarEvents(), otawa::etime::EdgeTimeBuilder::displayConfs(), otawa::etime::EdgeTimeBuilder::edge, otawa::etime::EdgeTimeBuilder::events, otawa::etime::EdgeTimeBuilder::genForOneCost(), otawa::etime::EdgeTimeBuilder::getBranchNode(), otawa::etime::EdgeTimeBuilder::rollback(), otawa::etime::EdgeTimeBuilder::sortEvents(), and otawa::etime::EdgeTimeBuilder::splitConfs().
The documentation for this class was generated from the following file:
include/otawa/etime/EdgeTimeBuilder.h