Otawa: otawa::sem::PathIter Class Reference
otawa::sem::PathIter Class Reference
Semantic Instructions
This iterator allows easily to traverse all execution paths of a block of semantic instructions.
#include <otawa/sem/PathIter.h>
Public Member Functions
void start (Inst *inst)
Start interpretation of an instruction.
void start (Process *proc)
Start interpretation of the initialization semantic instructions of a process.
void start (const sem::Block &block)
Start interpretation of a semantic block.
bool pathEnd (void) const
Test if the current instruction is a path end.
bool isCond (void) const
Test if the current instruction is a conditional, that means that two different paths will be created from this point.
bool ended (void) const
sem::inst item (void) const
void next (void)
Go to next semantic instruction.
opcode op (void) const
t::int16 d (void) const
t::int16 a (void) const
t::int16 b (void) const
t::uint32 cst (void) const
t::uint32 reg (void) const
t::uint32 addr (void) const
Private Attributes
sem::Block bb
genstruct::Vector< int > todo
int pc
Detailed Description
This iterator allows easily to traverse all execution paths of a block of semantic instructions.
As it may consume resources, it is delivered to support iteration on multiple blocks sequentially.
Member Function Documentation
t::int16 otawa::sem::PathIter::a (void) const inline
References otawa::sem::inst::a, and item().
t::uint32 otawa::sem::PathIter::addr (void) const inline
References otawa::sem::inst::addr(), and item().
t::int16 otawa::sem::PathIter::b (void) const inline
References otawa::sem::inst::b, and item().
t::uint32 otawa::sem::PathIter::cst (void) const inline
References otawa::sem::inst::cst, and item().
t::int16 otawa::sem::PathIter::d (void) const inline
References otawa::sem::inst::d(), and item().
bool otawa::sem::PathIter::ended (void) const inline
References pathEnd(), and todo.
Referenced by otawa::sem::BBIter::ended(), and otawa::sem::BBIter::instEnd().
bool otawa::sem::PathIter::isCond (void) const inline
Test if the current instruction is a conditional, that means that two different paths will be created from this point.
Returns
True if it is a condition, false else.
References bb, otawa::sem::IF, and pc.
Referenced by otawa::sem::BBIter::isCond().
sem::inst otawa::sem::PathIter::item (void) const inline
References bb, next(), and pc.
Referenced by a(), addr(), b(), cst(), d(), otawa::sem::BBIter::item(), op(), and reg().
void otawa::sem::PathIter::next (void)
Go to next semantic instruction.
References otawa::cfgio::bb().
Referenced by item().
opcode otawa::sem::PathIter::op (void) const inline
References item().
bool otawa::sem::PathIter::pathEnd (void) const inline
Test if the current instruction is a path end.
Returns
True if it is a path end, false else.
References bb, otawa::sem::CONT, and pc.
Referenced by ended(), and otawa::sem::BBIter::pathEnd().
t::uint32 otawa::sem::PathIter::reg (void) const inline
References item(), and otawa::sem::inst::reg().
void otawa::sem::PathIter::start (Inst * inst)
Start interpretation of an instruction.
Parameters
inst Instruction to interpret.
References otawa::cfgio::bb(), otawa::sem::cont(), and otawa::Inst::semInsts().
Referenced by otawa::stack::operator<<().
void otawa::sem::PathIter::start (Process * proc)
Start interpretation of the initialization semantic instructions of a process.
References otawa::cfgio::bb(), otawa::sem::cont(), and otawa::Process::semInit().
void otawa::sem::PathIter::start (const sem::Block & block)
Start interpretation of a semantic block.
Parameters
block Block to interpret.
References otawa::cfgio::bb(), and otawa::sem::cont().
Member Data Documentation
sem::Block otawa::sem::PathIter::bb private
Referenced by isCond(), item(), and pathEnd().
int otawa::sem::PathIter::pc private
Referenced by isCond(), item(), and pathEnd().
genstruct::Vector<int> otawa::sem::PathIter::todo private
Referenced by ended().
The documentation for this class was generated from the following files:
include/otawa/sem/PathIter.h
src/prog/sem.cpp