Otawa: otawa::ilp::AbstractSystem::AbstractVar Class Reference
otawa::ilp::AbstractSystem::AbstractVar Class Reference
Public Types
enum type_t { NO_TYPE = 0, INT = 1, BIN = 2, FLOAT = 3 }
Type of an ILP variable.
Public Member Functions
AbstractVar (const string &name, type_t type)
virtual ~AbstractVar (void)
int index (void) const
const string & name (void) const
Get the name of the variable if any.
type_t type (void) const
Get the type of the variable.
virtual void print (io::Output &out)
Print the name of the variable.
virtual Alias * toAlias (void)
If the variable is an alias, return it.
virtual double eval (System *sys)
Evaluate the variable in the given system.
Private Attributes
AbstractSystem * _sys
int _idx
Friends
class AbstractSystem
Member Enumeration Documentation
enum otawa::ilp::Var::type_t inherited
Type of an ILP variable.
Enumerator
NO_TYPE
Null value for ILP variable type.
INT
Integer (default) type for ILP variable.
BIN
Binary type (0 or 1) for ILP variable.
FLOAT
Real type for ILP variable.
Constructor & Destructor Documentation
otawa::ilp::AbstractSystem::AbstractVar::AbstractVar (const string & name, type_t type)
otawa::ilp::AbstractSystem::AbstractVar::~AbstractVar (void) virtual
References _sys, and otawa::ilp::AbstractSystem::remove().
Member Function Documentation
double otawa::ilp::Var::eval (System * sys) virtual inherited
Evaluate the variable in the given system.
Parameters
sys Resolved system to look in.
Returns
Value of the variable.
Reimplemented in otawa::ilp::Alias.
References otawa::ilp::System::valueOf().
int otawa::ilp::AbstractSystem::AbstractVar::index (void) const inline
String & otawa::ilp::Var::name (void) const inline inherited
Get the name of the variable if any.
Return an empty string if there is none.
Returns
Variable name.
Referenced by otawa::tsim::BBPath::makeVarName(), otawa::display::ILPSystemDisplayer::nameOf(), and otawa::ilp::operator<<().
void otawa::ilp::Var::print (io::Output & out) virtual inherited
Print the name of the variable.
Parameters
out Output to use.
References otawa::ilp::Var::_name.
Referenced by otawa::ilp::operator<<().
Alias * otawa::ilp::Var::toAlias (void) virtual inherited
If the variable is an alias, return it.
Returns
Alias object if it is alias, null else.
Reimplemented in otawa::ilp::Alias.
Referenced by otawa::ilp::Expression::add().
type_t otawa::ilp::Var::type (void) const inline inherited
Get the type of the variable.
Returns
Variable type.
Referenced by otawa::ilp::operator<<().
Friends And Related Function Documentation
friend class AbstractSystem friend
Member Data Documentation
int otawa::ilp::AbstractSystem::AbstractVar::_idx private
Referenced by otawa::ilp::AbstractSystem::newVar(), and otawa::ilp::AbstractSystem::remove().
AbstractSystem* otawa::ilp::AbstractSystem::AbstractVar::_sys private
Referenced by otawa::ilp::AbstractSystem::newVar(), and ~AbstractVar().
The documentation for this class was generated from the following files:
include/otawa/ilp/AbstractSystem.h
src/prog/ilp_AbstractSystem.cpp