Otawa: otawa::p::declare Class Reference
otawa::p::declare Class Reference
Processor Layer
Class to declare simple a processor.
#include <otawa/proc/Registration.h>
Public Member Functions
declare (otawa::p::init &i)
virtual ~declare (void)
virtual Processor * make (void) const
Build the registered processor.
virtual bool isFinal (void) const
const string & name (void) const
Get the name of the processor.
const Version & version (void) const
Get the version of the processor.
AbstractRegistration & base (void) const
bool provides (const AbstractFeature &feature)
Test if the current processor provides the given feature.
bool requires (const AbstractFeature &feature)
Test if the current processor requires the given feature.
bool invalidates (const AbstractFeature &feature)
Test if the current processor invalidates the given feature.
bool uses (const AbstractFeature &feature)
Test if the current processor uses or requires the given feature.
void initialize (void)
Internal.
Protected Member Functions
void init (cstring name, const Version &version, int tag, VarArg &args)
Initialize a registration from an argument list.
void setFeatures (const SLList< FeatureUsage > &features)
Set the features.
void setConfigs (const SLList< AbstractIdentifier * > &configs)
Set the configurations.
void record (void)
Private Attributes
AbstractMaker * _maker
Detailed Description
Class to declare simple a processor.
Each processor must have a static member of this type giving information about:
configuration identifier,
required features,
provided features,
invalidated features,
used features,
maker for the default processor.
Below an example of processor registration using declaration:
class MyProcessor: public BBProcessor {
public:
        static p::declare reg;
        ...
};
p::declare MyProcessor::reg =
                p::init("MyProcessor", Version(1, 0, 0), BBProcessor::reg)
                .require(OTHER_FEATURE)
                .provide(MY_FEATURE)
                .config(MY_CONFIG)
                .make<MyProcessor>());
Constructor & Destructor Documentation
otawa::p::declare::declare (otawa::p::init & i)
References otawa::p::init::_maker, _maker, otawa::p::init::configs, otawa::p::init::features, otawa::AbstractRegistration::record(), otawa::AbstractRegistration::setConfigs(), and otawa::AbstractRegistration::setFeatures().
otawa::p::declare::~declare (void) virtual
References _maker.
Member Function Documentation
AbstractRegistration& otawa::AbstractRegistration::base (void) const inline inherited
References otawa::make(), and name.
Referenced by otawa::AbstractRegistration::AbstractRegistration().
void otawa::AbstractRegistration::init (cstring name, const Version & version, int tag, VarArg & args) protected inherited
Initialize a registration from an argument list.
Parameters
name Processor name.
version Processor version.
tag First tag.
args List of pair (tag, value) ended by a otawa::p::end value.
References otawa::AbstractRegistration::_base, otawa::AbstractRegistration::_name, otawa::AbstractRegistration::_version, otawa::p::base, otawa::p::config, otawa::AbstractRegistration::configs, otawa::p::end, otawa::AbstractRegistration::features, otawa::p::invalidate, otawa::FeatureUsage::invalidate, otawa::AbstractRegistration::name(), otawa::p::provide, otawa::FeatureUsage::provide, otawa::AbstractRegistration::record(), otawa::p::require, otawa::FeatureUsage::require, otawa::p::use, otawa::FeatureUsage::use, and otawa::AbstractRegistration::version().
void otawa::AbstractRegistration::initialize (void) inherited
Internal.
References otawa::AbstractRegistration::name().
bool otawa::AbstractRegistration::invalidates (const AbstractFeature & feature) inherited
Test if the current processor invalidates the given feature.
Parameters
feature Tested feature.
Returns
True if the feature is invalidated, false else.
References otawa::FeatureUsage::invalidate.
bool otawa::p::declare::isFinal (void) const virtual
Implements otawa::AbstractRegistration.
Processor * otawa::p::declare::make (void) const virtual
Build the registered processor.
Returns
Built processor.
Implements otawa::AbstractRegistration.
References _maker, and otawa::AbstractMaker::make().
const string & otawa::AbstractRegistration::name (void) const inline inherited
Get the name of the processor.
Returns
Processor name.
Referenced by otawa::AbstractRegistration::init(), otawa::AbstractRegistration::initialize(), and otawa::Processor::process().
bool otawa::AbstractRegistration::provides (const AbstractFeature & feature) inherited
Test if the current processor provides the given feature.
Parameters
feature Tested feature.
Returns
True if the feature is provided, false else.
References otawa::FeatureUsage::provide.
void otawa::AbstractRegistration::record (void) protected inherited
Referenced by declare(), and otawa::AbstractRegistration::init().
bool otawa::AbstractRegistration::requires (const AbstractFeature & feature) inherited
Test if the current processor requires the given feature.
Parameters
feature Tested feature.
Returns
True if the feature is required, false else.
References otawa::FeatureUsage::require.
Referenced by otawa::AlternativeProcessor::AlternativeProcessor().
void otawa::AbstractRegistration::setConfigs (const SLList< AbstractIdentifier * > & coll) protected inherited
Set the configurations.
Parameters
coll Configures to set.
References otawa::AbstractRegistration::configs, and otawa::p::use.
Referenced by declare().
void otawa::AbstractRegistration::setFeatures (const SLList< FeatureUsage > & coll) protected inherited
Set the features.
Parameters
coll Features to set.
References otawa::AbstractRegistration::features, and otawa::p::use.
Referenced by declare().
bool otawa::AbstractRegistration::uses (const AbstractFeature & feature) inherited
Test if the current processor uses or requires the given feature.
Parameters
feature Tested feature.
Returns
True if the feature is used or required, false else.
References otawa::FeatureUsage::require, and otawa::FeatureUsage::use.
Referenced by otawa::Processor::process().
const Version & otawa::AbstractRegistration::version (void) const inline inherited
Get the version of the processor.
Returns
Processor version.
Referenced by otawa::AbstractRegistration::init().
Member Data Documentation
AbstractMaker* otawa::p::declare::_maker private
Referenced by declare(), make(), and ~declare().
The documentation for this class was generated from the following files:
include/otawa/proc/Registration.h
src/prog/proc_Registry.cpp