Otawa: otawa::tsim::BBPath Class Reference
otawa::tsim::BBPath Class Reference
#include <otawa/tsim/BBPath.h>
Classes
class BBIterator
Public Member Functions
elm::genstruct::Vector< BBPath * > * nexts ()
Builds a vector containing this BBSequence made longer with all successors of the last basic block it holds.
int time (WorkSpace *fw)
Returns the number of cycles the processor must do to cover the sequence.
int countInstructions ()
int t (WorkSpace *fw)
tests if two BBSequences are the same or not (same basic blocks in the path)
int length ()
Gives the number of basic blocks that composes this path.
int l ()
Same as BBPath::length()
Gives the number of basic blocks that composes this path.
BasicBlock * head ()
BasicBlock * tail ()
elm::String makeVarName ()
Creates a human-readable name (or representation) for this sequence
This name is like Seq_x1_x2_x3 if the basic blocks have names x1, x2 and x3.
ilp::Var * getVar (ilp::System *system, bool explicit_names=false)
if this sequence doesn't have a var (for the ilp system) attached, creates a new one
BBPath * sub (int begin, int end)
Returns a sub-path.
BBPath * operator() (int begin, int end)
Property * getProp (const AbstractIdentifier *id) const
Find a property by its identifier.
void setProp (Property *prop)
Set the property in the property list removing any double.
void setProp (const AbstractIdentifier *id)
void removeProp (const AbstractIdentifier *id)
Remove a property matching the given identifier.
void removeProp (const AbstractIdentifier &id)
Property * extractProp (const AbstractIdentifier *id)
Remove a property matching the given identifier and return it.
Property * extractProp (const AbstractIdentifier &id)
Remove a property matching the given identifier and return it.
void addProp (Property *prop)
Add property to the list without checking of duplication.
void removeAllProp (const AbstractIdentifier *id)
Remove all the properties matching the given identifier.
bool hasProp (const AbstractIdentifier &id) const
Test if the property list contains a property matching the given identifier.
void clearProps (void)
Remove all properties from the list.
void addProps (const PropList &props)
Add all properties from the given property list, in a reverse order.
void print (elm::io::Output &out) const
Display the current property list.
Static Public Member Functions
static BBPath * getBBPath (BasicBlock *start)
Returns the path of length 1 composed by only the given basic block.
static BBPath * getBBPath (elm::genstruct::Vector< BasicBlock * > *path)
Returns the path composed by the given path.
Static Public Attributes
static int instructions_simulated = 0
static const PropList EMPTY
This is an empty proplist for convenience.
Protected Member Functions
BBPath (BasicBlock *start)
Builds a new BBPath (length=1) from a given basic block.
BBPath (elm::genstruct::Vector< BasicBlock * > *path)
Builds a new BBPath from a vector of basic blocks.
int simulate (WorkSpace *fw)
Launches a simulation of the sequence.
Protected Attributes
int _length
elm::genstruct::Vector< BasicBlock * > basicBlocks
WorkSpace * last_framework_used
Friends
class PathManager
Detailed Description
Author
G. Cavaignac
This class represents a sequence of basic blocks, making a basic block path. BBPath are linked with others, and linked to basic blocks, and they are unique. One can't have two instances of the same path. It is possible to get a simulated time for this sequence
Constructor & Destructor Documentation
otawa::tsim::BBPath::BBPath (BasicBlock * start) protected
Builds a new BBPath (length=1) from a given basic block.
Parameters
framework FrameWork where one can get a simulator, or IPET::ID_Explicit
start starting basic block
References basicBlocks.
Referenced by getBBPath().
otawa::tsim::BBPath::BBPath (elm::genstruct::Vector< BasicBlock * > * path) protected
Builds a new BBPath from a vector of basic blocks.
Parameters
framework FrameWork where one can get a simulator, or IPET::ID_Explicit
path vector of the basic blocks
References basicBlocks, and l().
Member Function Documentation
void otawa::PropList::addProp (Property * prop) inherited
Add property to the list without checking of duplication.
Parameters
prop Property to add.
References otawa::Property::_next.
Referenced by otawa::Identifier< T >::add(), otawa::ast::ASTInfo::ASTInfo(), otawa::Identifier< otawa::arm::Info * >::copy(), otawa::AbstractIdentifier::initProps(), otawa::ContextualProperty::make(), otawa::script::Script::makeConfig(), otawa::ccg::Builder::processLBlockSet(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), and otawa::ContextualProperty::refProps().
void otawa::PropList::addProps (const PropList & props) inherited
Add all properties from the given property list, in a reverse order.
Parameters
props Property list to clone.
References otawa::Property::copy(), otawa::PropList::head, and otawa::Property::next().
Referenced by otawa::display::CFGDrawer::CFGDrawer(), otawa::display::GraphVizGraph::GraphVizGraph(), otawa::ParamFeature::instantiate(), otawa::Manager::loadXML(), otawa::display::GraphVizGraph::newEdge(), otawa::display::GraphVizGraph::newNode(), otawa::Process::Process(), otawa::display::GraphVizItem::setProps(), otawa::VirtualBasicBlock::VirtualBasicBlock(), and otawa::VirtualCFG::VirtualCFG().
void otawa::PropList::clearProps (void) inherited
Remove all properties from the list.
References otawa::Property::next().
Referenced by otawa::PSTBuilder::getVCFG(), otawa::display::GraphVizItem::setProps(), and otawa::WorkSpace::~WorkSpace().
int otawa::tsim::BBPath::countInstructions (void)
References _length, and basicBlocks.
Referenced by otawa::tsim::Delta::processCFG(), and simulate().
Property * otawa::PropList::extractProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::script::Script::makeConfig().
Property * otawa::PropList::extractProp (const AbstractIdentifier & id) inline inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::PropList::extractProp().
Referenced by otawa::PropList::extractProp().
BBPath * otawa::tsim::BBPath::getBBPath (BasicBlock * start) static
Returns the path of length 1 composed by only the given basic block.
If this path doesn't exist, creates it.
Parameters
start basic block
Returns
BBPath corresponding to the given basic block
References BBPath(), otawa::tsim::TreePath< T1, T2 >::rootData(), and otawa::tsim::Delta::TREE.
Referenced by nexts(), otawa::tsim::Delta::processBBPath(), otawa::tsim::Delta::processCFG(), and sub().
BBPath * otawa::tsim::BBPath::getBBPath (elm::genstruct::Vector< BasicBlock * > * path) static
Returns the path composed by the given path.
If this path doesn't exist, creates it.
Parameters
path vector of basic blocks composing the path
Returns
BBPath corresponding to the given path
References otawa::tsim::TreePath< T1, T2 >::add(), otawa::cfgio::bb(), BBPath(), otawa::tsim::TreePath< T1, T2 >::get(), and otawa::tsim::Delta::TREE.
Property * otawa::PropList::getProp (const AbstractIdentifier * id) const inherited
Find a property by its identifier.
Parameters
id Identifier of the property to find.
Returns
Found property or null.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::Identifier< otawa::arm::Info * >::exists(), otawa::ContextualProperty::exists(), otawa::ContextualProperty::find(), otawa::Identifier< T >::get(), otawa::ContextualProperty::make(), otawa::ParamFeature::matches(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::print(), otawa::ContextualProperty::print(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), otawa::ContextualProperty::refProps(), otawa::Identifier< T >::set(), otawa::Identifier< T >::use(), and otawa::Identifier< T >::value().
ilp::Var * otawa::tsim::BBPath::getVar (ilp::System * system, bool explicit_names = false)
if this sequence doesn't have a var (for the ilp system) attached, creates a new one
Returns
Var corresponding to this sequence
References basicBlocks, length(), makeVarName(), otawa::ilp::System::newVar(), and otawa::ipet::VAR.
Referenced by otawa::tsim::Delta::processBBPath().
bool otawa::PropList::hasProp (const AbstractIdentifier & id) const inline inherited
Test if the property list contains a property matching the given identifier.
Parameters
id Property identifier to look for.
Returns
True if the list contains the matching property, false else.
References otawa::p::print().
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::Monitor::configure(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::exists(), and otawa::Manager::setVerbosity().
BasicBlock * otawa::tsim::BBPath::head () inline
References basicBlocks.
Referenced by otawa::tsim::Delta::processBBPath(), and otawa::tsim::Delta::processCFG().
int otawa::tsim::BBPath::l () inline
Same as BBPath::length()
Gives the number of basic blocks that composes this path.
Returns
length of the path
References length().
Referenced by BBPath(), and nexts().
int otawa::tsim::BBPath::length (void) inline
Gives the number of basic blocks that composes this path.
Returns
length of the path
References _length.
Referenced by otawa::tsim::Delta::delta(), getVar(), l(), makeVarName(), otawa::tsim::Delta::processBBPath(), otawa::tsim::Delta::processCFG(), and sub().
String otawa::tsim::BBPath::makeVarName ()
Creates a human-readable name (or representation) for this sequence
This name is like Seq_x1_x2_x3 if the basic blocks have names x1, x2 and x3.
Returns
string containing the sequence name
References basicBlocks, length(), otawa::ilp::Var::name(), and otawa::ipet::VAR.
Referenced by getVar().
Vector< BBPath * > * otawa::tsim::BBPath::nexts ()
Builds a vector containing this BBSequence made longer with all successors of the last basic block it holds.
Searches in the Delta Processor if these sequences already exists
Returns
vector of the new BBSequences
References basicBlocks, otawa::cfgio::bb(), otawa::cfgio::edge(), getBBPath(), and l().
Referenced by otawa::tsim::Delta::processBBPath(), and otawa::tsim::Delta::processCFG().
BBPath * otawa::tsim::BBPath::operator() (int begin, int end) inline
References sub().
void otawa::PropList::print (elm::io::Output & out) const inherited
Display the current property list.
Parameters
out Output to use.
Referenced by otawa::Edge::kindName(), otawa::operator<<(), and otawa::ContextualProperty::print().
void otawa::PropList::removeAllProp (const AbstractIdentifier * id) inherited
Remove all the properties matching the given identifier.
Parameters
id Identifier of properties to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::LoopUnroller::unroll().
void otawa::PropList::removeProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier.
Parameters
id Identifier of the property to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::PSTBuilder::buildTree(), otawa::BBRemover< T >::clean(), otawa::CFGBuilder::cleanup(), otawa::display::CFGOutput::processCFG(), otawa::SubCFGBuilder::processWorkSpace(), otawa::Identifier< otawa::arm::Info * >::remove(), and otawa::ContextualPath::Ref< T >::remove().
void otawa::PropList::removeProp (const AbstractIdentifier & id) inline inherited
References otawa::PropList::removeProp().
Referenced by otawa::PropList::removeProp().
void otawa::PropList::setProp (Property * prop) inherited
Set the property in the property list removing any double.
Parameters
prop Property to set.
References otawa::Property::_next, otawa::Property::id(), and otawa::Property::next().
void otawa::PropList::setProp (const AbstractIdentifier * id) inline inherited
References otawa::PropList::setProp().
Referenced by otawa::PropList::setProp().
int otawa::tsim::BBPath::simulate (WorkSpace * fw) protected
Launches a simulation of the sequence.
If the simulator supports state cloning, it uses the saved state of the sub-sequences in order to simulate less instructions.
Returns
number of cycles to cover the sequence
References countInstructions(), otawa::sim::State::cycle(), otawa::sim::State::flush(), otawa::sim::Simulator::instantiate(), instructions_simulated, otawa::WorkSpace::process(), otawa::sim::State::reset(), otawa::sim::State::run(), otawa::Process::simulator(), and otawa::sim::USE_MEMORY.
Referenced by time().
BBPath * otawa::tsim::BBPath::sub (int begin, int end)
Returns a sub-path.
Searches if this path already exists
Parameters
begin index of the first basic block (first = 1)
end index of the last basic block (last = length())
Returns
sub-path of current path, from begin to end indexes
References basicBlocks, otawa::p::end, getBBPath(), and length().
Referenced by operator()().
int otawa::tsim::BBPath::t (WorkSpace * fw) inline
tests if two BBSequences are the same or not (same basic blocks in the path)
Parameters
bbs BBSequence to compare
Returns
boolean : true if both sequences are the same
Same as BBPath::time()
Returns the number of cycles the processor must do to cover the path. Simulates the path if necessary
Returns
number of cycles
References time().
Referenced by otawa::tsim::Delta::delta().
BasicBlock * otawa::tsim::BBPath::tail () inline
References basicBlocks.
Referenced by otawa::tsim::Delta::processBBPath(), and otawa::tsim::Delta::processCFG().
int otawa::tsim::BBPath::time (WorkSpace * fw)
Returns the number of cycles the processor must do to cover the sequence.
Simulates the sequence if necessary
Returns
number of cycles
References simulate(), and otawa::ipet::TIME.
Referenced by otawa::tsim::Delta::delta(), otawa::tsim::Delta::processBBPath(), and t().
Friends And Related Function Documentation
friend class PathManager friend
Member Data Documentation
int otawa::tsim::BBPath::_length protected
Referenced by countInstructions(), and length().
elm::genstruct::Vector<BasicBlock*> otawa::tsim::BBPath::basicBlocks protected
Referenced by BBPath(), countInstructions(), getVar(), head(), makeVarName(), nexts(), sub(), and tail().
const PropList otawa::PropList::EMPTY static inherited
This is an empty proplist for convenience.
Referenced by otawa::DynProcessor::configure(), otawa::ActualFeature::processor(), otawa::SilentFeature::SilentFeature(), otawa::Processor::version(), and otawa::display::Driver::~Driver().
int otawa::tsim::BBPath::instructions_simulated = 0 static
Referenced by simulate().
WorkSpace* otawa::tsim::BBPath::last_framework_used protected
The documentation for this class was generated from the following files:
include/otawa/tsim/BBPath.h
src/prog/BBPath.cpp