Otawa: otawa::ast::FunAST Class Reference
otawa::ast::FunAST Class Reference
AST Plugin
This class represents functions in the AST representation.
#include <otawa/ast/FunAST.h>
Public Member Functions
FunAST (WorkSpace *ws, Inst *entry, String name="")
Build a new function AST.
FunAST (ASTInfo *info, Inst *entry, String name="")
Build a new function AST.
Inst * entry (void) const
Get the instruction entry of this function.
String & name (void)
Get the name of the function.
AST * ast (void) const
Get the AST representing the body of this function.
void setAst (AST *ast)
Modify the AST representing the body of this function.
void setName (const String &name)
Private Member Functions
~FunAST (void)
Remove any link with the instruction representation.
Private Attributes
ASTInfo * info
Inst * ent
String _name
AST * _ast
Friends
class ASTInfo
Detailed Description
This class represents functions in the AST representation.
It provides the root of the AST.
Constructor & Destructor Documentation
FunAST::~FunAST (void) private
Remove any link with the instruction representation.
Referenced by FunAST().
FunAST::FunAST (WorkSpace * ws, Inst * entry, String name = "")
Build a new function AST.
Parameters
ws workspace containing the function.
entry First instruction of the function.
name Function name.
References _name, otawa::ast::ASTInfo::add(), ASTInfo, ent, otawa::ast::FUN, otawa::ast::INFO, info, and otawa::LABEL.
FunAST::FunAST (ASTInfo * info, Inst * entry, String name = "")
Build a new function AST.
Parameters
info AST information.
entry First instruction of the function.
name Function name.
References _ast, _name, otawa::ast::ASTInfo::add(), ast(), ent, otawa::ast::FUN, otawa::LABEL, otawa::ast::AST::release(), setAst(), and ~FunAST().
Member Function Documentation
AST * FunAST::ast (void) const inline
Get the AST representing the body of this function.
Returns
Body AST.
References _ast, and setAst().
Referenced by FunAST(), and otawa::ast::ASTProcessor::processFun().
Inst * FunAST::entry (void) const inline
Get the instruction entry of this function.
Returns
Entry instruction.
References ent.
const String & FunAST::name (void) inline
Get the name of the function.
Returns
Function name.
References _name.
Referenced by otawa::ast::ASTInfo::add(), otawa::ets::ACSComputation::applyProcess(), otawa::ets::CacheFirstMissComputation::computation(), otawa::ets::CacheHitComputation::computation(), otawa::ets::CacheMissComputation::computation(), otawa::ets::WCETComputation::computation(), otawa::ets::ACSComputation::initialization(), otawa::ets::FlowFactLoader::processAST(), otawa::ets::TrivialAstBlockTime::processAST(), and setName().
void FunAST::setAst (AST * ast)
Modify the AST representing the body of this function.
Parameters
ast New body AST.
Referenced by ast(), and FunAST().
void otawa::ast::FunAST::setName (const String & name) inline
References name().
Friends And Related Function Documentation
friend class ASTInfo friend
Referenced by FunAST().
Member Data Documentation
AST* otawa::ast::FunAST::_ast private
Referenced by ast(), and FunAST().
String otawa::ast::FunAST::_name private
Referenced by FunAST(), and name().
Inst* otawa::ast::FunAST::ent private
Referenced by entry(), and FunAST().
ASTInfo* otawa::ast::FunAST::info private
Referenced by FunAST().
The documentation for this class was generated from the following files:
include/otawa/ast/FunAST.h
src/prog/FunAST.cpp