Otawa: otawa::clp::ClpStatePack::InstPack Class Reference
otawa::clp::ClpStatePack::InstPack Class Reference
A pack of CLP states inside a machine instruction.
#include <otawa/data/clp/ClpPack.h>
Public Member Functions
InstPack ()
Constructor for a new instruction pack.
InstPack (address_t inst)
Constructor for a new instruction pack.
~InstPack (void)
Destructor.
address_t inst_addr (void)
StateIterator getIterator (void)
clp::State & outputState (void)
bool isEmpty (void)
void append (clp::State &state)
Add a new state at the end of this pack.
Private Attributes
address_t _inst_addr
Vector< clp::State * > _states
Friends
class ClpStatePack
class ClpProblem
Detailed Description
A pack of CLP states inside a machine instruction.
Each state of this pack is the state after a semantic instruction, in the order of the semantic instructions.
Constructor & Destructor Documentation
otawa::clp::ClpStatePack::InstPack::InstPack () inline
Constructor for a new instruction pack.
otawa::clp::ClpStatePack::InstPack::InstPack (address_t inst) inline
Constructor for a new instruction pack.
Parameters
inst the address of the instruction of this pack
References ~InstPack().
otawa::clp::ClpStatePack::InstPack::~InstPack (void)
Destructor.
Destructor for InstPack.
Referenced by InstPack().
Member Function Documentation
void otawa::clp::ClpStatePack::InstPack::append (clp::State & state)
Add a new state at the end of this pack.
Parameters
state the state to be added.
Referenced by isEmpty(), and otawa::clp::operator<<().
StateIterator otawa::clp::ClpStatePack::InstPack::getIterator (void) inline
Returns
an iterator over the states of this Pack.
References _states.
address_t otawa::clp::ClpStatePack::InstPack::inst_addr (void) inline
Returns
the address of the instruction of this Pack
References _inst_addr.
Referenced by otawa::clp::ClpStatePack::state_after(), and otawa::clp::ClpStatePack::state_before().
bool otawa::clp::ClpStatePack::InstPack::isEmpty (void) inline
Returns
if the InstPack is empty
References _states, and append().
Referenced by otawa::clp::ClpStatePack::state_before().
clp::State& otawa::clp::ClpStatePack::InstPack::outputState (void) inline
Returns
the last output state of this pack (i.e. the output state of the machine instruction of this pack).
References _states.
Referenced by otawa::clp::ClpStatePack::state_after(), and otawa::clp::ClpStatePack::state_before().
Friends And Related Function Documentation
friend class ClpProblem friend
friend class ClpStatePack friend
Member Data Documentation
address_t otawa::clp::ClpStatePack::InstPack::_inst_addr private
Referenced by inst_addr().
Vector<clp::State*> otawa::clp::ClpStatePack::InstPack::_states private
Referenced by getIterator(), isEmpty(), outputState(), otawa::clp::ClpStatePack::state_after(), and otawa::clp::ClpStatePack::state_before().
The documentation for this class was generated from the following files:
include/otawa/data/clp/ClpPack.h
src/prog/clp_analysis.cpp