Otawa: otawa::ProgItem Class Reference
otawa::ProgItem Class Reference abstract
Program Representation
Base class of the components of a program file segment.
#include <otawa/prog/ProgItem.h>
Public Member Functions
ProgItem * next (void) const
Get the next program item.
ProgItem * previous (void) const
Get the previous program item.
virtual address_t address (void) const =0
Get the address of the item .
virtual t::uint32 size (void) const =0
Get the size of the item in bytes.
address_t topAddress (void) const
Compute the address of the item immediately following the current item.
virtual Inst * toInst (void)
Return the instruction matching the current item.
Property * getProp (const AbstractIdentifier *id) const
Find a property by its identifier.
void setProp (Property *prop)
Set the property in the property list removing any double.
void setProp (const AbstractIdentifier *id)
void removeProp (const AbstractIdentifier *id)
Remove a property matching the given identifier.
void removeProp (const AbstractIdentifier &id)
Property * extractProp (const AbstractIdentifier *id)
Remove a property matching the given identifier and return it.
Property * extractProp (const AbstractIdentifier &id)
Remove a property matching the given identifier and return it.
void addProp (Property *prop)
Add property to the list without checking of duplication.
void removeAllProp (const AbstractIdentifier *id)
Remove all the properties matching the given identifier.
bool hasProp (const AbstractIdentifier &id) const
Test if the property list contains a property matching the given identifier.
void clearProps (void)
Remove all properties from the list.
void addProps (const PropList &props)
Add all properties from the given property list, in a reverse order.
void print (elm::io::Output &out) const
Display the current property list.
Static Public Attributes
static const PropList EMPTY
This is an empty proplist for convenience.
Protected Member Functions
virtual ~ProgItem (void)
Protected destructor for avoiding implementation unexpected deletion.
void insertPseudo (ProgItem *pos)
Friends
class Segment
Detailed Description
Base class of the components of a program file segment.
Constructor & Destructor Documentation
otawa::ProgItem::~ProgItem (void) protected virtual
Protected destructor for avoiding implementation unexpected deletion.
Member Function Documentation
void otawa::PropList::addProp (Property * prop) inherited
Add property to the list without checking of duplication.
Parameters
prop Property to add.
References otawa::Property::_next.
Referenced by otawa::Identifier< T >::add(), otawa::ast::ASTInfo::ASTInfo(), otawa::Identifier< otawa::arm::Info * >::copy(), otawa::AbstractIdentifier::initProps(), otawa::ContextualProperty::make(), otawa::script::Script::makeConfig(), otawa::ccg::Builder::processLBlockSet(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), and otawa::ContextualProperty::refProps().
void otawa::PropList::addProps (const PropList & props) inherited
Add all properties from the given property list, in a reverse order.
Parameters
props Property list to clone.
References otawa::Property::copy(), otawa::PropList::head, and otawa::Property::next().
Referenced by otawa::display::CFGDrawer::CFGDrawer(), otawa::display::GraphVizGraph::GraphVizGraph(), otawa::ParamFeature::instantiate(), otawa::Manager::loadXML(), otawa::display::GraphVizGraph::newEdge(), otawa::display::GraphVizGraph::newNode(), otawa::Process::Process(), otawa::display::GraphVizItem::setProps(), otawa::VirtualBasicBlock::VirtualBasicBlock(), and otawa::VirtualCFG::VirtualCFG().
address_t otawa::ProgItem::address (void) const pure virtual
Get the address of the item .
Returns
Address of the item or address 0 if none is assigned.
Note
In workstation systems, it is commonly accepted that the address 0 is ever invalid because it is the usual value of NULL in C. It should also work the same for embedded systems.
Implemented in otawa::loader::new_gliss::Inst, and otawa::loader::old_gliss::Inst.
Referenced by otawa::ParExeGraph::addEdgesForFetch(), otawa::PFGBuilder::addFunction(), otawa::ccg::LBlockBuilder::addLBlock(), otawa::LBlockBuilder::addLBlock(), otawa::LBlock::address(), otawa::BasicBlock::address(), otawa::ets::ACSComputation::applyProcess(), otawa::CFGBuilder::buildCFG(), otawa::ets::WCETComputation::computation(), otawa::ast::BlockAST::countInstructions(), otawa::LBlock::countInsts(), otawa::ccg::LBlock::countInsts(), otawa::ipet::FlowFactLoader::enteringCall(), otawa::Virtualizer::enteringCall(), otawa::FlowFactLoader::findCall(), otawa::CFGInfo::findCFG(), otawa::Segment::findItemAt(), otawa::WorkSpace::format(), otawa::se::getFilterForAddr(), otawa::se::getFilterForReg(), otawa::VarTextDecoder::getInst(), otawa::ets::ACSComputation::initialization(), otawa::Segment::insert(), otawa::ipet::FlowFactLoader::lookLineAt(), makeAddress(), otawa::ast::ASTLoader::makeBlock(), otawa::se::FilterBuilder::makeFilters(), otawa::DelayedBuilder::makeNOp(), otawa::Inst::multiCount(), otawa::LBlockManager::next(), otawa::DelayedBuilder::next(), otawa::FlowFactLoader::onLoop(), otawa::stack::operator<<(), otawa::clp::operator<<(), otawa::AccessedAddress::print(), otawa::ets::FlowFactLoader::processAST(), otawa::CFGChecker::processBB(), otawa::branch::CondNumber::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::ccg::LBlockBuilder::processBB(), otawa::LBlockBuilder::processBB(), otawa::dcache::CLPBlockBuilder::processBB(), otawa::etime::StandardEventBuilder::processBB(), otawa::dcache::BlockBuilder::processBB(), otawa::BBStatCollector::processCFG(), otawa::VarTextDecoder::processEntry(), otawa::VarTextDecoder::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), otawa::CFGBuilder::processWorkSpace(), otawa::FlowFactLoader::scanIgnoreControl(), otawa::FlowFactLoader::scanIgnoreSeq(), otawa::FlowFactLoader::scanMultiBranch(), otawa::FlowFactLoader::scanMultiCall(), otawa::FlowFactLoader::scanNoInline(), otawa::FlowFactLoader::scanSetInlining(), otawa::DelayedBuilder::size(), otawa::CFGProcessor::str(), topAddress(), and otawa::BranchProblem::update().
void otawa::PropList::clearProps (void) inherited
Remove all properties from the list.
References otawa::Property::next().
Referenced by otawa::PSTBuilder::getVCFG(), otawa::display::GraphVizItem::setProps(), and otawa::WorkSpace::~WorkSpace().
Property * otawa::PropList::extractProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::script::Script::makeConfig().
Property * otawa::PropList::extractProp (const AbstractIdentifier & id) inline inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::PropList::extractProp().
Referenced by otawa::PropList::extractProp().
Property * otawa::PropList::getProp (const AbstractIdentifier * id) const inherited
Find a property by its identifier.
Parameters
id Identifier of the property to find.
Returns
Found property or null.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::Identifier< otawa::arm::Info * >::exists(), otawa::ContextualProperty::exists(), otawa::ContextualProperty::find(), otawa::Identifier< T >::get(), otawa::ContextualProperty::make(), otawa::ParamFeature::matches(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::print(), otawa::ContextualProperty::print(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), otawa::ContextualProperty::refProps(), otawa::Identifier< T >::set(), otawa::Identifier< T >::use(), and otawa::Identifier< T >::value().
bool otawa::PropList::hasProp (const AbstractIdentifier & id) const inline inherited
Test if the property list contains a property matching the given identifier.
Parameters
id Property identifier to look for.
Returns
True if the list contains the matching property, false else.
References otawa::p::print().
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::Monitor::configure(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::exists(), and otawa::Manager::setVerbosity().
void otawa::ProgItem::insertPseudo (ProgItem * pos) inline protected
ProgItem * otawa::ProgItem::next (void) const
Get the next program item.
Returns
Next program item, null at the end of the list.
Referenced by otawa::Segment::findItemAt(), otawa::Segment::insert(), and otawa::Segment::ItemIter::next().
ProgItem * otawa::ProgItem::previous (void) const
Get the previous program item.
Returns
Previous program item, null at the begin of the list.
Referenced by otawa::Segment::insert().
void otawa::PropList::print (elm::io::Output & out) const inherited
Display the current property list.
Parameters
out Output to use.
Referenced by otawa::Edge::kindName(), otawa::operator<<(), and otawa::ContextualProperty::print().
void otawa::PropList::removeAllProp (const AbstractIdentifier * id) inherited
Remove all the properties matching the given identifier.
Parameters
id Identifier of properties to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::LoopUnroller::unroll().
void otawa::PropList::removeProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier.
Parameters
id Identifier of the property to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::PSTBuilder::buildTree(), otawa::BBRemover< T >::clean(), otawa::CFGBuilder::cleanup(), otawa::display::CFGOutput::processCFG(), otawa::SubCFGBuilder::processWorkSpace(), otawa::Identifier< otawa::arm::Info * >::remove(), and otawa::ContextualPath::Ref< T >::remove().
void otawa::PropList::removeProp (const AbstractIdentifier & id) inline inherited
References otawa::PropList::removeProp().
Referenced by otawa::PropList::removeProp().
void otawa::PropList::setProp (Property * prop) inherited
Set the property in the property list removing any double.
Parameters
prop Property to set.
References otawa::Property::_next, otawa::Property::id(), and otawa::Property::next().
void otawa::PropList::setProp (const AbstractIdentifier * id) inline inherited
References otawa::PropList::setProp().
Referenced by otawa::PropList::setProp().
size_t otawa::ProgItem::size (void) const pure virtual
Get the size of the item in bytes.
Returns
Size of the item.
Referenced by otawa::Segment::insert(), otawa::DelayedBuilder::makeNOp(), otawa::Inst::multiCount(), otawa::DelayedBuilder::size(), and topAddress().
Inst * otawa::ProgItem::toInst (void) virtual
Return the instruction matching the current item.
Returns
Matching instruction or null if the current program item is not an instruction.
Reimplemented in otawa::Inst.
Referenced by otawa::Segment::findInstAt(), otawa::Inst::nextInst(), otawa::Inst::prevInst(), otawa::TextDecoder::processWorkSpace(), and topAddress().
address_t otawa::ProgItem::topAddress (void) const inline
Compute the address of the item immediately following the current item.
Returns
Top address of the item.
References address(), size(), and toInst().
Referenced by otawa::ParExeGraph::addEdgesForFetch(), otawa::FlowFactLoader::findCall(), otawa::VarTextDecoder::getInst(), otawa::Segment::insert(), makeAddress(), otawa::DelayedBuilder::next(), otawa::FlowFactLoader::scanIgnoreControl(), otawa::FlowFactLoader::scanIgnoreSeq(), otawa::FlowFactLoader::scanMultiBranch(), otawa::FlowFactLoader::scanMultiCall(), otawa::FlowFactLoader::scanNoInline(), otawa::FlowFactLoader::scanSetInlining(), and otawa::DelayedBuilder::size().
Friends And Related Function Documentation
friend class Segment friend
Member Data Documentation
const PropList otawa::PropList::EMPTY static inherited
This is an empty proplist for convenience.
Referenced by otawa::DynProcessor::configure(), otawa::ActualFeature::processor(), otawa::SilentFeature::SilentFeature(), otawa::Processor::version(), and otawa::display::Driver::~Driver().
The documentation for this class was generated from the following files:
include/otawa/prog/ProgItem.h
src/prog/prog_ProgItem.cpp