Otawa: otawa::BackwardCFGAdapter Class Reference
otawa::BackwardCFGAdapter Class Reference
Adapter of CFG to the concept of otawa::concept::DiGraphWithIndexedVertex but with backward traversal of edges.
#include <otawa/cfg/CFGAdapter.h>
Classes
class Iterator
class Predecessor
class Successor
Public Types
typedef BasicBlock * Vertex
typedef otawa::Edge * Edge
Public Member Functions
BackwardCFGAdapter (CFG *_cfg)
int count (void) const
Vertex entry (void) const
int index (Vertex v) const
Vertex sourceOf (Edge edge) const
Vertex sinkOf (Edge edge) const
int outDegree (Vertex vertex) const
bool isSuccessorOf (Vertex succ, const Vertex &ref)
int inDegree (Vertex vertex) const
bool isPredecessorOf (const Vertex &pred, const Vertex &ref)
bool isLoopHeader (Vertex v) const
Private Attributes
CFG * cfg
Detailed Description
Adapter of CFG to the concept of otawa::concept::DiGraphWithIndexedVertex but with backward traversal of edges.
Member Typedef Documentation
typedef otawa::Edge* otawa::BackwardCFGAdapter::Edge
typedef BasicBlock* otawa::BackwardCFGAdapter::Vertex
Constructor & Destructor Documentation
otawa::BackwardCFGAdapter::BackwardCFGAdapter (CFG * _cfg) inline
Member Function Documentation
int otawa::BackwardCFGAdapter::count (void) const inline
References otawa::ForwardCFGAdapter::cfg, and otawa::CFG::countBB().
Vertex otawa::BackwardCFGAdapter::entry (void) const inline
References otawa::ForwardCFGAdapter::cfg, and otawa::CFG::exit().
int otawa::BackwardCFGAdapter::inDegree (Vertex vertex) const inline
int otawa::BackwardCFGAdapter::index (Vertex v) const inline
References otawa::BasicBlock::number().
bool otawa::BackwardCFGAdapter::isLoopHeader (Vertex v) const inline
References otawa::LOOP_HEADER.
bool otawa::BackwardCFGAdapter::isPredecessorOf (const Vertex & pred, const Vertex & ref) inline
References otawa::ForwardCFGAdapter::sourceOf().
bool otawa::BackwardCFGAdapter::isSuccessorOf (Vertex succ, const Vertex & ref) inline
References otawa::ForwardCFGAdapter::sinkOf().
int otawa::BackwardCFGAdapter::outDegree (Vertex vertex) const inline
Vertex otawa::BackwardCFGAdapter::sinkOf (Edge edge) const inline
References otawa::Edge::source().
Vertex otawa::BackwardCFGAdapter::sourceOf (Edge edge) const inline
References otawa::Edge::target().
Member Data Documentation
CFG* otawa::BackwardCFGAdapter::cfg private
The documentation for this class was generated from the following file:
include/otawa/cfg/CFGAdapter.h