Otawa: otawa::sem::BBIter Class Reference
otawa::sem::BBIter Class Reference
This class is an iterator on the semantic instruction paths of a basic block.
#include <otawa/sem/BBIter.h>
Public Member Functions
void start (BasicBlock *bb)
Start the traversal of a different basic block.
bool pathEnd (void) const
Test if the iteration point is at the end of an semantic execution path.
bool isCond (void) const
Test if the current instruction is a condition, that is a fork between two semantic execution paths.
bool instEnd (void) const
Test if the iterator is at the end of a machine instruction.
bool ended (void) const
Test if the iterator has ended the block.
sem::inst item (void) const
Get the current semantic instruction.
Inst * instruction (void) const
Get the current machine instruction.
void next (void)
Go to next semantic instruction (including changing instruction or changing execution path).
void nextInst (void)
Go to the start of the next instruction, performing the remaining execution paths of the current instruction.
void toEnd (void)
Go to the end of the basic block.
Private Attributes
sem::Block b
sem::PathIter si
BasicBlock::InstIter i
Detailed Description
This class is an iterator on the semantic instruction paths of a basic block.
Basically, a machine instruction is made of semantic instructions that may exhibit several executions paths (but no loop). This iterator enumerates all instructions of a basic block and for each instruction, all semantic paths of each instruction. As this iterator is relatively expansive, it should be allocated once and restarted for each basic block using start() method.
Several accessors allow to get the current execution point:
item() gets the current semantic instruction,
instruction() gets the current machine instruction.
This class provides also several end methods for:
ended() for the end of the basic block,
instEnd() for the end of a particular instruction (all semantic paths),
pathEnd() for the end of a particular semantic execution path.
Member Function Documentation
bool otawa::sem::BBIter::ended (void) const inline
Test if the iterator has ended the block.
Returns
True if at end of the block, false else.
References otawa::sem::PathIter::ended(), otawa::BasicBlock::InstIter::ended(), i, and si.
Referenced by otawa::sem::StateIter< Manager >::ended(), otawa::sem::StateIter< Manager >::next(), and otawa::sem::StateIter< Manager >::toEnd().
bool otawa::sem::BBIter::instEnd (void) const inline
Test if the iterator is at the end of a machine instruction.
Returns
True if at end of machine instruction, false else.
References otawa::sem::PathIter::ended(), and si.
Referenced by otawa::sem::StateIter< Manager >::nextInst().
Inst * otawa::sem::BBIter::instruction (void) const inline
Get the current machine instruction.
Returns
Current machine instruction.
References i, next(), nextInst(), and toEnd().
Referenced by otawa::sem::StateIter< Manager >::instruction().
bool otawa::sem::BBIter::isCond (void) const inline
Test if the current instruction is a condition, that is a fork between two semantic execution paths.
Returns
True if the current instruction is a condition, false else.
References otawa::sem::PathIter::isCond(), and si.
Referenced by otawa::sem::StateIter< Manager >::next().
inst otawa::sem::BBIter::item (void) const inline
Get the current semantic instruction.
Returns
Current semantic instruction.
References otawa::sem::PathIter::item(), and si.
void otawa::sem::BBIter::next (void)
Go to next semantic instruction (including changing instruction or changing execution path).
Referenced by instruction(), and otawa::sem::StateIter< Manager >::next().
void otawa::sem::BBIter::nextInst (void)
Go to the start of the next instruction, performing the remaining execution paths of the current instruction.
Referenced by instruction().
bool otawa::sem::BBIter::pathEnd (void) const inline
Test if the iteration point is at the end of an semantic execution path.
Returns
True if it is the end of a semantic instruction path, false else.
References otawa::sem::PathIter::pathEnd(), and si.
Referenced by otawa::sem::StateIter< Manager >::next().
void otawa::sem::BBIter::start (BasicBlock * bb)
Start the traversal of a different basic block.
Parameters
bb Basic block to start with.
Referenced by otawa::sem::StateIter< Manager >::start().
void otawa::sem::BBIter::toEnd (void)
Go to the end of the basic block.
Referenced by instruction().
Member Data Documentation
sem::Block otawa::sem::BBIter::b private
BasicBlock::InstIter otawa::sem::BBIter::i private
Referenced by ended(), and instruction().
sem::PathIter otawa::sem::BBIter::si private
Referenced by ended(), instEnd(), isCond(), item(), and pathEnd().
The documentation for this class was generated from the following files:
include/otawa/sem/BBIter.h
src/prog/sem.cpp