Otawa: otawa::dfa::Predecessor Class Reference
otawa::dfa::Predecessor Class Reference
Data Flow Analysis
This iterator is used to traverse forward a CFG in an iterative DFA analysis.
#include <otawa/dfa/IterativeDFA.h>
Public Types
typedef Successor Forward
Public Member Functions
Predecessor (BasicBlock *bb)
BasicBlock * item (void) const
bool ended (void) const
void next (void)
Static Public Member Functions
static BasicBlock * entry (CFG &cfg)
Private Member Functions
void look (void)
Private Attributes
BasicBlock::InIterator iter
Detailed Description
This iterator is used to traverse forward a CFG in an iterative DFA analysis.
Member Typedef Documentation
typedef Successor otawa::dfa::Predecessor::Forward
Constructor & Destructor Documentation
otawa::dfa::Predecessor::Predecessor (BasicBlock * bb) inline
References look().
Member Function Documentation
bool otawa::dfa::Predecessor::ended (void) const inline
static BasicBlock* otawa::dfa::Predecessor::entry (CFG & cfg) inline static
References otawa::CFG::entry().
BasicBlock* otawa::dfa::Predecessor::item (void) const inline
void otawa::dfa::Predecessor::look (void) inline private
References otawa::Edge::CALL.
Referenced by next(), otawa::dfa::Successor::next(), Predecessor(), and otawa::dfa::Successor::Successor().
void otawa::dfa::Predecessor::next (void) inline
References look().
Member Data Documentation
BasicBlock::InIterator otawa::dfa::Predecessor::iter private
The documentation for this class was generated from the following file:
include/otawa/dfa/IterativeDFA.h