Otawa: otawa::etime::Event Class Reference
otawa::etime::Event Class Reference abstract
Event Time Module
An event represents a time variation in the execution of an instruction.
#include <otawa/etime/features.h>
Public Member Functions
Event (Inst *inst)
Build an event.
virtual ~Event (void)
Inst * inst (void) const
Get the instruction this event applies to.
virtual kind_t kind (void) const =0
Get the kind of the event.
virtual ot::time cost (void) const =0
Get the cost in cycles of the occurrence of the event.
virtual type_t type (void) const =0
virtual occurrence_t occurrence (void) const
Get the occurrences class of this event.
virtual cstring name (void) const
Get the name of the event (for human user).
virtual string detail (void) const =0
virtual const hard::Stage * stage (void) const
For events applying to a particular processor stage, get this stage.
virtual const hard::FunctionalUnit * fu (void) const
For events applying to a particular processor functional unit, get this functional unit.
virtual int weight (void) const
Weight is a coarse-grain estimation of the number of times an event arises.
virtual bool isEstimating (bool on)
Ask for support of overestimation for the event when activated (on is true) or desactivated (on is false).
virtual void estimate (ilp::Constraint *cons, bool on)
Add an estimation of the event at the left of the given constraint.
Property * getProp (const AbstractIdentifier *id) const
Find a property by its identifier.
void setProp (Property *prop)
Set the property in the property list removing any double.
void setProp (const AbstractIdentifier *id)
void removeProp (const AbstractIdentifier *id)
Remove a property matching the given identifier.
void removeProp (const AbstractIdentifier &id)
Property * extractProp (const AbstractIdentifier *id)
Remove a property matching the given identifier and return it.
Property * extractProp (const AbstractIdentifier &id)
Remove a property matching the given identifier and return it.
void addProp (Property *prop)
Add property to the list without checking of duplication.
void removeAllProp (const AbstractIdentifier *id)
Remove all the properties matching the given identifier.
bool hasProp (const AbstractIdentifier &id) const
Test if the property list contains a property matching the given identifier.
void clearProps (void)
Remove all properties from the list.
void addProps (const PropList &props)
Add all properties from the given property list, in a reverse order.
void print (elm::io::Output &out) const
Display the current property list.
Static Public Attributes
static const PropList EMPTY
This is an empty proplist for convenience.
Private Attributes
Inst * _inst
Detailed Description
An event represents a time variation in the execution of an instruction.
Examples of events include instruction/data cache hit/miss, resolution of a branch prediction, hit/miss in the prefetch device of flash memory, etc.
Events are used to compute the execution time of code blocks and are usually linked to their matching block.
Constructor & Destructor Documentation
otawa::etime::Event::Event (Inst * inst)
Build an event.
Parameters
inst Instruction it applies to.
otawa::etime::Event::~Event (void) virtual
Member Function Documentation
void otawa::PropList::addProp (Property * prop) inherited
Add property to the list without checking of duplication.
Parameters
prop Property to add.
References otawa::Property::_next.
Referenced by otawa::Identifier< T >::add(), otawa::ast::ASTInfo::ASTInfo(), otawa::Identifier< otawa::arm::Info * >::copy(), otawa::AbstractIdentifier::initProps(), otawa::ContextualProperty::make(), otawa::script::Script::makeConfig(), otawa::ccg::Builder::processLBlockSet(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), and otawa::ContextualProperty::refProps().
void otawa::PropList::addProps (const PropList & props) inherited
Add all properties from the given property list, in a reverse order.
Parameters
props Property list to clone.
References otawa::Property::copy(), otawa::PropList::head, and otawa::Property::next().
Referenced by otawa::display::CFGDrawer::CFGDrawer(), otawa::display::GraphVizGraph::GraphVizGraph(), otawa::ParamFeature::instantiate(), otawa::Manager::loadXML(), otawa::display::GraphVizGraph::newEdge(), otawa::display::GraphVizGraph::newNode(), otawa::Process::Process(), otawa::display::GraphVizItem::setProps(), otawa::VirtualBasicBlock::VirtualBasicBlock(), and otawa::VirtualCFG::VirtualCFG().
void otawa::PropList::clearProps (void) inherited
Remove all properties from the list.
References otawa::Property::next().
Referenced by otawa::PSTBuilder::getVCFG(), otawa::display::GraphVizItem::setProps(), and otawa::WorkSpace::~WorkSpace().
ot::time otawa::etime::Event::cost (void) const pure virtual
Get the cost in cycles of the occurrence of the event.
Returns
Cost of the event (in cycles).
Referenced by otawa::etime::EdgeTimeBuilder::apply().
virtual string otawa::etime::Event::detail (void) const pure virtual
void otawa::etime::Event::estimate (ilp::Constraint * cons, bool on) virtual
Add an estimation of the event at the left of the given constraint.
If the event is considered on, it should an overestimation. If the event is considered off, it should be an underestimation.
May be overridden to provide specific behavior for the actual event. As a default, do nothing.
Parameters
cons Constraint to add overestimation to.
on Add overestimation when the event is triggered (true) or not triggered (false).
References OTAWA_PROC_VERSION.
Property * otawa::PropList::extractProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::script::Script::makeConfig().
Property * otawa::PropList::extractProp (const AbstractIdentifier & id) inline inherited
Remove a property matching the given identifier and return it.
Caller is responsible of the management of the obtained property.
Parameters
id Identifier of the property to extract.
References otawa::PropList::extractProp().
Referenced by otawa::PropList::extractProp().
const hard::FunctionalUnit * otawa::etime::Event::fu (void) const virtual
For events applying to a particular processor functional unit, get this functional unit.
Returns
Processor functional unit the event applies to.
Property * otawa::PropList::getProp (const AbstractIdentifier * id) const inherited
Find a property by its identifier.
Parameters
id Identifier of the property to find.
Returns
Found property or null.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::Identifier< otawa::arm::Info * >::exists(), otawa::ContextualProperty::exists(), otawa::ContextualProperty::find(), otawa::Identifier< T >::get(), otawa::ContextualProperty::make(), otawa::ParamFeature::matches(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::print(), otawa::ContextualProperty::print(), otawa::Identifier< T >::ref(), otawa::ContextualProperty::ref(), otawa::ContextualProperty::refProps(), otawa::Identifier< T >::set(), otawa::Identifier< T >::use(), and otawa::Identifier< T >::value().
bool otawa::PropList::hasProp (const AbstractIdentifier & id) const inline inherited
Test if the property list contains a property matching the given identifier.
Parameters
id Property identifier to look for.
Returns
True if the list contains the matching property, false else.
References otawa::p::print().
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::Monitor::configure(), otawa::ImmutableRef< T *, otawa::Identifier< T * > >::exists(), and otawa::Manager::setVerbosity().
Inst * otawa::etime::Event::inst (void) const inline
Get the instruction this event applies to.
Returns
Event instruction.
References kind, name, and otawa::type().
Referenced by otawa::etime::EdgeTimeBuilder::processSequence().
bool otawa::etime::Event::isEstimating (bool on) virtual
Ask for support of overestimation for the event when activated (on is true) or desactivated (on is false).
May be overridden according to the actual event. As a default, return false.
Parameters
on Test for event activated, or not activated.
Returns
True if the event provides support for the activation.
kind_t otawa::etime::Event::kind (void) const pure virtual
Get the kind of the event.
Returns
Event kind.
Referenced by otawa::etime::EdgeTimeBuilder::apply(), and otawa::etime::EdgeTimeBuilder::rollback().
cstring otawa::etime::Event::name (void) const virtual
Get the name of the event (for human user).
Returns
Event name.
occurrence_t otawa::etime::Event::occurrence (void) const virtual
Get the occurrences class of this event.
Returns
Event occurrence class.
References otawa::etime::SOMETIMES.
Referenced by otawa::etime::EdgeTimeBuilder::processSequence().
void otawa::PropList::print (elm::io::Output & out) const inherited
Display the current property list.
Parameters
out Output to use.
Referenced by otawa::Edge::kindName(), otawa::operator<<(), and otawa::ContextualProperty::print().
void otawa::PropList::removeAllProp (const AbstractIdentifier * id) inherited
Remove all the properties matching the given identifier.
Parameters
id Identifier of properties to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::LoopUnroller::unroll().
void otawa::PropList::removeProp (const AbstractIdentifier * id) inherited
Remove a property matching the given identifier.
Parameters
id Identifier of the property to remove.
References otawa::Property::_next, and otawa::Property::next().
Referenced by otawa::PSTBuilder::buildTree(), otawa::BBRemover< T >::clean(), otawa::CFGBuilder::cleanup(), otawa::display::CFGOutput::processCFG(), otawa::SubCFGBuilder::processWorkSpace(), otawa::Identifier< otawa::arm::Info * >::remove(), and otawa::ContextualPath::Ref< T >::remove().
void otawa::PropList::removeProp (const AbstractIdentifier & id) inline inherited
References otawa::PropList::removeProp().
Referenced by otawa::PropList::removeProp().
void otawa::PropList::setProp (Property * prop) inherited
Set the property in the property list removing any double.
Parameters
prop Property to set.
References otawa::Property::_next, otawa::Property::id(), and otawa::Property::next().
void otawa::PropList::setProp (const AbstractIdentifier * id) inline inherited
References otawa::PropList::setProp().
Referenced by otawa::PropList::setProp().
const hard::Stage * otawa::etime::Event::stage (void) const virtual
For events applying to a particular processor stage, get this stage.
Returns
Processor stage the event applies to.
virtual type_t otawa::etime::Event::type (void) const pure virtual
Referenced by otawa::etime::EdgeTimeBuilder::make().
int otawa::etime::Event::weight (void) const virtual
Weight is a coarse-grain estimation of the number of times an event arises.
As a default returns 1 but may be customized to get more precise weight estimation. This result will be used by heuristic approach to assess the impact of this event.
Returns
Weight of the event.
Member Data Documentation
Inst* otawa::etime::Event::_inst private
const PropList otawa::PropList::EMPTY static inherited
This is an empty proplist for convenience.
Referenced by otawa::DynProcessor::configure(), otawa::ActualFeature::processor(), otawa::SilentFeature::SilentFeature(), otawa::Processor::version(), and otawa::display::Driver::~Driver().
The documentation for this class was generated from the following files:
include/otawa/etime/features.h
src/etime/hook.cpp