Otawa: otawa::etime::ConfigSet Class Reference
otawa::etime::ConfigSet Class Reference
Set of configurations with the same or with a maximum of time.
#include <otawa/etime/Config.h>
Classes
class Iter
Public Member Functions
ConfigSet (void)
ConfigSet (ot::time time)
ConfigSet (const ConfigSet &set)
ot::time time (void) const
int count (void) const
void add (Config conf)
void add (const ConfigSet &set)
void push (const ConfigSet &set)
void pop (const ConfigSet &set)
t::uint32 posConst (void) const
TODO.
t::uint32 negConst (void) const
TODO.
t::uint32 unused (t::uint32 neg, t::uint32 pos, int n) const
TODO.
t::uint32 complex (t::uint32 neg, t::uint32 pos, t::uint32 unused, int n) const
TODO.
void scan (t::uint32 &pos, t::uint32 &neg, t::uint32 &unus, t::uint32 &comp, int n) const
TODO.
bool isFeasible (int n)
Test if the configuration set is feasible.
void dump (io::Output &out, int n)
TODO.
Private Attributes
ot::time t
genstruct::Vector< Config > confs
Detailed Description
Set of configurations with the same or with a maximum of time.
Constructor & Destructor Documentation
otawa::etime::ConfigSet::ConfigSet (void) inline
otawa::etime::ConfigSet::ConfigSet (ot::time time) inline
otawa::etime::ConfigSet::ConfigSet (const ConfigSet & set) inline
Member Function Documentation
void otawa::etime::ConfigSet::add (Config conf) inline
Referenced by otawa::etime::EdgeTimeBuilder::makeSplit().
void otawa::etime::ConfigSet::add (const ConfigSet & set) inline
References otawa::clp::max().
t::uint32 otawa::etime::ConfigSet::complex (t::uint32 neg, t::uint32 pos, t::uint32 unused, int n) const
TODO.
int otawa::etime::ConfigSet::count (void) const inline
void otawa::etime::ConfigSet::dump (io::Output & out, int n)
TODO.
bool otawa::etime::ConfigSet::isFeasible (int n)
Test if the configuration set is feasible.
References otawa::sem::neg().
t::uint32 otawa::etime::ConfigSet::negConst (void) const
TODO.
References otawa::etime::Config::bits().
void otawa::etime::ConfigSet::pop (const ConfigSet & set) inline
References otawa::sem::neg().
Referenced by otawa::etime::EdgeTimeBuilder::applyFloppySplit(), otawa::etime::EdgeTimeBuilder::applyStrictSplit(), otawa::etime::EdgeTimeBuilder::applyWeightedSplit(), and otawa::etime::EdgeTimeBuilder::splitConfs().
t::uint32 otawa::etime::ConfigSet::posConst (void) const
TODO.
References otawa::etime::Config::bits().
void otawa::etime::ConfigSet::push (const ConfigSet & set) inline
References otawa::clp::max().
void otawa::etime::ConfigSet::scan (t::uint32 & pos, t::uint32 & neg, t::uint32 & unus, t::uint32 & comp, int n) const
TODO.
Referenced by otawa::etime::EdgeTimeBuilder::applyFloppySplit(), otawa::etime::EdgeTimeBuilder::applyStrictSplit(), and otawa::etime::EdgeTimeBuilder::applyWeightedSplit().
ot::time otawa::etime::ConfigSet::time (void) const inline
t::uint32 otawa::etime::ConfigSet::unused (t::uint32 neg, t::uint32 pos, int n) const
TODO.
Member Data Documentation
genstruct::Vector<Config> otawa::etime::ConfigSet::confs private
ot::time otawa::etime::ConfigSet::t private
The documentation for this class was generated from the following files:
include/otawa/etime/Config.h
src/etime/EdgeTimeBuilder.cpp