Otawa: otawa::ilp::System Class Reference
otawa::ilp::System Class Reference abstract
ILP -- Integer Linear Programming
An ILP system is a colletion of ILP constraint that may maximize or minimize some object function.
#include <otawa/ilp/System.h>
Classes
class ConstIterator
class ObjTermIterator
Public Member Functions
virtual ~System (void)
virtual Constraint * newConstraint (Constraint::comparator_t comp, double constant=0)=0
Build a new constraint that may be initialized by the user.
virtual Constraint * newConstraint (const string &label, Constraint::comparator_t comp, double constant=0)=0
virtual bool solve (WorkSpace *ws=0)=0
Solve the ILP system.
virtual void addObjectFunction (double coef, Var *var=0)=0
Add a factor to the object function.
virtual double valueOf (Var *var)=0
This method can only be called after the resolution of the system and returns the value of a variable.
virtual double value (void)=0
Return the value of the optimized object function.
virtual Var * newVar (const string &name="")=0
virtual int countVars (void)=0
Count the number of variables in the system.
virtual int countConstraints (void)=0
Count the number of constraints in the system.
virtual elm::datastruct::IteratorInst< ilp::Constraint * > * constraints (void)=0
virtual elm::datastruct::IteratorInst< ilp::Constraint::Term > * objTerms (void)=0
virtual void exportLP (io::Output &out=elm::cout)=0
Export the system to the given output using the LP format (lp_solve).
virtual void dumpSystem (io::Output &out=elm::cout)
Dump the system in text format (as a default, call exportLP).
virtual void dumpSolution (io::Output &out=elm::cout)=0
Dump the solution textually to the given output.
virtual void dump (elm::io::OutStream &out=elm::io::out)
Dump the system to the given output.
virtual bool solve (WorkSpace *ws, otawa::Monitor &mon)
Solve the ILP system in the given workspace using the given monitor to output logs.
virtual string lastErrorMessage (void)
Get the message of the last error.
virtual ILPPlugin * plugin (void)
Return the owner plugin.
virtual Var * newVar (Var::type_t type, const string &name="")=0
Build a new variable with the given type.
bool hasDump (format_t fmt)
Tests if it is possible to dump in the given format.
void dump (format_t fmt, elm::io::OutStream &out=elm::io::out)
Dump the system to the given output and format.
void dumpLPSolve (elm::io::OutStream &out=elm::io::out)
Dump in LPSolve format.
void dumpCPlex (elm::io::OutStream &out=elm::io::out)
Dump system in CPlex format.
void dumpMOSEK (elm::io::OutStream &out=elm::io::out)
Dump in MOSEK format.
Detailed Description
An ILP system is a colletion of ILP constraint that may maximize or minimize some object function.
Constructor & Destructor Documentation
virtual otawa::ilp::System::~System (void) inline virtual
References addObjectFunction(), constraints(), countConstraints(), countVars(), dump(), dumpCPlex(), dumpLPSolve(), dumpMOSEK(), dumpSolution(), dumpSystem(), exportLP(), hasDump(), lastErrorMessage(), name, newConstraint(), newVar(), objTerms(), plugin(), solve(), otawa::type(), value(), and valueOf().
Member Function Documentation
void otawa::ilp::System::addObjectFunction (double coef, Var * var = 0) pure virtual
Add a factor to the object function.
Parameters
coef Coefficient of the factor.
var Variable of the factor.
Implemented in otawa::ilp::AbstractSystem.
Referenced by otawa::etime::EdgeTimeBuilder::contributeSplit(), otawa::etime::EdgeTimeBuilder::genForOneCost(), otawa::ipet::CachePenaltiesObjectFunctionBuilder::processBB(), otawa::ipet::BasicObjectFunctionBuilder::processBB(), otawa::tsim::TimeDeltaObjectFunctionModifier::processBB(), otawa::dcache::WCETFunctionBuilder::processBB(), otawa::branch::ConsBuilder::processBB(), otawa::tsim::Delta::processBBPath(), otawa::cat::CATConstraintBuilder::processLBlockSet(), otawa::ccg::ConstraintBuilder::processLBlockSet(), otawa::EdgeCAT2ConstraintBuilder::processWorkSpace(), otawa::CAT2ConstraintBuilder::processWorkSpace(), and ~System().
virtual elm::datastruct::IteratorInst<ilp::Constraint*>* otawa::ilp::System::constraints (void) pure virtual
Implemented in otawa::ilp::AbstractSystem.
Referenced by ~System().
int otawa::ilp::System::countConstraints (void) pure virtual
Count the number of constraints in the system.
Returns
Constraint count.
Implemented in otawa::ilp::AbstractSystem.
Referenced by ~System().
int otawa::ilp::System::countVars (void) pure virtual
Count the number of variables in the system.
Returns
Variable count.
Implemented in otawa::ilp::AbstractSystem.
Referenced by ~System().
void otawa::ilp::System::dump (elm::io::OutStream & out = elm::io::out) virtual
Dump the system to the given output.
The dumping format depends upon the actual used ILP engine. Usually, it is compatible with other tools of the ILP engine.
Parameters
out Used output.
Deprecated:
Use dumpSystem() and dumpSolution() instead.
Referenced by otawa::ilp::AbstractSystem::exportLP(), otawa::ilp::Output::processWorkSpace(), and ~System().
void otawa::ilp::System::dump (format_t fmt, elm::io::OutStream & out = elm::io::out)
Dump the system to the given output and format.
Parameters
out Used output.
fmt Used format
References otawa::ilp::CPLEX, otawa::ilp::DEFAULT, otawa::ilp::LP_SOLVE, and otawa::ilp::MOSEK.
void otawa::ilp::System::dumpCPlex (elm::io::OutStream & out = elm::io::out)
Dump system in CPlex format.
Parameters
_out Output stream to use.
References otawa::ilp::Constraint::EQ, otawa::ilp::Constraint::GE, otawa::ilp::Constraint::GT, otawa::ilp::Constraint::LE, otawa::ilp::Constraint::LT, and otawa::sign().
Referenced by ~System().
void otawa::ilp::System::dumpLPSolve (elm::io::OutStream & out = elm::io::out)
Dump in LPSolve format.
Parameters
_out Output stream.
References otawa::ilp::Var::BIN, otawa::ilp::Constraint::comparator(), otawa::ilp::Constraint::constant(), otawa::ilp::Var::FLOAT, otawa::ilp::Var::INT, otawa::ilp::Constraint::label(), otawa::sem::neg(), and otawa::ilp::Constraint::terms().
Referenced by ~System().
void otawa::ilp::System::dumpMOSEK (elm::io::OutStream & out = elm::io::out)
Dump in MOSEK format.
Parameters
_out Output stream.
References otawa::ilp::Constraint::EQ, otawa::ilp::Constraint::GE, otawa::ilp::Constraint::GT, otawa::ilp::Constraint::LE, otawa::ilp::Constraint::LT, and otawa::sign().
Referenced by ~System().
void otawa::ilp::System::dumpSolution (io::Output & out = elm::cout) pure virtual
Dump the solution textually to the given output.
Parameters
out Stream to output to (default to cout).
Implemented in otawa::ilp::AbstractSystem.
Referenced by ~System().
void otawa::ilp::System::dumpSystem (io::Output & out = elm::cout) virtual
Dump the system in text format (as a default, call exportLP).
Parameters
out Stream to dump to (default to cout).
Referenced by ~System().
void otawa::ilp::System::exportLP (io::Output & out = elm::cout) pure virtual
Export the system to the given output using the LP format (lp_solve).
Parameters
out Stream to export to (default to cout).
Implemented in otawa::ilp::AbstractSystem.
Referenced by ~System().
bool otawa::ilp::System::hasDump (format_t fmt)
Tests if it is possible to dump in the given format.
Parameters
fmt Used format
Returns
Boolean
References otawa::ilp::CPLEX, otawa::ilp::DEFAULT, otawa::ilp::LP_SOLVE, and otawa::ilp::MOSEK.
Referenced by ~System().
string otawa::ilp::System::lastErrorMessage (void) virtual
Get the message of the last error.
Since
1.2.0 ILP interface.
Returns
Last error message.
Referenced by otawa::ipet::WCETComputation::processWorkSpace(), and ~System().
Constraint * otawa::ilp::System::newConstraint (Constraint::comparator_t comp, double constant = 0) pure virtual
Build a new constraint that may be initialized by the user.
As the ILP system manage the memory of the constraint, the constraint must never be deleted by the user.
Parameters
comp Comparator used (one of Constraint::LT, LE, EQ, GT, GE).
constant Constant value.
Returns
Built constraint.
Implemented in otawa::ilp::AbstractSystem.
Referenced by otawa::ipet::ConstraintLoader::addConstraint(), otawa::ccg::ConstraintBuilder::addConstraintHeader(), otawa::etime::EdgeTimeBuilder::contributeSplit(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::etime::EventCollector::make(), otawa::ipet::CachePenaltiesObjectFunctionBuilder::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::tsim::Delta::processBBPath(), otawa::cat::CATConstraintBuilder::processLBlockSet(), otawa::ccg::ConstraintBuilder::processLBlockSet(), otawa::EdgeCAT2ConstraintBuilder::processWorkSpace(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), and ~System().
virtual Constraint* otawa::ilp::System::newConstraint (const string & label, Constraint::comparator_t comp, double constant = 0) pure virtual
Implemented in otawa::ilp::AbstractSystem.
virtual Var* otawa::ilp::System::newVar (const string & name = "") pure virtual
Implemented in otawa::ilp::AbstractSystem.
Referenced by otawa::etime::EdgeTimeBuilder::contributeSplit(), otawa::tsim::BBPath::getVar(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::ipet::CachePenaltiesObjectFunctionBuilder::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::cat::CATConstraintBuilder::processLBlockSet(), otawa::ccg::ConstraintBuilder::processLBlockSet(), otawa::EdgeCAT2ConstraintBuilder::processWorkSpace(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), and ~System().
Var * otawa::ilp::System::newVar (Var::type_t type, const string & name = "") pure virtual
Build a new variable with the given type.
Parameters
type Type of the variable.
name Variable name.
Returns
Built variable.
Since
ILP 1.2.0
Implemented in otawa::ilp::AbstractSystem.
virtual elm::datastruct::IteratorInst<ilp::Constraint::Term>* otawa::ilp::System::objTerms (void) pure virtual
Implemented in otawa::ilp::AbstractSystem.
Referenced by ~System().
ILPPlugin * otawa::ilp::System::plugin (void) virtual
Return the owner plugin.
As a default, return null.
Returns
Owner plugin.
Referenced by otawa::ipet::WCETComputation::processWorkSpace(), and ~System().
boolean otawa::ilp::System::solve (WorkSpace * ws = 0) pure virtual
Solve the ILP system.
Parameters
ws If passed (default to null), the given workspace is used to test if the computation is cancelled in order to stop the solver.
Returns
True if the resolution is succesful or false else (mainly due to lack of constraint).
Referenced by otawa::ipet::WCETComputation::processWorkSpace(), and ~System().
bool otawa::ilp::System::solve (WorkSpace * ws, otawa::Monitor & mon) virtual
Solve the ILP system in the given workspace using the given monitor to output logs.
The workspace may be used to support cancellation or progression in user interface.
Parameters
ws Current workspace.
mon Monitor to use.
double otawa::ilp::System::value (void) pure virtual
Return the value of the optimized object function.
Returns
Object function optimum.
Referenced by otawa::ipet::WCETComputation::processWorkSpace(), and ~System().
double otawa::ilp::System::valueOf (Var * var) pure virtual
This method can only be called after the resolution of the system and returns the value of a variable.
It is an error to pass a variable not involved in the system.
Parameters
var Variable whose value is looked for.
Returns
Value of the variable.
Referenced by otawa::display::ILPSystemDisplayer::displayVar(), otawa::ilp::AbstractSystem::dumpSolution(), otawa::ilp::Var::eval(), otawa::ilp::Expression::eval(), otawa::ipet::WCETCountRecorder::processBB(), otawa::BBRatioDisplayer::processBB(), otawa::BBRatioDisplayer::processCFG(), otawa::display::ILPSystemDisplayer::processWorkSpace(), and ~System().
The documentation for this class was generated from the following files:
include/otawa/ilp/System.h
src/prog/ilp_System.cpp