Otawa: otawa::ForwardCFGAdapter Class Reference
otawa::ForwardCFGAdapter Class Reference
Adapter of CFG to the concept of otawa::concept::DiGraphWithIndexedVertex.
#include <otawa/cfg/CFGAdapter.h>
Classes
class Iterator
class Predecessor
class Successor
Public Types
typedef BasicBlock * Vertex
typedef otawa::Edge * Edge
Public Member Functions
ForwardCFGAdapter (CFG *_cfg)
int count (void) const
Vertex entry (void) const
int index (Vertex v) const
Vertex sourceOf (Edge edge) const
Vertex sinkOf (Edge edge) const
int outDegree (Vertex vertex) const
bool isSuccessorOf (Vertex succ, const Vertex &ref)
int inDegree (Vertex vertex) const
bool isPredecessorOf (Vertex pred, const Vertex &ref)
bool isLoopHeader (Vertex v) const
Private Attributes
CFG * cfg
Detailed Description
Adapter of CFG to the concept of otawa::concept::DiGraphWithIndexedVertex.
Member Typedef Documentation
typedef otawa::Edge* otawa::ForwardCFGAdapter::Edge
typedef BasicBlock* otawa::ForwardCFGAdapter::Vertex
Constructor & Destructor Documentation
otawa::ForwardCFGAdapter::ForwardCFGAdapter (CFG * _cfg) inline
Member Function Documentation
int otawa::ForwardCFGAdapter::count (void) const inline
References cfg, and otawa::CFG::countBB().
Vertex otawa::ForwardCFGAdapter::entry (void) const inline
References cfg, and otawa::CFG::entry().
int otawa::ForwardCFGAdapter::inDegree (Vertex vertex) const inline
int otawa::ForwardCFGAdapter::index (Vertex v) const inline
References otawa::BasicBlock::number().
bool otawa::ForwardCFGAdapter::isLoopHeader (Vertex v) const inline
References otawa::LOOP_HEADER.
bool otawa::ForwardCFGAdapter::isPredecessorOf (Vertex pred, const Vertex & ref) inline
References sourceOf().
bool otawa::ForwardCFGAdapter::isSuccessorOf (Vertex succ, const Vertex & ref) inline
References sinkOf().
int otawa::ForwardCFGAdapter::outDegree (Vertex vertex) const inline
Vertex otawa::ForwardCFGAdapter::sinkOf (Edge edge) const inline
References otawa::Edge::target().
Referenced by isSuccessorOf(), and otawa::BackwardCFGAdapter::isSuccessorOf().
Vertex otawa::ForwardCFGAdapter::sourceOf (Edge edge) const inline
References otawa::Edge::source().
Referenced by isPredecessorOf(), and otawa::BackwardCFGAdapter::isPredecessorOf().
Member Data Documentation
CFG* otawa::ForwardCFGAdapter::cfg private
Referenced by count(), otawa::BackwardCFGAdapter::count(), entry(), and otawa::BackwardCFGAdapter::entry().
The documentation for this class was generated from the following file:
include/otawa/cfg/CFGAdapter.h