Otawa: src/dcache/CMakeLists.txt File Reference
src/dcache/CMakeLists.txt File Reference
Functions
set (CMAKE_INSTALL_RPATH"${ORIGIN}/../../..") set(CMAKE_MACOSX_RPATH true) set(CMAKE_CXX_FLAGS"-Wall") set(SOURCES"dcache.cpp""dcache_ACSBuilder.cpp""dcache_ACSMayBuilder.cpp""dcache_BlockBuilder.cpp""dcache_CatBuilder.cpp""dcache_CatConstraintBuilder.cpp""dcache_CLPBlockBuilder.cpp""dcache_WCETFunctionBuilder.cpp""Dirty.cpp""Purge.cpp") add_library(dcache SHARED $
set_property (TARGET dcache PROPERTY PREFIX"") set(SUFFIX"$
target_link_libraries (dcache ${LIBELM}) target_link_libraries(dcache otawa) install(TARGETS dcache DESTINATION"$
Function Documentation
set (CMAKE_INSTALL_RPATH"${ORIGIN}/../../..")
set_property (TARGET dcache PROPERTY PREFIX"")
Referenced by set().
target_link_libraries (dcache ${LIBELM})
References install().
Referenced by install(), set(), and target_link_libraries().