Otawa: Extended Timing Schema
Extended Timing Schema
This WCET computation approach is based on AST representation.
Classes
class otawa::ets::TrivialAstBlockTime
This processor is used for computing execution of ast blocks in a trivial way, that is, the multiplication of ast block instruction count by the pipeline depth.
Functions
SilentFeature otawa::ets::ACS_FEATURE ("otawa::ets::ACS_FEATURE", acs_maker)
Compute the Abstract Cache State at entry of each AST for L1 instruction cache.
Identifier< AbstractCacheState * > otawa::ets::ACS ("otawa::ets::ACS", 0)
This identifier (AbstractCacheState *) is used for storing the abstract cache line for each node.
SilentFeature otawa::ets::CACHE_FIRST_MISS_FEATURE ("otawa::ets::CACHE_FIRST_MISS_FEATURE", fmiss_maker)
Provide the computation of occurrences of first-misses of instruction cache.
Identifier< int > otawa::ets::FIRST_MISSES ("otawa::ets::FIRST_MISSES", 0)
This identifier (int) is used for storing the number of first miss accesses for each node.
SilentFeature otawa::ets::CACHE_HIT_FEATURE ("otawa::ets::CACHE_HIT_FEATURE", hit_maker)
Provided the computation of the number of hits for the L1 instruction cache.
Identifier< int > otawa::ets::HITS ("otawa::ets::HITS",-1)
This identifier (int) is used for storing the number of hit accesses for each node.
SilentFeature otawa::ets::CACHE_MISS_FEATURE ("otawa::ets::CACHE_MISS_FEATURE", miss_maker)
Provide the number of misses for a L1 instruction cache.
Identifier< int > otawa::ets::MISSES ("otawa::ets::misses", 0)
This identifier (int) is used for storing the number of miss accesses for each node.
SilentFeature otawa::ets::FLOWFACT_FEATURE ("otawa::ets::FLOWFACT_FEATURE", ff_maker)
Provide flow facts in the AST.
Identifier< int > otawa::ets::LOOP_COUNT ("otawa::ets::LOOP_COUNT",-1)
This identifier (int) is used for storing the number of iteration for each loop of the program.
SilentFeature otawa::ets::BLOCK_TIME_FEATURE ("otawa::ets::BLOCK_TIME_FEATURE", bt_maker)
Provide WCET for each AST.
SilentFeature otawa::ets::WCET_FEATURE ("otawa::ets::WCET_FEATURE", w_maker)
Provide the WCET of a task using the ETS approach.
Identifier< int > otawa::ets::WCET ("otawa::ets::wcet",-1)
Identifier of annotation (int) used for storing the WCET value in the ETS of the computed function.
Identifier< int > otawa::ets::DEPTH ("otawa::ets::DEPTH", 5)
Depth of the pipeline for the code processor TrivialAstBlockTime.
Variables
SilentFeature otawa::ets::ACS_FEATURE
Compute the Abstract Cache State at entry of each AST for L1 instruction cache.
Identifier< AbstractCacheState * > otawa::ets::ACS
This identifier (AbstractCacheState *) is used for storing the abstract cache line for each node.
SilentFeature otawa::ets::CACHE_FIRST_MISS_FEATURE
Provide the computation of occurrences of first-misses of instruction cache.
Identifier< int > otawa::ets::FIRST_MISSES
This identifier (int) is used for storing the number of first miss accesses for each node.
SilentFeature otawa::ets::CACHE_HIT_FEATURE
Provided the computation of the number of hits for the L1 instruction cache.
Identifier< int > otawa::ets::HITS
This identifier (int) is used for storing the number of hit accesses for each node.
SilentFeature otawa::ets::CACHE_MISS_FEATURE
Provide the number of misses for a L1 instruction cache.
Identifier< int > otawa::ets::MISSES
This identifier (int) is used for storing the number of miss accesses for each node.
SilentFeature otawa::ets::FLOWFACT_FEATURE
Provide flow facts in the AST.
Identifier< int > otawa::ets::LOOP_COUNT
This identifier (int) is used for storing the number of iteration for each loop of the program.
SilentFeature otawa::ets::BLOCK_TIME_FEATURE
Provide WCET for each AST.
SilentFeature otawa::ets::WCET_FEATURE
Provide the WCET of a task using the ETS approach.
Identifier< int > otawa::ets::WCET
Identifier of annotation (int) used for storing the WCET value in the ETS of the computed function.
Identifier< int > otawa::ets::DEPTH
Depth of the pipeline for the code processor TrivialAstBlockTime.
Detailed Description
This WCET computation approach is based on AST representation.
WCET is computed from leaves AST to the root by applying a computation depending on the type of the AST node.
Function Documentation
Identifier<AbstractCacheState *> otawa::ets::ACS ("otawa::ets::ACS" , 0)
This identifier (AbstractCacheState *) is used for storing the abstract cache line for each node.
SilentFeature otawa::ets::ACS_FEATURE ("otawa::ets::ACS_FEATURE" , acs_maker)
Compute the Abstract Cache State at entry of each AST for L1 instruction cache.
Properties
ACS
Default Processor
ACSComputation
SilentFeature otawa::ets::BLOCK_TIME_FEATURE ("otawa::ets::BLOCK_TIME_FEATURE" , bt_maker)
Provide WCET for each AST.
Properties
WCET
Default Processor
TrivialAstBlockTime
SilentFeature otawa::ets::CACHE_FIRST_MISS_FEATURE ("otawa::ets::CACHE_FIRST_MISS_FEATURE" , fmiss_maker)
Provide the computation of occurrences of first-misses of instruction cache.
Properties
FIRST_MISSES
Default Process
CacheFirstMissComputation
SilentFeature otawa::ets::CACHE_HIT_FEATURE ("otawa::ets::CACHE_HIT_FEATURE" , hit_maker)
Provided the computation of the number of hits for the L1 instruction cache.
Properties
HITS
Default Processor
CacheHitComputation
SilentFeature otawa::ets::CACHE_MISS_FEATURE ("otawa::ets::CACHE_MISS_FEATURE" , miss_maker)
Provide the number of misses for a L1 instruction cache.
Properties
MISSES
Default Processors
CacheMissComputation
Identifier<int> otawa::ets::DEPTH ("otawa::ets::DEPTH" , 5)
Depth of the pipeline for the code processor TrivialAstBlockTime.
Identifier<int> otawa::ets::FIRST_MISSES ("otawa::ets::FIRST_MISSES" , 0)
This identifier (int) is used for storing the number of first miss accesses for each node.
SilentFeature otawa::ets::FLOWFACT_FEATURE ("otawa::ets::FLOWFACT_FEATURE" , ff_maker)
Provide flow facts in the AST.
Properties
LOOP_COUNT
Default Processor
FlowFactLoader
Identifier<int> otawa::ets::HITS ("otawa::ets::HITS" , - 1)
This identifier (int) is used for storing the number of hit accesses for each node.
Identifier<int> otawa::ets::LOOP_COUNT ("otawa::ets::LOOP_COUNT" , - 1)
This identifier (int) is used for storing the number of iteration for each loop of the program.
Identifier<int> otawa::ets::MISSES ("otawa::ets::misses" , 0)
This identifier (int) is used for storing the number of miss accesses for each node.
Identifier<int> otawa::ets::WCET ("otawa::ets::wcet" , - 1)
Identifier of annotation (int) used for storing the WCET value in the ETS of the computed function.
SilentFeature otawa::ets::WCET_FEATURE ("otawa::ets::WCET_FEATURE" , w_maker)
Provide the WCET of a task using the ETS approach.
Properties
WCET
Default Processor
WCETComputation
Variable Documentation
Identifier<AbstractCacheState *> otawa::ets::ACS("otawa::ets::ACS", 0)
This identifier (AbstractCacheState *) is used for storing the abstract cache line for each node.
Referenced by otawa::ets::ACSComputation::applyProcess(), and otawa::dcache::ACSBuilder::processLBlockSet().
SilentFeature otawa::ets::ACS_FEATURE("otawa::ets::ACS_FEATURE", acs_maker)
Compute the Abstract Cache State at entry of each AST for L1 instruction cache.
Properties
ACS
Default Processor
ACSComputation
SilentFeature otawa::ets::BLOCK_TIME_FEATURE("otawa::ets::BLOCK_TIME_FEATURE", bt_maker)
Provide WCET for each AST.
Properties
WCET
Default Processor
TrivialAstBlockTime
SilentFeature otawa::ets::CACHE_FIRST_MISS_FEATURE("otawa::ets::CACHE_FIRST_MISS_FEATURE", fmiss_maker)
Provide the computation of occurrences of first-misses of instruction cache.
Properties
FIRST_MISSES
Default Process
CacheFirstMissComputation
SilentFeature otawa::ets::CACHE_HIT_FEATURE("otawa::ets::CACHE_HIT_FEATURE", hit_maker)
Provided the computation of the number of hits for the L1 instruction cache.
Properties
HITS
Default Processor
CacheHitComputation
SilentFeature otawa::ets::CACHE_MISS_FEATURE("otawa::ets::CACHE_MISS_FEATURE", miss_maker)
Provide the number of misses for a L1 instruction cache.
Properties
MISSES
Default Processors
CacheMissComputation
Identifier<int> otawa::ets::DEPTH("otawa::ets::DEPTH", 5)
Depth of the pipeline for the code processor TrivialAstBlockTime.
Referenced by otawa::ets::TrivialAstBlockTime::configure(), and otawa::ets::TrivialAstBlockTime::processAST().
Identifier<int> otawa::ets::FIRST_MISSES("otawa::ets::FIRST_MISSES", 0)
This identifier (int) is used for storing the number of first miss accesses for each node.
Referenced by otawa::ets::ACSComputation::applyProcess(), otawa::ets::CacheMissComputation::computation(), otawa::ets::CacheHitComputation::computation(), otawa::ets::CacheFirstMissComputation::computation(), and otawa::ets::ACSComputation::initialization().
SilentFeature otawa::ets::FLOWFACT_FEATURE("otawa::ets::FLOWFACT_FEATURE", ff_maker)
Provide flow facts in the AST.
Properties
LOOP_COUNT
Default Processor
FlowFactLoader
Identifier<int> otawa::ets::HITS("otawa::ets::HITS",-1)
This identifier (int) is used for storing the number of hit accesses for each node.
Referenced by otawa::ets::ACSComputation::applyProcess(), otawa::ets::CacheHitComputation::computation(), and otawa::ets::ACSComputation::initialization().
Identifier<int> otawa::ets::LOOP_COUNT("otawa::ets::LOOP_COUNT",-1)
This identifier (int) is used for storing the number of iteration for each loop of the program.
Referenced by otawa::ets::ACSComputation::applyProcess(), otawa::ets::CacheFirstMissComputation::computation(), otawa::ets::CacheMissComputation::computation(), otawa::ets::CacheHitComputation::computation(), otawa::ets::WCETComputation::computation(), and otawa::ets::FlowFactLoader::processAST().
Identifier<int> otawa::ets::MISSES("otawa::ets::misses", 0)
This identifier (int) is used for storing the number of miss accesses for each node.
Referenced by otawa::ets::ACSComputation::applyProcess(), otawa::ets::CacheMissComputation::computation(), and otawa::ets::ACSComputation::initialization().
Identifier<int> otawa::ets::WCET("otawa::ets::wcet",-1)
Identifier of annotation (int) used for storing the WCET value in the ETS of the computed function.
Referenced by otawa::ets::WCETComputation::computation(), and otawa::ets::TrivialAstBlockTime::processAST().
SilentFeature otawa::ets::WCET_FEATURE("otawa::ets::WCET_FEATURE", w_maker)
Provide the WCET of a task using the ETS approach.
Properties
WCET
Default Processor
WCETComputation