Otawa: Cat Plugin
Cat Plugin
Implementation of LRU instruction cache analysis by categorisation according to the paper:
Classes
class otawa::cat::CATBuilder
Create a new CATBuilder processor.
class otawa::cat::CATConstraintBuilder
This processor uses categories assigned to L-block of the instruction cache to add contraints and to modify maximized function to support the instruction cache.
Functions
Identifier< BasicBlock * > otawa::cat::LOWERED_CATEGORY ("otawa::cat::LOWERED_CATEGORY", 0)
This property is set for L-Block categories that has been lowered, that is, they was classified as first-miss but lowered to always-miss due to effect of a surrounding loop (whose header basic block is stored).
Variables
Identifier< BasicBlock * > otawa::cat::LOWERED_CATEGORY
This property is set for L-Block categories that has been lowered, that is, they was classified as first-miss but lowered to always-miss due to effect of a surrounding loop (whose header basic block is stored).
Identifier< ilp::Var * > otawa::cat::HIT_VAR ("otawa::cat::HIT_VAR_", 0)
Identifier< ilp::Var * > otawa::cat::MISS_VAR ("otawa::cat::MISS_VAR_")
Property giving the variable counting the number of misses.
Identifier< ilp::Var * > otawa::cat::BB_VAR ("otawa::cat::BB_VAR_")
Identifier< CATNode * > otawa::cat::NODE ("otawa::cat::NODE", 0)
static Identifier< bool > otawa::cat::CATBuilder::NON_CONFLICT
Does anybody know anything about this?
Detailed Description
Implementation of LRU instruction cache analysis by categorisation according to the paper:
C. A.Healy, R. D. Arnold, F. Mueller, D. B. Whalley, M. G. Harmon Bounding Pipeline and Instruction Cache Performance. IEEE Transactions on Computers, 1/1999.
Plugin Information
name: otawa/cat
header: <otawa/cat/features.h>
Function Documentation
Identifier<BasicBlock *> otawa::cat::LOWERED_CATEGORY ("otawa::cat::LOWERED_CATEGORY" , 0)
This property is set for L-Block categories that has been lowered, that is, they was classified as first-miss but lowered to always-miss due to effect of a surrounding loop (whose header basic block is stored).
Variable Documentation
Identifier<ilp::Var *> otawa::cat::BB_VAR("otawa::cat::BB_VAR_")
Referenced by otawa::cat::CATConstraintBuilder::processLBlockSet().
Identifier<ilp::Var *> otawa::cat::HIT_VAR("otawa::cat::HIT_VAR_", 0)
Referenced by otawa::cat::CATConstraintBuilder::processLBlockSet().
Identifier<BasicBlock *> otawa::cat::LOWERED_CATEGORY("otawa::cat::LOWERED_CATEGORY", 0)
This property is set for L-Block categories that has been lowered, that is, they was classified as first-miss but lowered to always-miss due to effect of a surrounding loop (whose header basic block is stored).
Referenced by otawa::cat::CATConstraintBuilder::processLBlockSet(), and otawa::cat::CATBuilder::worst().
Identifier<ilp::Var *> otawa::cat::MISS_VAR("otawa::cat::MISS_VAR_") ("otawa::cat::MISS_VAR_")
Property giving the variable counting the number of misses.
This property gives the variable counting the number of misses of a BlockAccess.
Gives the variable counting the number of misses.
Hook
LBlock
Feature
ICACHE_CONSTRAINT2_FEATURE
Referenced by otawa::dcache::WCETFunctionBuilder::processBB(), otawa::cat::CATConstraintBuilder::processLBlockSet(), otawa::ccg::ConstraintBuilder::processLBlockSet(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), and otawa::CAT2ConstraintBuilder::processWorkSpace().
Identifier<CATNode *> otawa::cat::NODE("otawa::cat::NODE", 0)
Referenced by otawa::cat::CATConstraintBuilder::buildLBLOCKSET(), and otawa::cat::CATConstraintBuilder::processLBlockSet().
Identifier< bool > otawa::cat::CATBuilder::NON_CONFLICT static
Does anybody know anything about this?
Referenced by otawa::cat::CATProblem::preserve(), and otawa::cat::CATBuilder::worst().