Otawa: IPET Method
IPET Method
OTAWA provides many code processors supporting IPET approach:
Functions
Identifier< ot::time > otawa::ipet::TIME ("otawa::ipet::TIME",-1, idLabel("time"), idDesc("execution time (in cycles)"), 0)
This identifier is used for storing the time of execution in cycles (int) of the program area it applies to.
Identifier< ilp::Var * > otawa::ipet::VAR ("otawa::ipet::VAR", 0, idLabel("variable"), idDesc("variable in ILP system for IPET resolution"), 0)
This identifier is used for storing in basic blocks and edges the variables (otawa::ilp::Var *) used in ILP resolution.
Identifier< ot::time > otawa::ipet::WCET ("otawa::ipet::WCET",-1, idLabel("WCET"), idDesc("WCET (in cycles)"), 0)
Identifier of annotation used for storing for storing the WCET value (int) in the CFG of the computed function.
Identifier< bool > otawa::ipet::EXPLICIT ("otawa::ipet::EXPLICIT", false)
Identifier of a boolean property requiring that explicit names must be used.
Identifier< ot::time > otawa::ipet::TIME_DELTA ("otawa::ipet::TIME_DELTA", 0, idLabel("time delta"), idDesc("time fix for an edge traversal (in cycles)"), 0)
This property is used to store time delta on edges.
Identifier< int > otawa::ipet::COUNT ("otawa::ipet::COUNT",-1, idLabel("execution count"), idDesc("execution count in WCET"), 0)
This property is put on basic blocks and edge to record the execution count of these object on the WCET path.
Feature< NoProcessor > otawa::ipet::INTERBLOCK_SUPPORT_FEATURE ("otawa::ipet::INTERBLOCK_SUPPORT_FEATURE")
This feature ensures that effects of the inter-block have been modelized in the current ILP system.
Variables
Identifier< ot::time > otawa::ipet::TIME
This identifier is used for storing the time of execution in cycles (int) of the program area it applies to.
Identifier< ilp::Var * > otawa::ipet::VAR
This identifier is used for storing in basic blocks and edges the variables (otawa::ilp::Var *) used in ILP resolution.
Identifier< ot::time > otawa::ipet::WCET
Identifier of annotation used for storing for storing the WCET value (int) in the CFG of the computed function.
Identifier< bool > otawa::ipet::EXPLICIT
Identifier of a boolean property requiring that explicit names must be used.
Identifier< ot::time > otawa::ipet::TIME_DELTA
This property is used to store time delta on edges.
Identifier< int > otawa::ipet::COUNT
This property is put on basic blocks and edge to record the execution count of these object on the WCET path.
Feature< NoProcessor > otawa::ipet::INTERBLOCK_SUPPORT_FEATURE
This feature ensures that effects of the inter-block have been modelized in the current ILP system.
Detailed Description
OTAWA provides many code processors supporting IPET approach:
VarAssignment - assign ILP variable to each basic block and edge of the graph.
BasicConstraintsBuilder - build constraints generated from the program CFG,
BasicObjectFunctionBuilder - build the object function to maximize to get the WCET,
ConstraintLoader - add constraints from an external file,
FlowFactLoader - load and add constraints for the flow facts (currently constante loop upper bounds only),
WCETComputation - perform the WCET final computation.
Some processors are dedicated to pipeline-level analyses:
TrivialBBTime - compute the execution time of a basic block by applying a constant execution to each instruction,
Delta - change the constraints and the object function to implement the Delta method for inter-basic-block pipe-line effect support,
ExeGraphBBTime - compute the execution time of basic block using an execution graph.
Some processors are dedicated to cache analyses:
CATBuilder - compute the cache category of each instruction (always-miss, always-hit, first-miss, first-it),
CATConstraintBuilder - add constraints to use instruction access categories,
CCGBuilder - build the Cache Conflict Graph for the instruction cache,
CCGConstraintBuilder - build the constraints using the CCG to take in account instruction cache accesses,
CCGObjectFunction - the CCG instruction cache approach requires to use a special object function in order to get the WCET,
TrivialDataCacheManager - consider each memory access as a miss.
These processors interacts using the following properties:
TIME - execution time of a program part (usually a basic block),
VAR - ILP variable associated with a program component (usually a basic block or an edge),
SYSTEM - ILP system associated with a root CFG,
WCET - WCET of a root CFG,
EXPLICIT - used in configuration of code processor, cause the generation of explicit variable names instead of numeric ones (default to false),
RECURSIVE - cause the processors to work recursively (default to false).
Function Documentation
Identifier<int> otawa::ipet::COUNT ("otawa::ipet::COUNT" , - 1, idLabel("execution count") , idDesc("execution count in WCET") , 0)
This property is put on basic blocks and edge to record the execution count of these object on the WCET path.
Feature
ipet::WCET_COUNT_RECORDED_FEATURE
Hooks
otawa::BasicBlock
otawa::Edge
Identifier<bool> otawa::ipet::EXPLICIT ("otawa::ipet::EXPLICIT" , false)
Identifier of a boolean property requiring that explicit names must be used.
The generation of explicit names for variables may be time-consuming and must only be activated for debugging purposes.
Feature<NoProcessor> otawa::ipet::INTERBLOCK_SUPPORT_FEATURE ("otawa::ipet::INTERBLOCK_SUPPORT_FEATURE")
This feature ensures that effects of the inter-block have been modelized in the current ILP system.
Currently, there is no default processor to get it cause the heterogeneity of solutions to this problem.
Implementing Processors
Delta
Identifier<ot::time> otawa::ipet::TIME ("otawa::ipet::TIME" , - 1, idLabel("time") , idDesc("execution time (in cycles)") , 0)
This identifier is used for storing the time of execution in cycles (int) of the program area it applies to.
Identifier<ot::time> otawa::ipet::TIME_DELTA ("otawa::ipet::TIME_DELTA" , 0 , idLabel("time delta") , idDesc("time fix for an edge traversal (in cycles)") , 0)
This property is used to store time delta on edges.
This time may be used to improve accuracy of the IPET system with a time modifier based on edges (use the TimeDeltaObjectFunctionModifier to add time deltas to the object function).
Identifier<ilp::Var *> otawa::ipet::VAR ("otawa::ipet::VAR" , 0 , idLabel("variable") , idDesc("variable in ILP system for IPET resolution") , 0)
This identifier is used for storing in basic blocks and edges the variables (otawa::ilp::Var *) used in ILP resolution.
Identifier<ot::time> otawa::ipet::WCET ("otawa::ipet::WCET" , - 1, idLabel("WCET") , idDesc("WCET (in cycles)") , 0)
Identifier of annotation used for storing for storing the WCET value (int) in the CFG of the computed function.
Variable Documentation
Identifier<int> otawa::ipet::COUNT("otawa::ipet::COUNT",-1, idLabel("execution count"), idDesc("execution count in WCET"), 0)
This property is put on basic blocks and edge to record the execution count of these object on the WCET path.
Feature
ipet::WCET_COUNT_RECORDED_FEATURE
Hooks
otawa::BasicBlock
otawa::Edge
Referenced by otawa::ipet::WCETCountRecorder::processBB().
Identifier<bool> otawa::ipet::EXPLICIT("otawa::ipet::EXPLICIT", false)
Identifier of a boolean property requiring that explicit names must be used.
The generation of explicit names for variables may be time-consuming and must only be activated for debugging purposes.
Referenced by otawa::ipet::CachePenaltiesObjectFunctionBuilder::configure(), otawa::CAT2OnlyConstraintBuilder::configure(), otawa::EdgeCAT2ConstraintBuilder::configure(), otawa::dcache::CatConstraintBuilder::configure(), otawa::ipet::FlowFactConstraintBuilder::configure(), otawa::etime::EdgeTimeBuilder::configure(), otawa::LinkedBlocksDetector::configure(), otawa::branch::OnlyConsBuilder::configure(), otawa::cat::CATConstraintBuilder::configure(), otawa::etime::StandardEventBuilder::configure(), otawa::ipet::BasicConstraintsBuilder::configure(), otawa::ipet::VarAssignment::configure(), otawa::ccg::ConstraintBuilder::configure(), and otawa::tsim::Delta::configure().
Feature<NoProcessor> otawa::ipet::INTERBLOCK_SUPPORT_FEATURE("otawa::ipet::INTERBLOCK_SUPPORT_FEATURE")
This feature ensures that effects of the inter-block have been modelized in the current ILP system.
Currently, there is no default processor to get it cause the heterogeneity of solutions to this problem.
Implementing Processors
Delta
Referenced by otawa::ipet::getSystem().
Identifier<ot::time> otawa::ipet::TIME("otawa::ipet::TIME",-1, idLabel("time"), idDesc("execution time (in cycles)"), 0)
This identifier is used for storing the time of execution in cycles (int) of the program area it applies to.
Referenced by otawa::GraphBBTime< G >::analyzePathContext(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::ipet::TrivialInstCacheManager::processBB(), otawa::ipet::BasicObjectFunctionBuilder::processBB(), otawa::ipet::TrivialBBTime::processBB(), otawa::tsim::BBTimeSimulator::processBB(), otawa::BBRatioDisplayer::processBB(), otawa::tsim::Delta::processBBPath(), and otawa::tsim::BBPath::time().
Identifier<ot::time> otawa::ipet::TIME_DELTA("otawa::ipet::TIME_DELTA", 0, idLabel("time delta"), idDesc("time fix for an edge traversal (in cycles)"), 0)
This property is used to store time delta on edges.
This time may be used to improve accuracy of the IPET system with a time modifier based on edges (use the TimeDeltaObjectFunctionModifier to add time deltas to the object function).
Referenced by otawa::tsim::TimeDeltaObjectFunctionModifier::processBB().
Identifier<ilp::Var *> otawa::ipet::VAR("otawa::ipet::VAR", 0, idLabel("variable"), idDesc("variable in ILP system for IPET resolution"), 0)
This identifier is used for storing in basic blocks and edges the variables (otawa::ilp::Var *) used in ILP resolution.
Referenced by otawa::ccg::ConstraintBuilder::addConstraintHeader(), otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), otawa::etime::EdgeTimeBuilder::contributeConst(), otawa::etime::EdgeTimeBuilder::contributeSplit(), otawa::etime::EdgeTimeBuilder::genForOneCost(), otawa::tsim::BBPath::getVar(), otawa::tsim::BBPath::makeVarName(), otawa::ipet::ConstraintLoader::newBBVar(), otawa::ipet::ConstraintLoader::newEdgeVar(), otawa::ipet::WCETCountRecorder::processBB(), otawa::ipet::CachePenaltiesObjectFunctionBuilder::processBB(), otawa::tsim::TimeDeltaObjectFunctionModifier::processBB(), otawa::ipet::BasicObjectFunctionBuilder::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::ipet::VarAssignment::processBB(), otawa::ipet::BasicConstraintsBuilder::processBB(), otawa::BBRatioDisplayer::processBB(), otawa::BBRatioDisplayer::processCFG(), otawa::cat::CATConstraintBuilder::processLBlockSet(), otawa::ccg::ConstraintBuilder::processLBlockSet(), otawa::EdgeCAT2ConstraintBuilder::processWorkSpace(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), and otawa::ipet::BasicConstraintsBuilder::processWorkSpace().
Identifier<ot::time> otawa::ipet::WCET("otawa::ipet::WCET",-1, idLabel("WCET"), idDesc("WCET (in cycles)"), 0)
Identifier of annotation used for storing for storing the WCET value (int) in the CFG of the computed function.
Referenced by otawa::ipet::WCETComputation::processWorkSpace(), otawa::display::ILPSystemDisplayer::processWorkSpace(), and otawa::BBRatioDisplayer::setup().