Otawa: AST Plugin
AST Plugin
This module provides facilities to handle an executable as an AST (Abstract Syntactic Tree).
Classes
class otawa::ast::AST
This is the base class for the representation of programs as Abstract Syntax Trees.
class otawa::ast::ASTLoader
This class may be used for loading AST from an external file using the Heptane format (see doc/ directory for more details).
class otawa::ast::ASTInfo
This class stores all the function known for the current framework.
class otawa::ast::BlockAST
This class represents the leafs of the AST.
class otawa::ast::CallAST
This class is a specialized block AST ended by a function call.
class otawa::ast::DoWhileAST
Representation of C do{ ...
class otawa::ast::ForAST
Representation of C language FOR loop.
class otawa::ast::FunAST
This class represents functions in the AST representation.
class otawa::ast::IfAST
AST for representing selections.
class otawa::ast::ASTProcessor
This is a specialization of the processor class dedicated to AST processing.
class otawa::ast::FunProcessor
This is a specialization of the processor class dedicated to function processing.
class otawa::ast::SeqAST
This AST represents sequences.
class otawa::ast::WhileAST
Representation of an iteration with test at start of the loop.
Functions
p::feature otawa::ast::FEATURE ("otawa::ast::FEATURE", new Maker< ASTLoader >())
This feature ensures that the AST structure of the binary has been loaded.
Identifier< String > otawa::ast::PATH ("otawa::ast::PATH","")
This identifier may be passed for specifying the path a file for loading the AST.
Identifier< ASTInfo * > otawa::ast::INFO ("otawa::ast::INFO", 0)
Identifier of the property storing the AST information on the framework object.
Identifier< FunAST * > otawa::ast::FUN ("otawa::ast::FUN", 0)
A property with this identifier is put on each instruction, start of an AST function.
Variables
p::feature otawa::ast::FEATURE
This feature ensures that the AST structure of the binary has been loaded.
Identifier< String > otawa::ast::PATH
This identifier may be passed for specifying the path a file for loading the AST.
Identifier< ASTInfo * > otawa::ast::INFO
Identifier of the property storing the AST information on the framework object.
Identifier< FunAST * > otawa::ast::FUN
A property with this identifier is put on each instruction, start of an AST function.
Detailed Description
This module provides facilities to handle an executable as an AST (Abstract Syntactic Tree).
This allows to implements ETS (Extending Timing Schema) approach to compute the WCET as in:
S.S. LIM, Y.H. BAE, G.T. JANG, S.L. MIN, C.Y. PARK, H. SHIN, H., C.S. KIM, C. S. An accurate worst case timing analysis for RISC processors. IEEE transactions on software engineering, 21(7), 593-604, 1995.
The AST is loaded from an external file (usually generated from source files) in the same format as Heptane tool (http://www.irisa.fr/alf/index.php?option=com_content&view=article&id=29&Itemid=0).
Plugin Information
name: otawa/ast
header: <otawa/ast/features.h>
Function Documentation
p::feature otawa::ast::FEATURE ("otawa::ast::FEATURE" , new Maker< ASTLoader > ())
This feature ensures that the AST structure of the binary has been loaded.
Configuration
PATH
Properties
FUN
INFO
Identifier<FunAST *> otawa::ast::FUN ("otawa::ast::FUN" , 0)
A property with this identifier is put on each instruction, start of an AST function.
Its value is of type "AST *".
Hook
Inst
Feature
otawa::ref::FEATURE
Identifier<ASTInfo *> otawa::ast::INFO ("otawa::ast::INFO" , 0)
Identifier of the property storing the AST information on the framework object.
Hook
WorkSpace
Feature
otawa::ast::FEATURE
Identifier<String> otawa::ast::PATH ("otawa::ast::PATH" , "")
This identifier may be passed for specifying the path a file for loading the AST.
Feature
otawa::ast::FEATURE
Variable Documentation
p::feature otawa::ast::FEATURE("otawa::ast::FEATURE", new Maker< ASTLoader >())
This feature ensures that the AST structure of the binary has been loaded.
Configuration
PATH
Properties
FUN
INFO
Referenced by otawa::ast::ASTLoader::ASTLoader().
Identifier<FunAST *> otawa::ast::FUN("otawa::ast::FUN", 0)
A property with this identifier is put on each instruction, start of an AST function.
Its value is of type "AST *".
Hook
Inst
Feature
otawa::ref::FEATURE
Referenced by otawa::ast::FunAST::FunAST(), and otawa::ast::ASTInfo::getFunction().
Identifier<ASTInfo *> otawa::ast::INFO("otawa::ast::INFO", 0)
Identifier of the property storing the AST information on the framework object.
Hook
WorkSpace
Feature
otawa::ast::FEATURE
Referenced by otawa::ast::ASTInfo::ASTInfo(), otawa::ast::CallAST::CallAST(), otawa::ast::FunAST::FunAST(), and otawa::ast::ASTInfo::getInfo().
Identifier<String> otawa::ast::PATH("otawa::ast::PATH","")
This identifier may be passed for specifying the path a file for loading the AST.
Feature
otawa::ast::FEATURE
Referenced by otawa::ast::ASTLoader::ASTLoader(), and otawa::ast::ASTLoader::configure().