Otawa: src/prog/hard_Processor.cpp File Reference
hard_Processor.cpp File Reference
#include <elm/genstruct/SortedBinMap.h>
#include <elm/serial2/XOMUnserializer.h>
#include <otawa/hard/CacheConfiguration.h>
#include <otawa/hard/Processor.h>
#include <otawa/proc/ProcessorPlugin.h>
#include <otawa/prog/WorkSpace.h>
Namespaces
otawa
$Id$ Copyright (c) 2007, IRIT - UPS casse.nosp@m.@iri.nosp@m.t.fr
otawa::hard
elm
elm::serial2
Functions
SilentFeature otawa::hard::PROCESSOR_FEATURE ("otawa::hard::PROCESSOR_FEATURE", maker)
This feature ensures we have obtained the memory configuration of the system.
Identifier< const hard::Processor * > otawa::hard::PROCESSOR ("otawa::hard::PROCESSOR",&Processor::null)
Configuration identifier to select the used processor.
Identifier< string > otawa::hard::PROCESSOR_ID ("otawa::hard::PROCESSOR_ID")
Configuration identifier to select used processor from its identifier (possibly found in an external plugin).
VALUE (otawa::hard::Stage::FETCH)
VALUE (otawa::hard::Stage::LAZY)
VALUE (otawa::hard::Stage::EXEC)
VALUE (otawa::hard::Stage::COMMIT)
ENUM_END SERIALIZE (otawa::hard::PipelineUnit)
SERIALIZE (otawa::hard::FunctionalUnit)
SERIALIZE (otawa::hard::Dispatch)
SERIALIZE (otawa::hard::Stage)
SERIALIZE (otawa::hard::Queue)
SERIALIZE (otawa::hard::Processor)
void elm::serial2::__unserialize (Unserializer &s, otawa::hard::Dispatch::type_t &v)
void elm::serial2::__serialize (Serializer &s, otawa::hard::Dispatch::type_t v)
Function Documentation
ENUM_END SERIALIZE (otawa::hard::PipelineUnit)
Referenced by otawa::hard::Processor::instantiate().
SERIALIZE (otawa::hard::FunctionalUnit)
SERIALIZE (otawa::hard::Dispatch)
SERIALIZE (otawa::hard::Stage)
SERIALIZE (otawa::hard::Queue)
SERIALIZE (otawa::hard::Processor)
VALUE (otawa::hard::Stage::FETCH)
Referenced by elm::serial2::__unserialize(), and otawa::hard::Processor::instantiate().
VALUE (otawa::hard::Stage::LAZY)
VALUE (otawa::hard::Stage::EXEC)
VALUE (otawa::hard::Stage::COMMIT)