Otawa: src/mkff/mkff.cpp File Reference
mkff.cpp File Reference
#include <elm/io.h>
#include <elm/options.h>
#include <elm/option/StringOption.h>
#include <elm/genstruct/Vector.h>
#include <otawa/cfg.h>
#include <otawa/otawa.h>
#include <otawa/util/ContextTree.h>
#include <elm/checksum/Fletcher.h>
#include <elm/io/InFileStream.h>
#include <elm/system/Path.h>
#include <otawa/cfg/CFGCollector.h>
#include <otawa/util/FlowFactLoader.h>
#include <otawa/flowfact/features.h>
#include <otawa/cfg/CFGChecker.h>
#include <otawa/app/Application.h>
Functions
string nameOf (CFG *cfg)
Find a name for the current CFG.
string makeAddress (CFG *cfg, Address addr)
Compute an address for an item, relative to the container CFG if possible.
OTAWA_RUN (Command)
Variables
const char * noreturn_labels []
const char * nocall_labels []
Function Documentation
string makeAddress (CFG * cfg, Address addr) inline
Compute an address for an item, relative to the container CFG if possible.
Parameters
CFG Container CFG.
address Address of the item.
xml Use XML output.
Returns
String representing the address of the instruction in F4. Compute an address for an instruction, relative to the container CFG if possible.
Parameters
CFG Container CFG.
inst Instruction to get address of.
Returns
String representing the address of the instruction in F4. Make an address for F4 file.
Parameters
cfg Current CFG.
addr Address of the item relative to the CFG.
Returns
String representing the address.
References otawa::Identifier< T >::add(), otawa::ProgItem::address(), otawa::CFG::address(), otawa::ot::address(), otawa::cfgio::bb(), otawa::BRANCH_TARGET, otawa::ContextTree::cfg(), otawa::cfgio::cfg(), otawa::CONTEXT_TREE, otawa::CONTEXT_TREE_BY_CFG_FEATURE, otawa::CONTEXTUAL_LOOP_BOUND, otawa::p::end, otawa::WorkSpace::findInstAt(), otawa::CFG::firstInst(), otawa::Process::getSourceLine(), otawa::Inst::isCall(), otawa::Inst::isControl(), otawa::WorkSpace::isProvided(), otawa::Inst::isReturn(), otawa::CFG::label(), otawa::p::init::maker(), otawa::MAX_ITERATION, name, nameOf(), nocall_labels, noreturn_labels, OTAWA_RUN(), otawa::PRESERVED, otawa::WorkSpace::process(), otawa::p::require, otawa::SOURCE_LINE_FEATURE, otawa::Inst::target(), otawa::cfgio::target(), otawa::TASK_ENTRY, otawa::ProgItem::topAddress(), and otawa::type().
string nameOf (CFG * cfg) inline
Find a name for the current CFG.
If there is a label, use it. Else build an identifier based on its address.
Parameters
cfg Current CFG.
Returns
Matching name.
References otawa::CFG::address(), and otawa::CFG::label().
Referenced by makeAddress().
OTAWA_RUN (Command)
Referenced by makeAddress().
Variable Documentation
const char* nocall_labels[]
Initial value:
= {
        "__eabi",
        "_main",
        0
}
Referenced by makeAddress().
const char* noreturn_labels[]
Initial value:
= {
        "_exit",
        "exit",
        0
}
Referenced by makeAddress().