var modules =
[
    [ "New Abstract Interpretation Engine", "group__ai.html", "group__ai" ],
    [ "Commands", "group__commands.html", null ],
    [ "Application Writing", "group__application.html", "group__application" ],
    [ "CFG (Control Flow Graph)", "group__cfg.html", "group__cfg" ],
    [ "CLP Analysis", "group__clp.html", "group__clp" ],
    [ "Data Flow Analysis", "group__dfa.html", "group__dfa" ],
    [ "Available Features and Processors", "group__features.html", null ],
    [ "Platform Description", "group__hard.html", "group__hard" ],
    [ "ILP -- Integer Linear Programming", "group__ilp.html", "group__ilp" ],
    [ "ExtCons : External Constraint Format", "group__extcons.html", "group__extcons" ],
    [ "IPET Method", "group__ipet.html", "group__ipet" ],
    [ "Parametric Execution Graph", "group__peg.html", "group__peg" ],
    [ "Dynamic Identifier, Feature and Processor", "group__dyn.html", "group__dyn" ],
    [ "Parametric Features and Processor", "group__parametric.html", "group__parametric" ],
    [ "Processor Layer", "group__proc.html", "group__proc" ],
    [ "Program Representation", "group__prog.html", "group__prog" ],
    [ "Contextual Information", "group__context.html", null ],
    [ "Properties System", "group__prop.html", "group__prop" ],
    [ "Scripts", "group__script.html", "group__script" ],
    [ "Semantic Instructions", "group__sem.html", "group__sem" ],
    [ "Memory Accesses", "group__addr.html", "group__addr" ],
    [ "Flow Facts", "group__ff.html", "group__ff" ],
    [ "Graph Handling", "group__graph.html", "group__graph" ],
    [ "Stack Analysis", "group__stack.html", "group__stack" ],
    [ "ODisplay Library", "group__display.html", "group__display" ],
    [ "bpred Plugin", "group__bpred.html", "group__bpred" ],
    [ "Data Cache", "group__dcache.html", "group__dcache" ],
    [ "AST Plugin", "group__ast.html", "group__ast" ],
    [ "Extended Timing Schema", "group__ets.html", "group__ets" ],
    [ "Event Time Module", "group__etime.html", "group__etime" ],
    [ "CFG Input / Output", "group__cfgio.html", "group__cfgio" ],
    [ "CCG Plugin", "group__ccg.html", "group__ccg" ],
    [ "branch Plugin", "group__branch.html", "group__branch" ],
    [ "Cat Plugin", "group__cat.html", "group__cat" ]
];