Otawa: otawa::ccg Namespace Reference
otawa::ccg Namespace Reference
Classes
class Builder
This processor builds the Cache Conflict Graph of the current task.
class Collection
class ConstraintBuilder
This processor allows handling timing effects of the instruction cache in the IPET approach.
class Domain
class Edge
This class represents edges in the CCG representation.
class Graph
class LBlock
The l-block is an abstraction allowing to split the basic block according to the bound of the cache block, that is, instructions composing a l-block are owned by the same basic block and same cache block.
class LBlockBuilder
This processor builds the list of l-blocks for each lines of instruction cache and stores it in the CFG.
class LBlockSet
This class represents the list of l-blocks of a task for a chosen cache row.
class Node
Node of a CCG (Cache Conflict Graph).
class Problem
Functions
Output & operator<< (Output &out, const LBlock *block)
p::feature FEATURE ("otawa::ccg::FEATURE", new Maker< Builder >())
This feature ensures that Cache Conflict Graphs has been built.
Identifier< ilp::Var * > MISS_VAR ("otawa::ccg::MISS_VAR", 0)
Gives the variable counting the number of misses.
p::feature CONSTRAINT_FEATURE ("otawa::ccg::CONSTRAINT_FEATURE", new Maker< ConstraintBuilder >())
This feature ensures that the CCG has been translated in the form of ILP constraints.
Identifier< LBlockSet ** > LBLOCKS ("otawa::ccg::LBLOCKS", 0)
This property is used for storing the list of L-Blocks.
Identifier< genstruct::AllocatedTable< LBlock * > * > BB_LBLOCKS ("otawa::ccg::BB_LBLOCKS", 0)
This property is used for storing the list of L-Blocks of a BasicBlock.
p::feature COLLECTED_LBLOCKS_FEATURE ("otawa::ccg::COLLECTED_LBLOCKS_FEATURE", new Maker< LBlockBuilder >())
This feature ensures that the L-blocks of the current task has been collected.
Variables
p::feature COLLECTED_LBLOCKS_FEATURE
This feature ensures that the L-blocks of the current task has been collected.
Identifier< LBlockSet ** > LBLOCKS
This property is used for storing the list of L-Blocks.
Identifier< genstruct::AllocatedTable< LBlock * > * > BB_LBLOCKS
This property is used for storing the list of L-Blocks of a BasicBlock.
p::feature FEATURE
This feature ensures that Cache Conflict Graphs has been built.
Identifier< ilp::Var * > MISS_VAR
Gives the variable counting the number of misses.
p::feature CONSTRAINT_FEATURE
This feature ensures that the CCG has been translated in the form of ILP constraints.
Function Documentation
Identifier<genstruct::AllocatedTable<LBlock* >* > otawa::ccg::BB_LBLOCKS ("otawa::ccg::BB_LBLOCKS" , 0)
This property is used for storing the list of L-Blocks of a BasicBlock.
cache.
Hooks
BasicBlock
p::feature otawa::ccg::COLLECTED_LBLOCKS_FEATURE ("otawa::ccg::COLLECTED_LBLOCKS_FEATURE" , new Maker< LBlockBuilder > ())
This feature ensures that the L-blocks of the current task has been collected.
Properties
LBLOCKS
BB_LBLOCKS
Identifier<LBlockSet **> otawa::ccg::LBLOCKS ("otawa::ccg::LBLOCKS" , 0)
This property is used for storing the list of L-Blocks.
The type of its date is LBlockSet *[] with a size equal to the line count of the instruction cache.
Hooks
FrameWork
Output & otawa::ccg::operator<< (Output & out, const LBlock * block)
References BB_LBLOCKS, LBLOCKS, otawa::ccg::LBlock::lblockset(), otawa::ccg::LBlockSet::line(), and otawa::ccg::LBlock::number().
Variable Documentation
Identifier<genstruct::AllocatedTable<LBlock* >* > otawa::ccg::BB_LBLOCKS("otawa::ccg::BB_LBLOCKS", 0)
This property is used for storing the list of L-Blocks of a BasicBlock.
cache.
Hooks
BasicBlock
Referenced by operator<<(), and otawa::ccg::LBlockBuilder::processBB().
p::feature otawa::ccg::COLLECTED_LBLOCKS_FEATURE("otawa::ccg::COLLECTED_LBLOCKS_FEATURE", new Maker< LBlockBuilder >())
This feature ensures that the L-blocks of the current task has been collected.
Properties
LBLOCKS
BB_LBLOCKS
Referenced by otawa::ccg::LBlockSet::LBlockSet().
Identifier<LBlockSet **> otawa::ccg::LBLOCKS("otawa::ccg::LBLOCKS", 0)
This property is used for storing the list of L-Blocks.
The type of its date is LBlockSet *[] with a size equal to the line count of the instruction cache.
Hooks
FrameWork
Referenced by operator<<(), otawa::ccg::ConstraintBuilder::processWorkSpace(), otawa::ccg::Builder::processWorkSpace(), and otawa::ccg::LBlockBuilder::setup().