Otawa: otawa::tsim Namespace Reference
otawa::tsim Namespace Reference
Classes
class BBPath
class BBTimeSimulator
class Delta
class TimeDeltaObjectFunctionModifier
This processor is used for modify the object function to maximize for resolving the IPET system, that is, For each edge where a TIME_DELTA is found, it adds: tdelta * ei,j where.
class TreePath
Functions
io::Output & operator<< (io::Output &out, BBPath &path)
Display a BB path as a sequence of basic blocks.
Feature< Delta > DELTA_SEQUENCES_FEATURE ("otawa::ipet::DELTA_SEQUENCES_FEATURE")
Feature ensure that sequences have been built to achieve the Delta interblock effect support.
Feature< TimeDeltaObjectFunctionModifier > EDGE_TIME_FEATURE ("otawa::tsim::EDGE_TIME_FEATURE")
This feature ensurers that the TIME_DELTA property linked to the CFG edges are used in the maximized object function of the IPET ILP system.
Variables
Feature< Delta > DELTA_SEQUENCES_FEATURE
Feature ensure that sequences have been built to achieve the Delta interblock effect support.
Feature< TimeDeltaObjectFunctionModifier > EDGE_TIME_FEATURE
This feature ensurers that the TIME_DELTA property linked to the CFG edges are used in the maximized object function of the IPET ILP system.
Function Documentation
Feature<Delta> otawa::tsim::DELTA_SEQUENCES_FEATURE ("otawa::ipet::DELTA_SEQUENCES_FEATURE")
Feature ensure that sequences have been built to achieve the Delta interblock effect support.
Properties
Delta::DELTA (BBPATH).
Feature<TimeDeltaObjectFunctionModifier> otawa::tsim::EDGE_TIME_FEATURE ("otawa::tsim::EDGE_TIME_FEATURE")
This feature ensurers that the TIME_DELTA property linked to the CFG edges are used in the maximized object function of the IPET ILP system.
io::Output & otawa::tsim::operator<< (io::Output & out, BBPath & path)
Display a BB path as a sequence of basic blocks.
Parameters
out Output channel.
path Path to display.
Returns
Output channel.
References otawa::cfgio::bb().
Variable Documentation
Feature<Delta> otawa::tsim::DELTA_SEQUENCES_FEATURE("otawa::ipet::DELTA_SEQUENCES_FEATURE")
Feature ensure that sequences have been built to achieve the Delta interblock effect support.
Properties
Delta::DELTA (BBPATH).
Referenced by otawa::tsim::Delta::delta().
Feature<TimeDeltaObjectFunctionModifier> otawa::tsim::EDGE_TIME_FEATURE("otawa::tsim::EDGE_TIME_FEATURE")
This feature ensurers that the TIME_DELTA property linked to the CFG edges are used in the maximized object function of the IPET ILP system.
Referenced by otawa::tsim::TimeDeltaObjectFunctionModifier::processBB().