Otawa: otawa::cache Namespace Reference
otawa::cache Namespace Reference
Classes
class CategoryStats
This class is used to store statistics about the categories about cache accesses.
Typedefs
typedef enum otawa::cache::category_t category_t
Enumerations
enum category_t {
INVALID_CATEGORY = 0, ALWAYS_HIT = 1, FIRST_HIT = 2, FIRST_MISS = 3,
ALWAYS_MISS = 4, NOT_CLASSIFIED = 5
}
Functions
io::Output & operator<< (io::Output &out, category_t cat)
io::Output & operator<< (io::Output &out, const CategoryStats &stats)
Identifier< category_t > DEFAULT_CAT ("otawa::cache::DEFAULT_CAT", ALWAYS_MISS)
This property is a configuration for PESSIMISTIC_CATEGORY_FEATURE.
p::feature PESSIMISTIC_CATEGORY_FEATURE ("otawa::cache::PESSIMISTIC_CATEGORY_FEATURE", new Maker< PessimisticCategoryBuilder >())
This feature assigns to each L-Block the same category, that is, ALWAYS_MISS as a default.
Identifier< CategoryStats * > CATEGORY_STATS ("otawa::CATEGORY_STATS", 0)
Put in the statistics to get statistics about cache categories.
p::feature ICACHE_CATEGORY_FEATURE ("otawa::ICACHE_CATEGORY_FEATURE", new Maker< NoProcessor >())
This feature asserts that a category is assigned at each l-block involved in the current task.
Identifier< category_t > CATEGORY ("otawa::category", INVALID_CATEGORY)
This property stores the instruction cache access category of L-Blocks.
Identifier< BasicBlock * > CATEGORY_HEADER ("otawa::CATEGORY_HEADER", 0)
In the case of a FIRST_HIT (or FIRST_MISS) property, contains the header of the loop causing the HIT (or MISS) at the first iteration.
Variables
Identifier< category_t > DEFAULT_CAT
This property is a configuration for PESSIMISTIC_CATEGORY_FEATURE.
p::feature PESSIMISTIC_CATEGORY_FEATURE
This feature assigns to each L-Block the same category, that is, ALWAYS_MISS as a default.
Identifier< category_t > CATEGORY
This property stores the instruction cache access category of L-Blocks.
Identifier< BasicBlock * > CATEGORY_HEADER
In the case of a FIRST_HIT (or FIRST_MISS) property, contains the header of the loop causing the HIT (or MISS) at the first iteration.
Identifier< CategoryStats * > CATEGORY_STATS
Put in the statistics to get statistics about cache categories.
p::feature ICACHE_CATEGORY_FEATURE
This feature asserts that a category is assigned at each l-block involved in the current task.
Typedef Documentation
typedef enum otawa::cache::category_t otawa::cache::category_t
Enumeration Type Documentation
enum otawa::cache::category_t
Enumerator
INVALID_CATEGORY
ALWAYS_HIT
FIRST_HIT
FIRST_MISS
ALWAYS_MISS
NOT_CLASSIFIED
Function Documentation
Identifier<category_t> otawa::cache::CATEGORY ("otawa::category" , INVALID_CATEGORY)
This property stores the instruction cache access category of L-Blocks.
This value may be :
ALWAYS_HIT : accesses to this l-block produces always a cache hit,
ALWAYS_MISS : accesses to this l-block produces always a cache miss,
FIRST_HIT : accesses to this l-block produces an cache hit at the first iteration of the containing loop and cache misses in the next iterations,
FIRST_MISS : accesses to this l-block produces a cache miss at the first iteration of the containing loop and cache hits in the next iterations,
Hooks
LBlock
Identifier<BasicBlock*> otawa::cache::CATEGORY_HEADER ("otawa::CATEGORY_HEADER" , 0)
In the case of a FIRST_HIT (or FIRST_MISS) property, contains the header of the loop causing the HIT (or MISS) at the first iteration.
Hooks
LBlocks
Identifier<CategoryStats *> otawa::cache::CATEGORY_STATS ("otawa::CATEGORY_STATS" , 0)
Put in the statistics to get statistics about cache categories.
Hooks
processor configuration property list
Identifier<category_t> otawa::cache::DEFAULT_CAT ("otawa::cache::DEFAULT_CAT" , ALWAYS_MISS)
This property is a configuration for PESSIMISTIC_CATEGORY_FEATURE.
As a default, the assigned category is ALWAYS_MISS but it can be changed by setting this property.
Feature: PESSIMISTIC_CATEGORY_FEATURE
Default Value: ALWAYS_MISS
Referenced by otawa::CAT2Builder::processCFG().
p::feature otawa::cache::ICACHE_CATEGORY_FEATURE ("otawa::ICACHE_CATEGORY_FEATURE" , new Maker< NoProcessor > ())
This feature asserts that a category is assigned at each l-block involved in the current task.
Properties
CATEGORY (LBlock).
CATEGORY_HEADER
io::Output & otawa::cache::operator<< (io::Output & out, category_t stats)
io::Output & otawa::cache::operator<< (io::Output & out, const CategoryStats & stats)
References ALWAYS_HIT, otawa::cache::CategoryStats::get(), otawa::cache::CategoryStats::linked(), NOT_CLASSIFIED, and otawa::cache::CategoryStats::total().
p::feature otawa::cache::PESSIMISTIC_CATEGORY_FEATURE ("otawa::cache::PESSIMISTIC_CATEGORY_FEATURE" , new Maker< PessimisticCategoryBuilder > ())
This feature assigns to each L-Block the same category, that is, ALWAYS_MISS as a default.
The assigned category can be changed using DEFAULT_CAT. It is basically used to provide a pessimistic analysis of the instruction cache.
Providing this feature implies providing also ICACHE_CATEGORY2_FEATURE.
Configuration:
DEFAULT_CAT
Default implementation: PessimisticCategoryBuilder
Referenced by otawa::CAT2Builder::processCFG().
Variable Documentation
Identifier<category_t> otawa::cache::CATEGORY("otawa::category", INVALID_CATEGORY)
This property stores the instruction cache access category of L-Blocks.
This value may be :
ALWAYS_HIT : accesses to this l-block produces always a cache hit,
ALWAYS_MISS : accesses to this l-block produces always a cache miss,
FIRST_HIT : accesses to this l-block produces an cache hit at the first iteration of the containing loop and cache misses in the next iterations,
FIRST_MISS : accesses to this l-block produces a cache miss at the first iteration of the containing loop and cache hits in the next iterations,
Hooks
LBlock
Referenced by otawa::cat::CATBuilder::buildLBLOCKSET(), otawa::CAT2Builder::processLBlockSet(), otawa::cat::CATConstraintBuilder::processLBlockSet(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), otawa::LinkedBlocksDetector::processWorkSpace(), otawa::LinkedBlocksDetector::recordBlocks(), otawa::cache::CategoryStats::reset(), and otawa::cat::CATBuilder::worst().
Identifier<BasicBlock*> otawa::cache::CATEGORY_HEADER("otawa::CATEGORY_HEADER", 0)
In the case of a FIRST_HIT (or FIRST_MISS) property, contains the header of the loop causing the HIT (or MISS) at the first iteration.
Hooks
LBlocks
Referenced by otawa::LBlockManager::next(), otawa::CAT2Builder::processLBlockSet(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), otawa::LinkedBlocksDetector::processWorkSpace(), and otawa::cache::CategoryStats::reset().
Identifier<CategoryStats *> otawa::cache::CATEGORY_STATS("otawa::CATEGORY_STATS", 0)
Put in the statistics to get statistics about cache categories.
Hooks
processor configuration property list
Referenced by otawa::LinkedBlocksDetector::configure(), otawa::CAT2Builder::configure(), and otawa::cache::CategoryStats::reset().
Identifier<category_t> otawa::cache::DEFAULT_CAT("otawa::cache::DEFAULT_CAT", ALWAYS_MISS)
This property is a configuration for PESSIMISTIC_CATEGORY_FEATURE.
As a default, the assigned category is ALWAYS_MISS but it can be changed by setting this property.
Feature: PESSIMISTIC_CATEGORY_FEATURE
Default Value: ALWAYS_MISS
p::feature otawa::cache::ICACHE_CATEGORY_FEATURE("otawa::ICACHE_CATEGORY_FEATURE", new Maker< NoProcessor >())
This feature asserts that a category is assigned at each l-block involved in the current task.
Properties
CATEGORY (LBlock).
CATEGORY_HEADER
Referenced by otawa::cat::CATBuilder::processWorkSpace(), and otawa::cache::CategoryStats::reset().
p::feature otawa::cache::PESSIMISTIC_CATEGORY_FEATURE("otawa::cache::PESSIMISTIC_CATEGORY_FEATURE", new Maker< PessimisticCategoryBuilder >())
This feature assigns to each L-Block the same category, that is, ALWAYS_MISS as a default.
The assigned category can be changed using DEFAULT_CAT. It is basically used to provide a pessimistic analysis of the instruction cache.
Providing this feature implies providing also ICACHE_CATEGORY2_FEATURE.
Configuration:
DEFAULT_CAT
Default implementation: PessimisticCategoryBuilder