Otawa: otawa::clp Namespace Reference
otawa::clp Namespace Reference
Classes
class Analysis
class ClpStatePack
A pack of CLP states inside a BasicBlock.
class Manager
This class allows to exploit the result of a CLP analysis.
class State
The abstract state of the computer (abstract domain).
class Value
A set of values represented by a Circular Linear Progression.
Typedefs
typedef elm::t::int32 intn_t
typedef elm::t::uint32 uintn_t
typedef t::uint64 STAT_UINT
Enumerations
enum kind_t { NONE, REG, VAL, ALL }
Allowed types for values: NONE represents nothing; REG is only used for addresses, and represents a register; VAL represents some values (either a constant or an interval); ALL is the Top element.
Functions
elm::io::Output & operator<< (elm::io::Output &out, const otawa::clp::Value &val)
long lcm (long a, long b)
Return the lcm of two long integers.
intn_t min (intn_t a, intn_t b)
Return the min with a signed comparison.
intn_t max (intn_t a, intn_t b)
Return the max with a signed comparison.
uintn_t umin (uintn_t a, uintn_t b)
Return the min with an unsigned comparison.
uintn_t umax (uintn_t a, uintn_t b)
Return the max with an usigned comparison.
io::Output & operator<< (io::Output &out, const State &state)
SilentFeature FEATURE ("otawa::clp::FEATURE", maker)
This features ensure that the clp analysis has been identified.
Identifier< clp::State > STATE_IN ("otawa::clp::STATE_IN")
Put on a basic block, it's the CLP state at the begining of the block.
Identifier< clp::State > STATE_OUT ("otawa::clp::STATE_OUT")
Put on a basic block, it's the CLP state at the end of the block.
Variables
const int NBITS = 32
const uintn_t UMAXn = elm::type_info<uintn_t>::max
const intn_t MAXn = elm::type_info<intn_t>::max
const intn_t MINn = elm::type_info<intn_t>::min
SilentFeature FEATURE
This features ensure that the clp analysis has been identified.
Identifier< clp::State > STATE_IN
Put on a basic block, it's the CLP state at the begining of the block.
Identifier< clp::State > STATE_OUT
Put on a basic block, it's the CLP state at the end of the block.
Typedef Documentation
typedef elm::t::int32 otawa::clp::intn_t
typedef t::uint64 otawa::clp::STAT_UINT
typedef elm::t::uint32 otawa::clp::uintn_t
Enumeration Type Documentation
enum otawa::clp::kind_t
Allowed types for values: NONE represents nothing; REG is only used for addresses, and represents a register; VAL represents some values (either a constant or an interval); ALL is the Top element.
Enumerator
NONE
REG
VAL
ALL
Function Documentation
long otawa::clp::lcm (long a, long b) inline
Return the lcm of two long integers.
Referenced by otawa::clp::Value::inter().
intn_t otawa::clp::max (intn_t a, intn_t b) inline
Return the max with a signed comparison.
Referenced by otawa::etime::ConfigSet::add(), otawa::ContextualLoopBound::addMax(), otawa::ContextualLoopBound::addTotal(), otawa::etime::EdgeTimeBuilder::applyWeightedSplit(), otawa::ContextualLoopBound::findMax(), otawa::ContextualLoopBound::findTotal(), otawa::WorkSpace::isCancelled(), otawa::MemArea::join(), otawa::ContextualLoopBound::lookMax(), otawa::MemArea::meet(), otawa::UnavailableFeatureException::message(), otawa::FlowFactLoader::onLoop(), otawa::sem::Printer::print(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::etime::ConfigSet::push(), otawa::FlowFactLoader::scanXLoop(), otawa::hard::Memory::worstAccess(), otawa::hard::Memory::worstReadAccess(), and otawa::hard::Memory::worstWriteAccess().
intn_t otawa::clp::min (intn_t a, intn_t b) inline
Return the min with a signed comparison.
Referenced by otawa::etime::EdgeTimeBuilder::applyFloppySplit(), otawa::etime::EdgeTimeBuilder::applyStrictSplit(), otawa::clp::Value::inter(), otawa::MemArea::join(), otawa::clp::Value::join(), otawa::MemArea::meet(), otawa::LiExeGraph::nodeEarliestTimes(), otawa::LiExeGraph::nodeLatestTimes(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::dcache::PERSProblem::Domain::set(), and otawa::etime::EdgeTimeBuilder::splitConfs().
elm::io::Output& otawa::clp::operator<< (elm::io::Output & out, const otawa::clp::Value & val) inline
References otawa::clp::Value::print().
io::Output& otawa::clp::operator<< (io::Output & out, const State & state)
References otawa::clp::Value::_or(), otawa::sem::inst::a, otawa::se::SymbExpr::a(), otawa::se::ADD, otawa::clp::Value::add(), otawa::se::ADDR_FILTERS, otawa::ProgItem::address(), otawa::Symbol::address(), otawa::Segment::address(), otawa::ot::address(), ALARM_STORE_TOP, ALL, otawa::clp::ClpStatePack::InstPack::append(), otawa::se::applyFilter(), otawa::sem::ASR, otawa::se::SECmp::asString(), otawa::sem::inst::b, otawa::se::SymbExpr::b(), otawa::dfa::Value::base(), otawa::cfgio::bb(), otawa::etime::BRANCH, otawa::cfgio::cfg(), otawa::clp::State::clear(), otawa::se::CMP, otawa::se::CMPU, otawa::Address::compare(), otawa::sem::inst::cond(), otawa::sem::CONT, otawa::se::SECmp::copy(), otawa::dfa::Value::count(), otawa::sem::inst::cst, otawa::sem::inst::d(), otawa::dfa::Value::delta(), otawa::clp::Value::delta(), otawa::Inst::dump(), otawa::cfgio::edge(), otawa::cfgio::entry(), FEATURE(), otawa::clp::State::Iter::id(), otawa::sem::IF, otawa::dfa::INITIAL_STATE_FEATURE, otawa::sem::INT16, otawa::sem::INT32, otawa::sem::INT8, otawa::clp::Value::isConst(), otawa::BasicBlock::isEnd(), otawa::sem::inst::jump(), otawa::Edge::kind(), otawa::clp::Value::kind(), otawa::sem::LOAD, otawa::LOOP_INFO_FEATURE, otawa::clp::Value::lower(), otawa::p::init::maker(), otawa::MAX_ITERATION, otawa::clp::Value::mtimes(), NONE, otawa::sem::NOP, otawa::Address::offset(), otawa::sem::inst::op, otawa::se::SymbExpr::op(), otawa::se::OR, otawa::hard::Register::platformNumber(), otawa::clp::State::print(), otawa::clp::Value::print(), proc(), otawa::Process::program(), REG, otawa::se::REG_FILTERS, otawa::p::require, otawa::sem::SCRATCH, otawa::Inst::semInsts(), otawa::sem::SET, otawa::clp::State::set(), otawa::sem::SETI, otawa::sem::SETP, otawa::sem::SHL, otawa::clp::Value::shl(), otawa::sem::SHR, otawa::clp::Value::shr(), otawa::Symbol::size(), otawa::Edge::source(), otawa::cfgio::source(), otawa::sem::inst::sr(), otawa::clp::Value::start(), STATE_IN(), STATE_OUT(), otawa::sem::STORE, otawa::sem::SUB, otawa::clp::Value::sub(), otawa::Edge::target(), TRACEA, TRACEI, TRACEP, TRACESI, TRACEU, otawa::sem::TRAP, otawa::sem::inst::type(), otawa::type(), otawa::sem::UINT16, otawa::sem::UINT32, otawa::sem::UINT8, UMAXn, VAL, otawa::se::SymbExpr::val(), and otawa::VIRTUALIZED_CFG_FEATURE.
uintn_t otawa::clp::umax (uintn_t a, uintn_t b) inline
Return the max with an usigned comparison.
Referenced by otawa::clp::Value::join().
uintn_t otawa::clp::umin (uintn_t a, uintn_t b) inline
Return the min with an unsigned comparison.
Variable Documentation
const intn_t otawa::clp::MAXn = elm::type_info<intn_t>::max
Referenced by otawa::clp::Value::ge(), otawa::clp::Value::le(), and otawa::clp::Value::PQValue().
const intn_t otawa::clp::MINn = elm::type_info<intn_t>::min
Referenced by otawa::clp::Value::le(), and otawa::clp::Value::PQValue().
const int otawa::clp::NBITS = 32
const uintn_t otawa::clp::UMAXn = elm::type_info<uintn_t>::max
Referenced by otawa::clp::Value::_and(), otawa::clp::Value::add(), otawa::clp::Value::ffwidening(), otawa::clp::Value::geu(), otawa::clp::Value::join(), operator<<(), otawa::clp::Value::shl(), otawa::clp::Value::shr(), and otawa::clp::Value::widening().