Otawa: otawa::gliss Namespace Reference
otawa::gliss Namespace Reference
Classes
class Info
This class provides access to the stay-behind GLISS data structures and code provided by the GLISS v2 utility used by some loaders.
Functions
Feature< NoProcessor > INFO_FEATURE ("otawa::gliss::INFO_FEATURE")
This feature that the current process has been built by a loader based on the GLISS tool.
Identifier< Info * > INFO ("otawa::gliss::INFO", 0)
This identifier allows to get the gliss::Info object from loader supporting it from a process generating it.
Variables
Feature< NoProcessor > INFO_FEATURE
This feature that the current process has been built by a loader based on the GLISS tool.
Identifier< Info * > INFO
This identifier allows to get the gliss::Info object from loader supporting it from a process generating it.
Function Documentation
Identifier<Info *> otawa::gliss::INFO ("otawa::gliss::INFO" , 0)
This identifier allows to get the gliss::Info object from loader supporting it from a process generating it.
Features
INFO_FEATURE
Hooks
Process
Referenced by otawa::gliss::Info::~Info().
Feature<NoProcessor> otawa::gliss::INFO_FEATURE ("otawa::gliss::INFO_FEATURE")
This feature that the current process has been built by a loader based on the GLISS tool.
This allows to have low-level access to GLISS primitives.
Properties
gliss::Info::ID
Referenced by otawa::gliss::Info::~Info().
Variable Documentation
Identifier<Info *> otawa::gliss::INFO("otawa::gliss::INFO", 0)
This identifier allows to get the gliss::Info object from loader supporting it from a process generating it.
Features
INFO_FEATURE
Hooks
Process
Referenced by otawa::gliss::Info::decode().
Feature<NoProcessor> otawa::gliss::INFO_FEATURE("otawa::gliss::INFO_FEATURE")
This feature that the current process has been built by a loader based on the GLISS tool.
This allows to have low-level access to GLISS primitives.
Properties
gliss::Info::ID
Referenced by otawa::gliss::Info::decode().