Otawa: otawa::display Namespace Reference
otawa::display Namespace Reference
Classes
class AbstractDrawer
Provides facilities to draw a graph.
class CFGAdapter
This adapter implements the otawa::concept::DiGraphWithNodeMap and allows to use apply the GenDrawer to a CFG.
class CFGDrawer
class CFGOutput
class Color
A color description.
class Decorator
A decorator is a concept that provides static functions used to display a graph.
class DefaultDecorator
Default decorator that just output the given edges and vertices.
class DisplayException
This exception is thrown during the display of a graph if there is an error.
class Driver
A driver provides facilities to display a graph.
class Edge
class Exception
class FillStyle
The style of a filled area.
class GenDrawer
A simple engine to draw graphs.
class GenGraphAdapter
class Graph
A graph provides facilities to display a graph.
class GraphVizDriver
class GraphVizEdge
class GraphVizGraph
class GraphVizGraphElement
class GraphVizItem
class GraphVizNode
class ILPSystemAddon
This class is an interface for ILPSystemDisplayer to add to its output specialized information about ILP variables and constraints generators.
class ILPSystemDisplayer
This processor may be used to generate an HTML output of an ILP system used to compute the WCET of a task.
class Item
This class is the base of Graph, Node and Edge.
class LineStyle
class Node
class Plugin
A plugin to provide driver to display graphs.
class ShapeStyle
Shape style.
class TextStyle
Description of the style of text.
Typedefs
typedef enum otawa::display::kind_t kind_t
typedef enum otawa::display::style_t style_t
typedef enum otawa::display::graphviz_layout_t graphviz_layout_t
Enumerations
enum kind_t {
OUTPUT_ANY = 0, OUTPUT_PS, OUTPUT_PDF, OUTPUT_PNG,
OUTPUT_GIF, OUTPUT_JPG, OUTPUT_SVG, OUTPUT_DOT,
OUTPUT_RAW_DOT
}
enum style_t {
STYLE_NONE = 0, STYLE_FILLED, STYLE_PLAIN, STYLE_DASHED,
STYLE_DOTTED, STYLE_BOLD
}
enum graphviz_layout_t {
LAYOUT_DOT, LAYOUT_RADIAL, LAYOUT_CIRCULAR, LAYOUT_UNDIRECTED_NEATO,
LAYOUT_UNDIRECTED_FDP
}
Functions
io::IntFormat hex2 (int v)
Identifier< AbstractIdentifier * > INCLUDE ("otawa::display::include")
Tells that the properties with the given identifier have to be printed.
Identifier< AbstractIdentifier * > EXCLUDE ("otawa::display::exclude")
Tells that the properties with the given identifier mustn't be printed.
Identifier< AbstractIdentifier * > DEFAULT ("otawa::display::default")
The value of the property must be either INCLUDE or EXCLUDE.
Identifier< elm::CString > BACKGROUND ("otawa::display::background")
Identifier of the background color.
Identifier< elm::CString > COLOR ("otawa::display::color")
Identifier of the drawing color (boxes, edges)
Identifier< int > STYLE ("otawa::display::style")
Identifier of the drawing style.
Identifier< elm::CString > FONT_COLOR ("otawa::display::text_color")
Identifier of the text color.
Identifier< int > FONT_SIZE ("otawa::display::text_size")
Identifier of the text size.
Identifier< elm::CString > FONT ("otawa::display::font_name")
Identifier of the font name.
Identifier< elm::CString > HREF ("otawa::display::href")
Identifier of the url of the link the object is pointing to.
Identifier< elm::String > TITLE ("otawa::display::title")
Identifier of the title of a node.
Identifier< elm::String > BODY ("otawa::display::body")
Identifier of the body of a node.
Identifier< int > SHAPE ("otawa::display::shape")
Identifier of a shape of a node.
Identifier< elm::String > LABEL ("otawa::display::label")
Identifier of a label of an edge.
Identifier< int > WEIGHT ("otawa::display::weight")
Identifier of a weight of an edge.
Driver * find (kind_t kind)
Find a driver by its output kind.
Identifier< kind_t > OUTPUT_KIND ("otawa::display::output_kind", OUTPUT_ANY)
Passed to the graph style of the Driver::newGraph() method, selects the kind of output.
Identifier< string > OUTPUT_PATH ("otawa::display::output_path","")
Passed to the graph style of the Driver::newGraph() method, selects the file to output to when the driver display in a file.
Identifier< int > GRAPHVIZ_LAYOUT ("otawa::display::graphviz_layout", LAYOUT_DOT)
Identifier for the dot layout.
String quoteSpecials (String str)
This function escapes all the special characters, and replaces the newlines by \l (left-align in dot)
String quoteNewlines (String str)
This function escapes the newlines in order to avoid giving the newline to DOT input.
Variables
Identifier< kind_t > OUTPUT_KIND
Passed to the graph style of the Driver::newGraph() method, selects the kind of output.
Identifier< string > OUTPUT_PATH
Passed to the graph style of the Driver::newGraph() method, selects the file to output to when the driver display in a file.
Identifier< AbstractIdentifier * > INCLUDE
Tells that the properties with the given identifier have to be printed.
Identifier< AbstractIdentifier * > EXCLUDE
Tells that the properties with the given identifier mustn't be printed.
Identifier< AbstractIdentifier * > DEFAULT
The value of the property must be either INCLUDE or EXCLUDE.
Identifier< elm::CString > BACKGROUND
Identifier of the background color.
Identifier< elm::CString > COLOR
Identifier of the drawing color (boxes, edges)
Identifier< int > STYLE
Identifier of the drawing style.
Identifier< elm::CString > FONT_COLOR
Identifier of the text color.
Identifier< elm::CString > & TEXT_COLOR = FONT_COLOR
Identifier of the text color.
Identifier< int > FONT_SIZE
Identifier of the text size.
Identifier< int > & TEXT_SIZE = FONT_SIZE
Identifier of the text size.
Identifier< elm::CString > FONT
Identifier of the font name.
Identifier< elm::CString > HREF
Identifier of the url of the link the object is pointing to.
Identifier< elm::String > TITLE
Identifier of the title of a node.
Identifier< elm::String > BODY
Identifier of the body of a node.
Identifier< int > SHAPE
Identifier of a shape of a node.
Identifier< int > WEIGHT
Identifier of a weight of an edge.
Identifier< elm::String > LABEL
Identifier of a label of an edge.
Driver & graphviz_driver = driver
The graphviz driver.
Identifier< int > GRAPHVIZ_LAYOUT
Identifier for the dot layout.
cstring exts []
Typedef Documentation
typedef enum otawa::display::graphviz_layout_t otawa::display::graphviz_layout_t
typedef enum otawa::display::kind_t otawa::display::kind_t
typedef enum otawa::display::style_t otawa::display::style_t
Enumeration Type Documentation
enum otawa::display::graphviz_layout_t
Enumerator
LAYOUT_DOT
LAYOUT_RADIAL
LAYOUT_CIRCULAR
LAYOUT_UNDIRECTED_NEATO
LAYOUT_UNDIRECTED_FDP
enum otawa::display::kind_t
Enumerator
OUTPUT_ANY
OUTPUT_PS
OUTPUT_PDF
OUTPUT_PNG
OUTPUT_GIF
OUTPUT_JPG
OUTPUT_SVG
OUTPUT_DOT
OUTPUT_RAW_DOT
enum otawa::display::style_t
Enumerator
STYLE_NONE
STYLE_FILLED
STYLE_PLAIN
STYLE_DASHED
STYLE_DOTTED
STYLE_BOLD
Function Documentation
Driver* otawa::display::find (kind_t kind)
Find a driver by its output kind.
Parameters
kind Kind of the output to produce.
Returns
Found driver.
References graphviz_driver, OUTPUT_ANY, OUTPUT_KIND, and OUTPUT_PATH.
Referenced by otawa::Property::getID(), and otawa::ContextualPath::Ref< T >::print().
Identifier<int> otawa::display::GRAPHVIZ_LAYOUT ("otawa::display::graphviz_layout" , LAYOUT_DOT)
Identifier for the dot layout.
Must be one of layout_t. Default is LAYOUT_DOT (standard directional graph, from up to down)
io::IntFormat otawa::display::hex2 (int v) inline
Referenced by otawa::display::Color::Color().
String otawa::display::quoteNewlines (String str)
This function escapes the newlines in order to avoid giving the newline to DOT input.
Referenced by otawa::display::GraphVizItem::attributes().
String otawa::display::quoteSpecials (String str)
This function escapes all the special characters, and replaces the newlines by \l (left-align in dot)
Referenced by otawa::display::GraphVizItem::printAttribute(), otawa::display::GraphVizGraphElement::printAttribute(), otawa::display::GraphVizNode::printOthersAttributes(), otawa::display::GraphVizEdge::printOthersAttributes(), and otawa::display::GraphVizGraph::printOthersAttributes().
Variable Documentation
cstring otawa::display::exts[]
Initial value:
= {
        "",
        "ps",
        "pdf",
        "png",
        "gif",
        "jpg",
        "svg",
        "dot"
}
Driver & otawa::display::graphviz_driver = driver
The graphviz driver.
Referenced by otawa::display::Driver::find(), and find().
Identifier<int> otawa::display::GRAPHVIZ_LAYOUT("otawa::display::graphviz_layout", LAYOUT_DOT)
Identifier for the dot layout.
Must be one of layout_t. Default is LAYOUT_DOT (standard directional graph, from up to down)
Referenced by otawa::display::GraphVizGraph::display().