Otawa: otawa::se Namespace Reference
otawa::se Namespace Reference
Classes
class FilterBuilder
class SEAdd
Addition.
class SEAddr
Memory reference.
class SECmp
Compare symbolic expression This class define three type of compare expression: condition (if): SECmp(operator, expression) undetermined compare: SECmp(CMP, exp1, exp2) determined compare: SECmp(operator, exp1, exp2)
class SEConst
Constants.
class SENeg
Negation.
class SEReg
Register.
class SymbExpr
Symbolic expression.
Typedefs
typedef clp::Value V
typedef struct otawa::se::path_t path_t
Enumerations
enum op_t {
NONE, CONST, ADDR, REG,
NEG, ADD, CMP, CMPU,
LE, LT, GE, GT,
EQ, NE, ULE, ULT,
UGE, UGT, OR
}
Defined operators.
Functions
void applyFilter (V &v, se::op_t cmp_op, V f)
Apply a filter on the value.
op_t reverse (op_t logop)
Identifier< Vector< SECmp * > > REG_FILTERS ("otawa::se::REG_FILTERS")
Identifier< Vector< SECmp * > > ADDR_FILTERS ("otawa::se::ADDR_FILTERS")
SECmp * getFilterForReg (SECmp *se, V reg, clp::ClpStatePack &pack, Inst *i, int sem, Vector< V > &used_reg, Vector< V > &used_addr)
SECmp * getFilterForAddr (SECmp *se, V addr, clp::ClpStatePack &pack, Inst *i, int sem, Vector< V > &used_reg, Vector< V > &used_addr)
Variables
Identifier< Vector< SECmp * > > REG_FILTERS
Identifier< Vector< SECmp * > > ADDR_FILTERS
Typedef Documentation
typedef struct otawa::se::path_t otawa::se::path_t
typedef clp::Value otawa::se::V
Enumeration Type Documentation
enum otawa::se::op_t
Defined operators.
Enumerator
NONE
CONST
ADDR
Constant.
REG
Memory reference.
NEG
Register.
ADD
Oposite of.
CMP
Addition.
CMPU
Undeterminate compare.
LE
Undeterminate unsigned compare.
Determinate compare:
LT
less or equal
GE
less than
GT
greater or equal
EQ
greater than
NE
equal
ULE
not equal
Unsigned forms:
ULT
UGE
UGT
OR
Function Documentation
Identifier<Vector<SECmp *> > otawa::se::ADDR_FILTERS ("otawa::se::ADDR_FILTERS")
void otawa::se::applyFilter (V & v, se::op_t cmp_op, V f)
Apply a filter on the value.
Parameters
v the CLP to be filtred
cmp_op compare operator
f CLP to filter with
References EQ, GE, otawa::clp::Value::ge(), otawa::clp::Value::geu(), GT, otawa::clp::Value::inter(), LE, otawa::clp::Value::le(), otawa::clp::Value::leu(), LT, NE, otawa::clp::Value::start(), otawa::clp::Value::stop(), otawa::clp::Value::swrap(), UGE, UGT, ULE, ULT, and otawa::clp::Value::uwrap().
Referenced by otawa::clp::operator<<().
SECmp* otawa::se::getFilterForAddr (SECmp * se, V addr, clp::ClpStatePack & pack, Inst * i, int sem, Vector< V > & used_reg, Vector< V > & used_addr)
References otawa::se::SymbExpr::a(), ADDR, otawa::ProgItem::address(), otawa::se::SECmp::asString(), otawa::se::SymbExpr::b(), otawa::se::SECmp::canonize(), CMPU, CONST, otawa::clp::State::get(), otawa::clp::Value::isConst(), otawa::se::SymbExpr::op(), otawa::clp::REG, otawa::se::SymbExpr::replace(), otawa::clp::ClpStatePack::state_before(), TRACEGF, and otawa::se::SymbExpr::val().
Referenced by otawa::se::FilterBuilder::makeFilters().
SECmp* otawa::se::getFilterForReg (SECmp * se, V reg, clp::ClpStatePack & pack, Inst * i, int sem, Vector< V > & used_reg, Vector< V > & used_addr)
References otawa::se::SymbExpr::a(), otawa::ProgItem::address(), otawa::se::SECmp::asString(), otawa::se::SymbExpr::b(), otawa::se::SECmp::canonize(), CMPU, CONST, otawa::clp::State::get(), otawa::clp::Value::isConst(), otawa::clp::Value::lower(), otawa::se::SymbExpr::op(), REG, otawa::clp::REG, otawa::se::SymbExpr::replace(), otawa::clp::ClpStatePack::state_before(), TRACEGF, and otawa::se::SymbExpr::val().
Referenced by otawa::se::FilterBuilder::makeFilters().
Identifier<Vector<SECmp *> > otawa::se::REG_FILTERS ("otawa::se::REG_FILTERS")
op_t otawa::se::reverse (op_t logop)
References GE, GT, LE, LT, UGE, UGT, ULE, and ULT.
Referenced by otawa::clp::Value::add(), otawa::se::SECmp::canonize(), and otawa::clp::Value::stop().
Variable Documentation
Identifier<Vector<SECmp *> > otawa::se::ADDR_FILTERS("otawa::se::ADDR_FILTERS")
Referenced by otawa::se::FilterBuilder::getFilters(), otawa::se::SECmp::logicalNot(), otawa::clp::operator<<(), and otawa::se::SECmp::SECmp().
Identifier<Vector<SECmp *> > otawa::se::REG_FILTERS("otawa::se::REG_FILTERS")
Referenced by otawa::se::FilterBuilder::getFilters(), otawa::se::SECmp::logicalNot(), otawa::clp::operator<<(), and otawa::se::SECmp::SECmp().