Otawa: otawa::ot Namespace Reference
otawa::ot Namespace Reference
Typedefs
typedef t::uint8 byte
typedef t::uint32 mask
typedef t::uint32 size
typedef t::int64 time
Functions
elm::io::IntFormat address (Address addr)
Build a format to display addresses.
Typedef Documentation
typedef t::uint8 otawa::ot::byte
typedef t::uint32 otawa::ot::mask
typedef t::uint32 otawa::ot::size
typedef t::int64 otawa::ot::time
Function Documentation
elm::io::IntFormat otawa::ot::address (Address addr)
Build a format to display addresses.
Parameters
addr Address to display.
Returns
Format to display the address.
References otawa::Address::offset().
Referenced by otawa::CFGBuilder::buildCFG(), otawa::hard::Memory::buses(), otawa::Segment::contains(), otawa::hard::Bank::contains(), otawa::ParamExeGraph::dump(), otawa::ParExeGraph::dump(), otawa::ParamExeGraph::dumpSimple(), otawa::CFG::format(), otawa::ccg::Problem::gen(), otawa::cat::CATProblem::gen(), otawa::display::CFGOutput::genBBLabel(), otawa::MemBlockMap< otawa::BasicBlock >::get(), otawa::VarTextDecoder::getInst(), otawa::MemArea::includes(), otawa::stack::Value::join(), otawa::MemArea::join(), makeAddress(), otawa::MemArea::meet(), otawa::MemArea::meets(), otawa::File::name(), otawa::dcache::BlockCollection::obtain(), otawa::display::CFGDrawer::onNode(), otawa::operator<<(), otawa::stack::operator<<(), otawa::clp::operator<<(), otawa::AccessedAddress::print(), otawa::Identifier< T >::print(), otawa::etime::StandardEventBuilder::processBB(), otawa::dcache::BlockBuilder::processBB(), otawa::FirstLastBuilder::processCFG(), otawa::BBProcessor::processCFG(), otawa::ccg::Builder::processLBlockSet(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), otawa::Process::program(), otawa::CFGProcessor::str(), otawa::pfg::BB::topAddress(), otawa::hard::Bank::topAddress(), otawa::FlowFactLoader::workSpace(), and otawa::sim::CacheDriver::~CacheDriver().