Otawa: otawa::ets Namespace Reference
otawa::ets Namespace Reference
Classes
class AbstractCacheState
This class is used to represent an abstract cache line state.
class ACSComputation
This processor is used to simule cache states.
class CacheFirstMissComputation
This processor is used for computing the First Misses accesses after the cache simulating.
class CacheHitComputation
This processor is used for computing the Hit accesses after the cache simulating.
class CacheMissComputation
This processor is used for computing the Miss accesses after the cache simulating.
class FlowFactLoader
This processor allows using extern flow facts in ETS.
class TrivialAstBlockTime
This processor is used for computing execution of ast blocks in a trivial way, that is, the multiplication of ast block instruction count by the pipeline depth.
class WCETComputation
This processor is used for computing the WCET with the Extended Timing Schema.
Functions
SilentFeature ACS_FEATURE ("otawa::ets::ACS_FEATURE", acs_maker)
Compute the Abstract Cache State at entry of each AST for L1 instruction cache.
Identifier< AbstractCacheState * > ACS ("otawa::ets::ACS", 0)
This identifier (AbstractCacheState *) is used for storing the abstract cache line for each node.
SilentFeature CACHE_FIRST_MISS_FEATURE ("otawa::ets::CACHE_FIRST_MISS_FEATURE", fmiss_maker)
Provide the computation of occurrences of first-misses of instruction cache.
Identifier< int > FIRST_MISSES ("otawa::ets::FIRST_MISSES", 0)
This identifier (int) is used for storing the number of first miss accesses for each node.
SilentFeature CACHE_HIT_FEATURE ("otawa::ets::CACHE_HIT_FEATURE", hit_maker)
Provided the computation of the number of hits for the L1 instruction cache.
Identifier< int > HITS ("otawa::ets::HITS",-1)
This identifier (int) is used for storing the number of hit accesses for each node.
SilentFeature CACHE_MISS_FEATURE ("otawa::ets::CACHE_MISS_FEATURE", miss_maker)
Provide the number of misses for a L1 instruction cache.
Identifier< int > MISSES ("otawa::ets::misses", 0)
This identifier (int) is used for storing the number of miss accesses for each node.
SilentFeature FLOWFACT_FEATURE ("otawa::ets::FLOWFACT_FEATURE", ff_maker)
Provide flow facts in the AST.
Identifier< int > LOOP_COUNT ("otawa::ets::LOOP_COUNT",-1)
This identifier (int) is used for storing the number of iteration for each loop of the program.
SilentFeature BLOCK_TIME_FEATURE ("otawa::ets::BLOCK_TIME_FEATURE", bt_maker)
Provide WCET for each AST.
SilentFeature WCET_FEATURE ("otawa::ets::WCET_FEATURE", w_maker)
Provide the WCET of a task using the ETS approach.
Identifier< int > WCET ("otawa::ets::wcet",-1)
Identifier of annotation (int) used for storing the WCET value in the ETS of the computed function.
Identifier< int > CONFLICTS ("otawa::ets::conflicts", 0)
This identifier (int) is used for storing the number of conflict accesses for each node.
Identifier< int > DEPTH ("otawa::ets::DEPTH", 5)
Depth of the pipeline for the code processor TrivialAstBlockTime.
Variables
SilentFeature ACS_FEATURE
Compute the Abstract Cache State at entry of each AST for L1 instruction cache.
Identifier< AbstractCacheState * > ACS
This identifier (AbstractCacheState *) is used for storing the abstract cache line for each node.
SilentFeature CACHE_FIRST_MISS_FEATURE
Provide the computation of occurrences of first-misses of instruction cache.
Identifier< int > FIRST_MISSES
This identifier (int) is used for storing the number of first miss accesses for each node.
SilentFeature CACHE_HIT_FEATURE
Provided the computation of the number of hits for the L1 instruction cache.
Identifier< int > HITS
This identifier (int) is used for storing the number of hit accesses for each node.
SilentFeature CACHE_MISS_FEATURE
Provide the number of misses for a L1 instruction cache.
Identifier< int > MISSES
This identifier (int) is used for storing the number of miss accesses for each node.
SilentFeature FLOWFACT_FEATURE
Provide flow facts in the AST.
Identifier< int > LOOP_COUNT
This identifier (int) is used for storing the number of iteration for each loop of the program.
SilentFeature BLOCK_TIME_FEATURE
Provide WCET for each AST.
SilentFeature WCET_FEATURE
Provide the WCET of a task using the ETS approach.
Identifier< int > WCET
Identifier of annotation (int) used for storing the WCET value in the ETS of the computed function.
Identifier< int > CONFLICTS
This identifier (int) is used for storing the number of conflict accesses for each node.
Identifier< int > DEPTH
Depth of the pipeline for the code processor TrivialAstBlockTime.
Function Documentation
Identifier<int> otawa::ets::CONFLICTS ("otawa::ets::conflicts" , 0)
This identifier (int) is used for storing the number of conflict accesses for each node.
Variable Documentation
Identifier<int> otawa::ets::CONFLICTS("otawa::ets::conflicts", 0)
This identifier (int) is used for storing the number of conflict accesses for each node.
Referenced by otawa::ets::ACSComputation::applyProcess(), otawa::ets::CacheMissComputation::computation(), and otawa::ets::ACSComputation::initialization().