Otawa: otawa::etime Namespace Reference
otawa::etime Namespace Reference
Classes
class Config
Represents a configuration for computing cost of a BB.
class ConfigSet
Set of configurations with the same or with a maximum of time.
class EdgeTimeBuilder
Compute execution time by edge using the parametric exegraph approach.
class Event
An event represents a time variation in the execution of an instruction.
class EventCollector
Collects variables linking events with blocks in ILP.
class StandardEventBuilder
Build standard events.
Typedefs
typedef enum otawa::etime::type_t type_t
Enumerations
enum kind_t {
NONE, FETCH, MEM, BRANCH,
STAGE, FU
}
enum occurrence_t { NEVER = 0, SOMETIMES = 1, ALWAYS = 2 }
enum type_t { EDGE, BLOCK }
Functions
io::Output & operator<< (io::Output &out, EdgeTimeBuilder::place_t p)
string maskToString (t::uint32 mask, int len)
Convert an event mask to a string.
p::feature EDGE_TIME_FEATURE ("otawa::etime::EDGE_TIME_FEATURE", new Maker< EdgeTimeBuilder >())
This feature ensures that block cost has been computed according to the context of edges.
Identifier< bool > RECORD_TIME ("otawa::etime::RECORD_TIME", false)
Configuration property of EDGE_TIME_FEATURE, if true, enable the production of LTS_TIME and HTS_OFFSET on the edge.
Identifier< ot::time > LTS_TIME ("otawa::etime::LTS_TIME",-1)
Produced only if the RECORD_TIME configuration is set, record for each edge the low-time-set maximum time in cycles.
Identifier< ot::time > HTS_OFFSET ("otawa::etime::HTS_OFFSET", 0)
Produced only if the RECORD_TIME configuration is set, record for each edge the difference between maximum time of low-time-set and the maximum time of high-time-set (in cycles).
Identifier< bool > PREDUMP ("otawa::etime::PREDUMP", false)
This property is used to configure the EDGE_TIME_FEATURE and ask to dump the generated execution graphs.
Identifier< int > EVENT_THRESHOLD ("otawa::etime::EVENT_THRESHOLD", 12)
This property is used to configure the EDGE_TIME_FEATURE and determine the maximum number of events to consider to time a block.
p::feature STANDARD_EVENTS_FEATURE ("otawa::etime::STANDARD_EVENTS_FEATURE", new Maker< StandardEventBuilder >())
This feature ensures that events of the following analyses has been hooked to the task basic blocks:
p::feature EVENTS_FEATURE ("otawa::etime::EVENTS_FEATURE", new Maker< StandardEventBuilder >())
This feature ensures that all timing events on pipeline has been recorded.
Identifier< Event * > EVENT ("otawa::etime::EVENT", 0)
Allows to hook an event to a basic block.
Variables
p::feature STANDARD_EVENTS_FEATURE
This feature ensures that events of the following analyses has been hooked to the task basic blocks:
p::feature EVENTS_FEATURE
This feature ensures that all timing events on pipeline has been recorded.
Identifier< Event * > EVENT
Allows to hook an event to a basic block.
Identifier< bool > PREDUMP
This property is used to configure the EDGE_TIME_FEATURE and ask to dump the generated execution graphs.
Identifier< int > EVENT_THRESHOLD
This property is used to configure the EDGE_TIME_FEATURE and determine the maximum number of events to consider to time a block.
Identifier< bool > RECORD_TIME
Configuration property of EDGE_TIME_FEATURE, if true, enable the production of LTS_TIME and HTS_OFFSET on the edge.
p::feature EDGE_TIME_FEATURE
This feature ensures that block cost has been computed according to the context of edges.
Identifier< ot::time > LTS_TIME
Produced only if the RECORD_TIME configuration is set, record for each edge the low-time-set maximum time in cycles.
Identifier< ot::time > HTS_OFFSET
Produced only if the RECORD_TIME configuration is set, record for each edge the difference between maximum time of low-time-set and the maximum time of high-time-set (in cycles).
Typedef Documentation
typedef enum otawa::etime::type_t otawa::etime::type_t
Enumeration Type Documentation
enum otawa::etime::kind_t
Enumerator
NONE
FETCH
MEM
BRANCH
STAGE
FU
enum otawa::etime::occurrence_t
Enumerator
NEVER
SOMETIMES
ALWAYS
enum otawa::etime::type_t
Enumerator
EDGE
BLOCK
Function Documentation
p::feature otawa::etime::EDGE_TIME_FEATURE ("otawa::etime::EDGE_TIME_FEATURE" , new Maker< EdgeTimeBuilder > ())
This feature ensures that block cost has been computed according to the context of edges.
Basically, this means that both the objective function and the constraint of events has been added to the ILP system.
Configuration
RECORD_TIME
Properties
LTS_TIME
HTS_OFFSET
Identifier<int> otawa::etime::EVENT_THRESHOLD ("otawa::etime::EVENT_THRESHOLD" , 12)
This property is used to configure the EDGE_TIME_FEATURE and determine the maximum number of events to consider to time a block.
If a value of n is passed, at most 2^n times will be computed and if a block gets a bigger number of events, it will be split.
Identifier<ot::time> otawa::etime::HTS_OFFSET ("otawa::etime::HTS_OFFSET" , 0)
Produced only if the RECORD_TIME configuration is set, record for each edge the difference between maximum time of low-time-set and the maximum time of high-time-set (in cycles).
Hooks
Edge
Identifier<ot::time> otawa::etime::LTS_TIME ("otawa::etime::LTS_TIME" , - 1)
Produced only if the RECORD_TIME configuration is set, record for each edge the low-time-set maximum time in cycles.
Hooks
Edge
string otawa::etime::maskToString (t::uint32 mask, int len)
Convert an event mask to a string.
Parameters
mask Event mask.
len Number of events.
Returns
String representing the event mask.
Referenced by otawa::etime::EdgeTimeBuilder::applyFloppySplit(), otawa::etime::EdgeTimeBuilder::applyStrictSplit(), and otawa::etime::EdgeTimeBuilder::applyWeightedSplit().
io::Output& otawa::etime::operator<< (io::Output & out, EdgeTimeBuilder::place_t p)
References otawa::etime::EdgeTimeBuilder::IN_PREFIX, and otawa::etime::EdgeTimeBuilder::IN_SIZE.
Identifier<bool> otawa::etime::PREDUMP ("otawa::etime::PREDUMP" , false)
This property is used to configure the EDGE_TIME_FEATURE and ask to dump the generated execution graphs.
Identifier<bool> otawa::etime::RECORD_TIME ("otawa::etime::RECORD_TIME" , false)
Configuration property of EDGE_TIME_FEATURE, if true, enable the production of LTS_TIME and HTS_OFFSET on the edge.
Variable Documentation
p::feature otawa::etime::EDGE_TIME_FEATURE("otawa::etime::EDGE_TIME_FEATURE", new Maker< EdgeTimeBuilder >())
This feature ensures that block cost has been computed according to the context of edges.
Basically, this means that both the objective function and the constraint of events has been added to the ILP system.
Configuration
RECORD_TIME
Properties
LTS_TIME
HTS_OFFSET
Referenced by otawa::etime::EdgeTimeBuilder::contributeConst(), and otawa::etime::EdgeTimeBuilder::make().
Identifier<int> otawa::etime::EVENT_THRESHOLD("otawa::etime::EVENT_THRESHOLD", 12)
This property is used to configure the EDGE_TIME_FEATURE and determine the maximum number of events to consider to time a block.
If a value of n is passed, at most 2^n times will be computed and if a block gets a bigger number of events, it will be split.
Referenced by otawa::etime::EdgeTimeBuilder::configure(), and otawa::etime::EdgeTimeBuilder::contributeConst().
Identifier<ot::time> otawa::etime::HTS_OFFSET("otawa::etime::HTS_OFFSET", 0)
Produced only if the RECORD_TIME configuration is set, record for each edge the difference between maximum time of low-time-set and the maximum time of high-time-set (in cycles).
Hooks
Edge
Referenced by otawa::etime::EdgeTimeBuilder::contributeConst(), and otawa::etime::EdgeTimeBuilder::contributeSplit().
Identifier<ot::time> otawa::etime::LTS_TIME("otawa::etime::LTS_TIME",-1)
Produced only if the RECORD_TIME configuration is set, record for each edge the low-time-set maximum time in cycles.
Hooks
Edge
Referenced by otawa::etime::EdgeTimeBuilder::contributeConst(), otawa::etime::EdgeTimeBuilder::contributeSplit(), and otawa::etime::EdgeTimeBuilder::genForOneCost().
Identifier<bool> otawa::etime::PREDUMP("otawa::etime::PREDUMP", false)
This property is used to configure the EDGE_TIME_FEATURE and ask to dump the generated execution graphs.
Referenced by otawa::etime::EdgeTimeBuilder::configure(), and otawa::etime::EdgeTimeBuilder::contributeConst().
Identifier<bool> otawa::etime::RECORD_TIME("otawa::etime::RECORD_TIME", false)
Configuration property of EDGE_TIME_FEATURE, if true, enable the production of LTS_TIME and HTS_OFFSET on the edge.
Referenced by otawa::etime::EdgeTimeBuilder::configure(), and otawa::etime::EdgeTimeBuilder::contributeConst().