Otawa: otawa::sim Namespace Reference
otawa::sim Namespace Reference
Classes
class AbstractCacheDriver
This is an abstract implementation of the cache driver allowing to customize only the cache replacement policy.
class BasicBlockDriver
This class is a simulator Driver that executes the instruction sequence found in a basic block.
class BBPathDriver
class CacheDriver
This class provides a simple interface to drive the cache management unit of a simulator.
class DirectMappedCacheDriver
This class provide a cache driver implementing direct mapped cache driver.
class Driver
This class is used to drive a simulator.
class Exception
Exception generated by a simulator.
class FIFOCacheDriver
This class provide a cache driver implementing a FIFO policy.
class LRUCacheDriver
This class provide a cache driver implementing the LRU replacement policy.
class Simulator
This class represents a plugin to use facilities provided by a simulator.
class State
This class represents a running simulator.
class TrivialSimulator
The trivial simulator is a simplistic simulator with a fixed execution time for each instruction (defined by otawa::sim::INSTRUCTION_TIME).
Functions
Identifier< bool > IS_FUNCTIONAL ("otawa::sim::IS_FUNCTIONAL")
If supported by the simulator, enable or disable the functional part.
Identifier< bool > IS_STRUCTURAL ("otawa::sim::IS_STRUCTURAL")
If supported by the simulator, enable or disable the structural part.
Identifier< bool > USE_MEMORY ("otawa::sim::USE_MEMORY", true)
Activate or unactivate the memory management.
Identifier< bool > USE_CONTROL ("otawa::sim::USE_CONTROL")
Activate or unactivate the control management.
Identifier< int > INSTRUCTION_TIME ("otawa::sim::instruction_time")
Instruction execution time.
Variables
Identifier< bool > IS_FUNCTIONAL
If supported by the simulator, enable or disable the functional part.
Identifier< bool > IS_STRUCTURAL
If supported by the simulator, enable or disable the structural part.
Identifier< bool > USE_MEMORY
Activate or unactivate the memory management.
Identifier< bool > USE_CONTROL
Activate or unactivate the control management.
Identifier< int > INSTRUCTION_TIME
Instruction execution time.
Function Documentation
Identifier<int> otawa::sim::INSTRUCTION_TIME ("otawa::sim::instruction_time")
Instruction execution time.
Default to 5.
Identifier<bool> otawa::sim::IS_FUNCTIONAL ("otawa::sim::IS_FUNCTIONAL")
If supported by the simulator, enable or disable the functional part.
Default to false.
Identifier<bool> otawa::sim::IS_STRUCTURAL ("otawa::sim::IS_STRUCTURAL")
If supported by the simulator, enable or disable the structural part.
Default to true.
Identifier<bool> otawa::sim::USE_CONTROL ("otawa::sim::USE_CONTROL")
Activate or unactivate the control management.
Default to false.
Identifier<bool> otawa::sim::USE_MEMORY ("otawa::sim::USE_MEMORY" , true)
Activate or unactivate the memory management.
Default to true.
Variable Documentation
Identifier<int> otawa::sim::INSTRUCTION_TIME("otawa::sim::instruction_time")
Instruction execution time.
Default to 5.
Referenced by otawa::sim::TrivialSimulator::instantiate().
Identifier<bool> otawa::sim::IS_FUNCTIONAL("otawa::sim::IS_FUNCTIONAL")
If supported by the simulator, enable or disable the functional part.
Default to false.
Referenced by otawa::sim::TrivialSimulator::instantiate().
Identifier<bool> otawa::sim::IS_STRUCTURAL("otawa::sim::IS_STRUCTURAL")
If supported by the simulator, enable or disable the structural part.
Default to true.
Identifier<bool> otawa::sim::USE_CONTROL("otawa::sim::USE_CONTROL")
Activate or unactivate the control management.
Default to false.
Referenced by otawa::sim::TrivialSimulator::instantiate().
Identifier<bool> otawa::sim::USE_MEMORY("otawa::sim::USE_MEMORY", true)
Activate or unactivate the memory management.
Default to true.
Referenced by otawa::sim::TrivialSimulator::instantiate(), otawa::tsim::BBTimeSimulator::setup(), and otawa::tsim::BBPath::simulate().