Otawa: otawa::sem Namespace Reference
otawa::sem Namespace Reference
Classes
class BBIter
This class is an iterator on the semantic instruction paths of a basic block.
class Block
A block represents a sequence of semantic instructions inst.
class inst
This structure class represents an instruction in the semantics representation of machine instruction.
class PathIter
This iterator allows easily to traverse all execution paths of a block of semantic instructions.
class Printer
Printer class for semantic instructions (resolve the generic register value to the their real platform name).
class StateIter
This class, based on BBIter, allows to traverse all semantic execution paths of a basic block while maintaining the consistency of the analysis state.
class StateManager
In DFA of OTAWA, intermediate state are only stored at basic block level.
Typedefs
typedef enum otawa::sem::opcode opcode
typedef enum otawa::sem::cond_t cond_t
typedef enum otawa::sem::type_t type_t
typedef int reg_t
typedef t::uint32 uint_t
typedef t::int32 int_t
typedef struct otawa::sem::inst inst
Enumerations
enum opcode {
NOP = 0, BRANCH, TRAP, CONT,
IF, LOAD, STORE, SCRATCH,
SET, SETI, SETP, CMP,
CMPU, ADD, SUB, SHL,
SHR, ASR, NEG, NOT,
AND, OR, XOR, MUL,
MULU, DIV, DIVU, MOD,
MODU, SPEC, MULH
}
enum cond_t {
NO_COND = 0, EQ, LT, LE,
GE, GT, ANY_COND = 8, NE,
ULT, ULE, UGE, UGT,
MAX_COND
}
enum type_t {
NO_TYPE = 0, INT8 = 1, INT16 = 2, INT32 = 3,
INT64 = 4, UINT8 = 5, UINT16 = 6, UINT32 = 7,
UINT64 = 8, FLOAT32 = 9, FLOAT64 = 10, MAX_TYPE = 11
}
enum { intmin = 0x80000000, intmax = 0x7fffffff, uintmin = 0, uintmax = 0xffffffff }
Functions
elm::io::Output & operator<< (elm::io::Output &out, inst i)
inst nop (void)
inst branch (uint_t to)
inst trap (void)
inst cont (void)
inst _if (cond_t c, reg_t s, uint_t j)
inst _if (uint_t c, reg_t s, uint_t j)
inst load (reg_t d, reg_t a, int t)
inst load (reg_t d, reg_t a, type_t t)
inst store (reg_t d, reg_t a, int t)
inst store (reg_t d, reg_t a, type_t t)
inst scratch (reg_t d)
inst set (reg_t d, reg_t a)
inst seti (reg_t d, uint_t cst)
inst setp (reg_t d, uint_t cst)
inst cmp (reg_t d, reg_t a, reg_t b)
inst cmpu (reg_t d, reg_t a, reg_t b)
inst add (reg_t d, reg_t a, reg_t b)
inst sub (reg_t d, reg_t a, reg_t b)
inst shl (reg_t d, reg_t a, reg_t b)
inst shr (reg_t d, reg_t a, reg_t b)
inst asr (reg_t d, reg_t a, reg_t b)
inst neg (reg_t d, reg_t a)
inst _not (reg_t d, reg_t a)
inst _and (reg_t d, reg_t a, reg_t b)
inst _or (reg_t d, reg_t a, reg_t b)
inst mul (reg_t d, reg_t a, reg_t b)
inst mulu (reg_t d, reg_t a, reg_t b)
inst div (reg_t d, reg_t a, reg_t b)
inst divu (reg_t d, reg_t a, reg_t b)
inst mod (reg_t d, reg_t a, reg_t b)
inst modu (reg_t d, reg_t a, reg_t b)
inst _xor (reg_t d, reg_t a, reg_t b)
inst spec (reg_t d, uint_t cst)
inst mulh (reg_t d, reg_t a, reg_t b)
elm::io::Output & operator<< (elm::io::Output &out, const Block &b)
cond_t invert (cond_t cond)
Invert the given condition.
int size (type_t type)
Get the size of the given type.
io::Output & operator<< (io::Output &out, type_t type)
io::Output & operator<< (io::Output &out, cond_t cond)
Typedef Documentation
typedef enum otawa::sem::cond_t otawa::sem::cond_t
typedef struct otawa::sem::inst otawa::sem::inst
typedef t::int32 otawa::sem::int_t
typedef enum otawa::sem::opcode otawa::sem::opcode
typedef int otawa::sem::reg_t
typedef enum otawa::sem::type_t otawa::sem::type_t
typedef t::uint32 otawa::sem::uint_t
Enumeration Type Documentation
anonymous enum
Enumerator
intmin
intmax
uintmin
uintmax
enum otawa::sem::cond_t
Enumerator
NO_COND
EQ
LT
LE
GE
GT
ANY_COND
NE
ULT
ULE
UGE
UGT
MAX_COND
enum otawa::sem::opcode
Enumerator
NOP
BRANCH
TRAP
CONT
IF
LOAD
STORE
SCRATCH
SET
SETI
SETP
CMP
CMPU
ADD
SUB
SHL
SHR
ASR
NEG
NOT
AND
OR
XOR
MUL
MULU
DIV
DIVU
MOD
MODU
SPEC
MULH
enum otawa::sem::type_t
Enumerator
NO_TYPE
INT8
INT16
INT32
INT64
UINT8
UINT16
UINT32
UINT64
FLOAT32
FLOAT64
MAX_TYPE
Function Documentation
inst otawa::sem::_and (reg_t d, reg_t a, reg_t b) inline
References AND.
Referenced by otawa::clp::Value::uwrap().
inst otawa::sem::_if (cond_t c, reg_t s, uint_t j) inline
References IF, and MAX_COND.
inst otawa::sem::_if (uint_t c, reg_t s, uint_t j) inline
References IF, and MAX_COND.
inst otawa::sem::_not (reg_t d, reg_t a) inline
References NOT.
inst otawa::sem::_or (reg_t d, reg_t a, reg_t b) inline
References OR.
Referenced by otawa::clp::Value::stop().
inst otawa::sem::_xor (reg_t d, reg_t a, reg_t b) inline
References XOR.
inst otawa::sem::add (reg_t d, reg_t a, reg_t b) inline
References ADD.
Referenced by otawa::AlternativeProcessor::AlternativeSet::add(), otawa::graph::Graph::addAll(), otawa::DelayedBuilder::cloneEdge(), otawa::Identifier< otawa::arm::Info * >::defaultValue(), otawa::ilp::Expression::Expression(), otawa::DelayedBuilder::insert(), otawa::LBlockSet::Iterator::Iterator(), otawa::ccg::LBlockSet::Iterator::Iterator(), otawa::graph::Graph::Iterator::Iterator(), otawa::script::Script::makeConfig(), otawa::se::FilterBuilder::makeFilters(), otawa::dfa::BitSet::operator+=(), otawa::dfa::BitSet::operator|=(), otawa::CFGCollector::processWorkSpace(), otawa::Inst::readRegSet(), otawa::Identifier< T >::set(), otawa::etime::EdgeTimeBuilder::sortEvents(), otawa::clp::Value::stop(), otawa::ilp::Expression::sub(), otawa::clp::Value::sub(), otawa::dfa::hai::HalfAbsInt< FixPoint >::tryAddToWorkList(), otawa::Virtualizer::virtualize(), and otawa::Inst::writeRegSet().
inst otawa::sem::asr (reg_t d, reg_t a, reg_t b) inline
References ASR.
inst otawa::sem::branch (uint_t to) inline
References BRANCH.
Referenced by otawa::hard::PipelineUnit::Make::do_branch(), otawa::se::FilterBuilder::getFilters(), otawa::hard::PipelineUnit::isBranch(), and set().
inst otawa::sem::cmp (reg_t d, reg_t a, reg_t b) inline
References CMP.
Referenced by otawa::se::FilterBuilder::makeFilters().
inst otawa::sem::cmpu (reg_t d, reg_t a, reg_t b) inline
References CMPU.
inst otawa::sem::cont (void) inline
References CONT.
Referenced by otawa::ParamExeGraph::analyzeContentions(), otawa::LiExeGraph::nodeEarliestTimes(), otawa::LiExeGraph::nodeLatestTimes(), otawa::tsim::Delta::processCFG(), otawa::ccg::ConstraintBuilder::processLBlockSet(), and otawa::sem::PathIter::start().
inst otawa::sem::div (reg_t d, reg_t a, reg_t b) inline
References otawa::DIV.
Referenced by otawa::ilp::Expression::sub().
inst otawa::sem::divu (reg_t d, reg_t a, reg_t b) inline
References DIVU.
inst otawa::sem::load (reg_t d, reg_t a, int t) inline
References LOAD.
Referenced by otawa::hard::Memory::buses(), otawa::stack::operator<<(), and otawa::Loader::~Loader().
inst otawa::sem::load (reg_t d, reg_t a, type_t t) inline
References LOAD.
inst otawa::sem::mod (reg_t d, reg_t a, reg_t b) inline
References MOD.
inst otawa::sem::modu (reg_t d, reg_t a, reg_t b) inline
References MODU.
inst otawa::sem::mul (reg_t d, reg_t a, reg_t b) inline
References otawa::MUL.
Referenced by otawa::ilp::Expression::sub().
inst otawa::sem::mulh (reg_t d, reg_t a, reg_t b) inline
References MULH.
inst otawa::sem::mulu (reg_t d, reg_t a, reg_t b) inline
References MULU.
inst otawa::sem::neg (reg_t d, reg_t a) inline
References NEG.
Referenced by otawa::etime::EdgeTimeBuilder::applyFloppySplit(), otawa::etime::EdgeTimeBuilder::applyStrictSplit(), otawa::etime::EdgeTimeBuilder::applyWeightedSplit(), otawa::ilp::System::dumpLPSolve(), otawa::etime::ConfigSet::isFeasible(), otawa::SymAddress::parse(), and otawa::etime::ConfigSet::pop().
inst otawa::sem::nop (void) inline
References NOP.
Referenced by otawa::DelayedBuilder::buildEdges(), and otawa::DelayedBuilder::makeNOp().
elm::io::Output& otawa::sem::operator<< (elm::io::Output & out, inst i) inline
References otawa::sem::inst::print().
elm::io::Output& otawa::sem::operator<< (elm::io::Output & out, const Block & b) inline
References otawa::sem::Block::print().
io::Output & otawa::sem::operator<< (io::Output & out, type_t type)
References MAX_TYPE, and otawa::type().
io::Output & otawa::sem::operator<< (io::Output & out, cond_t cond)
References MAX_COND.
inst otawa::sem::scratch (reg_t d) inline
References SCRATCH.
inst otawa::sem::set (reg_t d, reg_t a) inline
References SET.
Referenced by otawa::dcache::CATBuilder::cleanup().
inst otawa::sem::seti (reg_t d, uint_t cst) inline
References otawa::sem::inst::args, otawa::sem::inst::cst, and SETI.
inst otawa::sem::setp (reg_t d, uint_t cst) inline
References otawa::sem::inst::args, otawa::sem::inst::cst, and SETP.
inst otawa::sem::shl (reg_t d, reg_t a, reg_t b) inline
References SHL.
Referenced by otawa::clp::Value::stop().
inst otawa::sem::shr (reg_t d, reg_t a, reg_t b) inline
References SHR.
Referenced by otawa::clp::Value::stop().
inst otawa::sem::spec (reg_t d, uint_t cst) inline
References otawa::sem::inst::args, otawa::sem::inst::cst, and SPEC.
inst otawa::sem::store (reg_t d, reg_t a, int t) inline
References STORE.
Referenced by otawa::AccessedAddress::isLoad(), otawa::AccessedAddress::isStore(), and otawa::display::ILPSystemDisplayer::processWorkSpace().
inst otawa::sem::store (reg_t d, reg_t a, type_t t) inline
References STORE.
inst otawa::sem::sub (reg_t d, reg_t a, reg_t b) inline
References SUB.
Referenced by otawa::se::FilterBuilder::makeFilters(), otawa::clp::Value::stop(), and otawa::ilp::Expression::sub().
inst otawa::sem::trap (void) inline
References TRAP.