Otawa: elm::serial2 Namespace Reference
elm::serial2 Namespace Reference
Functions
void __serialize (elm::serial2::Serializer &serializer, const otawa::Address &address)
void __unserialize (elm::serial2::Unserializer &serializer, otawa::Address &address)
void __unserialize (Unserializer &s, otawa::hard::Dispatch::type_t &v)
void __serialize (Serializer &s, otawa::hard::Dispatch::type_t v)
void __unserialize (serial2::Unserializer &serializer, otawa::Address &address)
Function Documentation
void elm::serial2::__serialize (elm::serial2::Serializer & serializer, const otawa::Address & address)
References otawa::Address::offset(), and otawa::Address::page().
void elm::serial2::__serialize (Serializer & s, otawa::hard::Dispatch::type_t v)
Referenced by otawa::hard::Stage::select().
void elm::serial2::__unserialize (elm::serial2::Unserializer & serializer, otawa::Address & address)
Referenced by __unserialize().
void elm::serial2::__unserialize (Unserializer & s, otawa::hard::Dispatch::type_t & v)
References __unserialize(), otawa::Inst::IS_ALU, otawa::Inst::IS_CALL, otawa::Inst::IS_COND, otawa::Inst::IS_CONTROL, otawa::Inst::IS_DIV, otawa::Inst::IS_FLOAT, otawa::Inst::IS_INT, otawa::Inst::IS_INTERN, otawa::Inst::IS_LOAD, otawa::Inst::IS_MEM, otawa::Inst::IS_MUL, otawa::Inst::IS_RETURN, otawa::Inst::IS_SHIFT, otawa::Inst::IS_STORE, otawa::Inst::IS_TRAP, and VALUE().
Referenced by otawa::hard::Stage::select().
void elm::serial2::__unserialize (serial2::Unserializer & serializer, otawa::Address & address)