Otawa: otawa::cfgio Namespace Reference
otawa::cfgio Namespace Reference
Classes
class Output
Output the current CFG collection in XML matching the DTA ${OTAWA_HOME}/share/Otawa/dtd/cfg.dtd .
Enumerations
enum entity_t {
_NONE, _COLL, _CFG, _ENTRY,
_BB, _EXIT, _EDGE
}
Functions
dtd::IDAttr id ("id", dtd::STRICT|dtd::REQUIRED)
dtd::IntAttr address ("address", dtd::STRICT|dtd::REQUIRED)
dtd::IntAttr size ("size", dtd::STRICT|dtd::REQUIRED)
dtd::RefAttr< BasicBlock * > source ("source", dtd::STRICT|dtd::REQUIRED)
dtd::RefAttr< BasicBlock * > target ("target", dtd::STRICT|dtd::REQUIRED)
dtd::RefAttr< CFG * > called ("called", dtd::STRICT)
dtd::Element entry (dtd::make("entry", _ENTRY).attr(id))
dtd::Element bb (dtd::make("bb", _BB).attr(id).attr(address).attr(size))
dtd::Element exit (dtd::make("exit", _EXIT).attr(id))
dtd::Element edge (dtd::make("edge", _EDGE).attr(source).attr(target).attr(called))
dtd::Element cfg (dtd::make("cfg", _CFG).attr(id).content((entry,*bb, exit,*edge)))
dtd::Element cfg_collection (dtd::make("cfg-collection", _COLL).content((cfg,*cfg)))
Identifier< Path > FROM ("otawa::cfgio::FROM")
Variables
Identifier< Path > FROM
Enumeration Type Documentation
enum otawa::cfgio::entity_t
Enumerator
_NONE
_COLL
_CFG
_ENTRY
_BB
_EXIT
_EDGE
Function Documentation
dtd::IntAttr otawa::cfgio::address ("address" , dtd::STRICT|dtd::REQUIRED)
dtd::Element otawa::cfgio::bb (dtd::make("bb", _BB).attr(id).attr(address).attr(size))
Referenced by otawa::pfg::PFG::add(), otawa::PFGBuilder::addFunction(), otawa::CFGBuilder::addSubProgram(), otawa::GraphBBTime< G >::analyzePathContext(), otawa::BBCleaner::BBCleaner(), otawa::DelayedBuilder::buildBB(), otawa::CFGBuilder::buildCFG(), otawa::DelayedBuilder::buildEdges(), otawa::cat::CATBuilder::buildLBLOCKSET(), otawa::cat::CATConstraintBuilder::buildLBLOCKSET(), otawa::BBStatCollector::cfg(), otawa::VirtualCFG::cfg(), otawa::BBCleaner::clean(), otawa::dcache::CATBuilder::cleanup(), otawa::EdgeProcessor::cleanupCFG(), otawa::BBProcessor::cleanupCFG(), otawa::CFGInfo::clear(), otawa::dfa::IterativeDFA< Problem, Set, Iter >::compute(), otawa::PSTBuilder::depthFirstSearch(), otawa::ParExeGraph::dump(), otawa::ccg::Problem::empty(), otawa::cat::CATProblem::empty(), otawa::CFGCollection::BBIterator::ended(), otawa::dcache::MUSTPERS::equals(), otawa::MUSTPERS::equals(), otawa::dcache::MUSTProblem::equals(), otawa::dcache::MAYProblem::equals(), otawa::dcache::PERSProblem::equals(), otawa::MUSTBranch::equals(), otawa::MAYProblem::equals(), otawa::MUSTProblem::equals(), otawa::MAYBranch::equals(), otawa::PERSProblem::equals(), otawa::PERSBranch::equals(), otawa::BranchProblem::equals(), otawa::GraphBBTime< G >::FillSequence(), otawa::CFGInfo::findCFG(), otawa::CFG::firstInst(), otawa::SubCFGBuilder::floodBackward(), otawa::SubCFGBuilder::floodForward(), otawa::dfa::XCFGVisitor< P >::gen(), otawa::ccg::Problem::gen(), otawa::ipet::ConstraintLoader::getBB(), otawa::tsim::BBPath::getBBPath(), otawa::PSTBuilder::getVCFG(), otawa::dfa::hai::FirstUnrollingFixPoint< Listener >::init(), otawa::clp::Manager::isEnded(), otawa::CFGCollection::BBIterator::item(), otawa::dfa::IterativeDFA< Problem, Set, Iter >::IterativeDFA(), otawa::display::CFGDrawer::make(), makeAddress(), otawa::DelayedBuilder::mark(), otawa::Dominance::markLoopHeaders(), otawa::ipet::ConstraintLoader::newBBVar(), otawa::dfa::hai::DefaultFixPoint< Listener >::newState(), otawa::sem::PathIter::next(), otawa::CFGCollection::BBIterator::next(), otawa::tsim::BBPath::nexts(), otawa::display::CFGDrawer::onNode(), otawa::tsim::operator<<(), otawa::stack::operator<<(), otawa::dcache::operator<<(), otawa::clp::operator<<(), otawa::CFGCollection::BBIterator::operator=(), otawa::dfa::XCFGVisitor< P >::preserve(), otawa::dcache::DirtyManager::t::print(), otawa::ParamExeGraphBBTime::processBB(), otawa::ipet::FlowFactLoader::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::etime::StandardEventBuilder::processBB(), otawa::LiExeGraphBBTime::processBB(), otawa::CFGNormalizer::processCFG(), otawa::PCGBuilder::processCFG(), otawa::Dominance::processCFG(), otawa::CFGCheckSummer::processCFG(), otawa::EdgeProcessor::processCFG(), otawa::BBStatCollector::processCFG(), otawa::FirstLastBuilder::processCFG(), otawa::tsim::Delta::processCFG(), otawa::ContextualProcessor::processCFG(), otawa::BBProcessor::processCFG(), otawa::dcache::CATBuilder::processLBlockSet(), otawa::ACSMayBuilder::processLBlockSet(), otawa::cat::CATConstraintBuilder::processLBlockSet(), otawa::ACSBuilder::processLBlockSet(), otawa::ccg::Builder::processLBlockSet(), otawa::dcache::ACSMayBuilder::processLBlockSet(), otawa::dcache::ACSBuilder::processLBlockSet(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), otawa::PFGBuilder::processWorkSpace(), otawa::ACSMayBuilder::processWorkSpace(), otawa::LoopReductor::processWorkSpace(), otawa::StackAnalysis::processWorkSpace(), otawa::CFGCollector::processWorkSpace(), otawa::branch::BranchBuilder::processWorkSpace(), otawa::SubCFGBuilder::processWorkSpace(), otawa::ACSBuilder::processWorkSpace(), otawa::dcache::ACSMayBuilder::processWorkSpace(), otawa::dcache::ACSBuilder::processWorkSpace(), otawa::LoopReductor::reduce(), otawa::CFG::scan(), otawa::bpred::BPredProcessor::setBit(), otawa::CachePenalty::setHeader(), otawa::sem::PathIter::start(), otawa::SubCFGBuilder::SubCFGBuilder(), otawa::CFGBuilder::thisBB(), otawa::BBStatCollector::total(), otawa::LoopUnroller::unroll(), otawa::stack::Manager::updatePath(), otawa::VirtualCFG::virtualize(), otawa::Virtualizer::virtualize(), otawa::cat::CATBuilder::worst(), otawa::dfa::XCFGVisitor< P >::XCFGVisitor(), otawa::CFG::~CFG(), otawa::dfa::hai::DefaultListener< P >::~DefaultListener(), otawa::dfa::hai::HalfAbsInt< FixPoint >::~HalfAbsInt(), otawa::dfa::hai::UnrollingListener< P >::~UnrollingListener(), otawa::dfa::hai::WideningFixPoint< Listener >::~WideningFixPoint(), and otawa::dfa::hai::WideningListener< P >::~WideningListener().
dtd::RefAttr<CFG *> otawa::cfgio::called ("called" , dtd::STRICT)
Referenced by otawa::cfgio::Output::processBB(), otawa::ipet::BasicConstraintsBuilder::processBB(), otawa::VirtualCFG::virtualize(), otawa::Virtualizer::virtualize(), and otawa::dfa::XCFGVisitor< P >::XCFGVisitor().
dtd::Element otawa::cfgio::cfg (dtd::make("cfg", _CFG).attr(id).content((entry,*bb, exit,*edge)))
Referenced by otawa::CFGBuilder::addCFG(), otawa::BBCleaner::BBCleaner(), otawa::display::CFGDrawer::CFGDrawer(), otawa::CFGCollector::configure(), otawa::dfa::hai::DefaultListener< P >::DefaultListener(), otawa::ccg::Problem::empty(), otawa::cat::CATProblem::empty(), otawa::dfa::XCFGVisitor< P >::gen(), otawa::SESERegion::getCFG(), makeAddress(), otawa::CFGCollection::BBIterator::next(), otawa::clp::operator<<(), otawa::CFGCollection::BBIterator::operator=(), otawa::dfa::XCFGVisitor< P >::preserve(), otawa::dcache::DirtyManager::t::print(), otawa::PCGBuilder::processCFG(), otawa::ACSMayBuilder::processLBlockSet(), otawa::ACSBuilder::processLBlockSet(), otawa::cat::CATBuilder::processLBlockSet(), otawa::ccg::Builder::processLBlockSet(), otawa::dcache::ACSMayBuilder::processLBlockSet(), otawa::dcache::ACSBuilder::processLBlockSet(), otawa::PCGBuilder::processWorkSpace(), otawa::DeadCodeAnalysis::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), otawa::ACSMayBuilder::processWorkSpace(), otawa::LoopReductor::processWorkSpace(), otawa::LoopUnroller::processWorkSpace(), otawa::StackAnalysis::processWorkSpace(), otawa::CFGCollector::processWorkSpace(), otawa::branch::BranchBuilder::processWorkSpace(), otawa::ACSBuilder::processWorkSpace(), otawa::ipet::BasicConstraintsBuilder::processWorkSpace(), otawa::clp::Analysis::processWorkSpace(), otawa::dcache::ACSMayBuilder::processWorkSpace(), otawa::dcache::ACSBuilder::processWorkSpace(), otawa::dfa::hai::UnrollingListener< P >::UnrollingListener(), otawa::stack::Manager::updatePath(), otawa::VirtualCFG::virtualize(), otawa::Virtualizer::virtualize(), otawa::dfa::hai::WideningListener< P >::WideningListener(), otawa::dfa::XCFGVisitor< P >::XCFGVisitor(), otawa::dfa::hai::DefaultListener< P >::~DefaultListener(), otawa::dfa::hai::UnrollingListener< P >::~UnrollingListener(), otawa::dfa::hai::WideningListener< P >::~WideningListener(), and otawa::dfa::XCFGVisitor< P >::~XCFGVisitor().
dtd::Element otawa::cfgio::cfg_collection (dtd::make("cfg-collection", _COLL).content((cfg,*cfg)))
dtd::Element otawa::cfgio::edge (dtd::make("edge", _EDGE).attr(source).attr(target).attr(called))
Referenced by otawa::GenGraph< ParamExeNode, otawa::ExeGraph::ExeEdge >::_(), otawa::ContextTree::addBB(), otawa::PathContext::addBlock(), otawa::CFG::address(), otawa::GraphBBTime< G >::analyzePathContext(), otawa::PSTBuilder::assignClasses(), otawa::DelayedBuilder::buildBB(), otawa::DelayedBuilder::buildEdges(), otawa::LiExeGraphBBTime::buildEpilogueList(), otawa::ParamExeGraphBBTime::buildPrologueList(), otawa::LiExeGraphBBTime::buildPrologueList(), otawa::PSTBuilder::buildTree(), otawa::EdgeProcessor::cleanupBB(), otawa::CFGInfo::clear(), otawa::graph::Graph::clear(), otawa::display::DefaultDecorator< G >::decorate(), otawa::LoopReductor::depthFirstSearch(), otawa::PSTBuilder::depthFirstSearch(), otawa::display::AbstractDrawer::draw(), otawa::display::AbstractDrawer::Edge::Edge(), otawa::GraphBBTime< G >::FillSequence(), otawa::DelayedBuilder::fix(), otawa::display::GenDrawer< G, D >::GenDrawer(), otawa::BasicBlock::getNotTaken(), otawa::BasicBlock::getTaken(), otawa::graph::Graph::inDegree(), otawa::dfa::hai::FirstUnrollingFixPoint< Listener >::init(), otawa::pfg::BB::isBranch(), otawa::pfg::BB::isCall(), otawa::pfg::BB::isConditional(), otawa::pfg::BB::isControl(), otawa::pfg::BB::isMultiTarget(), otawa::graph::Graph::isPredecessorOf(), otawa::pfg::BB::isReturn(), otawa::graph::Graph::isSuccessorOf(), otawa::Edge::kindName(), otawa::display::CFGDrawer::make(), otawa::Dominance::markLoopHeaders(), otawa::display::GraphVizGraph::newEdge(), otawa::ipet::ConstraintLoader::newEdgeVar(), otawa::dfa::hai::DefaultFixPoint< Listener >::newState(), otawa::tsim::BBPath::nexts(), otawa::display::GenGraphAdapter< G >::Edge::operator->(), otawa::clp::operator<<(), otawa::graph::Graph::outDegree(), otawa::dfa::hai::HalfAbsInt< FixPoint >::outputProcessing(), otawa::ParExeGraph::Predecessor::Predecessor(), otawa::display::GraphVizGraph::printGraphData(), otawa::ipet::WCETCountRecorder::processBB(), otawa::ipet::CachePenaltiesObjectFunctionBuilder::processBB(), otawa::ParamExeGraphBBTime::processBB(), otawa::ipet::FlowFactLoader::processBB(), otawa::ipet::BasicObjectFunctionBuilder::processBB(), otawa::tsim::TimeDeltaObjectFunctionModifier::processBB(), otawa::cfgio::Output::processBB(), otawa::ipet::VarAssignment::processBB(), otawa::ipet::FlowFactConstraintBuilder::processBB(), otawa::CFGSaver::processBB(), otawa::ipet::BasicConstraintsBuilder::processBB(), otawa::CFGNormalizer::processCFG(), otawa::PCGBuilder::processCFG(), otawa::EdgeProcessor::processCFG(), otawa::BBStatCollector::processCFG(), otawa::ContextualProcessor::processCFG(), otawa::cat::CATConstraintBuilder::processLBlockSet(), otawa::ccg::ConstraintBuilder::processLBlockSet(), otawa::DeadCodeAnalysis::processWorkSpace(), otawa::SubCFGBuilder::processWorkSpace(), otawa::CFGCollector::processWorkSpace(), otawa::LoopReductor::reduce(), otawa::GenGraph< ParamExeNode, otawa::ExeGraph::ExeEdge >::remove(), otawa::graph::Graph::remove(), otawa::CFG::scan(), otawa::display::AbstractDrawer::Edge::setup(), otawa::display::CFGAdapter::Edge::sink(), otawa::display::GenGraphAdapter< G >::Edge::sink(), otawa::display::CFGAdapter::Edge::source(), otawa::display::GenGraphAdapter< G >::Edge::source(), otawa::ParExeGraph::Successor::Successor(), otawa::VirtualCFG::virtualize(), otawa::Virtualizer::virtualize(), otawa::dfa::XCFGVisitor< P >::visitPreds(), otawa::dfa::XCFGVisitor< P >::XCFGVisitor(), otawa::CFG::~CFG(), and otawa::dfa::hai::WideningFixPoint< Listener >::~WideningFixPoint().
dtd::Element otawa::cfgio::entry (dtd::make("entry", _ENTRY).attr(id))
Referenced by otawa::MemBlockMap< otawa::BasicBlock >::add(), otawa::DelayedBuilder::cloneEdge(), otawa::MemBlockMap< otawa::BasicBlock >::get(), otawa::DelayedBuilder::insert(), otawa::stack::operator<<(), otawa::clp::operator<<(), otawa::dcache::DirtyManager::t::print(), otawa::ipet::CachePenaltiesObjectFunctionBuilder::processBB(), otawa::cfgio::Output::processCFG(), otawa::ACSBuilder::processLBlockSet(), otawa::cat::CATConstraintBuilder::processLBlockSet(), otawa::CFGCollector::processWorkSpace(), and otawa::ipet::BasicConstraintsBuilder::processWorkSpace().
dtd::Element otawa::cfgio::exit (dtd::make("exit", _EXIT).attr(id))
Referenced by otawa::cfgio::Output::processCFG(), otawa::ccg::Builder::processLBlockSet(), otawa::VirtualCFG::virtualize(), and otawa::Virtualizer::virtualize().
dtd::IDAttr otawa::cfgio::id ("id" , dtd::STRICT|dtd::REQUIRED)
dtd::IntAttr otawa::cfgio::size ("size" , dtd::STRICT|dtd::REQUIRED)
Referenced by otawa::cfgio::Output::processBB().
dtd::RefAttr<BasicBlock *> otawa::cfgio::source ("source" , dtd::STRICT|dtd::REQUIRED)
Referenced by otawa::ccg::ConstraintBuilder::addConstraintHeader(), otawa::ExeGraph< N >::ExeEdge::ExeEdge(), otawa::DelayedBuilder::insert(), otawa::display::GraphVizGraph::newEdge(), otawa::clp::operator<<(), otawa::cfgio::Output::processBB(), otawa::ccg::ConstraintBuilder::processLBlockSet(), and otawa::FlowFactLoader::scanAddress().
dtd::RefAttr<BasicBlock *> otawa::cfgio::target ("target" , dtd::STRICT|dtd::REQUIRED)
Referenced by otawa::PFGBuilder::addFunction(), otawa::CFGBuilder::buildCFG(), otawa::DelayedBuilder::cloneEdge(), otawa::ExeGraph< N >::ExeEdge::ExeEdge(), otawa::PFGBuilder::finalizeBB(), otawa::DelayedBuilder::insert(), otawa::Inst::isBundleEnd(), makeAddress(), otawa::ast::ASTLoader::makeBlock(), otawa::display::GraphVizGraph::newEdge(), otawa::FlowFactLoader::onMultiBranch(), otawa::FlowFactLoader::onMultiCall(), otawa::cfgio::Output::processBB(), otawa::VarTextDecoder::processEntry(), otawa::ccg::ConstraintBuilder::processLBlockSet(), and otawa::FlowFactLoader::workSpace().