Otawa: otawa::hard Namespace Reference
otawa::hard Namespace Reference
Classes
class Bank
A bank in the memory.
class BHT
This class contains all information about the Branch History Predictor, that is,.
class Bus
A bus that tie together several memory banks.
class Cache
This class contains the configuration of a level of cache of processor.
class CacheConfiguration
This class represents the full configuration of caches of a processor.
class Dispatch
A dispatch object allows to map some kinds of instructions to a functional unit.
class Dumper
Dump to output the hardware configuration details.
class FunctionalUnit
A functional unit is specialized in the computation of some kinds of instructions.
class MeltedBank
A melted bank may contains registers with different sizes and kinds.
class Memory
Class to represent the whole memory of the platform.
class Mode
A working mode for the hardware memory.
class ModeTransition
Representation of a memory bank transition.
class PipelineUnit
A pipeline unit is microprocessor place that used to execute an instruction.
class PlainBank
A plain bank is a register bank whose registers have the same size and the same type.
class Platform
This class records information about the architecture where the processed program will run.
class Processor
Description of a processor pipeline.
class PureCache
class Queue
The instructions queues stores instruction that come from one stage to another one.
class RegBank
This class represents a bank of registers.
class Register
Objects of this class are simple machine register, more accurately unbreakable atomic registers.
class Stage
This class represents a stage in a pipeline.
class Step
An hardware step is a step or an action to perform inside the microprocessor to execute an instruction.
Functions
io::Output & operator<< (io::Output &out, const Platform::Identification &id)
elm::io::Output & operator<< (elm::io::Output &out, Register *reg)
p::feature BHT_FEATURE ("otawa::hard::BHT_FEATURE", new Maker< BHTGetter >())
This feature ensures that the BHT description has been loaded.
Identifier< BHT * > BHT_CONFIG ("otawa::hard::BHT_CONFIG", 0)
Gives the current BHT description.
SilentFeature MEMORY_FEATURE ("otawa::hard::MEMORY_FEATURE", maker)
This feature ensures we have obtained the memory configuration of the system.
Identifier< const Memory * > MEMORY ("otawa::hard::MEMORY",&Memory::full)
Current memory.
SilentFeature PROCESSOR_FEATURE ("otawa::hard::PROCESSOR_FEATURE", maker)
This feature ensures we have obtained the memory configuration of the system.
Identifier< const hard::Processor * > PROCESSOR ("otawa::hard::PROCESSOR",&Processor::null)
Configuration identifier to select the used processor.
Identifier< string > PROCESSOR_ID ("otawa::hard::PROCESSOR_ID")
Configuration identifier to select used processor from its identifier (possibly found in an external plugin).
SilentFeature CACHE_CONFIGURATION_FEATURE ("otawa::hard::CACHE_CONFIGURATION_FEATURE", maker)
This feature ensures we have obtained the cache configuration of the system.
Identifier< const CacheConfiguration * > CACHE_CONFIGURATION ("otawa::hard::CACHE_CONFIGURATION",&CacheConfiguration::NO_CACHE)
Current configuration.
FunAccessor< const Cache * > L1_ICACHE (l1_icache,"otawa::hard::L1_ICACHE")
Accessor on the instruction cache L1.
FunAccessor< const Cache * > L1_DCACHE (l1_dcache,"otawa::hard::L1_DCACHE")
Accessor on the data cache L1.
Variables
p::feature BHT_FEATURE
This feature ensures that the BHT description has been loaded.
Identifier< BHT * > BHT_CONFIG
Gives the current BHT description.
SilentFeature CACHE_CONFIGURATION_FEATURE
This feature ensures we have obtained the cache configuration of the system.
Identifier< const CacheConfiguration * > CACHE_CONFIGURATION
Current configuration.
FunAccessor< const Cache * > L1_ICACHE
Accessor on the instruction cache L1.
FunAccessor< const Cache * > L1_DCACHE
Accessor on the data cache L1.
SilentFeature MEMORY_FEATURE
This feature ensures we have obtained the memory configuration of the system.
Identifier< const Memory * > MEMORY
Current memory.
SilentFeature PROCESSOR_FEATURE
This feature ensures we have obtained the memory configuration of the system.
Identifier< const Processor * > PROCESSOR
Configuration identifier to select the used processor.
Identifier< string > PROCESSOR_ID
Configuration identifier to select used processor from its identifier (possibly found in an external plugin).
Function Documentation
Identifier<BHT*> otawa::hard::BHT_CONFIG ("otawa::hard::BHT_CONFIG" , 0)
Gives the current BHT description.
Hooks
configuration properties
WorkSpace
p::feature otawa::hard::BHT_FEATURE ("otawa::hard::BHT_FEATURE" , new Maker< BHTGetter > ())
This feature ensures that the BHT description has been loaded.
Properties
BHT_CONFIG
Identifier<const CacheConfiguration *> otawa::hard::CACHE_CONFIGURATION ("otawa::hard::CACHE_CONFIGURATION" , &CacheConfiguration::NO_CACHE)
Current configuration.
Hooks
otawa::WorkSpace
Features
otawa::CACHE_CONFIGURATION_FEATURE
Default Value
Cache configuration without any cache (never null).
SilentFeature otawa::hard::CACHE_CONFIGURATION_FEATURE ("otawa::hard::CACHE_CONFIGURATION_FEATURE" , maker)
This feature ensures we have obtained the cache configuration of the system.
Properties
otawa::CACHE_CONFIGURATION
Accessors
otawa::L1_ICACHE
otawa::L2_DCACHE
FunAccessor<const Cache *> otawa::hard::L1_DCACHE (l1_dcache , "otawa::hard::L1_DCACHE")
Accessor on the data cache L1.
Feature
otawa::CACHE_CONFIGURATION_FEATURE
FunAccessor<const Cache *> otawa::hard::L1_ICACHE (l1_icache , "otawa::hard::L1_ICACHE")
Accessor on the instruction cache L1.
Feature
otawa::CACHE_CONFIGURATION_FEATURE
Identifier<const Memory *> otawa::hard::MEMORY ("otawa::hard::MEMORY" , &Memory::full)
Current memory.
Hooks
otawa::WorkSpace
Features
otawa::CACHE_CONFIGURATION_FEATURE
Default Value
Cache configuration without any cache (never null).
SilentFeature otawa::hard::MEMORY_FEATURE ("otawa::hard::MEMORY_FEATURE" , maker)
This feature ensures we have obtained the memory configuration of the system.
Properties
otawa::hard::MEMORY
elm::io::Output& otawa::hard::operator<< (elm::io::Output & out, Register * reg) inline
References otawa::hard::Register::name().
io::Output& otawa::hard::operator<< (io::Output & out, const Platform::Identification & id) inline
Referenced by otawa::dcache::MAYProblem::leaveContext().
Identifier<const hard::Processor *> otawa::hard::PROCESSOR ("otawa::hard::PROCESSOR" , &Processor::null)
Configuration identifier to select the used processor.
Hooks
otawa::WorkSpace
Features
otawa::CACHE_CONFIGURATION_FEATURE
Default Value
Cache configuration without any cache (never null).
SilentFeature otawa::hard::PROCESSOR_FEATURE ("otawa::hard::PROCESSOR_FEATURE" , maker)
This feature ensures we have obtained the memory configuration of the system.
Properties
otawa::hard::PROCESSOR
otawa::hard::PROCESSOR_ID
Identifier<string> otawa::hard::PROCESSOR_ID ("otawa::hard::PROCESSOR_ID")
Configuration identifier to select used processor from its identifier (possibly found in an external plugin).
Variable Documentation
Identifier<BHT*> otawa::hard::BHT_CONFIG("otawa::hard::BHT_CONFIG", 0)
Gives the current BHT description.
Hooks
configuration properties
WorkSpace
Referenced by otawa::hard::BHT::getDefaultPrediction(), otawa::branch::CondNumber::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::branch::ConsBuilder::processBB(), otawa::branch::BranchBuilder::processWorkSpace(), otawa::branch::CondNumber::setup(), otawa::etime::StandardEventBuilder::setup(), and otawa::BranchProblem::update().
p::feature otawa::hard::BHT_FEATURE("otawa::hard::BHT_FEATURE", new Maker< BHTGetter >())
This feature ensures that the BHT description has been loaded.
Properties
BHT_CONFIG
Referenced by otawa::hard::BHT::getDefaultPrediction().
Identifier<const CacheConfiguration *> otawa::hard::CACHE_CONFIGURATION("otawa::hard::CACHE_CONFIGURATION",&CacheConfiguration::NO_CACHE)
Current configuration.
Hooks
otawa::WorkSpace
Features
otawa::CACHE_CONFIGURATION_FEATURE
Default Value
Cache configuration without any cache (never null).
Referenced by otawa::hard::CacheConfiguration::cacheName(), otawa::ipet::TrivialDataCacheManager::configure(), otawa::GraphBBTime< ParExeGraph >::configureMem(), otawa::dcache::operator<<(), otawa::ParExeGraph::ParExeGraph(), otawa::dcache::DirtyManager::t::print(), otawa::ipet::TrivialDataCacheManager::processBB(), otawa::CAT2Builder::processCFG(), otawa::FirstLastBuilder::processCFG(), otawa::cat::CATConstraintBuilder::processLBlockSet(), otawa::cat::CATBuilder::processLBlockSet(), otawa::ccg::ConstraintBuilder::processLBlockSet(), otawa::ccg::Builder::processLBlockSet(), otawa::LBlockProcessor::processWorkSpace(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), otawa::dcache::CATBuilder::processWorkSpace(), otawa::ACSMayBuilder::processWorkSpace(), otawa::LinkedBlocksDetector::processWorkSpace(), otawa::ets::ACSComputation::processWorkSpace(), otawa::cat::CATConstraintBuilder::processWorkSpace(), otawa::ACSBuilder::processWorkSpace(), otawa::cat::CATBuilder::processWorkSpace(), otawa::CAT2ConstraintBuilder::processWorkSpace(), otawa::ccg::ConstraintBuilder::processWorkSpace(), otawa::ccg::Builder::processWorkSpace(), otawa::dcache::ACSMayBuilder::processWorkSpace(), otawa::dcache::ACSBuilder::processWorkSpace(), otawa::ipet::TrivialInstCacheManager::setup(), otawa::dcache::CLPBlockBuilder::setup(), otawa::ccg::LBlockBuilder::setup(), otawa::LBlockBuilder::setup(), and otawa::dcache::BlockBuilder::setup().
SilentFeature otawa::hard::CACHE_CONFIGURATION_FEATURE("otawa::hard::CACHE_CONFIGURATION_FEATURE", maker)
This feature ensures we have obtained the cache configuration of the system.
Properties
otawa::CACHE_CONFIGURATION
Accessors
otawa::L1_ICACHE
otawa::L2_DCACHE
Referenced by otawa::hard::CacheConfiguration::cacheName(), otawa::operator<<(), otawa::dcache::DirtyManager::t::print(), otawa::ipet::TrivialDataCacheManager::processBB(), and otawa::CAT2Builder::processCFG().
FunAccessor<const Cache *> otawa::hard::L1_DCACHE(l1_dcache,"otawa::hard::L1_DCACHE")
Accessor on the data cache L1.
Feature
otawa::CACHE_CONFIGURATION_FEATURE
Referenced by otawa::hard::CacheConfiguration::cacheName().
FunAccessor<const Cache *> otawa::hard::L1_ICACHE(l1_icache,"otawa::hard::L1_ICACHE")
Accessor on the instruction cache L1.
Feature
otawa::CACHE_CONFIGURATION_FEATURE
Referenced by otawa::hard::CacheConfiguration::cacheName().
Identifier<const Memory *> otawa::hard::MEMORY("otawa::hard::MEMORY",&Memory::full)
Current memory.
Hooks
otawa::WorkSpace
Features
otawa::CACHE_CONFIGURATION_FEATURE
Default Value
Cache configuration without any cache (never null).
Referenced by otawa::GraphBBTime< ParExeGraph >::configureMem(), otawa::hard::Dumper::processWorkSpace(), otawa::dcache::WCETFunctionBuilder::setup(), otawa::dcache::CLPBlockBuilder::setup(), otawa::ccg::LBlockBuilder::setup(), otawa::LBlockBuilder::setup(), otawa::etime::StandardEventBuilder::setup(), otawa::dcache::BlockBuilder::setup(), otawa::clp::Analysis::setup(), and otawa::hard::Memory::worstWriteAccess().
SilentFeature otawa::hard::MEMORY_FEATURE("otawa::hard::MEMORY_FEATURE", maker)
This feature ensures we have obtained the memory configuration of the system.
Properties
otawa::hard::MEMORY
Referenced by otawa::GraphBBTime< G >::GraphBBTime(), and otawa::hard::Memory::worstWriteAccess().
Identifier<const hard::Processor *> otawa::hard::PROCESSOR("otawa::hard::PROCESSOR",&Processor::null)
Configuration identifier to select the used processor.
Hooks
otawa::WorkSpace
Features
otawa::CACHE_CONFIGURATION_FEATURE
Default Value
Cache configuration without any cache (never null).
Referenced by otawa::hard::Processor::instantiate(), otawa::ExeGraphBBTime< G >::processWorkSpace(), otawa::GraphBBTime< G >::processWorkSpace(), and otawa::hard::Stage::select().
SilentFeature otawa::hard::PROCESSOR_FEATURE("otawa::hard::PROCESSOR_FEATURE", maker)
This feature ensures we have obtained the memory configuration of the system.
Properties
otawa::hard::PROCESSOR
otawa::hard::PROCESSOR_ID
Referenced by otawa::GraphBBTime< G >::GraphBBTime(), otawa::hard::Processor::instantiate(), and otawa::hard::Stage::select().
Identifier<string> otawa::hard::PROCESSOR_ID("otawa::hard::PROCESSOR_ID")
Configuration identifier to select used processor from its identifier (possibly found in an external plugin).
Configuration identifier to select used processor from its identifier (possibly found in an external plugin).
Referenced by otawa::hard::Processor::instantiate(), otawa::Manager::prefixPath(), and otawa::hard::Stage::select().