Otawa: otawa::dfa Namespace Reference
otawa::dfa Namespace Reference
Namespaces
hai
Classes
class AbsIntLite
This class provides a light implementation for abstract interpretation.
class AbsIntLiteEx
class AbsIntLiteExtender
class BitSet
This class implements a set as a bit vector.
class FastState
Fast implementation of abstract domain on the functional state of a microprocessor including the registers and the memory content.
class IterativeDFA
This class provides a generic facility to implement iterative Data Flow Analysis (DFA) as presented in "Aho, Sethi, Ullman, Compilers: Principles, Techniques, and Tools, Addison Wesley 1986".
class MemCell
class Predecessor
This iterator is used to traverse forward a CFG in an iterative DFA analysis.
class State
Represents a value of the data state.
class Successor
This iterator is used to traverse backward a CFG in an iterative DFA analysis.
class Value
class XCFGVisitor
This class implements the visitor concept of XIterativeDFA class and allows applying an analysis on a collection of CFG in a flow-insensitive way.
class XIterativeDFA
The DFAEngine implements an extended Iterative Data Flow Algorithm, that is, it work on graphs with any forms.
Functions
elm::io::Output & operator<< (elm::io::Output &output, const BitSet &bits)
p::feature INITIAL_STATE_FEATURE ("otawa::dfa::INITIAL_STATE_FEATURE", new Maker< InitialStateBuilder >())
This feature ensures that the executable and user information have been parsed to make the initial state of the task.
Identifier< Pair< const hard::Register *, Value > > REG_INIT ("otawa::dfa::REG_INIT")
This configuration attribute allows to specify an initial value for a register.
Identifier< MemCell > MEM_INIT ("otawa::dfa::MEM_INIT")
This configuration attribute allows to specify an initial value for a memory cell.
Identifier< State * > INITIAL_STATE ("otawa::dfa::INITIAL_STATE", 0)
This attribute provides the initial state of the task.
Identifier< int > INDEX ("otawa::dfa::I",-1)
Identifier used for internal use.
Variables
Identifier< Pair< const hard::Register *, Value > > REG_INIT
This configuration attribute allows to specify an initial value for a register.
Identifier< MemCell > MEM_INIT
This configuration attribute allows to specify an initial value for a memory cell.
p::feature INITIAL_STATE_FEATURE
This feature ensures that the executable and user information have been parsed to make the initial state of the task.
Identifier< State * > INITIAL_STATE
This attribute provides the initial state of the task.
Identifier< int > INDEX
Identifier used for internal use.
Function Documentation
Identifier<int> otawa::dfa::INDEX ("otawa::dfa::I" , - 1)
Identifier used for internal use.
Identifier<State *> otawa::dfa::INITIAL_STATE ("otawa::dfa::INITIAL_STATE" , 0)
This attribute provides the initial state of the task.
Hook
WorkSpace
Feature
INITIAL_STATE_FEATURE
p::feature otawa::dfa::INITIAL_STATE_FEATURE ("otawa::dfa::INITIAL_STATE_FEATURE" , new Maker< InitialStateBuilder > ())
This feature ensures that the executable and user information have been parsed to make the initial state of the task.
Configuration
REG_INIT
MEM_INIT
Attributes
INITIAL_STATE
Identifier<MemCell> otawa::dfa::MEM_INIT ("otawa::dfa::MEM_INIT")
This configuration attribute allows to specify an initial value for a memory cell.
Implictely, it allows also to assign a type to the memory cell.
Feature
INITIAL_STATE_FEATURE
elm::io::Output& otawa::dfa::operator<< (elm::io::Output & output, const BitSet & bits) inline
References otawa::dfa::BitSet::contains(), and otawa::dfa::BitSet::size().
Identifier<Pair<const hard::Register *, Value> > otawa::dfa::REG_INIT ("otawa::dfa::REG_INIT")
This configuration attribute allows to specify an initial value for a register.
Feature
INITIAL_STATE_FEATURE
Variable Documentation
Identifier<int> otawa::dfa::INDEX("otawa::dfa::I",-1)
Identifier used for internal use.
Referenced by otawa::dfa::IterativeDFA< Problem, Set, Iter >::genSet(), otawa::dfa::XCFGVisitor< P >::index(), otawa::dfa::IterativeDFA< Problem, Set, Iter >::inSet(), otawa::dfa::IterativeDFA< Problem, Set, Iter >::IterativeDFA(), otawa::dfa::IterativeDFA< Problem, Set, Iter >::killSet(), otawa::dfa::IterativeDFA< Problem, Set, Iter >::outSet(), and otawa::dfa::XCFGVisitor< P >::XCFGVisitor().
Identifier<State *> otawa::dfa::INITIAL_STATE("otawa::dfa::INITIAL_STATE", 0)
This attribute provides the initial state of the task.
Hook
WorkSpace
Feature
INITIAL_STATE_FEATURE
Referenced by otawa::stack::operator<<(), otawa::clp::Analysis::processWorkSpace(), otawa::dfa::State::record(), and otawa::FlowFactLoader::setup().
p::feature otawa::dfa::INITIAL_STATE_FEATURE("otawa::dfa::INITIAL_STATE_FEATURE", new Maker< InitialStateBuilder >())
This feature ensures that the executable and user information have been parsed to make the initial state of the task.
Configuration
REG_INIT
MEM_INIT
Attributes
INITIAL_STATE
Referenced by otawa::clp::operator<<(), otawa::dfa::State::record(), and otawa::StackAnalysis::StackAnalysis().
Identifier<MemCell> otawa::dfa::MEM_INIT("otawa::dfa::MEM_INIT")
This configuration attribute allows to specify an initial value for a memory cell.
Implictely, it allows also to assign a type to the memory cell.
Feature
INITIAL_STATE_FEATURE
Referenced by otawa::dfa::State::record().
Identifier<Pair<const hard::Register *, Value> > otawa::dfa::REG_INIT("otawa::dfa::REG_INIT")
This configuration attribute allows to specify an initial value for a register.
Feature
INITIAL_STATE_FEATURE
Referenced by otawa::dfa::State::record().