Otawa: otawa::ipet Namespace Reference
otawa::ipet Namespace Reference
Classes
class BasicConstraintsBuilder
class BasicObjectFunctionBuilder
This processor is used for building the basic object function function to maximize for resolving the IPET system, that is, Then, it set the object function as maximizing the following expression: t1 * n1 + t2 * n2 + ...
class CachePenaltiesObjectFunctionBuilder
This processor is used for building the basic object function function in case of a L1 instruction cache.
class ConstraintLoader
This code processor allows loading IPET constraint from an external file.
class FlowFactConstraintBuilder
This processor allows using extern flow facts in an IPET system.
class FlowFactLoader
This processor allows using extern flow facts in an IPET system.
class ILPSystemGetter
This processor looks for an ILP plugin and build a new system that will be used by other IPET processor.
class TrivialBBTime
This processor is used for computing execution of basic blocks in a trivial way, that is, the multiplication of basic block instruction count by the pipeline depth.
class TrivialDataCacheManager
This processor apply a simple method for managing data cache in IPET method.
class TrivialInstCacheManager
This processor is a trivial manager of instruction cache for IPET approach.
class VarAssignment
This processor ensures that each basic block and each edge of the CFG has a variable associated with a ipet::VAR annotation.
class WCETComputation
This class is used for computing the WCET from the system found in the root CFG.
class WCETCountRecorder
This class may be used to record back in the CFG the execution count of each basic block and of each edge for the WCET path.
Functions
Identifier< Constraint * > CALLING_CONSTRAINT ("otawa::ipet::CALLING_CONSTRAINT", 0)
Used to record the constraint of a called CFG.
p::feature CONTROL_CONSTRAINTS_FEATURE ("otawa::ipet::CONTROL_CONSTRAINTS_FEATURE", new Maker< BasicConstraintsBuilder >())
This feature ensures that control constraints has been added to the current ILP system.
SilentFeature OBJECT_FUNCTION_FEATURE ("otawa::ipet::OBJECT_FUNCTION_FEATURE", maker)
This feature ensures that the object function of the ILP system to solve has been built.
p::feature INST_CACHE_SUPPORT_FEATURE ("otawa::ipet::INST_CACHE_SUPPORT_FEATURE", new Maker< TrivialInstCacheManager >)
This feature ensurers that the instruction cache has been modelled in the IPET approach.
p::feature DATA_CACHE_SUPPORT_FEATURE ("otawa::ipet::DATA_CACHE_SUPPORT_FEATURE", new Maker< TrivialDataCacheManager >())
This feature ensures that the first-level data cache has been taken in account in the basic block timing.
p::feature CACHE_SUPPORT_FEATURE ("otawa::ipet::CACHE_SUPPORT_FEATURE", new Maker< CacheSupport >())
This feature ensures that analysis for the cache configuration has been performed.
SilentFeature FLOW_FACTS_CONSTRAINTS_FEATURE ("otawa::ipet::FLOW_FACTS_CONSTRAINTS_FEATURE", maker)
This feature asserts that constraints tied to the flow fact information has been added to the ILP system.
SilentFeature FLOW_FACTS_FEATURE ("otawa::ipet::FLOW_FACTS_FEATURE", maker)
This feature ensures that flow facts information (at less the loop bounds) has been put on the CFG of the current task.
Identifier< string > ILP_PLUGIN_NAME ("otawa::ipet::ILP_PLUGIN_NAME","default")
Select the name of the plugin to use as the ILP solver.
Identifier< ilp::System * > SYSTEM ("otawa::ipet::SYSTEM", 0)
Link the curerently ILP system.
SilentFeature ILP_SYSTEM_FEATURE ("otawa::ipet::ILP_SYSTEM_FEATURE", maker)
This feature assert that an ILP is available for IPET computation.
Identifier< ot::time > TIME ("otawa::ipet::TIME",-1, idLabel("time"), idDesc("execution time (in cycles)"), 0)
This identifier is used for storing the time of execution in cycles (int) of the program area it applies to.
Identifier< ilp::Var * > VAR ("otawa::ipet::VAR", 0, idLabel("variable"), idDesc("variable in ILP system for IPET resolution"), 0)
This identifier is used for storing in basic blocks and edges the variables (otawa::ilp::Var *) used in ILP resolution.
Identifier< ot::time > WCET ("otawa::ipet::WCET",-1, idLabel("WCET"), idDesc("WCET (in cycles)"), 0)
Identifier of annotation used for storing for storing the WCET value (int) in the CFG of the computed function.
Identifier< bool > EXPLICIT ("otawa::ipet::EXPLICIT", false)
Identifier of a boolean property requiring that explicit names must be used.
Identifier< ot::time > TIME_DELTA ("otawa::ipet::TIME_DELTA", 0, idLabel("time delta"), idDesc("time fix for an edge traversal (in cycles)"), 0)
This property is used to store time delta on edges.
Identifier< int > COUNT ("otawa::ipet::COUNT",-1, idLabel("execution count"), idDesc("execution count in WCET"), 0)
This property is put on basic blocks and edge to record the execution count of these object on the WCET path.
ilp::System * getSystem (WorkSpace *fw, CFG *cfg)
Get the system tied with the given CFG.
Feature< NoProcessor > INTERBLOCK_SUPPORT_FEATURE ("otawa::ipet::INTERBLOCK_SUPPORT_FEATURE")
This feature ensures that effects of the inter-block have been modelized in the current ILP system.
Identifier< unsigned > PIPELINE_DEPTH ("otawa::ipet::PIPELINE_DEPTH", 5)
This property is used to configure the TrivialBBTime processor with the depth of the used pipeline.
SilentFeature BB_TIME_FEATURE ("otawa::ipet::BB_TIME_FEATURE", maker)
This feature ensures that the execution time of each basic block has been computed.
Identifier< String * > FORCE_NAME ("otawa::FORCE_NAME", 0)
Force the ilp variable name of an edge or basic block.
SilentFeature ASSIGNED_VARS_FEATURE ("otawa::ipet::ASSIGNED_VARS_FEATURE", maker)
This feature asserts that each block and each edge has a variable name asserted.
SilentFeature WCET_FEATURE ("otawa::ipet::WCET_FEATURE", maker)
This feature ensures that the WCET has been computed using IPET approach.
p::feature WCET_COUNT_RECORDED_FEATURE ("otawa::ipet::WCET_COUNT_RECORDED_FEATURE", new Maker< WCETCountRecorder >())
This feature asserts that WCET execution count of basic block and of edge have been recorded.
Variables
Identifier< bool > EXPLICIT
Identifier of a boolean property requiring that explicit names must be used.
Identifier< string > ILP_PLUGIN_NAME
Select the name of the plugin to use as the ILP solver.
Feature< NoProcessor > INTERBLOCK_SUPPORT_FEATURE
This feature ensures that effects of the inter-block have been modelized in the current ILP system.
SilentFeature BB_TIME_FEATURE
This feature ensures that the execution time of each basic block has been computed.
Identifier< ot::time > TIME
This identifier is used for storing the time of execution in cycles (int) of the program area it applies to.
Identifier< ot::time > TIME_DELTA
This property is used to store time delta on edges.
Identifier< int > COUNT
This property is put on basic blocks and edge to record the execution count of these object on the WCET path.
SilentFeature ASSIGNED_VARS_FEATURE
This feature asserts that each block and each edge has a variable name asserted.
Identifier< ilp::Var * > VAR
This identifier is used for storing in basic blocks and edges the variables (otawa::ilp::Var *) used in ILP resolution.
SilentFeature WCET_FEATURE
This feature ensures that the WCET has been computed using IPET approach.
Identifier< ot::time > WCET
Identifier of annotation used for storing for storing the WCET value (int) in the CFG of the computed function.
SilentFeature OBJECT_FUNCTION_FEATURE
This feature ensures that the object function of the ILP system to solve has been built.
p::feature CONTROL_CONSTRAINTS_FEATURE
This feature ensures that control constraints has been added to the current ILP system.
Identifier< otawa::ilp::Constraint * > CALLING_CONSTRAINT
Used to record the constraint of a called CFG.
SilentFeature FLOW_FACTS_CONSTRAINTS_FEATURE
This feature asserts that constraints tied to the flow fact information has been added to the ILP system.
SilentFeature FLOW_FACTS_FEATURE
This feature ensures that flow facts information (at less the loop bounds) has been put on the CFG of the current task.
SilentFeature ILP_SYSTEM_FEATURE
This feature assert that an ILP is available for IPET computation.
Identifier< ilp::System * > SYSTEM
Link the curerently ILP system.
p::feature DATA_CACHE_SUPPORT_FEATURE
This feature ensures that the first-level data cache has been taken in account in the basic block timing.
p::feature INST_CACHE_SUPPORT_FEATURE
This feature ensurers that the instruction cache has been modelled in the IPET approach.
p::feature CACHE_SUPPORT_FEATURE
This feature ensures that analysis for the cache configuration has been performed.
p::feature WCET_COUNT_RECORDED_FEATURE
This feature asserts that WCET execution count of basic block and of edge have been recorded.
Identifier< unsigned > PIPELINE_DEPTH
This property is used to configure the TrivialBBTime processor with the depth of the used pipeline.
Identifier< String * > FORCE_NAME
Force the ilp variable name of an edge or basic block.
Function Documentation
SilentFeature otawa::ipet::ASSIGNED_VARS_FEATURE ("otawa::ipet::ASSIGNED_VARS_FEATURE" , maker)
This feature asserts that each block and each edge has a variable name asserted.
Properties
ipet::VAR
Referenced by otawa::ipet::VarAssignment::cleanup().
SilentFeature otawa::ipet::BB_TIME_FEATURE ("otawa::ipet::BB_TIME_FEATURE" , maker)
This feature ensures that the execution time of each basic block has been computed.
Properties
otawa::ipet::TIME
otawa::ipet::DELTA_TIME
p::feature otawa::ipet::CACHE_SUPPORT_FEATURE ("otawa::ipet::CACHE_SUPPORT_FEATURE" , new Maker< CacheSupport > ())
This feature ensures that analysis for the cache configuration has been performed.
Identifier<Constraint *> otawa::ipet::CALLING_CONSTRAINT ("otawa::ipet::CALLING_CONSTRAINT" , 0)
Used to record the constraint of a called CFG.
Referenced by otawa::ipet::BasicConstraintsBuilder::addEntryConstraint(), and otawa::ipet::BasicConstraintsBuilder::processWorkSpace().
p::feature otawa::ipet::CONTROL_CONSTRAINTS_FEATURE ("otawa::ipet::CONTROL_CONSTRAINTS_FEATURE" , new Maker< BasicConstraintsBuilder > ())
This feature ensures that control constraints has been added to the current ILP system.
Properties
otawa::ipet::CONTROL_CONSTRAINTS_FEATURE
p::feature otawa::ipet::DATA_CACHE_SUPPORT_FEATURE ("otawa::ipet::DATA_CACHE_SUPPORT_FEATURE" , new Maker< TrivialDataCacheManager > ())
This feature ensures that the first-level data cache has been taken in account in the basic block timing.
SilentFeature otawa::ipet::FLOW_FACTS_CONSTRAINTS_FEATURE ("otawa::ipet::FLOW_FACTS_CONSTRAINTS_FEATURE" , maker)
This feature asserts that constraints tied to the flow fact information has been added to the ILP system.
SilentFeature otawa::ipet::FLOW_FACTS_FEATURE ("otawa::ipet::FLOW_FACTS_FEATURE" , maker)
This feature ensures that flow facts information (at less the loop bounds) has been put on the CFG of the current task.
Properties
ipet::MAX_ITERATION
ipet::MIN_ITERATION
ipet::TOTAL_ITERATION
Identifier<String* > otawa::ipet::FORCE_NAME ("otawa::FORCE_NAME" , 0)
Force the ilp variable name of an edge or basic block.
Referenced by otawa::ipet::VarAssignment::processBB().
ilp::System* otawa::ipet::getSystem (WorkSpace * fw, CFG * cfg)
Get the system tied with the given CFG.
If none exists, create ones.
Parameters
fw Current workspace.
cfg Current CFG. CFG ILP system.
References INTERBLOCK_SUPPORT_FEATURE, and SYSTEM.
Identifier<string> otawa::ipet::ILP_PLUGIN_NAME ("otawa::ipet::ILP_PLUGIN_NAME" , "default")
Select the name of the plugin to use as the ILP solver.
Processor Configuration
ILPSystemGetter
SilentFeature otawa::ipet::ILP_SYSTEM_FEATURE ("otawa::ipet::ILP_SYSTEM_FEATURE" , maker)
This feature assert that an ILP is available for IPET computation.
Properties
SYSTEM
Default Processor
ILPSystemGetter
p::feature otawa::ipet::INST_CACHE_SUPPORT_FEATURE ("otawa::ipet::INST_CACHE_SUPPORT_FEATURE" , new Maker< TrivialInstCacheManager >)
This feature ensurers that the instruction cache has been modelled in the IPET approach.
SilentFeature otawa::ipet::OBJECT_FUNCTION_FEATURE ("otawa::ipet::OBJECT_FUNCTION_FEATURE" , maker)
This feature ensures that the object function of the ILP system to solve has been built.
Identifier<unsigned> otawa::ipet::PIPELINE_DEPTH ("otawa::ipet::PIPELINE_DEPTH" , 5)
This property is used to configure the TrivialBBTime processor with the depth of the used pipeline.
Hooks
Configuration of ipet::TrivialBBTime.
Identifier<ilp::System *> otawa::ipet::SYSTEM ("otawa::ipet::SYSTEM" , 0)
Link the curerently ILP system.
Hooks
WorkSpace
Features
ILP_SYSTEM_FEATURE
p::feature otawa::ipet::WCET_COUNT_RECORDED_FEATURE ("otawa::ipet::WCET_COUNT_RECORDED_FEATURE" , new Maker< WCETCountRecorder > ())
This feature asserts that WCET execution count of basic block and of edge have been recorded.
Properties
ipet::COUNT
SilentFeature otawa::ipet::WCET_FEATURE ("otawa::ipet::WCET_FEATURE" , maker)
This feature ensures that the WCET has been computed using IPET approach.
Properties
otawa::ipet::WCET (FrameWork)
Variable Documentation
SilentFeature otawa::ipet::ASSIGNED_VARS_FEATURE("otawa::ipet::ASSIGNED_VARS_FEATURE", maker)
This feature asserts that each block and each edge has a variable name asserted.
Properties
ipet::VAR
Referenced by otawa::ipet::BasicConstraintsBuilder::BasicConstraintsBuilder(), otawa::EdgeCAT2ConstraintBuilder::EdgeCAT2ConstraintBuilder(), otawa::ipet::FlowFactConstraintBuilder::FlowFactConstraintBuilder(), otawa::LinkedBlocksDetector::LinkedBlocksDetector(), otawa::etime::EdgeTimeBuilder::make(), and otawa::ipet::VarAssignment::makeEdgeVar().
SilentFeature otawa::ipet::BB_TIME_FEATURE("otawa::ipet::BB_TIME_FEATURE", maker)
This feature ensures that the execution time of each basic block has been computed.
Properties
otawa::ipet::TIME
otawa::ipet::DELTA_TIME
Referenced by otawa::ExeGraphBBTime< G >::ExeGraphBBTime(), otawa::ExeGraphBBTime< ParamExeGraph >::ExeGraphBBTime(), otawa::GraphBBTime< G >::GraphBBTime(), otawa::ipet::TrivialBBTime::processBB(), and otawa::ipet::TrivialDataCacheManager::TrivialDataCacheManager().
p::feature otawa::ipet::CACHE_SUPPORT_FEATURE("otawa::ipet::CACHE_SUPPORT_FEATURE", new Maker< CacheSupport >())
This feature ensures that analysis for the cache configuration has been performed.
Referenced by otawa::ipet::TrivialDataCacheManager::processBB().
Identifier<Constraint *> otawa::ipet::CALLING_CONSTRAINT("otawa::ipet::CALLING_CONSTRAINT", 0)
Used to record the constraint of a called CFG.
p::feature otawa::ipet::CONTROL_CONSTRAINTS_FEATURE("otawa::ipet::CONTROL_CONSTRAINTS_FEATURE", new Maker< BasicConstraintsBuilder >())
This feature ensures that control constraints has been added to the current ILP system.
Properties
otawa::ipet::CONTROL_CONSTRAINTS_FEATURE
Referenced by otawa::ipet::BasicConstraintsBuilder::BasicConstraintsBuilder(), and otawa::ipet::BasicConstraintsBuilder::configure().
p::feature otawa::ipet::DATA_CACHE_SUPPORT_FEATURE("otawa::ipet::DATA_CACHE_SUPPORT_FEATURE", new Maker< TrivialDataCacheManager >())
This feature ensures that the first-level data cache has been taken in account in the basic block timing.
Referenced by otawa::ipet::TrivialDataCacheManager::processBB(), and otawa::ipet::TrivialDataCacheManager::TrivialDataCacheManager().
SilentFeature otawa::ipet::FLOW_FACTS_CONSTRAINTS_FEATURE("otawa::ipet::FLOW_FACTS_CONSTRAINTS_FEATURE", maker)
This feature asserts that constraints tied to the flow fact information has been added to the ILP system.
Referenced by otawa::ipet::FlowFactConstraintBuilder::configure(), and otawa::ipet::FlowFactConstraintBuilder::FlowFactConstraintBuilder().
SilentFeature otawa::ipet::FLOW_FACTS_FEATURE("otawa::ipet::FLOW_FACTS_FEATURE", maker)
This feature ensures that flow facts information (at less the loop bounds) has been put on the CFG of the current task.
Properties
ipet::MAX_ITERATION
ipet::MIN_ITERATION
ipet::TOTAL_ITERATION
Referenced by otawa::ipet::FlowFactConstraintBuilder::FlowFactConstraintBuilder(), and otawa::ipet::FlowFactLoader::processBB().
Identifier<String* > otawa::ipet::FORCE_NAME("otawa::FORCE_NAME", 0)
Force the ilp variable name of an edge or basic block.
Identifier<string> otawa::ipet::ILP_PLUGIN_NAME("otawa::ipet::ILP_PLUGIN_NAME","default")
Select the name of the plugin to use as the ILP solver.
Processor Configuration
ILPSystemGetter
Referenced by otawa::ipet::ILPSystemGetter::configure().
SilentFeature otawa::ipet::ILP_SYSTEM_FEATURE("otawa::ipet::ILP_SYSTEM_FEATURE", maker)
This feature assert that an ILP is available for IPET computation.
Properties
SYSTEM
Default Processor
ILPSystemGetter
Referenced by otawa::ipet::BasicConstraintsBuilder::BasicConstraintsBuilder(), otawa::ipet::ILPSystemGetter::configure(), otawa::EdgeCAT2ConstraintBuilder::EdgeCAT2ConstraintBuilder(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::ipet::ILPSystemGetter::ILPSystemGetter(), otawa::LinkedBlocksDetector::LinkedBlocksDetector(), and otawa::etime::EdgeTimeBuilder::make().
p::feature otawa::ipet::INST_CACHE_SUPPORT_FEATURE("otawa::ipet::INST_CACHE_SUPPORT_FEATURE", new Maker< TrivialInstCacheManager >)
This feature ensurers that the instruction cache has been modelled in the IPET approach.
Referenced by otawa::CAT2OnlyConstraintBuilder::collectStats(), otawa::EdgeCAT2ConstraintBuilder::EdgeCAT2ConstraintBuilder(), and otawa::ipet::TrivialInstCacheManager::processBB().
SilentFeature otawa::ipet::OBJECT_FUNCTION_FEATURE("otawa::ipet::OBJECT_FUNCTION_FEATURE", maker)
This feature ensures that the object function of the ILP system to solve has been built.
Referenced by otawa::etime::EdgeTimeBuilder::make(), otawa::ipet::BasicObjectFunctionBuilder::processBB(), and otawa::CAT2OnlyConstraintBuilder::processWorkSpace().
Identifier<unsigned> otawa::ipet::PIPELINE_DEPTH("otawa::ipet::PIPELINE_DEPTH", 5)
This property is used to configure the TrivialBBTime processor with the depth of the used pipeline.
Hooks
Configuration of ipet::TrivialBBTime.
Referenced by otawa::ipet::TrivialBBTime::configure(), and otawa::ipet::TrivialBBTime::processBB().
Identifier<ilp::System *> otawa::ipet::SYSTEM("otawa::ipet::SYSTEM", 0)
Link the curerently ILP system.
Hooks
WorkSpace
Features
ILP_SYSTEM_FEATURE
Referenced by otawa::ipet::ILPSystemGetter::configure(), getSystem(), otawa::etime::StandardEventBuilder::handleVariableBranchPred(), otawa::ipet::CachePenaltiesObjectFunctionBuilder::processBB(), otawa::ipet::BasicObjectFunctionBuilder::processBB(), otawa::tsim::TimeDeltaObjectFunctionModifier::processBB(), otawa::branch::OnlyConsBuilder::processBB(), otawa::ipet::BasicConstraintsBuilder::processBB(), otawa::branch::ConsBuilder::processBB(), otawa::tsim::Delta::processCFG(), otawa::ipet::ConstraintLoader::processCFG(), otawa::cat::CATConstraintBuilder::processLBlockSet(), otawa::ccg::ConstraintBuilder::processLBlockSet(), otawa::EdgeCAT2ConstraintBuilder::processWorkSpace(), otawa::ipet::WCETComputation::processWorkSpace(), otawa::CAT2OnlyConstraintBuilder::processWorkSpace(), otawa::ilp::Output::processWorkSpace(), otawa::dcache::CatConstraintBuilder::processWorkSpace(), otawa::ipet::ILPSystemGetter::processWorkSpace(), otawa::ipet::BasicConstraintsBuilder::processWorkSpace(), otawa::CAT2ConstraintBuilder::processWorkSpace(), otawa::display::ILPSystemDisplayer::processWorkSpace(), otawa::ipet::WCETCountRecorder::setup(), otawa::dcache::WCETFunctionBuilder::setup(), otawa::BBRatioDisplayer::setup(), otawa::ipet::FlowFactConstraintBuilder::setup(), otawa::etime::EdgeTimeBuilder::setup(), and otawa::ipet::VarAssignment::setup().
p::feature otawa::ipet::WCET_COUNT_RECORDED_FEATURE("otawa::ipet::WCET_COUNT_RECORDED_FEATURE", new Maker< WCETCountRecorder >())
This feature asserts that WCET execution count of basic block and of edge have been recorded.
Properties
ipet::COUNT
Referenced by otawa::ipet::WCETCountRecorder::WCETCountRecorder().
SilentFeature otawa::ipet::WCET_FEATURE("otawa::ipet::WCET_FEATURE", maker)
This feature ensures that the WCET has been computed using IPET approach.
Properties
otawa::ipet::WCET (FrameWork)
Referenced by otawa::ipet::WCETComputation::collectStats(), and otawa::ipet::WCETCountRecorder::WCETCountRecorder().