Otawa: otawa::ilp Namespace Reference
otawa::ilp Namespace Reference
Classes
class AbstractConstraint
Constraint generated by AbstractSystem.
class AbstractSystem
This class provides a convenient way to handle ILP systems in OTAWA.
class Alias
An alias is a specific variable that represents an expressions.
class cons
Encapsulation for ilp::Constraint pointers for {ilp} expr user-fiendly interface.
class Constraint
This class is used to represent constraints in an ILP system with the following form:
class ConstraintImpl
Provide a simple implementation of a constraint using expression.
class Expression
An expression allows to represent a sum of terms and may be used to represent the value of an aliased variable.
class ILPPlugin
This interface must be implemented by plugins providing ILP processors.
class model
Encapsulation for ilp::System pointers for {ilp} expr user-fiendly interface.
class Output
This processor provides an output of the built ILP system.
class System
An ILP system is a colletion of ILP constraint that may maximize or minimize some object function.
class Term
class Var
A variable is an identifier used for performing ILP computation.
class var
Encapsulation for ilp::Var pointers for {ilp} expr user-fiendly interface.
class VarImpl
Very trivial implementation of the Var class.
Typedefs
typedef double coef_t
typedef enum otawa::ilp::format_t format_t
Enumerations
enum format_t { DEFAULT = 0, LP_SOLVE = 1, CPLEX = 2, MOSEK = 3 }
Functions
io::Output & operator<< (io::Output &out, Constraint::comparator_t comp)
io::Output & operator<< (io::Output &out, const Term &t)
var x (Var *v)
Convert an ilp::Var * to a var.
Term operator* (coef_t c, var v)
Term operator* (var v, coef_t c)
Expression operator+ (const Term &t1, const Term &t2)
Expression operator- (const Term &t1, const Term &t2)
Expression operator+ (const Expression &e, const Term &t)
Expression operator- (const Expression &e, const Term &t)
io::Output & operator<< (io::Output &out, Var *var)
io::Output & operator<< (io::Output &out, Var &var)
io::Output & operator<< (io::Output &out, Var::type_t type)
SilentFeature OUTPUT_FEATURE ("otawa::ilp::OUTPUT_FEATURE", maker)
This feature ensures that an output of the ILP system has been produced.
Identifier< format_t > OUTPUT_FORMAT ("otawa::ilp::OUTPUT_FORMAT", LP_SOLVE)
Select the output format to build the OUTPUT_FEATURE.
Identifier< sys::Path > OUTPUT_PATH ("otawa::ilp::OUTPUT_PATH","")
Select the file to perform the output during build of OUTPUT_FEATURE.
Identifier< elm::io::OutStream * > OUTPUT ("otawa::ilp::OUTPUT", 0)
Select the output stream to perform the output to to build a OUTPUT_FEATURE.
io::Output & operator<< (io::Output &out, const CID &id)
Variables
SilentFeature OUTPUT_FEATURE
This feature ensures that an output of the ILP system has been produced.
Identifier< format_t > OUTPUT_FORMAT
Select the output format to build the OUTPUT_FEATURE.
Identifier< sys::Path > OUTPUT_PATH
Select the file to perform the output during build of OUTPUT_FEATURE.
Identifier< elm::io::OutStream * > OUTPUT
Select the output stream to perform the output to to build a OUTPUT_FEATURE.
Typedef Documentation
typedef double otawa::ilp::coef_t
typedef enum otawa::ilp::format_t otawa::ilp::format_t
Enumeration Type Documentation
enum otawa::ilp::format_t
Enumerator
DEFAULT
LP_SOLVE
CPLEX
MOSEK
Function Documentation
Term otawa::ilp::operator* (coef_t c, var v) inline
Term otawa::ilp::operator* (var v, coef_t c) inline
Expression otawa::ilp::operator+ (const Term & t1, const Term & t2) inline
References otawa::ilp::Expression::add().
Referenced by otawa::clp::Value::operator!=().
Expression otawa::ilp::operator+ (const Expression & e, const Term & t) inline
References otawa::ilp::Expression::add().
Expression otawa::ilp::operator- (const Term & t1, const Term & t2) inline
References otawa::ilp::Expression::add(), and otawa::ilp::Expression::sub().
Referenced by otawa::clp::Value::operator!=().
Expression otawa::ilp::operator- (const Expression & e, const Term & t) inline
References otawa::ilp::Expression::sub().
io::Output& otawa::ilp::operator<< (io::Output & out, Var * var) inline
References otawa::ilp::Var::print().
io::Output & otawa::ilp::operator<< (io::Output & out, Constraint::comparator_t comp)
References otawa::ilp::Constraint::GT, and otawa::ilp::Constraint::LT.
Referenced by operator<<(), otawa::dcache::operator<<(), and otawa::ilp::Constraint::TermIterator::TermIterator().
io::Output& otawa::ilp::operator<< (io::Output & out, Var & var) inline
References operator<<(), otawa::ilp::Var::print(), and otawa::type().
io::Output & otawa::ilp::operator<< (io::Output & out, const Term & t)
References otawa::ilp::Term::fst, otawa::ilp::Var::name(), and otawa::ilp::Term::snd.
io::Output & otawa::ilp::operator<< (io::Output & out, Var::type_t type)
References otawa::ilp::Var::FLOAT, and otawa::ilp::Var::type().
io::Output& otawa::ilp::operator<< (io::Output & out, const CID & id)
References otawa::ilp::Term::fst, and otawa::ilp::Term::snd.
Identifier<elm::io::OutStream *> otawa::ilp::OUTPUT ("otawa::ilp::OUTPUT" , 0)
Select the output stream to perform the output to to build a OUTPUT_FEATURE.
SilentFeature otawa::ilp::OUTPUT_FEATURE ("otawa::ilp::OUTPUT_FEATURE" , maker)
This feature ensures that an output of the ILP system has been produced.
Default processor
otawa::ilp::Output
Configuration
OUTPUT_FORMAT
OUTPUT_PATH
OUTPUT
Identifier<format_t> otawa::ilp::OUTPUT_FORMAT ("otawa::ilp::OUTPUT_FORMAT" , LP_SOLVE)
Select the output format to build the OUTPUT_FEATURE.
Accepted values includes ilp::LP_SOLVE (1), ilp::CPLEX (2) or (3).
Identifier<sys::Path> otawa::ilp::OUTPUT_PATH ("otawa::ilp::OUTPUT_PATH" , "")
Select the file to perform the output during build of OUTPUT_FEATURE.
Variable Documentation
Identifier<elm::io::OutStream *> otawa::ilp::OUTPUT("otawa::ilp::OUTPUT", 0)
Select the output stream to perform the output to to build a OUTPUT_FEATURE.
Referenced by otawa::ilp::Output::configure().
SilentFeature otawa::ilp::OUTPUT_FEATURE("otawa::ilp::OUTPUT_FEATURE", maker)
This feature ensures that an output of the ILP system has been produced.
Default processor
otawa::ilp::Output
Configuration
OUTPUT_FORMAT
OUTPUT_PATH
OUTPUT
Identifier<format_t> otawa::ilp::OUTPUT_FORMAT("otawa::ilp::OUTPUT_FORMAT", LP_SOLVE)
Select the output format to build the OUTPUT_FEATURE.
Accepted values includes ilp::LP_SOLVE (1), ilp::CPLEX (2) or (3).
Referenced by otawa::ilp::Output::configure().
Identifier<sys::Path> otawa::ilp::OUTPUT_PATH("otawa::ilp::OUTPUT_PATH","")
Select the file to perform the output during build of OUTPUT_FEATURE.
Referenced by otawa::ilp::Output::configure().