Otawa: otawa::stack Namespace Reference
otawa::stack Namespace Reference
Classes
class Iter
Iterator on the result of stack analysis.
class Manager
Manager for results of stack analysis.
class Value
Values in the StackAnalysis.
Enumerations
enum kind_t {
NONE, REG, SP, CST,
ALL
}
Functions
io::Output & operator<< (io::Output &out, const Value &v)
io::Output & operator<< (io::Output &out, const State &state)
p::feature ADDRESS_FEATURE ("otawa::stack::ADDRESS_FEATURE", new Maker< AddressBuilder >())
Feature ensuring that addresses are built from stack analysis.
Identifier< Manager * > MANAGER ("otawa::stack::Manager", 0)
Property providing analysis manager to use result of stack analysis.
Variables
p::feature ADDRESS_FEATURE
Feature ensuring that addresses are built from stack analysis.
Identifier< Manager * > MANAGER
Property providing analysis manager to use result of stack analysis.
Identifier< State * > STATE ("otawa::stack::STATE", 0)
Stack analysis state at entry of BBs.
Enumeration Type Documentation
enum otawa::stack::kind_t
Enumerator
NONE
REG
SP
CST
ALL
Function Documentation
p::feature otawa::stack::ADDRESS_FEATURE ("otawa::stack::ADDRESS_FEATURE" , new Maker< AddressBuilder > ())
Feature ensuring that addresses are built from stack analysis.
This features must always induce ADDRESS_ANALYSIS_FEATURE to be also provided.
io::Output& otawa::stack::operator<< (io::Output & out, const Value & v) inline
References otawa::stack::Value::print().
io::Output & otawa::stack::operator<< (io::Output & out, const State & state)
References otawa::stack::Value::_and(), otawa::stack::Value::_not(), otawa::stack::Value::_or(), otawa::stack::Value::_xor(), otawa::sem::inst::a, otawa::se::ADD, otawa::stack::Value::add(), otawa::ProgItem::address(), otawa::ot::address(), otawa::sem::AND, otawa::sem::ASR, otawa::stack::Value::asr(), otawa::sem::inst::b, otawa::cfgio::bb(), otawa::etime::BRANCH, otawa::se::CMP, otawa::se::CMPU, otawa::se::CONST, otawa::sem::CONT, CST, otawa::sem::inst::cst, otawa::sem::inst::d(), otawa::DIV, otawa::stack::Value::div(), otawa::sem::DIVU, otawa::stack::Value::divu(), otawa::Inst::dump(), otawa::cfgio::entry(), otawa::sem::IF, otawa::dfa::INITIAL_STATE, otawa::stack::Value::isConst(), otawa::Address::isNull(), otawa::sem::LOAD, otawa::sem::load(), otawa::sem::MOD, otawa::stack::Value::mod(), otawa::sem::MODU, otawa::stack::Value::modu(), otawa::MUL, otawa::stack::Value::mul(), otawa::sem::MULH, otawa::stack::Value::mulh(), otawa::sem::MULU, otawa::se::NEG, otawa::stack::Value::neg(), otawa::sem::NOP, otawa::sem::NOT, otawa::BasicBlock::number(), otawa::Address::offset(), otawa::sem::inst::op, otawa::se::OR, otawa::hard::Register::platformNumber(), proc(), otawa::WorkSpace::process(), otawa::clp::REG, otawa::sem::SCRATCH, otawa::Inst::semInsts(), otawa::sem::SET, otawa::stack::Value::set(), otawa::sem::SETI, otawa::sem::SETP, otawa::sem::SHL, otawa::stack::Value::shl(), otawa::sem::SHR, otawa::stack::Value::shr(), SP, otawa::sem::PathIter::start(), otawa::sem::STORE, otawa::sem::SUB, otawa::stack::Value::sub(), TRACED, TRACEI, TRACES, TRACEU, otawa::sem::TRAP, otawa::stack::Value::value(), and otawa::sem::XOR.
Variable Documentation
p::feature otawa::stack::ADDRESS_FEATURE("otawa::stack::ADDRESS_FEATURE", new Maker< AddressBuilder >())
Feature ensuring that addresses are built from stack analysis.
This features must always induce ADDRESS_ANALYSIS_FEATURE to be also provided.
Referenced by otawa::stack::Manager::updatePath().
Identifier<State *> otawa::stack::STATE("otawa::stack::STATE", 0)
Stack analysis state at entry of BBs.
Hooks
BasicBlock
Feature
otawa::STACK_ANALYSIS_FEATURE
Referenced by otawa::StackAnalysis::processWorkSpace(), and otawa::stack::Manager::state().