Otawa: otawa::dcache::DirtyManager::t Struct Reference
otawa::dcache::DirtyManager::t Struct Reference
#include <otawa/dcache/features.h>
Public Member Functions
t (void)
t (int s)
t (const t &i)
const dfa::BitSet & may (void) const
const dfa::BitSet & must (void) const
void print (io::Output &out) const
bool mayBeDirty (int b) const
bool mustBeDirty (int b) const
Private Member Functions
dfa::BitSet & may (void)
dfa::BitSet & must (void)
Private Attributes
dfa::BitSet _may
dfa::BitSet _must
Friends
class DirtyManager
Constructor & Destructor Documentation
otawa::dcache::DirtyManager::t::t (void) inline
otawa::dcache::DirtyManager::t::t (int s) inline
otawa::dcache::DirtyManager::t::t (const t & i) inline
Member Function Documentation
const dfa::BitSet& otawa::dcache::DirtyManager::t::may (void) const inline
Referenced by otawa::dcache::DirtyManager::DirtyManager(), otawa::dcache::DirtyManager::equals(), otawa::dcache::DirtyManager::join(), otawa::dcache::DirtyManager::mayBeDirty(), otawa::dcache::DirtyManager::set(), and otawa::dcache::DirtyManager::update().
dfa::BitSet& otawa::dcache::DirtyManager::t::may (void) inline private
bool otawa::dcache::DirtyManager::t::mayBeDirty (int b) const inline
const dfa::BitSet& otawa::dcache::DirtyManager::t::must (void) const inline
References otawa::p::print().
Referenced by otawa::dcache::DirtyManager::DirtyManager(), otawa::dcache::DirtyManager::equals(), otawa::dcache::DirtyManager::join(), otawa::dcache::DirtyManager::mustBeDirty(), otawa::dcache::DirtyManager::set(), and otawa::dcache::DirtyManager::update().
dfa::BitSet& otawa::dcache::DirtyManager::t::must (void) inline private
bool otawa::dcache::DirtyManager::t::mustBeDirty (int b) const inline
void otawa::dcache::DirtyManager::t::print (io::Output & out) const
References otawa::cfgio::bb(), otawa::dcache::DirtyManager::bottom(), cache(), otawa::hard::CACHE_CONFIGURATION, otawa::hard::CACHE_CONFIGURATION_FEATURE, otawa::dcache::BlockCollection::cacheSet(), otawa::cfgio::cfg(), otawa::COLLECTED_CFG_FEATURE, otawa::dcache::DATA_BLOCK_COLLECTION, otawa::dcache::DATA_BLOCK_FEATURE, otawa::dcache::DATA_BLOCKS, otawa::hard::CacheConfiguration::dataCache(), otawa::dcache::DIRTY, otawa::dcache::DIRTY_FEATURE, otawa::cfgio::entry(), otawa::dcache::DirtyManager::equals(), otawa::INVOLVED_CFGS, otawa::p::init::maker(), otawa::p::init::provide(), otawa::p::init::require(), otawa::dfa::hai::DefaultListener< P >::results, otawa::hard::Cache::rowCount(), otawa::dfa::hai::HalfAbsInt< FixPoint >::solve(), and otawa::dcache::DirtyManager::update().
Referenced by otawa::dcache::operator<<().
Friends And Related Function Documentation
friend class DirtyManager friend
Member Data Documentation
dfa::BitSet otawa::dcache::DirtyManager::t::_may private
dfa::BitSet otawa::dcache::DirtyManager::t::_must private
The documentation for this struct was generated from the following files:
include/otawa/dcache/features.h
src/dcache/Dirty.cpp