Otawa: otawa::sem::inst Class Reference
otawa::sem::inst Class Reference
Semantic Instructions
This structure class represents an instruction in the semantics representation of machine instruction.
#include <otawa/sem/inst.h>
Public Member Functions
inst (void)
inst (opcode _op)
inst (opcode _op, int d)
inst (opcode _op, int d, int a)
inst (opcode _op, int d, int a, int b)
reg_t d (void) const
reg_t a (void) const
reg_t b (void) const
uint_t cst (void) const
reg_t reg (void) const
reg_t addr (void) const
type_t type (void) const
cond_t cond (void) const
reg_t sr (void) const
uint_t jump (void) const
void print (elm::io::Output &out) const
Output the current instruction to the given output.
Public Attributes
t::uint16 op
t::int16 _d
union {
t::uint32 cst
struct {
t::int16 a
t::int16 b
} regs
} args
Detailed Description
This structure class represents an instruction in the semantics representation of machine instruction.
It contains an opcode, giving the performed operation, and arguments depending on this opcode.
The variable is ever used to store the result of an instruction. A variable may match a register (index is positive and matches the register unique number in otawa::hard::Platform description) or a temporary (index is strictly negative).
LOAD, STORE access memory data and uses variable a to get the address and b is an immediate value given the size of the accessed data item.
SCRATCH means that the register is replaced with meaningless value.
SET and SETI assigns to d the variable in b or the immediate value in cst.
CMP, ADD, SUB, SHL, SHR and ASR uses both variable a and b to perform, respectively, comparison, addition, subtraction, logical shift left, logical shift right, arithmetics shift right.
Constructor & Destructor Documentation
otawa::sem::inst::inst (void) inline
Referenced by otawa::ParamExeGraph::analyzeContentions(), otawa::GraphBBTime< G >::analyzePathContext(), otawa::LiExeGraphBBTime::buildEpilogueList(), otawa::GraphBBTime< G >::buildFMTimingContextListForICache(), otawa::GraphBBTime< G >::buildNCTimingContextListForICache(), otawa::ParamExeGraphBBTime::buildPrologueList(), otawa::LiExeGraphBBTime::buildPrologueList(), otawa::GraphBBTime< G >::computeDefaultTimingContextForICache(), otawa::ParExeGraph::createSequenceResources(), otawa::ParamExeGraph::dump(), otawa::ParExeGraph::dump(), otawa::ParamExeGraph::dumpSimple(), otawa::LiExeGraph::nodeEarliestTimes(), otawa::LiExeGraph::nodeLatestTimes(), otawa::ParamExeGraph::ParamExeGraph(), and otawa::ParamExeGraphBBTime::processBB().
otawa::sem::inst::inst (opcode _op) inline
otawa::sem::inst::inst (opcode _op, int d) inline
otawa::sem::inst::inst (opcode _op, int d, int a) inline
otawa::sem::inst::inst (opcode _op, int d, int a, int b) inline
Member Function Documentation
reg_t otawa::sem::inst::a (void) const inline
reg_t otawa::sem::inst::addr (void) const inline
Referenced by otawa::sem::PathIter::addr(), and otawa::dcache::CLPBlockBuilder::processBB().
reg_t otawa::sem::inst::b (void) const inline
cond_t otawa::sem::inst::cond (void) const inline
Referenced by otawa::se::FilterBuilder::makeFilters(), otawa::clp::operator<<(), and otawa::sem::Printer::print().
uint_t otawa::sem::inst::cst (void) const inline
reg_t otawa::sem::inst::d (void) const inline
Referenced by otawa::ParamExeGraph::analyzeContentions(), otawa::sem::PathIter::d(), otawa::se::FilterBuilder::makeFilters(), otawa::stack::operator<<(), otawa::clp::operator<<(), and otawa::sem::Printer::print().
uint_t otawa::sem::inst::jump (void) const inline
Referenced by otawa::clp::operator<<(), and otawa::sem::Printer::print().
void otawa::sem::inst::print (elm::io::Output & out) const
Output the current instruction to the given output.
Parameters
out Output to print to.
References otawa::sem::Printer::print().
Referenced by otawa::sem::operator<<().
reg_t otawa::sem::inst::reg (void) const inline
Referenced by otawa::sem::PathIter::reg().
reg_t otawa::sem::inst::sr (void) const inline
Referenced by otawa::clp::operator<<(), and otawa::sem::Printer::print().
type_t otawa::sem::inst::type (void) const inline
Referenced by otawa::clp::operator<<(), and otawa::sem::Printer::print().
Member Data Documentation
t::int16 otawa::sem::inst::_d
t::int16 otawa::sem::inst::a
Referenced by otawa::sem::PathIter::a(), otawa::se::FilterBuilder::makeFilters(), otawa::stack::operator<<(), otawa::clp::operator<<(), and otawa::sem::Printer::print().
union { ... } otawa::sem::inst::args
Referenced by otawa::sem::seti(), otawa::sem::setp(), and otawa::sem::spec().
t::int16 otawa::sem::inst::b
Referenced by otawa::sem::PathIter::b(), otawa::se::FilterBuilder::makeFilters(), otawa::stack::operator<<(), otawa::clp::operator<<(), and otawa::sem::Printer::print().
t::uint32 otawa::sem::inst::cst
Referenced by otawa::sem::PathIter::cst(), otawa::stack::operator<<(), otawa::clp::operator<<(), otawa::sem::Printer::print(), otawa::sem::seti(), otawa::sem::setp(), and otawa::sem::spec().
t::uint16 otawa::sem::inst::op
Referenced by otawa::se::FilterBuilder::makeFilters(), otawa::stack::operator<<(), otawa::clp::operator<<(), otawa::sem::Printer::print(), and otawa::dcache::CLPBlockBuilder::processBB().
struct { ... } otawa::sem::inst::regs
The documentation for this class was generated from the following files:
include/otawa/sem/inst.h
src/prog/sem.cpp