var annotated_dup =
[
    [ "arch_plugin_s", "structarch__plugin__s.html", "structarch__plugin__s" ],
    [ "auxv_t", "structauxv__t.html", "structauxv__t" ],
    [ "Elf32_Dyn", "structElf32__Dyn.html", "structElf32__Dyn" ],
    [ "Elf32_Ehdr", "structElf32__Ehdr.html", "structElf32__Ehdr" ],
    [ "Elf32_Phdr", "structElf32__Phdr.html", "structElf32__Phdr" ],
    [ "Elf32_Rel", "structElf32__Rel.html", "structElf32__Rel" ],
    [ "Elf32_Rela", "structElf32__Rela.html", "structElf32__Rela" ],
    [ "Elf32_Shdr", "structElf32__Shdr.html", "structElf32__Shdr" ],
    [ "Elf32_Sym", "structElf32__Sym.html", "structElf32__Sym" ],
    [ "gel_addr_iter_t", "structgel__addr__iter__t.html", "structgel__addr__iter__t" ],
    [ "gel_block_info_t", "structgel__block__info__t.html", "structgel__block__info__t" ],
    [ "gel_block_s", "structgel__block__s.html", "structgel__block__s" ],
    [ "gel_cursor_s", "structgel__cursor__s.html", "structgel__cursor__s" ],
    [ "gel_env_s", "structgel__env__s.html", "structgel__env__s" ],
    [ "gel_file_info_t", "structgel__file__info__t.html", "structgel__file__info__t" ],
    [ "gel_hash_enum_t", "structgel__hash__enum__t.html", "structgel__hash__enum__t" ],
    [ "gel_image_info_t", "structgel__image__info__t.html", "structgel__image__info__t" ],
    [ "gel_line_iter_t", "structgel__line__iter__t.html", "structgel__line__iter__t" ],
    [ "gel_line_map_t", "structgel__line__map__t.html", "structgel__line__map__t" ],
    [ "gel_location_t", "structgel__location__t.html", "structgel__location__t" ],
    [ "gel_memory_cluster_info_t", "structgel__memory__cluster__info__t.html", "structgel__memory__cluster__info__t" ],
    [ "gel_memory_image_info_t", "structgel__memory__image__info__t.html", "structgel__memory__image__info__t" ],
    [ "gel_note_t", "structgel__note__t.html", "structgel__note__t" ],
    [ "gel_platform_s", "structgel__platform__s.html", "structgel__platform__s" ],
    [ "gel_prog_info_t", "structgel__prog__info__t.html", "structgel__prog__info__t" ],
    [ "gel_sect_info_t", "structgel__sect__info__t.html", "structgel__sect__info__t" ],
    [ "gel_sym_info_t", "structgel__sym__info__t.html", "structgel__sym__info__t" ],
    [ "gel_unit_iter_t", "structgel__unit__iter__t.html", "structgel__unit__iter__t" ],
    [ "item", "structitem.html", "structitem" ],
    [ "segment_t", "structsegment__t.html", "structsegment__t" ],
    [ "stab_t", "structstab__t.html", "structstab__t" ],
    [ "sys_plugin_s", "structsys__plugin__s.html", "structsys__plugin__s" ],
    [ "unit_line_t", "structunit__line__t.html", "structunit__line__t" ],
    [ "unit_t", "structunit__t.html", "structunit__t" ]
];